### PR TITLE
Fixes #631 Scroll & constraint issues in BrowserViewController

### LINKED ISSUE #631: Issues while scrolling websites with sticky header/footer
### Description: 
App becomes unresponsive (loss of FPS maybe), while scrolling (jumps instead of scroll) in websites with sticky footer/Header.
Example: m.indiatimes.com (iPhone, footer) & m.youtube.com (iPad, header)

In certain cases the sticky header/footer may also get clipped by browser container. 
Example: m.youtube.com (iPad, header)

### Steps to Reproduce 
  1. Open either of the two websites above.
  2. Scroll slowly as to hide the top/bottom bars

**Actual result:** 
Loss of responsiveness/ fps and sometimes clipping of sticky header/footer in websites.

**Expected result:**
No Scroll Issues 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by danishjafri88**
This is a regression PR for [#631](https://github.com/brave/brave-ios/issues/631). Previous PR was reverted because of regression bug relating to constraints not properly set when bottom Toolbar is not visible.

Apart for the above regression fix, following are fixed:
->Youtube header problem
->Redundant Pan Gesture creation
->Mis-aligned constraints relations in BrowserViewController
->Refactored Show/Hide Tab Animation properly
-> Enable Zoom by ignoring viewport scale limit.
-> Removed a part of animation code(Hotfix for older logic) which became source of a jump issue during scroll.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/TabScrollController.swift [hunk 1]
```diff
@@ -251,20 +244,25 @@ private extension TabScrollingController {
     }
 
     func animateToolbarsWithOffsets(_ animated: Bool, duration: TimeInterval, headerOffset: CGFloat, footerOffset: CGFloat, alpha: CGFloat, completion: ((_ finished: Bool) -> Void)?) {
+        //NOTE: The issue below (& its fix) is irrelevant now since the the scroll logic is updated, infact the logic further
```
Comment (jhreis) [inline Client/Frontend/Browser/TabScrollController.swift]: Just delete all of this, no reason to keep old code laying around.

**Review by jhreis — CHANGES_REQUESTED** [review]
This feels much better to me, really solid improvements IMO, hopefully others will agree! Just one block of code/comments to remove.

**Review by jhreis — APPROVED** [review]
