### PR TITLE
Fix #974, fix #942 : add ability to call browserified script, fix qr code/codewords bug

### LINKED ISSUE #942: Ensure sync code words/qr code doesn't get stuck while generating
### Description: 
Some times sync code words/qr code may take time to generate causing the sync screen to be blank

### Steps to Reproduce 
  1. Enable sync
  2. Create a new sync chain
  3. Code word/QR code sometime doesn't show up

**Actual result:** 
file

**Expected result:**
Should always generate code words/qr code

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent. Ran into this only twice but cant consistently reproduce

**Brave Version:** 
1.9(19.3.2.15)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #974: Add ability to call browserified code.
We use few shared libraries based on javascript such as `brave-sync`, `brave-crypto`. 
Apple's `JavascriptCore` framework doesn't make it easy to call browserified code.

One approach is to wrap browserified code in a global `window` object which then can be called using JavascriptCore

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: BraveShared/Javascript/BrowserifiedJS.swift [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+/// A wrapper around `JSContext` to help with browserified code.
+public class BrowserifiedJS {
+    public let context: JSContext
+    
+    public init?(browserifiedScript script: BundledBrowserifiedScript?) {
+        context = JSContext()
+        
+        guard let script = script, let scriptString = script.get else { return nil }
+        let src = "var window = this; \(scriptString)"
```
Comment (jhreis) [inline BraveShared/Javascript/BrowserifiedJS.swift:19]: Why do we need to set window here? Assuming it is due to the API that sync interacts with, but should add a why comment here.

File: BraveShared/Javascript/BrowserifiedJS.swift [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+        context.evaluateScript(src)
+        
+        script.addExposedFunctions(to: context)
+    }
+    
+    public func callFunction(withName functionName: String, arguments: [Any]) throws -> JSValue {
```
Comment (jhreis) [inline BraveShared/Javascript/BrowserifiedJS.swift]: I think this is a bit cleaner:
```suggestion
    public func call(functionName function: String, arguments: [Any]) throws -> JSValue {
```

File: BraveShared/Javascript/BundledJSProtocol.swift [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+    var name: String { get }
+    /// Bundle where the javascript file is located.
+    var bundle: Bundle { get }
+    /// Gets a bundled javascript file and returns it as a String.
+    var get: String? { get }
+}
+
+public extension BundledJSProtocol {
+    var get: String? {
+        guard let filePath = bundle.path(forResource: name, ofType: "js") else {
```
Comment (jhreis) [inline BraveShared/Javascript/BundledJSProtocol.swift]: Could place this inside the `do-catch` below and instead of logging an error and returning could simply throw an exception and allow the `catch` below to deal with it?

File: Client/Frontend/Sync/SyncAddDeviceViewController.swift [hunk 4]
```diff
@@ -98,38 +98,49 @@ class SyncAddDeviceViewController: SyncViewController {
...
+            self.codewordsView.text = passphrase.joined(separator: " ")
+        case .failure:
+            showInitializationError()
+            return
         }
         
         self.setupVisuals()
     }
     
+    private func showInitializationError() {
```
Comment (jhreis) [inline Client/Frontend/Sync/SyncAddDeviceViewController.swift:134]: This looks mostly copied from the welcome screen, correct? If so we need to abstract this somewhere too.

File: Data/sync/BraveCryptoJSFunctions.swift [hunk 5]
```diff
@@ -0,0 +1,41 @@
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+import BraveShared
+
+struct BraveCryptoJSFunctions: BrowserifyExposable, BundledJSProtocol {
```
Comment (jhreis) [inline Data/sync/BraveCryptoJSFunctions.swift]: Wondering if this should just be named `BraveCryptoJS` and rename the `Names` struct to simply `Functions`? 

At the very least I don't think this should be plural, right?

File: Data/sync/BraveCryptoJSFunctions.swift [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+        
+        exposedFunctions = [ExposedJSFunction(name: Names.fromBytesOrHex, body: Bodies.fromBytesOrHex),
+                            ExposedJSFunction(name: Names.toBytes32, body: Bodies.toBytes32)]
+    }
+    
+    private struct Bodies {
+        static let fromBytesOrHex =
+        """
+        function(bytes){
+           return module.exports.passphrase.fromBytesOrHex(bytes);
```
Comment (jhreis) [inline Data/sync/BraveCryptoJSFunctions.swift]: I think we should use the `Names.rawValue` for the function calling here:

```suggestion
           return module.exports.passphrase.\(Names.fromBytesOrHex)(bytes);
```

File: Data/sync/BraveCryptoJSFunctions.swift [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+    
+    init?() {
+        name = "crypto"
+        bundle = Bundle.data
+        
+        exposedFunctions = [ExposedJSFunction(name: Names.fromBytesOrHex, body: Bodies.fromBytesOrHex),
+                            ExposedJSFunction(name: Names.toBytes32, body: Bodies.toBytes32)]
+    }
+    
+    private struct Bodies {
```
Comment (jhreis) [inline Data/sync/BraveCryptoJSFunctions.swift]: I think we can delete this and include it inside of the current `Names` struct (potentially renamed to `functions`. Then it calling would look like:

`BraveCryptoJS.Functions.fromBytesOrHex.body`

File: Data/sync/BraveCryptoJSFunctions.swift [hunk 8]
```diff
@@ -0,0 +1,41 @@
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
```
Comment (jhreis) [inline Data/sync/BraveCryptoJSFunctions.swift]: I have a few comments on this class that may be super off, so if you feeling I'm missing the larger architecture stuff here, then let's chat more about it.

**Review by jhreis — CHANGES_REQUESTED** [review]
Super great work, comments are pretty minor. Really love this refactor!

File: BraveShared/Javascript/BrowserifiedJS.swift (hunk 1 above)
Comment (iccub) [reply BraveShared/Javascript/BrowserifiedJS.swift:19]: Browserify doesn't work otherwise, I will add a comment

File: BraveShared/Javascript/JSError.swift [hunk 9]
```diff
@@ -0,0 +1,19 @@
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+import JavaScriptCore
+
+public struct JSError: Error, CustomStringConvertible {
```
Comment (danishjafri88) [inline BraveShared/Javascript/JSError.swift]: Since Error is a protocol you can use it with String Extension as: `extension String: Error {}` this line makes any String conform to Error. You can simply pass a String and need not create a struct with it.

File: Data/sync/BraveCryptoJSFunctions.swift (hunk 6 above)
Comment (iccub) [reply Data/sync/BraveCryptoJSFunctions.swift]: This function still should be copied 1:1 from javascript file.
For me it's easier if you can simply copy paste it into the string,.
I will change it to your suggestion

File: Data/sync/BraveCryptoJSFunctions.swift (hunk 8 above)
Comment (iccub) [reply Data/sync/BraveCryptoJSFunctions.swift]: The only problem there is having to manually copy and paste function declaration from javascript. No easy way around that, most we can do is to try to write at least one(happy path) unit test for each browserified script, so we are sure the function gets called

File: BraveShared/Javascript/BrowserifiedJS.swift (hunk 1 above)
Comment (jhreis) [reply BraveShared/Javascript/BrowserifiedJS.swift:19]: Oh, sorry, I read this wrong for some reason. I tought you were assigning `this` to `window` (e.g. `var this = window`), not sure how I misread that. thx regardless.

File: Data/sync/BraveCryptoJS.swift [hunk 10]
```diff
@@ -0,0 +1,47 @@
...
+
+import Foundation
+import BraveShared
+
+struct BraveCryptoJS: BrowserifyExposable, BundledJSProtocol {
+    let bundle: Bundle
+    let name: String
+    let exposedFunctions: [ExposedJSFunction]
+    
+    struct Functions {
```
Comment (jhreis) [inline Data/sync/BraveCryptoJS.swift]: wdyt of this for the struct?

```
struct BraveCryptoJS: BrowserifyExposable, BundledJSProtocol {
    let bundle = Bundle.data
    let name = "crypto"
    let exposedFunctions = Function.exposedFunctions
    
    enum Function: String {
        case fromBytesOrHex = "fromBytesOrHex"
        case toBytes32 = "toBytes32"
        
        var body: String {
            return """
            function(parameters){
            return module.exports.passphrase.\(self.rawValue)(parameters);
            };
            """
        }
        
        /// Creates new instance on access, thus private
        private var exposedFunction: ExposedJSFunction {
            return ExposedJSFunction(name: self.rawValue, body: self.body)
        }
        
        static var exposedFunctions: [ExposedJSFunction] {
            return [self.fromBytesOrHex.exposedFunction, self.toBytes32.exposedFunction]
        }
    }
}
```

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Sync/SyncAddDeviceViewController.swift (hunk 4 above)
Comment (iccub) [reply Client/Frontend/Sync/SyncAddDeviceViewController.swift:134]: I will add it here https://github.com/brave/brave-ios/pull/991, there's a new structure that groups Sync related alerts. Please merge this PR first :)

File: fastlane/Fastfile [hunk 11]
```diff
@@ -37,7 +37,16 @@ platform :ios do
       device: "iPhone 8",
       code_coverage: true,
       skip_testing: [
-        "DataTests",
```
Comment (iccub) [inline fastlane/Fastfile:40]: All Core Data tests fail occasionally, disabling them all to run `SyncCryptoTests` from `Data` framework

**Review by jhreis — APPROVED** [review]
Great, great PR, very nice cleanup.
