### PR TITLE
Fix #3899: Updated default browser notification to display iOS version

### LINKED ISSUE #3899: Update default browser notification to display device's iOS version
### Description: 
This notification should show user's device version instead of hardcoding `iOS 14`
On code side this requires change in NSLocalized string, the number has to be replaced with a number placeholder.
Then in app we have to fetch device's iOS version, with iOS 14 minimum, since iOS 13 can't be set as a default

File

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by singhbaidwan**
## Summary of Changes

This pull request fixes #3899 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Verify that the default browser notification shows correct iOS version. This is the best tested on iOS 15, but 14 should work too

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -157,7 +157,7 @@ extension Strings {
         public static let notificationBody =
             NSLocalizedString("defaultBrowserCallout.notificationBody",
                               tableName: "BraveShared", bundle: .braveShared,
-                              value: "Optimized for iOS 14. Make Brave your default browser today.",
+                              value: "Optimized for iOS \(floor(Double(UIDevice.current.systemVersion) ?? 13)). Make Brave your default browser today.",
```
Comment (iccub) [inline BraveShared/BraveStrings.swift]: It can't be done here because these translations are exported to a translation service,
here you have to use `%@` character for iOS version placeholder,

then in code you get this string like `String(format: notificationBody, your_number_logic)`

You can search for `findInPageFormat` in our code to see how other string with a placeholder is set up

**Review by iccub — CHANGES_REQUESTED** [review]

File: BraveShared/de.lproj/BraveShared.strings [hunk 2]
```diff
@@ -332,7 +332,7 @@
 "defaultBrowserCallout.introTertiaryText" = "Öffnen Sie die Einstellungen, tippen Sie auf „Standardbrowser“ und wählen Sie Brave aus.";
 
 /* Notification body to promote setting Brave app as default browser */
-"defaultBrowserCallout.notificationBody" = "Optimiert für iOS 14. Legen Sie Brave gleich als Ihren Standardbrowser fest.";
+"defaultBrowserCallout.notificationBody" = "Optimiert für iOS %@. Legen Sie Brave gleich als Ihren Standardbrowser fest.";
```
Comment (iccub) [inline BraveShared/de.lproj/BraveShared.strings:335]: These does not need to be changed, they get updated automatically, with a translations script.
But this can stay this way no problem

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -801,7 +801,7 @@ class BrowserViewController: UIViewController {
                 
                 let content = UNMutableNotificationContent().then {
                     $0.title = Strings.DefaultBrowserCallout.notificationTitle
-                    $0.body = Strings.DefaultBrowserCallout.notificationBody
+                    $0.body = String(format: Strings.DefaultBrowserCallout.notificationBody, String(floor(Double(UIDevice.current.systemVersion) ?? 14)) ?? "14")
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: There is a simpler method to get device's version, try calling it with
`ProcessInfo().operatingSystemVersion.majorVersion`, this should get you a nice Int value

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
Looks good to me, nice job :)

**Comment by iccub** [comment]
Update on this: Code looks good, we wait on final copy from our copywriter
