### PR TITLE
Fix #6591, Fix #6592: Shields P3A question fixes

### LINKED ISSUE #6591: Incorrect response value for `DomainAdsSettingsAboveGlobal` metrics
### Description: 
Incorrect response value for `DomainAdsSettingsAboveGlobal` metrics

### Steps to Reproduce 
  1. Clean profile 1.46 (22.12.6.19)
  2. Open local state file via Settings 
  3. The metrics `Brave.Shields.DomainAdsSettingsBelowGlobal` and `Brave.Shields.DomainAdsSettingsAboveGlobal` are NOT shown in local state file (Logged https://github.com/brave/brave-ios/issues/6592)
  4. Remove app from memory and relaunch
  5. Still the metrics are not shown, the step 4 is bug, in desktop the metrics are shown with response value `0`
  6. Open any site (e.g cnn.com)
  7. Open the shield panel for cnn.com
  8. Disable "Block Cross-Site Trackers" switch via shield panel
  9. Open the local state file and do refresh
  10. Remove app from memory and relaunch
  11. The metrics `Brave.Shields.DomainAdsSettingsAboveGlobal` response value is `1` in the local state file. 

**Note**: The metrics `Brave.Shields.DomainAdsSettingsBelowGlobal`  response is `1` which is correct and expected. But the metrics `Brave.Shields.DomainAdsSettingsAboveGlobal` response value is also `1` which is wrong as I have not updated the Adblocking settings to "Aggressive", moreover iOS doesn't have any option to set the local shield settings to "Aggressive" via panel

**Actual result:** 

Incorrect response value for `DomainAdsSettingsAboveGlobal` metrics

Example | Example
----------|--------
IMG_3246 | IMG_3247

**Expected result:**
The metrics `Brave.Shields.DomainAdsSettingsAboveGlobal` response value should be `0` 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easy
**Brave Version:** 

1.46 (22.12.6.19)
**Device details:** 
iPhone 8 - 16.1.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/qa-team @kylehickinson @anthonypkeane

### LINKED ISSUE #6592: The `DomainAdsSettingsBelowGlobal` and `DomainAdsSettingsAboveGlobal` are not reported in local state file until the adblocking settings is disabled via shield panel
### Description: 
The `Brave.Shields.DomainAdsSettingsBelowGlobal` is not reported in local state file until the adblocking settings is disabled via shield panel

### Steps to Reproduce 
  1. Clean profile 1.46 (22.12.6.19)
  2. Open local state file via Settings
  3. The metrics `Brave.Shields.DomainAdsSettingsBelowGlobal` and `Brave.Shields.DomainAdsSettingsAboveGlobal` are NOT shown in local state file
  5. Open a site and disable "Block Cross-Site Trackers" switch via shield panel
  6. The metrics `Brave.Shields.DomainAdsSettingsBelowGlobal` and `Brave.Shields.DomainAdsSettingsAboveGlobal` are shown with value `1` in the local state file

**Actual result:** 
The `Brave.Shields.DomainAdsSettingsBelowGlobal` is not reported in local state file until the adblocking settings is disabled via shield panel

**Expected result:**
The metric `Brave.Shields.DomainAdsSettingsBelowGlobal` should be reported with value `0` in the local state file, when adblocking settings is NOT disabled for any site

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

1.46 (22.12.6.19)
**Device details:** 
iPhone 8 - 16.1.1

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/qa-team @kylehickinson @anthonypkeane

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #6591 
This pull request fixes #6592 

Merge by rebase

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

File: Client/Frontend/Shields/ShieldsViewController.swift [hunk 1]
```diff
@@ -352,7 +352,7 @@ class ShieldsViewController: UIViewController, PopoverContentComponent {
     case fingerprintingProtection
   }
   
-  private func recordShieldsUpdateP3A(shield: BraveShield) {
+  static func recordShieldsUpdateP3A(shield: BraveShield) {
```
Comment (soner-yuksel) [inline Client/Frontend/Shields/ShieldsViewController.swift]: Do you think it might be a better idea to create a Manager class etc and inject this dependency in place where 3pa for record functions is a better idea or keeping them in their respective places is actually makes more sense ?

Comment (kylehickinson) [reply Client/Frontend/Shields/ShieldsViewController.swift]: Manager class is probably a bit heavy since we'd need different ones for many different questions and they'd all be mostly single function classes but we could take that direction in some form. I'm going to move this out of `ShieldsViewController` though just to get rid of this static method

Comment (soner-yuksel) [reply Client/Frontend/Shields/ShieldsViewController.swift]: This is change I wanted, thanks

**Review by soner-yuksel — APPROVED** [review]
