### PR TITLE
Fix #7658: Fix playlist shared folders to skip over videos that can't load

### LINKED ISSUE #7658: Issue adding shared playlist folder
### Description: 
Issue downloading shared playlist, I used sample playlist @ playlist.brave.com/bsa-sample but its not adding the folder successfully.

Not an issue in 1.51.x

### Steps to Reproduce 
  1. Install 1.52 (23.6.28.13)
  2. Navigate to playlist.brave.com/bsa-sample
  3. Click on button on add shared playlist sample

### Actual result: 
IMG_3287 2

### Expected result:
Shared Folder should load in playlist

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone X, iOS 16.3.1

### Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix playlist shared folders throwing an exception because a video was made private.

This pull request fixes #7658

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Data/models/PlaylistInfo.swift [hunk 1]
```diff
@@ -74,7 +74,7 @@ public struct PlaylistInfo: Codable, Identifiable, Hashable, Equatable {
   public init(from decoder: Decoder) throws {
     let container = try decoder.container(keyedBy: CodingKeys.self)
     self.name = try container.decode(String.self, forKey: .name)
-    let src = try container.decode(String.self, forKey: .src)
+    let src = try container.decode(String?.self, forKey: .src) ?? ""
```
Comment (kylehickinson) [inline Sources/Data/models/PlaylistInfo.swift]: Probably better to use `decodeIfPresent` over passing in an optional type

Comment (Brandon-T) [reply Sources/Data/models/PlaylistInfo.swift]: Fixed.

**Review by kylehickinson — APPROVED** [review]
