### PR TITLE
Fixed Passcode UI not resetting when going to foreground (Fix #1203)

### LINKED ISSUE #1203: Passcode UI not resetting on resume to foreground from background
### Steps to Reproduce 
1. Have passcode set.
2. Restart application.
3. Authenticate with passcode.
4. Go to private browsing.
5. Search for anything.. Stackoverflow for example.
6. Minimize app to background
7. Resume app to foreground
7. It prompts to authenticate

**Actual result:** 
It prompts to authenticate but authentication is already filled in from the first time we authenticated.

**Expected result:**
It should prompt without passcode being pre-filled.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% of the time.

**Brave Version:** 
1.9.3 (1.2.3.4) - Beta

**Device details:** 
iPhone X (12.2)

**Website problems only:**
- did you check with Brave Shields down? - Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  - Yes

### Additional Information 
Only happens on our "Beta" build (development repository)
Untitled-1

GIF is quite fast (I had to compress a video into GIF) but as you can see, the passcode field is pre-filled when put back into foreground.

### PR DESCRIPTION
**Pull request by Brandon-T**
Fixes Issue: https://github.com/brave/brave-ios/issues/1203

Issue:
1. Have passcode set.
2. Restart application.
3. Authenticate with passcode.
4. Go to private browsing.
5. Search for anything.. Stackoverflow for example.
6. Minimize app to background
7. It prompts to authenticate but authentication is already filled in from the first time we authenticated..

Solution:
Fixed Passcode UI not resetting when going to foreground by calling "resetCode" when successfully entered.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift [hunk 1]
```diff
@@ -99,6 +99,7 @@ extension PasscodeEntryViewController: PasscodeInputViewDelegate {
             authenticationInfo?.recordValidation()
             KeychainWrapper.sharedAppContainerKeychain.setAuthenticationInfo(authenticationInfo)
             delegate?.passcodeValidationDidSucceed()
+            passcodePane.codeInputView.resetCode()
```
Comment (kylehickinson) [inline Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: Since we also call this in the else flow just below, lets move both to be after the if-block so its executed regardless

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]

**Review by danishjafri88 — APPROVED** [review]
