### PR TITLE
Fix #322: Adjust height for popup when if it clips off screen

### LINKED ISSUE #322: Duckduckgo popup for iPhone horizontal has wrong size.
zrzut ekranu 2018-10-9 o 16 38 35

This bug also happens in 1.6 codebase.

### PR DESCRIPTION
**Pull request by danielbogomazov**
Fixes [issue 322](https://github.com/brave/brave-ios/issues/322)

Opening a popup in landscape mode would clip the popup off the bottom of the screen for smaller devices. This happened because the height of the popup is set based on the contents of the popup without adjusting for the screen's height.

## Pull Request Checklist

- [x] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

screen shot 2018-10-23 at 12 46 01 am

### CODE REVIEW

File: Client/Frontend/Popup/PopupView.swift [hunk 1]
```diff
@@ -467,6 +467,7 @@ class PopupView: UIView, UIGestureRecognizerDelegate {
         buttonData.isDefault = true
         buttonData.handler = tapped
         dialogButtons.append(buttonData)
+        layoutSubviews()
```
Comment (kylehickinson) [inline Client/Frontend/Popup/PopupView.swift]: Shouldn't call `layoutSubviews` directly. Instead make this call `setNeedsLayout` and additionally `layoutIfNeeded` if layout needs to happen instantly

File: Client/Frontend/Popup/AlertPopupView.swift [hunk 2]
```diff
@@ -60,29 +61,42 @@ class AlertPopupView: PopupView {
...
         containerView.frame = containerViewFrame
+        
+        let externalContentHeight: CGFloat = dialogButtons.count == 0 ? padding * 3.0 : kPopupDialogButtonHeight + padding * 3.0
+        resizePercentage = 1.0
+        if containerViewFrame.height + externalContentHeight > UIScreen.main.bounds.height {
+            let desiredHeight: CGFloat = UIScreen.main.bounds.height - externalContentHeight
+            resizePercentage = desiredHeight / containerViewFrame.height
+            titleLabel.adjustsFontSizeToFitWidth = true
+            messageLabel.adjustsFontSizeToFitWidth = true
+            updateSubviews()
```
Comment (kylehickinson) [inline Client/Frontend/Popup/AlertPopupView.swift]: I know it's probably never going to be a problem, but is it possible to get a solution that doesn't involve potential recursion? :)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Popup/AlertPopupView.swift (hunk 2 above)
Comment (danielbogomazov) [reply Client/Frontend/Popup/AlertPopupView.swift]: Thanks for the heads up. I've removed the recursion. Let me know what you think :)

File: Client/Frontend/Popup/AlertPopupView.swift [hunk 3]
```diff
@@ -56,32 +56,54 @@ class AlertPopupView: PopupView {
...
+        messageLabel.adjustsFontSizeToFitWidth = false
+
+        _updateSubviews()
+        
+        let paddingHeight: CGFloat = padding * 3.0
+        let externalContentHeight: CGFloat = dialogButtons.count == 0 ? paddingHeight
+            : kPopupDialogButtonHeight + paddingHeight
+        
+        if containerView.frame.height + externalContentHeight > UIScreen.main.bounds.height {
+            let desiredHeight: CGFloat = UIScreen.main.bounds.height - externalContentHeight
```
Comment (jhreis) [inline Client/Frontend/Popup/AlertPopupView.swift]: This logic is actually functionally equivalent to the `if` conditional logic right above it. Probably cleaner to create this constant outside the `if` and just use it in the boolean logic:

```
let desiredHeight: CGFloat = UIScreen.main.bounds.height - externalContentHeight
if containerView.frame.height > desiredHeight {
    // use `desiredHeight`
}
```

File: Client/Frontend/Popup/AlertPopupView.swift [hunk 4]
```diff
@@ -56,32 +56,54 @@ class AlertPopupView: PopupView {
     }
     
     func updateSubviews() {
+        titleLabel.adjustsFontSizeToFitWidth = false
+        messageLabel.adjustsFontSizeToFitWidth = false
+
+        _updateSubviews()
+        
+        let paddingHeight: CGFloat = padding * 3.0
```
Comment (jhreis) [inline Client/Frontend/Popup/AlertPopupView.swift]: Remove all unneeded manual type setting (e.g. the 3 `CGFloat` instances)

File: Client/Frontend/Popup/AlertPopupView.swift [hunk 5]
```diff
@@ -56,32 +56,54 @@ class AlertPopupView: PopupView {
...
+        if containerView.frame.height + externalContentHeight > UIScreen.main.bounds.height {
+            let desiredHeight: CGFloat = UIScreen.main.bounds.height - externalContentHeight
+            let resizePercentage = desiredHeight / containerView.frame.height
+            titleLabel.adjustsFontSizeToFitWidth = true
+            messageLabel.adjustsFontSizeToFitWidth = true
+            _updateSubviews(resizePercentage)
+        }
+    }
+    
+    fileprivate func _updateSubviews(_ resizePercentage: CGFloat = 1.0) {
```
Comment (jhreis) [inline Client/Frontend/Popup/AlertPopupView.swift]: - [ ] Remove leading `_`
- [ ] Make `resizePercentage` a named parameter (no leading `_` here either.

File: Client/Frontend/Popup/AlertPopupView.swift [hunk 6]
```diff
@@ -56,32 +56,54 @@ class AlertPopupView: PopupView {
...
         let width: CGFloat = dialogWidth
         
         var imageFrame: CGRect = dialogImage?.frame ?? CGRect.zero
         if let dialogImage = dialogImage {
+            imageFrame.size = CGSize(width: dialogImage.image!.size.width * resizePercentage, height: dialogImage.image!.size.height * resizePercentage)
```
Comment (jhreis) [inline Client/Frontend/Popup/AlertPopupView.swift]: Remove `image` forced casting (can unwrap inside the above if statement:

`if let dialogImage = dialogImage, let dialogeImageSize = dialogImage.image?.size {`

File: Client/Frontend/Popup/AlertPopupView.swift [hunk 7]
```diff
@@ -56,32 +56,54 @@ class AlertPopupView: PopupView {
     }
     
     func updateSubviews() {
+        titleLabel.adjustsFontSizeToFitWidth = false
+        messageLabel.adjustsFontSizeToFitWidth = false
+
+        _updateSubviews()
+        
+        let paddingHeight: CGFloat = padding * 3.0
+        let externalContentHeight: CGFloat = dialogButtons.count == 0 ? paddingHeight
```
Comment (jhreis) [inline Client/Frontend/Popup/AlertPopupView.swift]: Removed line break, think line is still decent length (< 120 at least), especially after removing the unneeded `CGFloat`.

**Review by jhreis — CHANGES_REQUESTED** [review]
Thanks so much for submitting a PR! This will be a really nice thing to have, just a few random comments. Please let us know if you have any questions!

**Comment by jhreis** [comment]
I've been thinking about this a bit more, and I think we can actually calculate all the necessary variables and setup what is needed before ever calling `updateSubviews`. Something like:

```
        let paddingHeight = padding * 3.0
        let externalContentHeight = dialogButtons.count == 0 ? paddingHeight : kPopupDialogButtonHeight + paddingHeight
        let desiredHeight = UIScreen.main.bounds.height - externalContentHeight

        let resizingRequired = containerView.frame.height > desiredHeight
```

and then use `resizingRequired` for the boolean related logic, thoughts @danielbogomazov?

**Comment by danielbogomazov** [comment]
Thanks for the review, @jhreis! I've fixed all of the commented blocks. 

I'm not quite sure what you mean by 
> I think we can actually calculate all the necessary variables and setup what is needed before ever calling `updateSubviews`

The variables required are only relevant _after_ the subviews are updated initially. They then check if the new height can fit on the screen - if not, it will resize them again, this time to fit. This means that `desiredHeight` can only be calculated after the first set of updates ran by `updateSubview` - only being relevant _if_ the default sizes clip off screen.

**Comment by jhreis** [comment]
Ah, gotcha, I was thinking the height was precalculated, was imaging something like*. But see now why that wasn't possible. 



*
```
    func updateSubviews() {
        let paddingHeight = padding * 3.0
        let externalContentHeight = dialogButtons.count == 0 ? paddingHeight : kPopupDialogButtonHeight + paddingHeight
        let desiredHeight = UIScreen.main.bounds.height - externalContentHeight

        let resizingRequired = containerView.frame.height > desiredHeight
        let resizePercentage = resizingRequired ? desiredHeight / containerView.frame.height : 1.0
        
        titleLabel.adjustsFontSizeToFitWidth = resizingRequired
        messageLabel.adjustsFontSizeToFitWidth = resizingRequired

        _updateSubviews(resizePercentage)
    }
```

**Review by jhreis — APPROVED** [review]
So great! Thank you so much for your help!

**Review by kylehickinson — APPROVED** [review]
