### PR TITLE
Fix #4092 - Weakify tab references due to memory leak.

### LINKED ISSUE #3544: Audio continues to play even after tab is closed
### Description: 
While testing #3358, ran into an bug where the audio continued to play even after the tab was closed. Opening and closing new tabs didn't stop the audio

### Steps to Reproduce 
  1. Clean install 1.25
  2. Open a new tab and open Amazon from favourites
  3. Open a second tab and load `radio.garden`
  4. Wait for the station to auto populate based on location
  5. Move to a different location to change station
  6. Change channel from the list and close the tab, audio continues to play

**Actual result:** 
Audio continues to play even after tab is closed 

**Expected result:**
Stop audio when tab is closed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Happened only once

**Brave Version:** 
1.25(21.4.15.13)

**Device details:** 
iPad Pro (iOS 14.4.2)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Was able to repro the issue only once and when tried few more times doesn't reproduce

### LINKED ISSUE #4092: Audio keeps playing when you open the 3-dot menu and close it even if all tabs are closed.
### Description: 
- Audio keeps playing when you open the 3-dot menu and close it even if all tabs are closed.

### Steps to Reproduce 
  1. Go to youtube.com in a new tab.
  2. Play a video
  3. Open 3-dot menu.
  4. Close 3-dot menu.
  5. Close tab.

**Actual result:** 
- Audio continues to play

**Expected result:**
- Tab should deallocate and audio should stop playing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any

**Device details:** 
Any

**Website problems only:**
N/A

### Additional Information
- Happens due to a leak in the 3-Dot menu and share activity.

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Make menu hold a weak-reference to tab.
- Make share activities hold a weak-reference to tab.

This pull request fixes #4092

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Included in the ticket.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

**Review by soner-yuksel — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 1]
```diff
@@ -83,7 +83,7 @@ extension BrowserViewController {
     
     struct MenuTabDetailsView: View {
         @SwiftUI.Environment(\.colorScheme) var colorScheme: ColorScheme
-        var tab: Tab?
+        weak var tab: Tab?
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift:159]: While this technically fixes the tab issue, we should fix the underlying leak in the menu as well

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 2]
```diff
@@ -80,6 +80,10 @@ class MenuViewController: UINavigationController, UIPopoverPresentationControlle
         fatalError()
     }
     
+    deinit {
+        print("MENU DEALLOCATED")
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift]: remove once tests are over

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
