### PR TITLE
Fix #6087: Address QR code prefix

### LINKED ISSUE #6087: Sending to another address using QR code is not working on IOS
## Description 

Tried sending to a Metamask and Gamestop wallet via QR code but it couldn't read the QR code.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- When reading an address via QR code, strip prefix before `0x` if there is a prefix. Ex. `ethereum:`
- Don't validate address as ethereum address for non-ethereum coin types

This pull request fixes #6087

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
Ethereum:
1. Install MetaMask extension on desktop.
2. Select Ethereum network
3. Open send crypto view and tap QR code button in the 'To' address field
4. Scan the QR code
5. Verify the address populates in the 'To' field, and does not contain `ethereum:` prefix

Solana:
1. Generate a text QR code for a Solana address ([QR code generator](https://www.qr-code-generator.com/))
2. Select Solana network
3. Open send crypto view and tap QR code button in the 'To' address field
4. Scan the QR code
5. Verify the address populates in the 'To' field

## Screenshots:

https://user-images.githubusercontent.com/5314553/193308151-5475a6e5-1c08-4b9c-be97-a3d65e3e2753.MP4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by nuo-xu — APPROVED** [review]

File: Sources/BraveWallet/Crypto/Scanner/AddressQRCodeScannerView.swift [hunk 1]
```diff
@@ -238,3 +260,19 @@ extension AddressQRCodeScannerViewController: AVCaptureMetadataOutputObjectsDele
     isFinishScanning = false
   }
 }
+
+private extension String {
```
Comment (soner-yuksel) [inline Sources/BraveWallet/Crypto/Scanner/AddressQRCodeScannerView.swift]: @StephenHeaps if it is urgent you can do it later but can you add a test for this ?

Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Scanner/AddressQRCodeScannerView.swift]: fixed https://github.com/brave/brave-ios/pull/6088/commits/f16e77e5ba967e32a6e4ded3f4cd11c9c0004c21

Comment (soner-yuksel) [reply Sources/BraveWallet/Crypto/Scanner/AddressQRCodeScannerView.swift]: 🔥

**Review by soner-yuksel — APPROVED** [review]
