### PR TITLE
Fixed #631 Scroll issues.

### LINKED ISSUE #631: Issues while scrolling websites with sticky header/footer
### Description: 
App becomes unresponsive (loss of FPS maybe), while scrolling (jumps instead of scroll) in websites with sticky footer/Header.
Example: m.indiatimes.com (iPhone, footer) & m.youtube.com (iPad, header)

In certain cases the sticky header/footer may also get clipped by browser container. 
Example: m.youtube.com (iPad, header)

### Steps to Reproduce 
  1. Open either of the two websites above.
  2. Scroll slowly as to hide the top/bottom bars

**Actual result:** 
Loss of responsiveness/ fps and sometimes clipping of sticky header/footer in websites.

**Expected result:**
No Scroll Issues 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by danishjafri88**
What is fixed:
->Youtube header problem
->Redundant Pan Gesture creation
->Mis-aligned constraints relations in BrowserViewController
->Refactored Show/Hide Tab Animation properly
-> Enable Zoom by ignoring viewport scale limit.
-> Removed a part of animation code(Hotfix for older logic) which became source of a jump issue during scroll.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Browser/TabScrollController.swift [hunk 1]
```diff
@@ -22,11 +22,12 @@ class TabScrollingController: NSObject {
...
         willSet {
             self.scrollView?.delegate = nil
-            self.scrollView?.removeGestureRecognizer(panGesture)
+            self.scrollView?.panGestureRecognizer.removeTarget(self, action: nil)
         }
 
         didSet {
-            self.scrollView?.addGestureRecognizer(panGesture)
+            self.scrollView?.panGestureRecognizer.addTarget(self, action: #selector(handlePan))
+            self.scrollView?.panGestureRecognizer.maximumNumberOfTouches = 1
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabScrollController.swift]: Should we be modifying the scroll view's pan gesture? This may have side-effects

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -667,8 +667,8 @@ class BrowserViewController: UIViewController {
             webViewContainerTopOffset = make.top.equalTo(readerModeBar?.snp.bottom ?? self.header.snp.bottom).constraint
 
             let findInPageHeight = (findInPageBar == nil) ? 0 : UIConstants.ToolbarHeight
-            if let toolbar = self.toolbar {
-                make.bottom.equalTo(toolbar.snp.top).offset(-findInPageHeight)
+            if let footerView = self.footer {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift:670]: Why does this work? `footer` will never be nil whereas `toolbar` will be when in landscape

Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift:670]: It's declared as optional.

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift:670]: Sorry I didn't mean why do you need the `if-let`, I meant this will execute every time now and never hit the `else` below. `footer` is set and never un-set.

File: Client/Frontend/Browser/TabScrollController.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/TabScrollController.swift]: Agreed. I copied what was done for the PanGesture created. Looking at it now there is no need to update this value.

File: Client/Frontend/Browser/BraveWebView.swift [hunk 3]
```diff
@@ -13,6 +13,8 @@ class BraveWebView: WKWebView {
             configuration.websiteDataStore = WKWebsiteDataStore.nonPersistent()
         }
         
+        // Enables Zoom in website by ignoring their javascript based viewport Scale limits.
+        configuration.ignoresViewportScaleLimits = true
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BraveWebView.swift]: Should probably put this with all the other configuration edits (for easier finding it later):

https://github.com/brave/brave-ios/blob/development/Client/Frontend/Browser/Tab.swift#L188-L191

Though I realize `TabWebView` subclasses `BraveWebView` (I don't think we need both, maybe we should bring `BraveWebView` stuff over to `TabWebView` and delete it)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 2 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift:670]: Oh, so footer is constrained to bottom of view and when there is no toolbar its height becomes 0. Hence its constrained to bottom of screen. If footer will never be nil then perhaps we can remove the else case and also make it non-optional. What do you suggest?

File: Client/Frontend/Browser/BraveWebView.swift (hunk 3 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/BraveWebView.swift]: Thanks! Was thinking where to put it myself. :)

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift:670]: I'd suggest taking a closer look at why it used `toolbar` and if it really doesn't matter (like you said, its height becomes 0 anyways), then we can just remove the else clause here. In fact, we can also change the declaration of footer so its not implicitly unwrapped:

```
let footer = UIView()
```

rather than its current declaration: `var footer: UIView!` and being init'd later

Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift:670]: Kept it as unwrapped optional as it is initialised in viewdidload, but used without `?` as it is never set to nil.

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Not sure if you still want @jhreis to take a look, so delaying merge for now

**Review by jhreis — APPROVED** [review]
