### PR TITLE
Fix #5835: Fix wallet crash caused by same coinGeckoId

### LINKED ISSUE #5835: Browser crash when trying to add SPL token (BAT Portal)
### Description: 
Browser crash when trying to add SPL token (BAT Portal)

### Steps to Reproduce 
  1. Create Solana Account
  2. Go to add custom token and search for Basic Attention Token (Portal)
  3. Add token, browser crashes after a second

**Actual result:** 

https://user-images.githubusercontent.com/17010094/184144571-c91fa11c-6c04-48ca-b61b-73758b4dca81.MP4

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.10.15)

**Device details:** 
iPhone XR (iOS 15.4.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
fix duplicate id for fetching price and price history. set up balance mapping with unique id

This pull request fixes #5835 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

1. create a solana account
2. add two or more tokens that have the same coinGeckoId (bat portal and bat wormhole) to your visible assets
3. observe if crash happens 

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/PortfolioStore.swift [hunk 1]
```diff
@@ -213,8 +213,9 @@ public class PortfolioStore: ObservableObject {
   @MainActor func fetchPriceHistory(
     for priceIds: [String]
   ) async -> [String: [BraveWallet.AssetTimePrice]] {
+    let uniquePriceIds = Array(Set(priceIds))
```
Comment (iccub) [inline BraveWallet/Crypto/Stores/PortfolioStore.swift]: Do we have to bridge it to Array? we can iterate over a `Set` too

Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/PortfolioStore.swift]: fixed in [edbc704](https://github.com/brave/brave-ios/pull/5838/commits/edbc704c503610a93ba78f438c39563a7f2805d0)

**Review by iccub — APPROVED** [review]

**Review by StephenHeaps — APPROVED** [review]
