### PR TITLE
Fix #6109: Recent Search Auto-Fill should populate the text not the URL

### LINKED ISSUE #6109: Recent Search Auto-Fill should populate the text not the URL
### Description: 

When a search is performed using quick search bar and recent search is populated with it. The Recent Search accessory icon should populated the URL bar with the search text not the url itself.

### Steps to Reproduce 
  1. Write test on URL bar
  2. Press one of the quick search engines from search bar
  3. Press arrow icon(accessory view to recent search)
  4. URL is populated in URL bar

**Actual result:** 

The url is populated in URL bar

https://user-images.githubusercontent.com/6643505/194124659-d6e65ac2-bf62-428c-a21d-59137fc36e98.MP4

**Expected result:**

The text of search keywords should be populated not the url

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced

**Brave Version:** 

Any

**Device details:** 

Any

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This pull request fixes #6109 and additionally is deleting some unused Strings

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

1. Write test on URL bar
2. Press one of the quick search engines from search bar
3. Press arrow icon(accessory view to recent search)
4. Query is populated in URL bar

## Screenshots:

https://user-images.githubusercontent.com/6643505/194125650-96a16d1d-cf9c-4a6b-a420-c6246b33d1e4.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Shared/SharedStrings.swift [hunk 1]
```diff
@@ -43,7 +39,7 @@ extension Strings {
   public static let backTitle = NSLocalizedString("BackTitle", bundle: .strings, value: "Back", comment: "Label to display in the Discoverability overlay for keyboard shortcuts")
   public static let forwardTitle = NSLocalizedString("ForwardTitle", bundle: .strings, value: "Forward", comment: "Label to display in the Discoverability overlay for keyboard shortcuts")
 
-  public static let findTitle = NSLocalizedString("FindTitle", bundle: .strings, value: "Find", comment: "Label to display in the Discoverability overlay for keyboard shortcuts")
+//  public static let findTitle = NSLocalizedString("FindTitle", bundle: .strings, value: "Find", comment: "Label to display in the Discoverability overlay for keyboard shortcuts")
```
Comment (kylehickinson) [inline Sources/Shared/SharedStrings.swift]: Assume this one was meant to be deleted too?

**Review by kylehickinson — APPROVED** [review]

File: Sources/Shared/SharedStrings.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/Shared/SharedStrings.swift]: Fixed at https://github.com/brave/brave-ios/pull/6110/commits/e588f9f38d2e9a80b7c79bc9e02267c7562c7983
