### PR TITLE
Fix #7548: Tab Deallocation on main thread

### LINKED ISSUE #7548: Crash - Sometimes when closing a tab, the browser crashes
### Description: 
- Sometimes, when a user closes a tab, the browser crashes.
- Crash log shows it's `Tab.deinit` in the Xcode organizer.

### Steps to Reproduce 
  1. Close some Tabs

### Actual result: 
- Crash

### Expected result:
- Shouldn't crash

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Very very hard to reproduce

### Brave Version: 
- 1.49.x

### Device details: 
- iPhone

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Access everything from brave-core weakly. If tab deallocates, all of the objects deallocate under the hood. The weak references become nil. If they are still for some reason doing an operation, well it should be cancelled.

- Fix possible favicon crash

This pull request fixes #7548

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/Tab.swift [hunk 1]
```diff
@@ -269,14 +295,14 @@ class Tab: NSObject {
     self.id = id
     rewardsId = UInt32.random(in: 1...UInt32.max)
     nightMode = Preferences.General.nightModeEnabled.value
-    syncTab = tabGeneratorAPI?.createBraveSyncTab(isOffTheRecord: type == .private)
+    _syncTab = tabGeneratorAPI?.createBraveSyncTab(isOffTheRecord: type == .private)
     
-    if let syncTab = syncTab {
-      faviconDriver = FaviconDriver(webState: syncTab.webState).then {
+    if let syncTab = _syncTab {
```
Comment (StephenHeaps) [inline Sources/Brave/Frontend/Browser/Tab.swift:300]: I don't think matters here but for consistency should this access remain on `syncTab` (instead of `_syncTab`) to match others?

**Review by StephenHeaps — APPROVED** [review]

File: Sources/Brave/Frontend/Browser/Tab.swift (hunk 1 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/Tab.swift:300]: It shouldn't make a difference since this is done in the `constructor`, and the driver only cares about the internal `webState` which we don't control from the Swift side.

Then in `deinit` both are deallocated weakly :) so no worries.
I think in the constructor we should access the hard reference instead of dealing with weak. Everywhere else we should use weak.
