### PR TITLE
Fix #3250: Text is not visible when editing a favourite/bookmark in dark mode 

### LINKED ISSUE #3250: Text is not visible when editing a favourite/bookmark in dark mode - Follow up to #2644
### Description: 

Text is really light/hard to read when editing bookmarks/favourites. This a follow up to https://github.com/brave/brave-ios/issues/2644.

### Steps to Reproduce 

  1. launch `1.23 (21.1.28.17)`
  2. switch over to `Private` mode
  3. edit a bookmark/favourite under NTP

**Actual result:** 

IMG_0093

**Expected result:**

IMG_3522

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.23 (21.1.28.17)`

**Device details:** 

* `iPhone 6s+` using `iOS 12.4.1`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @soner-yuksel @iccub @srirambv @bsclifton @aekeus

### PR DESCRIPTION
**Pull request by soner-yuksel**
DefaultTextAttributes change for fixing iOS 12 Alert textfield textcolor. 
This change is probably the only working way to alter text attributes for textfield inside AlertViewController < iOS13 when browser is in Private Mode. 

## Summary of Changes

This pull request fixes #3250 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Launch 1.23 (21.1.28.17)
- Switch over to Private mode
- Edit a bookmark/favourite under NTP

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Extensions/UIAlertControllerExtensions.swift [hunk 1]
```diff
@@ -248,6 +248,11 @@ class UserTextInputAlert {
                         attributes: [.foregroundColor: UIColor.placeholderText])
                 } else {
                     textField.placeholder = placeholder
+                    
+                    if PrivateBrowsingManager.shared.isPrivateBrowsing {
+                        UITextField.appearance(whenContainedInInstancesOf: [UIAlertController.self]).defaultTextAttributes =
+                            [.foregroundColor: UIColor.black]
+                    }
```
Comment (kylehickinson) [inline Client/Extensions/UIAlertControllerExtensions.swift]: What happens if you switch back to normal browsing? Wouldn't the text be stuck as black?

Comment (soner-yuksel) [reply Client/Extensions/UIAlertControllerExtensions.swift]: Good question and the answer is I tested it with a red color and it doesnt stuck.

Comment (iccub) [reply Client/Extensions/UIAlertControllerExtensions.swift]: This should be placed in `AppearanceExtensions` and maybe assign values to both dark and light modes? needs testing though

Comment (soner-yuksel) [reply Client/Extensions/UIAlertControllerExtensions.swift]: So in iOS 12 doesnt have difference in light and dark mode also this change will not get effected regarding to private or not. So moved the change into Appearance Extensions for iOS12

**Review by iccub — APPROVED** [review]
