### PR TITLE
Fix #2260: Don't show second NTP notification if Rewards enabled via …

### LINKED ISSUE #2260: Second NTP notification showing if enabling Rewards via NTP
### Steps to Reproduce 
  1. Fresh launch, skip onboarding
  2. Open sponsored tab, wait for banner
  3. Tap on `turn rewards` on the banner, wait until wallet is created
  4. Open new tabs until another sponsored image is shown, wait 1.5 sec

**Actual result:** 
Another NTP notification will show `you are getting paid for this image...`

**Expected result:**
Shouldn't show, the notification should show only once, exception is when you reset ads or rewards via Rewards settings panel

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
…NTP.

## Summary of Changes

This pull request fixes issue #2260 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Settings/SettingsViewController.swift [hunk 1]
```diff
@@ -137,14 +137,13 @@ class SettingsViewController: UIViewController {
   @objc private func rewardsSwitchValueChanged() {
     state.ledger.isEnabled = settingsView.rewardsToggleSection.toggleSwitch.isOn
     updateVisualStateOfSections(animated: true)
+    NotificationCenter.default.post(name: .adsOrRewardsToggledInSettings, object: nil)
```
Comment (iccub) [inline BraveRewardsUI/Settings/SettingsViewController.swift:140]: I know we reverted on this @kylehickinson, but resetting the status of NTP notification should happen only after toggling Rewards state in settings

otherwise tapping on Rewards button from ntp notification will trigger second notification, but we only want one
this solution should be enough, even if there are other ways/places to toggle Rewards

Comment (kylehickinson) [reply BraveRewardsUI/Settings/SettingsViewController.swift:140]: Im not really in love with this solution mostly because it looks like we're purposely missing adding notification posts to meet the spec of this feature when we should be handling it on Client side, but I'm fine with it considering the naming change to the notification defining that its happening `in settings`

**Review by kylehickinson — APPROVED** [review]
