### PR TITLE
Fix #739: Supporting favorites without http/https prefix

### LINKED ISSUE #739: Adding favourite without http/https prefix doesn't load the site
### Description: 
Adding favourite without http/https prefix doesn't load the site

### Steps to Reproduce 
  1. Clear profile on 1.7.2(19.1.15.15)
  2. Edit a favourite and add title as `Github` and replace url with `github.com`
  3. Load the edited favourite, doesn't load the site
  4. Edit the same favourite and add `https://` prefix in URL
  5. Load the favourite, site is loaded correctly

**Actual result:** 
https://youtu.be/kGOyRhP-3WQ

**Expected result:**
Should be able to load the site since user doesn't add https/http prefix in URL bar while loading the site

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.2(19.1.15.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by JonKaleidoscope**
**Fix** https://github.com/brave/brave-ios/issues/739

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adaquate test plan exists for QA to validate (if applicable)

## Other Comments

This change enables the _Favorites_ to accept pretty much any string not just URL's. The _Favorites_ UI allowed for easier changes but modifying the _Bookmarks_ to accept values that are not URL's is little more involved. In the nature of keeping PR's small, I think those changes would be better served in another PR.

The `BookmarksViewController` uses `URLRow` which requires the value to be an actual `URL`. [See details here](https://github.com/brave/brave-ios/blob/12df4aac9219cc6795866eab9de16f8696d5e45f/Client/Frontend/Menu/BookmarksViewController.swift#L95)

### CODE REVIEW

File: Client/Frontend/Browser/HomePanel/FavoritesViewController.swift [hunk 1]
```diff
@@ -73,8 +73,9 @@ class FavoritesViewController: UIViewController, Themeable {
     
     private let profile: Profile
     
-    init(profile: Profile) {
+    init(profile: Profile, dataSource: FavoritesDataSource = FavoritesDataSource()) {
```
Comment (jhreis) [inline Client/Frontend/Browser/HomePanel/FavoritesViewController.swift:76]: Love the use of composition here, nice architectural improvement.

File: Client/Frontend/Browser/HomePanel/FavoritesViewController.swift [hunk 2]
```diff
@@ -46,7 +46,7 @@ class FavoritesViewController: UIViewController, Themeable {
         }
         return view
     }()
-    private lazy var dataSource: FavoritesDataSource = { return FavoritesDataSource() }()
+    internal let dataSource: FavoritesDataSource
```
Comment (jhreis) [inline Client/Frontend/Browser/HomePanel/FavoritesViewController.swift]: Any reason this can't stay `private`?

**Comment by jhreis** [comment]
Hey, @JonKaleidoscope just wanted to let you know. I will get to your PR on Friday. It is really solid looking, just want to run some manual tests on it, but extremely thorough. Truly appreciate it. We haven't forgotten about it 😄 we've just been pretty swamped.

**Comment by JonKaleidoscope** [comment]
No worries @jhreis , just glad to know I was not forgotten. I am happy to help out where I can. Feel free to direct me to any other area where you think I can help out.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -2894,8 +2898,8 @@ extension BrowserViewController: HomeMenuControllerDelegate {
 
 extension BrowserViewController: TopSitesDelegate {
     
-    func didSelectUrl(url: URL) {
-        finishEditingAndSubmit(url, visitType: .bookmark)
+    func didSelect(urlString: String) {
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift]: This isn't technically a `url` anymore, right? Maybe maybe something like `input` instead?

**Review by jhreis — CHANGES_REQUESTED** [review]
Really slick, super great PR, just a few super small comments, and a merge conflict, will merge after that. Greatly appreciate this! 😄

File: Client/Frontend/Browser/HomePanel/FavoritesViewController.swift (hunk 2 above)
Comment (JonKaleidoscope) [reply Client/Frontend/Browser/HomePanel/FavoritesViewController.swift]: I think in the midst of trying to write some unit I exposed this variable. I was able to get around this my injecting the `dataSource` during initilaization. I will return in back to private.

Comment (jhreis) [reply Client/Frontend/Browser/HomePanel/FavoritesViewController.swift]: 👍 also, in a test file if you use `@testable` to import a module, it ignores scope, so private functions/properties are accessible, but composition works here too.

**Comment by jhreis** [comment]
Just a merge conflict left, I will get around to fixing this later if you don't have time to get around to it. Will merge once that's done. Really nice PR, thanks!

File: Client/Frontend/Browser/HomePanel/FavoritesViewController.swift (hunk 2 above)
Comment (JonKaleidoscope) [reply Client/Frontend/Browser/HomePanel/FavoritesViewController.swift]: I wish the `@testable` modifier worked like this but unfortunately it does not. It only exposes properties/types/functions that are `internal`.

**When you write an app with a unit test target, the code in your app needs to be made available to that module in order to be tested. By default, only entities marked as open or public are accessible to other modules. However, a unit test target can access any internal entity, if you mark the import declaration for a product module with the `@testable` attribute and compile that product module with testing enabled.**
  [Swift Docs - Access Control](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#)

Other Reading: 
https://cocoacasts.com/how-to-unit-test-private-methods-in-swift/

**Comment by JonKaleidoscope** [comment]
Apologies on not resolving the merge conflict. I thought I brought the commit forward. It should be good now.

**Review by jhreis — APPROVED** [review]
This is great, really appreciate it!
