### PR TITLE
Fix #6261: Ensure shields are loaded before the first tab launches.

### LINKED ISSUE #6261: Ensure shields are loaded before the first tab launches.
### Description: 
When launching the application (after it is terminated) shields may not be applied momentarily.

### Steps to Reproduce 
  1. Go to a website with visible blocking. For example https://dev-pages.brave.software/filtering/scriptlets.html or https://youtube.com (we block ads here)
  2. Kill the app
  3. Launch the app

**Actual result:** 
Shields not applied applied: 
1. https://dev-pages.brave.software/filtering/scriptlets.html does not show true for all values
2. Youtube shows ads when watching a video

**Expected result:**
Should apply shields right away (for that first tab):
1. https://dev-pages.brave.software/filtering/scriptlets.html should show true for all values
2. Youtube should not show ads when watching a video

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproducible

**Brave Version:** 
1.45

**Device details:** 
N/A

### Additional Information
Caused by independently loading shields and the first tab. This is a race condition and usually the tab loads faster than the shields. Need to improve loading the shields (and block the first tab) from cache.
This is tricky because we don't want to block the app from launching the first tab (so it doesn't look slow) for the sake of loading shields

Youtube navigation doesn't solve the issue because it's a single page application. you need to refresh YouTube to solve the ads problem. Most people are not aware of this and stay and navigate YouTube which gives them ads all the time if this is the first page they go to after launching the app.

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #6261 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -40,18 +40,83 @@ private let KVOs: [KVOConstants] = [
...
+    tabsBar.delegate = self
+    return tabsBar
+  }()
+
+  // These views wrap the top and bottom toolbars to provide background effects on them
+  let header = HeaderContainerView()
+  private let headerHeightLayoutGuide = UILayoutGuide()
+  
+  private(set) lazy var footer: UIView = {
+    let footer = UIView()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Doesn't need to be lazy

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -40,18 +40,83 @@ private let KVOs: [KVOConstants] = [
...
+    footer.translatesAutoresizingMaskIntoConstraints = false
+    return footer
+  }()
+  
+  private lazy var topTouchArea: UIButton = {
+    let topTouchArea = UIButton()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Doesnt need to be lazy

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -40,18 +40,83 @@ private let KVOs: [KVOConstants] = [
...
+    topTouchArea.isAccessibilityElement = false
+    return topTouchArea
+  }()
+  
+  private lazy var bottomTouchArea: UIButton = {
+    let bottomTouchArea = UIButton()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Doesn't need to be lazy

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -40,18 +40,83 @@ private let KVOs: [KVOConstants] = [
...
+    bottomTouchArea.isAccessibilityElement = false
+    return bottomTouchArea
+  }()
+  
+  /// These constraints allow to show/hide tabs bar
+  private var webViewContainerTopOffset: Constraint?
+
+  /// Backdrop used for displaying greyed background for private tabs
+  private lazy var webViewContainerBackdrop: UIView = {
+    let webViewContainerBackdrop = UIView()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Doesn't need to be lazy

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 5]
```diff
@@ -40,18 +40,83 @@ private let KVOs: [KVOConstants] = [
...
+    return webViewContainerBackdrop
+  }()
+  
   var readerModeBar: ReaderModeBarView?
-  var readerModeCache: ReaderModeCache
-  var statusBarOverlay: UIView!
-  fileprivate(set) var toolbar: BottomToolbarView?
+  private(set) var readerModeCache: ReaderModeCache
+  
+  private lazy var statusBarOverlay: UIView = {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Doesn't need to be lazy

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 6]
```diff
@@ -40,18 +40,83 @@ private let KVOs: [KVOConstants] = [
...
+  var searchLoader: SearchLoader?
   var searchController: SearchViewController?
   var favoritesController: FavoritesViewController?
-  var screenshotHelper: ScreenshotHelper!
-  var searchLoader: SearchLoader?
-  let alertStackView = UIStackView()  // All content that appears above the footer should be added to this view. (Find In Page/SnackBars)
+  
+  /// All content that appears above the footer should be added to this view. (Find In Page/SnackBars)
+  private(set) lazy var alertStackView: UIStackView = {
+    let alertStackView = UIStackView()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Doesn't need to be lazy

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 7]
```diff
@@ -40,18 +40,83 @@ private let KVOs: [KVOConstants] = [
 ]
 
 public class BrowserViewController: UIViewController {
-  var webViewContainer: UIView!
-  var topToolbar: TopToolbarView!
-  var tabsBar: TabsBarViewController!
+  private(set) lazy var webViewContainer = UIView()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Doesn't need to be lazy

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 8]
```diff
@@ -0,0 +1,67 @@
...
+  }
+  
+  private func markAdBlockReady() {
+    areAdBlockServicesReady = true
+  }
+  
+  private func performPostLoadTasks(adBlockService: AdblockService) {
+    Task { @MainActor in
+      await ContentBlockerManager.shared.cleanupDeadRuleLists()
+      await ContentBlockerManager.shared.compilePendingResources()
```
Comment (Brandon-T) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift:60]: Can these be ran in parallel, or is the ordering here strict?

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 9]
```diff
@@ -0,0 +1,67 @@
...
+      _ = await (loadBundledResources, filterListCache, adblockResourceCache)
+
+      // Compile some engines and load cached rule lists
+      async let compiledResourcesCompile: Void = await AdBlockEngineManager.shared.compileResources()
+      async let cachedRuleListLoad: Void = await ContentBlockerManager.shared.loadCachedRuleLists()
+      _ = await (compiledResourcesCompile, cachedRuleListLoad)
+      
+      // This one is non-blocking
+      await performPostLoadTasks(adBlockService: adBlockService)
+      await markAdBlockReady()
```
Comment (Brandon-T) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: Should `markAdBlockReady` be called before `performPostLoadTasks` are actually done running since those are ran async?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+    guard !areAdBlockServicesReady else { return }
+    
+    // Check if we're still preparing the ad-block services
+    // If so we await that task
+    if let task = loadTask {
+      return await task.value
+    }
+    
+    // Otherwise prepare the services and await the task
+    let task = Task { @MainActor in
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: This `@MainActor` is redundant, everything inside is being await'd on

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+      // Load cached data
+      // This is done first because compileResources and loadCachedRuleLists need their results
+      async let loadBundledResources: Void = await ContentBlockerManager.shared.loadBundledResources()
+      async let filterListCache: Void = await FilterListResourceDownloader.shared.loadCachedData()
+      async let adblockResourceCache: Void = await AdblockResourceDownloader.shared.loadCachedData()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: `await` keyword is not required on the rhs of `async let`

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 12]
```diff
@@ -0,0 +1,67 @@
...
+      _ = await (loadBundledResources, filterListCache, adblockResourceCache)
+
+      // Compile some engines and load cached rule lists
+      async let compiledResourcesCompile: Void = await AdBlockEngineManager.shared.compileResources()
+      async let cachedRuleListLoad: Void = await ContentBlockerManager.shared.loadCachedRuleLists()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: `await` keyword is not required on the rhs of `async let`

File: Client/WebFilters/AdBlockEngineManager.swift [hunk 13]
```diff
@@ -395,10 +392,12 @@ public actor AdBlockEngineManager: Sendable {
           return
         }
         
-        if engine.deserialize(data: data) {
-          continuation.resume()
-        } else {
-          continuation.resume(throwing: CompileError.couldNotDeserializeDATFile)
+        DispatchQueue.main.async {
```
Comment (cuba) [inline Client/WebFilters/AdBlockEngineManager.swift:395]: Shouldn't we use the serial queue on Adblock stats?

**Review by cuba — COMMENTED** [review]
Just one comment

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 9 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift]: Well internally `performPostLoadTasks` is non blocking. the async is needed because we're calling an actor

Could be replaced with 

```
     Task { @MainActor in
        await ContentBlockerManager.shared.cleanupDeadRuleLists()
        await ContentBlockerManager.shared.compilePendingResources()
        FilterListResourceDownloader.shared.start(with: adBlockService)
        await AdblockResourceDownloader.shared.startFetching()
        ContentBlockerManager.shared.startTimer()
        await AdBlockEngineManager.shared.startTimer()
      }
      
      await markAdBlockReady()
```

File: Client/WebFilters/AdBlockEngineManager.swift (hunk 13 above)
Comment (iccub) [reply Client/WebFilters/AdBlockEngineManager.swift:395]: Needs further investigation, for the time being it's safer to use main queue here

Comment (soner-yuksel) [reply Client/WebFilters/AdBlockEngineManager.swift:395]: Do not remove this line or we will have the threading pause/delay again.

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 8 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift:60]: I think it can be parallel, the one removes any rules that shouldn't be there (i.e not enabled resources) the other one compiles pending ones. Since pending ones are a subset of enabled resources the two shouldn't interfere

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 14]
```diff
@@ -0,0 +1,67 @@
...
+      _ = await (loadBundledResources, filterListCache, adblockResourceCache)
+
+      // Compile some engines and load cached rule lists
+      async let compiledResourcesCompile: Void = AdBlockEngineManager.shared.compileResources()
+      async let cachedRuleListLoad: Void = ContentBlockerManager.shared.loadCachedRuleLists()
+      _ = await (compiledResourcesCompile, cachedRuleListLoad)
+      
+      // This one is non-blocking
+      performPostLoadTasks(adBlockService: adBlockService)
+      markAdBlockReady()
```
Comment (Brandon-T) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift:44]: Should `markAdBlockReady` be called in parallel to `performPostLoadTasks`? Because `performPostLoadTasks` is ran concurrently and `areAdBlockServicesReady = true` is set immediately before it is finished.

So should `areAdBlockServicesReady = true` from `markAdBlockReady` be set only after `performPostLoadTasks` is completed?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 8 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift:60]: But it shouldn't affect load time because this is not blocking. It may affect however how quickly we get the latest rules in.

Comment (Brandon-T) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift:60]: We should run them in parallel (`async`) then, for better performance and to free up the main-thread faster IF they might take long :)

Comment (iccub) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift:60]: Let's handle separately https://github.com/brave/brave-ios/issues/6423

**Review by kylehickinson — APPROVED** [review]

**Review by soner-yuksel — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 8 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift:60]: Oops, I accedentally resolved this one. @Brandon-T ill let you resolve this one if you agree

**Review by cuba — APPROVED** [review]
