### PR TITLE
Fix #4777:  Update reset wallet to call BraveWalletService.reset

### LINKED ISSUE #4777: Change to new way to Reset Wallet for brave-core 1.36.x upgrade
### Description: 

Before 1.35.x brave-core, you could just call KeyringController::Reset to reset the wallet. This changes as of this PR:
https://github.com/brave/brave-core/pull/11669/files#diff-d5d80c8bf10054827601d890b9e85e6c9bfc4304b17089bd7d443c94c554f232R19

Resetting Wallet must change to this new method for upgrade to 1.36.x brave-core or else there will be Reset regressions.

cc @nuo-xu or @kylehickinson

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Core had an update to solve resetting `KeyringService` is not resetting `RpcService`.
Hence iOS side needs to update to call the correct reset.
According to bbondy, `BraveWalletService.reset` is the only one we need. ref: https://github.com/brave/brave-ios/issues/4777#issuecomment-1006113518 

This pull request fixes #4777 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/KeyringStore.swift [hunk 1]
```diff
@@ -96,10 +96,15 @@ public class KeyringStore: ObservableObject {
   }
   
   private let keyringService: BraveWalletKeyringService
+  private let walletService: BraveWalletBraveWalletService // for wallet reset
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/KeyringStore.swift]: Remove this and `reset` from `KeyringStore` and use wallet service directly in settings instead. Then use the observer to handle the logic from reset (`isOnboardingVisible`/`Self.resetKeychainStoredPassword`)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 2]
```diff
@@ -141,9 +141,23 @@ extension BrowserViewController {
...
+                   let txService = BraveWallet.EthTxServiceFactory.get(privateMode: PrivateBrowsingManager.shared.isPrivateBrowsing) {
+                    keyringStore = KeyringStore(keyringService: keyringService)
+                    cryptoStore = CryptoStore(keyringService: keyringService,
+                                              rpcService: rpcService,
+                                              walletService: walletService,
+                                              assetRatioService: assetRatioService,
+                                              swapService: swapService,
+                                              blockchainRegistry: BraveCoreMain.blockchainRegistry,
+                                              txService: txService)
+                }
```
Comment (nuo-xu) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift]: @kylehickinson this is what i meant - big init.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 3]
```diff
@@ -141,21 +141,39 @@ extension BrowserViewController {
...
+                                                        feedDataSource: self.feedDataSource,
+                                                        rewards: self.rewards,
+                                                        legacyWallet: self.legacyWallet,
+                                                        windowProtection: self.windowProtection,
+                                                        historyAPI: self.historyAPI,
+                                                        syncAPI: self.syncAPI)
+                        vc.settingsDelegate = self
+                        menuController.pushInnerMenu(vc)
+                    }
+                }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift]: Remove this, add the check in SettingsViewController when deciding whether or not to add the row

File: BraveWallet/Crypto/Stores/CryptoStore.swift [hunk 4]
```diff
@@ -176,6 +176,19 @@ public class CryptoStore: ObservableObject {
...
+      return store
+    }
+    let store = SettingsStore(
+      keyringService: keyringService,
+      walletService: walletService
+    )
+    settingsStore = store
+    return store
+  }
+
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/CryptoStore.swift]: Is there any reason for this to be nil other than off screen? If not, then just make this lazy instead? `private(set) lazy var settingsStore = SettingsStore(keyringService: keyringService, walletService: walletService)` and then use directly

File: BraveWallet/Crypto/Stores/CryptoStore.swift [hunk 5]
```diff
@@ -201,6 +214,10 @@ public class CryptoStore: ObservableObject {
       }
     }
   }
+  
+  func reset() {
+    walletService.reset()
+  }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/CryptoStore.swift]: This is no longer needed?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/Accounts/AccountsHeaderView.swift [hunk 6]
```diff
@@ -8,6 +8,7 @@ import struct Shared.Strings
 
 struct AccountsHeaderView: View {
   @ObservedObject var keyringStore: KeyringStore
+  var cryptoStore: CryptoStore
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Accounts/AccountsHeaderView.swift]: You can just pass `SettingsStore` in here, its going to be evaluated immediately anyways since `NavigationLink` isn't lazy

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 7]
```diff
@@ -581,6 +576,28 @@ class SettingsViewController: TableViewController {
         )
     }()
     
+    private func setUpSections() {
+        if #available(iOS 14.0, *), let settingsStore = walletSettingsStore {
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: Lets remove the iOS 14 check, we're 14 min now, its no longer needed

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 8]
```diff
@@ -581,6 +576,28 @@ class SettingsViewController: TableViewController {
...
+                }) {
+                    copyOfSections[index].rows.append(
+                        Row(text: Strings.Wallet.braveWallet, selection: { [unowned self] in
+                            let vc = UIHostingController(rootView: WalletSettingsView(settingsStore: settingsStore))
+                            self.navigationController?.pushViewController(vc, animated: true)
+                        }, image: #imageLiteral(resourceName: "menu-crypto").template, accessory: .disclosureIndicator)
+                    )
+                    self.dataSource.sections = copyOfSections
+                } else {
+                    self.dataSource.sections = self.sections
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: Redundant else clause, just move the `self.dataSource.sections = copyOfSections` outside of the scope of this branch

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
