### PR TITLE
Fix #2375: Crash when NTP resource is downloaded with network error.

### LINKED ISSUE #2375: NTP `unpackMetadata` crash.
### Description: 

Zrzut ekranu 2020-02-27 o 11 54 00

### Steps to Reproduce 
  1. Hard to reproduce, it crashes for some users only

**Actual result:** 
Crash

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

Completion handler from `unpackMetadata` was sent twice in case of network error.
This caused the dispatchgroup to crash.

This pull request fixes #2375 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/HomePanel/NTPDownloader.swift [hunk 1]
```diff
@@ -328,7 +328,7 @@ class NTPDownloader {
             }
             
             if response.statusCode != 304 && (response.statusCode < 200 || response.statusCode > 299) {
-                completion(nil, nil, "Invalid Response Status Code: \(response.statusCode)")
+                return completion(nil, nil, "Invalid Response Status Code: \(response.statusCode)")
```
Comment (jhreis) [inline Client/Frontend/Browser/HomePanel/NTPDownloader.swift]: This return should be on a separate line, since we aren't actually returning anything. 
```suggestion
                completion(nil, nil, "Invalid Response Status Code: \(response.statusCode)")
                return
```

**Review by jhreis — CHANGES_REQUESTED** [review]
Checking implementation, but wanted to leave this comment.

**Review by kylehickinson — APPROVED** [review]
Do people like this syntax? I've seen it a few times now but its confusing to read because the function has no return type. I get this is essentially the same as 

```
completion(nil, nil, "Invalid Response Status Code: \(response.statusCode)")
return
```

But just was wondering what others thought

**Comment by iccub** [comment]
I don't like it but when it was crashing for me when i put return one line below lol, might recheck it

**Review by jhreis — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
