### PR TITLE
Fix #5692: Pull favicons from cache when necessary

### LINKED ISSUE #5692: Favicons not cache properly and not pulling from the cache
### Steps to Reproduce 
  1. Visit any website.
  2. Favicons are downloaded correctly.
  3. Close the tab.
  4. Visit History, Bookmarks, or make a search (but do not submit the search, we only care about the suggestions)

**Actual result:** 
- Application makes a request for all icons

**Expected result:**
- Application should not request favicons again. It should pull favicons from cache for sites visited in the past.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced

**Brave Version:** 
- Any

**Device details:** 
- Any

**Website problems only:**
- Nope

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Pull favicons from cache only, when viewing History and Search Suggestions screens.
- Properly cache icons when they are fetched

This pull request fixes #5692

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Check that the app does not make any requests for favicons when NOT viewing/visiting a page.

## Screenshots:
image

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift [hunk 1]
```diff
@@ -292,6 +292,17 @@ public class FaviconFetcher {
           if !cache.isCached(url) {
             completion(self.url, self.monogramFavicon)
             return
+          } else {
+            cache.getCachedImage(for: url) { image in
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favicons/FaviconFetcher.swift]: Technically this doesn't have to be inside an else clause since the if above returns early

File: Client/Frontend/Browser/FaviconHandler.swift [hunk 2]
```diff
@@ -97,6 +101,10 @@ class FaviconHandler {
         favicon.width = Int(image.size.width)
         favicon.height = Int(image.size.height)
         
+        if let tab = tab, !tab.isPrivate {
+          webImageCache.cacheImage(image: image, data: data ?? Data(), url: url)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/FaviconHandler.swift]: `data ?? Data()` fallback is a bit weird, if there's no data wouldn't we have a an empty image? Maybe we should just guard against missing data at the top with the `guard let image = image` part

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
