### PR TITLE
Fix #7055: Enable Highest Quality Youtube Videos

### LINKED ISSUE #7055: Auto-upgrade of Youtube video resolution
### Description: 

When using the mobile version of the YouTube website in fullscreen mode, rotating the screen should upgrade the resolution from 360p to 720p.

At one point (late fall of 2022?) I believe this was working on Brave iOS but appears to have reverted back to the old way of handling YouTube video resolution.  

### Steps to Reproduce 
  1.  Play video on YouTube mobile website (notice resolution is set to Auto (360p in my case).
  2.  Enter fullscreen
  3.  Video resolution does not improve.

### Actual result: 

Video resolution stays at 360p.

### Expected result:

Video resolution should improve to 720p.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced.

### Brave Version: 1.48.1 (23.3.2.0)

- Can you reproduce this issue with the most recent build from TestFlight?
Don't have TestFlight.

- Can you reproduce this issue with the previous version of the current build from TestFlight?
Dont have TestFlight.

- Can you reproduce this issue with the current build from AppStore? 
Yes

### Website problems only:
- did you check with Brave Shields down? 
Yes

- did you check in Safari/Firefox (WkWebView-based browsers)? 
No, I only use Brave.

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Adds a preference to make Youtube render the highest quality videos by default.

This pull request fixes #7055

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Screenshots:
image
image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Shared/Extensions/URLExtensions.swift [hunk 1]
```diff
@@ -230,6 +230,12 @@ extension URL {
 
     return self
   }
+  
+  public var withoutFragment: URL {
```
Comment (iccub) [inline Sources/Shared/Extensions/URLExtensions.swift:234]: Can you add a unit test for it?

**Review by iccub — APPROVED** [review]
