### PR TITLE
Fix #6294: Bookmark import not working

### LINKED ISSUE #6294: Bookmark import not working
### Description: 
The iOS bookmarks import feature appears to be broken.

### Steps to Reproduce 
  1. Export bookmarks from Brave Desktop (or Chrome).
  2. Attempt to import the exported html file from step 1.

**Actual result:** 
The import fails.
image

**Expected result:**
Bookmarks are imported successfully.

**Reproduces how often:**
Easily reproduced

**Brave Version:** 
Version 1.43 (22.9.9.14)

**Device details:** 
iPhone SE (iOS 16.1)

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

While accessing document URL from UIDocumentPickerViewController to access the file startAccessingSecurityScopedResource should be called for that URL.

Given an NSURL created by resolving a bookmark data created with security scope, make the resource referenced by the url accessible to the process. When access to this resource is no longer needed the client must call stopAccessingSecurityScopedResource. Each call to startAccessingSecurityScopedResource must be balanced with a call to stopAccessingSecurityScopedResource (Note: this is not reference counted).

This pull request fixes #6294

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

- Add a website to Bookmarks
- Export the Bookmarks on the same phone to iCloud or otherwise
- Import Bookmarks

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift [hunk 1]
```diff
@@ -43,9 +43,22 @@ class BraveCoreImportExportUtility {
...
+      
+      self.importer.import(fromFile: nativePath, topLevelFolderName: Strings.Sync.importFolderName, automaticImport: true) { [weak self] state, bookmarks in
         guard let self = self, state != .started else { return }
-
+        
+        defer {
+          // Each call to startAccessingSecurityScopedResource must be balanced with a call to stopAccessingSecurityScopedResource
+          // (Note: this is not reference counted)
+          path.stopAccessingSecurityScopedResource()
+        }
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift:58]: Probably want to move this defer _above_ the `guard let ...` part

File: Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift [hunk 2]
```diff
@@ -78,9 +91,19 @@ class BraveCoreImportExportUtility {
...
+      guard path.startAccessingSecurityScopedResource() else {
+        return
+      }
+      
+      self.importer.import(fromFile: nativePath, topLevelFolderName: Strings.Sync.importFolderName, automaticImport: false) { [weak self] state, bookmarks in
         guard let self = self, state != .started else { return }
 
+        defer {
+          path.stopAccessingSecurityScopedResource()
+        }
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift:103]: Same as above

File: Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift [hunk 3]
```diff
@@ -190,7 +213,7 @@ extension BraveCoreImportExportUtility {
   func nativeURLPathFromURL(_ url: URL) -> String? {
     return url.withUnsafeFileSystemRepresentation { bytes -> String? in
       guard let bytes = bytes else { return nil }
-      return String(cString: bytes)
+      return String(cString: bytes)//.replacingOccurrences(of: " ", with: "%20").replacingOccurrences(of: "file://", with: "")
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift]: Comment needed?

Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift]: My bad sorry, we were testing something there forgot. 
Fix at https://github.com/brave/brave-ios/pull/6781/commits/e20fbcb4cc732f3fa86e81c4539d698fbe054c60

File: Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift (hunk 2 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift:103]: Fix at https://github.com/brave/brave-ios/pull/6781/commits/e20fbcb4cc732f3fa86e81c4539d698fbe054c60

File: Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift:58]: Fix at https://github.com/brave/brave-ios/pull/6781/commits/e20fbcb4cc732f3fa86e81c4539d698fbe054c60

**Review by kylehickinson — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
