### PR TITLE
Fix #3632: Refactor theme logic to use iOS 13 APIs

### LINKED ISSUE #1506: Browser Menus do not Respond to Light/Dark OS Theme Changes
### Description: 

Most menus inside Brave to do not respond to OS dark / light theme changes. 

From a technical perspective, this is an opportunity to clean up menu usage through out application and make parent -> child UI relationships more definitive.

When BVC gets a trait collection update (BVC responds correctly), it should be able to propagate an `applyTheme` update down to all presented VC's and children. This includes having a handle on settings, and all nested menus.

This also breaks the tight coupling we often have throughout the application where children often dismiss themselves (meaning they know how they are being presented).

### Steps to Reproduce 
  1. Make sure theme selection is "automatic"
  1. Open settings (or main menu / shields panel)
  2. Change the OS system theme
  3. Observe settings screen is not dynamically updated (also happens with other menus)

**Actual result:** 

Image of wrong colored main menu when theme changed
Image of wrong colored shield panel when theme changed

**Expected result:**

All menus should be styled correctly.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 

Related #1503

### LINKED ISSUE #1572: iOS 13 Dark mode auto switch
### Description: 

It appears if you switch between light and dark mode within Brave, tabs will be refreshed accordingly. However, if you have display set to “Auto” in Brave and switch between light & dark mode under iOS setting , tabs will not be refreshed and you need to manually relaunch the app.

This is quiet annoying if you have dark set to auto under iOS setting, which is my case. :slight_smile:

### Steps to Reproduce 
  1. Configure Display & Brightness to auto on Brave.
2.Switch dark mode under system setting in iOS

**Actual result:** 

**Expected result:**

Tabs are either locked to light or dark mode in brave, you have to manually to close and relaunch the app.

Brave Version( check About Brave):
1.12 (19.09.13.06)

Mobile Device details
iOS 13 iPhone XsMax

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced

### Additional Information
https://wetransfer.com/downloads/f26e644c6d433a61b84cbb5c1c0d0ecb20190923122432/d295c9

### LINKED ISSUE #1721: New tab strip retains dark/white theme when quick mode toggled via control center
### Description: 
New tab strip retains dark/white theme when quick mode toggled via control center

### Steps to Reproduce 
  1. Set device theme to dark/light
  2. Set browser theme to automatic
  3. Quick toggle between dark/light mode via control center
  4. New tab strip retains dark/light theme based on what device theme is set
  5. Open tab tray and switch back to tabs, resets the theme   

**Actual result:** 
Dark tab strip on iPad
image

White tab strip on iPhone
image

[Video record of the issue](https://github.com/brave/brave-ios/files/3740303/theme.zip)

**Expected result:**
Theme should adapt to change automatically

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #1722: Quick theme toggle doesn't update theme for download/history/bookmarks
### Description: 
Found while testing #1553. With Downloads/Bookmarks/History page open if you toggle theme from control center it doesn't update the theme for the page but updates the entire browser theme 

### Steps to Reproduce 
  1. Set browser to dark theme
  2. Open download/bookmarks/history
  3. Change theme via control center with downloads/bookmarks/history page opened
  4. Page remains on previous theme only updates when you close and reopen it

**Actual result:** 
Quick theme toggle doesn't update theme for download/history/bookmarks

**Expected result:**
Should update theme accordingly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.16.18)

**Device details:** 
Both iPhone and iPad with iOS 13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #1862: Closing a private tab  switches theme from dark to light
### Description: 
Closing a private tab causes theme to switch from dark to light

### Steps to Reproduce 
  1. Set device theme to dark
  2. Visit a site with link
  3. Long press on a link and open in a private tab
  4. Exit private tab
  5. Open normal tab again, theme is changed to light from dark even though device theme is still set to dark

**Actual result:** 
private_light

**Expected result:**
Not change theme when exiting private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.31.19)

**Device details:** 
iPhone 7+ (iOS 13.2)
iPhone XR (iOS 13.2)

**Website problems only:**
- did you check with Brave Shields down? N?A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### LINKED ISSUE #2053: Changing theme while ad notification causes weird theme issues
### Description: 
Changing theme via control center when an ad notification on screen causes theming issue on the browser. The only way to fix it is to remove the app from memory and relaunch

### Steps to Reproduce 
  1. Set device theme to dark
  2. Enable rewards and wait till you get an ad
  3. While ad is shown change theme via control center
  4. Clear browsing data after dismissing the notification 
  5. New tab has dark and white theme mixed
  6. Shields also has dark theme on both new tab and on page

**Actual result:** 
image
image
image

**Expected result:**
No theme issue 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.27.22)

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Possibly related to #2044

### LINKED ISSUE #2925: Cancel button is not hidden completely
### Description: 
Cancel button is not hidden completely. Reported by @bsclifton  as well 

### Steps to Reproduce 
 No proper steps to reproduce happens out of the blue 

**Actual result:** 

Page | NTP
-- | --
image | image

**Expected result:**
Should hide the button completely when URL is not highlighted

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent 

**Brave Version:** 
Not sure when it started but have seen this in the past on older builds as well

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### LINKED ISSUE #3180: Reduce font weight for info text in shields settings
### Description: 
Reduce font weight for info text in shields settings

### Steps to Reproduce 
  1. Install any build
  2. Open Global Shields settings 
  3. Get overwhelmed with the amount of text on the screen

**Actual result:** 
image

**Expected result:**
Proposed changes by @karenkliu 
image

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### LINKED ISSUE #3383: History window does not persist theme
### Description: 
Please see this report https://community.brave.com/t/the-history-window-is-white-instead-of-purple/211984/3

### Steps to Reproduce 
  1. Open the app in private browsing mode
  2. Open history panel

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #3632: Modernize theme application logic and introduce design system colors
Replace the `Themable` API with `UITraitCollection` related APIs to have more stable theming code and replace Firefox/legacy color palette colors with design system colors

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

Fixes #3632

Theme related bugs affected:

- Fixes #3383
- Fixes #2053
- Fixes #1862
- Fixes #1722
- Fixes #1721
- Fixes #1572
- Fixes #2925 
- Fixes #1506
- Fixes #3180

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Change dark mode on all parts of the UI to ensure things switch back and forth properly
- Verify you can still force a specific theme via settings and that all UI only shows colors for that theme
- Verify private mode toolbars are purple instead of the regular dark/light colors

**Known Issue**: The toolbar that appears above the keyboard when you focus a text box in a web page does not theme correctly. This is true even in the live version of the app, and seems to be an iOS specific bug. Haven't tested to determine which versions of iOS are affected.

## Screenshots:

There are many screenshots so they've been zipped into separate folders:

- [new-light.zip](https://github.com/brave/brave-ios/files/6437545/new-light.zip)
- [new-dark.zip](https://github.com/brave/brave-ios/files/6437546/new-dark.zip)
- [new-private.zip](https://github.com/brave/brave-ios/files/6437547/new-private.zip)

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveUI/Then.swift [hunk 1]
```diff
@@ -61,7 +61,7 @@ extension Then where Self: AnyObject {
   ///
   ///     let label = UILabel().then {
   ///       $0.textAlignment = .Center
-  ///       $0.appearanceTextColor = UIColor.blackColor()
+  ///       $0.textColor = UIColor.blackColor()
```
Comment (iccub) [inline BraveUI/Then.swift:64]: Can remove this code while we are at it

File: Client/Frontend/Brave Rewards/Transfer/WalletTransferExpiredViewController.swift [hunk 2]
```diff
@@ -20,7 +20,7 @@ class WalletTransferExpiredViewController: UIViewController, PopoverContentCompo
     )
     
     private let textLabel = UILabel().then {
-        $0.appearanceTextColor = .white
+        $0.textColor = .white
```
Comment (iccub) [inline Client/Frontend/Brave Rewards/Transfer/WalletTransferExpiredViewController.swift:23]: use design system value

File: Client/Frontend/Brave Today/Source List/FeedSourceListViewController.swift [hunk 3]
```diff
@@ -75,7 +75,7 @@ class FeedSourceListViewController: UITableViewController {
         tableView.estimatedRowHeight = UITableView.automaticDimension
         tableView.delegate = self
         tableView.dataSource = self
-        tableView.sectionIndexColor = BraveUX.braveOrange
+        tableView.sectionIndexColor = UIColor.braveOrange
```
Comment (iccub) [inline Client/Frontend/Brave Today/Source List/FeedSourceListViewController.swift]: UIColor not needed here?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -2786,10 +2766,11 @@ extension BrowserViewController: TabManagerDelegate {
                 }
             }
 
-            let newTheme = Theme.of(tab)
-            if previous == nil || newTheme != Theme.of(previous) {
-                applyTheme(newTheme)
-            }
+            // FIXME: Theme - Private Mode
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: comment

File: Client/Frontend/Browser/ButtonToast.swift [hunk 5]
```diff
@@ -57,7 +57,7 @@ class ButtonToast: Toast {
 
         if let imageName = imageName {
             let icon = UIImageView(image: UIImage(imageLiteralResourceName: imageName).template)
-            icon.tintColor = UIColor.Photon.white100
+            icon.tintColor = UIColor.white
```
Comment (iccub) [inline Client/Frontend/Browser/ButtonToast.swift]: `UIColor` can be removed

File: Client/Frontend/Browser/ButtonToast.swift [hunk 6]
```diff
@@ -67,7 +67,7 @@ class ButtonToast: Toast {
 
         let label = UILabel()
         label.textAlignment = textAlignment
-        label.appearanceTextColor = UIColor.Photon.white100
+        label.textColor = UIColor.white
```
Comment (iccub) [inline Client/Frontend/Browser/ButtonToast.swift]: `UIColor` can be removed

File: Client/Frontend/Browser/ButtonToast.swift [hunk 7]
```diff
@@ -82,7 +82,7 @@ class ButtonToast: Toast {
 
             descriptionLabel = UILabel()
             descriptionLabel?.textAlignment = textAlignment
-            descriptionLabel?.appearanceTextColor = UIColor.Photon.white100
+            descriptionLabel?.textColor = UIColor.white
```
Comment (iccub) [inline Client/Frontend/Browser/ButtonToast.swift]: UIColor can be removed

File: Client/Frontend/Browser/ButtonToast.swift [hunk 8]
```diff
@@ -94,8 +94,9 @@ class ButtonToast: Toast {
         if let buttonText = buttonText {
             let button = HighlightableButton()
             button.layer.cornerRadius = ButtonToastUX.toastButtonBorderRadius
+            button.layer.cornerCurve = .continuous
             button.layer.borderWidth = ButtonToastUX.toastButtonBorderWidth
-            button.layer.borderColor = UIColor.Photon.white100.cgColor
+            button.layer.borderColor = UIColor.white.cgColor
```
Comment (iccub) [inline Client/Frontend/Browser/ButtonToast.swift:99]: UIColor can be removed

File: Client/Frontend/Browser/DefaultBrowserIntroCalloutViewController.swift [hunk 9]
```diff
@@ -10,45 +10,36 @@ import BraveUI
 
 private let log = Logger.browserLogger
 
-class DefaultBrowserIntroCalloutViewController: UIViewController, Themeable {
+class DefaultBrowserIntroCalloutViewController: UIViewController {
     
     private let openSettingsButton = Button(type: .system).then {
         $0.setTitle(Strings.DefaultBrowserCallout.introOpenSettingsButtonText, for: .normal)
-        $0.backgroundColor = BraveUX.braveOrange
+        $0.backgroundColor = UIColor.braveOrange
```
Comment (iccub) [inline Client/Frontend/Browser/DefaultBrowserIntroCalloutViewController.swift]: UIColor can be removed, no more comments about it, maybe just search for `UIColor.` in the project and replace where possible

File: Client/Frontend/Browser/FindInPageBar.swift [hunk 10]
```diff
@@ -65,10 +61,10 @@ class FindInPageBar: UIView {
     override init(frame: CGRect) {
         super.init(frame: frame)
 
-        backgroundColor = .white
-
+        backgroundColor = .secondaryBraveBackground
+        
         searchText.addTarget(self, action: #selector(didTextChange), for: .editingChanged)
-        searchText.textColor = FindInPageUX.searchTextColor
+        searchText.textColor = .braveLabel
```
Comment (iccub) [inline Client/Frontend/Browser/FindInPageBar.swift:67]: This does not seem right, should be orange
`searchTextColor = UIColor.Photon.orange60`

File: Client/Frontend/Browser/FindInPageBar.swift [hunk 11]
```diff
@@ -79,35 +75,35 @@ class FindInPageBar: UIView {
         searchText.accessibilityIdentifier = "FindInPage.searchField"
         addSubview(searchText)
 
-        matchCountView.textColor = FindInPageUX.matchCountColor
+        matchCountView.textColor = .braveLabel
```
Comment (iccub) [inline Client/Frontend/Browser/FindInPageBar.swift]: I think all these text colors you updated in this class have to be audited, some are light gray or always black i think

File: Client/Frontend/Browser/New Tab Page/Sections/DuckDuckGoCalloutSectionProvider.swift [hunk 12]
```diff
@@ -65,16 +69,19 @@ class DuckDuckGoCalloutSectionProvider: NSObject, NTPObservableSectionProvider {
     
     private typealias DuckDuckGoCalloutCell = NewTabCenteredCollectionViewCell<DuckDuckGoCalloutButton>
     
+    var privateModeCancellable: AnyCancellable?
```
Comment (iccub) [inline Client/Frontend/Browser/New Tab Page/Sections/DuckDuckGoCalloutSectionProvider.swift]: can be private?

File: Client/Frontend/Browser/New Tab Page/Sections/DuckDuckGoCalloutSectionProvider.swift [hunk 13]
```diff
@@ -65,16 +69,19 @@ class DuckDuckGoCalloutSectionProvider: NSObject, NTPObservableSectionProvider {
...
-        NotificationCenter.default.addObserver(self, selector: #selector(privateModeChanged), name: .privacyModeChanged, object: nil)
-    }
-    
-    deinit {
-        NotificationCenter.default.removeObserver(self)
+        privateModeCancellable = PrivateBrowsingManager.shared
+            .$isPrivateBrowsing
+            .receive(on: RunLoop.main)
+            .sink(receiveValue: { [weak self] _ in
+                self?.privateModeChanged()
```
Comment (iccub) [inline Client/Frontend/Browser/New Tab Page/Sections/DuckDuckGoCalloutSectionProvider.swift:83]: Maybe remove `@objc` keyword from this method since we do not use selector observation anymore?

File: Client/Frontend/Browser/New Tab Page/Sections/NTPDefaultBrowserCalloutProvider.swift [hunk 14]
```diff
@@ -89,7 +89,8 @@ private class DefaultBrowserCalloutView: SpringButton, Themeable {
         
         clipsToBounds = true
         layer.cornerRadius = 8
-        backgroundColor = #colorLiteral(red: 0.8588235294, green: 0.9568627451, blue: 0.862745098, alpha: 1)
+        layer.cornerCurve = .continuous
+        backgroundColor = .braveSuccessBackground
```
Comment (iccub) [inline Client/Frontend/Browser/New Tab Page/Sections/NTPDefaultBrowserCalloutProvider.swift:93]: Does this translate well to what we've had before?

File: Client/Frontend/Shields/ShareTrackersController.swift [hunk 15]
```diff
@@ -176,11 +155,13 @@ private class ShareTrackersView: UIView, Themeable {
         $0.backgroundColor = .clear
         $0.setContentCompressionResistancePriority(.required, for: .horizontal)
         $0.numberOfLines = 0
+        $0.textColor = .white
```
Comment (iccub) [inline Client/Frontend/Shields/ShareTrackersController.swift:158]: This view should have non dynamic colors?

File: Client/Frontend/Sync/SyncCameraView.swift [hunk 16]
```diff
@@ -13,7 +13,6 @@ class SyncCameraView: UIView, AVCaptureMetadataOutputObjectsDelegate {
         let button = self.createCameraButton()
         button.setTitle(Strings.grantCameraAccess, for: .normal)
         button.tintColor = .white
-        button.appearanceTextColor = .white
```
Comment (iccub) [inline Client/Frontend/Sync/SyncCameraView.swift:16]: We do not set title color here?

File: Client/Frontend/Sync/SyncCodewordsView.swift [hunk 17]
```diff
@@ -10,16 +10,16 @@ class SyncCodewordsView: UIView, UITextViewDelegate {
         textView.autocapitalizationType = .none
         textView.autocorrectionType = .yes
         textView.font = UIFont.systemFont(ofSize: 18, weight: UIFont.Weight.medium)
-        textView.textColor = BraveUX.greyJ
-        textView.backgroundColor = .white
+        textView.textColor = .braveLabel
+        textView.backgroundColor = .braveBackground
```
Comment (iccub) [inline Client/Frontend/Sync/SyncCodewordsView.swift:14]: This has to be checked as well, white -> dynamic change

File: Client/Frontend/Widgets/SnackBar.swift [hunk 18]
```diff
@@ -23,21 +23,15 @@ class SnackButton: UIButton {
...
     init(title: String, accessibilityIdentifier: String, callback: @escaping SnackBarCallback) {
         self.callback = callback
 
         super.init(frame: .zero)
 
         setTitle(title, for: .normal)
         titleLabel?.font = DynamicFontHelper.defaultHelper.DefaultMediumFont
-        setTitleColor(SnackBarUX.highlightText, for: .highlighted)
-        setTitleColor(SettingsUX.tableViewRowTextColor, for: .normal)
+        setTitleColor(.braveOrange, for: .highlighted)
```
Comment (iccub) [inline Client/Frontend/Widgets/SnackBar.swift:33]: `highlightText = UIColor.Photon.blue60` seems to be blue not orange, unless we want to update it

File: Client/Frontend/Widgets/Themes/Theme.swift [hunk 19]
```diff
@@ -6,312 +6,35 @@ import Foundation
...
-                footer = UIColor(colorString: footerStr)
-                addressBar = UIColor(colorString: addressBarStr)
-            }
-
-            let home: UIColor
-            let header: UIColor
-            let footer: UIColor
-            let addressBar: UIColor
+enum DefaultTheme: String, RepresentableOptionType {
+    case system = "Z71ED37E-EC3E-436E-AD5F-B22748306A6B"
```
Comment (iccub) [inline Client/Frontend/Widgets/Themes/Theme.swift:10]: We leave these json files and Theme class?

File: Client/Frontend/Widgets/TwoLineCell.swift [hunk 20]
```diff
@@ -211,12 +211,13 @@ private class TwoLineCellHelper {
...
         }
 
-        textLabel.textColor = TwoLineCellUX.textColor
-        detailTextLabel.textColor = TwoLineCellUX.detailTextColor
+        textLabel.textColor = .braveLabel
+        detailTextLabel.textColor = .secondaryBraveLabel
         setupDynamicFonts()
 
         imageView.contentMode = .scaleAspectFill
         imageView.layer.cornerRadius = 6 // hmm
```
Comment (iccub) [inline Client/Frontend/Widgets/TwoLineCell.swift:219]: 🤔

**Review by iccub — COMMENTED** [review]
Love to see these changes.

Leaving random comments about using certain colors in certain places.

One thing we can consider to clean this up further is to replace `UIColor.xxx` with just `.xxx` in places that allow it.

I assume you did find/replace on `BraveUX -> UIColor` that's why some of it left

File: Client/Frontend/Widgets/Themes/Theme.swift (hunk 19 above)
Comment (kylehickinson) [reply Client/Frontend/Widgets/Themes/Theme.swift:10]: The JSON files were removed, but unfortunately I need to keep these UUID's for system/light/dark as they are the values that are saved in NSUserDefaults

File: Client/Frontend/Widgets/SnackBar.swift (hunk 18 above)
Comment (kylehickinson) [reply Client/Frontend/Widgets/SnackBar.swift:33]: Decided to update it to reflect Brave highlight/tint colors

File: Client/Frontend/Brave Rewards/Transfer/WalletTransferExpiredViewController.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Brave Rewards/Transfer/WalletTransferExpiredViewController.swift:23]: The background is a hard-coded gradient (non design system) which is why this uses a non-dynamic color

File: Client/Frontend/Browser/New Tab Page/Sections/NTPDefaultBrowserCalloutProvider.swift (hunk 14 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/New Tab Page/Sections/NTPDefaultBrowserCalloutProvider.swift:93]: Yeah I took the color that was hard-coded and compared it against this color and it matched

File: Client/Frontend/Shields/ShareTrackersController.swift (hunk 15 above)
Comment (kylehickinson) [reply Client/Frontend/Shields/ShareTrackersController.swift:158]: Should be OK because it uses a gradient bg

File: BraveUI/Then.swift (hunk 1 above)
Comment (kylehickinson) [reply BraveUI/Then.swift:64]: This is just documentation

File: Client/Frontend/Browser/ButtonToast.swift (hunk 8 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/ButtonToast.swift:99]: `UIColor` needs to remain on this one until CI can be updated to 12.5 (`.white.cgColor` not valid < 12.5)

File: BraveUI/Then.swift (hunk 1 above)
Comment (iccub) [reply BraveUI/Then.swift:64]: LOL

**Review by iccub — APPROVED** [review]
