### PR TITLE
Fix#2907: Clearing Browsing History should clear Tab History as well

### LINKED ISSUE #2907: Clearing Browsing history should clear tab history as well
### Description: 
Clearing Browsing history should clear tab history as well

### Steps to Reproduce 
  1. Visit sites in tabs
  2. Open settings and clear data
  3. Tab history is not cleared 

**Actual result:** 
Clearing Browsing history should clear tab history as well

**Expected result:**
Tab history should be cleared

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.20/1.21

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes
This pull request fixes #2907

- This PR makes changes to Tab History when Browsing History is cleared
- After clearing the browser history from settings, the tab history for every tab is also cleared.
- In addition the history data of the saved tabs is also cleared in order to achieve when the browser is reloaded it will not bring back the cleared history.
## Security Review
https://github.com/brave/security/issues/268

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Visit websites in different tabs or same tab
- Open settings - Navigate to Privacy - Clear Data for Browsing History
- Check the Tab History is also cleared

## Screenshots:

Issue:2907

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Tab.swift [hunk 1]
```diff
@@ -256,6 +256,23 @@ class Tab: NSObject {
...
+            webView.go(to: firstWebsite)
+        }
+        
+        guard let tabID = id else { return }
+        
+        // Remove the tab history from saved tabs
+        TabMO.removeHistory(with: tabID)
+        
+        // Clear backforward list
+        webView.backForwardList.perform(Selector(("_removeAllItems")))
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Tab.swift]: We'll probably have to obfuscate this otherwise we'll probably be dinged by app submission.

Also won't SwiftLint warn about using perform selector?

File: Client/Frontend/Browser/Tab.swift [hunk 2]
```diff
@@ -256,6 +256,23 @@ class Tab: NSObject {
         contentScriptManager.helpers.removeAll()
     }
     
+    func clearHistory(config: WKWebViewConfiguration) {
+        guard let webView = webView, let firstWebsite = webView.backForwardList.backList.first else { return }
+
+        // First we make sure the webview is on the earliest item in the history
+        if webView.canGoBack {
+            webView.go(to: firstWebsite)
+        }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Tab.swift]: Why would we force the user back to the first navigation item when they clear history?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Tab.swift (hunk 2 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Tab.swift]: Actually this is not needed, I was using to clear the backwardlist first, will remove

File: Client/Frontend/Browser/Tab.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Browser/Tab.swift]: i do not know about this private api if it's worth the risk, another option would be to just dump the webview and recreate it?

File: Client/Frontend/Browser/Tab.swift (hunk 2 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Tab.swift]: Unnecessary back navigation is removed

File: Client/Frontend/Browser/Tab.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Tab.swift]: The selector  usage is changed and method is obfuscated

File: Client/Frontend/Browser/Tab.swift [hunk 3]
```diff
@@ -256,6 +256,31 @@ class Tab: NSObject {
...
+        let allBase64Decoded = Data(base64Encoded: "QWxs", options: Data.Base64DecodingOptions(rawValue: 0))
+            .map({ String(data: $0, encoding: .utf8) }) ?? "" // "All" text in base64Decoded
+              
+        // Clear backforward list
+        let argument: [Any] = ["_", "r", "\u{65}", "mov", "\u{65}", // _remove
+                             "\(allBase64Decoded ?? "")", // All
+                             "It", "\u{65}", "ms"] // Items
+
+        let method = argument.compactMap { $0 as? String }.joined()
+        let selector: Selector = NSSelectorFromString(method)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Tab.swift]: I think this is still over the top a bit, also please add some comments around what private API we're using and why. Otherwise seems like this works, tested it and the UI reacts appropriately showing no back/forward options and restoring without the previous history either.

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Tab.swift (hunk 3 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Tab.swift]: Unnecessary obfuscation is removed and comments are added

**Review by iccub — CHANGES_REQUESTED** [review]
left feedback in DMs

**Comment by soner-yuksel** [comment]
> left feedback in DMs

Not Registering first entered URL problem is fixed and method is changed with "clear"

Creating the security ticket for review

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/Tab.swift [hunk 4]
```diff
@@ -256,6 +256,32 @@ class Tab: NSObject {
...
+        /*
+         * Clear selector is used on WKWebView backForwardList because backForwardList list is only exposed with a getter
+         * and this method Removes all items except the current one in the tab list so when another url is added it will add the list properly
+         * This approach is chosen to achieve removing tab history in the event of removing  browser history
+         * Best way perform this is to clear the backforward list and in our case there is no drawback to clear the list
+         * And alternative would be to reload webpages which will be costly and also can cause unexpected results
+         */
+        let argument: [Any] = ["_c", "lea", "r"]
+
+        let method = argument.compactMap { $0 as? String }.joined()
```
Comment (Brandon-T) [inline Client/Frontend/Browser/Tab.swift:277]: PR Looks good. This MIGHT not work if the optimizer is smart. If it is, this will get optimized back into a single string `_clear` and then get flagged by the automatic review for private methods :D 
Typically I base-64 encode the string and then decode it at runtime. But for now, leave it and let's see. Just adding a comment in case it does get rekt.

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/Tab.swift (hunk 4 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Tab.swift:277]: Actually I added extra [obfuscation](https://github.com/brave/brave-ios/pull/3089#discussion_r531745554) which includes base-64 encode and unicode encoding but we decided it is unnecessary.
But like you said let's see, we can put it back.

**Review by jumde — APPROVED** [review]
lgtm
