### PR TITLE
Fix #2185: `loadPersistentStore` crash.

### LINKED ISSUE #2185: CoreData loadPersistentStore crashes
### Steps to Reproduce 
 Can't reproduce on my devices

**Actual result:** 

Zrzut ekranu 2020-01-13 o 15 59 06

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
rare

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
Another blind guess of what is causing the crash. This doesn't change app logic at all, just attempt to initialize database container at earlier point.

This pull request fixes issue #2185 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Data/models/DataController.swift [hunk 1]
```diff
@@ -45,6 +45,13 @@ public class DataController: NSObject {
     public static var shared: DataController = DataController()
     public static var sharedInMemory: DataController = InMemoryDataController()
     
+    /// A possible hacky solution to prevent  #2185 crashes.
+    public func lazyInitialization() {
+        DispatchQueue.main.async {
```
Comment (Brandon-T) [inline Data/models/DataController.swift]: Does this require async? or can we call it in AppDelegate normally without the dispatch?

**Review by Brandon-T — APPROVED** [review]

File: Data/models/DataController.swift (hunk 1 above)
Comment (iccub) [reply Data/models/DataController.swift]: yeah, removed it
