### PR TITLE
Fix #593: Bookmark order migration

### LINKED ISSUE #593: Bookmarks reordering is messed up
### Description: 
Bookmarks reordering is messed up

### Steps to Reproduce 
  1. Add bookmarks and bookmarks folders in 1.6.6
  2. Upgrade to 1.7 (18.12.06.00)
  3. Go to edit mode in bookmarks, reorder them and see the magic
  4. Come out of edit mode and changes not saved

**Actual result:** 
https://drive.google.com/open?id=1jPVOtygsmuxmyQvR2-Qjb7MDy0n7VaSG

**Expected result:**
Reordering shouldn't mess up the bookmarks icon or folders

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.12.06.00)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [x] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

File: Client/Application/Migration.swift [hunk 1]
```diff
@@ -97,9 +97,14 @@ extension Preferences {
         // This needs to be translated to our new preference.
         Preferences.General.isFirstLaunch.value = Preferences.DAU.lastLaunchInfo.value == nil
         
+        // Core Data
+        
         // Migrate the shield overrides
         migrateShieldOverrides()
         
+        Bookmark.migrateOrder(forFavorites: true)
+        Bookmark.migrateOrder(forFavorites: false)
```
Comment (kylehickinson) [inline Client/Application/Migration.swift:106]: I get why this is like this but it still looks weird to me :)

**Comment by jhreis** [comment]
Does this handle new bookmarks being added? 
Or like new user installs 1.7 freshly, and adds 5 bookmarks, looks like they would all still have `0` `order`, right? (maybe this was fixed in past PR?)

**Comment by iccub** [comment]
https://github.com/brave/brave-ios/pull/602/files#diff-01f57e7d7609dba0eec131782b05f57dR218 we add order on insert

**Review by jhreis — APPROVED** [review]
