### PR TITLE
Fix #5588: Add padding to Brave Search promo cell on iOS 14.

### LINKED ISSUE #5588: Brave search promotion cell padding needs adjustment [iOS 14]
### Description: 
Minor ui issue when the `brave search promotional cell` is displayed on iOS 14. The section headings are highlighted on version 14 so it seems like there's no padding between `On The Page` section and the `brave search promotion cell`

Actual
iOS 14 | iOS 14 | iOS 15
-|-|-
IMG_2719 | IMG_2720 | IMG_3148

### Steps to Reproduce 
  1. Clean install
  2. Navigate to settings > search engine > set to bing
  3. navigate to brave.com
  4. type `brave` in search field in same tab
  5. Observe search suggestions

**Expected result:**
on iOS 14, there should be some padding between the search suggestion section header and the cell.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.40 (22.6.24.14)

**Device details:** 
iPhone X | iOS 14.4.2

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #5588 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

Zrzut ekranu 2022-06-27 o 16 13 16

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift [hunk 1]
```diff
@@ -108,8 +108,15 @@ class BraveSearchPromotionCell: UITableViewCell {
...
       $0.leading.equalTo(safeArea.leading).inset(8)
       $0.trailing.equalTo(safeArea.trailing).inset(8)
-      $0.top.equalTo(safeArea.top)
-      $0.bottom.equalTo(safeArea.bottom)
+      
+      if #available(iOS 15, *) {
+        $0.top.equalTo(safeArea.top)
+        $0.bottom.equalTo(safeArea.bottom)
+      } else {
+        // iOS 14 table headers look different, solid color, adding small inset to make it look better.
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift:116]: Wouldn't it be better to remove the solid colour (as well as add insets)?
 
I assume the extra spacing on 15 is coming from [`sectionHeaderTopPadding`](https://developer.apple.com/documentation/uikit/uitableview/3750914-sectionheadertoppadding)

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift:116]: Missed this comment, thanks github notifications!
Followup ticket https://github.com/brave/brave-ios/issues/5608
