### PR TITLE
Fix #2539: Super Referrer Improvements (Clipboard)

### LINKED ISSUE #2539: Super Referrer Improvements (Clipboard)
### Description: 

To improve installation metrics, implement clipboard inspection for new referral code detection.

### Steps to Reproduce 

This change is to allow referral codes to be read from the clipboard.

The general tech flow is:

Open Brave
- If first time, read clipboard
- If clipboard matches a predefined prefix, read the associated code that follows (e.g. ABC123)
- Use this ref code, instead of asking the server
- Previously we used /ua endpoint (which provided a ref-code), in this case we will be using /nonua endpoint (but only if a ref-code is found)

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by jhreis**
## Summary of Changes

This pull request fixes #2539

## Review Notes:

This change is to allow referral codes to be read from the clipboard.

The general tech flow is:

- Open Brave
- If first time, read clipboard
- If clipboard matches a predefined prefix, read the associated code that follows (e.g. `ABC123`)
- Use this ref code, instead of asking the server
- Previously we used `/ua` endpoint (which provided a ref-code), in this case we will be using `/nonua` endpoint (but only if a ref-code is found)

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

#### Clipboard Identification Verification
1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993` followed by a single character (either `:` or `/`) and then the specific ref code (e.g. ABC123) from the referral
1. So full out put would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Download Brave through TF
1. Disable internet (this makes sure the fallback is not activated if clipboard fails for some reason)
1. Open Brave
1. Since no internet connection, no custom assets, but ref code should still be shown inside the settings page
1. If the ref code shows here, this is a successful test

#### Clipboard Full Test
1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993` followed by a single character (either `:` or `/`) and then the specific ref code (e.g. ABC123) from the referral
1. So full out put would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Download Brave through TF
1. Open Brave
1. Verify that correct ref code shows up in settings / on server
1. Verify assets are shown on the home page
1. Verify favorites show the referral’s custom favs

#### Fallback to Standard System
1. Referral should still work, even if clipboard approach fails, this tests that condition:
1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993` followed by a single character (either `:` or `/`) and then the specific ref code (e.g. ABC123) from the referral
1. So full output would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Copy a random string (e.g. “chocolate and coffee”)
1. Re-paste the clipboard to verify the new string is _not_ the referral string
1. Download Brave through TF
1. Open Brave
1. Verify that correct ref code shows up in settings / on server
1. Verify assets are shown on the home page
1. Verify favorites show the referral’s custom favs

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 1]
```diff
@@ -180,6 +187,19 @@ public class UserReferralProgram {
...
     }
     
+    /// Passing string, attempts to derive a ref code from it.
+    /// Uses very strict matching.
+    /// Returns the sanitized code, or nil if no code was found
+    public class func sanitize(input: String?) -> String? {
+        guard var input = input, input.hasPrefix(self.clipboardPrefix) else { return nil }
+        
+        input.removeFirst(self.clipboardPrefix.count + 1)
+        // Add any other potential validation here, e.g. validating the actual ref code string
```
Comment (jumde) [inline BraveShared/Analytics/UserReferralProgram.swift]: https://docs.google.com/document/d/15oSBC-57OpLO3pZK_XjHa1SwIjnjuxA8Wi74K5ZaxPc/edit?disco=AAAAJWaIrNI - `[0-9A-Z]{6}` should work

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 2]
```diff
@@ -78,6 +79,12 @@ public class UserReferralProgram {
             
             completion(nil)
         }
+        
+        if let refCode = refCode {
+            Preferences.URP.referralCode.value = refCode
```
Comment (kylehickinson) [inline BraveShared/Analytics/UserReferralProgram.swift:88]: This pref is not new right? Is this the only place we can set this?

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 3]
```diff
@@ -180,6 +187,19 @@ public class UserReferralProgram {
         return nil
     }
     
+    /// Passing string, attempts to derive a ref code from it.
+    /// Uses very strict matching.
+    /// Returns the sanitized code, or nil if no code was found
+    public class func sanitize(input: String?) -> String? {
+        guard var input = input, input.hasPrefix(self.clipboardPrefix) else { return nil }
+        
+        input.removeFirst(self.clipboardPrefix.count + 1)
```
Comment (kylehickinson) [inline BraveShared/Analytics/UserReferralProgram.swift:207]: Understand this probably set in a spec somewhere, but maybe a comment about why `+ 1`?

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 4]
```diff
@@ -180,6 +187,19 @@ public class UserReferralProgram {
...
+        // Add any other potential validation here, e.g. validating the actual ref code string
+        
+        if input.isEmpty { return nil }
+        return input
```
Comment (Brandon-T) [inline BraveShared/Analytics/UserReferralProgram.swift]: We can do `!input.isEmpty ? input : nil`

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 1 above)
Comment (Brandon-T) [reply BraveShared/Analytics/UserReferralProgram.swift]: The ref code is guaranteed to be 6 upper-case, 0-9 codes?

Comment (BrendanEich) [reply BraveShared/Analytics/UserReferralProgram.swift]: Refcode must be ABC123 format, 3 uppercase alphabetic and 3 decimal digits.

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 3 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift:207]: Nah, lol, yeah, will do!

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 2 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift:88]: Not new, and no. This only gets set for ref codes passed in via clipboard. 
I'll add comment here too.

It also gets set if the server passes down a ref code.

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 5]
```diff
@@ -16,6 +16,7 @@ public class UserReferralProgram {
     public static let shared = UserReferralProgram()
     
     private static let apiKeyPlistKey = "API_KEY"
+    private static let clipboardPrefix = "F83AB73F-9852-4F01-ABA8-7830B8825993"
```
Comment (kylehickinson) [inline BraveShared/Analytics/UserReferralProgram.swift:19]: Would we maybe want to place this at build time/in PLIST or maybe even pull from servers? Or do we expect this to not change ever

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 4 above)
Comment (jumde) [reply BraveShared/Analytics/UserReferralProgram.swift]: Need to clear the clipboard when a match is found.

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 1 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift]: @jumde Please finalize this on the spec first.

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 4 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift]: We clear elsewhere. Will update @Brandon-T but not with the double negative 😄 
`input.isEmpty ? nil : input`

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 5 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift:19]: Very unlikely to change, as would require changes to our partner landing pages. I did verify that no sec concerns with this. If you think better elsewhere I can remove. It could just as well be something like `Brave_Referral_Partnership`, was requested to make it something super random though.

File: BraveShared/Analytics/UrpService.swift [hunk 6]
```diff
@@ -33,16 +37,24 @@ struct UrpService {
...
+        var params = [UrpService.ParamKeys.api: apiKey]
+            
+        var lastPathComponent = "ua"
+        if let refCode = refCode {
+            params[UrpService.ParamKeys.referralCode] = refCode
+            params[UrpService.ParamKeys.platform] = "ios"
+            lastPathComponent = "nonua"
+        }
+        
+        endPoint.appendPathComponent("promo/initialize/\(lastPathComponent)")
```
Comment (iccub) [inline BraveShared/Analytics/UrpService.swift]: could chain `appendPathComponent` here instead of hardcoding forward slashes. I know it was like that in previous implementation, it was my code I bet lol

**Review by iccub — APPROVED** [review]

**Review by jumde — APPROVED** [review]
lgtm

File: BraveShared/Analytics/UrpService.swift (hunk 6 above)
Comment (jhreis) [reply BraveShared/Analytics/UrpService.swift]: Updated, take a look :)

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 1 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift]: Updated regex per spec.

File: BraveShared/Analytics/UrpService.swift (hunk 6 above)
Comment (iccub) [reply BraveShared/Analytics/UrpService.swift]: looks less URL-y but it's safer, thanks :D

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 7]
```diff
@@ -181,6 +190,20 @@ public class UserReferralProgram {
...
     
+    /// Passing string, attempts to derive a ref code from it.
+    /// Uses very strict matching.
+    /// Returns the sanitized code, or nil if no code was found
+    public class func sanitize(input: String?) -> String? {
+        guard var input = input, input.hasPrefix(self.clipboardPrefix) else { return nil }
+        
+        // +1 to strip off `:` that proceeds the defined prefix
+        input.removeFirst(self.clipboardPrefix.count + 1)
+        let valid = input.range(of: #"\b[A-Z]{3}[0-9]{3}\b"#, options: .regularExpression) != nil // true
```
Comment (kylehickinson) [inline BraveShared/Analytics/UserReferralProgram.swift]: Leftover `// true` comment? 😄

File: Client/Application/Delegates/AppDelegate.swift [hunk 8]
```diff
@@ -258,9 +258,13 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
...
             profile?.searchEngines.regionalSearchEngineSetup()
         }
+        
         if let urp = UserReferralProgram.shared {
             if isFirstLaunch {
-                urp.referralLookup { referralCode, offerUrl in
+                let refCode = UserReferralProgram.sanitize(input: UIPasteboard.general.string)
+                if refCode != nil { UIPasteboard.general.clearPasteboard() }
+                
+                urp.referralLookup(refCode: refCode) { referralCode, offerUrl in
```
Comment (kylehickinson) [inline Client/Application/Delegates/AppDelegate.swift:267]: If this call fails for some reason (spotty internet, loss of connection, server went down, etc.), I assume we don't have any retry logic? Given that we clear out the pasteboard and don't save the parsed ref code

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 9]
```diff
@@ -181,6 +190,20 @@ public class UserReferralProgram {
...
     }
     
+    /// Passing string, attempts to derive a ref code from it.
+    /// Uses very strict matching.
+    /// Returns the sanitized code, or nil if no code was found
+    public class func sanitize(input: String?) -> String? {
+        guard var input = input, input.hasPrefix(self.clipboardPrefix) else { return nil }
+        
+        // +1 to strip off `:` that proceeds the defined prefix
+        input.removeFirst(self.clipboardPrefix.count + 1)
```
Comment (Brandon-T) [inline BraveShared/Analytics/UserReferralProgram.swift:207]: If `input` is exactly the same length as `clipboardPrefix`, then removing `count + 1` is undefined behaviour and could potentially cause a crash.

> The number of elements to remove from the collection. k must be greater than or equal to zero and must not exceed the number of elements in the collection.

We can add to the guard statement that `input.count > self.clipboardPrefix.count + 1`
Is it possible that the ref-code after the prefix could potentially be blank? I'm not sure, but I think some people might try to manipulate it :D

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 7 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift]: lol, yup, used for testing in a playground, thanks for pointing out.

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 9 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift:207]: Good catch, thanks @Brandon-T

File: Client/Application/Delegates/AppDelegate.swift (hunk 8 above)
Comment (jhreis) [reply Client/Application/Delegates/AppDelegate.swift:267]: We actually do save it before the network request here: https://github.com/brave/brave-ios/pull/2535/files#diff-60f6d7911cf19ceb7bcfcde55f9bc740R87
And the network request should be re-attempted, if onboarding not completed, and we pull from prefs to use the actual referral code. I will add a comment there to help clarify.

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 9 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift:207]: I added a unit test to cover this too, thanks for pointing out.

**Review by kylehickinson — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]

**Comment by iccub** [comment]
Merging despite CI failing, it fails due to ipad simulator not launching fast enough for WKWebView UA test
