### PR TITLE
Fix #8100: Use proper ad-block components

### LINKED ISSUE #8100: Use proper components for ad-block (reflecting brave-core changes)
### Description: 
Adds changes related to brave-core updates here: https://github.com/brave/brave-browser/issues/32799

Test strategy:
1. Ensure settings prior to upgrade are remembered after the upgrade
2. Test some general ad-blocking [here](https://test-pages.privacytests.org/tracking_content.html)
3. Test cosmetic filtering [here](https://dev-pages.brave.software/filtering/cosmetic-filtering.html)
4. Test scriplets [here](https://dev-pages.brave.software/filtering/scriptlets.html)
5. ~~Test some filter lists [here](https://dev-pages.brave.software/filtering/additional-lists.html)~~ (This test seems to broken)
6. ~~Test network blocking [here](https://dev-pages.brave.software/filtering/network-requests.html)~~ (This test seems to be broken)

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #8100

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

See issue for STR

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/WebFilters/FilterListResourceDownloader.swift [hunk 1]
```diff
@@ -40,23 +40,27 @@ public actor FilterListResourceDownloader {
...
+       ), FileManager.default.fileExists(atPath: resourcesFolderURL.path) {
+      let resourcesInfo = await didUpdateResourcesComponent(folderURL: resourcesFolderURL)
+      async let startedCustomFilterListsDownloader: Void = FilterListCustomURLDownloader.shared.startIfNeeded()
+      async let cachedFilterLists: Void = compileCachedFilterLists(resourcesInfo: resourcesInfo)
+      async let compileDefaultEngine: Void = compileDefaultEngine(defaultFilterListFolderURL: defaultFilterListFolderURL, resourcesInfo: resourcesInfo)
+      _ = await (startedCustomFilterListsDownloader, cachedFilterLists, compileDefaultEngine)
+    } else if let legacyComponentFolderURL = await FilterListSetting.makeFolderURL(
+      forFilterListFolderPath: Preferences.AppState.lastLegacyDefaultFilterListFolderPath.value
+    ), FileManager.default.fileExists(atPath: legacyComponentFolderURL.path) {
+      // TODO: @JS Remove this after this release. Its here just so users can upgrade without a pause to their adblocking
```
Comment (iccub) [inline Sources/Brave/WebFilters/FilterListResourceDownloader.swift:57]: what does it mean `after this release`?

**Review by iccub — APPROVED** [review]

File: Sources/Brave/WebFilters/FilterListResourceDownloader.swift (hunk 1 above)
Comment (cuba) [reply Sources/Brave/WebFilters/FilterListResourceDownloader.swift:57]: oh its just temporary code that we can remove next version.
