### PR TITLE
Fix #459: New non-selected tabs will correctly show https padlock

### LINKED ISSUE #459: Open link in a new tab doesn't show https padlock
### Description: 
Open link in a new tab doesn't show https padlock

### Steps to Reproduce 
  1. Open a site in a new tab
  2. Long press on a https link and open in a new tab
  3. Switch to the newly opened tab, URL bar doesn't show the green padlock before URL
  4. Reload the page, padlock appears

**Actual result:** 
Open link in a new tab doesn't show https padlock

**Expected result:**
Should always show the padlock for https sites when loaded

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Some what easy but when you try to record follows Sods law and never happens

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc: @tomlowenthal @jumde @diracdeltas

### PR DESCRIPTION
**Pull request by kylehickinson**
Problem was that the two observed properties of the `Tab`'s webview (`hasOnlySecureContent` and `serverTrust`) only set the `Tab.contentIsSecure` if the tab's webView was the selected tab, where it should only be _updating the url bar_ if its the selected tab.

## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

_None included_

## Notes for testing this patch

_None included_

### CODE REVIEW

**Review by jhreis — COMMENTED** [review]
Can't we just _always_ call `self.updateURLBar(forTab: tab)` as it is okay to update a tab that is not currently the `selectedTab`?

**Comment by kylehickinson** [comment]
@jhreis We can update the `Tab` object but we can't update the URL bar to display said tab unless its the selected tab, otherwise the URL bar would show a different URL for instance.

See: https://github.com/brave/brave-ios/blob/development/Client/Frontend/Browser/BrowserViewController.swift#L981

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -913,22 +913,26 @@ class BrowserViewController: UIViewController {
...
+            guard let tab = tabManager[webView] else {
                 break
             }
             
             if tab.contentIsSecure && !webView.hasOnlySecureContent {
                 tab.contentIsSecure = false
             }
             
-            updateURLBar(forTab: tab)
+            if tab === tabManager.selectedTab {
```
Comment (danishjafri88) [inline Client/Frontend/Browser/BrowserViewController.swift]: Can't we create a nested function for doing this? Exact code is repeated thrice

**Review by danishjafri88 — CHANGES_REQUESTED** [review]

**Review by danishjafri88 — APPROVED** [review]
