### PR TITLE
Start loading ad-block early and add wait later

### LINKED ISSUE #6461: Startup time increased after 1.45.* update
### Description: 
Before 1.45 update, Brave was the fastest browser. Now it takes much more time to load the application. 

### Steps to Reproduce 
  1. Open Brave Browser on iOS.

**Actual result:** 
Brave is loading fast. Even faster than Safari.

**Expected result:**
Brave is loading slower. And 2x slower, than Safari,

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Often, but looks like not every time. 

**Brave Version:** 
1.45.1 (22.11.17.19)

**Device details:** 
iPhone 11, iOS 16.1.1

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes
I hope this will have some improvements of the Adblock engine loading times
The basic principle here is to load the engine as early as possible and to do the wait as late as possible so the perceived time is insignificant. So far I've had some good results on my tests where even if I remove the wait the engine is ready before the first page loads. Yes even the engine YouTube script is ready on time.

This pull request fixes #6461 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — CHANGES_REQUESTED** [review]
Please remove the refactor commit that is unrelated to the adblock engine performance

**Comment by cuba** [comment]
@kylehickinson done

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -230,11 +220,16 @@ extension BrowserViewController: WKNavigationDelegate {
        navigationAction.targetFrame?.isMainFrame == true,
        let redirectURL = WebsiteRedirects.redirect(for: url) {
       
-      decisionHandler(.cancel, preferences)
       tab?.loadRequest(URLRequest(url: redirectURL))
-      return
+      return (.cancel, preferences)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: This technically changes the order of execution, can we make sure that this change hasn't broken anything?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 2]
```diff
@@ -270,9 +265,6 @@ extension BrowserViewController: WKNavigationDelegate {
         
         // Once we check the redirect chain only need the last (final) url from our redirect chain
         if let redirectURL = redirectChain.last?.url {
-          // Cancel the original request. We don't want it to load as it's tracking us
-          decisionHandler(.cancel, preferences)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:274]: Same here

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 1 above)
Comment (cuba) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: I tried it for debouncing and it's fine. However if we go for async await we would have to do this change regardless.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 2 above)
Comment (cuba) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:274]: This one I tested it was working correctly

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 1 above)
Comment (cuba) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: So I tested this and it works just fine (back, forward works just fine too)

Comment (cuba) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: Do you think it would make sense to wrap the `loadRequest` in a `Task { @MainThread in }` just in case

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: Hopping it to next runtime loop would be closer to what we have now but probably unnecessary if it was tested and working

**Review by kylehickinson — APPROVED** [review]

**Comment by cuba** [comment]
This PR doesn't fully improve the engine speed loads. I will merge another PR on top of this before merging that one. The other PR will have its own review
