### PR TITLE
Fix #7692: Fix performance issues with cosmetic filters

### LINKED ISSUE #7692: Web compat issues on youtube when scrolling/reloading page [iPad]
### Description: 
Web compat issues on youtube when scrolling/reloading page [iPad]

Related to: https://github.com/brave/brave-ios/issues/7655

### Steps to Reproduce 
  1. Install 1.52.x
  2. Navigate to youtube.com
  3. Play some videos, scroll through the comments/related videos
  4. Try reloading the page and adding video to playlist and then return from playlist

### Actual result: 
Content fails to load/starts to freeze up

### Expected result:
Content should load and navigation should be fluid

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  Any 1.52.x

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPadOS

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #7692

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

1. Check STR in issue
2. Go to sites like reddit.com and ensure cookie consent and open in app notifications are blocked (Make sure the appropriate filter lists are enabled)
3. Go to theverge.com and ensure that the cookie notices are blocked
4. Go to https://dev-pages.brave.software/filtering/cosmetic-filtering.html and click run test: on aggressive all images are hidden, on standard only 3rd party images are hidden
5. Enable a VPN and ensure you're in the USA. Search for trezor: on standard mode AdBeta appears, on aggressive it does not (it takes a moment to hide the ad).

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 1]
```diff
@@ -683,27 +715,30 @@ window.__firefox__.execute(function($) {
...
-    if (!changes) { return }
-    setRulesOnStylesheet()
+    // Send any found selectors to the browser
+    sendPendingSelectorsThrottled()
 
-    if (!args.hideFirstPartyContent) {
-      pumpCosmeticFilterQueuesOnIdle()
+    if (switchToMutationObserverAtTime !== undefined &&
+      window.Date.now() >= switchToMutationObserverAtTime) {
+      useMutationObserver('CALLBACK')
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: This function doesn't accept any parameters. Why do we pass this string as a parameter?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 1 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Sorry I was adding some logs for testing and accidentally merged it. Ill fix it

Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Done

**Review by iccub — CHANGES_REQUESTED** [review]
blocking merging until the ads blocking team reviews and approves it

**Review by Brandon-T — APPROVED** [review]

**Review by pes10k — APPROVED** [review]

**Review by iccub — APPROVED** [review]
