### PR TITLE
Fix #7952: Opening link in private tab will bypass biometrics authentication

### LINKED ISSUE #7952: Opening link in private tab will bypass biometrics authentication
### Description: 
Opening link in private tab will bypass biometrics authentication

There are 2 use cases to investigate

**Case 1**: Opening link in private tab from context menu. 
**Case 2**: Opening a link in new private window mode. This only pertains to iPad since iPhone does not support this. Such a context menu is available on webpage when long pressing on link. 

### Steps to Reproduce 
  1. Install 1.57.x
  2. Open menu and scroll down to the `TABS` section
  3. Tap on Private Tabs Settings
  4. Enable `Require Face ID` for Private tabs
  5. Return to NTP
  6. Long press on favorite, select `Open in New Private Tab`
  7. Observe tab mode switch

### Actual result: 

https://github.com/brave/brave-ios/assets/17885425/3a4eb183-6b0e-4aff-8086-3b1b35116a60

### Expected result:
Should require biometrics authentication like when switch to private mode from tab view.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  `1.57 (23.8.24.17)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No (new feature)

### Device details: 
iPhone X, 16.5.1
iPad, 16.5.1

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

The conditions of opening in private tab is handled

* Context menu open in private tab
* Context menu open in private window
* Playlist context menu open in new private tab
* Playlist share open in new private tab
* NTP favourite open in new private tab
* NTP favourite show more open in private tab
* Bookmarks open in a new private tab
* History open in new private tab
* Bottom bar long press middle icon action open in new private tab
* News open in new Private tab 

This pull request fixes #7952

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
The test plan is determined in the ticket

### Context menu open in private tab - Context menu open in private window

https://github.com/brave/brave-ios/assets/6643505/207f5b0d-9caf-4a75-b46e-85c5ce406eb4

### Playlist context menu open in private tab - Playlist share open in private tab

https://github.com/brave/brave-ios/assets/6643505/86ee8d8a-6f08-45df-a843-28a7970c25a5

### NTP favourite open in private new tab - NTP favourite show more open in new private tab

https://github.com/brave/brave-ios/assets/6643505/a895d62e-529a-41b4-938b-72e37b67f263

### Bookmarks open in a new private tab

https://github.com/brave/brave-ios/assets/6643505/3b12509f-4c4e-4987-b9e6-9470d6cbd690

### History open in new private tab

https://github.com/brave/brave-ios/assets/6643505/99ccb51a-7172-4915-97cf-1b2ae7add9b9

###  Bottom bar long press middle icon action open in new private tab

https://github.com/brave/brave-ios/assets/6643505/37698fe7-54ff-484c-97e3-cbb961f15b49

### News open in new private tab

https://github.com/brave/brave-ios/assets/6643505/b36ab458-0bf6-4765-baef-a8010b87ae20

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2987,11 +2987,23 @@ extension BrowserViewController: NewTabPageDelegate {
...
+        self.askForLocalAuthentication { [weak self] success, error in
+          if success {
+            self?.navigateToInput(
+              url,
+              inNewTab: inNewTab,
+              switchingToPrivateMode: switchingToPrivateMode
+            )
+          }
+        }
+      } else {
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/BrowserViewController.swift]: I'm confused by this logic (and the rest below): Why are we asking for auth without checking `switchingToPrivateMode` before?

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift]: Yes because of the result of Auth we will let them switch or not. This is the requested logic, it is like this for tab tray also.

Comment (kylehickinson) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift]: Right but wouldn't this display an auth request to a user who is simply opening a new tab in general since you don't verify that the new tab is opening in a private tab first?

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift]: No because this logic is only added to the actions opening private tab when user is in private mode.

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift]: I tested every action one by one hopefully didn't miss anything here but I will warn QA about to test all the actions mentioned in PR not just ticket.

Comment (kylehickinson) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift]: I just tested this and this logic is bugged:

1. Turn on Private Browsing Lock
2. Long press a favourite and choose "Open in New Tab"
3. See auth lock

Because you don't check `switchingToPrivateMode` along with whether or not private lock is on along with if you're already private browsing and if the pref is on

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift]: Ok got it, I will check all the actions here again with both of the modes and correct mistakes.

File: Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift [hunk 2]
```diff
@@ -624,11 +624,23 @@ class NewTabPageViewController: UIViewController {
           completion: { _ in }
         )
       }
-      delegate?.navigateToInput(
-        url.absoluteString,
-        inNewTab: inNewTab,
-        switchingToPrivateMode: switchingToPrivateMode
-      )
+      if tab?.isPrivate == false, Preferences.Privacy.privateBrowsingLock.value {
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: Missing `switchingToPrivateMode` check here as well

File: Sources/Brave/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 3]
```diff
@@ -358,7 +358,15 @@ extension FavoritesViewController: UICollectionViewDelegateFlowLayout {
...
-              self.action(bookmark, .opened(inNewTab: true, switchingToPrivateMode: true))
+              if Preferences.Privacy.privateBrowsingLock.value {
+                self.askForLocalAuthentication { [weak self] success, error in
+                  if success {
+                    self?.action(bookmark, .opened(inNewTab: true, switchingToPrivateMode: true))
+                  }
+                }
+              } else {
+                self.action(bookmark, .opened(inNewTab: true, switchingToPrivateMode: true))
+              }
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/Favorites/FavoritesViewController.swift]: This is technically duplicated logic. The action here calls `self?.action(...)` which hits the `handleFavoriteAction` method you added the auth check to already. You can delete either this one or that, this one probably makes more sense to keep since its a direct action

File: Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift [hunk 4]
```diff
@@ -173,7 +174,15 @@ extension PlaylistListViewController: UITableViewDelegate {
...
-              self?.openInNewTab(currentItem, isPrivate: true)
+              if !isPrivateBrowsing, Preferences.Privacy.privateBrowsingLock.value {
+                self?.askForLocalAuthentication { [weak self] success, error in
+                  if success {
+                    self?.openInNewTab(currentItem, isPrivate: true)
+                  }
+                }
+              } else {
+                self?.openInNewTab(currentItem, isPrivate: true)
+              }
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift]: There's an additional action to open in a new private tab in playlist by table view context menu: https://github.com/brave/brave-ios/blob/15743fea2949291b5a167853c4b6b86d3e312643/Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController%2BTableViewDelegate.swift#L270

You may want to unify these to call one shared method

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift]: Fixed at https://github.com/brave/brave-ios/pull/7959/commits/68dbdac411e43999da1077d4dc34a50e45e5d03c

Thanks for checking in detail for this

File: Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift (hunk 2 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: Fixed at https://github.com/brave/brave-ios/pull/7959/commits/68dbdac411e43999da1077d4dc34a50e45e5d03c

File: Sources/Brave/Frontend/Browser/Favorites/FavoritesViewController.swift (hunk 3 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/Favorites/FavoritesViewController.swift]: Fixed at https://github.com/brave/brave-ios/pull/7959/commits/68dbdac411e43999da1077d4dc34a50e45e5d03c

File: Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift (hunk 4 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift]: Fixed at https://github.com/brave/brave-ios/pull/7959/commits/68dbdac411e43999da1077d4dc34a50e45e5d03c

**Comment by soner-yuksel** [comment]
All scenarios are tested after the changes and there is video uploaded in description for all of them

File: Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift [hunk 5]
```diff
@@ -250,7 +264,7 @@ extension PlaylistListViewController: UITableViewDelegate {
                 UIAction(
                   title: Strings.PlayList.sharePlaylistOpenInNewTabTitle, image: UIImage(systemName: "plus.square.on.square"),
                   handler: { [weak self] _ in
-                    self?.openInNewTab(currentItem, isPrivate: false)
+                    self?.openInPrivateTabWithAuthentication(currentItem)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift]: This is the wrong action, you want the one just below this (`Strings.PlayList.sharePlaylistOpenInNewPrivateTabTitle`)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift (hunk 5 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift]: Missed the testing that action sorry from table context menu, it is fixed with https://github.com/brave/brave-ios/pull/7959/commits/6450920c972b039742a2dbde1964b8ead3b45f34

**Review by kylehickinson — APPROVED** [review]
