### PR TITLE
Fix #4237: Resume Playlist Playback when AudioSession interrupted

### LINKED ISSUE #4237: When a phone call comes through, Playlist stops playing and never resumes
### Description: 
- When a phone call comes through, Playlist stops playing and never resumes
- Playlist needs to handle session interruption

### Steps to Reproduce 
  1. Play some video in playlist
  2. Someone else calls you
  3. Playlist pauses.
  4. End the phone call.

**Actual result:** 
- Playlist never resumes playback.

**Expected result:**
- Playlist should continue playback when the phone call ends.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Resume Playlist Playback when AudioSession interrupted (Phone-Calls for Example).

This pull request fixes #4237

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- In Ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

File: Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift [hunk 1]
```diff
@@ -449,6 +449,44 @@ extension MediaPlayer {
...
+                  let type = AVAudioSession.InterruptionType(rawValue: typeValue) else {
+                      
+                return
+            }
+
+            switch type {
+            case .began:
+                // An interruption began. Update the UI as necessary.
+                self.pause()
+                break
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift]: break can be skipped

**Review by iccub — APPROVED** [review]

**Comment by iccub** [comment]
blocked: we have to decide on exact behavior we want here
