### PR TITLE
Fix #2699: Adblock-rust race condition crash.

### LINKED ISSUE #2699: Adblock list update crash
### Description: 

Zrzut ekranu 2020-07-6 o 12 29 17

### Steps to Reproduce 
Hard to reproduce. Looks like it happens on first launch after version/adblock file update

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.18, happens on 1.17 too but it's less common

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #2699 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

1. Verify that adblock stat counting works

Upgrade test:
1. Install 1.17
2. Open ad heavy website, keep that tab open
3. Upgrade to 1.18.1
4. The upgrade should not crash

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift [hunk 1]
```diff
@@ -136,15 +140,18 @@ class AdBlockStats: LocalAdblockResourceProtocol {
...
         
-        if engine.set(data: data) {
-            log.debug("Adblock file with id: \(id) deserialized successfully")
-            // Clearing the cache or checked urls.
-            // The new list can bring blocked resource that were previously set as not-blocked.
-            fifoCacheOfUrlsChecked = FifoDict()
-            completion.fill(())
-        } else {
-            log.error("Failed to deserialize adblock list with id: \(id)")
+        AdBlockStats.adblockSerialQueue.async {
```
Comment (iccub) [inline Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift:143]: It would be ideal to move this serial queue directly to `AdblockRust` class but I didn't want to make a bigger rewrite for now

**Review by Brandon-T — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
