### PR TITLE
Black screen appears while app launch bug fixed

### LINKED ISSUE #4190: Black screen keep showing after every brave app launch activity.
### Description: 
After every launch of Brave app, black screen keep showing for quite some time.

### Steps to Reproduce 
  1. Launch the app with some pre opened browse tabs

**Actual result:** 
There is black screen appears for quite some time until it reloads the pre opened tabs.
And app became unresponsive until the black screen disappears

**Expected result:**
App should open pre tabs immediate after app launch and it should responsive after app launch

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 
Simulator iphone 12 latest

### PR DESCRIPTION
**Pull request by prabagaranganesan**
## Summary of Changes
This PR fixes #4190

This pull request fixes #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -612,6 +612,7 @@ class BrowserViewController: UIViewController {
                            name: NSNotification.Name(rawValue: BraveGlobalShieldStats.didUpdateNotification), object: nil)
         }
         
+        view.backgroundColor = .white
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: why is this added?
I think we can use a dynamic color here to match theme, use `.braveBackground`

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (prabagaranganesan) [reply Client/Frontend/Browser/BrowserViewController.swift]: @iccub Addressed your comments.

**Comment by Brandon-T** [comment]
Hi & Thank You for this PR. Always appreciated.

My review:
There is potentially thread-unsafe code introduced in this PR:

`func unzipAndLoad(_ dir: String, data: Data) ` is called on the `MainQueue` and `loadDb` is called on `loadDbQueue` asynchronously.

`shouldUpgrade` is calling `tryRedirectingUrl` from the `MainQueue` but `loadDb` may still be in progress at the time, on its `loadDbQueue`. During a session restore, the db may not be loaded yet, and so every `shouldUpgrade` call can potentially return the wrong value (Undefined behaviour to access thread-unsafe objects from multiple different threads).

This can potentially cause race conditions. You can leave the `@synchronized(self)` blocks so that no two threads may call that function at the same time, while keeping the load code which will make the loading asynchronous, and block only when a value needs to be retrieved.

**Comment by prabagaranganesan** [comment]
@Brandon-T Thanks for comments, I agree with you. I will try to fix this.

**Comment by prabagaranganesan** [comment]
@Brandon-T I have fixed the thread issue by assigning `loaddb` and `tryRedirectingUrl` tasks to the same `loaddbqueue`. I have tested some scenarios by manually and enabled thread sanitiser to identify thread problem, It works without any issues for me. Please suggest if I missed anything in this changes.

File: Client/WebFilters/ShieldStats/Httpse/HttpsEverywhereStats.swift [hunk 2]
```diff
@@ -43,15 +45,20 @@ class HttpsEverywhereStats: LocalAdblockResourceProtocol {
         assert(httpseDb.isLoaded())
     }
     
-    func tryRedirectingUrl(_ url: URL) -> URL? {
+    func tryRedirectingUrl(_ url: URL, _ completion: @escaping(Bool) -> Void) {
         
         if url.scheme?.starts(with: "https") == true {
-            return nil
+            completion(false)
```
Comment (Brandon-T) [inline Client/WebFilters/ShieldStats/Httpse/HttpsEverywhereStats.swift]: Hi, everything looks good. However, you need to add a `return` statement after `completion(false)` otherwise it will fall through to the `loadDbQueue.async` code right below it.
We should also call `completion` on the same queue.

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/WebFilters/ShieldStats/Httpse/HttpsEverywhereStats.swift (hunk 2 above)
Comment (prabagaranganesan) [reply Client/WebFilters/ShieldStats/Httpse/HttpsEverywhereStats.swift]: @Brandon-T Updated as per your comments.

**Review by iccub — APPROVED** [review]
my review part looks good

**Review by Brandon-T — APPROVED** [review]

**Comment by iccub** [comment]
@prabagaranganesan good job :) you have pull latest development branch and rebase this PR in order to pass CI

**Comment by prabagaranganesan** [comment]
@iccub rebased with latest development.

**Comment by iccub** [comment]
thank you for being super responsive in this PR, rerunning CI again.

we will get one more person from security team to review your code and we should be good, this PR affects app launch so we should be extra careful here

**Comment by prabagaranganesan** [comment]
@iccub yeah I agree, this needs lot of testing. Since I am new to code, I have tested some flows that I familiar with. There can be other flows as well that I am not aware, FYI.

**Review by jumde — APPROVED** [review]
lgtm
