### PR TITLE
Fixed clearing of all Tabs and Data in Private-Browsing-Only

### LINKED ISSUE #580: Consider Not Restoring Tabs when Disabling PBO
When a user turns on PBO on, we should prompt them that this will destroy all of their tabs (potentially other data?). This prevents a user who stays in PBO mode for many months from having super old tabs being restored. It can appear to be a security vulnerability.

Ref: https://github.com/brave/brave-ios/pull/576/

### PR DESCRIPTION
**Pull request by Brandon-T**
- Fixed clearing of all tabs and data when switching to private-browsing-only.
- Fixes https://github.com/brave/brave-ios/issues/580

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/models/TabMO.swift [hunk 1]
```diff
@@ -134,11 +134,14 @@ public final class TabMO: NSManagedObject, CRUD {
         deleteAll(context: .new(inMemory: false))
     }
     
+    public class func deleteAllNormalTabs() {
+        deleteAll(predicate: NSPredicate(format: "isPrivate != true"), context: .new(inMemory: false))
```
Comment (iccub) [inline Data/models/TabMO.swift]: We do not save private tabs anymore, you can just call `deleteAll()` context is also set to `.new` by default

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -3061,6 +3061,29 @@ extension BrowserViewController: PreferencesObserver {
             setupTabs()
             updateTabsBarVisibility()
             updateApplicationShortcuts()
+            
+            // Destroy all tab data
+            tabManager.allTabs.forEach({
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: this first `(` bracket shouldn't be needed, can be removed

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -3061,6 +3061,29 @@ extension BrowserViewController: PreferencesObserver {
...
+                tabManager.removeAllBrowsingDataForTab($0, completionHandler: { [weak self] in
+                    self?.tabManager.removeAll()
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: I don't get it, why we iterate over each tab, and for each tab we call `removeAll()` to remove all tabs here?

**Review by iccub — CHANGES_REQUESTED** [review]

File: Data/models/TabMO.swift (hunk 1 above)
Comment (Brandon-T) [reply Data/models/TabMO.swift]: Fixed.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: I kept it there because the rest of the code has it. A search for `({` brings up 250+ results.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: Fixed.

**Review by iccub — APPROVED** [review]
Looks good to me.
I would like to get this reviewed by @danishjafri88 as well, as he's done a bit of similar data-clearing work

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -3061,6 +3061,29 @@ extension BrowserViewController: PreferencesObserver {
             setupTabs()
             updateTabsBarVisibility()
             updateApplicationShortcuts()
+            
+            // Destroy all tab data
```
Comment (danishjafri88) [inline Client/Frontend/Browser/BrowserViewController.swift]: The logic is good, but to save performance and to keep similar code in same place. Can you please move the clearable logic to settings itself? And do the reset configure before setup tabs

**Review by danishjafri88 — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 5]
```diff
@@ -3061,6 +3061,29 @@ extension BrowserViewController: PreferencesObserver {
...
+            tabManager.allTabs.forEach({
+                tabManager.removeAllBrowsingDataForTab($0)
```
Comment (danishjafri88) [inline Client/Frontend/Browser/BrowserViewController.swift]: We need not do this since cookie and cache clearable already does that for us

**Review by danishjafri88 — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 5 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: https://github.com/brave/brave-ios/blob/cbe5efa082bb453ed7b389391f72ab5941a32cdd/Client/Frontend/Settings/Clearables.swift#L52

Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: Also let’s make a check to delete data if switching from normal to private, since we already have a logic to clear data when going to normal from private

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: SettingsController doesn't have access to `tabManager` so it won't be able to remove all the tabs or reset configuration.

For the logic for going from `normal to private`, the code above does that because any time you toggle the switch, it will clear the data regardless of whether it is true or false.

IE: Go to settings and turn on PBO. Search for anything in a private tab. Search for anything in google. If you open a new private tab, and attempt to search, history will be there. Now go to settings and turn PBO off, all data is immediately cleared. Try searching in normal mode and see your history is gone. Go to PB (not PBO) and see your history is also gone.

**Review by danishjafri88 — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 6]
```diff
@@ -3061,6 +3061,8 @@ extension BrowserViewController: PreferencesObserver {
             setupTabs()
             updateTabsBarVisibility()
             updateApplicationShortcuts()
+            tabManager.removeAll()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: We need to reset config & remove all tabs even if the user is turning the feature _off_?

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: @kylehickinson when you turn PBO off, it automatically switches you to Normal mode. This was the behaviour from long before.
Only thing I did was add a call to removeAll and resetConfiguration.. which I guess isn't necessary. I just tested and it seems it makes no difference.

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 7]
```diff
@@ -313,23 +313,48 @@ class SettingsViewController: TableViewController {
...
+                    if value {
+                        let alert = UIAlertController(title: Strings.Private_Browsing_Only, message: Strings.Private_Browsing_Only_Warning, preferredStyle: .alert)
+                        alert.addAction(UIAlertAction(title: Strings.CancelButtonTitle, style: .cancel, handler: { _ in
+                            DispatchQueue.main.async {
+                                self.toggleSwitch(on: false, section: self.privacySection, rowUUID: Preferences.Privacy.privateBrowsingOnly.key)
+                            }
+                        }))
+
+                        alert.addAction(UIAlertAction(title: Strings.OKString, style: .default, handler: { _ in
+                            Preferences.Privacy.privateBrowsingOnly.value = value
```
Comment (jhreis) [inline Client/Frontend/Settings/SettingsViewController.swift:319]: This could should be moved to a block right above this. Then can just execute that block in either location, duplicating this much code is not ideal.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 7 above)
Comment (Brandon-T) [reply Client/Frontend/Settings/SettingsViewController.swift:319]: Fixed :)

**Review by jhreis — APPROVED** [review]
