### PR TITLE
Fix #5889: allow users to input decimal value with other locale's decimal separator

### LINKED ISSUE #5889: Wallet bug: Cannot send or swap decimal if device region is set to countries that use comma for decimals
### Description: 
Wallet failed to convert input to decimal number which block users from sending or swapping if users' keyboard using comma for decimal numbers.

### Steps to Reproduce 
  1. set region to a country that use comma for decimal numbers (e.x Poland)
  2. open wallet
  3. try to send and swap with a decimal number
  

**Actual result:** 
send and swap are disabled 

**Expected result:**
user should be able to send and swap when they have sufficient balance 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by nuo-xu**
Unfortunately we cannot force the keyboard to use en_US locale in SwiftUI, so users can input decimal value with a decimal separator that is not a dot. This will cause Big Number construction failure since this library only expecting dot as the decimal separator. 
This solution will convert any decimal input that is not using a dot as the decimal separator to use dot.

This pull request fixes #5889

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:
please refer to the issue

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Extensions/String+NumberFormatter.swift [hunk 1]
```diff
@@ -0,0 +1,25 @@
+// Copyright 2021 The Brave Authors. All rights reserved.
```
Comment (iccub) [inline Sources/BraveWallet/Extensions/String+NumberFormatter.swift]: old license

**Review by iccub — APPROVED** [review]
seem to work for me

**Review by StephenHeaps — APPROVED** [review]
