### PR TITLE
Fix #460, correctly set firstLaunch preference after migration.

### LINKED ISSUE #460: Page load progress gets stuck when tab is closed quickly
### Description: 
Page load progress gets stuck when tab is closed quickly 

### Steps to Reproduce 
  1. Visit any site in a new tab
  2. Open a new tab and load https://badssl.com
  3. Quickly close badssl.com tab while the page is loading, the blue progress indicator gets stuck on the current tab

**Actual result:** 
https://drive.google.com/open?id=1UPoHGvIeVBYGk4NVf3Pr--y-SeQM0ujz

**Expected result:**
Once tab is closed page load should not continue and the progress indicator should be removed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: BraveShared/Preferences.swift [hunk 1]
```diff
@@ -26,8 +26,8 @@ public class Preferences {
 }
 
 extension Preferences {
-    final class DAU {
-        static let lastLaunchInfo = Option<[Int?]?>(key: "dau.last-launch-info", default: nil)
+    public final class DAU {
```
Comment (iccub) [inline BraveShared/Preferences.swift:29]: The preference we need to check here is in a framework so I had to add some `public` keywords to make it acceesible.
I don't think we should have preference keys in a framework tbh.

Comment (kylehickinson) [reply BraveShared/Preferences.swift:29]: Yeah we would need to re-structure some of the stuff in `BraveShared` (`DAU` and `URP` for example) to either not live there or open them up to accept these preferences from `Client` side. Obviously out of scope for this ticket though :)

**Review by kylehickinson — APPROVED** [review]

File: BraveShared/Preferences.swift (hunk 1 above)
Comment (jhreis) [reply BraveShared/Preferences.swift:29]: Oh fine.
