### PR TITLE
Fix #8095: Favorites are shown in Private Tab mode when switching the apps 

### LINKED ISSUE #8095: [Follow up to #6577] `Favorites` are shown in `Private Tab` mode when switching the apps
### Description: 

Follow-up to #6577

### Steps to Reproduce 
1. Launch Brave 
2. Open `NTP` in `Private Tab` mode
3. Tap `Search` button  > Use the app switch gesture to see all opened apps > Observe

### Actual result: 

`Favorites` are shown in `Private Tab` mode when switching the apps.

|1|2|
|:-:|:-:|
|  |  |

### Expected result:

A blank screen must be shown in `Private Tab` mode when switching the apps

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.58 (23.9.19.14)
BraveCore: 1.58.124 (117.0.5938.62)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This pull request fixes #8095

Hide Active background favorites when backgrounding the app in private mode

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

- Begin Brave
- Open NTP in Private Tab mode
- Tap Search button > Use the app switch gesture to see all opened apps > Observe

## Screenshots:

1testss

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -721,6 +721,7 @@ public class BrowserViewController: UIViewController {
       webViewContainerBackdrop.alpha = 1
       webViewContainer.alpha = 0
       activeNewTabPageViewController?.view.alpha = 0
+      favoritesController?.view.alpha = 0
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/BrowserViewController.swift:724]: Should we add search controller as well?

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController.swift:724]: Actually yes so we can hide the suggestion from history ... Fixes https://github.com/brave/brave-ios/pull/8119/commits/fe08fc212c681308cee661fc1bbf39bf5d893357

**Review by kylehickinson — APPROVED** [review]
