### PR TITLE
Fix #3867 - Fixes using lots of RAM for NTP

### LINKED ISSUE #3867: Reopening new tabs increase app memory a lot
### Steps to Reproduce 
  1. Open a tab 
  2. Close a tab, open new tab
  3. Repeat 10 times

**Actual result:** 
A lot of memory is used

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes opening tabs taking too much memory due to loading NTP images every single time for all tabs.
- This changes it so that only the currently displayed tab's image is shown, and all other tabs that are not being disabled will have their images purged from memory.

This pull request fixes #3867

## Submitter Checklist:

- [X] *Unit Tests* are updated to cover new or changed functionality
- [X] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/HomePanel/NTPModels.swift [hunk 1]
```diff
@@ -56,10 +56,19 @@ class NTPBackground: Codable {
         let y: CGFloat?
     }
     
-    lazy var image: UIImage? = {
+    var image: UIImage? {
         // Remote resources are downloaded files, so must be loaded differently
-        packaged == true ? UIImage(named: imageUrl) : UIImage(contentsOfFile: imageUrl)
-    }()
+        if packaged == true {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/HomePanel/NTPModels.swift:61]: nit:

```suggestion
        if packaged {
```

File: Client/Frontend/Browser/HomePanel/NTPModels.swift [hunk 2]
```diff
@@ -56,10 +56,19 @@ class NTPBackground: Codable {
...
+            // Load without cache if possible
+            if let path = Bundle.main.path(forResource: imageUrl, ofType: nil) {
+                return UIImage(contentsOfFile: path)
+            }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/HomePanel/NTPModels.swift:65]: Is this needed? The previous solution didn't compute the path like this?

Comment (soner-yuksel) [reply Client/Frontend/Browser/HomePanel/NTPModels.swift:65]: Agreed `imageUrl` and path from `imageUrl` with nil type is same in this context.

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/HomePanel/NTPModels.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/HomePanel/NTPModels.swift:65]: They are different. `UIImage(named:)` does internal caching in memory. `UIImage(contentsOfFile:)` does caching but will purge it from memory, and will reload it from file as necessary.

`nil` just means you don't want to specify the extension of the file and the system will figure it out for you.

File: Client/Frontend/Browser/HomePanel/NTPModels.swift [hunk 3]
```diff
@@ -56,10 +56,19 @@ class NTPBackground: Codable {
         let y: CGFloat?
     }
     
-    lazy var image: UIImage? = {
+    var image: UIImage? {
         // Remote resources are downloaded files, so must be loaded differently
-        packaged == true ? UIImage(named: imageUrl) : UIImage(contentsOfFile: imageUrl)
-    }()
+        if packaged {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/HomePanel/NTPModels.swift]: `if packaged == true` otherwise you will get a compilation error.

**Review by soner-yuksel — APPROVED** [review]
