### PR TITLE
Fix #2565: Retry ref code lookup on subsequent launches.

### LINKED ISSUE #2565: iOS does not retry to get a downloadId
### Description: 
Found while testing https://github.com/brave/brave-ios/pull/2535

iOS does not retry to get a downloadId if internet is down or referral server is unreachable. 

This was recently implemented on desktop w/ https://github.com/brave/brave-browser/issues/7742

#### Clipboard Identification Verification
1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993` followed by a single character (either `:` or `/`) and then the specific ref code (e.g. ABC123) from the referral
1. So full out put would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Download Brave through TF
1. Disable internet (this makes sure the fallback is not activated if clipboard fails for some reason)
1. Open Brave
1. Since no internet connection, no custom assets, but ref code should still be shown inside the settings page
1. Re-enable wifi/internet on your device
1. Close Browser, remove from memory, relaunch
1. Check logs.

**Actual result:** 
No downloadId
Image from iOS
Image from iOS (1)

**Expected result:**
get a downloadId

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily, reproduced by @srirambv 

**Brave Version:** 
1.17 (20.05.18.18)

**Device details:** 
iOS12 iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by jhreis**
## Summary of Changes

This is fully dependent on https://github.com/brave/brave-ios/pull/2535, do not merge this before that completes.

This pull request fixes #2565 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

This impacts user referral promo logic, so should test all _initial_ download ids and referral code retrieval paths. Download Id redemption has not touched, as this only impacts app opening logic, but it may be good to run a quick test or two on that as well.

### User launches with clipboard referral and internet

1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993` and then the specific ref code (e.g. ABC123) from the referral
1. So full out put would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Download Brave through TF
1. Open Brave
1. Verify that correct ref code shows up in settings / on server
1. Verify assets are shown on the home page
1. Verify favorites show the referral’s custom favs

### User launches with clipboard referral and no internet

1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993` and then the specific ref code (e.g. ABC123) from the referral
1. So full output would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Download Brave through TF
1. Disable internet (this makes sure the fallback is not activated if clipboard fails for some reason)
1. Open Brave
1. Since no internet connection, no custom assets / download id, but *ref code should still be shown inside the settings page*
1. Close app entirely (swipe up on it)
1. Re-enable internet connection
1. Launch Brave again
1. Check settings page, download id should now be showing
1. Custom assets should eventually show up (may take a bit)

### User launches with no clipboard referral and internet

1. Referral should still work, even if clipboard approach fails, this tests that condition:
1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993:` and then the specific ref code (e.g. ABC123) from the referral
1. So full output would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Copy a random string (e.g. “chocolate and coffee”)
1. Re-paste the clipboard to verify the new string is _not_ the referral string
1. Download Brave through TF
1. Open Brave
1. Verify that correct ref code shows up in settings / on server
1. Verify assets are shown on the home page
1. Verify favorites show the referral’s custom favs

### User launches with no clipboard referral and no internet

1. Referral should still work, even if clipboard approach fails, this tests that condition:
1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993:` and then the specific ref code (e.g. ABC123) from the referral
1. So full output would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Copy a random string (e.g. “chocolate and coffee”)
1. Re-paste the clipboard to verify the new string is _not_ the referral string
1. Download Brave through TF
1. Disable internet (this makes sure the fallback is not activated if clipboard fails for some reason)
1. Open Brave
1. Since no internet connection, no custom assets / download id, *no ref-code should be shown* this time
1. Close app entirely (swipe up on it)
1. Re-enable internet connection
1. Launch Brave again
1. Check settings page, download id / ref code should now be showing
1. Custom assets should eventually show up (may take a bit)

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 1]
```diff
@@ -47,6 +47,7 @@ public class UserReferralProgram {
     
     /// Looks for referral and returns its landing page if possible.
     public func referralLookup(refCode: String?, completion: @escaping (_ refCode: String?, _ offerUrl: String?) -> Void) {
+        Preferences.URP.referralLookupOutstanding.value = false
```
Comment (iccub) [inline BraveShared/Analytics/UserReferralProgram.swift]: Doesn't make sense to me, shouldn't this flag be toggled after the ref lookup network call?

**Review by iccub — CHANGES_REQUESTED** [review]

File: BraveShared/Analytics/UserReferralProgram.swift (hunk 1 above)
Comment (jhreis) [reply BraveShared/Analytics/UserReferralProgram.swift]: Yup 😄 I think I moved this last minute when cleaning things up, but this looks v wrong. Fixing.

**Review by iccub — APPROVED** [review]

File: BraveShared/Analytics/UserReferralProgram.swift [hunk 2]
```diff
@@ -23,6 +23,13 @@ public class UserReferralProgram {
         static let prod = "https://laptop-updates.brave.com"
     }
     
+    // In case of network problems when looking for referrral code
+    // we retry the call few times while the app is still alive.
+    private var referralLookupRetryTimer: Timer?
```
Comment (jhreis) [inline BraveShared/Analytics/UserReferralProgram.swift]: Probably more clear to just wrap these all in a struct, since all related to the same thing.

```
struct ReferralLookupRetry {
    private var retryTimer: Timer?
    private var currentCount = 0
    ...
}
```

File: Client/Application/Delegates/AppDelegate.swift [hunk 3]
```diff
@@ -260,9 +260,22 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
...
+                Preferences.URP.referralLookupOutstanding.value = isFirstLaunch
+            }
+            
+            if Preferences.URP.referralLookupOutstanding.value == true {
                 let refCode = UserReferralProgram.sanitize(input: UIPasteboard.general.string)
-                if refCode != nil { UIPasteboard.general.clearPasteboard() }
+                if refCode != nil {
+                    UrpLog.log("Clipboard ref code found: " + (UIPasteboard.general.string ?? "!Clipboard Empty!"))
+                    UrpLog.log("Clearing clipboard.")
+                    UIPasteboard.general.clearPasteboard()
```
Comment (jumde) [inline Client/Application/Delegates/AppDelegate.swift:277]: If the refcode is cleared here, app won't find the refcode on the next launch if the the 10 network requests are not successful. May be store it in URP preferences?

Comment (jhreis) [reply Client/Application/Delegates/AppDelegate.swift:277]: Ref code is passed into the look up function, and it is stored internally there:
https://github.com/brave/brave-ios/pull/2574/files#diff-bfe2070e3d8f02013654953e18b60730R280

Here is where it is stored:
https://github.com/brave/brave-ios/pull/2574/files#diff-60f6d7911cf19ceb7bcfcde55f9bc740R126

Then two lines below the network request (and potential retry logic) is executed.

**Comment by jhreis** [comment]
New commits from @iccub lgtm, ++
(can't formally review, since originally my PR)

File: Client/Application/Delegates/AppDelegate.swift (hunk 3 above)
Comment (jumde) [reply Client/Application/Delegates/AppDelegate.swift:277]: My concern is that we are still accessing the clipboard on subsequent launches, I think we should just store it in a preference and use it from there: https://github.com/brave/brave-ios/pull/2574/files#diff-bfe2070e3d8f02013654953e18b60730R273 - Let me know if I'm missing something.

Comment (jhreis) [reply Client/Application/Delegates/AppDelegate.swift:277]: That make sense, we will add a ref code check to prevent reading the clipboard again. Will be in a follow PR though, as it doesn't pertain to what this PR is.

**Comment by jhreis** [comment]
Per @jumde's comments, created follow up ticket, which will be required for this feature:
https://github.com/brave/brave-ios/issues/2584

**Comment by jumde** [comment]
Issue to access clipboard on subsequent launches is being addressed here: https://github.com/brave/brave-ios/pull/2585/files - rest looks good to me

**Review by jumde — APPROVED** [review]
