### PR TITLE
Fix #2644/#2558: Dark Mode Related Changes

### LINKED ISSUE #2558: iPad dark mode issue with tab color
### Description: 
When iOS for iPad switches from light to dark mode automatically the tab color does not adjust itself other then after closing and re-opening the Brave browser.

### Steps to Reproduce 
  1.  Launch Brave browser on iOS
  2. Switch from light to dark mode or reverse
  3. Observe the tab color to stay in light mode when iOS is in dark mode or reverse

**Actual result:** 
IMG_0029

**Expected result:**
Switching from light to dark mode or reverse should cause all visible browser elements to follow the mode when the appearance is set to automatic.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.16.1(20.05.14.20)

**Device details:** 
iPad Pro 12.9 inch 3rd generation (iOS 13.4.1)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A 

### Additional Information
Thanks for looking into this. Best regards.

### LINKED ISSUE #2644: Text is not visible when editing a favourite/bookmark in dark mode
### Description: 
Text is not visible when editing a favourite/bookmark on iPad in dark mode

### Steps to Reproduce 
  1. Install 1.18
  2. Open a new tab and edit the favourite/bookmark
  3. Text is not visible

**Actual result:** 
image

**Expected result:**
Should be visible 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.18(20.06.16.08)

**Device details:** 
iPad (iOS 12) - Yes
iPhone 6 (iOS 12) - Yes
iPhone XR(iOS 13.5) - No
iPhone 7+(iOS 13.5.1) - No
iPad Pro (iOS 13) - No

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by soner-yuksel**
Some Dark mode related fixed are added to

- Edit Bookmark Textfield
- TabBar 

## Summary of Changes

This pull request fixes #2644
This pull request fixes #2558

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Load Brave Browser while using DarkMode and long press a favourite
- Click Edit BookMark and check colors in textfields are ok
- Delete values inside textfield and check placeholder text colors

- Load Brave Browser while using DarkMode or Light Mode and check Tabbar color
- Go settings change device appearance to the mode that is not being used 
- Go back to the browser and check TabBar color

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/TabsBar/TabBarCell.swift [hunk 1]
```diff
@@ -109,12 +111,19 @@ class TabBarCell: UICollectionViewCell {
         }
     }
     
+    func setTheme(with activeTheme: Theme) {
+        backgroundColor = .clear
+        titleLabel.textColor = PrivateBrowsingManager.shared.isPrivateBrowsing ? .white : activeTheme.colors.tints.header
+        closeButton.tintColor = activeTheme.colors.tints.header
+    }
+
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabsBar/TabBarCell.swift]: Probably just easier to make `TabBarCell` `Themable` and use `applyTheme` that all other instances of theming use :)

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift [hunk 2]
```diff
@@ -53,8 +53,12 @@ class TabsBarViewController: UIViewController {
     fileprivate weak var tabManager: TabManager?
     fileprivate var tabList = WeakList<Tab>()
     
+    private var activeTheme: Theme
+    
     init(tabManager: TabManager) {
         self.tabManager = tabManager
+        activeTheme = Theme.of(tabManager.selectedTab)
+
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabsBar/TabsBarViewController.swift]: Instead of tracking a theme, perhaps we can follow what was done in TabTrayController: 

https://github.com/brave/brave-ios/blob/613103e8fdf98cb85e159546476be10baec5ca8b/Client/Frontend/Browser/TabTrayController.swift#L415-L424

`styleChildren` is a default method of the `Themable` protocol. Then we just call `cell.applyTheme(Theme.of(tab))`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/TabsBar/TabBarCell.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/TabsBar/TabBarCell.swift]: setTheme is removed and Themable protocol is added along side with appleTheme method inside the cell

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift (hunk 2 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/TabsBar/TabsBarViewController.swift]: Defined the themeableChildren for the viewcontroller to update cell theme.

File: Client/Frontend/Browser/TabsBar/TabBarCell.swift [hunk 3]
```diff
@@ -126,4 +129,12 @@ class TabBarCell: UICollectionViewCell {
             strongSelf.titleLabel.text = tab.displayTitle
         }
     }
+    
+    func applyTheme(_ theme: Theme) {
+        styleChildren(theme: theme)
+
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabsBar/TabBarCell.swift]: Tiny nit: calling `styleChildren` here is not required since you have not assigned `themableChildren` to anything

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift [hunk 4]
```diff
@@ -343,6 +373,10 @@ extension TabsBarViewController: TabManagerDelegate {
 }
 
 extension TabsBarViewController: Themeable {
+    var themeableChildren: [Themeable?]? {
+        return  collectionView.visibleCells.compactMap({ $0 as? TabBarCell })
+    }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabsBar/TabsBarViewController.swift]: Tiny nit: No need for the `return` statement for a single-line function

**Review by kylehickinson — CHANGES_REQUESTED** [review]
Just a couple of super tiny nits to fix but otherwise things look good! :D

**Review by kylehickinson — APPROVED** [review]
