### PR TITLE
Fix #735: Set correct order of bookmarks on insert and update.

### LINKED ISSUE #735: Bookmarks from sync are received in wrong order.
### Steps to Reproduce 
  1. Add few bookmarks on both devices
  2. Pair them with sync

**Actual result:** 
The order of bookmarks on both devices is not the same

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adaquate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/models/Bookmark+Sync.swift [hunk 1]
```diff
@@ -108,4 +108,56 @@ extension Bookmark {
...
+            return
+        }
+        
+        for (order, bookmark) in sortedSyncOrders.enumerated() {
+            bookmark.order = Int16(order)
+        }
+    }
+    
+    static let syncOrderComparator: (Any, Any) -> ComparisonResult = { obj1, obj2 in
+        guard let s1 = obj1 as? Bookmark, let s2 = obj2 as? Bookmark,
```
Comment (jhreis) [inline Data/models/Bookmark+Sync.swift]: `s1` and `s2` are only used in this guard statement, I do not think unwrapping them is super necessary.

File: Data/models/Bookmark+Sync.swift [hunk 2]
```diff
@@ -108,4 +108,56 @@ extension Bookmark {
...
+            let order1 = s1.syncOrder, let order2 = s2.syncOrder else {
+                fatalError()
+        }
+        
+        // Split is O(n)
+        var i1 = order1.split(separator: ".").compactMap { Int($0) }
```
Comment (jhreis) [inline Data/models/Bookmark+Sync.swift]: what is `i`? Also maybe add a comment could help a bit:
```
// 0.0.1.1 to [ 0, 0, 1, 1 ]
```

File: Data/models/Bookmark+Sync.swift [hunk 3]
```diff
@@ -108,4 +108,56 @@ extension Bookmark {
...
+                if i1.count == i2.count { return .orderedSame }
+                if i1.count > i2.count { return .orderedDescending }
+                if i1.count < i2.count { return .orderedAscending }
+            }
+            
+            if i1[i] == i2[i] && iterationCount != i { // number equal, going through next one
+                continue
+            }
+            
+            if i1[i] > i2[i] { return .orderedDescending }
```
Comment (jhreis) [inline Data/models/Bookmark+Sync.swift]: Can we place this at the beginning of the `for` loop? Feels a bit weird down here. Or would this impact something else?

File: Data/models/Bookmark.swift [hunk 4]
```diff
@@ -507,3 +548,52 @@ extension Bookmark {
...
+            log.info("""
+                Wanting to compare bookmark: \(String(describing: displayTitle)) \
+                and \(String(describing: rhs.displayTitle)) but no syncOrder is set \
+                in at least one of them.
+                """)
+            return .orderedSame
+        }
+        
+        // Split is O(n)
+        var lhsSyncOrderBits = lhsSyncOrder.split(separator: ".").compactMap { Int($0) }
```
Comment (jhreis) [inline Data/models/Bookmark.swift]: `let`?

File: Data/models/Bookmark.swift [hunk 5]
```diff
@@ -277,37 +288,67 @@ public final class Bookmark: NSManagedObject, WebsitePresentable, Syncable, CRUD
...
+                             sourceIndexPath: sourceIndexPath, destinationIndexPath: destinationIndexPath, context: context)
+        
+        setOrderForAllBookmarksOnGivenLevel(parent: src.parentFolder, forFavorites: src.isFavorite, context: context)
+        
+        DataController.save(context: context)
+        // Updating sync orders is not supported on server side yet, see issue #772 for more details.
+        if !src.isFavorite { Sync.shared.sendSyncRecords(action: .update, records: [src]) }
+    }
+    
+    private class func reorderWithSyncOrder(frc: NSFetchedResultsController<Bookmark>,
```
Comment (jhreis) [inline Data/models/Bookmark.swift]: Please add function comments here to thoroughly explain what this is doing.

File: Data/models/Bookmark.swift [hunk 6]
```diff
@@ -277,37 +288,67 @@ public final class Bookmark: NSManagedObject, WebsitePresentable, Syncable, CRUD
         return count > 0
     }
     
-    public class func reorderBookmarks(
-        frc: NSFetchedResultsController<Bookmark>?,
-        sourceIndexPath: IndexPath,
-        destinationIndexPath: IndexPath) {
+    public class func reorderBookmarks(frc: NSFetchedResultsController<Bookmark>?, sourceIndexPath: IndexPath,
```
Comment (jhreis) [inline Data/models/Bookmark.swift:299]: Please add function comments here to thoroughly explain what this is doing.

File: Data/models/Bookmark+Sync.swift [hunk 7]
```diff
@@ -108,4 +108,16 @@ extension Bookmark {
         DataController.save(context: context)
         Sync.shared.baseSyncOrder = nil
     }
+    
+    class func setOrderForAllBookmarksOnGivenLevel(parent: Bookmark?, forFavorites: Bool, context: NSManagedObjectContext) {
```
Comment (jhreis) [inline Data/models/Bookmark+Sync.swift:124]: Although this function name is pretty clear, would still be good to add some function comments.

File: Data/models/Bookmark.swift [hunk 8]
```diff
@@ -277,37 +288,67 @@ public final class Bookmark: NSManagedObject, WebsitePresentable, Syncable, CRUD
...
+            var next: String?
+            
+            // Bookmark at the bottom has no next bookmark.
+            if let objects = frc.fetchedObjects, destinationIndexPath.row + 1 < objects.count {
+                let index = IndexPath(row: destinationIndexPath.row + 1, section: destinationIndexPath.section)
+                let objectAtIndexOnBgContext = context.object(with: frc.object(at: index).objectID) as? Bookmark
+                next = objectAtIndexOnBgContext?.syncOrder
+            }
+            
+            srcBgContext.syncOrder = Sync.shared.getBookmarkOrder(previousOrder: prev, nextOrder: next)
```
Comment (jhreis) [inline Data/models/Bookmark.swift]: Move this outside the `if-else` and place `prev` / `next` as defined outside, and set inside the `if-else`.

**Review by jhreis — CHANGES_REQUESTED** [review]

**Review by jhreis — APPROVED** [review]
