### PR TITLE
Fix #4073: Intermittent Issue while displaying the History when Sync is enabled

### LINKED ISSUE #4073: Intermittent Issue while displaying the History when Sync is enabled
Description:
There are some reports from users when Sync is enabled for History, viewing History Page can cause a crash.
Crash Report from Xcode is added for the problem.

Crash Log From Xcode:

[Dlo5sItyGy7nM8t_opLIJ.xccrashpoint.zip](https://github.com/brave/brave-ios/files/7015637/Dlo5sItyGy7nM8t_opLIJ.xccrashpoint.zip)

Steps to Reproduce

- Enable History Sync
- Open History Screen from the options menu

Actual result:
Users reporting rare crashes

Expected result:
The history screen should be viewed properly

Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent Issue

Brave Version:
1.30.1 (21.8.17.19

Device details:
Crash reports are mainly from iPhone 12
OS 14.6 14.7

Website problems only:
did you check with Brave Shields down? NA
did you check in Safari/Firefox (WkWebView-based browsers)?NA

### PR DESCRIPTION
**Pull request by soner-yuksel**
This PR is adding extra checks to History cell configuration in order to prevent any potential crashes while setting the tableview.

In addition loadFavIcon logic is changed in History List so it will be helpful with the flickering of favicons when list tries to refresh itself after a reload notification is fetched.

## Summary of Changes

This pull request fixes #4073

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Enable History Sync
- Open History Screen from the options menu and check if data is displayed

## Screenshots:

https://user-images.githubusercontent.com/6643505/130099449-bcb9c04b-7c56-4def-8008-c411c56ac233.MP4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift [hunk 1]
```diff
@@ -68,8 +68,8 @@ class Historyv2: WebsitePresentable {
         }
     }
     
-    public var domain: String? {
-        historyNode.url.domainURL.absoluteString
+    public var domain: Domain? {
+        return Domain.getOrCreate(forUrl: historyNode.url, persistent: true)
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: should we persist it when in private mode?

Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: You are right I am adding Private mode part, btw do we have to do the same for bookmarks ?

Comment (iccub) [reply Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: no, bookmarks always persist even if you add them in private mode, but history should be gone when you switch back to normal mode

Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: Fix at https://github.com/brave/brave-ios/pull/4074/commits/69f9d82a0c96279e34980c676e0334c5569d3007

**Review by iccub — APPROVED** [review]
