### PR TITLE
Fix #2168: Update user agent.

### LINKED ISSUE #2168: User agent is outdated
### Steps to Reproduce 
  1. Open https://www.whatismybrowser.com/

**Actual result:** 
Zrzut ekranu 2020-01-9 o 13 32 52

**Expected result:**
Match firefox

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes issue #2168 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Compare user agents between Brave and Firefox.
Please use mobile only mode when on iPad

## Screenshots:

IMG_0049
IMG_0048

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Shared/UserAgent.swift [hunk 1]
```diff
@@ -80,7 +75,7 @@ open class UserAgent {
         }
 
         let mutableUA = NSMutableString(string: userAgent)
-        mutableUA.insert("FxiOS/\(appVersion)b\(buildNumber) ", at: mobileRange.location)
+        mutableUA.insert("FxiOS/\(appVersion) ", at: mobileRange.location)
```
Comment (iccub) [inline Shared/UserAgent.swift:78]: FF doesn't use build number anymore

**Review by Brandon-T — APPROVED** [review]
