### PR TITLE
Fix #7103: Shields show Session Restore - Reader Mode Internal URL

### LINKED ISSUE #7103: Shields show Session Restore - Reader Mode Internal URL
### Description: 
Shields show `INTERNAL://LOCAL/SESSIONRESTORE?URL=` whilst the page is loading. In addition when Reader Mode is activated Shields show `INTERNAL://LOCAL/READER-MODE?URL=`  if reader mode is activated.

### Steps to Reproduce 
Test 1:
  1. Load a page
  2. Quit browser and relaunch
  3. Open shields while the page is loading
 
Test 2:
  1. Load a page
  2. Activate Reader mode
  3. Open shields

### Actual result: 

test1 1

### Expected result:
Should show original URL

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 
1.49(23.3.15.7)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @iccub @Brandon-T

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes
Adding Internal URL display for Shields Screen

This pull request fixes #7103

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Test 1:

Load a page
Quit browser and relaunch
Open shields while the page is loading

Test 2:

Load a page
Activate Reader mode
Open shields

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveShared/Extensions/URLExtensions.swift [hunk 1]
```diff
@@ -22,4 +23,60 @@ extension URL {
...
+  /// Returns the original url without  internal parameters
+  public var stippedInternalURL: URL? {
+    if InternalURL.isValid(url: self),
+       let internalURL = InternalURL(self) {
+      
+      switch internalURL.urlType {
+      case .errorPage:
+        return internalURL.originalURLFromErrorPage
+      case .web3Page, .sessionRestorePage, .readerModePage, .aboutHomePage:
+        return internalURL.extractedUrlParam?.displayURL
```
Comment (Brandon-T) [inline Sources/BraveShared/Extensions/URLExtensions.swift]: Why does it return `displayURL`?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Sources/BraveShared/Extensions/URLExtensions.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/BraveShared/Extensions/URLExtensions.swift]: Nice catch you are right `displayURL` is not necessary at all. extractedUrlParam does what we need, I carrie it over from previous implementation, I should have checked.

Fix at  https://github.com/brave/brave-ios/pull/7264/commits/a014ea01d93e1c80b5483051a85c9634263f254a

**Review by Brandon-T — APPROVED** [review]
