### PR TITLE
Fix #7835, #8494: Fix handling of External URL when in third-party frames but active tab

### LINKED ISSUE #7835: [hackerone] Add `Suppress` button to `Allow link to switch apps?` pop-up
https://hackerone.com/reports/2098015

### LINKED ISSUE #8494: links not opening third party apps when `target=blank/open in new tab`
### Description: 

As originally reported via https://x.com/StrawberrySith/status/1729823719030202673, AppStore links using `target=blank/open in new tab` are not opening/working as expected. Looks like it's generally working now that we've fixed https://github.com/brave/brave-ios/issues/8383.

### Steps to Reproduce 

  1. open https://connect.causality.xyz and attempt tapping/opening the `App Store` link

For context/information can be found via https://x.com/StrawberrySith/status/1729823719030202673 as mentioned above.

### Actual result: 

Tapping on the `App Store` link doesn't do anything.

### Expected result:

Tapping on the `App Store` link should produce the modal re: opening the link in another application (in this case the App Store)

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes

### Device details: 

* `iPhone 11` running `iOS 17.1.1` - **Reproduced**

### Website problems only:
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Do not ever cancel requests when handling opening URLs, especially those with `target=_blank` as they will NOT have a `parent` tab! This is because when a URL is cancelled, if the user hits `allow` to open it, then a NEW request is made and all of the entire navigationAction/State is completely lost. The new URL will not have the same privileges, it will not open in a CHILD tab, and it will not have the `syntheticClickType` or `navigationActionType` as its parent! This is important to determine if a URL has been opened by a user action vs. by Javascript.

- Second problem is that we block opening of external URLs in third-party frames, but a lot of websites now outsource universal links to third-party service providers which for some odd reason always seems to open the URL with `target=_blank`, and since we block this, the applications don't open. This behaviour is undesired as all other browser **EXCEPT brave** can handle such URLs. Instead, we should either handle the specific case of `sms/tel` URLs like Safari does, OR we allow it in third-party frames but only for `active` tabs.

This pull request fixes #7835 
This pull request fixes #8494

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -180,8 +180,11 @@ extension BrowserViewController: WKNavigationDelegate {
     
     if ["sms", "tel", "facetime", "facetime-audio"].contains(requestURL.scheme) {
       // Do not allow opening external URLs from child tabs
-      handleExternalURL(requestURL, tab: tab, navigationAction: navigationAction)
-      return (.cancel, preferences)
+      return await withCheckedContinuation { continuation in
+        handleExternalURL(requestURL, tab: tab, navigationAction: navigationAction) { shouldOpen in
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Just make `handleExternalURL` an `async` function and await like normal. There's only 1 usage of the variant that actually uses the completion handler and that one can also just await

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 2]
```diff
@@ -406,13 +438,22 @@ extension BrowserViewController: WKNavigationDelegate {
...
-        if !didOpenURL, navigationAction.navigationType == .linkActivated {
-          let alert = UIAlertController(title: Strings.unableToOpenURLErrorTitle, message: Strings.unableToOpenURLError, preferredStyle: .alert)
-          alert.addAction(UIAlertAction(title: Strings.OKString, style: .default, handler: nil))
-          self.present(alert, animated: true, completion: nil)
+      return await withCheckedContinuation { continuation in
+        handleExternalURL(requestURL, tab: tab, navigationAction: navigationAction) { shouldOpen in
+          // Do not show error message for JS navigated links or redirect
+          // as it's not the result of a user action.
+          if !shouldOpen, navigationAction.navigationType == .linkActivated {
+            let alert = UIAlertController(title: Strings.unableToOpenURLErrorTitle, message: Strings.unableToOpenURLError, preferredStyle: .alert)
```
Comment (stoletheminerals) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: https://stoletheminerals.github.io/dosscheme.html

this page will DoS with infinite alerts

**Review by stoletheminerals — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 2 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: Fixed: https://github.com/brave/brave-ios/pull/8495/commits/e069a88b06e707af8e8c42f34d10d0e09e26aade

Safari also shows the same alert indefinitely. But the above commit fixes the spam and allows the user to suppress it.

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: Can we have this as a test case in manual passes actually ? 
Check the link https://stoletheminerals.github.io/dosscheme.html for DoS. cc @iccub

Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: Also I've just blocked `syntheticClicks`: https://github.com/brave/brave-ios/pull/8495/commits/ee11f4920bb2ec717d0a73b19ae395df84d2dd24

So now Javascript cannot open external URLs without user consent. IE: `anchor_tag.click()` is not going to work anymore for this. Technically this synthetic click blocking isn't really necessary as my precautions already work anyway, so I can always remove it if requested.

Comment (stoletheminerals) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: Looks like it's fixed now for the active tab, but all kinds of alerts are popping up once I switch the tabs. I think we had a similar problem when @soner-yuksel was fixing it initially, not sure if it's now caused by this PR or we didn't fully fixed it last time.

https://github.com/brave/brave-ios/assets/10810135/26a37804-6d71-4042-8040-92d68bdb0a9c

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: Yeah we were doing the active link check for this so inactive tabs dont show popups but I am not sure at what stage this is changed

https://github.com/brave/brave-ios/issues/6687

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 3]
```diff
@@ -834,7 +863,8 @@ extension BrowserViewController {
     // Finally check non-active tab
     let isNonActiveTab = isAboutHome ? false : tab?.url?.host != topToolbar.currentURL?.host
 
-    if !isMainFrame || isNonActiveTab {
+    if !isMainFrame && isNonActiveTab {
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: So this change here instead of returning now we are handling the actions from other tabs. Checking what we can do.

Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Fix: https://github.com/brave/brave-ios/pull/8495/commits/1d8af082fbab4fe44083548914e49c544e8d73e2

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 2 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: Fix: https://github.com/brave/brave-ios/pull/8495/commits/1d8af082fbab4fe44083548914e49c544e8d73e2

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:418]: Tested all the variations, the DoS prevention works and all the external app action including AppStore action from subframe is working properly.

**Review by soner-yuksel — APPROVED** [review]

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 1 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Fixed: https://github.com/brave/brave-ios/pull/8495/commits/e4702276a8a942ec39140e49e113195dcd71d53b

**Review by stoletheminerals — APPROVED** [review]
