### PR TITLE
Fix #3081: Rewards onboarding typo.

### LINKED ISSUE #3081: Remove/Replace "?" from rewards onboarding string
### Description: 

Looks like there's a `?` at the end of the reward onboarding string which doesn't make sense.

### Steps to Reproduce 
  1. install `1.22 (20.11.25.21)` via TF
  2. run through onboarding till you get to rewards

**Actual result:** 

<p align="center">

</p>

**Expected result:**

I'm not 100% sure what it should be, but maybe using `!` or a period makes more sense. CCing @jamesmudgett @anthonypkeane to decide how the string should look like.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.22 (20.11.25.21)`

**Device details:** 

* `iPhone 11` running `iOS 14.2` - **Reproduced**

**Website problems only:** `N/A`
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @srirambv

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #3081 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -646,7 +646,7 @@ extension Strings {
...
     public static let OBAdsOptInMessageJapan = NSLocalizedString("OBAdsOptInMessageJapan", bundle: Bundle.braveShared, value: "Earn points and reward creators for great content while you browse.", comment: "Message when opting into brave Ads when region becomes available")
     public static let OBRewardsDetailInAdRegion = NSLocalizedString("OBRewardsDetailInAdRegion", bundle: Bundle.braveShared, value: "Earn tokens and reward creators for great content while you browse.", comment: "Detail text for rewards onboarding screen")
-    public static let OBRewardsDetail = NSLocalizedString("OBRewardsDetail", bundle: Bundle.braveShared, value: "Start supporting creators with private and anonymized ads while you browse?", comment: "Detail text for rewards onboarding screen")
+    public static let OBRewardsDetail = NSLocalizedString("OBRewardsDetail", bundle: Bundle.braveShared, value: "Start supporting creators with private and anonymized ads while you browse", comment: "Detail text for rewards onboarding screen")
```
Comment (kylehickinson) [inline BraveShared/BraveStrings.swift:649]: Is this supposed to end with a period?

Comment (iccub) [reply BraveShared/BraveStrings.swift:649]: yes,
https://github.com/brave/brave-ios/issues/3081#issuecomment-736125758
