### PR TITLE
Fix: #4422 Send Screen with Unapproved Transaction API

### LINKED ISSUE #4422: Integrate Brave Wallet Send UI with API
Integrate the wallet send screen with the create tx API in brave-core

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
This PR integrated Send Crypto Screen with unapproved transaction API.
Transaction confirmation UI and integration will be in separated tickets.
Also added unit test against `isAddress` 

This pull request fixes #4422

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 1]
```diff
@@ -71,6 +80,15 @@ struct SendTokenView: View {
                                                      sendTokenStore.selectedSendToken?.symbol ?? ""),
                     text: $amountInput
           )
+            .onChange(of: amountInput, perform: { value in
+              guard let token = sendTokenStore.selectedSendToken else { return }
+              // will ignore if input is not a decimal number
+              if let decimal = Decimal(string: value), -decimal.exponent > 0 {
```
Comment (nuo-xu) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: should i use BDecimal?

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 2]
```diff
@@ -17,9 +17,18 @@ struct SendTokenView: View {
   @State private var amountInput = ""
   @State private var sendAddress = ""
   @State private var isShowingScanner = false
+  @State private var isShowingError = false
   
   @ScaledMetric private var length: CGFloat = 16.0
   
+  private var disableSend: Bool {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: nit: `isSendDisabled`

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift (hunk 1 above)
Comment (kylehickinson) [reply BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Yeah you should consider using `BDouble` or just toss values into `WeiFormatter` since we need to support not only 18 digits _after_ the decimal point but all the data before it

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 3]
```diff
@@ -111,7 +123,32 @@ public class SendTokenStore: ObservableObject {
...
             return
           }
-          self.selectedSendTokenBalance = balance
+          updateBalance(success, balance)
+        }
+      }
+    }
+  }
+  
+  func sendToken(account: BraveWallet.AccountInfo, to: String, amount: String, completion: @escaping (_ success: Bool) -> Void) {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift]: nit: API naming

```swift
func sendToken(
  from account: BraveWallet.AccountInfo, 
  to address: String, 
  amount: String, 
  completion: @escaping (_ success: Bool) -> Void
)
```

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 4]
```diff
@@ -71,6 +80,15 @@ struct SendTokenView: View {
                                                      sendTokenStore.selectedSendToken?.symbol ?? ""),
                     text: $amountInput
           )
+            .onChange(of: amountInput, perform: { value in
+              guard let token = sendTokenStore.selectedSendToken else { return }
+              // will ignore if input is not a decimal number
+              if let decimal = Decimal(string: value), -decimal.exponent > 0 {
+                if -decimal.exponent > Int(token.decimals) {
+                  self.amountInput = String(value.prefix(Int(token.decimals) + 2))
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Is it possible for this to cause recursion in any way since you're changing the amount input in a closure that is triggered when you change the amount input? Not sure if `onChange` is triggered if the value is changed within the closure

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 5]
```diff
@@ -104,17 +122,31 @@ struct SendTokenView: View {
...
             .listRowBackground(Color(.clear))
         ) {
         }
         .listRowBackground(Color(.secondaryBraveGroupedBackground))
       }
+      .alert(isPresented: $isShowingError) {
+        Alert(
+          title: Text(""),
+          message: Text(Strings.Wallet.sendCryptoSendError),
+          dismissButton: .cancel(Text( Strings.OKString))
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: nit: random space

**Review by kylehickinson — CHANGES_REQUESTED** [review]
Mostly nits :)

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 6]
```diff
@@ -111,7 +123,32 @@ public class SendTokenStore: ObservableObject {
...
+      }
+    } else {
+      transactionController.makeErc20TransferData(account.address, amount: "0x\(weiHexString)") { [self] success, data in
+        guard success else {
+          completion(false)
+          return
+        }
+        rpcController.chainId { [self] chainId in
+          let txData = BraveWallet.TxData(nonce: "", gasPrice: "", gasLimit: "", to: token.contractAddress, value: "0x0", data: data)
+          self.transactionController.addUnapprovedTransaction(txData, from: account.address) { success, txMetaId, errorMessage in
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift]: Don't need `self` since you already have `[self]`

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 7]
```diff
@@ -111,7 +123,32 @@ public class SendTokenStore: ObservableObject {
...
+      }
+    }
+  }
+  
+  func sendToken(account: BraveWallet.AccountInfo, to: String, amount: String, completion: @escaping (_ success: Bool) -> Void) {
+    let weiFormatter = WeiFormatter(decimalFormatStyle: .decimals(precision: 18))
+    guard let token = selectedSendToken, let weiHexString = weiFormatter.weiString(from: amount, radix: .hex, decimals: 18) else { return }
+    
+    if token.isETH {
+      let data = BraveWallet.TxData(nonce: "", gasPrice: "", gasLimit: "", to: to, value: "0x\(weiHexString)", data: [NSNumber]())
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift]: `[NSNumber]()` → `.init()` ?

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift (hunk 4 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: > Is it possible for this to cause recursion in any way since you're changing the amount input in a closure that is triggered when you change the amount input? Not sure if `onChange` is triggered if the value is changed within the closure

It will trigger `onChange` one more time, but it will fail at line 87

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 8]
```diff
@@ -82,11 +82,11 @@ struct SendTokenView: View {
...
-              if let decimal = Decimal(string: value), -decimal.exponent > 0 {
-                if -decimal.exponent > Int(token.decimals) {
-                  self.amountInput = String(value.prefix(Int(token.decimals) + 2))
-                }
+              let weiFormatter = WeiFormatter(decimalFormatStyle: .decimals(precision: Int(token.decimals)))
+              
+              guard weiFormatter.weiString(from: value, radix: .decimal, decimals: Int(token.decimals)) != nil else {
+                self.amountInput = String(value.dropLast())
+                return
               }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: 1. Given this is the end of the scope, you may as well just use `if` without a return instead of `guard-else`.
2. If a user pastes a really large number with too many decimals, won't this execute over and over until it eventually passes? What if we instead just disable the button for invalid amounts rather than try and correct them?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 9]
```diff
@@ -22,11 +23,18 @@ struct SendTokenView: View {
   @ScaledMetric private var length: CGFloat = 16.0
   
   private var isSendDisabled: Bool {
-    guard let sendAmount = Double(amountInput), let balance = sendTokenStore.selectedSendTokenBalance else {
+    guard let sendAmount = BDouble(amountInput),
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift:26]: Can you validate that this doesn't crash if you enter alpha-numeric characters? I remember having a crash when I had `BDouble(value, radix: 16)` where value included non-hex digits

File: BraveWallet/Crypto/Stores/Address.swift [hunk 10]
```diff
@@ -22,7 +22,14 @@ extension String {
...
-    return dropFirst(2).allSatisfy(\.isHexDigit)
+    
+    // removing `0x`
+    let hex = removingHexPrefix
+    if hex.count >= 40 {
+      // Check the rest of the char is a hex digit
+      return hex.allSatisfy(\.isHexDigit)
+    } else {
+      return false
+    }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/Address.swift]: Can be simplified to `return hex.count == 40 && hex.allSatisfy(\.isHexDigit)`

File: BraveWallet/Crypto/Stores/Address.swift [hunk 11]
```diff
@@ -22,7 +22,14 @@ extension String {
   var isAddress: Bool {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/Address.swift]: Can be renamed to `isETHAddress`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
