### PR TITLE
Fix #2849: Archive.is webcompat. Domain specific user scripts refactor.

### LINKED ISSUE #2849: archive.is lists Brave as 'unsupported browser'
### Steps to Reproduce 
  1. visit archive.is

**Actual result:** 
'Unsupported browser' message is showing.

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #2849 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Browser through youtube.com and archive.is websites, see if they work well

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by kylehickinson** [comment]
Is this still needed?

**Comment by iccub** [comment]
yes it is, just asked Ryan

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 1]
```diff
@@ -45,21 +46,44 @@ class UserScriptManager {
...
+    var domainUserScript: DomainUserScript? {
         didSet {
-            if oldValue == isYoutubeAdblockEnabled { return }
+            if oldValue == domainUserScript { return }
             reloadUserScripts()
         }
     }
     
-    init(tab: Tab, isFingerprintingProtectionEnabled: Bool, isCookieBlockingEnabled: Bool, isU2FEnabled: Bool, isPaymentRequestEnabled: Bool, isYoutubeAdblockEnabled: Bool) {
+    func handlerDomainUserScript(for url: URL) {
```
Comment (iccub) [inline Client/Frontend/Browser/UserScriptManager.swift]: typo: should be `handle`

**Review by Brandon-T — APPROVED** [review]
