### PR TITLE
Fix #290: Leave URL bar overlay mode when deleting tabs/opening new URLs

### LINKED ISSUE #290: Closing a new tab retains the url overlay state & favourites screen on newly selected tab
### Description: 
Close new tab retains the webview on current active tab

### Steps to Reproduce 
  1. Visit a site on a new tab
  2. Open a new tab with + button
  3. Close the new tab from step 2, Current active tab from step 1 shows up on title but tab view still has new tab content. Press cancel shows the actual tab content 

**Actual result:** 
https://drive.google.com/open?id=1iyaOe6Ny_bBuk9eWztxLYMaWQvPBXqYN

**Expected result:**
Should not do this

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
18.8.3.14

**Device details:** 
iPhone 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc: @tmancey

### PR DESCRIPTION
**Pull request by kylehickinson**
## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

_None included_

## Notes for testing this patch

Prelude tests with creating a new tab or entering URL bar overlay

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -975,6 +975,11 @@ class BrowserViewController: UIViewController {
     }
 
     func openURLInNewTab(_ url: URL?, isPrivate: Bool = false, isPrivileged: Bool) {
+        if urlBar.inOverlayMode {
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift]: Is this check necessary, can we just call `urlBar.leaveOverlayMode(didCancel: true)` regardless of our current state?

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: Im not actually sure if it is, it's just how it was setup in previous calling sites. I'll double check.

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: I checked, it seems that `leaveOverlayMode(didCancel:)` makes a delegate call regardless of if it actually left overlay mode (`urlBarDidLeaveOverlayMode`), which would technically incorrect if it didn't leave overlay mode.

Maybe a better solution would be to add the check if its in overlay mode to that method instead like: 

```swift
func leaveOverlayMode(didCancel cancel: Bool = false) {
    if !inOverlayMode { return }
    locationTextField?.resignFirstResponder()
    animateToOverlayState(overlayMode: false, didCancel: cancel)
    delegate?.urlBarDidLeaveOverlayMode(self)
}
```

Comment (jhreis) [reply Client/Frontend/Browser/BrowserViewController.swift]: That looks good assuming you are confident the impact won't cause other side effects.

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: I'll have to double-check all the calls to it first, but I think it should be good.

**Comment by kylehickinson** [comment]
Updated to now remove redundant checks to `inOverlayMode`

**Review by jhreis — APPROVED** [review]
