### PR TITLE
Fix #2584: No longer check clipboard if ref code exists on launch.

### LINKED ISSUE #2584: Super Referral Clipboard Check Improvements
### Description: 

Currently when the app launches, it checks the clipboard for a referral code. Following this, it pings the server to retrieve a download id. If this fetch fails, and the app is thrown from memory, it will read from the clipboard again.

The clipboard may have been cleared, but it will still attempt to look at it, and will even replace the ref-code if a new one exists.

A check should be added to prevent re-reading from the clipboard.

Related:
https://github.com/brave/brave-ios/pull/2574/files#r431366934
https://github.com/brave/brave-ios/pull/2574
https://github.com/brave/brave-ios/pull/2535

### Steps to Reproduce 
  1. Copy a referral link (or retrieve from website) `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123`
  1. Disable internet
  1. Launch Brave (reads from clipboard)
  1. See ref code in settings
  1. Force quit Brave
  1. Copy new ref code (`F83AB73F-9852-4F01-ABA8-7830B8825993:XYZ789`)
  1. Re-open Brave (internet still off)
  1. Look at clipboard, see new ref-code

**Actual result:** 

Ref code is replaced

**Expected result:**

Old ref code should not be overwritten

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by jhreis**
## Summary of Changes

This pull request fixes #2584

No longer allow ref codes to be overwritten from clipboard on subsequent launches when network request fails.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

  1. Copy a referral link (or retrieve from website) `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123`
  1. Disable internet
  1. Launch Brave (reads from clipboard)
  1. See ref code in settings
  1. Force quit Brave
  1. Copy new ref code (`F83AB73F-9852-4F01-ABA8-7830B8825993:XYZ789`)
  1. Re-open Brave (internet still off)
  1. Look at settings, should still see same / old ref-code
  1. Quit~~e~~ Brave 
  1. Enable internet
  1. Re-open Brave
  1. Check logs (should see some server response, either invalid code, or a download id)

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Application/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -260,9 +260,28 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
...
+                
+                // Setting this to an explicit value so it will never get overwritten on subsequent launches.
+                // Upgrade users should not have ref code ping happening.
+                Preferences.URP.referralLookupOutstanding.value = isFirstLaunch
+            }
+            
+            if Preferences.URP.referralLookupOutstanding.value == true {
+                var refCode: String?
+                
+                if Preferences.URP.referralCode.value == nil {
```
Comment (jumde) [inline Client/Application/Delegates/AppDelegate.swift:275]: @jhreis - You missed setting the `refcode = Preferences.URP.referralCode.value` if the value is not nill.

Comment (jhreis) [reply Client/Application/Delegates/AppDelegate.swift:275]: That's set later, when it processes the ref code, the URP class takes care of that.

**Review by iccub — APPROVED** [review]

File: Client/Application/Delegates/AppDelegate.swift (hunk 1 above)
Comment (jumde) [reply Client/Application/Delegates/AppDelegate.swift:275]: Makes sense, all good 👍

**Review by jumde — APPROVED** [review]
