### PR TITLE
Fix #7642: Move reload long press action to UIContext menu action.

### LINKED ISSUE #7642: URL Bar Context Menu is interfering with URL Bar Custom Buttons Long Press Action
### Description: 

The change from using long-press action / action_sheet behaviour for copy-paste actions on URL bar to context menu for URL Bar is blocking long-press actions for custom buttons like refresh or reader mode.

Right now only refresh button has a long press action that presents action sheet for loading the website using desktop/mobile mode.

To fix this the context menu can be triggered from url text field however it is not working due to url bar textfield is having drag and drop delegate.

Need some other idea / solution to handle this.

### Steps to Reproduce 
  1. Long-Press on Refresh button
  2. It selects and activates url bar and shows context menu

### Actual result: 
It selects and activates url bar and shows context menu

### Expected result:
It should show a load website in desktop mode action sheet

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily produced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
I also cleaned up other long press actions

This pull request fixes #7642 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by kylehickinson** [comment]
Why not move the actions into the regular url bar long press context menu? Wouldn't that be simpler?

File: Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift [hunk 1]
```diff
@@ -29,14 +29,6 @@ extension BrowserViewController {
     self.topToolbar.locationView.rewardsButton.iconState = Preferences.Rewards.rewardsToggledOnce.value ? (rewards.isEnabled || rewards.isCreatingWallet ? .enabled : .disabled) : .initial
   }
 
-  func showRewardsDebugSettings() {
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift:32]: We are ok with removing this interaction ?

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift [hunk 2]
```diff
@@ -926,6 +913,51 @@ extension BrowserViewController: ToolbarDelegate {
...
+        image: UIImage(braveSystemNamed: icon),
+        handler: UIAction.deferredActionHandler { [weak tab] _ in
+          tab?.switchUserAgent()
+        })
+
+      let copyMenu = UIMenu(title: "", options: .displayInline, children: [copyAction])
+      
+      actionMenu = [copyMenu]
+      
+      return UIMenu(title: "", identifier: nil, children: actionMenu)
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift]: Action Menu is not edited, it can be removed and action can be added here direct

return UIMenu(title: "",  identifier: nil, children:  [copyMenu])

**Review by soner-yuksel — COMMENTED** [review]
Nice solution, just couple of nits

File: Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift (hunk 1 above)
Comment (iccub) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift:32]: No need to duplicate QA functionality, it's 1 tap away from the settings screen and our Ads/Rewards usage on iOS is light.
What do you think @kylehickinson

Comment (kylehickinson) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift:32]: Its technically been broken ever since we added the context menu anyways, so fine to remove it IMO

Comment (iccub) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BVC+Rewards.swift:32]: yeah. we will readd if needed. also as a contextmenu action to mvoe away from gesture recognizers

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift [hunk 3]
```diff
@@ -953,6 +956,8 @@ extension BrowserViewController: UIContextMenuInteractionDelegate {
         pasteMenuChildren.reverse()
       }
       
+      var copyMenu: UIMenu?
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift]: Why optional?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift (hunk 3 above)
Comment (iccub) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+ToolbarDelegate.swift]: I can remove. I was playing with logic updates so no copy action if on ntp for example

**Comment by iccub** [comment]
Zrzut ekranu 2023-08-8 o 18 56 00

**Review by soner-yuksel — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
