### PR TITLE
Fix #1654, Fix #1656, Fix #1861: Add support for claiming virtual grants

### LINKED ISSUE #1654: Implement virtual grants

### LINKED ISSUE #1656: Add support for claiming a grants
When a grant is available the user can claim it on the settings screen (or a notifications). 

This needs to be integrated from both points (`solveGrantCaptcha`)

No expiration date when claiming ads earnings in the grant claim screen

Blocked by https://github.com/brave/brave-core/pull/3294

### LINKED ISSUE #1861: Enrol with attestation servers if previous enrolment fails
If for some reason the first enrolment fails (when the user creates a wallet/enables rewards), we need to make sure to try again to ensure that they can claim promotions.

We will do this when it the user attempts to claim a promotion.

We should make sure only to do this if:
1. We haven't successfully enrolled in the past, _or_
2. There is no private key in the secure enclave, therefore we wouldn't be able to attest a promotion anyways

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes issue #1654
This pull request fixes issue #1656 
This pull request fixes issue #1861 
 
## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Set environment to dev
- Enable rewards
- Wait 30s until grants come in
- Claim one!

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Extensions/BraveLedgerExtensions.swift [hunk 1]
```diff
@@ -117,6 +120,90 @@ extension BraveLedger {
...
+              completion(false)
+              return
+            }
+            
+            let solution = PromotionSolution()
+            solution.noonce = noonce
+            solution.signature = verification.signature
+            do {
+              solution.blob = try verification.attestationBlob.bsonData().base64EncodedString()
+            } catch { }
```
Comment (iccub) [inline BraveRewardsUI/Extensions/BraveLedgerExtensions.swift]: scary to have empty catch all, can we add a log at least? Or is it too spammy here

**Review by iccub — CHANGES_REQUESTED** [review]

File: BraveRewardsUI/Extensions/BraveLedgerExtensions.swift [hunk 2]
```diff
@@ -4,6 +4,9 @@
 
 import Foundation
 import BraveRewards
+import Shared
+
+let log = Logger.rewardsLogger
```
Comment (iccub) [inline BraveRewardsUI/Extensions/BraveLedgerExtensions.swift]: Make private

File: BraveRewardsUI/Extensions/BraveLedgerExtensions.swift (hunk 1 above)
Comment (kylehickinson) [reply BraveRewardsUI/Extensions/BraveLedgerExtensions.swift]: No I can totally add a log at the very least, thanks for catching.

File: BraveRewardsUI/Extensions/BraveLedgerExtensions.swift (hunk 2 above)
Comment (kylehickinson) [reply BraveRewardsUI/Extensions/BraveLedgerExtensions.swift]: Whooooooooooooooops

File: BraveRewardsUI/Extensions/BraveLedgerExtensions.swift [hunk 3]
```diff
@@ -117,6 +120,90 @@ extension BraveLedger {
...
+  }
+  
+  public func claimPromotion(_ promotion: Promotion, completion: @escaping (_ success: Bool) -> Void) {
+    guard let paymentId = self.paymentId else { return }
+    let deviceCheck = DeviceCheckClient(environment: BraveLedger.environment)
+    let group = DispatchGroup()
+    if !DeviceCheckClient.isDeviceEnrolled() {
+      group.enter()
+      setupDeviceCheckEnrollment(deviceCheck) {
+        if !DeviceCheckClient.isDeviceEnrolled() {
```
Comment (Brandon-T) [inline BraveRewardsUI/Extensions/BraveLedgerExtensions.swift:170]: In the future since this is not a blocker, we can just check the callback of the enrollment for an error. If the callback returns nil, it’s successful. That way we don’t have to even check keychain. But for now it’s fine :)

**Review by Brandon-T — APPROVED** [review]

**Review by iccub — APPROVED** [review]
Approving to not block you over night, please address the two review comments
