### PR TITLE
Fix #2955: Open external link by other navigation action types too.

### LINKED ISSUE #2955: Unable to join Teams Meeting link in Brave/IOS
### Description: 
Unable to join meeting link in Teams via Brave/IOS

### Steps to Reproduce 
  1. From Teams, send invite to an email address (this can be done via Desktop)
  2. Open email, and copy link into Brave
  3. Button to join meeting, doesn't work.

**Actual result:** 
https://streamable.com/xhgcjz

Link (may/maynot work):
`https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3A29fe3a4374614791bfe0b3e74edaa876%40thread.skype%2F1602551536715%3Fcontext%3D%257b%2522Tid%2522%253a%2522e14e1473-6808-4288-83ac-8006a7fcfa6d%2522%252c%2522Oid%2522%253a%2522bc208d3f-9992-4ff1-8ac5-9701140daead%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=6ed5143f-6d82-4150-93ce-b00d89b9ee38&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true`

**Expected result:**
Let user join meeting

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily, Shields not affecting it.

**Brave Version:** 
Tested in Brave Release (IOS) and Brave Beta (IOS)

**Device details:** 
iPhone 8Plus

**Website problems only:**
- did you check with Brave Shields down? Yes, doesn't work.
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes

### Additional Information
Was reported here:
https://old.reddit.com/r/brave_browser/comments/j945m3/cant_click_on_teams_invitation_link_on_brave_ios/

Seems the issue is launching the teams app from within Brave.  This is  what occurred in Firefox/IOS:
teams-ff

### PR DESCRIPTION
**Pull request by iccub**
Previously we opened external links only when navigation action type
was `linkActivated`. This is not always the case, sometimes tapping
on a link has a different navigation type.

This is a followup to #551 ticket.

## Summary of Changes

This pull request fixes #2955 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Try to open a zoom link and make it switch to the external Zoom app.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -267,10 +267,14 @@ extension BrowserViewController: WKNavigationDelegate {
             return
         }
 
-        // Ignore JS navigated links, the intention is to match Safari and native WKWebView behaviour.
-        if navigationAction.navigationType == .linkActivated {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:271]: opening a zoom scheme link triggers `case other = -1` navigation type for some reason..
now we match what Firefox does

**Review by kylehickinson — APPROVED** [review]
