### PR TITLE
Fix #6979: Fetch the largest possible favicon

### LINKED ISSUE #6979: Preloaded favicons are updated after visiting url
### Description: 
The preloaded favicons are updated with lower res icons after visiting url

### Steps to Reproduce 
  1. Install 1.48
  2. From NTP, tap on amazon or wikipedia favorites
  3. Open new tab
  4. Try visiting another url via the favorites

### Actual result: 

Before | After
-|-
IMG_1009 | IMG_1008

https://user-images.githubusercontent.com/17885425/220415284-2f553079-5b7a-48c3-852b-d28e374a7a83.MP4

### Expected result:
Icons should not be replaced 

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version:  `1.48 (23.2.16.28)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone, iPad, iOS 16, 15

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fetches the largest possible favicon, instead of copying Chromium.
- Hide background on icons that have no transparent edges (amazon icon).

This pull request fixes #6979

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Screenshots:
New Tab Page:
image

New Tab Page (Suggestions):
image

Tab Switcher:
image

Tab Switcher (iPad):
image

Bookmarks:
image

New Bookmark:
image

History (iPhone):
image

History (iPad):
image

Widgets (iPhone):
image

Widgets (iPad):
image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Favicon/FaviconFetcher.swift [hunk 1]
```diff
@@ -64,7 +64,7 @@ public class FaviconFetcher {
   @MainActor
   public static func monogramIcon(url: URL, monogramString: Character? = nil) async throws -> Favicon {
     // Render the Monogram on a UIImage
-    guard let attributes = BraveCore.FaviconAttributes.withDefaultImage() else {
+    guard let attributes = BraveCore.FaviconAttributes(image: Favicon.defaultImage) else {
```
Comment (soner-yuksel) [inline Sources/Favicon/FaviconFetcher.swift]: Do we need this part ?I thought we were using the default image inside the iOS project now ?

Comment (Brandon-T) [reply Sources/Favicon/FaviconFetcher.swift]: Fixed

**Review by kylehickinson — APPROVED** [review]
