### PR TITLE
Fix #2121 - Shields not obeying their domain toggle.

### LINKED ISSUE #2121: All Shields Toggle doesn't work
### Description: 
When toggling all shields, it doesn't disable properly.

### Steps to Reproduce 
  1. Enable "Block Scripts" from the shields menu in the URL bar
  2. Toggle the "All Shields" option to OFF
  3. Notice that the pages still don't load because it didn't take effect.

**Actual result:** 
Shields are still on

**Expected result:**
Shields to be off

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
**Security Review:**
- https://github.com/brave/security/issues/32

- Fixed shields not obeying their domain toggle.
- Fixed crash due to tabs being killed on a background thread.

**Steps to Reproduce:**
1. Turn on "Block Scripts" toggle.
2. Visit a website and notice some things don't load.
3. Turn OFF the site-shield toggle.
4. Notice that the page refreshed but scripts are still blocked!

**Fix:**
1. This PR fixes it so that if you turn off "All Toggles"/"Site Shield", it will disable all shields.
2. If you turn all toggles/site shield, it should show all your previous toggles with their previous settings.

## Summary of Changes

This pull request fixes issue #2121

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -214,10 +215,18 @@ extension BrowserViewController: WKNavigationDelegate {
...
-                webView.configuration.preferences.javaScriptEnabled = !domainForShields.isShieldExpected(.NoScript)
+                webView.configuration.preferences.javaScriptEnabled =
+                    domainForShields.isAllShieldsOff()
+                    ||
+                    !domainForShields.isShieldExpected(.NoScript)
+                
+                print(webView.configuration.preferences.javaScriptEnabled)
             }
             
             //Cookie Blocking code below
```
Comment (diracdeltas) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: i think cookie blocking should also be disabled when shields is off?

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: @diracdeltas Cookie blocking isn't on the shields panel. Cookie blocking is in settings where you have to explicitly turn on "Block All Cookies" (this is why I left it because I didn't want to enable/disable something the user cannot see as a toggle/option).

Panel:
image


Settings (block all cookies):
image

In other words, Cookie Blocking isn't a shield on iOS (Desktop has it as a shield).

Comment (diracdeltas) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:224]: ah i forgot it wasn't in shields on iOS

File: Client/Frontend/Browser/FaviconHandler.swift [hunk 2]
```diff
@@ -28,7 +28,7 @@ class FaviconHandler {
             return deferMaybe(FaviconError())
         }
 
-        let deferred = Deferred<Maybe<(Favicon, Data?)>>()
+        let deferred = Deferred<Maybe<(Favicon, Data?)>>(value: nil, defaultQueue: .main)
```
Comment (iccub) [inline Client/Frontend/Browser/FaviconHandler.swift:31]: why does it need to run on main queue, do you remember?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 3]
```diff
@@ -214,10 +215,16 @@ extension BrowserViewController: WKNavigationDelegate {
                 off.compactMap { $0.rule }.forEach(controller.remove)
               
                 if let tab = tabManager[webView] {
-                    tab.userScriptManager?.isFingerprintingProtectionEnabled = domainForShields.isShieldExpected(.FpProtection)
+                    tab.userScriptManager?.isFingerprintingProtectionEnabled =
+                        !domainForShields.isAllShieldsOff()
+                        &&
+                        domainForShields.isShieldExpected(.FpProtection)
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Wouldn't it be better to put `!domainForShields.isAllShieldsOff()` logic inside of `isShieldExpected`?

It makes more sense and we can still exclude it for safe browsing.

Now it's easy to forget to add `isAllShieldsOff` for all cases

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: I tried that, it breaks the UI for some reason. The toggles actually show the wrong state on initial opening of the panel if I do that because this function isn't just for the shields, it's used for the UI as well.

File: Client/Frontend/Browser/FaviconHandler.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/FaviconHandler.swift:31]: Because it crashes if it doesn't: https://bravesoftware.slack.com/archives/GB9CJGQV6/p1575324798015800

Comment (Brandon-T) [reply Client/Frontend/Browser/FaviconHandler.swift:31]: Because it crashes if it doesn't: https://bravesoftware.slack.com/archives/GB9CJGQV6/p1575324798015800

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 3 above)
Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: What do you think about adding `considerAllShieldsOff` parameter to  `isShieldExpected` method?
And set that param to `false` in cases that break UI

File: Client/Frontend/Browser/FaviconHandler.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Browser/FaviconHandler.swift:31]: thanks

**Review by iccub — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
