### PR TITLE
Fix #1349: Touch key dialog should be displayed once 

### LINKED ISSUE #1349: Touch key dialog shows up multiple times on hitting cancel
### Description: 

If the user clicks `cancel` on the touch key dialog it should return an error. The dialog pops-up multiple times before showing an error.

### Steps to Reproduce 
  1. Navigate to demo.yubico.com/u2f
  2. Click register
  3. Hit cancel

### Test Plan
Specified here: https://github.com/brave/brave-ios/pull/1356

**Actual result:** 
The dialog box shows up again

**Expected result:**
Should return an error

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by jumde**
Fix #1349 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

1. Open 5 tabs
2. Navigate to demo.yubico.com/u2f
3. Initiate the registration workflow
4. Confirm that the dialog to touch the key only shows up once.

### Screenshots:

Screen Shot 2019-08-08 at 2 32 00 PM

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/U2FExtensions.swift [hunk 1]
```diff
@@ -238,6 +239,12 @@ class U2FExtensions: NSObject {
         currentMessageType = U2FMessageType.FIDO2Create
         currentHandle = handle
         
+        guard let tabId = tab?.id else {
```
Comment (jhreis) [inline Client/U2FExtensions.swift]: This is copy/pasted in like 4 places, and I see that these function implementations are pretty much identical, can we abstract these?

Also, this file is quite massive and contains almost no comments, moving forward it may be good to start addign some to newly added code.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/U2FExtensions.swift (hunk 1 above)
Comment (jumde) [reply Client/U2FExtensions.swift]: on it 👍

**Review by iccub — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
