### PR TITLE
Fix #4473: Remove YubiKit dependency and use the built in WebKit APIs

### LINKED ISSUE #4473: Deprecate Yubico sdk in favor of built-in webauth of WKWebView
WebAuth added most of webauth items we need, and maintaining this sdk might not be worth anymore.

Remove yubico sdk and corresponding webauth javascript files.
To verify and check what is supported by webkit what not, you can use the google doc from this ticket
https://github.com/brave/security/issues/649

### LINKED ISSUE #4857: Unable to use yubikey (fido) in Ipad
### Description: 

Hi,

I'm using brave recently, and I tried to login into my Google account with 2FA, using key (Yubikey), where the Browser popup a modal screen indicating to insert the key, ones I insert the key, doesn't go on, stay with the popup on. I try in Firefox, with the same process to login to my Google account and using the same yubikey, and works properly, maybe its an issue with Brave.

### Steps to Reproduce 
  1. Goes to Account.google.com, input my credentials.
  2. Google request de 2fa with the key
  3. Brave popup a modal screen indicating to insert the key; and stuck here.

image

**Expected result:**
Login to my account of google using the key

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:**
Brave Version 1.34 (22.1.10.19)

**Device details:**
Device iPad13,6 (iPadOS 15.2.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

I check with Firefox and works.

### PR DESCRIPTION
**Pull request by Brandon-T**
## Security Review
- https://github.com/brave/security/issues/695

## Summary of Changes
- Remove YubiKit dependency and use the built in WebKit APIs which are available only if the `Default Browser Entitlement` is used.
- The app does NOT have to be the default browser, it just has to have the entitlement.

This pull request fixes #4473

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [ x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Test on: https://demo.yubico.com/webauthn-technical/registration
- Test on Github Sign-In or Gmail Sign-In or any website with WebAuthN
- Test on https://webauthn.io/ or https://webauthn.me/

## Screenshots:

image
image
image
image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/Extensions/StringExtensions.swift [hunk 1]
```diff
@@ -28,4 +28,9 @@ extension String {
         }
         return words
     }
+    
+    /// Encode a String to Base64
+    public func toBase64() -> String {
+        return Data(self.utf8).base64EncodedString()
+    }
```
Comment (nuo-xu) [inline BraveShared/Extensions/StringExtensions.swift:35]: Can we create a unit test for it?

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 2]
```diff
@@ -174,28 +164,6 @@ class UserScriptManager {
         return WKUserScript(source: source, injectionTime: .atDocumentStart, forMainFrameOnly: false)
     }()
     
-    // U2FUserScript is injected at document start to avoid overriding the low-level
-    // FIDO legacy sign and register APIs that have different arguments
-    private let U2FUserScript: WKUserScript? = {
-        guard let path = Bundle.main.path(forResource: "U2F", ofType: "js"), let source = try? String(contentsOfFile: path) else {
```
Comment (iccub) [inline Client/Frontend/Browser/UserScriptManager.swift:180]: those js files can be removed too

File: BraveShared/Extensions/StringExtensions.swift (hunk 1 above)
Comment (Brandon-T) [reply BraveShared/Extensions/StringExtensions.swift:35]: This is a built in Apple API (`base64EncodedString`). All I did was move the code to the StringExtension as it existed in three places. So now it exists in one.

**Review by soner-yuksel — APPROVED** [review]
