### PR TITLE
Fix #5461: Infinite redirect loop between amp page and non-amp page

### LINKED ISSUE #5461: Infinite redirect loop between amp page and non-amp page
### Description: 
Infinite redirect on the following urls 
* https://digiday.com/marketing/googles-david-temkin-sheds-light-on-the-companys-preparations-for-disabling-third-party-cookies/amp/
* https://thehustle.co/06022022-elvis-vegas-weddings
* https://t.co/0Ydr4haUQd 

https://user-images.githubusercontent.com/909331/172476022-8bc811d4-16d0-4a44-9395-9f0d565e3aa9.MP4

### Steps to Reproduce 
  1. Enable de-amping
  2. Navigate to the url above

**Actual result:** 
Infinite load loop between amp and non-amp page

**Expected result:**
Should load the page without an infinite redirect (in this case, amp should fail and load the amp page)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.39

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down?
no issue with brave shields down because its caused by enabling brave shields. But this is still a de-amp issue.
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes. Only an iOS issue

### Additional Information
This is caused by a battle between de-amping forcing a non-amp page and the server hosting the website forcing the amp page.

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #5461 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

See steps on the ticket

## Screenshots:

See video on ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Helpers/DeAmpHelper.swift [hunk 1]
```diff
@@ -0,0 +1,72 @@
+//
+//  DeAmpHelper.swift
+//  
+//
+//  Created by Jacob on 2022-06-07.
```
Comment (iccub) [inline Client/Frontend/Browser/Helpers/DeAmpHelper.swift]: copy MPL license from some other file

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 2]
```diff
@@ -174,16 +174,29 @@ class UserScriptManager {
...
-      in: .defaultClient)
+    
+    do {
+      let arguments = try UserScriptHelper.makeDeAmpScriptParamters()
+      
+      source = [
+        source,
+        "window.braveDeAmp(\(arguments))",
+        "delete window.braveDeAmp"
+      ].joined(separator: "\n")
```
Comment (Brandon-T) [inline Client/Frontend/Browser/UserScriptManager.swift:189]: nit: Would be a bit more clear to use:
```swift
"""
\(source)
window.braveDeAmp(\(arguments));
delete window.braveDeAmp;
"""
```

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/UserScriptManager.swift (hunk 2 above)
Comment (cuba) [reply Client/Frontend/Browser/UserScriptManager.swift:189]: Honestly I don't like that way that `"""` formats things (Because it includes your tabbing) plus I think joined is slightly faster than `"\(somestring)"`

**Review by iccub — APPROVED** [review]
