### PR TITLE
Fix #3838: Improve menu accessibility

### LINKED ISSUE #3838: Very difficult to dismiss the new menu while VoiceOver is active
### Description: 

While VoiceOver is active it is very difficult/near impossible to dismiss the new menu once its been displayed.

We should remedy this in two ways:
- Support the scrub gesture (2-finger z shape swipe -- "Dismiss an alert or return to the previous screen") which will trigger menu dismissal
- Increase the space from the top of the screen to add the ability to tap the background to dismiss

### Steps to Reproduce 
  1. Turn on VoiceOver
  2. Open the new menu (•••)

**Actual result:** You can't dismiss the new menu with VoiceOver gestures

**Expected result:** You should be able to dismiss the new menu without selecting Playlist or an action that dismisses it for you such as page actions

**Reproduces how often:** Always while VoiceOver is active

**Brave Version:** 1.26+

### PR DESCRIPTION
**Pull request by kylehickinson**
- Adds support for accessibility escape while VoiceOver is active
- Increases the top inset so there is always space to tap to dismiss the menu

## Summary of Changes

This pull request fixes #3838 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- With VoiceOver active, verify that you can perform a two finger scrub (drawing z shape with two fingers) to dismiss the menu
- Verify there is now sufficient space at the top of the menu to tap the background to dismiss even when the menu is expanded

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 1]
```diff
@@ -198,7 +203,7 @@ extension MenuViewController: PanModalPresentable {
         return _scrollViewChild(in: topVC.view)
     }
     var longFormHeight: PanModalHeight {
-        .maxHeight
+        .maxHeightWithTopInset(32)
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:206]: Is this for this ticket or the last-bookmark-hidden one?

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:206]: That is for this ticket:

> Increases the top inset so there is always space to tap to dismiss the menu

It helps VoiceOver users or users with motor function disabilities to dismiss by tapping the background instead of being forced to dismiss by gesture

**Review by soner-yuksel — APPROVED** [review]
