### PR TITLE
Fix #3570 - Fixes Add to Playlist Share Menu allowing you to add duplicate items

### LINKED ISSUE #3570: Disable Add to Brave Playlist via share sheet if the video is already added via toast/share sheet
### Description: 
Disable Add to Brave Playlist via share sheet if the video is already added via toast/share sheet

### Steps to Reproduce 
  1. Visit a media link
  2. Add to playlist via toast/share sheet
  3. Add the same video multiple times via share sheet

**Actual result:** 

**Expected result:**
Should probably detect if the video is added to playlist already and not show the add option in share sheet

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.21.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Adds new activity to share menu for `View In Playlist`.
- Fixes Add to Playlist allowing you to add duplicate items by checking if the item exists first in the JS callback.

This pull request fixes #3570

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1769,6 +1770,19 @@ class BrowserViewController: UIViewController {
             }
         }
         
+        let openInPlayListActivity = OpenInPlaylistActivity() { [unowned self] in
+            guard let item = self.openInPlaylistActivityItem?.item else { return }
+            
+            // Update playlist with new items..
+            self.openInPlaylist(item: item) { [weak self]  in
+                guard let self = self else { return }
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: self not used in this block?

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
