### PR TITLE
Fix #3530 - Detecting file sizes for HLS streams!

### LINKED ISSUE #3530: On iPad, offline videos show wrong size
### Steps to Reproduce 
  1. Install on an iPad
  2. Go to youtube, pick a video
  3. Add it to playlsits
  4. Go to to playlists screen

**Actual result:** 
Very small download size value is shown,

IMG_0198

**Expected result:**
The download size should be bigger

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #3555: Update "Add to Playlist" text
### Description: 
Please update the "Add to Playlist" text to "Add to Brave Playlist" 

There are 3 or more places where the text needs to change, 

- toast
- long press menu
- In the share section
- In settings

possibly more.

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes HLS stream sizes by iterating through all the files in a `.movpkg`.
- Although `.movpkg` seems like a file, it is NOT.. It's a folder that contains all the media fragments of the stream.. and iOS does NOT give the correct folder size! So to get the size, we enumerate all files in the folder. This seems to be correct as it reports the exact same size as "Settings.app"! So now we have proper file sizes showing.

This pull request fixes #3530, fixes #3555

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift [hunk 1]
```diff
@@ -101,13 +101,37 @@ class PlaylistManager: NSObject {
...
+                let formatter = ByteCountFormatter()
+                formatter.zeroPadsFractionDigits = true
+                formatter.countStyle = .file
+                return formatter.string(fromByteCount: Int64(totalSize))
+            }
+            
+            if let size = try? FileManager.default.attributesOfItem(atPath: asset.url.path)[.size] as? Int {
+                let formatter = ByteCountFormatter()
+                formatter.zeroPadsFractionDigits = true
+                formatter.countStyle = .file
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift]: Formatter setup can be moved out of these 2 conditions you added, to declare it in a single place

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift [hunk 2]
```diff
@@ -101,13 +101,37 @@ class PlaylistManager: NSObject {
...
+                guard let enumerator = FileManager.default.enumerator(at: asset.url,
+                                                                      includingPropertiesForKeys: properties,
+                                                                      options: .skipsHiddenFiles,
+                                                                      errorHandler: nil) else {
+                    return nil
+                }
+                
+                let resources = enumerator.compactMap({ try? ($0 as? URL)?.resourceValues(forKeys: Set(properties)) })
+                                          .filter({ $0.isRegularFile == true })
+                let sizes = resources.compactMap({ $0.totalFileAllocatedSize })
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift]: Since we do this functional convention we can assign it to a single property after all modifications are done, no need to have `resources` constant imo

Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift]: image

Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift]: I fixed it up by removing the `.reduce` and just putting it in the subsequent expression :D
Seems to work fine.

Comment (iccub) [reply Client/Frontend/Browser/Playlist/Cache/PlaylistManager.swift]: Too early for functional Swift I guess :)

**Review by iccub — APPROVED** [review]
