### PR TITLE
Fix #3762 - Fixes Search Overlay spacing, prompt, actions, and ordering

### LINKED ISSUE #3762: Search Overlay Issues
- [x] In dark mode - Prompt to enable recent searches needs white text on "enable" button (currently displaying dark color which makes it hard to read)
- [ ] Maybe an issue: doesn't seem that all searches are being logged in recents.
- [x] Add 10px more spacing between bottom of favorites section and Recent search section in search overlay.
- [x] Move "On this page" directly below the search engine pre-search suggestions (should be above history/bookmarks)
- [x] "Clear" needs to have a confirmation action sheet pop up before clearing recents. No title just two buttons "Clear Recent" (destructive) and "Cancel"
- [ ] If possible add swipe-to-delete on individual "recents" rows.

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes the arrow button on search overlay to immediately submit the search engine url and QRCode urls.
- Fixes spacing in favourites section
- Fixes text colour to be `.white` instead of `.braveBackground`

## Other
- Cannot reproduce not all searches are showing in recent search
- Cannot add swipe-to-delete on collection views.

This pull request fixes #3762

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 1]
```diff
@@ -359,6 +359,10 @@ extension FavoritesViewController: UICollectionViewDataSource, UICollectionViewD
                 return cell
             }
             
+            cell.setOpenButtonAction { [weak self] in
+                self?.onOpenRecentSearch(recentSearch)
+            }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: `[unowned self]` is probably better here, the `cell` lifetime depends on the VC, so this callback shouldn't ever be hit unless self is alive

File: Client/Frontend/Browser/Search/Recent Search/RecentSearchCell.swift [hunk 2]
```diff
@@ -51,4 +54,13 @@ class RecentSearchCell: UICollectionViewCell, CollectionViewReusable {
     func setAttributedTitle(_ title: NSAttributedString?) {
         titleLabel.attributedText = title
     }
+    
+    func setOpenButtonAction(_ action: (() -> Void)?) {
+        openButtonAction = action
+    }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Search/Recent Search/RecentSearchCell.swift]: Why is this function needed? Just remove `private` from `openButtonAction`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]

File: BraveShared/BraveStrings.swift [hunk 3]
```diff
@@ -2616,4 +2616,5 @@ extension Strings {
     public static let recentSearchScannerTitle = NSLocalizedString("RecentSearchScannerTitle", bundle: .braveShared, value: "Scan QR Code", comment: "Scanning a QRCode for searching")
     public static let recentSearchScannerDescriptionTitle = NSLocalizedString("RecentSearchScannerDescriptionTitle", bundle: .braveShared, value: "Instructions", comment: "Scanning a QRCode for title")
     public static let recentSearchScannerDescriptionBody = NSLocalizedString("RecentSearchScannerDescriptionBody", bundle: .braveShared, value: "To search by QRCode, align the QR in the center of the frame.", comment: "Scanning a QRCode for searching body")
+    public static let recentSearchClearAlertButton = NSLocalizedString("RecentSearchClearAlertButton", bundle: .braveShared, value: "Clear Recent", comment: "The button title that shows when you clear all recent searches")
```
Comment (kylehickinson) [inline BraveShared/BraveStrings.swift:2619]: Make sure to push strings up if this is for 1.27 (cc @iccub)

**Review by iccub — APPROVED** [review]
