### PR TITLE
Fix #1414: Full screen modal presentation style for iOS 13.

### LINKED ISSUE #1414: Modal screens not taking full screen in iOS 13
### Description: 
In iOS 13, view controllers presented modally don't take full screen space, see for example here https://miro.medium.com/max/866/1*JuPvxhMr1isAtYYXG-EDYQ.png

### Steps to Reproduce 
  1. Open app settings
  1. Observe that it is not full screen (see image)

**Actual result:** 
Zrzut ekranu 2019-08-20 o 11 01 48

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

Check if settings screen is showing correctly on iPhone iOS 13

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 1]
```diff
@@ -180,9 +180,18 @@ class MenuViewController: UITableViewController {
     private enum DoneButtonPosition { case left, right }
     private typealias DoneButton = (style: UIBarButtonItem.SystemItem, position: DoneButtonPosition)
     
-    private func open(_ viewController: UIViewController, doneButton: DoneButton) {
+    private func open(_ viewController: UIViewController, doneButton: DoneButton,
+                      allowSwipeTodismiss: Bool = true) {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift]: minor nit: camel case typo `allowSwipeToDismiss`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
