### PR TITLE
Fix #2237: Show 'my first ad' after tapping on Rewards button on NTP.

### LINKED ISSUE #2237: Sample ad notification is not triggered when enabling rewards via sponsored image onboarding
### Description: 
Sample ad notification is not triggered when enabling rewards via sponsored image onboarding

### Steps to Reproduce 
  1. Clean install 1.14.3
  2. Skip onboarding
  3. View sponsored image 
  4. Tap on learn more to bring up onboarding modal
  5. Tap on `Turn on Rewards`, sample ad notification is not triggered when rewards is enabled

**Actual result:** 
Sample ad notification is not triggered when enabling rewards via sponsored image onboarding

**Expected result:**
Sample ad notification should be triggered irrespective of how rewards is enabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
About 80% time. Sometime ad notification shows up when you open panel other(most) times doesn't show up at all

**Brave Version:** 
1.14.3(20.01.24.18)

**Device details:** 
iPad Pro (iOS 12.4.4)
iPhone 7+ (iOS 13.3.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes issue #2237 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -264,6 +264,18 @@ class BrowserViewController: UIViewController {
...
+            
+            let isRewardsPanelShowing = (self.presentedViewController as? PopoverController)?
+                .contentController is RewardsPanelController
+            
+            // We do not want to show first ad when Rewards panel is opened. This happens when user
+            // enabled Rewards for the first time in the panel. In that case the ad will show after
+            // the panel is closed.
+            // This call is used if Rewards are enabled from another location, for example when user
+            // enables Rewards in one of NTP notifications.
+            if !isRewardsPanelShowing {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: This also solves another case when user enables rewards in the panel and closes it right after

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -264,6 +264,18 @@ class BrowserViewController: UIViewController {
             if result == .walletCreated {
                 self.rewards.ledger.setupDeviceCheckEnrollment(client) { }
             }
+            
+            let isRewardsPanelShowing = (self.presentedViewController as? PopoverController)?
+                .contentController is RewardsPanelController
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: This is supposed to happen when the user enables rewards via the NTP notification correct? In that case, it should probably be part of the above check (`result == .walletCreated`)

Also we technically already have code that checks if an ad can show here: https://github.com/brave/brave-ios/blob/5eab26a129be31811365cf74961e8b08fe2658cf/BraveRewardsUI/Ads/AdsNotificationHandler.swift#L105-L127

Perhaps we could reuse that instead somehow? (Edit: `notificationsHandler` is in BVC, so you should be able to just call it directly)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
