### PR TITLE
Fix #201: Tab reordering now respects tab type & selects the correct tab

### LINKED ISSUE #201: Tabs open incorrect URL after tabs are reordered in tab tray
### Steps to Reproduce 

Pre-requisite: Start browser in regular browsing mode

  1. Open tab tray
  2. Add 3 tabs within the tab tray
  3. Change to private browsing mode
  4. Add 2 tabs within the tab tray
  5. Reorder tabs within the tab tray
  6. Open a tab within the tab tray

**Actual result:** After moving tabs, tabs should navigate to the correct URL

**Expected result:** After moving tabs, tabs do not navigate to the correct URL

**Reproduces how often:** Everytime

**Brave Version:** Development build hash 93f59d7cb8905acc3dd342c49a8a9f333afd01b1

**Device details:** iPad Pro 10.5" iOS 11.4.1

### PR DESCRIPTION
**Pull request by kylehickinson**
## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

_none included_

## Notes for testing this patch

_none included_

### CODE REVIEW

File: Client/Frontend/Browser/TabManager.swift [hunk 1]
```diff
@@ -346,7 +346,8 @@ class TabManager: NSObject {
             return
         }
 
-        tabs.swapAt(fromIndex, toIndex)
+        let tab = tabs.remove(at: fromIndex)
+        tabs.insert(tab, at: toIndex)
```
Comment (jhreis) [inline Client/Frontend/Browser/TabManager.swift:350]: Is this so it properly selects the tab? If so, should leave a comment _why_ we aren't using the more "intuitive" `swapAt`.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/TabManager.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/TabManager.swift:350]: No this is because using `swapAt` is inherently wrong to use in this case because the UI doesn't swap two tabs, it only moves a single tab and the others are moved based on the new location of that tab.  I don't think we need a comment to use the correct logic :)

edit: I could have at least added a comment to the review at least lol

**Review by jhreis — APPROVED** [review]
