### PR TITLE
Fix #7506, fix #7501: Remove legacy cosmetic filters engine

### LINKED ISSUE #7501: Preroll ads shown as black screen when disabling 'Ads Blocking' in shields
### Description: 
When Ads Blocking is disabled in shields panels, pre-roll ads will show black screen when playing. This does not happen when shields are disabled, the ads play/show normally.

Not a regression. Impacts 1.51, 1.51.1

### Steps to Reproduce 
  1. Install 1.51
  2. Wait a few mins after installing
  3. Open youtube.com
  4. Disable `Tracking & Ads Blocking` toggle in shields
  5. Play a popular video with ads
  6. Observe ad

### Actual result: 
IMG_3220 2

### Expected result:
IMG_3240

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  1.51.x

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone X, iOS 16.3.1

### LINKED ISSUE #7506: Remove legacy cosmetic filtering engine
### Description: 
There is an old CF engine that should have been removed long ago. This is causing problems such as: 
- https://github.com/brave/brave-ios/issues/7501

This legacy CF code was replaced with filter lists, engine script injection and the `SelectorsPollerScript.js`

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes
Removed legacy cosmetic filtering code

This pull request fixes #7506 
This also fixes #7501

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Test any popular (or important) ad-blocking that we have such as YouTube ad-blocking.

## Screenshots:

N/A

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

File: Sources/Brave/WebFilters/BraveS3Resource.swift [hunk 1]
```diff
@@ -12,6 +12,7 @@ enum BraveS3Resource: Hashable, DownloadResourceInterface {
   /// Generic iOS only content blocking behaviours used for the iOS content blocker
   case genericContentBlockingBehaviors
   /// Cosmetic filter rules
+  /// - Warning: Do not use this. This is here solely so we can delete the files
   case generalCosmeticFilters
```
Comment (soner-yuksel) [inline Sources/Brave/WebFilters/BraveS3Resource.swift]: Additionally can you rename this like .deprecatedGeneralCosmeticFilters so name will suggest, it is not proper going to be used anymore.

Comment (cuba) [reply Sources/Brave/WebFilters/BraveS3Resource.swift]: Done
