### PR TITLE
Error URL validation

### LINKED ISSUE #2913: Fix Error URL Loading Side-Effects
### Description: 
- Error URLs use the `url` query parameter which can cause issues if other URLs have this parameter as they aren't validated against local host.

### Steps to Reproduce 
  1. https://github.com/brave/security/issues/231

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Added Error **URL validation** to prevent unintended URL opening.
- Since this is a security issue, the steps to reproduce it, is in the linked security ticket.

This pull request fixes #2913
Security Ticket: https://github.com/brave/security/issues/231

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

**Review by iccub — CHANGES_REQUESTED** [review]
Maybe add unit test for this property?

**Review by iccub — APPROVED** [review]

File: SharedTests/NSURLExtensionsTests.swift [hunk 1]
```diff
@@ -477,6 +477,27 @@ class NSURLExtensionsTests: XCTestCase {
         XCTAssertEqual("http://foo.com/bar/?ppp=123&rrr=aaa", urlE.absoluteString)
     }
     
+    func testLocalQueryParamHandling() {
+        let urlA = URL(string: "http://brave.com?url=https://foo.com")
+        let urlB = URL(string: "http://brave.com/?url=https://foo.com")
+        let urlC = URL(string: "http://brave.com?url=https://foo.com/meh")
+        let urlD = URL(string: "http://localhost/errors/foo.hmtl?url=https://foo.com")
```
Comment (jumde) [inline SharedTests/NSURLExtensionsTests.swift:484]: nit: html

**Review by jumde — APPROVED** [review]
lgtm
