### PR TITLE
Fix #7676: Changing compression priority search button item

### LINKED ISSUE #7676: Voice search icon in the url bar changes size sometimes
### Description: 
Voice search icon in the url bar changes size sometimes depending on the url

papa bear | mama bear | baby bear ( I think)
-|-|-
 |  | 

### Steps to Reproduce 
  1. Install 1.53.x
  2. Navigate to webpage, tap on url and clear
  3. Observe icon size, search again
  4. Repeat a few times

### Actual result: 
Voice search icon does not display the same size

### Expected result:
Should be shown the same size in url bar

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  1.53 (23.6.23.14)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No (New feature)

### Device details: 
iPhone, iOS 16.3.1

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

Changing content compression  and priority search button items

This pull request fixes #7676

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

1. Install 1.53.x
2. Navigate to webpage, tap on url and clear
3. Observe icon size, search again
4. Repeat a few times

## Screenshots:

https://github.com/brave/brave-ios/assets/6643505/55c4ca44-23d9-4c50-bd03-fd901a4efd3a

https://github.com/brave/brave-ios/assets/6643505/f11c4d47-0926-40a1-bc0a-6ff0c60924b1

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift [hunk 1]
```diff
@@ -198,22 +198,30 @@ class TopToolbarView: UIView, ToolbarProtocol {
...
-  private lazy var qrCodeButton = ToolbarButton().then {
+  private var qrCodeButton = ToolbarButton().then {
     $0.accessibilityIdentifier = "TabToolbar.qrCodeButton"
     $0.isAccessibilityElement = true
     $0.accessibilityLabel = Strings.quickActionScanQRCode
     $0.setImage(UIImage(braveSystemNamed: "leo.qr.code", compatibleWith: nil), for: .normal)
     $0.tintColor = .braveLabel
-    $0.addTarget(self, action: #selector(topToolbarDidPressQrCodeButton), for: .touchUpInside)
+    $0.contentEdgeInsets = UIEdgeInsets(top: 0, left: 5, bottom: 0, right: 5)
+    $0.setContentCompressionResistancePriority(UILayoutPriority(rawValue: 1000), for: .horizontal)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift]: UILayoutPriority with a 1000 is just `.required` fyi:

```objc
static const UILayoutPriority UILayoutPriorityRequired API_AVAILABLE(ios(6.0)) = 1000;
```

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift]: true, fixed at https://github.com/brave/brave-ios/pull/7700/commits/db9730aa2742f41b055ff3186e1ca840bbe3440d
