### PR TITLE
Fix #8379: Transaction Details v2 UI

### LINKED ISSUE #8379: Transaction Detail v2
### Description: 

Update Transaction Detail to v2 UI

Send ETH - In Progress | Send ETH - Failed | Send ETH - Success |  Send NFT
--|--|--|--

https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=11042-326457&mode=design&t=ZHC6Meo8jpABcgUY-4

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Updated UI for Transaction Details

This pull request fixes #8379

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Make a few different types of transactions; they do not need to be confirmed (though should confirm at least 1 to verify transaction status states).
2. Open Activity tab and tap on any transaction to open transaction details.
3. Verify From/To/Transaction Fee rows appear below transaction details. 
4. Verify From/To fields copy button copies the respective address
5. Confirm at least 1 transaction.
6. Open transaction details for confirmed transaction.
7. Verify Transaction Hash row appears. Verify copy button copies tx hash, and link button opens the explorer URL.
8. Open accounts detail for an account you made a transaction on, verify transactions open using new Transaction Details UI.
9. Open asset detail for an asset you made a transaction with, verify transactions open using new Transaction Details

## Screenshots:

Send NFT - light | Send NFT - dark | Send ETH - light | Send ETH - dark
--|--|--|--
Approve Value - light | Approve Value - dark | Approve Unlimited - light | Approve Unlimited - dark
Swap - light | Swap - dark | Solana Swap - light | Solana Swap - dark

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift [hunk 1]
```diff
@@ -14,122 +14,569 @@ struct TransactionDetailsView: View {
...
+    }
+  }
+  
+  /// Color of status badge
+  var badgeBackgroundColor: Color {
+    switch self {
+    case .confirmed, .approved:
+      return Color(braveSystemName: .systemfeedbackSuccessBackground)
+    case .rejected, .error, .dropped:
+      return Color(braveSystemName: .systemfeedbackErrorIcon)
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift]: im not sure if this is the correct color for those three statuses. looks too red.
Simulator Screenshot - iPhone 15 Pro - 2023-11-27 at 14 51 34

File: Sources/BraveWallet/Crypto/Stores/TransactionDetailsStore.swift [hunk 2]
```diff
@@ -35,30 +31,36 @@ class TransactionDetailsStore: ObservableObject, WalletObserverStore {
...
     transaction: BraveWallet.TransactionInfo,
+    parsedTransaction: ParsedTransaction?,
     keyringService: BraveWalletKeyringService,
     walletService: BraveWalletBraveWalletService,
     rpcService: BraveWalletJsonRpcService,
     assetRatioService: BraveWalletAssetRatioService,
     blockchainRegistry: BraveWalletBlockchainRegistry,
     solanaTxManagerProxy: BraveWalletSolanaTxManagerProxy,
+    ipfsApi: IpfsAPI,
     userAssetManager: WalletUserAssetManagerType
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/TransactionDetailsStore.swift:59]: i think we also need to add a `TxService` to listen to the change of the status in case user stays in transaction details screen for very long time.

File: Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift [hunk 3]
```diff
@@ -14,122 +14,569 @@ struct TransactionDetailsView: View {
...
-          detailRow(title: Strings.Wallet.transactionDetailsStatusTitle) {
-            HStack(spacing: 4) {
-              Image(systemName: "circle.fill")
-                .foregroundColor(transactionDetailsStore.transaction.txStatus.color)
-                .imageScale(.small)
-                .accessibilityHidden(true)
-              Text(transactionDetailsStore.transaction.txStatus.localizedDescription)
-                .foregroundColor(Color(.braveLabel))
-                .multilineTextAlignment(.trailing)
+            Image(braveSystemName: "leo.arrow.right")
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift:458]: since it's always gonna be inside a 1`VStack` should the image be `leo.arrow.down`?

**Review by nuo-xu — CHANGES_REQUESTED** [review]

File: Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift (hunk 3 above)
Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift:458]: We're still using the right arrow on desktop (& in designs); I think best to keep right arrow for consistency? (Arrow is on separate line on mobile due to screen space)

desktop

File: Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift (hunk 1 above)
Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift]: Good catch, had wrong colour for failed/rejected/dropped status. Fixed in [ff80cea](https://github.com/brave/brave-ios/pull/8474/commits/ff80cead166e23a009d8ce02410d01c89343c439).
Simulator Screenshot - iPhone 15 Pro - 2023-11-28 at 09 53 32

**Review by nuo-xu — APPROVED** [review]
