### PR TITLE
Fix #566 & Migration code for keychain

### LINKED ISSUE #566: Passcode auto enabled after migration
### Description: 
Passcode auto enabled after migration

### Steps to Reproduce 
  1. Enable PB only on 1.6.6
  2. Ensure to select `Not now` in Enable pincode
  3. Upgrade to 1.7(18.12.0.23)
  4. Launch app after upgrade, Passcode is autoenabled. If you don't remember previously set passcode you are screwed

**Actual result:** 
Passcode auto enabled after migration

**Expected result:**
Passcode should not be enabled 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.12.04.23)

**Device details:** 
iPhone 7+(iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by danishjafri88**
This will migrate browser lock settings from 1.6 to 1.7+.

**What this fixes**
#566 
And migrates user browser-lock settings (`isPasscodeRequiredImmediately`) from 1.6 to new builds.  
Prevents security loophole when updating the app (The lock wont be shown when you update from 1.6).

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch
@devs: bundle-id and app-groups has to be same -obviously

what to test:
1. browserlock policy is transfered 
2. passcode is 4 digit long if migrated, and its working
3 verify #566 is fixed

### CODE REVIEW

**Comment by danishjafri88** [comment]
~~Since we use SwiftKeychainWrapper (third party), the decode was crashing/ failing silently and was not debuggable. The Problem was that the class AuthenticationKeychainInfo was not conforming to NSSecureCoding~~
This is not required if all keys are used.

**Comment by kylehickinson** [comment]
What issues does this fix?

File: Shared/AuthenticationKeychainInfo.swift [hunk 1]
```diff
@@ -63,6 +67,8 @@ open class AuthenticationKeychainInfo: NSObject, NSCoding {
         self.useTouchID = aDecoder.decodeAsBool(forKey: "useTouchID")
         if aDecoder.containsValue(forKey: "isPasscodeRequiredImmediately") {
             self.isPasscodeRequiredImmediately = aDecoder.decodeAsBool(forKey: "isPasscodeRequiredImmediately")
+        } else if let interval = aDecoder.decodeObject(forKey: "requiredPasscodeInterval") as? NSNumber {
```
Comment (jhreis) [inline Shared/AuthenticationKeychainInfo.swift:66]: Is this a key from 1.6 that is no longer used in 1.7? (besides here)?

File: Shared/AuthenticationKeychainInfo.swift [hunk 2]
```diff
@@ -25,7 +25,7 @@ public extension KeychainWrapper {
     }
 }
 
-open class AuthenticationKeychainInfo: NSObject, NSCoding {
+open class AuthenticationKeychainInfo: NSObject, NSCoding, NSSecureCoding {
```
Comment (kylehickinson) [inline Shared/AuthenticationKeychainInfo.swift]: You don't have to have both `NSCoding` and `NSSecureCoding`

File: Shared/AuthenticationKeychainInfo.swift [hunk 3]
```diff
@@ -63,6 +67,8 @@ open class AuthenticationKeychainInfo: NSObject, NSCoding {
         self.useTouchID = aDecoder.decodeAsBool(forKey: "useTouchID")
         if aDecoder.containsValue(forKey: "isPasscodeRequiredImmediately") {
             self.isPasscodeRequiredImmediately = aDecoder.decodeAsBool(forKey: "isPasscodeRequiredImmediately")
+        } else if let interval = aDecoder.decodeObject(forKey: "requiredPasscodeInterval") as? NSNumber {
+            self.isPasscodeRequiredImmediately = (interval == 0)
```
Comment (kylehickinson) [inline Shared/AuthenticationKeychainInfo.swift]: `interval` should never be 0 based on 1.6 since `requiredPasscodeInterval` is an `Int` enum which starts at `immediate = 2` and [these lines](https://github.com/brave/browser-ios/blob/development/Shared/AuthenticationKeychainInfo.swift#L81): 

```swift
if var interval = aDecoder.decodeObject(forKey: "requiredPasscodeInterval") as? NSNumber {
    // We have updated the immediate lockout value to 2 from 0 due to timing issues with systemUptime()
    interval = interval == 0 ? 2 : interval
    self.requiredPasscodeInterval = PasscodeInterval(rawValue: interval.intValue)
}
```

So probably best to make this `self.isPasscodeRequiredImmediately = (interval == 2)` or even `(interval <= 2)` for safety

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Comment by jhreis** [comment]
@kylehickinson think this is related to https://github.com/brave/brave-ios/issues/566
Even though exact STR on this issue aren't repro, it is if the user turns on passcode, and turns it off in 1.6, 1.7 thinks it is still enabled.

File: Shared/AuthenticationKeychainInfo.swift (hunk 1 above)
Comment (danishjafri88) [reply Shared/AuthenticationKeychainInfo.swift:66]: Yes, this is used for the isPasscodeRequiredImmediately bool, It will fall in this case only once.

File: Shared/AuthenticationKeychainInfo.swift (hunk 2 above)
Comment (danishjafri88) [reply Shared/AuthenticationKeychainInfo.swift]: yeah didn't notice, Thanks

File: Shared/AuthenticationKeychainInfo.swift (hunk 3 above)
Comment (danishjafri88) [reply Shared/AuthenticationKeychainInfo.swift]: ~~UserDefaults(suiteName: AppInfo.sharedContainerIdentifier)?.bool(forKey: "profile.browserLock")~~
Yeah changing to == 2

File: Shared/AuthenticationKeychainInfo.swift [hunk 4]
```diff
@@ -25,7 +25,7 @@ public extension KeychainWrapper {
     }
 }
 
-open class AuthenticationKeychainInfo: NSObject, NSCoding {
+open class AuthenticationKeychainInfo: NSObject, NSSecureCoding {
```
Comment (danishjafri88) [inline Shared/AuthenticationKeychainInfo.swift]: Reverting this as all keys are fully compatible

File: Client/Application/Migration.swift [hunk 5]
```diff
@@ -60,7 +60,13 @@ extension Preferences {
         // Security
         NSKeyedUnarchiver.setClass(AuthenticationKeychainInfo.self, forClassName: "AuthenticationKeychainInfo")
         if let pinLockInfo = KeychainWrapper.standard.object(forKey: "pinLockInfo") as? AuthenticationKeychainInfo {
-            KeychainWrapper.sharedAppContainerKeychain.setAuthenticationInfo(pinLockInfo)
+            //Checks if browserLock was enabled in old app.
+            let isBrowserLockEnabled: Bool = UserDefaults(suiteName: AppInfo.sharedContainerIdentifier)?.bool(forKey: "profile.browserLock") ?? false
```
Comment (kylehickinson) [inline Client/Application/Migration.swift]: You can use `Preferences.defaultContainer` instead of `UserDefaults(suiteName: AppInfo.sharedContainerIdentifier)`

Comment (kylehickinson) [reply Client/Application/Migration.swift]: Not huge since I think its always going to be `profile.` for us, but you should use `profile.prefs.getBranchPrefix()` instead of hardcoding `profile.`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
