### PR TITLE
Fix #2027 - Notification Orientation only stabled on SOME iPads

### LINKED ISSUE #2027: Device orientation change doesn't size up the ad notification
### Description: 
Device orientation change doesn't size up the ad notification 

### Steps to Reproduce 
  1. Use device in landscape mode and wait for an ad to show up 
  2. Rotate the device to portrait mode when an ad notification shows up
  3. Ad size is small on portrait as compared to landscape

**Actual result:** 
Device orientation change doesn't size up the ad notification 

**Expected result:**
Size of ad notification shouldn't be changed with device orientation

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14

**Device details:** 
iPad (iOS 13.2/12.4)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
This is a follow up to https://github.com/brave/brave-ios/issues/1916#issuecomment-558347191

### PR DESCRIPTION
**Pull request by Brandon-T**
Switch to using a constraint constant and manual calculation because `.multiplier(0.40).priority(.high)` doesn't work on ALL iPads (only some).

This makes the notification width on ALL iPads ALWAYS 40% of the longest side of the view/screen if possible.
Prior to this PR, it somehow only worked for SOME iPads and I really don't know why. IE: Sri was seeing small notifications but other QAs saw large ones. I saw large ones.

With this fix, I have tested iPad Pro 12.9in, 9.7in, iPad Air 2 and 3rd Gen.. iOS 12 and 13.
I have tested split screen and multi-tasking and rotation with all of the former.

## Summary of Changes

This pull request fixes issue #2027

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by Brandon-T** [comment]
I only tested on Simulator. I do not have a physical iPad.

File: BraveRewardsUI/Ads/AdsViewController.swift [hunk 1]
```diff
@@ -44,13 +45,17 @@ public class AdsViewController: UIViewController {
       $0.top.equalTo(view.safeAreaLayoutGuide.snp.top)
       $0.top.greaterThanOrEqualTo(view).offset(4) // Makes sure in landscape its at least 4px from the top
       
-      if UIDevice.current.userInterfaceIdiom == .pad {
-        let isWidthLarger = UIScreen.main.bounds.width > UIScreen.main.bounds.height
-        $0.width.equalTo(isWidthLarger ? view.snp.width : view.snp.height).multipliedBy(0.40).priority(.high)
-      } else {
+      if UIDevice.current.userInterfaceIdiom != .pad {
         $0.width.equalTo(view).priority(.high)
```
Comment (kylehickinson) [inline BraveRewardsUI/Ads/AdsViewController.swift:49]: Is this needed for iPhone? Since we have leading > 8 and trailing < 8 above?

File: BraveRewardsUI/Ads/AdsViewController.swift [hunk 2]
```diff
@@ -76,6 +81,15 @@ public class AdsViewController: UIViewController {
     adView.addGestureRecognizer(swipePanGesture)
   }
   
+  public override func viewWillLayoutSubviews() {
+    super.viewWillLayoutSubviews()
+    
+    if UIDevice.current.userInterfaceIdiom == .pad {
+      let isWidthLarger = view.bounds.width > view.bounds.height
+      widthAnchor?.constant = isWidthLarger ? view.bounds.width * 0.40 : view.bounds.height * 0.40
```
Comment (kylehickinson) [inline BraveRewardsUI/Ads/AdsViewController.swift]: We should probably round these to nearest valid pixel (0, 0.5, 1 on 2x devices, 0, 0.33, 0.66, 1 on 3x devices, though not sure if there's an iPad that supports that currently)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveRewardsUI/Ads/AdsViewController.swift (hunk 1 above)
Comment (Brandon-T) [reply BraveRewardsUI/Ads/AdsViewController.swift:49]: Screen Shot 2019-12-13 at 11 58 54 AM

Without it^

**Review by kylehickinson — APPROVED** [review]
