### PR TITLE
Fix #6792: Reject N Transactions does not dismiss tx confirmation

### LINKED ISSUE #6792: Rejecting all transactions doesn't close the transaction confirmation screen
### Description: 
Rejecting all transactions doesn't close the transaction confirmation screen

### Steps to Reproduce 
  1. Create multiple transactions without approving them
  2. Open the panel and click on bell icon to bring pending transactions
  3. Click on Reject all transactions
  4. The first transaction approval screen is still shown instead of dismissing it

### Actual result: 

https://user-images.githubusercontent.com/17010094/213395398-6507b1ba-cd5a-4082-8bfa-587707932412.MP4

### Expected result:
Should close the transaction confirmation screen when transactions are rejected

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Fix for dismissal when using reject all transactions by calling dismiss handler to match cancel / confirm individual transaction buttons

This pull request fixes #6792

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Create a transaction in a dapp
2. Swipe to dismiss that transaction
3. Create a second transaction in the dapp (more can be added if needed, but need at least 2)
4. Tap 'Reject 2 transactions'
5. Verify transaction confirmation is dismissed as expected
6. Create 2 more transactions
7. Open main wallet
8. Tap 'Reject 2 transactions'
9. Verify transaction confirmation is dismissed as expected
    - Tests separate presentation flow for tx confirmation

## Screenshots:

https://user-images.githubusercontent.com/5314553/213486471-15c5e7b6-b397-45df-8477-8244e410efd0.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/TransactionConfirmationStore.swift [hunk 1]
```diff
@@ -147,9 +147,20 @@ public class TransactionConfirmationStore: ObservableObject {
...
   }
 
-  func rejectAllTransactions() {
+  func rejectAllTransactions(completion: @escaping (Bool) -> Void) {
+    let dispatchGroup = DispatchGroup()
+    var allRejectsSucceeded = true
     for transaction in transactions {
-      reject(transaction: transaction, completion: { _ in })
+      dispatchGroup.enter()
+      reject(transaction: transaction, completion: { success in
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/TransactionConfirmationStore.swift:155]: needs an api takes a list of transactions to reject. ¯\_(ツ)_/¯

**Review by nuo-xu — APPROVED** [review]
