### PR TITLE
Fix #5424: Dapp get public encryption key / decrypt requests

### LINKED ISSUE #5424: Dapp Implement Get Encryption Public Key & Decrypt Requests
### Description: 

Need to support `GetEncryptionPublicKeyRequest` and `DecryptRequest` for web3 / dapps

### Steps to Reproduce 
for `GetEncryptionPublicKeyRequest` request
  1. Open [Metamask Test Dapp Site](https://metamask.github.io/test-dapp/) 
  2. Tap 'GET ENCRYPTION KEY'
 
for `DecryptRequest` request
  1. Open [Metamask Test Dapp Site](https://metamask.github.io/test-dapp/) 
  2. Enter message in field under 'GET ENCRYPTION KEY' button
  3. Tap 'ENCRYPT'
  4. Tap 'DECRYPT'

**Actual result:** 

Nothing happens, requests not implemented

**Expected result:**

Similar to other dapp requests, modal shown for each request

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Desktop panels:

get encryption public key request | decrypt request | decrypt request - showing message
--|--|--

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Added support for handling Get Public Encryption Key & Decrypt requests from dapp sites
- `OriginText` was replaced with a `Text` initializer so we can use it when concatenating other text views (used in get public encryption key request view).

This pull request fixes #5424

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

For get public encryption key requests
  1. Open [Metamask Test Dapp Site](https://metamask.github.io/test-dapp/) 
  2. Tap 'GET ENCRYPTION KEY'
  3. Tap 'Provide' on modal get public encryption key request view
 
For decrypt request please verify on device (for screenshot alert)
  1. Open [Metamask Test Dapp Site](https://metamask.github.io/test-dapp/) 
  2. Enter message in field under 'GET ENCRYPTION KEY' button
  4. Tap 'ENCRYPT'
  5. Tap 'DECRYPT'
  6. Tap 'Reveal' to see message
  7. Trigger device screenshot: should see an alert warning
  8. Trigger a screen recording: should not see message in screen recording
  9. Tap 'Allow'

Please also verify Account private key screen is working as expected on device (view was extracted for re-use)
1. Open main brave wallet
2. Tap Accounts
3. Tap your account
4. Tap 'Details'
5. Tap 'Private Key'
6. Trigger device screenshot: should see an alert warning
7. Trigger a screen recording: should not see message in screen recording

## Screenshots:

https://user-images.githubusercontent.com/5314553/172480093-fa91a290-3fae-4119-9d5d-aeb293f88e38.mov

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Panels/Encryption/EncryptionView.swift [hunk 1]
```diff
@@ -0,0 +1,271 @@
...
+      return Strings.Wallet.decryptRequestSubtitle
+    }
+  }
+  
+  var body: some View {
+    ScrollView(.vertical) {
+      if let chain = networkStore.selectedChain {
+        HStack(alignment: .top) {
+          Text(chain.chainName)
+          Spacer()
```
Comment (nuo-xu) [inline BraveWallet/Panels/Encryption/EncryptionView.swift:74]: maybe just add a bottom padding?

File: BraveWallet/WalletStrings.swift [hunk 2]
```diff
@@ -2430,5 +2430,68 @@ extension Strings {
...
+      tableName: "BraveWallet",
+      bundle: .strings,
+      value: "A DApp is requesting your public encryption key",
+      comment: "A subtitle of the view shown over a dapps website that requests the users public encryption key."
+    )
+    public static let getEncryptionPublicKeyRequestMessage = NSLocalizedString(
+      "wallet.getEncryptionPublicKeyRequestMessage",
+      tableName: "BraveWallet",
+      bundle: .strings,
+      value: "is requesting your wallets public encryption key. If you consent to providing this key, the site will be able to compose encrypted messages to you.",
```
Comment (nuo-xu) [inline BraveWallet/WalletStrings.swift]: is requesting your `wallet's` public encryption key.

**Review by nuo-xu — APPROVED** [review]
