### PR TITLE
Fix#3414: Add Search engine still shows up even if the site is manually added

### LINKED ISSUE #3414: Add Search engine still shows up even if the site is manually added
### Description: 
Add Search engine still shows up even if the site is manually added 

### Steps to Reproduce 
  1. Add `https://github.com/search?q=%s` manually to search engine
  2. Ensure its listed under custom search engine list
  3. Visit `https://github.com` and tap on search box
  4. Add search engine using the `Add search engine` button
  5. Able to add duplicate entries for the same search engine 

**Actual result:** 
image | image
-- | --

https://user-images.githubusercontent.com/17010094/111308043-1e604d00-8652-11eb-94c3-bc1b9ad34c99.MP4

**Expected result:**
Should not show add search engine if the site is already added with or without `&ref=opensearch` 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24

**Device details:** 
iPhone 7+ (iOS 14.4)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by soner-yuksel**
The shortname is added as an extra criteria to determine if the search engine is added

## Summary of Changes

This pull request fixes #3414

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Add https://github.com/search?q=%s manually to search engine
- Ensure its listed under custom search engine list
- Visit https://github.com and tap on search box
- Add search engine using the Add search engine button
- Not Able to add duplicate entries for the same search engine

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift [hunk 1]
```diff
@@ -45,14 +45,17 @@ extension BrowserViewController {
         
         // Open Search guidlines requires Title to be same as Short Name but it is not enforced,
         // thus in case of yahoo.com the title is 'Yahoo Search' and Shortname is 'Yahoo'
-        // Instead we are checking referenceURL match to determine searchEngine is added or not
+        // We are checking referenceURL match to determine searchEngine is added or not
+        //In addition we are also checking if there is another engine with same name
         
         let searchEngineExists = profile.searchEngines.orderedEngines.contains(where: {
+            let nameExists = $0.shortName.lowercased() == referenceObject.title?.lowercased() ?? ""
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift:52]: Do we have to unwrap `referenceObject` here? String to String? comparison should work, no?

File: Client/Frontend/Settings/SearchCustomEngineViewController.swift [hunk 2]
```diff
@@ -334,7 +334,15 @@ extension SearchCustomEngineViewController {
             return
         }
         
-        let searchEngineExists = profile.searchEngines.orderedEngines.contains(where: {$0.referenceURL == openSearchEngine.reference})
+        let searchEngineExists = profile.searchEngines.orderedEngines.contains(where: {
+            let nameExists = $0.shortName.lowercased() == openSearchEngine.title?.lowercased() ?? ""
```
Comment (iccub) [inline Client/Frontend/Settings/SearchCustomEngineViewController.swift:338]: see previous comment

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift:52]: The Swift compiler does not implicitly unwrap any optionals as far as I know and It doesn't work I tried.
