### PR TITLE
Fix #7146: Crash when creating sync chain after attempting to join deleted chain [Same profile]

### LINKED ISSUE #7146: Crash when creating sync chain after attempting to join deleted chain [Same profile]
### Description: 
Creating standalone sync chain after trying to join deleted chain will result in the app crashing. This will impact all iOS devices that were connected to the sync chain. I tried to repeat with other devices and had the same result. It will NOT repro if you use a new profile and try to use the same deleted sync QR code, only same profile which had the deleted sync chain. 

https://user-images.githubusercontent.com/17885425/227647089-8284dc18-be67-4c30-b606-07b00c8bc63c.MP4

### Steps to Reproduce 
  1. Create sync chain and add some devices
  2. Enable Sync `History` (Not sure if this is related)
  3. Save the QR for later for the active sync chain
  4. Now, permanently delete the sync chain using the `Delete Sync Account` button in sync settings
  5. Attempt to rejoin the deleted chain by scanning QR in previous step, which should fail
  6. Reload sync page and select `Start a new Sync Chain`
  7. Then, select `Computer` option in the Device Type Page

### Actual result: 
Example | Example
-|-
IMG_2851 | IMG_0168 2

### Expected result:
Sync chain should be created successfully

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily using STR

### Brave Version:  `1.49 (23.3.23.15)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
`iPhone X`, `iOS 16.3.1`
`iPad (9th Gen)`, `iPadOS 15.6.1`

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

Adding DidJoinSynChain result successful when creating a new chain.

This pull request fixes #7146

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
Actually crash can happen without involving other devices.

-Create a Sync Chain and record the code
-Delete that Sync Chain
-Try to join the same sync chain with deleted words
-Create a new chain

## Screenshots:

https://user-images.githubusercontent.com/6643505/228028982-c8f17afc-83a5-487b-b7b5-7cf2dc39ff58.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift [hunk 1]
```diff
@@ -228,15 +228,30 @@ class SyncWelcomeViewController: SyncViewController {
         self.navigationController?.pushViewController(view, animated: true)
       }
 
+      self.syncAPI.leaveSyncGroup()
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift]: Why do we need this one?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Sync/SyncWelcomeViewController.swift]: Wanted to be sure observers are removed and chain is reseted before creation but we dont need it, Removed at 
https://github.com/brave/brave-ios/pull/7156/commits/7d94bfb9082599c0840a79bfb6ec2eb30c7cbc09

**Review by Brandon-T — APPROVED** [review]
