### PR TITLE
Fix #511: Youtube ads

### LINKED ISSUE #511: Youtube pre-roll ads are not blocked
### Description: 
Youtube pre-rol ads are not blocked

### Steps to Reproduce 
  1. Install 1.7 (18.11.30.3)
  2. Watch a video on YT in a new tab
  3. Open a new tab and visit YT and play a random video
  4. After 2-3 videos played on the second tab, preroll ad shows up

**Actual result:** 
image from ios

**Expected result:**
Should block all pre-roll ads

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent happened twice but not continuous 

**Brave Version:** 
1.7  (18.11.30.3)

**Device details:** 
iPhone 7+ (IOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

Added Javascript injection into the `MainFrame` only (same as Desktop).. to block youtube ads. The JS is injected into EVERY page and not just the youtube domain which can come in multiple forms: `youtube.com`, `youtu.be`, etc..

If we want it only on youtube domain, we can add it whenever. Just let me know.

This pull request fixes #511 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/UserContent/UserScripts/YoutubeAdblock.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
+(function() {
```
Comment (iccub) [inline Client/Frontend/UserContent/UserScripts/YoutubeAdblock.js:6]: Add license header

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 2]
```diff
@@ -197,6 +206,23 @@ class UserScriptManager {
...
+        guard let path = Bundle.main.path(forResource: "YoutubeAdblock", ofType: "js"), let source = try? String(contentsOfFile: path) else {
+            log.error("Failed to load YoutubeAdblock.js")
+            return nil
+        }
+        
+        //Verify that the application itself is making a call to the JS script instead of other scripts on the page.
+        //This variable will be unique amongst scripts loaded in the page.
+        //When the script is called, the token is provided in order to access the script variable.
+        var alteredSource = source
+        let token = UserScriptManager.securityToken.uuidString.replacingOccurrences(of: "-", with: "", options: .literal)
```
Comment (iccub) [inline Client/Frontend/Browser/UserScriptManager.swift:220]: We have `securityToken` constant in the UserScriptManager, maybe use it?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 3]
```diff
@@ -188,7 +188,14 @@ extension BrowserViewController: WKNavigationDelegate {
             decisionHandler(.cancel)
             return
         }
+        
         let isPrivateBrowsing = PrivateBrowsingManager.shared.isPrivateBrowsing
+
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:193]: Can you add a comment referencing the ticket we are fixing?

I think we should use this old ticket for it 
https://github.com/brave/brave-ios/issues/511

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 4]
```diff
@@ -188,7 +188,14 @@ extension BrowserViewController: WKNavigationDelegate {
             decisionHandler(.cancel)
             return
         }
+        
         let isPrivateBrowsing = PrivateBrowsingManager.shared.isPrivateBrowsing
+        
+        if url.baseDomain == "youtube.com" {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:194]: the WKNavDelegate getting bigger and bigger :(

Nothing to do now, but if we add another site specific hack for adblocking we should abstract it somewhere, maybe in Tab or in userScriptManager itself

**Review by iccub — CHANGES_REQUESTED** [review]
Looks good, left small comments.

File: Client/Frontend/Browser/UserScriptManager.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Browser/UserScriptManager.swift:220]: lol nevermind, we use it here :D

**Comment by iccub** [comment]
Unblocking this, turns out the script works well, no more adjustments are needed.
We may consider changing architecture to put 'if-youtube' code directly into the script

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 5]
```diff
@@ -197,6 +206,23 @@ class UserScriptManager {
         
         return WKUserScript(source: alteredSource, injectionTime: .atDocumentStart, forMainFrameOnly: false)
     }()
+    
+    private let AdblockJSScript: WKUserScript? = {
```
Comment (iccub) [inline Client/Frontend/Browser/UserScriptManager.swift]: rename to `youtubeAdblockJSScript`

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
