### PR TITLE
Fix #6276: Process immediate child nodes that aren't added and aren't observed.

### LINKED ISSUE #6276: Playlist URL bar prompt isn't showing for rumble.com
### Description: 
Playlist URL bar prompt isn't showing for odysee.com 

### Steps to Reproduce 
  1. Open rumble.com and tap on a video

**Actual result:** 
- Prompt UI to add the video to Playlist doesn't appear from the URL bar

**Expected result:**
- Prompt to add the video to Playlist should appear from the URL bar

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
-  Process immediate child nodes that aren't added and aren't observed
- This fixes sites like: `rumble.com` not showing the URL-Bar icon.

This pull request fixes #6276

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Visit `rumble.com`
2. Click on any video
3. Playlist icon should show in the URL Bar.

## Screenshots:
image

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Lol left a review on the wrong PR, but approved anyways 😂

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift [hunk 1]
```diff
@@ -78,16 +78,21 @@ extension PlaylistListViewController: UITableViewDataSource {
...
         return cell
       }
       
-      let domain = URL(string: item.pageSrc)?.baseDomain ?? "0s"
-      
       cell.do {
         $0.showsReorderControl = false
         $0.setTitle(title: item.name)
-        $0.setDetails(details: domain)
+        $0.setDetails(details: URL(string: item.pageSrc)?.baseDomain ?? "0s")
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift]: `0s` probably has to be localized, right?

Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift]: Done. Copied what Brave Shields is doing. Don't think it has to be a date formatter.
