### PR TITLE
Fix #859: Delete nested bookmarks on a single context.

### LINKED ISSUE #859: Deleting bookmark folders doesn't sync across correctly
### Description: 
Deleting bookmark folders doesn't sync across correctly 

### Steps to Reproduce 
  1. Create sync chain with desktop on device 1 and import bookmarks on desktop, ensure syncs to device 1
  2. Sync device 2 using QR code, ensure all bookmarks and folders are sync'd 
  3. Delete the bookmark folder sync'd from desktop 
  4. Bookmarks inside folders are deleted on device 1 but folder structure is retained
  5. Remove app from memory on device 1 and relaunch, same folder structure is maintained on device 1

**Actual result:** 
Device 1:
file 6
Device 2:
file 7

**Expected result:**
All deleted bookmark/folders should be removed from all devices

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent 

**Brave Version:** 
1.8(19.02.05.03)

**Device details:** 
Device 1: iPhone 7+ sync chain creator, has bookmarks from desktop
Device 2: iPad pro deletes the bookmark folder sync'd from desktop

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
Two things were changed
- Using one context for deleting all sync records
- Saving this context after all objects are deleted, previously we saved context after each delete operation

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adaquate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/models/CRUDProtocols.swift [hunk 1]
```diff
@@ -27,8 +27,8 @@ public protocol Readable where Self: NSManagedObject {
 
 // MARK: - Implementations
 public extension Deletable where Self: NSManagedObject {
-    func delete() {
-        let context = DataController.newBackgroundContext()
+    func delete(context: NSManagedObjectContext? = nil) {
```
Comment (jhreis) [inline Data/models/CRUDProtocols.swift]: Why not just make the default `DataController.newBackgroundContext()`? Then don't need the line below, and can remove optionality.

**Review by jhreis — CHANGES_REQUESTED** [review]

**Review by jhreis — APPROVED** [review]
