### PR TITLE
Fix #969: This fixes `Open Image In New Tab` button In Private window that opens the image in a Normal tab

### LINKED ISSUE #969: In Private window `Open Image In New Tab` opens the image in a Normal tab
### Description: 
In Private window `Open Image In New Tab` opens the image in a Normal tab

### Steps to Reproduce 
  1. Open a private window
  2. Open any webpage
  3. Hold the image and Tap `Open Image In New Tab`

**Actual result:** 
The image opens in a Normal tab

**Expected result:**
The image should open in a private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 

1.8
**Device details:** 
iPhone 8

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information 
The issue is reported by the community

https://community.brave.com/t/in-private-browsing-open-image-in-new-tab-opens-the-image-in-a-regular-tab/48541

### PR DESCRIPTION
**Pull request by Mahmoud333**
-The change happened in BrowserViewController.swift inside openInNewTabAction Alert Action completion.
-Fixed bug #969. 
-I also changed Cartfile SwiftyJSON from 4.1.0 to 4.2.0 because i had issue building the project with xcode log: "Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /brave-ios/Carthage/Build/iOS/SwiftyJSON.framework/Modules/SwiftyJSON.swiftmodule/x86_64.swiftmodule" 

## Test Plan:
1- Open private window
2- Long press on any image and tap "Open In New Tab" button
Result: The image should be opened in a new tab in private mode

### CODE REVIEW

File: Cartfile [hunk 1]
```diff
@@ -7,7 +7,7 @@ github "kif-framework/KIF"                  "v3.7.4"
 github "mozilla-mobile/SwiftKeychainWrapper" "3.0.1"
 github "DaveWoodCom/XCGLogger"              "6.0.4"
 github "cezheng/Fuzi"                       "2.1.0"
-github "SwiftyJSON/SwiftyJSON"              "4.1.0"
+github "SwiftyJSON/SwiftyJSON"              "4.2.0"
```
Comment (kylehickinson) [inline Cartfile]: This should be in a separate PR/commit

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -2494,7 +2494,11 @@ extension BrowserViewController: ContextMenuHelperDelegate {
             }
             
             let openInNewTabAction = UIAlertAction(title: Strings.OpenImageInNewTabActionTitle, style: .default) { _ in
-                self.tabManager.addTab(URLRequest(url: url), afterTab: self.tabManager.selectedTab)
+                if PrivateBrowsingManager.shared.isPrivateBrowsing {
+                    self.tabManager.addTabAndSelect(URLRequest(url: url), afterTab: self.tabManager.selectedTab, isPrivate: true)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Should probably use the same call for both states. Currently this uses `addTabAndSelect` for private and just `addTab` for normal.

Probably best to just use the original call and add `isPrivate` to it like: 

```swift
let isPrivate = PrivateBrowsingManager.shared.isPrivateBrowsing
self.tabManager.addTab(URLRequest(url: url), afterTab: self.tabManager.selectedTab, isPrivate: isPrivate)
```

**Review by kylehickinson — CHANGES_REQUESTED** [review]
Thanks for fixing this up @Mahmoud333 ! :) 

Just a few things to change up before we can merge it in.  Thanks!

**Comment by Mahmoud333** [comment]
thanks @kylehickinson, i changed the BrowserViewController as requested and separated it from Cartfile commit

**Review by kylehickinson — APPROVED** [review]
Sweet, thanks again @Mahmoud333 

Will merge after CI build finishes 👍
