### PR TITLE
Fix #3828: Potential CoreData initialization crash.

### LINKED ISSUE #3828: Core data initialization crash
### Description: 

Zrzut ekranu 2021-06-21 o 17 22 00

### Steps to Reproduce 
Hard to reproduce, but there's a lot of reports in xcode crashes organizer.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
Two changes to potentially fix the problem:
- We do not crash the app if a persistent store was already loaded.
- For persistent store we let the `NSPersistentContainer` do its job instead of preparing store description by ourselves.

This pull request fixes #3828 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

This is high impact code.

Please do regression tests, verify that Tabs, bookmarks, history, playlist data are persisted.
Verify that private browsing and private browsing only mode works, nothing regressed.
Verify that upgrading from 1.27 to 1.28 does not crash the app

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

File: Data/models/DataController.swift [hunk 1]
```diff
@@ -23,6 +23,8 @@ public class DataController {
     private static let databaseName = "Brave.sqlite"
     private static let modelName = "Model"
     
+    private static let storeExistsErrorCode = 134081
```
Comment (soner-yuksel) [inline Data/models/DataController.swift:28]: Can we comment here what is the error code for and why we need it specifically ?

File: Data/models/DataController.swift [hunk 2]
```diff
@@ -235,49 +237,24 @@ public class DataController {
         return DataController.sharedInMemory.container.viewContext
     }
     
-    static func save(context: NSManagedObjectContext?) {
```
Comment (soner-yuksel) [inline Data/models/DataController.swift:238]: Do we not need the "save" method anywhere ? Did we remove its usage before ?

File: Data/models/DataController.swift [hunk 3]
```diff
@@ -235,49 +237,24 @@ public class DataController {
...
-    
     var storeURL: URL {
         let supportDirectory = Preferences.Database.DocumentToSupportDirectoryMigration.completed.value
         return supportDirectory ? supportStoreURL : oldDocumentStoreURL
     }
     
     private func configureContainer(_ container: NSPersistentContainer, store: URL) {
-        addPersistentStore(for: container, store: store)
-        
-        // Dev note: This completion handler might be misleading: the persistent store is loaded synchronously by default.
```
Comment (soner-yuksel) [inline Data/models/DataController.swift:277]: Does this comment do not apply anymore ?

File: Data/models/DataController.swift [hunk 4]
```diff
@@ -235,49 +237,24 @@ public class DataController {
...
-        container.loadPersistentStores(completionHandler: { _, error in
+        container.loadPersistentStores(completionHandler: { store, error in
             if let error = error {
-                fatalError("Load persistent store error: \(error)")
+                // Do not crash the app if the store already exists.
+                if (error as NSError).code != Self.storeExistsErrorCode {
+                    fatalError("Load persistent store error: \(error)")
```
Comment (soner-yuksel) [inline Data/models/DataController.swift:252]: Can we log the error here isntead of giving a fatalError? Is there a benefit for us to crash application ?

File: Data/models/DataController.swift (hunk 3 above)
Comment (iccub) [reply Data/models/DataController.swift:277]: not anymore, there's bunch of other synchronous completion handlers

File: Data/models/DataController.swift (hunk 2 above)
Comment (iccub) [reply Data/models/DataController.swift:238]: we do not, you are supposed to save with `perform` method, this method was not used

File: Data/models/DataController.swift (hunk 4 above)
Comment (iccub) [reply Data/models/DataController.swift:252]: no, you should not allow the app to run if the database did not load correctly, 
only exception is the error code i added

File: Data/models/DataController.swift (hunk 1 above)
Comment (iccub) [reply Data/models/DataController.swift:28]: the constant name is `what`, i can add in comment `why`

**Review by soner-yuksel — APPROVED** [review]
