### PR TITLE
Fix #2344: Add default font color for `accessoryLabel` of TableViewCell.

### LINKED ISSUE #2344: On dark theme the site details view text is not visible
### Description: 
While testing #1670, found on dark theme the site details view text is not visible 

### Steps to Reproduce 
  1. Set device theme to dark 
  2. Send a tip to non-verified pub
  3. Open site details in pending contribution, text is not visible

**Actual result:** 
image

**Expected result:**
Text should be visible on any theme

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.02.18.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
@kylehickinson please move the issue to 1.15 if you think this should be fixed in it

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes issue #2344 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Common/Tables/TableViewCell.swift [hunk 1]
```diff
@@ -31,14 +31,13 @@ class TableViewCell: UITableViewCell, TableViewReusable {
...
-    case .default:
+    case .default, .subtitle, .value2:
       accessoryLabel = nil
     case .value1:
       accessoryLabel = UILabel().then {
         $0.setContentCompressionResistancePriority(.required, for: .horizontal)
+        $0.appearanceTextColor = Colors.grey100
       }
-    case .subtitle, .value2:
-      fallthrough
```
Comment (iccub) [inline BraveRewardsUI/Common/Tables/TableViewCell.swift:41]: swiftlint complained here, maybe I should throw fatal error idk

**Review by kylehickinson — APPROVED** [review]
