### PR TITLE
Fix #5086, #5088: Playlist FavIcons & Particle Renderer not showing

### LINKED ISSUE #5086: FavIcon fallback aren't shown properly on Playlist
### Description: 
- Sometimes on Playlist, the favicon fails to load

### Steps to Reproduce 
  1. Go to `https://apple.ca`
  2. Add video to playlist
  3. Go to create a new folder. Notice the fav-icon isn't shown.

1. Go to https://www.bbc.co.uk/sounds/play/p0bp8nhq
2. Add video to playlist via menu
3. No fav-icon showing.

**Actual result:** 
No icon shown for fav-icon

**Expected result:**
image

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.34?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix playlist fallback fav-icons not showing
- Fixed particle renderer not showing on audio only websites.

This pull request fixes #5086, #5088

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Included in Ticket

## Screenshots:
image
image

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]
It really seems like lots of work here to draw evert possible condition, can we make `FavIconImageRenderer` no private and add it to a Utility class of some sort so we can use this in future in other places.

File: Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift [hunk 1]
```diff
@@ -295,13 +309,43 @@ private class FavIconImageRenderer {
...
                         for: siteURL,
                         fallbackCharacter: nil
-                    )
+                    ) as NSString
                     
-                    let finalImage = self.renderOnImageContext { context, _ in
-                        label.layer.render(in: context)
+                    let padding = 4.0
+                    let finalImage = self.renderOnImageContext { context, rect in
+                        let font = label.font!
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift]: can we unwrap it?

File: Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift [hunk 2]
```diff
@@ -295,13 +309,43 @@ private class FavIconImageRenderer {
...
+                        var fontSize = font.pointSize
+                        
+                        // Estimate the size of the font required to fit the context's bounds + padding
+                        // Usually we can do this by iterating and calculating the size that fits
+                        // But this is a very good estimated size
+                        let newSize = text.size(withAttributes: [.font: font.withSize(fontSize)])
+                        let ratio = min((rect.size.width - padding) / newSize.width,
+                                        (rect.size.height - padding) / newSize.height)
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift:329]: Should we guard here against divide by 0 if `newSize` returns zero somehow?

Comment (iccub) [inline Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift:329]: Should we guard here against divide by 0 if `newSize` returns zero somehow?

**Review by iccub — COMMENTED** [review]
two nitpicks
