### PR TITLE
Fix #1803: Constraint runtime errors.

### LINKED ISSUE #1803: Constraint runtime issues
### Steps to Reproduce 
  1. Rune the app in development mode
  2. Look at logs

**Actual result:** 
There's bunch of runtime constraint errors.

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
This fixes some constraint problems in:
- bvc(there's still one more runtime error I haven't managed to fix)
- search controller
- shields view controller

There's one error I couldn't fix, shows up when keybard is shown for the first time

This pull request fixes issue #1803 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

This is for reviewer: run the app and look at logs if there's still some constraint errors.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Shields/ShieldsView.swift [hunk 1]
```diff
@@ -38,31 +39,35 @@ extension ShieldsViewController {
...
         
         @available(*, unavailable)
         required init?(coder aDecoder: NSCoder) {
             fatalError()
         }
         
+        override func layoutSubviews() {
+            super.layoutSubviews()
+            
+            scrollView.snp.remakeConstraints {
```
Comment (Brandon-T) [inline Client/Frontend/Shields/ShieldsView.swift:58]: Hmm, is there a reason we constrain the scrollView in `layoutSubviews`?
Just wondering if this will trigger another layout.

I tested it and it doesn't seem to trigger anything so looks good to me.

**Review by Brandon-T — CHANGES_REQUESTED** [review]

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Shields/ShieldsView.swift [hunk 2]
```diff
@@ -38,31 +39,35 @@ extension ShieldsViewController {
...
+                $0.edges.equalToSuperview()
+            }
+            
+            scrollView.contentLayoutGuide.snp.remakeConstraints {
+                $0.left.right.equalTo(self)
+            }
+            
+            stackView.snp.remakeConstraints {
+                $0.edges.equalToSuperview()
```
Comment (Brandon-T) [inline Client/Frontend/Shields/ShieldsView.swift:67]: This works. It will also work if constrained to the contentLayoutGuide.

IE: `scrollView.frameLayoutGuide.constrain(to: self)` and `stackView.constrain(to: scrollView.contentLayoutGuide)`.

But your code works so it's fine :)

**Comment by kylehickinson** [comment]
@iccub Please rebase :)
