### PR TITLE
Fix #2016: Don't hide the keyboard when we take a screenshot of the page

### LINKED ISSUE #2016: Keyboard auto hides while typing
### Description: 
Keyboard auto hides while typing

### Steps to Reproduce 
  1. Open a new tab 
  2. Start typing 
  3. Keyboard auto hides

**Actual result:** 
phone

**Expected result:**
Should not hide keyboard while typing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
Both iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
This is even more annoying on iPhone X series as the bottom swipe bar shows up on top of the quick-search bar 
image

### PR DESCRIPTION
**Pull request by kylehickinson**
Another solution is not doing a screenshot if the tab is backgrounded, as it almost never produces a proper screenshot anyways

## Summary of Changes

This pull request fixes issue #2016 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1500,6 +1500,10 @@ class BrowserViewController: UIViewController {
             // forward/backward. Strange, but LayoutChanged fixes that.
             UIAccessibility.post(notification: .layoutChanged, argument: nil)
         } else if let webView = tab.webView {
+            // For some reason the web view will steal first responder as soon
+            // as its added to the view heirarchy below. This line fixes that...
+            // somehow...
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:1506]: Can you add ticket number to this comment for reference?

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift:1506]: Sure

**Review by iccub — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
