### PR TITLE
Fix #2697: Use correct icon size during edge loop for scaled image data

### LINKED ISSUE #2697: Favicon transparency check crash
### Description: 

Zrzut ekranu 2020-07-6 o 12 29 21

### Steps to Reproduce 
Hard to repro, intermittent crash.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.18

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by kylehickinson**
Also:
- Adds a check for if the icon passed is non-zero in both axis
- Dispatches completion blocks within the global thread on main queue because the function is now static and not private

## Summary of Changes

This pull request fixes #2697 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test plan
Hard to reproduce. Please do a general browsing test
Try to add each website you visit to bookmarks.
You only have to bring up the 'add bookmark' screen, no need to tap to add it.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift [hunk 1]
```diff
@@ -410,12 +410,19 @@ class FaviconFetcher {
     
     /// Determines if the downloaded image should be padded because its edges
     /// are for the most part transparent
-    private func isIconBackgroundTransparentAroundEdges(_ icon: UIImage, completion: @escaping (_ isTransparent: Bool) -> Void) {
+    static func isIconBackgroundTransparentAroundEdges(_ icon: UIImage, completion: @escaping (_ isTransparent: Bool) -> Void) {
+        if icon.size.width.isZero || icon.size.height.isZero {
+            completion(false)
```
Comment (iccub) [inline Client/Frontend/Browser/Favicons/FaviconFetcher.swift]: Maybe put on main thread too? Since this is called from `downloadIcon` which I assume is async

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift [hunk 2]
```diff
@@ -438,24 +445,28 @@ class FaviconFetcher {
...
                     }
-                    for x in 0..<Int(icon.size.width) {
-                        updateScore(x: x, y: Int(icon.size.height))
+                    for x in 0..<Int(iconSize.width) {
+                        updateScore(x: x, y: Int(iconSize.height))
                     }
                     // We've already scanned the first and last pixel during
                     // top/bottom pass
-                    for y in 1..<Int(icon.size.height)-1 {
+                    for y in 1..<Int(iconSize.height)-1 {
```
Comment (iccub) [inline Client/Frontend/Browser/Favicons/FaviconFetcher.swift:458]: Will this crash if `iconSize .height == 1`? 
earlier in this method we check for non zero value, and with subtracting 1 we can get 1..<0 range which can crash

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Favicons/FaviconFetcher.swift:458]: Good point but I don't think this is possible, as `iconSize` will be the size of the scaled context regardless (48*scale)

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Favicons/FaviconFetcher.swift]: I think downloadIcon comes back on main thread, but I fixed this anyways

**Review by iccub — APPROVED** [review]
