### PR TITLE
Fix #1359: Improved modals for security keys

### LINKED ISSUE #1153: UI to avoid double-tap on security keys when unplugged
Hardware security keys generally take some time to change state where the tap can be accepted, we should think about a pop-over similar to one on desktop to avoid double taps. 

Screen Shot 2019-06-13 at 2 43 51 PM

### Test Plan:
Specified here: https://github.com/brave/brave-ios/pull/1362

### LINKED ISSUE #1347: Security key prompt is dismissed and showed again when key is disconnected and reconnected
### Description: 
Security key prompt is dismissed and showed again when key is disconnected and reconnected

### Steps to Reproduce 
  1. Login to a site that supports security keys
  2. Wait for the browser to prompt to connect security key
  3. Connect the device(do not authenticate), popup prompt is retained
  4. Disconnect the key and reconnect it (again do not authenticate)
  5. Connect security key prompt is dismissed and showed again

### Test Plan 
Specified here: https://github.com/brave/brave-ios/pull/1362

**Actual result:** 
Security key prompt is dismissed and showed again when key is disconnected and reconnected

**Expected result:**
Should only dismiss the prompt if the API request times out or when the user cancels it 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.08.08.06)

**Device details:** 
iPhone 7+ (iOS 12.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #1359: Add site url to the touch key modal
### Description: 
Cancel on touch key dialog still allows authenticating into the website

### Steps to Reproduce 
  1. Visit u2fdemo.hypersecu.com and create an account 
  2. Add a security key to the account and logout
  3. Relogin to prompt for security key
  4. Cancel the touch the key dialog that pops up
  5. Touch the key connectors, website authenticates and then brings back the popup 

### Test Plan
Specified here: https://github.com/brave/brave-ios/pull/1362

**Actual result:** 
image

**Expected result:**
Should include website name in the popup so that easy to understand which popup to use to verify and which ones can be cancelled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by jumde**
Fix #1153 
Fix #1359 
Fix #1347 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

1. Navigate to https://demo.yubico.com/u2f (Unplug the security key)
2. Click Next and verify that the `Insert key dialog` is displayed. The dialog should include the site host invoking the request.
3. Insert the key and verify the `PIN dialog` shows up. (Use YubiKey Manager to set a key for your key)
4. Enter the PIN and confirm the dialog to `Interact with key` pops-up.  The dialog should include the site host invoking the request.
5. Interact with the key and verify that the registration completes successfully.

### Screenshots:

**PIN Dialog:**

Screen Shot 2019-08-10 at 11 25 37 AM

**Interact with key dialog:**

Screen Shot 2019-08-10 at 11 25 50 AM

**Insert with key dialog:**

Screen Shot 2019-08-10 at 11 25 59 AM

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Popup/AlertPopupView.swift [hunk 1]
```diff
@@ -76,6 +76,14 @@ class AlertPopupView: PopupView {
         setDialogColor(color: BraveUX.PopupDialogColorLight)
     }
     
+    func updateTitle(title: String) {
```
Comment (jhreis) [inline Client/Frontend/Popup/AlertPopupView.swift]: More accurate naming would be `update(title: String)`.

File: Client/U2FExtensions.swift [hunk 2]
```diff
@@ -132,27 +136,30 @@ class U2FExtensions: NSObject {
...
+            }
+            return self.handleCancelButton()
+        }
+        
+        pinVerificationPopup.addButton(title: Strings.keyCancel) { [weak self] in
+            guard let self = self else {
+                return .flyDown
             }
-            return .flyDown
+            return self.handleCancelButton()
```
Comment (jhreis) [inline Client/U2FExtensions.swift]: Return can be simplified:
`return self?.handleCancelButton() ?? .flyDown`

File: Client/U2FExtensions.swift [hunk 3]
```diff
@@ -132,27 +136,30 @@ class U2FExtensions: NSObject {
...
-                    self.sendFIDORegistrationError(handle: handle, requestId: self.requestId[handle] ?? -1, errorCode: U2FErrorCodes.other_error)
-                case .FIDOSign:
-                    self.sendFIDOAuthenticationError(handle: handle, requestId: self.requestId[handle] ?? -1, errorCode: U2FErrorCodes.other_error)
-                case .FIDOLowLevel, .None:
-                    break
+            return self.handleCancelButton()
+        }
+        
+        insertKeyPopup.addButton(title: Strings.keyCancel) { [weak self] in
+            guard let self = self else {
```
Comment (jhreis) [inline Client/U2FExtensions.swift]: These blocks are identical so should be split up:

```
let popupButtonClosure: () -> PopupViewDismissType = {
    // ... all this code
}

[touchKeyPopup, insertKeyPopup, pinVerificationPopup].forEach {
    $0.addButton(title: Strings.keyCancel, tapped: popupButtonClosure)
}
```

**Review by iccub — APPROVED** [review]

File: Client/U2FExtensions.swift [hunk 4]
```diff
@@ -164,6 +171,24 @@ class U2FExtensions: NSObject {
         observeKeyStateUpdates = false
     }
     
+    private func handleCancelButton() -> PopupViewDismissType {
```
Comment (jhreis) [inline Client/U2FExtensions.swift]: Since we're DRY'ing up the previous usage of this, we could potentially in-line this, but not a big deal either way)

File: Client/U2FExtensions.swift [hunk 5]
```diff
@@ -613,46 +648,74 @@ class U2FExtensions: NSObject {
...
+                    return .flyDown
+                }
+                return self.verifyPin(completion: completion)
+            }
+            self.pinVerificationPopup.showWithType(showType: .flyUp)
+        }
+    }
+    
+    private func verifyPin(completion: @escaping (Bool) -> Void) -> PopupViewDismissType {
+        if let pin = pinVerificationPopup.text, !pin.isEmpty {
```
Comment (jhreis) [inline Client/U2FExtensions.swift]: We should probably `guard` these too to keep this method flatter. 

Also, since so many of these use `completion(true); return;` we may as well just combine the guard statements:
```
guard
    let pin = 
    let fido2Service = 
    let verifyPinRequest =
    else {
        completion(true)
        return
    }
}
```

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/U2FExtensions.swift (hunk 3 above)
Comment (jumde) [reply Client/U2FExtensions.swift]: looks much better, will update. Thanks!

File: Client/U2FExtensions.swift [hunk 6]
```diff
@@ -132,29 +136,34 @@ class U2FExtensions: NSObject {
             observeKeyStateUpdates = true
         }
         
-        popup = AlertPopupView(image: #imageLiteral(resourceName: "browser_lock_popup"), title: Strings.touchKeyTitle, message: Strings.touchKeyMessage)
+        touchKeyPopup = AlertPopupView(image: #imageLiteral(resourceName: "browser_lock_popup"), title: Strings.keyTitle, message: Strings.touchKeyMessage)
```
Comment (jhreis) [inline Client/U2FExtensions.swift]: These should be created when they are defined. 

```
fileprivate let touchKeyPopup = AlertPopupView(image: #imageLiteral(resourceName: "browser_lock_popup"), title: Strings.keyTitle, message: Strings.touchKeyMessage)
```

File: Client/U2FExtensions.swift [hunk 7]
```diff
@@ -613,46 +632,69 @@ class U2FExtensions: NSObject {
...
-                        return
-                    }
-                } else {
-                    completion(true)
-                    return
+            self.pinVerificationPopup.addButton(title: Strings.confirmPin) { [weak self] in
+                guard let self = self else {
+                    return .flyDown
                 }
+                return self.verifyPin(completion: completion)
```
Comment (jhreis) [inline Client/U2FExtensions.swift]: `return self?.verifyPin(completion: completion) ?? .flyDown`

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/U2FExtensions.swift (hunk 7 above)
Comment (jumde) [reply Client/U2FExtensions.swift]: `verifyPin` always returns `.flyDown`. Is this still needed?

Comment (jumde) [reply Client/U2FExtensions.swift]: 👍

**Review by jhreis — APPROVED** [review]
