### PR TITLE
Fix #6813: Remove usage of LocalRequestHandler in internal scripts

### LINKED ISSUE #6813: Remove usage of LocalRequestHelper
### Description: 
- LocalRequestHelper.swift handler is not currently injected into any pages.
- Everything seems to work without it, but there are `potential` edge cases where it MIGHT be used, so we should inject it OR rewrite those internal scripts to remove it.

### Steps to Reproduce 
  1. N/A

### PR DESCRIPTION
**Pull request by Brandon-T**
## Security Review
- https://github.com/brave/security/issues/1169

## Summary of Changes
- Remove usage of LocalRequestHandler in scripts, in favour of having the page reload itself via `location.replace`

This pull request fixes #6813

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

## Test Cases:
1. Enter Reader-Mode and make sure it works.
2. Exit Reader-Mode and make sure it works.
3. Enter and Exit Reader-Mode on a very bad network, if it shows `loading screen` it is working.

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

**Review by nuo-xu — APPROVED** [review]

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Internal/LocalRequestHelper.swift [hunk 1]
```diff
@@ -11,7 +11,7 @@ class LocalRequestHelper: TabContentScript {
   static let scriptName = "LocalRequestScript"
   static let scriptId = UUID().uuidString
   static let messageHandlerName = "\(scriptName)_\(messageUUID)"
-  static let scriptSandbox: WKContentWorld = .page
+  static let scriptSandbox: WKContentWorld = .defaultClient
```
Comment (stoletheminerals) [inline Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Internal/LocalRequestHelper.swift]: We don't need this handler anymore, right? Can we just remove it?

Comment (Brandon-T) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Internal/LocalRequestHelper.swift]: Removed

**Review by stoletheminerals — APPROVED** [review]
