### PR TITLE
Fix #5438: Save password prompt does not surface to the page after login

### LINKED ISSUE #5438: Save password prompt does not surface to the page after signing in.
### Description: 
After successfully signing in, the save password modal looks it appears for a second but doesn't surface to the page/gets backgrounded immediately. 

Impacts iPhone/IPad, Works in 1.38.x 

### Steps to Reproduce 
  1. Clean install
  2. Navigate to Google.com
  3. Sign in
  4. Observe 

**Actual result:** 

https://user-images.githubusercontent.com/17885425/171736344-5910708e-a131-4d81-98e6-10330b316704.mov

**Expected result:**
Save password prompt should appear

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.39 (22.5.30.17)
1.39 (22.6.2.20)

**Device details:** 
iPad (7th Gen) iOS 15.5
iPhone 12 Pro iOS 15.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
AlertStackView contains prompts also not related with page zoom, while altering visibility only pageZoomView should be removed.

## Summary of Changes

This pull request fixes #5438

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Clean install
- Navigate to Google.com
- Sign in
- Observe Login save prompt is shown

## Screenshots:

IMG_0363

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1908,13 +1908,15 @@ public class BrowserViewController: UIViewController, BrowserViewControllerDeleg
...
-      alertStackView.arrangedSubviews.forEach({
-        $0.removeFromSuperview()
-      })
-      
+    if !visible || pageZoomBar != nil {     
+      pageZoomBar?.view.removeFromSuperview()
       updateViewConstraints()
       pageZoomBar = nil
+      
+      if let zoomBarView = pageZoomBar?.view {
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift:1914]: This line never gets hit because `pageZoomBar = nil` is on the line before it.

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift:1914]: Yeah thats right,  I put it wrong place while editing it. Fix at [e3e29fd](https://github.com/brave/brave-ios/pull/5439/commits/e3e29fdaa59b89cbbb3264998e9f5f4c436854c0)

**Review by Brandon-T — APPROVED** [review]
