### PR TITLE
Fix #4908: Update sync v2 error copy.

### LINKED ISSUE #4908: Sync QR code scanning error text
Similar to https://github.com/brave/brave-browser/issues/20742

From 
https://www.reddit.com/r/brave/comments/se32k7/how_do_i_go_around_this/ and Slack discussion

when device tries to connect via version 1 QR code, it gets
```
This code has expired. Please generate a new one on your other device and try again.
```

it should be instead 
```
Title: Can’t sync this device
Body:
This sync code was generated by an outdated version of Brave on another device. Please update Brave on all synced devices and try again.”
```
UPD:
if device is trying to connect to the sync QR code where `version` field is greater than current `2`, it should give such error:

```
This sync code was generated by a newer version of Brave on another device. Please update Brave on all synced devices and try again.
```

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #4908 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Sync/SyncPairCameraViewController.swift [hunk 1]
```diff
@@ -227,9 +227,7 @@ class SyncPairCameraViewController: SyncViewController {
     private func showErrorAlert(error: BraveSyncQRCodeError) {
         let errorMessage = { (error: BraveSyncQRCodeError) -> String in
             switch error {
-            case .insecure: return Strings.syncInsecureVersionError
```
Comment (Brandon-T) [inline Client/Frontend/Sync/SyncPairCameraViewController.swift:230]: `insecure` and `newerVersion` aren't the same.
`Insecure` = When you scan QRCode v1
`NewVersion` = When you scan a version that is higher than your current browser supports. `"This sync code was generated by an outdated version of Brave on another device."` wouldn't work.

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/Sync/SyncPairCameraViewController.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Sync/SyncPairCameraViewController.swift:230]: good point, we will update the ticket with new copy and I will change it, @AlexeyBarabash to update it

Comment (AlexeyBarabash) [reply Client/Frontend/Sync/SyncPairCameraViewController.swift:230]: Updated at https://github.com/brave/brave-ios/issues/4908#issue-1116614816

**Review by Brandon-T — APPROVED** [review]
