### PR TITLE
Fix #789: Don't add a Device if it already exists.

### LINKED ISSUE #789: Sometimes new sync device is added twice
### Steps to Reproduce 
  1. Pair two devices together

**Actual result:** 
It does not happen often, but sometimes the device that joins your sync chain is added twice on one device.

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
This is a workaround solution. Proper fix will be done once https://github.com/brave/brave-ios/pull/681 is merged in, so we have an OperationQueue to avoid any race conditions.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adaquate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/models/Device.swift [hunk 1]
```diff
@@ -49,10 +51,26 @@ public final class Device: NSManagedObject, Syncable, CRUD {
...
+        // There can't be more than two device with the same syncUUID.
+        // A race condition could sometimes happen while getting two `Sync.resolvedSyncRecords` callbacks at the same time.
+        // Fixing issue #692 should help with it, until then we do a simple guard and disallow adding another device
+        // with the same syncUUID.
+        if let syncDisplayUUID = SyncHelpers.syncDisplay(fromUUID: syncUUID) {
+            let predicate = NSPredicate(format: "syncDisplayUUID == %@", syncDisplayUUID)
+            let first = Device.first(where: predicate, context: context)
+            if first != nil {
+                log.warning("A device with sync UUID \(syncDisplayUUID) already exists. Aborting inserting a new device.")
+                return nil
```
Comment (jhreis) [inline Data/models/Device.swift]: What do you think about just failing silently and letting this bleed through?

```
var device = Device.first(where: predicate, context: context)
if device == nil {
  // This is expected, however, see race condition comments above.
  device = Device(entity: Device.entity(context: context), insertInto: context)
  device.created = root?.syncNativeTimestamp ?? Date()
  device.syncUUID = syncUUID
}

device.update(syncRecord: root)
```

Comment (iccub) [reply Data/models/Device.swift]: The question is, do we want to eventually update record on insert in this case?
We do something similar in `Sync.resolvedRecords` so that shouldn't be a problem

File: Data/models/Device.swift [hunk 2]
```diff
@@ -49,12 +51,25 @@ public final class Device: NSManagedObject, Syncable, CRUD {
...
+            let predicate = NSPredicate(format: "syncDisplayUUID == %@", syncDisplayUUID)
+            device = Device.first(where: predicate, context: context)
+        }
+        
+        if device == nil {
+            device = Device(entity: Device.entity(context: context), insertInto: context)
+            device?.created = root?.syncNativeTimestamp ?? Date()
+            device?.syncUUID = syncUUID
+            
+            device?.update(syncRecord: root)
```
Comment (jhreis) [inline Data/models/Device.swift]: I think we can place this outside the `if`? That way it would update regardless of what device it will use.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Data/models/Device.swift (hunk 2 above)
Comment (iccub) [reply Data/models/Device.swift]: Why only `update` then and no syncUUID and `created` which also uses `root` object?

**Review by jhreis — APPROVED** [review]
