### PR TITLE
Fix #627 Add brave://search URL scheme

### LINKED ISSUE #627: Add more brave:// URL scheme actions
It'd be nice to offer more url schemes than the only one we support right now (`open-url`) which requires that the input be a URL.

Possible additions:
- [x] `brave://search?q=<search-query>`: Allow a user to pass in any string that would search with whatever search engine the user is currently using
- [ ] `brave://bookmark?url=<url>`: Allow the user to bookmark a URL from outside the app

In addition to the url scheme we have: `brave://open-url?url=<url>` which will fail if a non-url string is passed through.

### PR DESCRIPTION
**Pull request by KacperWybranski**
## Summary of Changes

This pull request fixes part of #627.
It fix handling nonUrl text when sharing to Brave. Before, app opened blank tab. With this fix, app search for the text using default search engine in the browser.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Open safari, go to a wikipedia article
- Select a word or a sentence, tap 'share', and share it with Brave
- Verify that text you selected was used as a search query in Brave app

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by KacperWybranski** [comment]
As you can see I deleted file that should just stay there, I'm sorry about that. Really hope it doesn't ruin whole pull request.

File: BraveShareTo/ShareToBraveViewController.swift [hunk 1]
```diff
@@ -35,22 +39,31 @@ class ShareToBraveViewController: SLComposeServiceViewController {
...
-            if let braveUrl = urlString.addingPercentEncoding(withAllowedCharacters: .alphanumerics).flatMap(self.urlScheme) {
-                self.handleUrl(braveUrl)
+            // Open url if it was found, in other case search for text with default search engine in browser
+            if let urlString = urlItem?.absoluteString {
+                if let braveUrl = urlString.addingPercentEncoding(withAllowedCharacters: .alphanumerics).flatMap(self.urlScheme) {
+                    self.handleUrl(braveUrl)
+                }
+            } else if let text = nonUrlText {
+                if let braveUrl = text.addingPercentEncoding(withAllowedCharacters: .alphanumerics).flatMap(self.searchScheme) {
+                    self.handleUrl(braveUrl)
```
Comment (iccub) [inline BraveShareTo/ShareToBraveViewController.swift]: This part is too duplicated, what do you think about adding new `var urlOrText: String?` then assign to it either url absolute string or the `nonUrlText`, and call rest of the code.

This way you won't need to call `addingPercentEncoding` two times

File: Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift [hunk 2]
```diff
@@ -386,7 +386,7 @@ class TopToolbarView: UIView, ToolbarProtocol {
         if search {
             locationTextField?.text = text
             // Not notifying when empty agrees with AutocompleteTextField.textDidChange.
-            delegate?.topToolbar(self, didEnterText: text)
+            delegate?.topToolbar(self, didSubmitText: text)
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift]: What is this change needed for? 
Currently it seems to break other part of the app when you are on google.com for example, and tap on url bar, it reloads the app instead of focusing on url bar

**Review by iccub — CHANGES_REQUESTED** [review]
Thanks for your PR and sorry for late reply, we had an important release to handle before jumping to contributor's code

I left some review, please check it out when you have time

File: BraveShareTo/ShareToBraveViewController.swift (hunk 1 above)
Comment (KacperWybranski) [reply BraveShareTo/ShareToBraveViewController.swift]: Good idea, I'll solve it this way

File: Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift (hunk 2 above)
Comment (KacperWybranski) [reply Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift]: I noticed that without this change, view is stuck with empty url bar and doesn't submit searching. Thanks for your comment, I haven't realized it breaks other part of the app, will try to solve that in different way.

File: BraveShareTo/ShareToBraveViewController.swift [hunk 3]
```diff
@@ -56,14 +56,8 @@ class ShareToBraveViewController: SLComposeServiceViewController {
...
-                if let braveUrl = urlString.addingPercentEncoding(withAllowedCharacters: .alphanumerics).flatMap(self.urlScheme) {
-                    self.handleUrl(braveUrl)
-                }
-            } else if let text = nonUrlText {
-                if let braveUrl = text.addingPercentEncoding(withAllowedCharacters: .alphanumerics).flatMap(self.searchScheme) {
-                    self.handleUrl(braveUrl)
-                }
+            if let braveUrl = urlItem?.absoluteString.addingPercentEncoding(withAllowedCharacters: .alphanumerics).flatMap(self.urlScheme) ?? nonUrlText?.addingPercentEncoding(withAllowedCharacters: .alphanumerics).flatMap(self.searchScheme) {
+                self.handleUrl(braveUrl)
             }
```
Comment (KacperWybranski) [inline BraveShareTo/ShareToBraveViewController.swift]: I didn't remove one of the .addingPercentEncoding parts since later there is a .flatMap part which is different in both cases, but I managed to make it little simpler

File: BraveShareTo/ShareToBraveViewController.swift [hunk 4]
```diff
@@ -35,21 +39,24 @@ class ShareToBraveViewController: SLComposeServiceViewController {
         
         provider.loadItem(of: provider.isUrl ? kUTTypeURL : kUTTypeText) { item, error in
             var urlItem: URL?
+            var nonUrlText: String?
```
Comment (iccub) [inline BraveShareTo/ShareToBraveViewController.swift]: This work, but I think we can make the code cleaner now, if you look at logic below that, there is a lot of nested ifs and the code is not super readable,

For us differences between text and url are small, we can remove code duplication a little and improve architecture

What do you think if we create a new structure to `ShareToBraveViewController` class holding either URL or text and handling the scheme properly,
Sample code

```
private struct Scheme {
        private enum SchemeType {
            case url, query
        }
        
        private let type: SchemeType
        private let urlOrQuery: String
        
        init?(item: NSSecureCoding) {
            if let text = item as? String {
                urlOrQuery = text
                type = .query
            } else if let url = (item as? URL)?.absoluteString.firstURL?.absoluteString {
                urlOrQuery = url
                type = .url
            } else {
                return nil
            }
        }
        
        var schemeUrl: URL? {
            guard let percentEncodedUrlOrQuery = urlOrQuery
                    .addingPercentEncoding(withAllowedCharacters: .alphanumerics) else {
                return nil
            }
            
            // Can improve even further with adding param using `URLComponents`
            switch type {
            case .url:
                return URL(string: "brave://open-url?url=\(percentEncodedUrlOrQuery)")
            case .query:
                return URL(string: "brave://search?q=\(percentEncodedUrlOrQuery)")
            }
        }
    }
```

Then calling it from `provider.loadItem` is much cleaner, you can simply do:

```
guard let item = item, let schemeUrl = Scheme(item: item)?.schemeUrl else {
    self.cancel()
    return
 }
            
self.handleUrl(schemeUrl)
```

what do you think about it?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 5]
```diff
@@ -1725,7 +1725,7 @@ class BrowserViewController: UIViewController {
                 // This let's the user spam the Cmd+T button without lots of responder changes.
                 guard freshTab == self.tabManager.selectedTab else { return }
                 if let text = searchText {
-                    self.topToolbar.setLocation(text, search: true)
+                    self.topToolbar.submitLocation(text)
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:1728]: I tested it, works nice now, good job

File: Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift [hunk 6]
```diff
@@ -392,6 +392,17 @@ class TopToolbarView: UIView, ToolbarProtocol {
         }
     }
     
+    func submitLocation(_ location: String?) {
+        guard let text = location, !text.isEmpty else {
+            locationTextField?.text = location
+            return
+        }
+        
+        locationTextField?.text = text
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift]: You can move it to first line in this function, 
`locationTextField?.text = text` is set here and in early return, we can simplify it and call once at the beginning of this function

File: ClientTests/NavigationRouterTests.swift [hunk 7]
```diff
@@ -42,6 +42,14 @@ class NavigationRouterTests: XCTestCase {
         XCTAssertEqual(badNav, NavigationPath.url(webURL: URL(string: "blah"), isPrivate: false))
     }
     
+    func testSearchScheme() {
```
Comment (iccub) [inline ClientTests/NavigationRouterTests.swift:45]: Thank you for adding unit test for it

**Review by iccub — CHANGES_REQUESTED** [review]
Functionality wise code works for me now, good job
we can make more improvements to our code architecture in `ShareToBraveViewController` class

File: BraveShareTo/ShareToBraveViewController.swift [hunk 8]
```diff
@@ -8,15 +8,47 @@ import MobileCoreServices
...
+                    components.host = "open-url"
+                    queryItem = URLQueryItem(name: "url", value: urlOrQuery)
+                case .query:
+                    components.host = "search"
+                    queryItem = URLQueryItem(name: "q", value: urlOrQuery)
+                }
+                
+                components.queryItems = [queryItem]
+                return components.url
+            }
```
Comment (KacperWybranski) [inline BraveShareTo/ShareToBraveViewController.swift:48]: Tried to added URLComponents logic you've mentioned, what do you think?
I also deleted ".addingPercentEncoding" part since encoding is solved by URLComponents type.

Comment (iccub) [reply BraveShareTo/ShareToBraveViewController.swift:48]: that's even better, nice find

**Review by iccub — APPROVED** [review]
Looks great, I will run this code for a bit and if all is good we will merge it

**Comment by iccub** [comment]
Thanks for this PR, merging it, should be live in version 1.28 early July
