### PR TITLE
Fix #5423: Add eTLD+1 in new/edit site connection + various iPad fixes.

### LINKED ISSUE #5423: New/Edit Site Connection doesn't bold eTLD+1
### Description: 
eTLD+1 should be bold on New Site Connection view and Edit Site Connection view

### Steps to Reproduce 
  1. Clear Uniswap connections from 'Manage Site Connections' in Brave Wallet settings
  2. Open [Uniswap](https://app.uniswap.org)
  3. Tap notification / wallet icon to be prompted for new site connection
  4. Observe New Site Connection.
  5. Edit site accessible by tapping 'Connect' on wallet panel after closing new site connection

**Actual result:** 

new site connection | edit site connection
--|--

**Expected result:**

eTLD+1 is bolded in the display. Example from transaction confirmation:

img

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Added eTLD+1 in new/edit site connection
Fixed lots iPad issues.

This pull request fixes #5423 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Please refer to the issue for eTLD+1
For iPad, please do a sanity test on UI and UX

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Accounts/AccountListView.swift [hunk 1]
```diff
@@ -22,7 +25,11 @@ struct AccountListView: View {
           ForEach(keyringStore.keyring.accountInfos) { account in
             Button(action: {
               keyringStore.selectedAccount = account
-              presentationMode.dismiss()
+              if onDismiss == nil {
+                presentationMode.dismiss()
+              } else {
+                onDismiss?()
+              }
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/Accounts/AccountListView.swift]: Should we just call both instead of needing this check? Similar to `cancellationAction` below. Alternatively we drop the `presentationMode` from this file, and use the `onDismiss` closure in `AccountPicker` to set `isPresentingPicker` to false.

File: BraveWallet/Crypto/BuySendSwap/BuyTokenView.swift [hunk 2]
```diff
@@ -118,8 +118,11 @@ struct BuyTokenView: View {
       .toolbar {
         ToolbarItemGroup(placement: .cancellationAction) {
           Button(action: {
-            onDismiss?()
-            presentationMode.dismiss()
+            if onDismiss == nil {
+              presentationMode.dismiss()
+            } else {
+              onDismiss?()
+            }
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/BuySendSwap/BuyTokenView.swift]: Same comment as on `AccountListView`

File: BraveWallet/Crypto/BuySendSwap/SendTokenView.swift [hunk 3]
```diff
@@ -192,8 +192,11 @@ struct SendTokenView: View {
       .toolbar {
         ToolbarItemGroup(placement: .cancellationAction) {
           Button(action: {
-            onDismiss?()
-            presentationMode.dismiss()
+            if onDismiss == nil {
+              presentationMode.dismiss()
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/BuySendSwap/SendTokenView.swift]: Same comment as on `AccountListView`

File: BraveWallet/Crypto/BuySendSwap/SwapCryptoView.swift [hunk 4]
```diff
@@ -483,8 +483,11 @@ struct SwapCryptoView: View {
       .toolbar {
         ToolbarItemGroup(placement: .cancellationAction) {
           Button(action: {
-            onDismiss?()
-            presentationMode.dismiss()
+            if onDismiss == nil {
+              presentationMode.dismiss()
+            } else {
+              onDismiss?()
+            }
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/BuySendSwap/SwapCryptoView.swift]: Same comment as on `AccountListView`

**Review by StephenHeaps — COMMENTED** [review]
Mostly nitpick comments, eTLD+1 & iPad issues resolved 👍

File: BraveWallet/Crypto/Accounts/AccountTransactionListView.swift [hunk 5]
```diff
@@ -29,65 +28,56 @@ struct AccountTransactionListView: View {
...
+    .listStyle(InsetGroupedListStyle())
+    .navigationTitle(Strings.Wallet.transactionsTitle)
+    .navigationBarTitleDisplayMode(.inline)
+    .sheet(item: $transactionDetails) { tx in
+      TransactionDetailsView(
+        info: tx,
+        networkStore: networkStore,
+        keyringStore: keyringStore,
+        visibleTokens: activityStore.assets.map(\.token),
+        allTokens: [],
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/Accounts/AccountTransactionListView.swift]: I believe we need to provide `activityStore.allTokens` here, or we won't display correct info for ERC20 approve transactions if the token approved is not a user visible token

File: BraveWallet/Panels/WalletPanelView.swift [hunk 6]
```diff
@@ -23,6 +23,7 @@ public struct WalletPanelContainerView: View {
   var origin: URLOrigin
   var presentWalletWithContext: ((PresentingContext) -> Void)?
   var presentBuySendSwap: (() -> Void)?
+  var buySendSwapBackground: InvisibleUIView = .init()
```
Comment (StephenHeaps) [inline BraveWallet/Panels/WalletPanelView.swift:27]: Can we put a comment for what this view is used for?

**Review by StephenHeaps — CHANGES_REQUESTED** [review]

**Review by StephenHeaps — APPROVED** [review]
