### PR TITLE
Fix #2081

### LINKED ISSUE #2081: Time out details on passcode lockdown copy should have a line break (Follow up of #443)
### Description: 

Follow up #443 

Should have a line break between try again and attempts as per:

> Too many failed attempts
> Try again in $TIME minutes

### PR DESCRIPTION
**Pull request by quangDecember**
## Summary of Changes

This pull request fixes issue #2081 
Besides fixing, I also added some code for previewing the issue/fix. Please help me check if it's suitable for the project.
Thanks

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift [hunk 1]
```diff
@@ -121,3 +121,19 @@ extension PasscodeEntryViewController: PasscodeInputViewDelegate {
         passcodePane.codeInputView.resetCode()
     }
 }
+
+#if canImport(SwiftUI) && MOZ_CHANNEL_FENNEC
```
Comment (iccub) [inline Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: That Preview stuff is not needed, just updating Strings in this PR is enough.
There are no plans to use SwiftUI for our project at the moment.

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
Looks nice, thanks :)
