### PR TITLE
Fixed #1102 by changing the WKWebview privacy protection using tab's isPrivate value.

### LINKED ISSUE #1102: Data from normal tab is carried over into private tab
### Description: 
Data from normal tab is carried over into private tab

### Steps to Reproduce 
  1. Visit jbhifi.com.au
  2. Add a product to shopping cart
  3. Long press on a different product and open in private tab via context menu
  4. Shopping cart in private tab already has the item added in step 2 

**Actual result:** 
Data from normal tab is carried over into private tab

**Expected result:**
No data should be carried over from normal tab to private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9.3(19.05.20.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc: @danishjafri88 @jumde

### PR DESCRIPTION
**Pull request by danishjafri88**
Added logic to utilise tab's `isPrivate` state to appropriately initialise the WKWebview.

STR from #1102 just instead of jbhifi.com.au use any other shopping cart site
like tedbaker.com. jbhifi.com.au is causing issues and is being worked on in a separate thread.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/PrivacyProtection/PrivacyProtection.swift [hunk 1]
```diff
@@ -8,8 +8,6 @@ import UIKit
 final class PrivacyProtection: PrivacyProtectionProtocol {
 
     var nonPersistent: Bool {
-        let isPrivateBrowsing = PrivateBrowsingManager.shared.isPrivateBrowsing
-        return isPrivateBrowsing
+        return true
```
Comment (iccub) [inline Client/Frontend/Browser/PrivacyProtection/PrivacyProtection.swift]: Can simplify this to `let nonPersistent = true` if we are never changing it

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/PrivacyProtection/PrivacyProtection.swift (hunk 1 above)
Comment (jhreis) [reply Client/Frontend/Browser/PrivacyProtection/PrivacyProtection.swift]: Can we actually just completely remove `PrivacyProtectionProtocol`? The only difference between the two is a `true`/`false` boolean. Can't we just put a flag `nonPersistent` directly onto the webview rather than using a protocol and two custom classes?

**Review by jhreis — CHANGES_REQUESTED** [review]

**Review by jhreis — APPROVED** [review]
Nice cleanup! :)

**Review by iccub — APPROVED** [review]

**Comment by jumde** [comment]
@jhreis @danishjafri88 - I think there is a memory leak when opening `jbhifi.com.au`. I tried on iPhone and iPad, brave browser freezes on both.

Otherwise the fix looks good.

**Comment by danishjafri88** [comment]
> @jhreis @danishjafri88 - I think there is a memory leak when opening `jbhifi.com.au`. I tried on iPhone and iPad, brave browser freezes on both.
> 
> Otherwise the fix looks good.

@jumde this was a known bug and is fixed + merged in development. I rebased with development to get those fixes.
