### PR TITLE
Fix #4181: Cap playlist popover width.

### LINKED ISSUE #4181: Reduce the size of Playlist modal
### Description: 
Reduce the size of Playlist modal

### Steps to Reproduce 
  1. Clean install 1.31
  2. Play a video on YT
  3. See the gigantic modal about playlist

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.31(22)

**Device details:** 
iPad Pro (iOS 15)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Not blocking 1.31 on this can be moved to next one

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #4181 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

IMG_CB1510AFF9E4-1

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

File: Client/Frontend/Browser/Playlist/PlaylistPopoverView.swift [hunk 1]
```diff
@@ -22,8 +22,10 @@ struct PlaylistPopoverView: View {
     var body: some View {
         if state == .addToPlaylist {
             addToPlaylistView
+                .frame(maxWidth: 450)
         } else {
             addedToPlaylistView
+                .frame(maxWidth: 450)
         }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/PlaylistPopoverView.swift]: Place in `Group`, then apply `frame` to the group i.e. 

```swift
Group {
  if x { } else { }
}
.frame(maxWidth: 450)
```

`Group` applies its modifiers to all children defined within it, which is useful for conditional ViewBuilder expressions such as if/else, switch, if-let-else

**Review by Brandon-T — APPROVED** [review]
