### PR TITLE
Fix #7026: Remove `SDWebImageSVGNativeCoder` and use `WebImageDownloader` to decode web images in Wallet

### LINKED ISSUE #7026: Remove SDWebImage SVG
### Description: 
- SDWebImage SVG crashes a lot when parsing SVGs
- We should remove it and use the Brave-Core SVG parser

### Brave Version: 
- 1.48.x

### PR DESCRIPTION
**Pull request by nuo-xu**
`WebImageDownloader` from core will be passed to wallet. And will be an environment value from the root of the hierarchy. 
In Wallet, `WebImageReader` will read the environment value and using the `WebImageDownloader` to decode web image via url or base64 image data. 
In News, `WebImageReader` will still use `SDWebImageManager` since its the default value for this environment path/value.  

## Summary of Changes
1. Both `SDWebImageManager` and `BraveCore.WebImageDownloader` conform protocol `WebImageDownloaderType` to make sure both can decode web image using urls and base64 image data. 
2. In Wallet, `BraveCore.WebImageDownloader` as a custom environment path/value will be passed from the root of the hierarchy (`CryptoView`) to everywhere in Wallet who needs to decode web images via `WebImageReader`
3. In News, nothing is passed so the `WebImageReader` will use the default `SDWebImageManager` to decode web image using urls and base64 image data. 

This pull request fixes #7026

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Test some websites that usually will cause app crashed caused by decoding svg favicon using `SDWebImageSVGNativeCoder` for example: [https://users.rust-lang.org/](https://users.rust-lang.org/)
2. Test web images (NFT) inside Wallet that usually rendered in previous version still get rendered the same (svg or not svg)
3. Test Brave News settings -> Popular Source images are still rendered the same

## Screenshots:

https://github.com/brave/brave-ios/assets/1187676/f6d84a33-6ee2-4216-88fc-99ef68ee067e

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Preview Content/MockStores.swift [hunk 1]
```diff
@@ -6,9 +6,21 @@
 import Foundation
 import BraveCore
 import BraveShared
+import BraveUI
 
 #if DEBUG
 
+
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Preview Content/MockStores.swift]: Extra whitespace here

**Review by StephenHeaps — APPROVED** [review]

File: Package.swift [hunk 2]
```diff
@@ -51,7 +51,6 @@ var package = Package(
     .package(url: "https://github.com/airbnb/lottie-ios", from: "3.1.9"),
     .package(url: "https://github.com/jrendel/SwiftKeychainWrapper", from: "4.0.1"),
     .package(url: "https://github.com/SDWebImage/SDWebImage", exact: "5.10.3"),
-    .package(url: "https://github.com/SDWebImage/SDWebImageSVGNativeCoder", from: "0.1.1"),
     .package(url: "https://github.com/SDWebImage/SDWebImageSwiftUI", from: "2.2.0"),
```
Comment (kylehickinson) [inline Package.swift:54]: Unrelated but is this still needed?

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 3]
```diff
@@ -5,81 +5,82 @@
...
+        }
+      }
     }
+    return nil
+  }
+  
+  public func imageFromData(data: Data) -> UIImage? {
+    WebImageDownloader.image(from: data)
   }
 }
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: This shouldn't exist here, BraveUI shouldn't import BraveCore

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 4]
```diff
@@ -5,81 +5,82 @@
...
-    for coder in supportedCoders where coder.canDecode(from: data) {
-      image = coder.decodedImage(with: data, options: options)
-      break
+  public func imageFromData(data: Data) -> UIImage? {
+    SDImageCodersManager.shared.decodedImage(with: data)
+  }
+}
+
+extension BraveCore.WebImageDownloader: WebImageDownloaderType {
+  @MainActor public func downloadImage(url: URL?) async -> UIImage? {
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: Optional URL doesn't really make sense

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 5]
```diff
@@ -5,81 +5,82 @@
...
     self.content = content
     self.url = url
-    self.options = options
-    self.coderOptions = coderOptions
   }
 
   public var body: some View {
-    content(imageManager.image, imageManager.isFinished)
+    content(image)
       .onAppear {
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: Make this `.task` instead so it is cancelled when the view leaves the hierarchy and add `.id(url)` to the view to ensure its reloaded properly when the URL changes

File: Sources/BraveWallet/Crypto/CryptoView.swift [hunk 6]
```diff
@@ -272,6 +272,10 @@ public struct CryptoView: View {
       .init(action: { [appRatingRequestAction] in
         appRatingRequestAction?()
       }))
+    .environment(
+      \.webImageDownloader,
+       walletStore.cryptoStore?.webImageDownloader
```
Comment (kylehickinson) [inline Sources/BraveWallet/Crypto/CryptoView.swift]: this can possibly resolve to nil which would break image loading entirely

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 7]
```diff
@@ -5,81 +5,82 @@
...
-  func cancel() {
-    operation?.cancel()
-    operation = nil
+extension SDWebImageManager: WebImageDownloaderType {
+  @MainActor public func downloadImage(url: URL?) async -> UIImage? {
+    return await withCheckedContinuation { continuation in
+      loadImage(with: url, progress: nil) { image, _, _, _, _, _ in
+        continuation.resume(returning: image)
+      }
+    }
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: This should become a `withTaskCancellationHandler` that holds onto the `SDWebImageCombinedOperation` and calls cancel on it when the task is cancelled:

```swift
@MainActor public func downloadImage(url: URL?) async -> UIImage? {
  var operation: SDWebImageCombinedOperation?
  return await withTaskCancellationHandler {
    operation?.cancel()
  } operation: {
    await withCheckedContinuation { continuation in
      operation = loadImage(with: url, progress: nil) { image, _, _, _, _, _ in
        continuation.resume(returning: image)
      }
    }
  }
}
```

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 8]
```diff
@@ -5,81 +5,82 @@
...
-    guard base64Str.hasPrefix("data:image/") else { return }
-    guard let dataString = base64Str.separatedBy(",").last else { return }
-    
-    let data = Data(base64Encoded: dataString, options: .ignoreUnknownCharacters)
-    for coder in supportedCoders where coder.canDecode(from: data) {
-      image = coder.decodedImage(with: data, options: options)
-      break
+  public func imageFromData(data: Data) -> UIImage? {
+    SDImageCodersManager.shared.decodedImage(with: data)
+  }
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: It probably makes sense to make this async as well, no need to decode an image on the current thread

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Package.swift (hunk 2 above)
Comment (nuo-xu) [reply Package.swift:54]: still used to display NFT that has gif format image

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 9]
```diff
@@ -5,82 +5,70 @@
...
-  @Published public var image: UIImage?
-  /// loaded image data, may be nil if hit from memory cache. This will only published once loading is finished
-  @Published public var isFinished: Bool = false
-  /// loading error
-  @Published public var error: Error?
-
-  private var manager = SDWebImageManager.shared
-  private var operation: SDWebImageOperation?
+public protocol WebImageDownloaderType: AnyObject {
+  func downloadImage(url: URL) async -> (UIImage?, Error?)
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: API design nit: swap to a throwing function instead:

```swift
func downloadImage(url: URL) async throws -> UIImage
```

Either it downloads an image successfully or there's an error. No need to deal with optionals or tuples.

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 10]
```diff
@@ -5,82 +5,70 @@
...
-    content(imageManager.image, imageManager.isFinished)
-      .onAppear {
-        if let urlString = url?.absoluteString {
-          if urlString.hasPrefix("data:image/") {
-            imageManager.load(base64Str: urlString)
-          } else if !imageManager.isFinished {
-              imageManager.load(url: url, options: options)
-          }
+    content(image, error)
+      .id(url)
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: This may need to be _after_ the `task`? Not sure if `id` will apply correctly to the modifiers after it

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 11]
```diff
@@ -5,82 +5,70 @@
...
-  @StateObject private var imageManager: WalletWebImageManager = .init()
-  var url: URL?
-  var options: SDWebImageOptions
-  var coderOptions: [SDImageCoderOption: Any]
+  var url: URL
+  
+  @Environment(\.webImageDownloader) private var imageDownloader: WebImageDownloaderType
+  
+  @State private var image: UIImage?
+  @State private var error: Error?
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: Maybe store this as `Result<UIImage, Error>` instead

Comment (kylehickinson) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: What's the reason for storing the error btw? It's not used at all anywhere in this PR

File: Sources/BraveWallet/Crypto/NFTImageView.swift [hunk 12]
```diff
@@ -20,20 +20,26 @@ struct NFTImageView<Placeholder: View>: View {
...
+            Image(uiImage: image)
+              .resizable()
+              .aspectRatio(contentMode: .fit)
+          } else {
+            placeholder()
+          }
+        }
+      } else if url.isSecureWebPage() {
+        if url.absoluteString.hasSuffix(".gif") {
+          WebImage(url: url)
```
Comment (kylehickinson) [inline Sources/BraveWallet/Crypto/NFTImageView.swift:36]: Not sure that this is technically enough to determine if its a gif, but maybe fine for the time being? Does BraveCore's implementation not download gif's correctly? Or is it just about display?

File: Sources/BraveWallet/Extensions/WebImageDownloaderExtensions.swift [hunk 13]
```diff
@@ -0,0 +1,25 @@
+// Copyright 2023 The Brave Authors. All rights reserved.
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import BraveCore
+import BraveUI
+
+extension BraveCore.WebImageDownloader: WebImageDownloaderType {
+  @MainActor public func downloadImage(url: URL) async -> (UIImage?, Error?) {
```
Comment (kylehickinson) [inline Sources/BraveWallet/Extensions/WebImageDownloaderExtensions.swift]: Do these methods need to be main actor isolated?

File: Sources/BraveUI/SwiftUI/WebImageReader.swift [hunk 14]
```diff
@@ -5,82 +5,70 @@
...
+    get { self[WebImageDownloaderKey.self] }
+    set { self[WebImageDownloaderKey.self] = newValue }
   }
+}
 
-  func cancel() {
-    operation?.cancel()
-    operation = nil
+extension SDWebImageManager: WebImageDownloaderType {
+  @MainActor public func downloadImage(url: URL) async -> (UIImage?, Error?) {
```
Comment (kylehickinson) [inline Sources/BraveUI/SwiftUI/WebImageReader.swift]: Do these methods need to be main actor isolated?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Sources/BraveUI/SwiftUI/WebImageReader.swift (hunk 11 above)
Comment (nuo-xu) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: as @StephenHeaps mentioned that `isFinished` is removed there is no way to determine image is being loaded. If both image and error are nil can be considered as its being loaded. If we don't care about loading state, i can remove it.

Comment (kylehickinson) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: Given how this was set up as a protocol, loading state should be held by `WebImageReader` prior to calling `downloadURL` then. There doesn't seem to be a need for holding onto errors though atm

Comment (nuo-xu) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: @kylehickinson i realize adding Result<UIImage, Error>/Throws is creating unnecessary complexity. also feel weird that one protocol method requires throw an error but the other just an optional UIImage. So, I'm removing the error as it doesn't seem to be worth of adding right now.

Comment (kylehickinson) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: Fine to remove the error entirely right now, there's no usage of it either way.

File: Sources/BraveWallet/Extensions/WebImageDownloaderExtensions.swift (hunk 13 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Extensions/WebImageDownloaderExtensions.swift]: it will give a crash (EXC_BREAKPOINT) once you start loading NFT images without the main actor isolated

File: Sources/BraveUI/SwiftUI/WebImageReader.swift (hunk 14 above)
Comment (nuo-xu) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: however, this one does not need to be main actor isolated 🤔

File: Sources/BraveWallet/Crypto/NFTImageView.swift (hunk 12 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/NFTImageView.swift:36]: There is another field in the metadata `animation_url`, however, it's a html (technically, this field is for multi-media support. It could a gif, a video or a piece of audio) I guess WKWebView all the way 🥲 
The BraveCore's implementation is able to download one frame of the gif which will be a static image.

Comment (kylehickinson) [reply Sources/BraveWallet/Crypto/NFTImageView.swift:36]: Okay sounds good we can keep this for now

File: Sources/BraveWallet/Extensions/WebImageDownloaderExtensions.swift (hunk 13 above)
Comment (kylehickinson) [reply Sources/BraveWallet/Extensions/WebImageDownloaderExtensions.swift]: Okay fine to keep the main actor isolation for brave core's, most likely some sort of threading issue on the chromium side

Comment (nuo-xu) [reply Sources/BraveWallet/Extensions/WebImageDownloaderExtensions.swift]: can confirm no crash using SDWebImage without being main actor isolated to load NFT images. so yeah must be some threading issues on the chromium side.

File: Sources/BraveUI/SwiftUI/WebImageReader.swift (hunk 11 above)
Comment (nuo-xu) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: `UIImage?` is now the only `State` variable being stored in [8e4439d](https://github.com/brave/brave-ios/pull/7881/commits/8e4439db703e9ca9718fade5121652e75ebc5e68)

File: Sources/BraveUI/SwiftUI/WebImageReader.swift (hunk 10 above)
Comment (nuo-xu) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: `id` is now after `task` in [8e4439d](https://github.com/brave/brave-ios/pull/7881/commits/8e4439db703e9ca9718fade5121652e75ebc5e68)

File: Sources/BraveUI/SwiftUI/WebImageReader.swift (hunk 9 above)
Comment (nuo-xu) [reply Sources/BraveUI/SwiftUI/WebImageReader.swift]: `Error` has been removed in [8e4439d](https://github.com/brave/brave-ios/pull/7881/commits/8e4439db703e9ca9718fade5121652e75ebc5e68)

**Review by kylehickinson — APPROVED** [review]
