### PR TITLE
Fixed #304 by removing 'Preferences' folder from clearing.

### LINKED ISSUE #304: Preferences aren't persisted throughout multiple launches
### Description: 
Preferences aren't persisted throughout multiple launches

### Steps to Reproduce 
  1. Install test build from TF
  2. Change preferences settings 
  3. Remove app from memory and relaunch, changed settings revert back to defaults

**Actual result:** 
Preferences aren't persisted throughout multiple launches

**Expected result:**
Preferences should be retained across multiple launch

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
18.10.02.15

**Device details:** 
iPhone 7+ (iOS 11.4.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Default favourite gets added everytime app is relaunched #149

### PR DESCRIPTION
**Pull request by danishjafri88**
This fixes #304. While clearing cache and data the iOS **Preferences** folder was deleted. This folder is also used to store UserDefaults. Since the UserDefaults was destroyed all preferences were lost.

p.s You will not notice this till relaunch as the Userdefaults is cached in memory.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Settings/Clearables.swift [hunk 1]
```diff
@@ -127,7 +127,10 @@ class CacheClearable: Clearable {
             URLCache.shared.removeAllCachedResponses()
             
             var err: Error?
-            for item in ["Caches", "Preferences", "Cookies", "WebKit"] {
+            /* Please note that this is a hack. If possible please use a public api.
```
Comment (jhreis) [inline Client/Frontend/Settings/Clearables.swift]: Please remove this comment. If you feel this is inadequate, file a ticket instead of leaving a comment. Link to the code, and this PR.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Settings/Clearables.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/Frontend/Settings/Clearables.swift]: Done

**Review by jhreis — APPROVED** [review]
