### PR TITLE
Fix #3172: Autocomplete label covers clear button in url bar.

### LINKED ISSUE #3172: 'Clear' does not show up in url bar when autocompletion is available
### Steps to Reproduce 
  1. Visit wikipedia once
  2. Tap on url bar, type `w` start typing the wikipedia url
  3. See that url autocompleted but there is no clear button at the end of it

**Actual result:** 
Clear button is hidden

IMG_42AA03BEFFA3-1

**Expected result:**
Should be visible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

The url autocomplete code is not great in general, it uses a mix of uitextfield and uilabel to display urls, and the uilabel gets recreated on each key input. This is an easy solution for now

This pull request fixes #3172 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

IMG_BD28589A9099-1

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Widgets/AutocompleteTextField.swift [hunk 1]
```diff
@@ -214,7 +214,10 @@ class AutocompleteTextField: UITextField, UITextFieldDelegate {
 
         let enteredTextSize = self.attributedText?.boundingRect(with: self.frame.size, options: NSStringDrawingOptions.usesLineFragmentOrigin, context: nil)
         frame.origin.x = (enteredTextSize?.width.rounded() ?? 0)
-        frame.size.width = self.frame.size.width - frame.origin.x
+        // The autocomplete label overlaps whole uitextfield covering the clear button.
+        // The label's frame must be slightly shorter to make the clear button visible.
+        let clearButtonOffset: CGFloat = 30
```
Comment (kylehickinson) [inline Client/Frontend/Widgets/AutocompleteTextField.swift:219]: Does this work in other languages?

Comment (kylehickinson) [reply Client/Frontend/Widgets/AutocompleteTextField.swift:219]: Ah never mind, clear button is an icon, so it doesn't change 😆

**Review by kylehickinson — APPROVED** [review]
