### PR TITLE
Fix #3023: Migrate ads confirmations from ledger state container

### LINKED ISSUE #3023: "Ad notifications received this month" & "Estimated pending rewards" being cleared after upgrade
### Description: 

When updating from `1.20` to `1.21`, `Ad notifications received this month` & `Estimated pending rewards` are cleared.

### Steps to Reproduce 

  1. install `1.20 (20.09.11.20)` via the AppStore
  2. enable rewards and change the ads settings to 5/hr
  3. visit brave.com and a few other websites until you receive an ad notification
  4. click on the ad which should load a new tab with the ad
  5. double check and ensure that `Ad notifications received this month` & `Estimated pending rewards` have been updated
  6. upgrade to `1.21 (20.11.09.09)` using TF

**Actual result:** 

Both `Ad notifications received this month` & `Estimated pending rewards` are being cleared. Example of the issue:
* https://youtu.be/xESx2CkxAjs

**Expected result:**

Both `Ad notifications received this month` & `Estimated pending rewards` and shouldn't be cleared

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.21 (20.11.09.09)`

**Device details:** 

* `iPhone 11` running `Android 14` - **Reproduced**
* `iPhone 6s+` running `Android 12` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @tmancey @NejcZdovc @bsclifton @aekeus @kylehickinson @iccub

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #3023 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift [hunk 1]
```diff
@@ -134,6 +134,36 @@ extension BrowserViewController {
         Preferences.NewTabPage.atleastOneNTPNotificationWasShowed.value = false
     }
     
+    static func migrateAdsConfirmations(for configruation: BraveRewardsConfiguration) {
+        // To ensure after a user launches 1.21 that their ads confirmations, viewed count and
+        // estimated payout remain correct.
+        //
+        // This hack is unfortunately neccessary due to a missed migration path when moving
```
Comment (tmancey) [inline Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift:141]: There is currently no way this logic can move to the ads lib as Rewards has now deprecated save/load functionality so there would be no way to access the file

**Review by tmancey — APPROVED** [review]
LGTM++

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift:141]: Right, just meant it should have been handled in brave-core where these directories & paths are known, but due to timing we will add this change here with hard-coded paths & file names
