### PR TITLE
Fix #5843, #5844: Wallet dapps show empty modal, account not selected after creating first account

### LINKED ISSUE #5843: [Follow up #5815] Wallet panel is not shown when a Dapp is trying to interact with wallet
### Description: 
[Follow up #5815] Wallet panel is not shown when a Dapp is trying to interact with wallet

### Steps to Reproduce 
  1. Set Solana as active network in Wallet
  2. Visit `https://app.1inch.io` and try to connect wallet
  3. Shows White/Dark panel depending on device theme and doesn't allow to interact with wallet
  4. Change network in Wallet and repeat steps, still doesn't show wallet

**Actual result:** 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/184352789-fda1e080-8cb4-43a0-8b48-079eba1d57ae.MP4> | <video src=https://user-images.githubusercontent.com/17010094/184352891-fc6de978-7bf1-4f5d-8c74-ccf5e2b460c2.MP4>

**Expected result:**
Able to interact with Dapp

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.11.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- When a new keyring is created, call `setSelectedAccount` on the account in that keyring
- Additionally, protect against having no selected account for a coin type by selecting the first account if this situation occurs.
- #5844 was caused by this bug. When switching networks in the panel, the `selectedAccount` returned from keyring service was nil because we did not select any account after creating the keyring.

This pull request fixes #5843, #5844.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Reset your wallet
2. Setup a new wallet
3. Open buy/send/swap. 
4. Verify Ethereum account shows as selected account in the top left.
5. Close buy/send/swap.
6. Switch to Solana network, create an account when prompted.
7. Open buy/send/swap. 
8. Verify Solana account shows as selected account in the top left
9. Close buy/send/swap, then close wallet
10. Open to `app.1inch.io`
11. Connect your wallet
12. Verify blank modal does not appear

## Screenshots:

https://user-images.githubusercontent.com/5314553/184379195-dee97ce1-14a1-4098-b5b0-ef137041f1de.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/KeyringStore.swift [hunk 1]
```diff
@@ -155,6 +155,10 @@ public class KeyringStore: ObservableObject {
         if self.selectedAccount.address != selectedAccountAddress {
           if let selectedAccount = selectedAccountKeyring.accountInfos.first(where: { $0.address == selectedAccountAddress }) {
             self.selectedAccount = selectedAccount
+          } else if let firstAccount = selectedAccountKeyring.accountInfos.first {
```
Comment (nuo-xu) [inline BraveWallet/Crypto/Stores/KeyringStore.swift:158]: this else if is really when `self.selectedAccount.` is just .init() right?

Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/KeyringStore.swift:158]: Yes it should work for that, and it should also protect against any other _potential_ situation where no selected account exists in the keyring for some coin type. 

FWIW, I cannot hit this flow anymore with the fix from yesterday in #5815, and the fix below to select an account after a keyring is created.

File: BraveWallet/Crypto/Stores/KeyringStore.swift [hunk 2]
```diff
@@ -381,10 +385,10 @@ extension KeyringStore: BraveWalletKeyringServiceObserver {
         break
       }
       
-      if selectedAccount.coin.keyringId != keyringId {
+      let newKeyring = await keyringService.keyringInfo(keyringId)
+      if let newAccount = newKeyring.accountInfos.first {
         walletService.setSelectedCoin(coin)
```
Comment (nuo-xu) [inline BraveWallet/Crypto/Stores/KeyringStore.swift:389]: if you set a new coin here without setNetwork
`selectedAccountChanged` will not take care of changing network since the coin is already set to the correct one.

File: BraveWallet/Crypto/Stores/KeyringStore.swift (hunk 1 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/KeyringStore.swift:158]: can we have some comment on this condition for future reference. i was little confused by looking at it at the beginning

File: BraveWallet/Crypto/Stores/KeyringStore.swift (hunk 2 above)
Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/KeyringStore.swift:389]: `NetworkStore` observes selected account changed and updates the network. However, this did catch an issue where `isSwapSupported` was not being updated when a Solana account was created outside of the network picker. This was addressed in [bc8e9c3](https://github.com/brave/brave-ios/pull/5845/commits/bc8e9c3c3a5ae8c3c049a6bbe391d8d0842c162b)

File: BraveWallet/Crypto/Stores/KeyringStore.swift (hunk 1 above)
Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/KeyringStore.swift:158]: There is a comment already below this line

**Comment by StephenHeaps** [comment]
Updated description, but this PR also fixes #5844 which was caused by this bug. When switching networks in the panel, the `selectedAccount` returned from keyring service was nil because we did not select any account after creating the keyring, so we did not have an account to switch to for that network.

**Review by nuo-xu — APPROVED** [review]

File: BraveWallet/Crypto/Stores/KeyringStore.swift [hunk 3]
```diff
@@ -155,6 +155,10 @@ public class KeyringStore: ObservableObject {
         if self.selectedAccount.address != selectedAccountAddress {
           if let selectedAccount = selectedAccountKeyring.accountInfos.first(where: { $0.address == selectedAccountAddress }) {
             self.selectedAccount = selectedAccount
+          } else if let firstAccount = selectedAccountKeyring.accountInfos.first {
+            // try and correct invalid state (no selected account for this coin type)
+            self.selectedAccount = firstAccount
+            await self.keyringService.setSelectedAccount(firstAccount.address, coin: firstAccount.coin)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/KeyringStore.swift]: Won't this call `setSelectedAccount` twice when `updateKeyringInfo` gets called outside of init? (Due to `selectedAccount.didSet`)

Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/KeyringStore.swift]: Yes, nice catch, will remove the call to `keyringService`.

Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/KeyringStore.swift]: Addressed in [40f5664](https://github.com/brave/brave-ios/pull/5845/commits/40f5664659ea1afa432738b4b3f0d844f6dada0c)

**Review by kylehickinson — APPROVED** [review]
