### PR TITLE
Fix #5415: Private tab Link-Previews

### LINKED ISSUE #5415: 'Manage website data' screen gets filled while in private mode
### Description: 
Reported here https://community.brave.com/t/lots-of-website-data-remains-after-clearing-history-ios-15-3-15-4/365627/19

### Steps to Reproduce 
  1. Use private browsing mode
  2. Browse websites
  3. Exit private browsing mode, go to 'manage website data' screen

**Actual result:** 
Manage website data screen has entries, should be empty

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Hard to reproduce for me, our users have success in reproducing it sometimes

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix private tabs Link Previews to not store History.
- Fix private tabs Link Previews to use the same delegates as all other tabs, so it automatically gets ad-block, fingerprint protection, etc...

This pull request fixes #5415

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
- In the Ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/LinkPreviewViewController.swift [hunk 1]
```diff
@@ -9,33 +9,49 @@ import Shared
...
 class LinkPreviewViewController: UIViewController {
 
-  let url: URL
+  private let url: URL
+  private weak var parentTab: Tab?
+  private var currentTab: Tab?
+  private weak var browserController: BrowserViewController?
 
-  init(url: URL) {
+  init(url: URL, for tab: Tab, browserController: BrowserViewController) {
```
Comment (iccub) [inline Client/Frontend/Browser/LinkPreviewViewController.swift:17]: Let's fix the tight coupling in a rewrite later this year, ticket for it here https://github.com/brave/brave-ios/issues/5934

File: Client/Frontend/Browser/LinkPreviewViewController.swift [hunk 2]
```diff
@@ -9,33 +9,49 @@ import Shared
...
-    let domain = Domain.getOrCreate(forUrl: url, persistent: !PrivateBrowsingManager.shared.isPrivateBrowsing)
-
-    BlocklistName.blocklists(forDomain: domain).on.forEach {
-      ContentBlockerHelper.ruleStore.lookUpContentRuleList(forIdentifier: $0.filename) { rule, _ in
-        guard let rule = rule else { return }
-        wk.configuration.userContentController.add(rule)
-      }
+    
+    currentTab = Tab(configuration: tabWebView.configuration,
+                     type: .private,
```
Comment (iccub) [inline Client/Frontend/Browser/LinkPreviewViewController.swift]: per slack discussion we want to base this off tab's private mode?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 3]
```diff
@@ -393,8 +393,9 @@ extension BrowserViewController: WKNavigationDelegate {
   public func webView(_ webView: WKWebView, decidePolicyFor navigationResponse: WKNavigationResponse, decisionHandler: @escaping (WKNavigationResponsePolicy) -> Void) {
     let response = navigationResponse.response
     let responseURL = response.url
+    let tab = tabManager[webView] ?? (webView as? TabWebView)?.tab
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Maybe if it's done every time across this file we can create a helper to always grab the proper tab? instead of writing it like this every time. I'm fine if we keep it and address it later in the rewrite

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Fixed: https://github.com/brave/brave-ios/pull/5933/commits/95f0a4adade087473b54181d7171040fc030b62a

File: Client/Frontend/Browser/LinkPreviewViewController.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/LinkPreviewViewController.swift]: Fixed: https://github.com/brave/brave-ios/pull/5933/commits/34b1b748df12e8c23b40e38b9bd50f972a7b3036

**Review by iccub — APPROVED** [review]
Thank you <3
