### PR TITLE
Fix #6066: Fixes Favicon fetching to fetch from Brave-Core

### LINKED ISSUE #5312: Incorrect favicons in history panel post upgrade
### Description: 
Incorrect favicons in history panel post upgrade

### Steps to Reproduce 
  1. Install 1.37 build from app store
  2. Visit a bunch of pages to add browsing history
  3. Upgrade to 1.38 build 
  4. Upon upgrade open the history page on the active tab, site favicons are all wrong
  5. Open a new link/reload the same active tab, favicons gets fixed in history 

**Actual result:** 
image

**Expected result:**
Show correct favicons when upgraded from previous version

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.38 (22.4.29.16)

**Device details:** 
iPad Pro (iOS 15.5 Beta 3)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @Uni-verse @kjozwiak @iccub

### LINKED ISSUE #6066: Improve Favicon fetching
## Test Plan:
- Test Favicons in History
- Test Favicons in Bookmarks
- Test Favicons in Sync-Chain (sync bookmarks and history)
- Test visiting a website, showing tab switcher with Favicon.
- Test visiting a website, showing tab switcher with Favicon, and close the tab, expect no crashes on tab close.
- Test Favicons in widgets

### LINKED ISSUE #6752: Crash on yourls website
### Steps to Reproduce 
  1. visit https://yourls.org/
  2.
  3.

### Brave Version: Version 1.46.2 (23.1.10.20)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? yes
- did you check in Safari/Firefox (WkWebView-based browsers)? yes

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Move everything out of BraveShared
- Adding separate renderers for custom and bundled icons vs. fetched icons
- Removing FaviconMO
- Porting all APIs that use FaviconMO to use the new APIs
- Cache icons for domain url
- Add SVG Support for icons
- Move Favicon scripts to `.defaultClient` content world.
- Moved Widgets to its own module

This pull request fixes #6066

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

## Test Plan:
- Test Favicons in History
- Test Favicons in Bookmarks
- Test Favicons in Sync-Chain (sync bookmarks and history)
- Test visiting a website, showing tab switcher with Favicon.
- Test visiting a website, showing tab switcher with Favicon, and close the tab, expect no crashes on tab close.
- Test Favicons in widgets

### CODE REVIEW

File: App/BraveWidgets/FavoritesWidget.swift [hunk 1]
```diff
@@ -138,15 +139,8 @@ private struct FavoritesGridView: View {
...
-                  FaviconImage(image: image, contentMode: attributes.contentMode, includePadding: {
-                    switch attributes.contentMode {
-                    case .scaleToFill, .scaleAspectFit, .scaleAspectFill:
-                      return false
-                    default:
-                      return true
-                    }
-                  }())
-                    .background(Color(attributes.backgroundColor ?? .clear))
+                  FaviconImage(image: image, contentMode: .scaleAspectFit, includePadding: false)
```
Comment (soner-yuksel) [inline App/BraveWidgets/FavoritesWidget.swift:142]: I believe we dont use contentMode in FavIcon object anymore and we will always pass . scaleAspectFit to FavIocnImage?

I think we can make `contentMode` parameter defaulted to .scaleAspectFit in this case ?

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift [hunk 2]
```diff
@@ -230,13 +231,12 @@ extension Tab {
...
     group.notify(queue: .main) {
-      let faviconURL = URL(string: self.displayFavicon?.url ?? "")
-      if faviconURL == nil {
+      if self.displayFavicon == nil {
         adsRewardsLog.warning("No favicon found in \(self) to report to rewards panel")
       }
       rewards.reportLoadedPage(
         url: url, redirectionURLs: urls.isEmpty ? [url] : urls,
-        faviconURL: faviconURL, tabId: Int(self.rewardsId),
+        faviconURL: nil, tabId: Int(self.rewardsId),
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: We might remove the faviconURL anymore we can remove it from the function decleration

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 3]
```diff
@@ -615,11 +616,10 @@ extension BrowserViewController: WKNavigationDelegate {
 
       navigateInTab(tab: tab, to: navigation)
       if let url = tab.url, tab.shouldClassifyLoadsForAds {
-        let faviconURL = URL(string: tab.displayFavicon?.url ?? "")
         rewards.reportTabUpdated(
           tab: tab,
           url: url,
-          faviconURL: faviconURL,
+          faviconURL: nil,
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Check the comment above please

File: Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift [hunk 4]
```diff
@@ -151,48 +153,14 @@ extension BrowserViewController {
...
-
-            self?.createSearchEngine(url, reference: reference, icon: searchEngineIcon)
-          }
-
-        })
-    } else {
-      createSearchEngine(url, reference: reference, icon: searchEngineIcon)
-    }
+    let searchEngineIcon = favicon?.image ?? Favicon.defaultImage
+    createSearchEngine(url, reference: reference, icon: searchEngineIcon)
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift:162]: This is like proof of amazing improvement here 🥇

File: Client/Frontend/Browser/FaviconHandler.swift [hunk 5]
```diff
@@ -16,7 +16,7 @@ class FaviconHandler {
   private let backgroundQueue = OperationQueue()
 
   init() {
-    self.tabObservers = registerFor(.didLoadPageMetadata, queue: backgroundQueue)
+    //self.tabObservers = registerFor(.didLoadPageMetadata, queue: backgroundQueue)
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/FaviconHandler.swift]: nit: remove

File: Client/Frontend/Browser/Favicons/UIImageView+Favicon.swift [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+  }
+
+  /// Cancel any pending favicon load task. This is to prevent race condition UI glitches with reusable table/collection view cells.
+  func cancelFaviconLoad() {
+    faviconTask?.cancel()
+    faviconTask = nil
+  }
+  
+  func clearMonogramFavicon() {
+
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Favicons/UIImageView+Favicon.swift:47]: I believe we should clear the monogram here :)

File: Client/Frontend/Browser/Tab.swift [hunk 7]
```diff
@@ -276,6 +278,14 @@ class Tab: NSObject {
     rewardsId = UInt32.random(in: 1...UInt32.max)
     nightMode = Preferences.General.nightModeEnabled.value
     syncTab = tabGeneratorAPI?.createBraveSyncTab(isOffTheRecord: type == .private)
+    
+    if let syncTab = syncTab {
+      faviconDriver = FaviconDriver(webState: syncTab.webState).then {
+        $0.setMaximumFaviconImageSize(1024)
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Tab.swift:285]: Do we need to set the maximum image size everytime we set a driver ?

File: Sources/BraveFavicon/Assets/Images.xcassets/defaultFavicon.imageset/Contents.json [hunk 8]
```diff
@@ -0,0 +1,22 @@
+{
+  "images" : [
```
Comment (soner-yuksel) [inline Sources/BraveFavicon/Assets/Images.xcassets/defaultFavicon.imageset/Contents.json]: nit: Maybe we should use SFSymbol for this

**Comment by soner-yuksel** [comment]
Btw I tested every part of the application throughly and Fav icons are working excellent, great job. These are some nits and questions thats all.

Also reminder whichever gets merged first, other Pr needs to be altered accordingly the changes https://github.com/brave/brave-ios/pull/6755

**Comment by soner-yuksel** [comment]
I believe FavIconFethcer in `TestFavicons` test class must be changed in order to support tests with new version.

File: Client/Frontend/Browser/Tab.swift (hunk 7 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Tab.swift:285]: Yeah we need to. I made it this way on purpose. All it does is set an integer in Brave-Core, so that any favicons downloaded will be restricted by that size. This is because some Favicons are absolutely HUGE, and we need this number so we can scale them down if they're larger.

File: Client/Frontend/Browser/Favicons/UIImageView+Favicon.swift (hunk 6 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Favicons/UIImageView+Favicon.swift:47]: Nothing to remove here. The monogram is part of the image itself instead of a UILabel. Still trying to figure out whether we should change it to a label.

File: App/BraveWidgets/FavoritesWidget.swift (hunk 1 above)
Comment (Brandon-T) [reply App/BraveWidgets/FavoritesWidget.swift:142]: This is a SwiftUI struct. I left it in case we do use it for scaling the SwiftUI image.

File: Package.swift [hunk 9]
```diff
@@ -23,10 +23,11 @@ var package = Package(
     .library(name: "Data", targets: ["Data"]),
     .library(name: "Storage", targets: ["Storage", "sqlcipher"]),
     .library(name: "BrowserIntentsModels", targets: ["BrowserIntentsModels"]),
-    .library(name: "BraveWidgetsModels", targets: ["BraveWidgetsModels"]),
+    .library(name: "BraveWidgets", targets: ["BraveWidgets"]),
```
Comment (kylehickinson) [inline Package.swift]: Whats the reason for renaming this? We dont actually have the widgets inside this package still?

File: Package.swift [hunk 10]
```diff
@@ -241,6 +242,20 @@ var package = Package(
       .copy("opml-test-files/states.opml"),
     ]),
     .target(name: "CodableHelpers"),
+    .target(
+      name: "BraveFavicon",
```
Comment (kylehickinson) [inline Package.swift]: Naming nit: Not a brave feature, maybe better to call it `Favicons` or something similar

File: Package.swift (hunk 9 above)
Comment (Brandon-T) [reply Package.swift]: Ahh I can change the name back. I used to have the widgets inside this package, but I got some weird compilation errors, so I had to move it out at the last moment.

Comment (Brandon-T) [reply Package.swift]: Fixed @kylehickinson I had it as `BraveWidgets.framework` so everything was in there. I changed it back to BraveWidgetsModels and removed the dependencies on `BraveShared`

File: Package.swift (hunk 10 above)
Comment (Brandon-T) [reply Package.swift]: Fixed

File: Package.swift [hunk 11]
```diff
@@ -165,8 +166,8 @@ var package = Package(
     ),
     .target(
       name: "BraveWidgetsModels",
-      dependencies: ["BraveShared"],
-      sources: ["BraveWidgets.intentdefinition", "LockScreenFavoriteIntentHandler.swift"],
+      dependencies: ["Favicon", "LoggerPlugin"],
```
Comment (kylehickinson) [inline Package.swift]: `LoggerPlugin` should be part of `plugins` not `dependencies`

Comment (Brandon-T) [reply Package.swift]: Fixed

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Tests failing

File: Client/Frontend/Browser/Favicons/UIImageView+Favicon.swift (hunk 6 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Favicons/UIImageView+Favicon.swift:47]: Can we have comment here why it empty here in that case? It has been used in many places and it can be if someone came upon it and wonder why it is empty method.

**Review by soner-yuksel — APPROVED** [review]

**Comment by soner-yuksel** [comment]
Also one thing would be very nice to change in this PR. FaviconImage class we integrate to SwiftUI views is using faviconLoader - PlaylistFolderImageLoader which is created inside PlaylistNewFolderView.

It can be great to move this out of Playlist entirely and move it to BraveShared etc. Because we will use this more and more.
