### PR TITLE
Fix #2946 : iOS Sync Integration

### LINKED ISSUE #2946: Add Sync v2 support for bookmarks
## Description
Add support for syncing bookmarks with desktop/android using new sync APIs

#### Import from CoreDB succeeds
 - Does table (or records) get deleted? How can we verify

#### Import from CoreDB fails
 - Does this retry? if so, how many times?
 - Failure screen should show - what should this look like?

### Test new profile

### LINKED ISSUE #2962: Add sync translations
- [x] push new strings once https://github.com/brave/brave-ios/issues/2946 is done
- [x] pull translations

### LINKED ISSUE #2996: [Sync v2] Crash when moving bookmark to just deleted folder
### Steps to Reproduce 
DeviceA : iPhone SE
DeviceB: Ubuntu 18.04 LTS

1. Clean install on DeviceA and DeviceB
1. Establish sync chain between DeviceA and DeviceB
1. DeviceA: Add bookmark folder FA1
1. DeviceA: Add bookmark A1
1. Wait for sync update
1. DeviceB: Delete FA1 and at the same time on DeviceA: Move A1 to FA1
1. Wait for sync update

**Actual result:** 
Crash

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.21 (20.10.27.20), iPhone SE (iOS 12.4)

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

### LINKED ISSUE #2997: Internet connection check is not performed when `Delete sync chain modal` is shown
Generally we are performing Internet connection checks, but this case was missed

### Steps to Reproduce 
DeviceA : iPhone SE
DeviceB: Ubuntu 18.04 LTS

1. Clean install on DeviceA and DeviceB
1. Establish sync chain between DeviceA and DeviceB
1. DeviceA: Open Sync Settings
1. DeviceA: Tap on  DeviceA (note: it has `This Device` in the name)
1. Tap `Remove Device` -> `Delete sync chain modal` is shown
1. Go offline
1. Tap Remove on `Delete sync chain modal`

**Actual result:** 
Internet connection check is not preformed

**Expected result:**
Internet connection check is preformed

IMG_0048

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.21 (20.10.27.20), iPhone SE (iOS 12.4)

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

### LINKED ISSUE #2998: Favicons are not synced
### Steps to Reproduce 
DeviceA: Ubuntu 18.04 LTS
DeviceB : iPhone SE

1. Clean install on DeviceA and DeviceB
1. Establish sync chain between DeviceA and DeviceB
1. DeviceA: Open interia.pl and bookmark it
1. Wait till the bookmark is synced to DeviceB
1. Check favicon on DeviceB

Note: Issue also reproduces when devices are switched

**Actual result:** 
Favicon is not synced
IMG_0049

**Expected result:**
Favicon is synced
IMG_0050

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.21 (20.10.27.20), iPhone SE (iOS 12.4)

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

### LINKED ISSUE #3004: unable to import bookmarks on iPad if bookmark file is not named Bookmarks.html
### Description: 
Tried importing bookmarks file on iPad w/ iOS13 and bookmarks were not imported. No error message or visible reason as to why.

### Steps to Reproduce 

1. Install 1.20 from Dev TF
1. Setup bookmarks/folders/subfolders
1. Upgrade to latest 1.21 on Dev TF
1. Wait at least 1 minute
1. View the Files on my iPad (under Brave Dev there was a Bookmarks file that I guess the upgrade creates automatically?) --> sent this file to my laptop to have a copy (rename from Bookmarks.html to something else like `Bookmarks-created on upgrade - Step 5.html`)
1. Check 1.21 to confirm bookmarks are visible as expected :white_check_mark: 
1. Export bookmarks to Files (just wanted to compare this to the one created on upgrade) --> sent this file to my laptop to have a copy (Rename from Bookmarks.html to something else like `Bookmarks-manually exported after upgrade - Step 7.html`)
1. Deleted 1.21
1. Clean install 1.21
1. Sent renamed bookmarks from step 5 to iPad
1. Tried to import this file --> bookmarks not imported

**Actual result:** 
Unable to import file from step 5 or 7, no indication of why on screen

**Expected result:**
bookmarks imported

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% on my device w/ above steps

**Brave Version:** 
1.21 (20.10.30.21)

**Device details:** 
iPad iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #3005: order of bookmarks in files are slightly different
### Description: 
When testing case from https://github.com/brave/brave-ios/issues/3004, I noticed that the bookmark files from steps 5 and 7 are slightly different. Maybe this isn't an issue, but I am not sure.

### Steps to Reproduce 

1. Install 1.20 from Dev TF
1. Setup bookmarks/folders/subfolders
1. Upgrade to latest 1.21 on Dev TF
1. Wait at least 1 minute
1. View the Files on my iPad (under Brave Dev there was a Bookmarks file that I guess the upgrade creates automatically?) --> sent this file to my laptop to have a copy
1. Check 1.21 to confirm bookmarks are visible as expected :white_check_mark: 
1. Export bookmarks to Files (just wanted to compare this to the one created on upgrade) --> sent this file to my laptop to have a copy

**Actual result:** 
Compare files from steps 5 and 7, ignoring different values for fields like `ADD_DATE` and `LAST_MODIFIED`, one of the bookmarks is in a different place in the file. See below boxes:
Screen Shot 2020-11-02 at 8 57 23 AM

**Expected result:**
Expected order of bookmarks and files to be the same in both files

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.21 (20.10.30.21)

**Device details:** 
iPad iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #3006: bookmark order is different after upgrade
### Description: 
After upgrading from 1.20 to 1.21, @srirambv and I noticed that the order of some bookmark/folders in the UI can be different.

### Steps to Reproduce 

1. Have this file:
[ios copy.txt](https://github.com/brave/brave-ios/files/5475898/ios.copy.txt)
2. Rename to .html
3. Import on desktop version 
4. Using 1.20 on iOS, mimic this setup (order, folders, bookmarks, etc)
5.  Note how the "Sports" folder looks:

```
Sports (folder)
   espncricinfo.com (site)
   Cricket (folder)
   Sports (folder)
```

6. Upgrade to 1.21
7. Wait a minute 
8. Look at "Sports" folder now

```
Sports (folder)
   Cricket (folder)
   espncricinfo.com (site)
   Sports (folder)
```

**Actual result:** 
order is different
IMG_0090

**Expected result:**
order to be the same
IMG_0091

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.21 (20.10.30.21)

**Device details:** 
iPad iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #3011: [Sync v2] - Follow up of #2996 Crash when moving bookmark to just deleted folder
### Description: 
[Sync v2] - Follow up of #2996 Crash when moving bookmark to just deleted folder

### Steps to Reproduce 
DeviceA : iPhone 8
DeviceB: Windows 10 x64

1. Clean install on DeviceA and DeviceB
2. Establish sync chain between DeviceA and DeviceB
3. DeviceA: Add bookmark folder FA1
4. DeviceA: Add bookmark A1
5. Wait for sync update
6. DeviceB: Delete FA1 and at the same time on DeviceA: Move A1 to FA1
7. Wait for sync update

**Actual result:** 
Crash

Please find the recorded file for reference
https://drive.google.com/file/d/1m5aRUydiZuHh5CuWpDBI1_7D2djWpWNR/view

**Expected result:**
No Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always
**Brave Version:** 

1.21(20.11.02.20)
**Device details:** 

iPhone 8 - iOS 13.3.1
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

### LINKED ISSUE #3016: Browser crash when visiting a reddit page
### Description: 
Browser crash when visiting a reddit page

### Steps to Reproduce 
  1. Install latest dev build and set wallet to staging
  2. Visit http://reddit.com/u/beachbum0407
  3. Browser crash
  4. Try visiting another reddit user page no crash

**Actual result:** 
Browser crash

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.11.6.13)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Note: Crash happens only on staging and not on production wallet. @LaurenWags  and @GeetaSarvadnya  also reproduced the crash

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Adds Importing/Exporting of Bookmarks to .html file so that bookmarks can be imported from Desktop or exported to Desktop.
- Adds Syncing so that Bookmarks & Folders can be synced with Desktop.
- Migrates CoreData bookmarks to Desktop/BraveCore bookmarks.
- If Migration fails, a WebPage/tab opens up with the Bookmarks.html being displayed with minor styling.
- Add BraveCore interface to iOS to choose which SyncServiceURL to use as the sync endpoint.
- Integrate BraveCore bookmarks into iOS UI.

This pull request fixes #2946, #2996, #3006, #3005, #2998, #3004, #2997, #3011, #3016 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Application/ClientPreferences.swift [hunk 1]
```diff
@@ -154,6 +154,11 @@ extension Preferences {
             Option<Bool>(key: "vpn.vpn-header-dismissed", default: false)
     }
     
+    final class Chromium {
+        static let migrationBookmarks = Option<Bool>(key: "chromium.migration.bookmarks", default: true)
```
Comment (iccub) [inline Client/Application/ClientPreferences.swift]: can you rename it to something like `syncV2MigrationCompleted`

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -666,6 +666,72 @@ class BrowserViewController: UIViewController {
         
         vpnProductInfo.load()
         BraveVPN.initialize()
+        
+        if !Preferences.Chromium.migrationBookmarks.value {
+            //TODO: Show a loading screen and block the user?
+            self.migrateToChromiumBookmarks { shouldShowError in
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: `[weak self]` not needed here?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -666,6 +666,72 @@ class BrowserViewController: UIViewController {
...
+                if shouldShowError {
+                    DispatchQueue.main.async {
+                        let alert = UIAlertController(title: Strings.syncV2MigrationErrorTitle,
+                                                      message: Strings.syncV2MigrationErrorMessage,
+                                                      preferredStyle: .alert)
+                        alert.addAction(UIAlertAction(title: Strings.OKString, style: .default, handler: nil))
+                        self.present(alert, animated: true, completion: nil)
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: `completion` can be removed, it's nil by default

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 4]
```diff
@@ -451,4 +451,16 @@ extension AddEditBookmarkTableViewController: NSFetchedResultsControllerDelegate
         // Watching for CoreData save notification could be an alternative to using a frc delegate.
         reloadData()
     }
+    
+    func controllerWillChangeContent(_ controller: BookmarksV2FetchResultsController) {
+        print("WILL CHANGE CONTENT")
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift]: remove print if not needed

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 5]
```diff
@@ -451,4 +451,16 @@ extension AddEditBookmarkTableViewController: NSFetchedResultsControllerDelegate
...
+    }
+    
+    func controllerDidChangeContent(_ controller: BookmarksV2FetchResultsController) {
+        print("DID CHANGE CONTENT")
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift]: remove print if not needed

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 6]
```diff
@@ -451,4 +451,16 @@ extension AddEditBookmarkTableViewController: NSFetchedResultsControllerDelegate
...
+    }
+    
+    func noIdeaReloadTable(_ controller: BookmarksV2FetchResultsController) {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift]: rename this method

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift [hunk 7]
```diff
@@ -197,7 +233,7 @@ class BookmarksViewController: SiteTableViewController, ToolbarUrlActionsProtoco
     }
     
     guard let item = bookmarksFRC?.object(at: indexPath) else { return }
-    cell.tag = item.objectID.hashValue
+    cell.tag = item.objectID //.hashValue
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: this comment still needed?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift [hunk 8]
```diff
@@ -435,5 +473,82 @@ extension BookmarksViewController: NSFetchedResultsControllerDelegate {
         break
     }
   }
+  
+  func noIdeaReloadTable(_ controller: BookmarksV2FetchResultsController) {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: function name

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift [hunk 9]
```diff
@@ -435,5 +473,82 @@ extension BookmarksViewController: NSFetchedResultsControllerDelegate {
...
 
+extension BookmarksViewController {
+    func importBookmarks(from url: URL) {
+        guard let importURL = URL(string: url.relativePath) else {
+            log.error("Invalid Bookmarks Import File URL")
+            return
+        }
+        
+        self.importExportUtility.importBookmarks(from: importURL) { success in
+            let alert = UIAlertController(title: "Bookmarks",
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: move to `BraveStrings`

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift [hunk 10]
```diff
@@ -435,5 +473,82 @@ extension BookmarksViewController: NSFetchedResultsControllerDelegate {
...
+                                          message: success ? "Bookmarks Imported Successfully" : "Bookmarks Import Failed",
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: Move to `BraveStrings`

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift [hunk 11]
```diff
@@ -435,5 +473,82 @@ extension BookmarksViewController: NSFetchedResultsControllerDelegate {
...
+                                          preferredStyle: .alert)
+            alert.addAction(UIAlertAction(title: "Okay", style: .default, handler: nil))
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: Use `Strings.OKString`

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 12]
```diff
@@ -0,0 +1,316 @@
...
+            return bookmarkNode?.dateAdded
+        }
+        
+        set {
+            bookmarkNode?.dateAdded = newValue ?? Date()
+        }
+    }
+    
+    public var parent: Bookmarkv2? {
+        get {
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: `get` can be removed

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 13]
```diff
@@ -0,0 +1,316 @@
...
+        return bookmarkNode?.isPermanentNode == false
+    }
+    
+    public var objectID: Int {
+        return Int(bookmarkNode?.nodeId ?? 0)
+    }
+    
+    public var order: Int16 {
+        let children = bookmarkNode?.parent?.children
+        return Int16(children?.firstIndex(where: { $0.guid == self.bookmarkNode?.guid }) ?? -1)
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: what is going to happen if order is `-1` is such bookmark going at the top of the list?

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 14]
```diff
@@ -0,0 +1,316 @@
...
+    public class func add(url: URL, title: String?, parentFolder: Bookmarkv2? = nil) {
+        if let parentFolder = parentFolder?.bookmarkNode {
+            Bookmarkv2.bookmarksAPI.createBookmark(withParent: parentFolder, title: title ?? "", with: url)
+        } else {
+            Bookmarkv2.bookmarksAPI.createBookmark(withTitle: title ?? "", url: url)
+        }
+    }
+    
+    public func existsInPersistentStore() -> Bool {
+        return true //Need a way to tell if a folder already exists in the sync chain..
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: is this still valid?

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 15]
```diff
@@ -0,0 +1,316 @@
...
+    
+    func controllerDidChangeContent(_ controller: BookmarksV2FetchResultsController)
+    
+    func controller(_ controller: BookmarksV2FetchResultsController, didChange anObject: Any, at indexPath: IndexPath?, for type: NSFetchedResultsChangeType, newIndexPath: IndexPath?)
+    
+    func noIdeaReloadTable(_ controller: BookmarksV2FetchResultsController)
+}
+
+protocol BookmarksV2FetchResultsController {
+    /* weak */ var delegate: BookmarksV2FetchResultsDelegate? { get set }
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: does it have to be weak?

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift [hunk 16]
```diff
@@ -0,0 +1,475 @@
...
+                if bookmark.inToolbar && parent == nil && folderName == bookmark.path?.first {
+                    //If we're importing directly to the bookmarks bar, skip over the
+                    // folder named "Bookmarks Toolbar" (or any non-Firefox equivalent).
+                    continue
+                }
+                
+                let index = parent?.children?.first(where: { $0.isFolder && $0.customTitle == folderName })
+                if index == nil {
+                    Bookmark.addFolder(title: folderName, parentFolder: parent, context: .existing(context))
+                    //try context.save()
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: remove

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift [hunk 17]
```diff
@@ -0,0 +1,475 @@
...
+                    parent = parent?.children?.filter({ $0.isFolder && $0.customTitle == folderName }).first
+                } else {
+                    parent = index
+                }
+            }
+            
+            foldersAddedTo.insert(parent)
+            if bookmark.isFolder {
+                Bookmark.addFolder(title: bookmark.title, parentFolder: parent, context: .existing(context))
+                //try context.save()
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: remove this and other commented out context saves

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift [hunk 18]
```diff
@@ -0,0 +1,475 @@
...
+            }
+        }
+    }
+}
+
+extension BraveCoreDataImportExportUtility {
+    private func convertToChromiumFormat(_ bookmark: Bookmark) -> BraveExportedBookmark {
+        // Tail recursion to map children..
+        return BraveExportedBookmark(title: bookmark.isFolder ? bookmark.customTitle ?? "(No Title)" : bookmark.title ?? "(No Title)", id: Int64(bookmark.order), guid: UUID().uuidString.lowercased(), url: URL(string: bookmark.url ?? ""), dateAdded: bookmark.created ?? Date(), dateModified: bookmark.lastVisited ?? Date(), children: bookmark.children?.map({ convertToChromiumFormat($0) }))
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: `No Title` strings should be most likely moved to BraveStrings to translate it, unless we want to have it in english for all languages.
Also break this line, it's too long

File: Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift [hunk 19]
```diff
@@ -0,0 +1,209 @@
...
+
+class BraveCoreImportExportUtility {
+    
+    // Import an array of bookmarks into BraveCore
+    func importBookmarks(from array: [BraveImportedBookmark], _ completion: @escaping (_ success: Bool) -> Void) {
+        precondition(state == .none, "Bookmarks Import - Error Importing while an Import/Export operation is in progress")
+        
+        state = .importing
+        self.queue.async {
+            self.importer.import(from: array, topLevelFolderName: Strings.syncImportFolderName) { state in
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreImportExportUtility.swift]: add weak self

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 20]
```diff
@@ -0,0 +1,245 @@
...
+private let log = Logger.browserLogger
+
+class BraveCoreMigrator {
+    
+    private let dataImportExporter = BraveCoreImportExportUtility()
+    private let bookmarksAPI = BraveBookmarksAPI()
+    private var observer: BookmarkModelListener?
+    
+    public init() {
+        /*var didFinishTest = false
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: is this still needed?

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 21]
```diff
@@ -0,0 +1,245 @@
...
+        }
+    }
+    
+    private func exportBookmarks(_ completion: @escaping (_ success: Bool) -> Void) {
+        let paths = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)
+        guard let documentsDirectory = paths.first else {
+            return completion(false)
+        }
+        
+        guard let url = URL(string: "\(documentsDirectory)/Bookmarks.html") else {
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: I saw this url in few places, what about extracting it to a constant somewhere? to guarantee each call uses the same url

File: Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift [hunk 22]
```diff
@@ -0,0 +1,39 @@
...
+        if let codeWords = UserDefaults.standard.object(forKey: BraveSyncAPI.isInGroupKey) as? Bool {
+            return codeWords
+        }
+        return false
+    }
+    
+    @discardableResult
+    func joinSyncGroup(codeWords: String) -> Bool {
+        if self.setSyncCode(codeWords) {
+            UserDefaults.standard.setValue(true, forKey: BraveSyncAPI.isInGroupKey)
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift]: Why not using our `Preferences` implementation, instead of UserDefaults?

File: Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift [hunk 23]
```diff
@@ -0,0 +1,39 @@
+// Copyright 2020 The Brave Authors. All rights reserved.
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+import BraveRewards
+import SwiftKeychainWrapper
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift]: this import is not needed

File: Client/Frontend/Sync/SyncPairCameraViewController.swift [hunk 24]
```diff
@@ -47,34 +48,33 @@ class SyncPairCameraViewController: SyncViewController {
...
+            // Forced timeout
+            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + Double(Int64(25.0) * Int64(NSEC_PER_SEC)) / Double(NSEC_PER_SEC), execute: {
+                Scanner.lock = false
+                self.cameraView.cameraOverlayError()
+            })
+            
+            // If multiple calls get in here due to race conditions it isn't a big deal
+            
+            let codeWords = BraveSyncAPI.shared.syncCode(fromHexSeed: data)
+            if !codeWords.isEmpty {
```
Comment (iccub) [inline Client/Frontend/Sync/SyncPairCameraViewController.swift]: reverse this if condition to be remove negation

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 25]
```diff
@@ -30,15 +47,16 @@ class SyncSettingsTableViewController: UITableViewController {
...
-            try frc?.performFetch()
-        } catch {
-            log.error("frc fetch error: \(error)")
+        syncDeviceObserver = BraveSyncDeviceObserver { [weak self] in
+            self?.updateDeviceList()
         }
         
+        let codeWords = BraveSyncAPI.shared.getSyncCode()
+        BraveSyncAPI.shared.joinSyncGroup(codeWords: codeWords)
+        BraveSyncAPI.shared.syncEnabled = true
```
Comment (iccub) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift:38]: why do we join and turn on sync here?

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 26]
```diff
@@ -107,8 +125,9 @@ class SyncSettingsTableViewController: UITableViewController {
             return
         }
         
-        guard let frc = frc, let deviceCount = frc.fetchedObjects?.count else { return }
-        let device = frc.object(at: indexPath)
+        let devices = self.devices
+        guard !devices.isEmpty else { return }
```
Comment (iccub) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: convert to if `if devices.empty { return }`

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 27]
```diff
@@ -107,8 +125,9 @@ class SyncSettingsTableViewController: UITableViewController {
...
+        let device = devices[indexPath.row]
```
Comment (iccub) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: for safety, you can use safe subscript here to make sure the device exist at given index path
`devices[safe: indexPath.row]`

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 28]
```diff
@@ -203,14 +222,14 @@ class SyncSettingsTableViewController: UITableViewController {
     }
     
     private func configureCell(_ cell: UITableViewCell, atIndexPath indexPath: IndexPath) {
-        guard let frc = frc else {
-            log.error("FetchedResultsController is nil.")
+        guard !devices.isEmpty else {
```
Comment (iccub) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: convert to `if devices.isEmpty { return }`

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 29]
```diff
@@ -203,14 +222,14 @@ class SyncSettingsTableViewController: UITableViewController {
...
+            log.error("No sync devices to configure.")
             return
         }
         
         switch indexPath.section {
         case Sections.deviceList.rawValue:
-            let device = frc.object(at: indexPath)
+            let device = devices[indexPath.row]
```
Comment (iccub) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: use `safe` subscript

File: Client/Frontend/Sync/SyncWelcomeViewController.swift [hunk 30]
```diff
@@ -131,80 +168,123 @@ class SyncWelcomeViewController: SyncViewController {
...
-            Sync.shared.initializeNewSyncGroup(deviceName: UIDevice.current.name)
+            self.navigationController?.pushViewController(pairCamera, animated: true)
         }
-
-        navigationController?.pushViewController(addDevice, animated: true)
     }
     
-    @objc func existingUserAction() {
-        let pairCamera = SyncPairCameraViewController()
+    private func migrationCheck(completion: @escaping (() -> Void)) {
```
Comment (iccub) [inline Client/Frontend/Sync/SyncWelcomeViewController.swift]: remove this migration check, not used anymore, added by me

File: Client/Frontend/Sync/SyncWelcomeViewController.swift [hunk 31]
```diff
@@ -12,7 +13,43 @@ protocol NavigationPrevention {
 }
 
 class SyncWelcomeViewController: SyncViewController {
-    var dismissHandler: (() -> Void)?
+    private var overlayView: UIView?
+    
+    private var isLoading: Bool = false {
```
Comment (iccub) [inline Client/Frontend/Sync/SyncWelcomeViewController.swift:18]: remove this overlay code, not used anymore, added by me

**Review by iccub — CHANGES_REQUESTED** [review]
first look changes

File: Client/Application/Delegates/AppDelegate.swift [hunk 32]
```diff
@@ -64,6 +66,11 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
         self.window = UIWindow(frame: UIScreen.main.bounds)
         self.window!.backgroundColor = .black
         
+        //Brave Core Initialization
+        self.braveCore = BraveCoreMain()
+        self.braveCore?.setUserAgent(UserAgent.mobile)
```
Comment (diracdeltas) [inline Client/Application/Delegates/AppDelegate.swift:71]: FYI the latest iOS safari user agent contains `14_0_1` not `14_0` https://github.com/brave/brave-ios/blob/ba8686d7436cf305693cdce32a3bfe58147a7fa0/Shared/UserAgentBuilder.swift#L99

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift [hunk 33]
```diff
@@ -0,0 +1,475 @@
...
+                
+                //URL
+                try file.write(bookmark.url?.escapeAsHTMLQuotes() ?? "")
+                
+                //Created Date
+                try file.write("\(Int(bookmark.created?.timeIntervalSince1970 ?? Date().timeIntervalSince1970))")
+                
+                //ICON (OPTIONAL) - 16x16 PNG
+                if let iconUrl = bookmark.domain?.favicon?.url,
+                   let url = URL(string: iconUrl),
```
Comment (diracdeltas) [inline Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: if i understand correctly, this fetches all the bookmark favicons on import. i think this is somewhat of a privacy issue for first-time syncs because anyone on the network can see what domains you've bookmarked (because these requests occur so close together). @darkdh do you know if chromium has this issue?

after a favicon is written to disk, do we always display it from disk?

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift [hunk 34]
```diff
@@ -0,0 +1,475 @@
...
+        "<META HTTP-EQUIV=\"Content-Type\"" +
+        " CONTENT=\"text/html; charset=UTF-8\">\r\n" +
+        "<TITLE>Bookmarks</TITLE>\r\n" +
+        "<H1>Bookmarks</H1>\r\n" +
+        "<DL><p>\r\n"
+
+    // Newline separator.
+    private static let kNewline = "\r\n"
+
+    private struct BookmarkWriter {
```
Comment (diracdeltas) [inline Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: is there an XSS risk here? for instance if someone's bookmark title is `\"</a><script>alert(1)</script>`

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift [hunk 35]
```diff
@@ -0,0 +1,475 @@
...
+        static let kAddDate = "\" ADD_DATE=\""
+        // After kAddDate.
+        static let kIcon = "\" ICON=\""
+        // After kIcon.
+        static let kBookmarkAttributeEnd = "\">"
+        // End of a bookmark.
+        static let kBookmarkEnd = "</A>"
+    }
+    
+    private struct FolderWriter {
```
Comment (diracdeltas) [inline Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: same as above

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift (hunk 34 above)
Comment (diracdeltas) [reply Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: i guess not because all the external input here is HTML-escaped

Comment (diracdeltas) [reply Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: just to be paranoid, i think we should HTML escape every injected field including date and icon.

File: Client/Frontend/Sync/WebFilter/Bookmarks.html [hunk 36]
```diff
@@ -0,0 +1,99 @@
+<!--
+Copyright (c) 2020 The Brave Authors. All rights reserved.
+This Source Code Form is subject to the terms of the Mozilla Public
+License, v. 2.0. If a copy of the MPL was not distributed with this file,
+You can obtain one at https://mozilla.org/MPL/2.0/.
+-->
+
+<head>
+    <meta name='viewport' content='initial-scale=1, viewport-fit=cover'>
```
Comment (diracdeltas) [inline Client/Frontend/Sync/WebFilter/Bookmarks.html:10]: if this supports content security policy, we should add one like `<meta http-equiv="Content-Security-Policy" content="default-src 'self'">` (only allow resources loaded from the same origin as this file, disable eval and inline scripts)

note that this can also be done using a HTTP response header: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift (hunk 33 above)
Comment (darkdh) [reply Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: Chromium usually get it from `ICON` attribute which is basically a data url and will be used by 
https://source.chromium.org/chromium/chromium/src/+/master:chrome/utility/importer/bookmark_html_reader.cc;l=221-224;drc=929e790ad17a54008b3dac86cbe30751c968c2ce

Comment (diracdeltas) [reply Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: ah, if these are data URLs then this isn't a problem

Comment (Brandon-T) [reply Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: @diracdeltas this file isn't used anymore. Nothing in this file is used. It will be completely removed. We only use `BraveCoreImportExportUtility.swift`, not `BraveCoreDataImportExportUtility.swift`. Sorry for this confusion :( I forgot to remove it.

File: Client/Frontend/Sync/WebFilter/Bookmarks.html (hunk 36 above)
Comment (Brandon-T) [reply Client/Frontend/Sync/WebFilter/Bookmarks.html:10]: Fixed. Though, this HTML is completely local (localhost) and can't be accessed from any domain except 127.0.0.1 :)

File: BraveShared/BraveStrings.swift [hunk 37]
```diff
@@ -382,7 +382,7 @@ extension Strings {
     public static let enterCodeWords = NSLocalizedString("EnterCodeWords", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Enter code words", comment: "Sync enter code words")
     public static let showCodeWords = NSLocalizedString("ShowCodeWords", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Show code words instead", comment: "Show code words instead")
     public static let syncDevices = NSLocalizedString("SyncDevices", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Devices & Settings", comment: "Sync you browser settings across devices.")
-    public static let devices = NSLocalizedString("Devices", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Devices on chain", comment: "Sync device settings page title.")
+    public static let devices = NSLocalizedString("Devices", tableName: "BraveShared", bundle: Bundle.braveShared, value: "DEVICES ON SYNC CHAIN", comment: "Sync device settings page title.")
```
Comment (iccub) [inline BraveShared/BraveStrings.swift]: Leave it lower cased, the upper case is auto generated by the table's section header

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 38]
```diff
@@ -666,6 +666,72 @@ class BrowserViewController: UIViewController {
         
         vpnProductInfo.load()
         BraveVPN.initialize()
+        
+        if !Preferences.Chromium.syncV2BookmarksMigrationCompleted.value {
+            //TODO: Show a loading screen and block the user?
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: remove this `TODO:`, i do not think it's needed anymore

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 39]
```diff
@@ -666,6 +666,72 @@ class BrowserViewController: UIViewController {
...
+        }
+    }
+    
+    private func migrateToChromiumBookmarks(_ completion: @escaping (_ showError: Bool) -> Void) {
+        Migration.braveCoreBookmarksMigrator?.migrate({ success in
+            if success {
+                let paths = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)
+                guard let documentsDirectory = paths.first else {
+                    log.error("Unable to access documents directory")
+                    completion(true)
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: what do you think about renaming it to `completionWithError(true)`?
Now it's a bit hard to read, you see `true` you expect it to be success while it is actually a failure

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 40]
```diff
@@ -666,6 +666,72 @@ class BrowserViewController: UIViewController {
...
+                
+                guard let url = URL(string: "\(documentsDirectory)/Bookmarks_\(dateString).html") else {
+                    log.error("Unable to access Bookmarks_\(dateString).html")
+                    completion(true)
+                    return
+                }
+                
+                Migration.braveCoreBookmarksMigrator?.exportBookmarks(to: url) { success in
+                    if success {
+                        if !BookmarksInterstitialPageHandler.showBookmarksPage(tabManager: self.tabManager, url: url) {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: why do we call this if the export bookmarks method is successful?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 41]
```diff
@@ -666,6 +666,72 @@ class BrowserViewController: UIViewController {
...
+                            log.error("Unable to open the users bookmarks.html in a new tab")
+                            completion(true)
+                            return
+                        }
+                        completion(false)
+                    } else {
+                        guard let url = URL(string: "\(documentsDirectory)/Bookmarks.html") else {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: Commented about it in other place, export it to a helper method, I believe we can export the whole url together with documents directory path

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 42]
```diff
@@ -71,14 +71,14 @@ class AddEditBookmarkTableViewController: UITableViewController {
     /// Returns a count of how many non-folder cells should be visible(depends on Mode state)
     private var specialButtonsCount: Int {
         switch mode {
-        case .addFolder(_), .editFolder(_): return 1
-        case .addBookmark(_, _), .editBookmark(_), .editFavorite(_): return 3
+        case .addFolder(_), .editFolder(_): return 0
+        case .addBookmark(_, _), .editBookmark(_), .editFavorite(_): return 2
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift:76]: we decrement the button count because the general `bookmarks` cell is not used, correct?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 43]
```diff
@@ -112,21 +112,24 @@ class AddEditBookmarkTableViewController: UITableViewController {
...
     init(mode: BookmarkEditMode) {
         self.mode = mode
         
         saveLocation = mode.initialSaveLocation
         presentationMode = .currentSelection
-        frc = Bookmark.foldersFrc(excludedFolder: mode.folder)
-        
+        frc = Bookmarkv2.foldersFrc(excludedFolder: mode.folder)
+        rootFolderName = Bookmarkv2.mobileNode()?.displayTitle ?? Strings.bookmarkRootLevelCellTitle
+        rootFolderId = Bookmarkv2.mobileNode()?.objectID ?? 0
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift]: We should move this magic number `0` to a constant, it stands for root level object id or something right?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 44]
```diff
@@ -178,23 +181,23 @@ class AddEditBookmarkTableViewController: UITableViewController {
...
     /// Main data source
     private var sortedFolders = [IndentedFolder]()
     
     /// Sorts folders by their older and nesting level.
     /// Indentation level starts with 0, but level 0 is designed for special folders
     /// (root level bookamrks, favorites).
-    private func sortFolders(parentID: NSManagedObjectID? = nil,
-                             indentationLevel: Int = 1) -> [IndentedFolder] {
+    private func sortFolders(parentID: Int? = nil,
+                             indentationLevel: Int = 0) -> [IndentedFolder] {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift]: same as previous comment, extract it to a constant, 0 alone does not tell us too much

**Review by iccub — CHANGES_REQUESTED** [review]
second round, please address my remaining previous comments too

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 45]
```diff
@@ -0,0 +1,370 @@
...
+    public var customTitle: String? {
+        return self.title
+    }
+    
+    public var displayTitle: String? {
+        return self.customTitle
+    }
+    
+    public var url: String? {
+        return bookmarkNode?.titleUrlNodeUrl?.absoluteString
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: `return` can be removed if there is a one line getter, same for other properties

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 46]
```diff
@@ -0,0 +1,370 @@
...
+    public static func frc(parent: Bookmarkv2?) -> BookmarksV2FetchResultsController? {
+        return Bookmarkv2Fetcher(parent?.bookmarkNode, api: Bookmarkv2.bookmarksAPI)
+    }
+    
+    public static func foldersFrc(excludedFolder: Bookmarkv2? = nil) -> BookmarksV2FetchResultsController {
+        return Bookmarkv2ExclusiveFetcher(excludedFolder?.bookmarkNode, api: Bookmarkv2.bookmarksAPI)
+    }
+    
+    public static func getChildren(forFolder folder: Bookmarkv2, includeFolders: Bool) -> [Bookmarkv2]? {
+        return folder.bookmarkNode?.children.filter({ $0.isFolder == includeFolders }).map({ Bookmarkv2($0) })
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: This seems wrong, if `includeFolders` is true, this will return only folders, when it should return bookmarks and folders

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 47]
```diff
@@ -0,0 +1,370 @@
...
+        if let url = url {
+            bookmarkNode?.url = URL(string: url)
+        } else {
+            bookmarkNode?.url = nil
+        }
+    }
+    
+    public class func reorderBookmarks(frc: BookmarksV2FetchResultsController?, sourceIndexPath: IndexPath,
+                                       destinationIndexPath: IndexPath,
+                                       isInteractiveDragReorder: Bool = false) {
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: `isInteractiveDragReorder` is never used

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 48]
```diff
@@ -0,0 +1,370 @@
...
+}
+
+protocol BookmarksV2FetchResultsDelegate: class {
+    func controllerWillChangeContent(_ controller: BookmarksV2FetchResultsController)
+    
+    func controllerDidChangeContent(_ controller: BookmarksV2FetchResultsController)
+    
+    func controller(_ controller: BookmarksV2FetchResultsController, didChange anObject: Any, at indexPath: IndexPath?, for type: NSFetchedResultsChangeType, newIndexPath: IndexPath?)
+    
+    func noIdeaReloadTable(_ controller: BookmarksV2FetchResultsController)
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: rename

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 49]
```diff
@@ -0,0 +1,370 @@
...
+            if self.children.isEmpty {
+                throw NSError(domain: "brave.core.migrator", code: -1, userInfo: [
+                    NSLocalizedFailureReasonErrorKey: "Invalid Bookmark Nodes"
+                ])
+            }
+        }
+    }
+    
+    func object(at indexPath: IndexPath) -> Bookmarkv2? {
+        return Bookmarkv2(children[indexPath.row])
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: Add this for index out of bounds safety
`guard let children = children[safe: indexPath.row] else { return nil }`

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 50]
```diff
@@ -0,0 +1,370 @@
...
+            self.delegate?.noIdeaReloadTable(self)
+        })
+    }
+    
+    var fetchedObjects: [Bookmarkv2]? {
+        return children.map({ Bookmarkv2($0) })
+    }
+    
+    func performFetch() throws {
+        self.children = []
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: self not needed here in this method

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift [hunk 51]
```diff
@@ -0,0 +1,370 @@
...
+            self.delegate?.noIdeaReloadTable(self)
+        })
+    }
+    
+    var fetchedObjects: [Bookmarkv2]? {
+        return children.map({ Bookmarkv2($0) })
+    }
+    
+    func performFetch() throws {
+        self.children.removeAll()
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: self not needed here in this method

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 52]
```diff
@@ -0,0 +1,245 @@
...
+        }
+        
+        func bookmarkModelLoaded() {
+            self.onModelLoaded()
+        }
+    }
+}
+
+extension BraveCoreMigrator {
+    private func testMigration(_ completion: @escaping () -> Void) {
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift:279]: can be removed now

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 53]
```diff
@@ -5,21 +5,38 @@ import CoreData
 import Shared
 import Data
 import BraveShared
+import BraveRewards
 
 private let log = Logger.browserLogger
 
+struct BraveSyncDevice: Codable {
```
Comment (iccub) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: can be `private`

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 54]
```diff
@@ -5,21 +5,38 @@ import CoreData
...
+    
+    func remove() {
+        BraveSyncAPI.shared.removeDeviceFromSyncGroup(deviceGuid: self.guid)
+    }
+}
+
 class SyncSettingsTableViewController: UITableViewController {
-    private var frc: NSFetchedResultsController<Device>?
+    private var syncDeviceObserver: BraveSyncDeviceObserver?
+    private var syncStateObserver: BraveSyncServiceObserver?
```
Comment (iccub) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: this is not used, can be removed

File: Client/Frontend/Sync/SyncWelcomeViewController.swift [hunk 55]
```diff
@@ -131,80 +168,123 @@ class SyncWelcomeViewController: SyncViewController {
...
-            self?.dismiss(animated: true)
-            sync.leaveSyncGroup()
+        syncServiceObserver = BraveSyncServiceObserver { [weak self] in
+            guard let self = self else { return }
+            print("SYNC SERVICE STATUS - In Sync Group: \(BraveSyncAPI.shared.isInSyncGroup)")
             
-            let bvc = (UIApplication.shared.delegate as? AppDelegate)?.browserViewController
-            
-            bvc?.present(SyncAlerts.initializationError, animated: true)
+            //bvc?.present(SyncAlerts.initializationError, animated: true)
```
Comment (iccub) [inline Client/Frontend/Sync/SyncWelcomeViewController.swift]: remove this comment

File: Client/Frontend/Sync/SyncWelcomeViewController.swift [hunk 56]
```diff
@@ -131,80 +168,123 @@ class SyncWelcomeViewController: SyncViewController {
     /// Sync setup failure is handled here because it can happen from few places in children VCs(new chain, qr code, codewords)
     /// This makes all presented Sync View Controllers to dismiss, cleans up any sync setup and shows user a friendly message.
     private func handleSyncSetupFailure() {
-        let sync = Sync.shared
-        sync.syncSetupFailureCallback = { [weak self] in
-            self?.dismiss(animated: true)
-            sync.leaveSyncGroup()
+        syncServiceObserver = BraveSyncServiceObserver { [weak self] in
+            guard let self = self else { return }
+            print("SYNC SERVICE STATUS - In Sync Group: \(BraveSyncAPI.shared.isInSyncGroup)")
```
Comment (iccub) [inline Client/Frontend/Sync/SyncWelcomeViewController.swift]: remove this print or replace with logger

**Review by iccub — CHANGES_REQUESTED** [review]
third round

File: BraveShared/BraveStrings.swift [hunk 57]
```diff
@@ -399,14 +399,15 @@ extension Strings {
     public static let syncChooseDeviceHeader = NSLocalizedString("SyncChooseDeviceHeader", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Choose the type of device you would like to sync to.", comment: "Header for device choosing screen.")
     public static let syncRemoveThisDeviceQuestionDesc = NSLocalizedString("SyncRemoveThisDeviceQuestionDesc", tableName: "BraveShared", bundle: Bundle.braveShared, value: "This device will be disconnected from sync group and no longer receive or send sync data. All existing data will remain on device.", comment: "Sync remove device?")
     public static let pair = NSLocalizedString("Pair", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Pair", comment: "Sync pair device settings section title")
-    public static let syncAddAnotherDevice = NSLocalizedString("SyncAddAnotherDevice", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Add another device", comment: "Add another device cell button.")
+    public static let syncAddAnotherDevice = NSLocalizedString("SyncAddAnotherDevice", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Add New Device", comment: "Add New Device cell button.")
```
Comment (jamesmudgett) [inline BraveShared/BraveStrings.swift:402]: Should be "Add New Device"

File: Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift (hunk 33 above)
Comment (diracdeltas) [reply Client/Frontend/Sync/BraveCore/BraveCoreDataImportExportUtility.swift]: ah thanks for clarifying

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift (hunk 42 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift:76]: Correct.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 39 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: Fixed.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 40 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: Fixed.

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift (hunk 13 above)
Comment (Brandon-T) [reply Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: It shouldn't be possible for this to happen ever. A bookmark on the Chromium side always has a parent.. There is only one node possible that can have no parent and that is `Root`.

It goes:

```
Root {
   MobileBookmarks,
   DesktopBookmarks,
   OtherBookmarks
}
```

Root is never exposed in this API at all so this should never be the case for iOS. I only added the `-1` there because the field is not optional.

But yes, it will move the bookmark to the top. This `order` is only used for UI and it is automatically set by the API when a bookmark is added. You can't change it unless you call `reorderBookmarks` but in that case it will still choose the order for you based on the UI.

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift (hunk 14 above)
Comment (Brandon-T) [reply Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: It is still needed. There is currently no way for me to know until it is synced. I'm trying to find a way to determine if it is even possible.

This is only a guard against one device having a folder and the other device not having that folder yet because it didn't sync over yet.

Atm, I call `reloadTable` so it doesn't have any effect. But once we switch that to be animated, we should figure out a way for this.

File: Client/Frontend/Sync/BraveCore/Bookmarkv2.swift (hunk 15 above)
Comment (Brandon-T) [reply Client/Frontend/Sync/BraveCore/Bookmarkv2.swift]: Yes it has to be weak as it is a delegate. The bookmarks controller owns the FRC and we don't want the FRC also owning the delegate (bookmarkscontroller)

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift (hunk 25 above)
Comment (Brandon-T) [reply Client/Frontend/Sync/SyncSettingsTableViewController.swift:38]: Because that's how the API works. It's the same API for both creating and joining a sync chain.
The only way to start the sync engine, is to setSyncEnabled.

You can never get to this screen unless you were already in a sync chain as per the `Preferences` anyway.

Previous SyncV1 code was using Keychain to store the words and it'd retrieve the words there to determine if the user was already in a sync chain.

In SyncV2, we use preferences and we use the BraveCoreAPI for getting the code words.

File: Client/Application/Migration.swift [hunk 58]
```diff
@@ -23,6 +25,9 @@ class Migration {
             documentsDirectoryCleanup()
             Preferences.Migration.documentsDirectoryCleanupCompleted.value = true
         }
+        
+        //`.migrate` is called in `BrowserViewController.viewDidLoad()`
+        braveCoreBookmarksMigrator = BraveCoreMigrator()
```
Comment (iccub) [inline Client/Application/Migration.swift]: do we have to initialize it if the sync migration has happened already?

File: Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift [hunk 59]
```diff
@@ -0,0 +1,36 @@
...
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+import BraveRewards
+import BraveShared
+
+extension BraveSyncAPI {
+    
+    public static let seedByteLength = 32
+    private static let isInGroupKey = "BraveSyncAPI.isInGroupKey"
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift]: This is not used

**Review by iccub — CHANGES_REQUESTED** [review]
2 more comments, rest looks good to me

File: Client/Application/Migration.swift (hunk 58 above)
Comment (Brandon-T) [reply Client/Application/Migration.swift]: There are some observers that might use it to check if it did happen or the state of it. I was planning to use it for when the user goes to the bookmarks screen, but it's ok. 
For now we don't have to allocate it. I fixed it :)

**Review by iccub — APPROVED** [review]

**Comment by iccub** [comment]
approved, good job

File: Client/Application/Delegates/AppDelegate.swift (hunk 32 above)
Comment (iccub) [reply Client/Application/Delegates/AppDelegate.swift:71]: This is done manually now, added ticket for it, i will get it done in 1.22 or later, depends on time
https://github.com/brave/brave-ios/issues/3020
