### PR TITLE
Fix #5150: Reader Mode bar stuck on page after closing tab

### LINKED ISSUE #5150: Reader Mode bar stuck on page after closing tab
### Description: 
Reader Mode bar stuck on page after closing tab. Been able to repro on Twitch.tv and youtube.com so far.

### Steps to Reproduce 
  1. Navigate to m.youtube.com
  2. Open new tab, navigate to wikipedia
  3. Click on any article and enable Reader Mode
  4. Now close current tab

**Actual result:** 
Reader Mode bar is stuck on page, refresh will clear. Also happens on desktop site

https://user-images.githubusercontent.com/17885425/159817368-08a23a38-7073-451a-a2e9-f9fc4d9a0d8a.MP4

**Expected result:**
Reader mode bar should not be shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily (youtube)

**Brave Version:** 
1.37 (22.2.23.17)

**Device details:** 
iPhone 12 Pro | iOS 15.4
iPad | iOS 15.2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
Hiding reader mode toolbar when tab is closed. This action will dismiss the bar before tab is killed so it will not stuck on other tab opened.

## Summary of Changes

This pull request fixes #5150

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Navigate to m.youtube.com
- Open new tab, navigate to wikipedia
- Click on any article and enable Reader Mode
- Now close current tab

## Screenshots:

https://user-images.githubusercontent.com/6643505/162323565-ccec42e7-7d98-44da-a1db-75e898bf8ad0.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift [hunk 1]
```diff
@@ -60,11 +60,13 @@ class TabsBarViewController: UIViewController {
...
   }
 
-  fileprivate weak var tabManager: TabManager?
-  fileprivate var tabList = WeakList<Tab>()
+  private weak var tabManager: TabManager?
+  private weak var browserViewController: BrowserViewController?
+  private var tabList = WeakList<Tab>()
 
-  init(tabManager: TabManager) {
+  init(tabManager: TabManager, browserViewController: BrowserViewController) {
```
Comment (iccub) [inline Client/Frontend/Browser/TabsBar/TabsBarViewController.swift]: Perhaps it would be better to add new delegate method to `TabsBarViewControllerDelegate`?
BVC implements it and this way we can avoid passing entire bvc to this class

**Review by iccub — CHANGES_REQUESTED** [review]
If possible I would rather add a delegate method instead of passing bvc to the tabs bar vc

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/TabsBar/TabsBarViewController.swift]: Yeah I thought that, I was thinking making bvc bigger or passing the reference. But will do the change.

Comment (soner-yuksel) [reply Client/Frontend/Browser/TabsBar/TabsBarViewController.swift]: Fix at https://github.com/brave/brave-ios/pull/5232/commits/1f4d62bd0ad0ce2a442cf89302d883c134cfc332

**Review by iccub — APPROVED** [review]
