### PR TITLE
Fixed punycoding of URLs and emails.

### LINKED ISSUE #1209: Can't search an email address in Brave iOS
### Description: 
Users are reporting that searching for an email address in the iOS app does not actually search that address -- instead, going to xyz@aol.com for example, will route you to aol.com, rather than searching for the email address entered.

### Steps to Reproduce 
  1. Search for an email address in iOS app
  2. Observe Brave directing you to the email domain or displaying odd search results

**Expected result:**
Search results for the email addressed entered

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

### Additional Information 
From Slack conversation @Brandon-T stated:

> It’s a bug in `processAddressBar` function of the BrowserViewController.
> 
> It calls `URIFixup.getURL` which adds `http://` to the beginning of the URL and submits it as a request via `finishEditingAndSubmit` instead of `submitSearchText` which produces the expected result.
> 
> For the quoted URL, it’s the same thing.. it converts `"test@brave.com"` to: `"http://%E2%80%9Ctest@brave.xn--com-9o0a"` (via `utf8HostToAscii` function)

Reddit user reporting:
https://www.reddit.com/r/brave_browser/comments/c8u6m2/bug_ios_searching_an_email_address/

### PR DESCRIPTION
**Pull request by Brandon-T**
This fixes the ability to search with quoted queries.
This fixes the ability to search with email address as a search query.
Fixes https://github.com/brave/brave-ios/issues/1209

Security Review: https://github.com/brave/internal/issues/664

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/URIFixup.swift [hunk 1]
```diff
@@ -32,6 +32,18 @@ class URIFixup {
         if trimmed.range(of: " ") != nil {
             return nil
         }
+        
+        // A URL is only valid when the URL has a scheme, is not an email, is not quoted, and can be punycoded.
+        // If one of the above conditions is NOT satisfied, the URL is invalid and should be deemed "search terms" search terms instead. Technically, an email is also a valid URL but does not get handled by the DNS server.
```
Comment (kylehickinson) [inline Client/Frontend/Browser/URIFixup.swift]: Can we fix-up these comments to be contained to a max 110 char column count?

File: Client/Frontend/Browser/URIFixup.swift [hunk 2]
```diff
@@ -50,4 +62,18 @@ class URIFixup {
...
+    static func isValidEmail(_ string: String) -> Bool {
+        let regex =
+            "(?:[a-zA-Z0-9!#$%\\&‘*+/=?\\^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%\\&'*+/=?\\^_`{|}" +
+            "~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\" +
+            "x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-" +
+            "z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5" +
+            "]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-" +
+            "9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21" +
+            "-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])"
+        return NSPredicate(format: "SELF MATCHES[c] %@", regex).evaluate(with: string)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/URIFixup.swift]: Interesting, never thought of using `NSPredicate` here instead of `NSRegularExpression`, is there any diff?

Comment (Brandon-T) [reply Client/Frontend/Browser/URIFixup.swift]: Hmm I never thought to use any of the other options.. however, it seems that `range(of:)` is actually the most optimized between all three with -O.. It doesn't let me specify -O3 but I'm sure with O3 it'd be negligible or produce the same results.

https://godbolt.org/z/p8XcFE

I'll switch to `range(of:)` which is more legible anyway.

File: Client/Frontend/Browser/URIFixup.swift [hunk 3]
```diff
@@ -50,4 +62,18 @@ class URIFixup {
         }
         return components?.url
     }
+    
+    /// Checks whether a string is a valid email conforming to RFC 2822.
+    /// http://www.cocoawithlove.com/2009/06/verifying-that-string-is-email-address.html
+    static func isValidEmail(_ string: String) -> Bool {
```
Comment (iccub) [inline Client/Frontend/Browser/URIFixup.swift]: Could we add few unit tests to it? That regex looks scary :D

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/URIFixup.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/URIFixup.swift]: Fixed.

File: Client/Frontend/Browser/URIFixup.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/URIFixup.swift]: Fixed.

File: Client/Frontend/Browser/URIFixup.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/URIFixup.swift]: Fixed. Added Punycode unit tests.

Comment (Brandon-T) [reply Client/Frontend/Browser/URIFixup.swift]: Added Unit tests for emails. Although, that regex conforms to RFC2822 strictly, I added on that allows more "relaxed" testing which omits quotes and square brackets which still conforms to RFC2822.

**Review by danishjafri88 — COMMENTED** [review]
Sorry for not mentioning this earlier, I forgot my security fix for eTLD had the `punycode` implementation removed from the app. The URI fixes are now handled by Webkit hence no longer required to be done in the app. Please refer to https://github.com/brave/brave-ios/pull/869 `Client/Frontend/Browser/URIFixup.swift` changes

**Comment by Brandon-T** [comment]
> Sorry for not mentioning this earlier, I forgot my security fix for eTLD had the `punycode` implementation removed from the app. The URI fixes are now handled by Webkit hence no longer required to be done in the app. Please refer to #869 `Client/Frontend/Browser/URIFixup.swift` changes

Hmm.. that pull request has been open for 6 months? Also, when you remove PunyCoding, does the `homograph` attack become effective? or?

EDIT: Just tested. The homograph attack is mitigated in your PR still.. However, it does NOT fix the bug this PR fixes (Entering Emails or Quoted strings: #1209).

**Comment by danishjafri88** [comment]
> > Sorry for not mentioning this earlier, I forgot my security fix for eTLD had the `punycode` implementation removed from the app. The URI fixes are now handled by Webkit hence no longer required to be done in the app. Please refer to #869 `Client/Frontend/Browser/URIFixup.swift` changes
> 
> Hmm.. that pull request has been open for 6 months? Also, when you remove PunyCoding, does the `homograph` attack become effective? or?

Webkit now ensures that IDN are now Punycoded by default. try `ΓΝΩΘΙΣΕΑΥΤΟΝ.EXAMPLE.COM` as an example.

**Comment by danishjafri88** [comment]
> mitigated

Agreed, we need your fix for email, just making sure that we don't use the old `punycoded` method anymore.

**Comment by Brandon-T** [comment]
> > mitigated
> 
> Agreed, we need your fix for email, just making sure that we don't use the old `punycoded` method anymore.

We will need your PR merged first then. After that, I will have to redo this PR and apply the fix.

**Review by iccub — APPROVED** [review]
Code looks good, thanks.

Could you add some Test Plan for QA please?

**Comment by jhreis** [comment]
I apologize for #869 falling through the cracks. It was a lengthy discussed PR and had many moving parts, but should have been merged long ago. It is now merged.

**Comment by Brandon-T** [comment]
> I apologize for #869 falling through the cracks. It was a lengthy discussed PR and had many moving parts, but should have been merged long ago. It is now merged.

:)

Updated the PR to have a much simpler fix now. No more need for checking if it's an email specifically via a Regex. I took some of the code from the PR with the safe-browsing and applied it here.

Specifically "canonicalization" and then checking if the url has a "user" for a "domain" :D. This fixed a hidden bug as well in Chrome that Safari handles perfectly!

**Comment by iccub** [comment]
@Brandon-T  Please submit a security ticket if it hasn't been done already

File: Client/Frontend/Browser/URIFixup.swift [hunk 4]
```diff
@@ -6,6 +6,23 @@ import Foundation
 import Shared
 
 class URIFixup {
+
+    private static func validateURL(_ url: URL) -> URL? {
+        // Validate the domain to make sure it doesn't have any invalid characters
+        // IE: quotes, etc..
+        if let host = url.host {
+            guard let decodedASCIIURL = host.replacingOccurrences(of: "+", with: "").removingPercentEncoding else {
```
Comment (diracdeltas) [inline Client/Frontend/Browser/URIFixup.swift]: why is `+` removed?

File: ClientTests/SearchTests.swift [hunk 5]
```diff
@@ -45,6 +45,20 @@ class SearchTests: XCTestCase {
...
+        checkInvalidURL(#""123""#)
+        checkInvalidURL(#""ftp.mozilla.org"#)
+        checkInvalidURL(#""ftp.mozilla.org""#)
+        checkInvalidURL(#"https://"ftp.mozilla.org""#)
+        checkInvalidURL(#"https://"ftp.mozilla.org"#)
+        checkInvalidURL("foo@brave.com")
+        checkInvalidURL("\"foo@brave.com")
+        checkInvalidURL("\"foo@brave.com\"")
+        checkInvalidURL(#""创业咖啡.中国"#)
+        checkInvalidURL(#""创业咖啡.中国""#)
```
Comment (diracdeltas) [inline ClientTests/SearchTests.swift:61]: thx for adding tests

File: Client/Frontend/Browser/URIFixup.swift (hunk 4 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/URIFixup.swift]: IIRC, it was for email searching as emails could have a plus sign in the host but the function would have returned invalid.. but the code has changed since I first wrote it, and it works without it.

Should be fixed now.

**Comment by diracdeltas** [comment]
lgtm
