### PR TITLE
Fix #487: Fix perceived sluggishness of page load

### LINKED ISSUE #487: Sometimes page doesn't load immediately
### Description: 
Sometimes page doesn't load immediately

### Steps to Reproduce 
  1. Open a new tab
  2. Visit a site say http://espn.com
  3. Page doesn't load immediately, looks like its stuck loading and remains on white screen

**Actual result:** 
Sometimes page doesn't load immediately

**Expected result:**
Page should be loaded instantly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent Issue. Sometimes leads to crash if you try to close the tab

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by kylehickinson**
- Fixes the submitted URL not showing up in the url bar
- Fixes navigating with empty titles to use the URL instead of doing nothing
- Adjusts the progress bar to 0.1 on start of loading since WKWebView doesn't report enough incremental estimated progress (makes it seem like nothings happening initially)

## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Notes for testing this patch

Just basic usage test to see if it feels better

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -910,7 +913,7 @@ class BrowserViewController: UIViewController {
             
             // Ensure that the tab title *actually* changed to prevent repeated calls
             // to navigateInTab(tab:).
-            guard let title = tab.title else { break }
+            guard let title = (webView.title?.count == 0 ? webView.url?.absoluteString : webView.title) else { break }
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:916]: Brackets could be removed unless it feels more readable to you

**Review by iccub — APPROVED** [review]
Tested it and it feels better than previous implementation

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (jhreis) [reply Client/Frontend/Browser/BrowserViewController.swift:916]: @kylehickinson

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift:916]: I think I'd rather leave the brackets to be honest, looks more contained as a result to be unwrapped in the guard-let
