### PR TITLE
Fix #214, Fix #215: Secure connection security indicator should not be shown for insecure sites

### LINKED ISSUE #214: Secure connection security indicator should not be shown for bad SSL requests
### Steps to Reproduce 
  1. Navigate to "badssl.com"
  2. Select a link with a bad icon, i.e. untrusted-root
  3. Tap "Advanced" button
  4. Tap "Visit site anyway" link

**Actual result:** Secure connection security indicator is shown

**Expected result:** Insecure connection security indicator should be shown

**Reproduces how often:** Every time

**Brave Version:** Development build hash e9d99c36697bc59ff348d174f5dfc6532bd95b3c

**Device details:** iPad Pro 10.5" iOS 11.4.1

### Additional Information 

Fix should be validated at badssl.com by validating that the insecure connection security indicator is shown for all links that have a bad icon

### LINKED ISSUE #215: Secure connection security indicator should not be shown for partially secure sites
### Steps to Reproduce 
  1. Navigate to "badssl.com"
  2. Select a link with the  icon, i.e. mixed-form

**Actual result:** Secure connection security indicator is shown

**Expected result:** Partially secure connection security indicator should be shown

**Reproduces how often:** Every time

**Brave Version:** Development build hash e9d99c36697bc59ff348d174f5dfc6532bd95b3c

**Device details:** iPad Pro 10.5" iOS 11.4.1

### Additional Information 

Fix should be validated at badssl.com by validating that the partially secure connection security indicator is shown for all links that have a  icon

### PR DESCRIPTION
**Pull request by tmancey**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [x] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Browser/BraveWebView.swift [hunk 1]
```diff
@@ -7,6 +7,8 @@ import WebKit
 
 class BraveWebView: WKWebView {
     
+    var isSecure = false
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BraveWebView.swift:10]: Seems a bit redundant/problematic to track the secure-ness with this boolean when we just call the `updateURLBar(forTab:)` anyways. Could we not just determine secure-ness in that call (since it would be called when both `hasOnlySecureContent` and `serverTrust` are changed?)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BraveWebView.swift (hunk 1 above)
Comment (tmancey) [reply Client/Frontend/Browser/BraveWebView.swift:10]: Unfortunately we cannot determine secure-ness in that call, due to when changing tabs as we need to remember the secureness of the web view.

Comment (kylehickinson) [reply Client/Frontend/Browser/BraveWebView.swift:10]: Hmm, then is it possible then to make this a computed read-only property? I know that one of those call's is async, so if it's not possible then I will accept this solution and mark as approved :)

Comment (tmancey) [reply Client/Frontend/Browser/BraveWebView.swift:10]: Thanks, if you could approve and merge that would be great as it will unblock my next ticket

**Review by kylehickinson — APPROVED** [review]
