### PR TITLE
Fix #3970 - #3971 - #3972: Shortcuts Related Bug fixes and changes

### LINKED ISSUE #3970: Custom Siri command opens a normal tab when Private Browsing only is enabled
### Description: 
Custom Siri command opens a normal tab when Private Browsing only is enabled

### Steps to Reproduce 
  1. Clean install 1.29 build and add Siri commands 
  2. Open Shortcuts and add a custom command with Brave to open a site
  3. Open Brave and enable Private browsing only mode
  4. Background the app and use voice command to open a new tab, loads Brave and opens a new private tab
  5. Visit a page on the new private tab that is launched, open a few tabs and load random pages
  6. Use voice command to launch the custom Siri shortcut added in step 2
  7. Click on the card to launch the page, opens in a normal tab rather than in private tab

**Actual result:** 
https://bravesoftware.slack.com/files/U1U85R2ES/F029F7F89U3/image_from_ios.mp4

**Expected result:**
Custom voice commands to open links should respect private tabs settings

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.29(21.07.28.9)

**Device details:** 
iPhone 7+ (iOS 14.5.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel @iccub @brave/sec-team

### LINKED ISSUE #3971: Tooltip shows when Siri overlay is recording command
### Description: 
Tooltip shows when Siri overlay is recording command 

### Steps to Reproduce 
  1. Clean install and add siri shrotcuts
  2. Visit a page in new tab
  3. Before page loads completely use siri voice command 
  4. Voice command hides the URL bar but the tooltip still shows up anyway

**Actual result:** 
image

**Expected result:**
Only show tooltip when shields is visible 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.29(21.07.28.9)

**Device details:** 
iPhone 7+ (iOS 14.5.1)

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel

### LINKED ISSUE #3972: Siri shortcut for Clear browser history has wrong message
### Description: 
Siri shortcut for Clear browser history has wrong message

### Steps to Reproduce 
  1. Clean install 1.29
  2. Open Siri shortcuts from settings
  3. Clear browser history info message reads `Use shortcuts to open a new tab via Siri - Voice Assistance`

**Actual result:** 

**Expected result:**
Should read `Use shortcuts to Clear browser history via Siri - Voice Assistance`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.29(21.07.28.09)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by soner-yuksel**
Open Website opens a private tab when Private Browsing only is enabled
Tooltip doesn't show when Siri overlay is recording command
Siri shortcut for Clear browser history message change

## Summary of Changes

This pull request fixes #3972
This pull request fixes #3971
This pull request fixes #3970

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Follow the Test plans inside the ticket for all the tickets

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Application/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -678,7 +678,10 @@ extension AppDelegate {
                 return false
             }
 
-            browserViewController.switchToTabForURLOrOpen(url, isPrivileged: false)
+            browserViewController.switchToTabForURLOrOpen(
+                url,
+                isPrivate: Preferences.Privacy.privateBrowsingOnly.value ? true :  false,
```
Comment (iccub) [inline Client/Application/Delegates/AppDelegate.swift]: can't just write it like
`isPrivate: Preferences.Privacy.privateBrowsingOnly.value`?

Comment (soner-yuksel) [reply Client/Application/Delegates/AppDelegate.swift]: Fix at https://github.com/brave/brave-ios/pull/3973/commits/cf0498e296d6a7db8bdb6d45b0f0b2ee044349b5

**Review by iccub — APPROVED** [review]
