### PR TITLE
Fix #5211: Force BraveCore cleanup before it gets the notification which might b…

### LINKED ISSUE #5211: BraveCore sometimes crashes the app when the app is killed
### Description: 
- Sometimes when the app is forcefully killed, it will be considered a crash because BraveCore causes it to hang.

### Steps to Reproduce 
  1. Kill the app

**Actual result:** 
- Crash

**Expected result:**
- No Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Very very hard to reproduce

**Brave Version:** 
Any

**Device details:** 
Any

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Force BraveCore cleanup before it gets the notification which might be too late.

This pull request fixes #5211

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Client/Application/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -335,6 +335,11 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
 
     // Clean up BraveCore
     braveCore.syncAPI.removeAllObservers()
+    if braveCore.responds(to: Selector(("onAppWillTerminate:"))) {
```
Comment (soner-yuksel) [inline Client/Application/Delegates/AppDelegate.swift:338]: Hopefully it will help.

**Review by soner-yuksel — APPROVED** [review]
