### PR TITLE
Fix #7771: When no qualities exist, try again for the YT-auto-quality.

### LINKED ISSUE #7771: [Follow up to #7055] Video quality not always set to "720p" even if it enabled in the settings
### Description: 

Follow-up to #7055

### Steps to Reproduce 
1. Launch Brave 
2. Three-dot menu > Settings
3. Open `Media` under `DISPLAY` section
4. Find `YOUTUBE` section > Tap `Highest Quality Playback` > Enable `Always on`
5. Go back and open www.youtube.com > Play any video
6. Tap ⚙︎ icon > Observe that quality is still set to `Auto (360p)`
7. If it is set to the expected `720p`, try to play a few more videos and check the `Gear` icon each time

### Actual result: 

Sometimes the video quality is set to `Auto (360p)` even if `Always on` is enabled in the `Highest Quality Playback` settings. If you manually refresh the page, then the video quality will be set to `720p` (time stamp ~20s - 30s in the video).

https://github.com/brave/brave-ios/assets/128532965/2cbba03f-d416-4ba1-93b9-02570ed8bba4

### Expected result:

When `Always on` (`Only when using WiFi`) is enabled in the `Highest Quality Playback` settings, the default video quality must be set to `720p` if that resolution is available for the video.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

Device/OS: iPhone 14 [iOS 16.5.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
From my tests, getAvailableQualityLevels sometimes returns an empty array. In this case we should try again few times before going with default option.

## Summary of Changes

This pull request fixes #7771 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/YoutubeQualityScript.js [hunk 1]
```diff
@@ -19,13 +19,16 @@ window.__firefox__.includeOnce("YoutubeQuality", function($) {
...
+  // Returns -1 if the api does not exist.
+  // If it does exist it returns number of available video qualities of the player.
+  function hasAPIsAndEnoughVideoQualities(player) {
+    if (!player || typeof player.getAvailableQualityLevels === 'undefined') {
+      return -1;
     }
     
-    return typeof player.getAvailableQualityLevels !== 'undefined';
+    return player.getAvailableQualityLevels().length;
   }
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/YoutubeQualityScript.js]: This is implied to be a boolean op, so best to return true/false, so return false instead of -1 and then return `.length > 0`. Then you can remove the > 0 check below

**Review by soner-yuksel — APPROVED** [review]
Tested, works very well, didnt really encounter an occasion where it fails with the script change here
