### PR TITLE
Fix #927, migrate syncOrder for reordering changes in 1.8

### LINKED ISSUE #927: adding bookmarks after updating visually replaces older ones in the UI (restores after re-opening bookmarks)
### Description: 

When updating from `1.7.4 (19.02.01.22)` to `1.8 (19.2.26.22)`, adding bookmarks after the update will start visually replacing other bookmark/folders that have already been created.

It's a UI issue and it doesn't actually replace the other already added bookmarks. Closing/Reopening settings/bookmarks will return everything back to a normal state.

### Steps to Reproduce 
  1. download `1.7.4 (19.02.01.22)` from App Store
  2. add a folder in bookmarks and add a random website into the newly created folder
  3. add a random bookmark in the root directory
  4. update to `1.8 (19.2.26.22)` using an `ipa` file
  5. once updated, go to another random website and attempt to add the bookmark
  4. you'll notice it will replace either the folder or the root bookmark in the UI
  5. close/re-open bookmarks and it and everything will be restored

**Actual result:** 

Example of the issue occurring: https://youtu.be/CcLls9xv2-M

**Expected result:**

Bookmarks should be added without having any strange behaviour where the UI replaces the folder

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

Upgrading from `1.7.4 (19.02.01.22)` to `1.8 (19.2.26.22)` (using the `ipa` file)

**Device details:** 

* `iPad Mini 4 running iOS 12.1.4` - Reproduced
* `iPhone 6s+ running iOS 12.1.4` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Application/Migration.swift [hunk 1]
```diff
@@ -14,6 +14,7 @@ extension Preferences {
     /// Migration preferences
     final class Migration {
         static let completed = Option<Bool>(key: "migration.completed", default: false)
+        static let syncOrderCompleted = Option<Bool>(key: "syncorder.migration.completed", default: false)
```
Comment (kylehickinson) [inline Client/Application/Migration.swift]: Small nit (😅): Considering all the keys it'd probably be better to name this `migration.sync-order.completed`

It doesn't _really_ matter though heh.

File: Data/models/Bookmark+Sync.swift [hunk 2]
```diff
@@ -15,14 +15,48 @@ extension Bookmark {
     /// Base order is needed to distinguish between bookmarks on different devices and platforms.
     static var baseOrder: String { return Preferences.Sync.baseSyncOrder.value }
     
-    /// Sets order for all bookmarks. Needed after user joins sync group for the first time.
+    // Errors thrown when using the javascript library for calculating sync orders are returned
+    // as 'undefined'.
+    private var isSyncOrderValid: Bool { return syncOrder != nil && syncOrder != "undefined" }
```
Comment (kylehickinson) [inline Data/models/Bookmark+Sync.swift]: Is this something we can't fix on the JS end?

File: Data/models/Bookmark+Sync.swift [hunk 3]
```diff
@@ -15,14 +15,48 @@ extension Bookmark {
...
+        }
+    }
+    
+    /// Sets order for all bookmarks. Needed after user joins sync group for the first time,
+    // or after updating from older Brave versions(<1.8.0)
     /// Returns an array of bookmarks with updated `syncOrder`.
-    class func updateBookmarksWithNewSyncOrder(parentFolder: Bookmark? = nil,
-                                               context: NSManagedObjectContext) -> [Bookmark]? {
+    @discardableResult
+    public class func updateBookmarksWithNewSyncOrder(parentFolder: Bookmark? = nil,
```
Comment (kylehickinson) [inline Data/models/Bookmark+Sync.swift]: Does this need to be `public`? Looks like its only only change in call site is from `syncOrderMigration`

File: Data/models/Bookmark+Sync.swift (hunk 2 above)
Comment (iccub) [reply Data/models/Bookmark+Sync.swift]: I will make a validator so js stuff like `null` `undefined` won't be returned

File: Client/Application/AppDelegate.swift [hunk 4]
```diff
@@ -243,6 +243,11 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
             log.error("Failed to initialize user referral program")
             UrpLog.log("Failed to initialize user referral program")
         }
+        
+        if !Preferences.Migration.syncOrderCompleted.value {
```
Comment (jhreis) [inline Client/Application/AppDelegate.swift]: I think we should consider doing the following.

Adding a static function on `Preferences.Migration` called `launchMigrations` or something that we just call. It will then run through each necessary migration and handle the flags internally. I do not want to continue adding tons of `Preferences.Migration.foo` to `AppDelegate`, as we will just continue having more and more of these.

Then when a new migration is necessary, we just internally add it to the `Preferences.Migration` function.

This also let's all migration preferences to be internalized. We can leave the existing migration call where it is, but I think this (and future ones where possible), should be moved internally.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Data/models/Bookmark+Sync.swift [hunk 5]
```diff
@@ -15,14 +15,50 @@ extension Bookmark {
     /// Base order is needed to distinguish between bookmarks on different devices and platforms.
     static var baseOrder: String { return Preferences.Sync.baseSyncOrder.value }
     
-    /// Sets order for all bookmarks. Needed after user joins sync group for the first time.
+    public class func isSyncOrderValid(_ value: String) -> Bool {
```
Comment (jhreis) [inline Data/models/Bookmark+Sync.swift:18]: This is just a bit hard to read. What about something like:

`return value.split(separator: ".").allSatisfy { Int($0) != nil }`

File: Data/models/Bookmark+Sync.swift [hunk 6]
```diff
@@ -15,14 +15,50 @@ extension Bookmark {
...
+            }
+            
+            let allFavorites = all(where: NSPredicate(format: "isFavorite == YES"), context: context) ?? []
+            let favoritesWithInvalidSyncOrder = allFavorites.filter { $0.syncOrder == nil }
+            
+            if allFavorites.count == favoritesWithInvalidSyncOrder.count {
+                updateBookmarksWithNewSyncOrder(updateFavorites: true, context: context)
+            }
+            
+            DataController.save(context: context)
```
Comment (jhreis) [inline Data/models/Bookmark+Sync.swift:48]: Is the same needed here if inside of a `perform`?

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Data/models/Bookmark+Sync.swift (hunk 5 above)
Comment (jhreis) [reply Data/models/Bookmark+Sync.swift:18]: Never mind, this doesn't work for a number of reasons.

File: Data/models/Bookmark+Sync.swift (hunk 6 above)
Comment (jhreis) [reply Data/models/Bookmark+Sync.swift:48]: Never mind on this too.

File: Data/models/Bookmark+Sync.swift (hunk 5 above)
Comment (danishjafri88) [reply Data/models/Bookmark+Sync.swift:18]: @jhreis though your solution is more readable I would advise to go with Michal's solution as it is more performant (O(n) in this case). @iccub it would be good to have a description of what this function does. Another good to have would be to create a func in String ext to validate syncOrder/versioning

Comment (iccub) [reply Data/models/Bookmark+Sync.swift:18]: we have decided to stay with regex as it catches more weird cases, added a comment on it too

**Review by jhreis — APPROVED** [review]
Great work!
