### PR TITLE
Fixed #446 by blocking  popups completely in private mode.

### LINKED ISSUE #446: Brave crashes when we share video via Twitter option
### Description: 
Brave crashes when we share video via Twitter option

### Steps to Reproduce 
  1. Open `https://theverge.com/` in Private tab
  2. Open any video which has SHARE option
  3. Scroll the page up and down, click on SHARE link and select `TWEET` option

**Actual result:** 
Brave crashes
https://drive.google.com/open?id=1qU4iGFFDs3ZqYBwKH0svTj0Q3clr-alg
**Expected result:**
Brave should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 8 (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by danishjafri88**
Fix for #446, when in private mode the WKProcessPoll of the configuration is changed, this leads to a crash for popups ie window.open where the configuration is craeted by parent wkwebview. To handle this for now we are stopping popup when in private mode. The fix is done in guard statement below.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

**Comment by kylehickinson** [comment]
A user may perceive this is as broken when they go to tap a link and nothing happens. Should we not show some sort of alert/toast to let the user know that the popup was not opened due to private mode?

Also is there no alternative, such as just navigating to the popup page instead of failing?

**Comment by danishjafri88** [comment]
@kylehickinson after discussing with @jhreis we decided to go with this for now. The issue is raised for enhancement in #456. Also apparently FF also is doing this right now.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1989,7 +1989,8 @@ private let schemesAllowedToBeOpenedAsPopups = ["http", "https", "javascript", "
 
 extension BrowserViewController: WKUIDelegate {
     func webView(_ webView: WKWebView, createWebViewWith configuration: WKWebViewConfiguration, for navigationAction: WKNavigationAction, windowFeatures: WKWindowFeatures) -> WKWebView? {
-        guard let parentTab = tabManager[webView] else { return nil }
+        // Fix for #446, when in private mode the WKProcessPoll of the configuration is changed, this leads to a crash for popups ie window.open where the configuration is craeted by parent wkwebview. To handle this for now we are stopping popup when in private mode. The fix is done in guard statement below.
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift]: Break this comment into multiple lines, pretty long.

Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift]: Also "craeted" typo.

**Review by jhreis — CHANGES_REQUESTED** [review]
To confirm, this matches the behavior on FF?

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: corrected

Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: Done

**Comment by danishjafri88** [comment]
Yes this is same as how it behaves in FF.

**Review by jhreis — APPROVED** [review]
