### PR TITLE
Fix#2790: Unable to save Gif images on iOS 12

### LINKED ISSUE #2790: Unable to save Gif images on iOS 12
### Description: 
Unable to save Gif images on iOS 12

### Steps to Reproduce 
  1. Search for funny gif 
  2. Open a gif image
  3. Long press to save image, save one frame instead of the gif image

**Actual result:** 
Unable to save Gif images on iOS 12

**Expected result:**
Should be able to save gif image 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.19 / 1.19.1

**Device details:** 
iPad and iPhone running iOS 12 only

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Found while testing https://github.com/brave/brave-ios/issues/2778

### PR DESCRIPTION
**Pull request by soner-yuksel**
For linkContextMenu saveImage - copyImage action is not handled properly for gifs in contextMenuConfigurationForElement.

## Summary of Changes

This pull request fixes #2790

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Same as explained in the ticket
Save a gif image in context menu while using iOS 12

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2992,6 +2992,54 @@ extension BrowserViewController: WKUIDelegate {
...
+                            // Only set the image onto the pasteboard if the pasteboard hasn't changed since
+                            // fetching the image; otherwise, in low-bandwidth situations,
+                            // we might be overwriting something that the user has subsequently added.
+                            if changeCount == pasteboard.changeCount, let imageData = data, error == nil {
+                                pasteboard.addImageWithData(imageData, forURL: url)
+                            }
+                            
+                            application.endBackgroundTask(taskId)
+                        }).resume()
+                    })
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Shouldn't we already have the image downloaded on the page to copy?

Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift]: It is the imageUrl being passed to copy paste board and save actions.

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -3125,45 +3142,12 @@ extension BrowserViewController: ContextMenuHelperDelegate {
...
-                    // Only set the image onto the pasteboard if the pasteboard hasn't changed since
-                    // fetching the image; otherwise, in low-bandwidth situations,
-                    // we might be overwriting something that the user has subsequently added.
-                    if changeCount == pasteboard.changeCount, let imageData = data, error == nil {
-                        pasteboard.addImageWithData(imageData, forURL: url)
-                    }
-                    
-                    application.endBackgroundTask(taskId)
-                }).resume()
+                self.copyImageClipBoardAction(url)
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: make `self` weak

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -3125,45 +3142,12 @@ extension BrowserViewController: ContextMenuHelperDelegate {
...
 
             let saveImageAction = UIAlertAction(title: Strings.saveImageActionTitle, style: .default) { _ in
-                self.getData(url) { [weak self] data in
-                    guard let self = self, let image = UIImage(data: data, scale: UIScreen.main.scale) else {
-                        return
-                    }
-                    
-                    UIImageWriteToSavedPhotosAlbum(image, self, #selector(self.image(image:didFinishSavingwithError:contextInfo:)), nil)
-                }
+                self.writePhotoToAlbumAction(url)
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: make `self` weak, maybe it doesnt make much sense in context of browserViewController :)

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
