### PR TITLE
Fix #3834: Adding Open Search References to Default Search Engines

### LINKED ISSUE #3834: Prevent Adding Default Search Engines to Search Engine List using Open Search Auto-Add
### Description: 

Some of the Default Search Engines including Brave Search can be added using Open Search Auto add.

We should add Open Search Reference to default Search Engines so the Add functionality will not be activated for already added engines.

### Steps to Reproduce 
  1. Go brave.search.com
  2. Press Search Textfield
  3. The Add button for Open Search is active over the keyboard

**Actual result:** 

The Add button for Open-Search is active

**Expected result:**

It should not be activated.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.27.1 (21.6.22.16)

**Device details:** 
Any Device

**Website problems only:**
N/A

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This pull request fixes #3834

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

### Steps to Reproduce 
  1. Go brave.search.com
  2. Press Search Textfield
  3. The Add button for Open Search is not active

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Search/InitialSearchEngines.swift [hunk 1]
```diff
@@ -12,6 +12,21 @@ class InitialSearchEngines {
     enum SearchEngineID: String {
         case google, braveSearch, bing, duckduckgo, yandex, qwant, startpage, yahoo, ecosia
         
+        /// Return time interval when to remove old tabs, or nil if no tabs should be removed.
```
Comment (iccub) [inline Client/Frontend/Browser/Search/InitialSearchEngines.swift]: Wrong comment

**Review by iccub — CHANGES_REQUESTED** [review]
looks super clean, few lines of code and our problems are solved

File: Client/Frontend/Browser/Search/InitialSearchEngines.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Search/InitialSearchEngines.swift]: Fix at https://github.com/brave/brave-ios/pull/3836/commits/a498ef00b182d14fbeb06f16077b2f12cf165411

**Review by iccub — APPROVED** [review]
