### PR TITLE
Fix #7079: Race condition resolving wallet address with ENS

### LINKED ISSUE #7079: Domain name is resolved when showing the ENS offchain lookup
### Description: 
Domain name is resolved when showing the ENS offchain lookup

### Steps to Reproduce 
  1. Install 1.49 and open Send screen
  2. Type `ethereum.eth` and wait for domain to resolve
  3. Replace `etherum` with `offchainexample`
  4. On ENS offchain lookup message it resolves `offchain.eth` and shows address 

### Expected result:
Shouldn't resolve domain names until user stops typing 

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Happened once

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
iPhone XR (iOS 16.3.1)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Potential race condition when resolving an ENS address.
    - Tricky to reproduce, but it could occur when `sendAddress` changes during network request to resolve the address. 
    - Fixed by verifying the domain we were resolving matches the current `sendAddress` prior to assigning the `resolvedAddress:

This pull request fixes #7079

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
Tricky to reproduce. 
1. Set ENS Offchain preference to `Ask`
2. Enter `offchain.eth` and quickly change to `offchainexample.eth`
3. Verify offchain message is shown without any resolved address displayed below it.

## Screenshots:

https://user-images.githubusercontent.com/5314553/224376185-646adc21-fc00-4832-9249-b42490553c5c.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 1]
```diff
@@ -283,6 +285,10 @@ public class SendTokenStore: ObservableObject {
         addressError = .sameAsFromAddress
         return
       }
+      guard domain == sendAddress, !Task.isCancelled else {
+        // address changed while resolving, or validation cancelled.
+        return
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/SendTokenStore.swift:290]: maybe we should disable input while the address is being resolved?

Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Stores/SendTokenStore.swift:290]: If we disable input while the address is being resolved it would close the software keyboard on the user while they are typing. I don't think this would be good UX on mobile, even increasing the current throttle from 0.25s to a high value would be tricky to find a nice 'sweet spot' to not interfere with the user.

https://user-images.githubusercontent.com/5314553/224394842-022416b0-cddc-4e1d-9d91-4e46e2a93edb.mp4

With this change we ignore the first request result if the send address / domain changed while we were resolving it (the request for current send address / domain pending).

**Review by nuo-xu — APPROVED** [review]
