### PR TITLE
Fix: #4503 Added more error handling in swap

### LINKED ISSUE #4503: Wallet handles unkown error and insufficient liquidity errors in swap
### Description: 

There should be 4 errors in Swap:
1. insufficient balance
2. insufficient funds for gas
3. Insufficient liquidity
4. unknown error
Currently missing last too. unkown error is for all other errors other than the first 3

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Fixed switching network not refreshing price quote
Added more error handling in swap.

This pull request fixes #4503 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:
File

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by nuo-xu** [comment]
wrong target branch

File: BraveWallet/WalletStrings.swift [hunk 1]
```diff
@@ -1164,25 +1164,39 @@ extension Strings {
...
+      bundle: .braveWallet,
+      value: "Insufficient liquidity",
+      comment: "This error is checked for price quote api call. This copy will be displayed as the title of the button at the bottom of Swap Screen."
+    )
+    public static let unknownError = NSLocalizedString(
+      "wallet.unknownError",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Unknown error",
+      comment: "Unknown error will be the error other than `Insufficient balance`, `Insufficient funds for gas` and `Insufficient liquidity"
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: Comment is for the translator and should explain the words/context of the words. This comment doesn't really make sense since the value doesn't change.

Something more like "An error message displayed when an unspecified problem occurs"

File: BraveWallet/WalletStrings.swift [hunk 2]
```diff
@@ -1164,25 +1164,39 @@ extension Strings {
...
       bundle: .braveWallet,
       value: "Activate Token %@",
       comment: "The title of the button at the bottom of Swap Screen, when the sell token is erc20 and it has not been activated its allowance. %@ will be replaced with the sell token's symbol such as 'DAI' or 'USDC'"
     )
+    public static let insufficientLiquidity = NSLocalizedString(
+      "wallet.insufficientLiquidity",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Insufficient liquidity",
+      comment: "This error is checked for price quote api call. This copy will be displayed as the title of the button at the bottom of Swap Screen."
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: Similar comment problem, something better: "An error message displayed when the user doesn't have enough liquidity to proceed with a transaction"

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift [hunk 3]
```diff
@@ -392,6 +392,43 @@ public class SwapTokenStore: ObservableObject {
...
+        if let response = response {
+          self.handlePriceQuoteResponse(response, base: base)
+        }
+        self.updatingPriceQuote = false
+      } else {
+        self.state = .error(Strings.Wallet.unknownError)
+        // check if priceQuote fails due to insufficient liquidity
+        if let error = error, self.isLiquidityError(error) {
+          self.state = .error(Strings.Wallet.insufficientLiquidity)
+        }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SwapTokenStore.swift]: May as well do if let/else rather than set `unknownError` immediately, want to avoid a possible double view update

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift [hunk 4]
```diff
@@ -392,6 +392,43 @@ public class SwapTokenStore: ObservableObject {
...
+    guard let swapParams = swapParameters(for: base) else { return }
+    
+    updatingPriceQuote = true
+    swapController.priceQuote(swapParams) { [weak self] success, response, error in
+      guard let self = self else { return }
+      if success {
+        if let response = response {
+          self.handlePriceQuoteResponse(response, base: base)
+        }
+        self.updatingPriceQuote = false
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SwapTokenStore.swift]: Just set this in `defer` of the closure and remove the set in the else

i.e. `defer { self.updatingPriceQuote = false }` (after `guard let self = self`)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
