### PR TITLE
Fix #5789: Pin Certs with Chromium API

### LINKED ISSUE #5789: [security] Pin SSL certificates with Chromium API
### Description: 
SSL Pinning doesn't work for the domains listed in https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc

### Steps to Reproduce 
  1. Navigate to https://ssl-pinning.someblog.org/

**Actual result:** 
Webpage loads without an SSL error
image

**Expected result:**
Webpage fails to load with an SSL error

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced,

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Security Review
- https://github.com/brave/security/issues/1127

## Summary of Changes
- Pin Certs with Chromium API
- Display appropriate error pages when pinning fails or certificate validation fails.

This pull request fixes #5789

## Screenshots
image

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by Brandon-T** [comment]
Added Unit tests.

**Review by stoletheminerals — CHANGES_REQUESTED** [review]
We should not allow a user to dismiss the error and proceed

image

**Comment by Brandon-T** [comment]
> We should not allow a user to dismiss the error and proceed
> 
> image

Fixed

image

**Comment by stoletheminerals** [comment]
Sorry @Brandon-T I missed this, the error text is not correct as well. The cert IS trusted by the OS, it's just not trusted by Brave because Brave expects a specific cert. Chrome has NET::ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN error for this case, can we show something similar on iOS?

**Comment by Brandon-T** [comment]
> Sorry @Brandon-T I missed this, the error text is not correct as well. The cert IS trusted by the OS, it's just not trusted by Brave because Brave expects a specific cert. Chrome has NET::ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN error for this case, can we show something similar on iOS?

Hmm I see. I can add a special error code like Chromium and the same error message as on desktop.

Will do it shortly.

**Comment by Brandon-T** [comment]
image

@stoletheminerals

**Review by stoletheminerals — APPROVED** [review]

File: Client/Frontend/Browser/Authenticator.swift [hunk 1]
```diff
@@ -11,6 +11,7 @@ import os.log
 class Authenticator {
   fileprivate static let maxAuthenticationAttempts = 3
 
+  @MainActor
```
Comment (iccub) [inline Client/Frontend/Browser/Authenticator.swift]: why do we need main actor to handle it now?

File: Client/Frontend/Browser/Interstitial Pages/CertificateErrorPageHandler.swift [hunk 2]
```diff
@@ -7,6 +7,10 @@ import Foundation
 import Shared
 import BraveShared
 
+extension CFNetworkErrors {
+  static let braveCertificatePinningFailed = CFNetworkErrors(rawValue: Int32.min)!
```
Comment (iccub) [inline Client/Frontend/Browser/Interstitial Pages/CertificateErrorPageHandler.swift:11]: is this safe? can't we use an enum's value `CFNetworkErrors.kXXXX` or something

File: Client/Frontend/Browser/TabManagerNavDelegate.swift [hunk 3]
```diff
@@ -41,18 +41,19 @@ class TabManagerNavDelegate: NSObject, WKNavigationDelegate {
...
     guard let firstAuthenticatingDelegate = authenticatingDelegates.first else {
-      return completionHandler(.performDefaultHandling, nil)
+      return (.performDefaultHandling, nil)
     }
 
-    firstAuthenticatingDelegate.webView?(webView, didReceive: challenge) { (disposition, credential) in
-      completionHandler(disposition, credential)
-    }
+    // Do NOT change to `delegate.webView?(....)` the optional operator makes async-await calls crash the compiler atm!
+    // It must be force-unwrapped at the time of writing `January 17th, 2023`.
```
Comment (iccub) [inline Client/Frontend/Browser/TabManagerNavDelegate.swift:54]: this comment still valid?

File: Client/Frontend/Browser/Interstitial Pages/CertificateErrorPageHandler.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Interstitial Pages/CertificateErrorPageHandler.swift:11]: No because we don't know what is the exact range of ALL network errors. Sometimes WebKit can throw errors outside of this range :(
So we use an extreme number so it doesn't clash.

File: Client/Frontend/Browser/TabManagerNavDelegate.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/TabManagerNavDelegate.swift:54]: Still valid as of January 17th. We have this comment on all other WebKit async delegate methods as well

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 4]
```diff
@@ -529,45 +529,87 @@ extension BrowserViewController: WKNavigationDelegate {
     return .allow
   }
 
-  // When this function is moved to Async-Await, do NOT forget to move the `TabManagerNavDelegate` to async-await!
-  public func webView(_ webView: WKWebView, didReceive challenge: URLAuthenticationChallenge, completionHandler: @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {
+  @MainActor
+  public func webView(_ webView: WKWebView, respondTo challenge: URLAuthenticationChallenge) async -> (URLSession.AuthChallengeDisposition, URLCredential?) {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Do we need to execute this on MainActor?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 5]
```diff
@@ -529,45 +529,87 @@ extension BrowserViewController: WKNavigationDelegate {
...
+      return (.useCredential, URLCredential(trust: trust))
+    }
+    
+    // Certificate Pinning
+    if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust {
+      if let serverTrust = challenge.protectionSpace.serverTrust {
+        let host = challenge.protectionSpace.host
+        let port = challenge.protectionSpace.port
+        
+        return await Task.detached(priority: .userInitiated) {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Why detach? Is `BraveCertificateUtility.verifyTrust` a heavy function?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 6]
```diff
@@ -529,45 +529,87 @@ extension BrowserViewController: WKNavigationDelegate {
...
+            return (.useCredential, URLCredential(trust: serverTrust))
+          }
+          
+          // Cert is valid and should not be pinned
+          // Let the system handle it and we'll show an error if the system cannot validate it
+          if result == Int32.min {
+            return (.performDefaultHandling, nil)
+          }
+          
+          return await Task { @MainActor in
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Why another Task inside? To access `tab(for:)`?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 7]
```diff
@@ -529,45 +529,87 @@ extension BrowserViewController: WKNavigationDelegate {
...
+            // Cert is invalid and cannot be pinned
+            Logger.module.error("CERTIFICATE_INVALID")
+            let errorCode = CFNetworkErrors.braveCertificatePinningFailed.rawValue
+            
+            let underlyingError = NSError(domain: kCFErrorDomainCFNetwork as String,
+                                          code: Int(errorCode),
+                                          userInfo: ["_kCFStreamErrorCodeKey": Int(errorCode)])
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Private API key?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 8]
```diff
@@ -529,45 +529,87 @@ extension BrowserViewController: WKNavigationDelegate {
...
+            
+            let error = NSError(domain: kCFErrorDomainCFNetwork as String,
+                                code: Int(errorCode),
+                                userInfo: [NSURLErrorFailingURLErrorKey: webView.url as Any,
+                                           "NSErrorPeerCertificateChainKey": certificateChain,
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Private API key?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 4 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: No but the old WebKit code with callbacks, calls it on `Main` like all the other WebKit delegates. So I made it the same as before and it matches all the other async-await delegates.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 5 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: It has to be called on a non-main queue because `verifyTrust` also uses `SecTrustEvaluate` which is required to be called on a non-main queue.

If I don't, it will give the usual purple error in Xcode

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 6 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Yeah it's for the `tab(for:)` access.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 7 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Yeah. It is used in our certificate pinning. This is the only way known to get certificate error codes :(

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 8 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Yeah. It's the only way to get the certificate chain from `NSError`. Fortunately, I'm the one setting it here, so even if Apple removes this key, it won't break anything as I'm the one setting it, and reading it back elsewhere in the code (certificate viewer).

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 4 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Since we're changing a majority of the logic in here let's just dump the main actor isolation here and then dump the `Task.detached` part

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Fixed

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 9]
```diff
@@ -529,46 +529,87 @@ extension BrowserViewController: WKNavigationDelegate {
...
+                            code: Int(errorCode),
+                            userInfo: [NSURLErrorFailingURLErrorKey: webView.url as Any,
+                                       "NSErrorPeerCertificateChainKey": certificateChain,
+                                               NSUnderlyingErrorKey: underlyingError])
+          
+        return await Task { @MainActor in
+          // Handle the error later in `didFailProvisionalNavigation`
+          self.tab(for: webView)?.sslPinningError = error
+          return (.cancelAuthenticationChallenge, nil)
+        }.value
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: minor nit: since you aren't using a value inside the task in the return value you can just use `MainActor.run` to execute this code and return like normal, e.g.:

```swift
await MainActor.run {
  self.tab(for: webView)?.sslPinningError = error
}
return (.cancelAuthenticationChallenge, nil)
```

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Fixed

**Review by kylehickinson — APPROVED** [review]
