### PR TITLE
Fix #5222: Playlist overlay showing at end of stream

### LINKED ISSUE #5222: [Playlist] - Sometimes when near the end of a stream, particle emitter shows when seeking
### Description: 
- When near the end of a stream, while seeking towards the very end, sometimes the particle emitter shows

### Steps to Reproduce 
  1. Seek to the end of a stream using the gestures (drag on the video/screen). Does not happen with the `seek bar`.

**Actual result:** 
- Particle Emitter shows

**Expected result:**
- Particle Emitter should not show

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

**Brave Version:** 
1.37.x-beta

**Device details:** 
Any

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Sometimes at the end of a stream, the playlist overlay shows when seeking via the gesture recognizers

This pull request fixes #5222

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift [hunk 1]
```diff
@@ -545,23 +546,14 @@ class VideoView: UIView, VideoTrackerBarDelegate {
...
-      // If the overlay is showing, hide the particle view.. else show it..
-      except.append(particleView)
-      display.append(particleView)
-    }
-
     UIView.animate(
       withDuration: 1.0, delay: 0.0, usingSpringWithDamping: 1.0, initialSpringVelocity: 1.0, options: [.curveEaseInOut, .allowUserInteraction],
       animations: {
         self.subviews.forEach({
+          if $0 == self.particleView {
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift:553]: Should we not use reference equality `===` here?

Comment (kylehickinson) [reply Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift:553]: `NSObject` subclass equality is based on pointers by default so they would be the same

Comment (iccub) [reply Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift:553]: in the repo we do compare by === reference for `Tab` objects which subclasses `NSObject` as well, was thinking this is a good convention in general, could cause undesired behavior if we conform to a custom Equatable comparison method or overriding `isEqual`, unlikely for this view of course

File: Client/Frontend/Browser/Playlist/Utilities/PlaylistStatusObserver.swift [hunk 2]
```diff
@@ -17,40 +17,33 @@ class PlaylistPlayerStatusObserver: NSObject {
...
-            })
+        let status = change.newValue ?? .unknown
+        switch status {
+        case .readyToPlay:
+          log.debug("Player Item Status: Ready")
+          self.onStatusChanged(.readyToPlay)
+        case .failed:
+          log.debug("Player Item Status: Failed")
+          self.onStatusChanged(.failed)
+        case .unknown:
```
Comment (cuba) [inline Client/Frontend/Browser/Playlist/Utilities/PlaylistStatusObserver.swift:39]: you can also remove the `?? .unknown` above and add a `.none` case

File: Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift [hunk 3]
```diff
@@ -652,7 +652,23 @@ extension AVPlayerItem {
       return true  // Assume video
     }
     
-    return (tracks.filter({ $0.assetTrack?.mediaType == .video }).isEmpty == false) || asset.isVideoTracksAvailable()
+    // If the only current track types are audio
+    if !tracks.allSatisfy({ $0.assetTrack?.mediaType == .audio }) {
+      return true  // Assume video
+    }
```
Comment (cuba) [inline Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift:658]: This is a personal preference but I like guards in these cases:
```
guard tracks.allSatisfy({ $0.assertTrack?.mediaType == .audio }) else { return true }
```

File: Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift [hunk 4]
```diff
@@ -652,7 +652,23 @@ extension AVPlayerItem {
...
+    
+    let hasVideoTracks = (tracks.filter({ $0.assetTrack?.mediaType == .video }).isEmpty == false) || asset.isVideoTracksAvailable()
```
Comment (cuba) [inline Client/Frontend/Browser/Playlist/VideoPlayer/MediaPlayer.swift]: Why not just `!tracks.filter({ $0.assetTrack?.mediaType == .video }).isEmpty`

File: Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift [hunk 5]
```diff
@@ -640,10 +632,31 @@ class VideoView: UIView, VideoTrackerBarDelegate {
...
     if let playerLayer = playerLayer {
       layer.insertSublayer(playerLayer, at: 0)
+      
+      if let player = playerLayer.player {
+        playerStatusObserver = player.observe(
+          \AVPlayer.currentItem?.tracks, options: [.new],
+          changeHandler: { [weak self] _, change in
+            guard let self = self else { return }
+            
+            if let tracks = change.newValue, tracks?.isEmpty == false {
```
Comment (cuba) [inline Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift]: i'm a little confused why tracks is optional if you do a `let tracks = `

File: Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift [hunk 6]
```diff
@@ -640,10 +632,31 @@ class VideoView: UIView, VideoTrackerBarDelegate {
...
+                self.particleView.alpha = 0.0
+              } else {
+                self.particleView.alpha = 1.0
+              }
+            } else {
+              self.particleView.alpha = 0.0
+            }
+          }
+        )
+      }
```
Comment (cuba) [inline Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayer.swift:651]: You can remove all these nested scopes by using guards in most places.

**Review by cuba — APPROVED** [review]
Just some minor nitpicks on my end

File: Client/Frontend/Browser/Playlist/Utilities/PlaylistStatusObserver.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Utilities/PlaylistStatusObserver.swift:39]: No you can't because `change.newValue` is a double optional.
I can only change it to `?? .none`
