### PR TITLE
Fix #3921: Use device authentication for browser lock feature

### LINKED ISSUE #1919: Investigate PIN code issue
### Description: 

We may have an issue with the pin code feature

_Another bug in the PIN code for Brave: if you have a pin code set and then use the “Share via..._

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1572277253164800

Please investigate

### LINKED ISSUE #2127: OSK focusing on URL bar instead of password modal when "Touch ID & Passcode" is enabled
### Description: 

When you have `Touch ID & Passcode` enabled, initially launching Brave will have the URL selected so whenever you type anything into the OSK, the URL will receive the input rather than the password modal. However, when you background Brave and re-open it for the second time, the focus goes back onto the password modal and you should be able to login.

### Steps to Reproduce 

  1. download the latest version of Brave (`1.14.2 (19.12.12.17)` in this instance)
  2. enable `Turn Passcode On` via `Settings` --> `Touch ID & Passcode`
  3. once enabled, close and re-open Brave and start typing your password into the OSK
  4. you'll notice that the password modal isn't receiving the input (URL bar is)
  5. background the application and re-open it, this time the password modal will receive the input

**`Note:`** as mentioned above, if you're running into this issue, try backgrounding the re-open Brave. This should switch the focus from the URL bar to the password modal and you should be able to login.

**Actual result:** 

Example of the issue occurring: https://youtu.be/8Krdx4Elrm8

**Expected result:**

Password modal should always get focus when `Touch ID & Passcode` is enabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.14.2 (19.12.12.17)` - **Reproduced**

**Device details:** 

* `iPad Air (3rd Gen)` running `iPadOS 13.3` - **Reproduced**
* `iPad Mini 4` running `iPadOS 12.4.1` - **Reproduced**
* `iPhone 6s` running `iOS 13.3` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jhreis @anthonypkeane @brave/legacy_qa

### LINKED ISSUE #2405: Pin code bug :: Face ID scan.
### Description: 

> This is Brave if you tap the URL box during the Face ID scan. If you switch apps and come back it corrects.

https://bravesoftware.slack.com/archives/C06UXF3KJ/p1584109414079300

### LINKED ISSUE #3687: iOS Face ID remains blurred if keyboard open
## Description 

If you have the brave app set to only allow access with Face ID on iOS, the expected behaviour is the browser unlocks upon successful face match. This works for the most part, but if you have your cursor in an input field such that the keyboard is open, and then move to another app, when you return to the Brave app, the Face ID authenticates successfully but the screen remains blurred. 

Workaround: when it is in this state, drag the app up as if you’re about to switch to another iOS app (but stay on the brave app) and it unblurs and is usable. 

## Steps to Reproduce

   1. Enable Face ID and passcode under settings 
   2. Visit website with HTML input field such as a login username field
   3. Click into the field so the keyboard pops up
   4. Switch to another app in iOS by dragging the app up from the bottom
   5. Switch back to the brave app, and the issue is reproduced

## Actual result:
On step 5, screen remains blurred instead. See screenshot 

## Expected result:

Brave browser should instead be available to use and not blurred 
## Reproduces how often: 
All the time

## Brave version (info found on brave://version)
1.25 on iOS

## Version/Channel Information:
N/A

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

### LINKED ISSUE #3921: Use device authentication for browser lock feature
Goal is the move the current custom browser PIN feature to use the users device authentication (including their device PIN)

Spec: `iOS Pin Upgrade`

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #3921

This pull request fixes #1919
This pull request fixes #2127
This pull request fixes #2405
This pull request fixes #3687

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Migration:
    - Test the 3 flows of migration (user has custom PIN and device PIN, user has custom PIN and no device PIN, user has no custom PIN)
        - If the user successfully migrates then browser lock is enabled in settings and their previous PIN is erased
    - Migration should happen before any other launch modals such as default browser
- Authentication
    - Backgrounding should hide the screen the next time you open the app switcher
    - App contents should not be visible (should be behind a thick blur)
    - Opening the app from background or fresh launch should request auth immediately
    - Cancelling the auth should leave you on blur with the ability to tap new "Unlock" button which repeats auth presented initially
    - Removing biometrics from the device will force you to authenticate with your PIN only
    - Disabling your device PIN will allow you to enter Brave even if the feature is on until you enable a PIN again

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -410,53 +404,23 @@ extension Strings {
...
-    
-    public static let authenticationWrongPasscodeError = NSLocalizedString("AuthenticationWrongPasscodeError", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Incorrect passcode. Try again.", comment: "Error message displayed when user enters incorrect passcode when trying to enter a protected section of the app")
-    
-    public static let authenticationIncorrectAttemptsRemaining = NSLocalizedString("AuthenticationIncorrectAttemptsRemaining", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Incorrect passcode. Try again (Attempts remaining: %d).", comment: "Error message displayed when user enters incorrect passcode when trying to enter a protected section of the app with attempts remaining")
+    public static let authenticationLoginsTouchReason = NSLocalizedString("AuthenticationLoginsTouchReason", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Access Brave by entering your device", comment: "Touch ID prompt subtitle when accessing logins")
```
Comment (ShivanKaul) [inline BraveShared/BraveStrings.swift]: `value:"Access Brave by using Touch ID"`?

Comment (kylehickinson) [reply BraveShared/BraveStrings.swift]: It will be displayed in both touch ID instances and when the user is asked to enter their PIN, just waiting on updated copy for a few of these strings

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -930,6 +930,18 @@ class BrowserViewController: UIViewController {
     }
 
     override func viewDidAppear(_ animated: Bool) {
+        if KeychainWrapper.sharedAppContainerKeychain.authenticationInfo() != nil {
+            let controller = UIHostingController(rootView: PasscodeMigrationContainerView())
+            controller.rootView.dismiss = { [unowned controller] in
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift]: `dimiss` should have the signature:
 ```swift
var dismiss: ((Self) -> Void))?
...
controller.rootView.dismiss = { controller in
    ...
}
 ``` 
 so you won't need `[unowned controller]`.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -930,6 +930,18 @@ class BrowserViewController: UIViewController {
...
+                KeychainWrapper.sharedAppContainerKeychain.setAuthenticationInfo(nil)
+                Preferences.Privacy.lockWithPasscode.value = true
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift]: Why is `setAuthenticationInfo(nil)` called in `dismiss` of the controller? `setAuthenticationInfo(nil)` removes the data from the keychain via `removeObject(forKey: KeychainKeyAuthenticationInfo)`. Is it intended?

File: Client/Frontend/Passcode/PasscodeViewController.swift [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+        passcodeWindow.rootViewController = lockedViewController
+        
+        lockedViewController.unlockButton.addTarget(self, action: #selector(tappedUnlock), for: .touchUpInside)
+
+        NotificationCenter.default.publisher(for: UIApplication.didEnterBackgroundNotification)
+            .sink(receiveValue: { [weak self] _ in
+                guard let self = self else { return }
+                // Update visibility when entering background
+                self.isVisible = Preferences.Privacy.lockWithPasscode.value &&
+                    self.context.canEvaluatePolicy(.deviceOwnerAuthentication, error: nil)
```
Comment (Brandon-T) [inline Client/Frontend/Passcode/PasscodeViewController.swift]: We should check against these error codes: https://developer.apple.com/documentation/localauthentication/laerror/code

or log the error because `canEvaluatePolicy` can fail for example if the context is invalid or the user unplugs an authenticator, etc.

File: Client/Frontend/Passcode/PasscodeViewController.swift [hunk 5]
```diff
@@ -0,0 +1,135 @@
...
+            })
+            .store(in: &cancellables)
+        
+        NotificationCenter.default.publisher(for: UIApplication.willEnterForegroundNotification)
+            .merge(with: NotificationCenter.default.publisher(for: UIApplication.didFinishLaunchingNotification))
+            .sink(receiveValue: { [weak self] _ in
+                guard let self = self else { return }
+                let isLocked = Preferences.Privacy.lockWithPasscode.value &&
+                    self.context.canEvaluatePolicy(.deviceOwnerAuthentication, error: nil)
```
Comment (Brandon-T) [inline Client/Frontend/Passcode/PasscodeViewController.swift]: What if the device is locked with a passcode, but evaluation of the context fails? This view will not be visible and the user will gain access?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 6]
```diff
@@ -930,6 +930,18 @@ class BrowserViewController: UIViewController {
     }
 
     override func viewDidAppear(_ animated: Bool) {
+        if KeychainWrapper.sharedAppContainerKeychain.authenticationInfo() != nil {
+            let controller = UIHostingController(rootView: PasscodeMigrationContainerView())
+            controller.rootView.dismiss = { [unowned controller] enableBrowserLock in
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift:937]: We should change the signature of `dismiss` to `(Self) -> Void` so we don't have to `unowned controller` and we can just do `dismiss = { controller, enableBrowserLock in ... }`

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 7]
```diff
@@ -930,6 +930,18 @@ class BrowserViewController: UIViewController {
...
+                KeychainWrapper.sharedAppContainerKeychain.setAuthenticationInfo(nil)
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift:938]: Why do we call `setAuthenticationInfo(nil)` when the controller is dismissed? It wipes the authentication info from the keychain. Is this expected?

File: Client/Frontend/Passcode/PasscodeMigrationView.swift [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+            .canEvaluatePolicy(.deviceOwnerAuthentication, error: nil)
+        biometryType = context.biometryType
+    }
+    
+    var body: some View {
+        PasscodeMigrationView(
+            isUserAuthenticationAvailable: isUserAuthenticationAvailable,
+            availableBiometryMethod: biometryType
+        ) {
+            if isUserAuthenticationAvailable {
```
Comment (Brandon-T) [inline Client/Frontend/Passcode/PasscodeMigrationView.swift]: We should do the evaluation here as well because `canEvaluatePolicy` states not to store the value for any duration of time because the policy can change. For example, the user might remove their fingerprints or passcode while this screen is active or the info might be invalidated by the system at any moment.

https://developer.apple.com/documentation/localauthentication/lacontext/1514149-canevaluatepolicy

`Don’t store the return value from this method because it might change as a result of changes in the system.`

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: `Self` is a SwiftUI view in this case, not the `UIHostingController` so can't do that

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 3 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: Yes this is intended, we no longer use the custom PIN in the keychain, once the user is migrated via this UI there is no need for it

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 6 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift:937]: Not sure why this double posted, going to mark this dupe as resolved

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 7 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift:938]: Not sure why this double posted, going to mark this dupe as resolved

File: Client/Frontend/Passcode/PasscodeViewController.swift (hunk 4 above)
Comment (kylehickinson) [reply Client/Frontend/Passcode/PasscodeViewController.swift]: Do you know which particular errors can be returned by `canEvaluatePolicy` other than `passcodeNotSet` when passing in the `deviceOwnerAuthentication` policy? Cancellation and Biometry related failures are not valid, iOS doesn't support watch and `authenticationFailed`, `userFallback` and `invalidContext` don't seem to be relevant to `canEvaluatePolicy` compared to actually evaluating the policy

Comment (kylehickinson) [reply Client/Frontend/Passcode/PasscodeViewController.swift]: I mean I can check if the error actually is `passcodeNotSet` before allowing the user through, but just seeing if I need to check anything else

File: Client/Frontend/Passcode/PasscodeViewController.swift (hunk 5 above)
Comment (kylehickinson) [reply Client/Frontend/Passcode/PasscodeViewController.swift]: See https://github.com/brave/brave-ios/pull/3922#discussion_r669117205 

But yes, if the user disables their PIN we will let them access the app since we can no longer evaluate the policy. Do we also need to create a new `LAContext` each time?

File: Client/Frontend/Passcode/PasscodeViewController.swift (hunk 4 above)
Comment (Brandon-T) [reply Client/Frontend/Passcode/PasscodeViewController.swift]: If the `invalidContext` is returned, create a new context, call it on that new context, and update `isVisible`. If the new one fails, ignore it as there's nothing more you can do.

File: Client/Frontend/Passcode/PasscodeViewController.swift (hunk 5 above)
Comment (Brandon-T) [reply Client/Frontend/Passcode/PasscodeViewController.swift]: We don't need a new context each time, but we do need one if it somehow got invalidated. The state of the context can change when you go from background to foreground.

Comment (kylehickinson) [reply Client/Frontend/Passcode/PasscodeViewController.swift]: Went with create new `LAContext` each time we foreground the app and checked explicitly for `passcodeNotSet` error code

File: Client/Frontend/Passcode/PasscodeMigrationView.swift (hunk 8 above)
Comment (kylehickinson) [reply Client/Frontend/Passcode/PasscodeMigrationView.swift]: Fixed

File: Client/Frontend/Passcode/PasscodeViewController.swift (hunk 4 above)
Comment (kylehickinson) [reply Client/Frontend/Passcode/PasscodeViewController.swift]: Fixed

**Review by Brandon-T — APPROVED** [review]
++ from me.
1. Works when app is in foreground and resumed from lock screen.
2. Works when app is in background resumed to foreground.
3. Works properly for incorrect passcode and when passcode is removed/unset.

It asks for pin every time :)

**Review by iccub — APPROVED** [review]

**Comment by bsclifton** [comment]
Nice job here! 😄  Lots of changes... but also a nice cleanup

**Comment by entonio** [comment]
This is problematic: most of the end user use cases for the Brave passcode require it to be different from the system passcode. Even in apps that allow face / touch locking, that is usually an alternative to an app~specific PIN. This PR may close a number of issues, but it renders the feature pointless to most.
There are already complaints in the community forums, and the reason there aren’t more is probably that users think it’s something to do with their illiteracy rather than an intentional change.
