### PR TITLE
Fix #2786: Remove yahoo se for unsupported regions.

### LINKED ISSUE #2786: Remove Yahoo for non-supported regions
### Description: 
Remove Yahoo for non-supported regions

### Steps to Reproduce 
  1. Set region to Poland
  2. Clean install
  3.Yahoo is listed in onboarding and quick search engine list

**Actual result:** 
Yahoo is listed for non-supported regions

**Expected result:**
Yahoo should be removed from onboarding, search engine list and quick search engines to match Android

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.19.1

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by iccub**
This commit also refactors logic of selecting initial search engines.

## Summary of Changes

This pull request fixes #2786 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

New install test
- Install new build with Polish locale
- verify that yahoo isn't on the list

Upgrade test
- Install 1.19.2/1.20 with Polish locale
- Set yahoo as your default search
- Upgrade to 1.21
- Verify that yahoo is not showing anymore
- For Polish locale the default show now be Google I think

I refactor the search engine logic a little so please test this locales as well to catch regressions.

New install, other regions:
- `US`, see if yahoo is present and showing first on the list, google should be default
- `DE`, see if yahoo is present and showing first on the list, ddg should be default, yahoo url should be `de.yahoo.com..`
- `FR`, see if yahoo is present and showing first on the list, qwant should be default, yahoo url should be `fr.yahoo.com..`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Search/InitialSearchEngines.swift [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+        /// Some search engines have regional variations which correspond to different xml files in `SearchPlugins` folder.
+        /// If you provide this custom id, it will be used instead of `regular` id when accessing the open search xml file.
+        var customId: String?
+        
+        // Only `id` mattera when comparing search engines.
+        // This is to prevent adding more than 2 engines of the same type.
+        static func == (lhs: Self, rhs: Self) -> Bool {
+            lhs.id == rhs.id
+        }
+    }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Search/InitialSearchEngines.swift]: This is a bit confusing to me, why do we have both an enum for ID's and custom IDs when only one is used.

We should instead just have `SearchEngine` take 1 ID and create a set of static variables that init with the enum IDs such as:

```
struct SearchEngine: Equatable {
  var id: String
  static let google = SearchEngine(id: "google")
  static let bing = SearchEngine(id: "bing")
  // ...
}
```

This allows you to still create a `SearchEngine` with a custom ID but without requiring to check for that ID in places, as well as let you use dot-syntax when trying to check for the base search engines that used to be `SearchEngineID`. Also should fix up type confusion around `defaultSearchEngine` and `priorityEngine` which both seem like they should be `SearchEngine` objects but instead are `SearchEngineID`s

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Search/InitialSearchEngines.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Browser/Search/InitialSearchEngines.swift]: `ID` is used to determine general search engine type, like it is Yandex for both Russian Yandex(ru) and Turkish Yandex(tr), 
my goal was to have this id so we are never able to add 2 of the same engine types, like having both yandex-ru and yandex-tr for one client.

`customId` is like a subcategory, usually used for regional search engines

The idea of my flow was:
1. Load default engines, those which are used by everyone
2. See if we should replace any search engine by locale specific ones
3. If yes, i check for search engine with `id` and replace it with the regional SE

In your example, if we have SE with id `google` added then we want to override it with `google-ru` how do you want to check if this SE already exists in the array and replace it?

Comment (kylehickinson) [reply Client/Frontend/Browser/Search/InitialSearchEngines.swift]: So for the example of finding `google` and override it with `google-ru` it would be pretty much the same as what you have now:

```swift
private func replaceOrInsert(engine: SearchEngine, with replacementEngine: SearchEngine) {
   guard let engineIndex = engines.firstIndex(of: engine) else {
       engines.append(replacementEngine)
       return
   }

   engines[engineIndex] = replacementEngine
}
...
replaceOrInsert(engine: .yahoo, with: .init(id: "yahoo-jp"))
```

The only difference being you are no longer dealing with having 2 ID's. The reason why I got rid of having 2 ID's was because of how you use it here: https://github.com/brave/brave-ios/pull/2889/files#diff-61f7191853dc8966b402988bb553c0edR262 

The very nature of its usage shows that there is no reason for keeping both (assuming I'm not missing a usage of the base ID somewhere?) 

> my goal was to have this id so we are never able to add 2 of the same engine types, like having both yandex-ru and yandex-tr for one client.

I think this usage will still adhere to this goal. It was still possible in your original code to have two of the same with programmer error since you were using an `enum` + `struct` in an array rather than an `OptionSet` of some kind.

Comment (iccub) [reply Client/Frontend/Browser/Search/InitialSearchEngines.swift]: `replaceOrInsert(engine: .yahoo, with: .init(id: "yahoo-jp"))`

This would not work with multiple overrides, we can detect `yahoo` <-> `yahoo-jp`, but if a new special case appears we can't find the original `yahoo` to replace

At the moment we have 3 layers of overrides,
1. language code + optional region
2. region only, lang code doesn't matter
3. special cases(for now it's only for priority engines)

at each step we might override the search engine

We can rewrite the code to avoid multiple overrides but this can make the code harder to read

Comment (kylehickinson) [reply Client/Frontend/Browser/Search/InitialSearchEngines.swift]: Ah I see what you mean. I guess that would mean we would have to keep 2 ID's regardless then.

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/Search/InitialSearchEngines.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Browser/Search/InitialSearchEngines.swift]: I will try to think if there's a cleaner way, i pushed this PR to run tests as xcode12 crashes on simulator :D
