### PR TITLE
Fix #3416, ref #3377: Attempt pre1.12 migration before Database init.

### LINKED ISSUE #3416: Default favourites are lost when app is relaunched
### Description: 
Default favourites are lost when app is relaunched

### Steps to Reproduce 
  1. Clean install 1.24
  2. Skip onboarding and tap on URL bar to bring up default favourites
  3. Quit and relaunch browser, all favourites are lost
  4. Visit GH and add it to favourite 
  5. Quit and relaunch, GH is retained as favourite 

**_Note: If you add a new custom favourite and then quit and relaunch all default and newly added favourites are lost_**

**Actual result:** 

**Expected result:**
No favourites should be lost

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.15.18)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #3416, references #3377 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

STR in the ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Application/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -70,6 +70,9 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
         
         // Must happen before passcode check, otherwise may unnecessarily reset keychain
         Migration.moveDatabaseToApplicationDirectory()
+        // We have to wait until pre1.12 migration is done until we proceed with database
+        // initialization. This is because Database container may change. See bugs #3416, #3377.
+        DataController.shared.initialize()
```
Comment (kylehickinson) [inline Client/Application/Delegates/AppDelegate.swift:75]: Will this cause similar lazy-style issues?

Comment (iccub) [reply Client/Application/Delegates/AppDelegate.swift:75]: no, no more lazy properties in DataController,
and the old migration logic should all happen on main thread

**Review by kylehickinson — APPROVED** [review]
