### PR TITLE
Fix #6909: fix textfield not display text value on appear.

### LINKED ISSUE #6909: NFT gateway URL is only shown when clicked on the input field
### Description: 
NFT gateway URL is only shown when clicked on the input field

### Steps to Reproduce 
  1. Install 1.48 build
  2. Go to Menu -> Web3 -> NFT Gateway
  3. URL is not shown until you click on the input field

### Actual result: 

https://user-images.githubusercontent.com/17010094/217594528-fa5e1fd9-c0f9-4834-bfea-a76617cb9e55.MP4

### Expected result:
Should show the NFT gateway link without having to click the input field

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
iPhone XR (iOS 15.7.1)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
a swiftui bug. has to give a little delay

This pull request fixes #6909

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

1. Install 1.48 build
2. Go to Menu -> Web3 -> NFT Gateway
3. URL is not shown until you click on the input field

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Settings/IPFSCustomGatewayView.swift [hunk 1]
```diff
@@ -85,8 +85,11 @@ struct IPFSCustomGatewayView: View {
       )
     }
     .onAppear {
-      if let url = ipfsAPI.nftIpfsGateway?.absoluteString {
-        self.url = url
+      // SwiftUI bug, has to wait a bit
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Settings/IPFSCustomGatewayView.swift]: Can we put the issue number into this comment so we can understand this in the future / possibly remove when we drop iOS 15.

**Review by StephenHeaps — APPROVED** [review]

File: Sources/BraveWallet/Settings/IPFSCustomGatewayView.swift (hunk 1 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Settings/IPFSCustomGatewayView.swift]: added in [be85902](https://github.com/brave/brave-ios/pull/7044/commits/be85902ee0b39dd8892151ff732098e812b817a3)
