### PR TITLE
Fix #8560, #8542, #8558: Two NFT UI bugs and one caching issue

### LINKED ISSUE #8560: Wallet: NFT GIF failed to load causes incorrect grid height
Screenshot 2023-12-12 at 2 13 40 PM

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
1. Fix weird animation caused by shimmering in NFT group dropdown button and NFT details 
2. Fix wrong NFT placeholder image height on GIF failure loading on iPad 
3. Update NFT caching after a successful send tx made in NFT detail  

This pull request fixes #8560, #8542, #8558

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

#### Animation
Please refer to the ticket #8542 (it's easier to reproduce on iOS15 device)
weird animation in NFT detail screen: please refer to this [video](https://github.com/brave/brave-ios/assets/1187676/37422b58-7827-44d6-9d6d-0222ec3f0144) 

#### Placeholder height (only reproducible on iPad)
1. Set up network to be very slow (developer can hardcode an invalid gif url)
2. set up wallet and add a NFT has a gif resource
3. go to portfolio/NFT
4. observe after NFT shimmering loading, the NFT placeholder image (image should be the same width and height) being displayed for that NFT

#### Caching
1. set up wallet that owns a NFT (Let's say Account 1 owns this NFT)
2. make sure this wallet has multiple accounts that have the same coin type with the NFT in step 1 (Let's say Account 1 and Account 2)
3. go to portfolio/NFT
4. open filter and select group with account and save
6. observe NFT is being displayed under the correct account 
7. click the NFT to go to its detail 
8. observe `owned by Account 1` is displayed
9. click ... button on navigation bar and select send 
10. send this NFT to Account 2
11. confirm this tx in confirmation prompt, and wait for the status to be `Confirmed` in the same screen
12. dismiss 
13. observe that you are back to the NFT detail screen but now `owned by Account 2` is displayed 
14. back to the NFT tab 
15. observe this NFT is grouped under `Account 2`

#### Extra 
1. set up a wallet and add some NFTs
2. go to portfolio/NFT
3. click any NFT to go to its detail screen
4. navigate to other tabs via the bottom tabs
5. navigate back to Portfolio 
6. observe NFT detail is not reloaded, everything is displayed the same (previously, this screen will reload and blockchain info will be gone)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift [hunk 1]
```diff
@@ -69,19 +69,32 @@ class NFTDetailStore: ObservableObject, WalletObserverStore {
...
-  @Published var networkInfo: BraveWallet.NetworkInfo = .init()
+  @Published var networkInfo: BraveWallet.NetworkInfo? {
+    didSet {
+      if networkInfo != nil {
+        print("new network assignment")
+      } else {
+        print("nil")
+      }
+    }
+  }
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift]: Debug code

File: Sources/BraveWallet/Crypto/NFT/NFTView.swift [hunk 2]
```diff
@@ -16,7 +16,7 @@ struct NFTView: View {
   
   @State private var isPresentingFiltersDisplaySettings: Bool = false
   @State private var isPresentingEditUserAssets: Bool = false
-  @State private var selectedNFTViewModel: NFTAssetViewModel?
+  @State private var nftDetailStore: NFTDetailStore?
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/NFT/NFTView.swift]: Why are we holding a reference here and in `CryptoStore`, is this change needed? It seems we're only using the `BockchainToken` / NFT from this model itself, can we just store that object instead?

File: Sources/BraveWallet/Crypto/Stores/NFTStore.swift [hunk 3]
```diff
@@ -245,14 +250,21 @@ public class NFTStore: ObservableObject, WalletObserverStore {
...
+    )
     
     userAssetsStore.setupObservers()
   }
   
   /// Cache of NFT balances for each account tokenBalances: [token.contractAddress]
   private var nftBalancesCache: [String: [String: Int]] = [:]
   
-  func update() {
+  func update(force: Bool = false) {
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Stores/NFTStore.swift]: nit: `force` -> `forceUpdateNFTBalances` 🙂

File: Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift (hunk 1 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift]: oops

**Review by StephenHeaps — APPROVED** [review]
