### PR TITLE
Fix #6320: Fix issue with long wait before downloading files

### LINKED ISSUE #6320: Can take 6 hours on a fresh install to download new ad-block rules
### Description: 
It's been discovered that the fetch tasks for getting files sleep for 6 hours before actually doing a download. This could result in new installs not having the ad-block rules for up to 6 hours (or longer if the app is not used frequently).

### Steps to Reproduce 
  1. Delete the app
  2. Install the app and run it
  3. Run the test here: https://test-pages.privacytests.org/tracking_content.html

**Actual result:** 
Google tag manager is not blocked (this is because the bundled rules don't block it

**Expected result:**
Google tag manager should be blocked 

Note: Facebook tracker is not being blocked instead. This is an issue that is being investigated separately and is the reason why this issue has been discovered.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.44

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
This is caused by a sleep that happens before the download is performed instead of after

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

Do an initial download instead of waiting on `ResourceDownloaderStream`

This pull request fixes #6320 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

On ticket

## Screenshots:

N/A

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/WebFilters/AdBlockEngineManager.swift [hunk 1]
```diff
@@ -185,20 +185,17 @@ public actor AdBlockEngineManager: Sendable {
             resultString = "not compiled"
```
Comment (cuba) [inline Client/WebFilters/AdBlockEngineManager.swift:185]: This file is just an output cleanup for debugging purposes. No real change here otherwise

File: Client/WebFilters/ContentBlocker/ContentBlockerHelper.swift [hunk 2]
```diff
@@ -116,19 +116,15 @@ class ContentBlockerHelper {
...
       
-      return rulesDebugString
-    }
+      return ["{", rulesDebugString, "}"].joined()
+    }.joined(separator: ", ")
     
-    log.debug("ContentBlockerHelper")
-    log.debug("loaded \(self.loadedRuleTypeWithSourceTypes.count, privacy: .public) tab rules:\n\(rulesString, privacy: .public)")
+    log.debug("Loaded \(self.loadedRuleTypeWithSourceTypes.count, privacy: .public) tab rules: \(rulesString, privacy: .public)")
     #endif
```
Comment (cuba) [inline Client/WebFilters/ContentBlocker/ContentBlockerHelper.swift:128]: This is just an output cleanup for debugging purposes. No real change here otherwise

File: Client/WebFilters/ContentBlocker/ContentBlockerManager.swift [hunk 3]
```diff
@@ -455,21 +455,18 @@ final public class ContentBlockerManager: Sendable {
...
+          "result: \(resultString)"
+        ].joined(separator: ", ")
         
-        return resourcesDebugString
-      }
+        return ["{", resourcesDebugString, "}"].joined()
+      }.joined(separator: ", ")
 
-    Self.log.debug("Compiled \(resources.count, privacy: .public) additional block list resources: \n\(resourcesString, privacy: .public))")
+    Self.log.debug("Compiled \(resources.count, privacy: .public) additional block list resources: \(resourcesString, privacy: .public))")
```
Comment (cuba) [inline Client/WebFilters/ContentBlocker/ContentBlockerManager.swift:469]: This is just an output cleanup for debugging purposes. No real change here otherwise

File: Client/WebFilters/ResourceDownloaderStream.swift [hunk 4]
```diff
@@ -27,7 +28,19 @@ final class ResourceDownloaderStream: Sendable, AsyncSequence, AsyncIteratorProt
...
+      // After that we wait only for changes while sleeping
+      self.firstLoad = false
+      let result = try await resourceDownloader.download(resource: resource)
+      
+      switch result {
+      case .downloaded(let url, let date), .notModified(let url, let date):
+        return .success(DownloadResult(date: date, fileURL: url))
+      }
+    }
+
```
Comment (cuba) [inline Client/WebFilters/ResourceDownloaderStream.swift:47]: This is the actual fix

File: Client/WebFilters/ResourceDownloaderStream.swift [hunk 5]
```diff
@@ -17,6 +17,7 @@ final class ResourceDownloaderStream: Sendable, AsyncSequence, AsyncIteratorProt
   private let resource: ResourceDownloader.Resource
   private let resourceDownloader: ResourceDownloader
   private let fetchInterval: TimeInterval
+  private var firstLoad = true
```
Comment (cuba) [inline Client/WebFilters/ResourceDownloaderStream.swift:20]: Made this a struct in order to conform to Sendable because I need to have a var

File: Client/WebFilters/AdBlockEngineManager.swift [hunk 6]
```diff
@@ -185,22 +185,19 @@ public actor AdBlockEngineManager: Sendable {
...
+            "result: \(resultString)",
+          ].joined(separator: ", ")
           
-          return sourceDebugString
-        }
+          return ["{", sourceDebugString, "}"].joined()
+        }.joined(separator: ", ")
 
-      log.debug("Loaded \(self.enabledResources.count, privacy: .public) (total) engine resources:\n\(resourcesString, privacy: .public)")
+      log.debug("Loaded \(self.enabledResources.count, privacy: .public) (total) engine resources: \(resourcesString, privacy: .public)")
```
Comment (cuba) [inline Client/WebFilters/AdBlockEngineManager.swift:200]: This is just an output cleanup for debugging purposes. No real change here otherwise

**Review by iccub — APPROVED** [review]

**Review by iccub — CHANGES_REQUESTED** [review]
`testSequenceWithErrorDownload` test does not pass after the changes

**Review by iccub — APPROVED** [review]
