### PR TITLE
Fix #6322: Use SFSafariViewController to display Rewards ToS url.

### LINKED ISSUE #6322: Error pages not loading assets
### Steps to Reproduce 
  1. Go to an error page, like `example.comasdasda`

**Actual result:** 
IMG_1303

**Expected result:**
Should look nicer

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
This commit also moves InternalSchemeHandler back to the main target.

## Summary of Changes

This pull request fixes #6322 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift [hunk 1]
```diff
@@ -12,6 +12,7 @@ import Onboarding
 import Storage
 import WebKit
 import os.log
+import SafariServices
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: nit: this import is not needed

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift [hunk 2]
```diff
@@ -11,6 +11,7 @@ import SwiftKeychainWrapper
 import SwiftUI
 import BraveVPN
 import Onboarding
+import SafariServices
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Callout.swift]: nit: same as above

**Review by soner-yuksel — APPROVED** [review]
Thanks for the fix 🥇

**Review by soner-yuksel — APPROVED** [review]
