### PR TITLE
Fix #6271: Race condition when removing a secondary account

### LINKED ISSUE #6271: Removing secondary account doesn't close the account details screen
### Description: 
Removing secondary account doesn't close the account details screen

### Steps to Reproduce 
  1. Import a second account on wallet
  2. Open the secondary account by tapping on it in accounts tab
  3. Tap on Remove account
  4. Enter password/use biometric unlock to confirm removal
  5. Goes back to Accout details screen
  6. Can't close or done
  7. Swipe down the account details screen, account is removed from the accounts tab

**Actual result:** 

https://user-images.githubusercontent.com/17010094/198374448-e1d606a2-1b35-473e-bcc8-c00fb7ccd894.MP4

**Expected result:**
Close the account details screen once its removed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45(22.10.25.19)

**Device details:** 
iPhone XR (iOS 15.6.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Fix race condition that could cause Account Details modal to fail to dismiss after removing an account. 'Cancel' / 'Done' buttons would not dismiss either, requiring a swipe to dismiss.
- Race condition: 
    - When integrating the Wallet Panel for dapps, `AccountActivityStore` was updated to change it's account to the selected account when the selected account changes, so that it would fetch the new info for the current account on display in the panel.
    - `AccountActivityView` is observing the `KeyringStore`s `allKeyrings` property to handle account deletion [here](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Crypto/Accounts/Activity/AccountActivityView.swift#L139-L146). When the account on display no longer exists in the keyring, we dismiss account details and pop back to the 'Accounts' tab.
    - The race condition can occur when the `AccountActivityStore` account updates _before_ the `AccountActivityView` observation of the keyring used for dismissing Account Details. `AccountActivityStore` account would update to the _selected_ account, no longer referencing the _removed_ account and thus the condition to dismiss Account Details modal would fail and we would not dismiss.

This pull request fixes #6271

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
I was able to reproduce this easiest on iOS 15, however it's possible on all versions.
1. Add a secondary account
2. Make sure this secondary account is selected account (buy/send/swap will show selected account)
3. Open account details for the secondary account
4. Tap 'Remove Account'
5. Enter wallet password to remove the account
6. Verify the account details modal is dismissed as expected, back to 'Accounts' tab.
7. Repeat from step 1 at least twice, given the issue was a race condition

## Screenshots:

iOS 14.5 | iOS 15.5 | iOS 16 | iPadOS 14.5 | iPadOS 15.5 | iPadOS 16
-- | -- | -- | -- | -- | --
<video src=https://user-images.githubusercontent.com/5314553/199066739-c262b2ed-860c-43b6-90c9-e47d702baa77.mp4> | <video src=https://user-images.githubusercontent.com/5314553/199066776-0e2fcac6-c114-47f3-a612-5d19148e7e26.mp4> | <video src=https://user-images.githubusercontent.com/5314553/199066797-e4ead8a1-ee76-43eb-9254-3641c0b7fb6f.mp4> | <video src=https://user-images.githubusercontent.com/5314553/199066938-1dbcc496-56d1-4fae-a293-0a4cd4a81efc.mp4> | <video src=https://user-images.githubusercontent.com/5314553/199067011-83684236-c949-4938-af05-cd6590428ef9.mp4> | <video src=https://user-images.githubusercontent.com/5314553/199067073-342312ab-d682-4d52-a8b3-45df4a7cf543.mp4>

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/AccountActivityStore.swift [hunk 1]
```diff
@@ -7,6 +7,10 @@ import Foundation
 import BraveCore
 
 class AccountActivityStore: ObservableObject {
+  /// If we are displaying the selected account (ex. in `WalletPanelView`).
+  /// In some cases, we do not want to update the current account displayed
+  /// when the selected account changes (ex. when removing an account)
+  let isSelectedAccount: Bool
```
Comment (kylehickinson) [inline Sources/BraveWallet/Crypto/Stores/AccountActivityStore.swift]: The naming is a tad confusing here, since you do not check whether or not the account is actually the selected account when making the store. It also is only used for equality checks and to stop `selectedAccountChanged` from setting the account.

Perhaps we could replace this with something like `observeAccountUpdates` or something.

Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Stores/AccountActivityStore.swift]: Good point, updated in [f11c050](https://github.com/brave/brave-ios/pull/6293/commits/f11c0505aaa9936d8212619418d631b4895da1f1)

**Review by kylehickinson — APPROVED** [review]

**Review by nuo-xu — APPROVED** [review]
