### PR TITLE
Fix #3974: Migrate favorites screen to use diffable data source.

### LINKED ISSUE #3974: Favorites screen collection view crash.
### Steps to Reproduce 
Hard to reproduce, but xcode has a lot of crashes reported.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #3974 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Sanity test, verify favorites can be deleted, moved and updated
- @bsclifton can repro on Beta and Dev; ping him to verify bug and fix

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 1]
```diff
@@ -742,7 +512,228 @@ extension FavoritesViewController {
...
+                    cell.setTitle(recentSearch.text)
+                }
+            }
+            
+            return cell
+        }
+        
+    }
+    
+    private func supplementaryViewProvider(collectionView: UICollectionView, kind: String, indexPath: IndexPath) -> UICollectionReusableView? {
```
Comment (iccub) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift:695]: method body copied from previous implementation

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 2]
```diff
@@ -742,7 +512,228 @@ extension FavoritesViewController {
...
+                if dataSource.snapshot().indexOfSection(.recentSearches) != nil {
+                    newSnapshot.reloadSections([.recentSearches])
+                }
+            }
+        }
+        
+        dataSource.apply(newSnapshot)
+    }
+    
+    private func cellProvider(collectionView: UICollectionView,
```
Comment (iccub) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift:621]: method body copied from previous implementation

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 3]
```diff
@@ -742,7 +512,228 @@ extension FavoritesViewController {
...
+                                header.setButtonVisibility(showButtonVisible: false, clearButtonVisible: true)
+                            } else {
+                                header.setButtonVisibility(showButtonVisible: false, clearButtonVisible: false)
+                            }
+                        } else {
+                            header.setButtonVisibility(showButtonVisible: false, clearButtonVisible: false)
+                        }
+                    } else {
+                        header.setButtonVisibility(showButtonVisible: true, clearButtonVisible: true)
+                    }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: Simplified:

```swift
let shouldShowRecentSearches = Preferences.Search.shouldShowRecentSearches.value
var showButtonVisible = !shouldShowRecentSearches
var clearButtonVisible = !shouldShowRecentSearches
if let fetchedObjects = recentSearchesFRC.fetchedObjects, shouldShowRecentSearches {
    let totalCount = RecentSearch.totalCount()
    showButtonVisible = fetchedObjects.count < totalCount
    clearButtonVisible = fetchedObjects.count <= totalCount
}
header.setButtonVisibility(
    showButtonVisible: showButtonVisible, 
    clearButtonVisible: clearButtonVisible
)
```

Edit: Updated to fix mismatched comparison for `showButtonVisible` and `clearButtonVisible` based on total count

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 4]
```diff
@@ -742,7 +512,228 @@ extension FavoritesViewController {
...
+                    header.button.addTarget(self, action: #selector(onPasteboardAction), for: .touchUpInside)
+                    return header
+                }
+            case .favorites:
+                return collectionView.dequeueReusableSupplementaryView(ofKind: kind, withReuseIdentifier: "fav_header", for: indexPath)
+            case .recentSearches:
+                if let header = collectionView.dequeueReusableSupplementaryView(ofKind: kind, withReuseIdentifier: "recent_searches_header", for: indexPath) as? RecentSearchHeaderView {
+                    header.resetLayout(showRecentSearches: Preferences.Search.shouldShowRecentSearches.value)
+                    header.showButton.removeTarget(self, action: nil, for: .touchUpInside)
+                    header.hideClearButton.removeTarget(self, action: nil, for: .touchUpInside)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: These calls are redundant, as per [`UIControl` documentation](https://developer.apple.com/documentation/uikit/uicontrol/1618259-addtarget):

> It is also safe to call this method multiple times with the same values for the target and action parameters. The control maintains a list of its attached targets and actions along with the events each supports.

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 5]
```diff
@@ -34,6 +34,35 @@ private class FavoritesHeaderView: UICollectionReusableView {
...
     
+    /// CoreData's diffable method relies on managed object ID only.
+    /// This does not work in our case since the object may be the same but with changed title or order.
+    /// This struct stores managed object ID as well as properties that we observer whether they have changed.
+    /// Note: `order` property does not have to be stored, favorite's frc handles order updates, it returns items in correct order.
+    private struct FavoriteDiffable: Hashable {
+        let objectID: NSManagedObjectID
+        let title: String?
+        let url: String?
+    }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: Does the title/url affect the identity of the favourite or is identity specific to the object ID?

If it doesn't affect identity, you should write a `hash(into:)` method that only hashes the `objectID`

Comment (iccub) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: If you change title or url, the objectID stays the same, it's the same object, that's the problem

I was afraid to add any hashable/equatable stuff directly into `Favorite` class to not break it in any other place

**Review by nasser7312 — APPROVED** [review]

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift (hunk 5 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: Right then in that case its identity is only linked to `objectID` and thus the hash produced should only be based on that. This is important for diffable data sources since it uses hash to determine identity (what cells get moved), and equality to determine if that cell needs to be updated

Comment (iccub) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: ah I see, so objectID must be hashed only but for equality i put the other properties

I will add it

Comment (kylehickinson) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: Yeah Hashable conforms to Equatable, you only need to implement an actual `hash(into:)` method, whereas Equality can be synthesized by the compiler with no change needed

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 6]
```diff
@@ -742,7 +516,226 @@ extension FavoritesViewController {
         } else {
             // User doesn't want to see the recent searches option again
             Preferences.Search.shouldShowRecentSearchesOptIn.value = false
-            collectionView.reloadData()
         }
     }
 }
+
+// MARK: - Diffable data source + NSFetchedResultsControllerDelegate
```
Comment (bsclifton) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift:523]: What does this mean, `MARK`?

Comment (kylehickinson) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift:523]: @bsclifton It's an Xcode-specific syntax that adds text to the file navigator and minimap:
image
image

Comment (iccub) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift:523]: It is a visual thing, splits sections of code in XCode navigator, for example 

xcode_mark_lines_example

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 7]
```diff
@@ -742,7 +516,226 @@ extension FavoritesViewController {
...
+        }
+        
+        let currentSnapshot = dataSource.snapshot()
+        var newSnapshot = Snapshot()
+        newSnapshot.appendSections(availableSections)
+        
+        guard let ids = snapshot.itemIdentifiers as? [NSManagedObjectID] else { return }
+        
+        if controller === favoritesFRC {
+            var items = [DataWrapper]()
```
Comment (bsclifton) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift:572]: I think this is fine as-is, but there's a possibility to break out each of the body for these `if controller === <condition>` into a separate method (ex: `onUpdateFavorites`, or `onUpdateRecentSearches`), so that you can easily unit test. For example, you can have unit tests which checks that when `recentSearchesSectionExists` is true, it appends items to `newSnapshot` and that nothing happens if `recentSearchesSectionExists` is false

As the code becomes more complex, this can help catch regressions. And when new bugs are discovered, you can create a test checking for that specific bug (to make sure it doesn't happen again). Just some food for thought 😄

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift (hunk 6 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift:523]: Also marks minimap my favourite :)

Screen Shot 2021-08-09 at 1 04 04 PM

This is similar to what we do in objective-c code `#pragma mark ` in brave-core.
