### PR TITLE
Fixed WebKit not laying out properly when the `viewport` meta tag is …

### LINKED ISSUE #1189: Youtube Video Rotation Issues
### Description: 
If a video is played without going into full screen mode, then the device is rotates, the video will maintain the same format before the rotation (too small or too big) after the device has rotate

### Steps to Reproduce 
  1. Play a video on youtube.com without going into full screen in vertical mode
  2. Rotate the device
  3. Keep Rotating to see all the different variants

**Actual result:** 
Correct Fit:

Too Small:

Too Large:

**Expected result:**
The size of the video should match the size of the video player

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.9.3

**Device details:** 

iPhone X, iOS 13

### Additional Information 
Does not work with Shields down
Works perfectly on Safari

### PR DESCRIPTION
**Pull request by Brandon-T**
Fixed WebKit not laying out properly when the `viewport` meta tag is NOT correctly on device rotation.
IE: Fixes Youtube rotation bug on iPhone.

Fixes: https://github.com/brave/brave-ios/issues/1189

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

**Review by iccub — COMMENTED** [review]
This is a tricky solution that affects all pages, not sure if it's worth for that youtube bug.
Looking forward to hear others opinions on that

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -181,6 +181,16 @@ class BrowserViewController: UIViewController {
         }, completion: { _ in
             self.scrollController.setMinimumZoom()
         })
+        
+        coordinator.animate(alongsideTransition: { context in
+            if let webView = self.tabManager.selectedTab?.webView {
+                webView.frame = self.view.bounds
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: ~I find it interesting because I dug a little into it and couldn't even find a point where the web view's frame is updated based on the new `webViewContainer`'s frame (which is constrained) other than on `didCreateWebView`…  So I'm not sure how this ever worked in landscape mode 😅~

I think the idea of adding the update to the webView's frame is fine, but we may want to consider doing it in `viewDidLayoutSubviews` so its always based on `self.webViewContainer.bounds` and not temporarily based on the view's bounds.

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: Ah, found where its set:

https://github.com/brave/brave-ios/blob/4b540b4d209ee5411ded1d491603fac2e3c3c07a/Client/Frontend/Browser/BrowserViewController.swift#L2019-L2021

If it's constrained, is there a reason why we need to animate it alongside the coordinator to the view's bounds?

**Comment by danishjafri88** [comment]
Its not working for the first load of webview. Post the first orientation change it works, with a flicker.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: @kylehickinson Yeah I have ZERO idea why that is. It's not the WebView's fault. It's Google's fault for their weird JS on Youtube only (so far).

Who knows what other sites have weird meta tags or JS to modify the video size based on view-port.. The problem I found is that Youtube does it "early".. IE: they do it the same time as the rotation instead of on the next layout cycle. Vimeo and other sites do it correctly.

Not sure how Safari handles it but it works for Apple lol.

Actually, if we scroll after the bug has happened, it fixes itself which is why I originally thought programatically scrolling would fix it but it doesn't. I can try adding the layoutSubviews too (I tried it by itself, it doesn't work at all without this animateAlongSide fix).

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: Its just that we technically are constraining it, so setting its frame is actually going to get overriden anyways at next layout cycle. Not sure if that can happen during the willTransition methods though. Perhaps we can try to force relayout with `setNeedsLayout`/`layoutIfNeeded` instead?

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: Originally I programatically injected `<meta name="viewport" content="width=device-width, initial-scale=1">` but youtube already has that.. so I figured I'd change `width=device-width` to the actual size and it works but not every time until the viewport change gets noticed (requires window.scrollBy(1, 1)`, etc..

I ended up making a separate test application with WKWebView constrained to view and rotating.. same bug happens and the same fix fixes it. :S

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: But is it because `webViewContainer` doesn't have the right frame? I'm not sure why we have to set it to `view.bounds`

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: Fixed. I gave up on the solution of modifying the frame. The webViewContainer had the right frame. The webView's `WKContentView (private)` did not.

I changed the solution to use Javascript. It should make us all feel safer I hope.

**Comment by Brandon-T** [comment]
> Its not working for the first load of webview. Post the first orientation change it works, with a flicker.

Fixed. Uses Javascript instead so it works every single time.

**Comment by Brandon-T** [comment]
> This is a tricky solution that affects all pages, not sure if it's worth for that youtube bug.
> Looking forward to hear others opinions on that

Changed to use Javascript the same way the browser would. When the page is finished loading, we size it for whatever size the page requests.. We're only triggering a resize but not explicitly saying what size to choose. We let the page and the webView figure that out.

**Review by danishjafri88 — APPROVED** [review]

**Comment by iccub** [comment]
Needs rebase

File: Client/Frontend/UserContent/UserScripts/WindowRenderHelper.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+    function resizeWindow() {
+        var evt = document.createEvent('UIEvents');
+        evt.initUIEvent('resize', true, false, window, 0);
+        window.dispatchEvent(evt);
+    }
+
+    function addDocumentStateListener() {
+        document.addEventListener('readystatechange', event => {
+            if (event.target.readyState === "interactive") {
+//                postMessage(event.target.readyState);
```
Comment (iccub) [inline Client/Frontend/UserContent/UserScripts/WindowRenderHelper.js]: Remove or leave a note why it's commented out

File: Client/Frontend/UserContent/UserScripts/WindowRenderHelper.js [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+                resizeWindow();
+            }
+
+            if (event.target.readyState === "complete") {
+//                postMessage(event.target.readyState);
```
Comment (iccub) [inline Client/Frontend/UserContent/UserScripts/WindowRenderHelper.js]: Remove or leave a note why it's commented out

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
