### PR TITLE
Fix #1963, Fix #1964 - URL bar alignment is off and secure page icon not showing

### LINKED ISSUE #1963: Icons to highlight cert errors in the address bar is missing
### Description: 
Address bar icons to highlight cert errors are missing in the address bar.

image

### Steps to Reproduce 
  1. Navigate to expired.badssl.com

**Actual result:** 
No icon for expired certs

**Expected result:**
Icon should be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
v1.13 (19.11.06.18)

**Device details:** 
iPhone SE

### LINKED ISSUE #1964: URL alignment is a bit off
### Description: 
Alignment of URLs in address bar is a bit off. 
image

### Steps to Reproduce 
  1. Navigate to wikipedia.org

**Actual result:** 
Only edia.org is displayed in the address bar

**Expected result:**
wikipedia.org should be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
v1.13 (19.11.06.18)

**Device details:** 
iPhone SE

### PR DESCRIPTION
**Pull request by Brandon-T**
## Security Review:
- https://github.com/brave/security/issues/28

## Summary of Changes
- Fixes URL bar alignment due to security bug #552 
- Fixes URL bar secure webpage icon not showing 100% of the time
- Like Android, added green and red colours to the icon.
- Fixes 4 security flaws in the validation of the `SecTrust` for `WKWebView` (calling `SecTrustEvaluate` was not enough.. I have added a list of policies to validate.. can be tested with https://badssl.com)
   - Now validates expired certificates
   - Now validates wrong host
   - Now validates CRL (Certificate Revocation)
   - Now validates x509 (SHA1, Subject, KeyLength, etc)..
      - In iOS 13, any certificate with SHA1 or weak algorithms will fail.
      - Any non TLS1.2 cert will fail.
      - Any certificate with invalid SubjectInfo or any invalid fields will fail.

Prior to these "small" changes, all tests against `badssl.com` would fail and show the page was secure when it wasn't.

**WIP**: 
- Still waiting on the real icons for iOS to be uploaded to the ticket.
- Unit tests for security.

This pull request fixes issue #1964 & #1963 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by iccub** [comment]
What is verdict on this? I mean how this PR works with etld+1 stuff?

**Comment by Brandon-T** [comment]
> What is verdict on this? I mean how this PR works with etld+1 stuff?

It works great. Basically we want to keep that it shows the ETLD+1 in the middle of the bar, but I reduced the amount of padding on the sides so it doesn't look like it's severely cut off..

However, @jhreis has asked someone if we're okay with how many icons are in the URL bar causing it to look really cluttered on iPhone 5S. Not sure the verdict on that part.

**Comment by iccub** [comment]
thanks, 5S runs on iOS 12 and is a really small fraction of devices, this is definitely out of scope for this PR

**Review by iccub — CHANGES_REQUESTED** [review]
The lock icon is red for new tab page, reader mode and error pages is showing, and it's red color.
We should hide it

**Comment by Brandon-T** [comment]
> The lock icon is red for new tab page, reader mode and error pages is showing, and it's red color.
> We should hide it

I fixed it for about page and reader mode by changing its colour back to the default or secure. Are you sure we should hide it? If we want to hide it, I can definitely do that but what about reader mode? Our GCD webserver has no cert or trust to evaluate so it will technically be insecure or undetermined. So when we switch back and forth from reader to non-reader mode, it will shift the URL every time if I hide it.

**Comment by jumde** [comment]
> thanks, 5S runs on iOS 12 and is a really small fraction of devices, this is definitely out of scope for this PR

@iccub the experience is same on iPhone SE.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1194,29 +1194,49 @@ class BrowserViewController: UIViewController {
...
                 break
             }
 
-            tab.contentIsSecure = false
-            topToolbar.contentIsSecure = tab.contentIsSecure
-
+            tab.secureContentState = .insecure
+            
             guard let serverTrust = tab.webView?.serverTrust else {
+                if let url = tab.webView?.url {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:1265]: This chain of `if` conditions is a bit complex, wdyt about refactoring it to be more readable?
Could be something like this, please recheck the logic
```
guard let serverTrust = tab.webView?.serverTrust else {
    if let url = tab.webView?.url {
        if url.isAboutHomeURL || url.isAboutURL {
            tab.secureContentState = .localHost
            topToolbar.secureContentState = .localHost
            break
        }

        if url.isReaderModeURL || url.isLocal {
            tab.secureContentState = .unknown
            topToolbar.secureContentState = .unknown
            break
        }
    }

    // fallback
    topToolbar.secureContentState = tab.secureContentState
    break
}
```

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
Wait with merging until security review is finished

File: Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift [hunk 2]
```diff
@@ -74,11 +74,17 @@ class TabLocationView: UIView {
...
-
-        if wasHidden != lockImageView.isHidden {
-            UIAccessibility.post(notification: .layoutChanged, argument: nil)
+        lockImageView.isHidden = false
+        
+        switch secureContentState {
+        case .localHost:
+            lockImageView.isHidden = true
+        case .secure:
+            lockImageView.tintColor = #colorLiteral(red: 0.3764705882, green: 0.3843137255, blue: 0.4, alpha: 1)
```
Comment (fmarier) [inline Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift]: Nit: This could be moved into the default section above the `switch` statement, next to `isHidden = false` and it wouldn't have to be duplicated across `.unknown` and `.secure`.

Comment (jhreis) [reply Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift]: Even better to support strict typing, `case .secure, .unknown`, just clump them together. That way we'll continue to get compiler checks.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Toolbars/UrlBar/TabLocationView.swift]: Fixed.

File: Client/Frontend/Browser/ErrorPageHelper.swift [hunk 3]
```diff
@@ -280,6 +280,40 @@ class ErrorPageHelper {
...
+            
+            if let code = CFNetworkErrors(rawValue: Int32(errCode)), cfErrors.contains(code) {
+                return errCode
+            }
+            
+            if ErrorPageHelper.CertErrors.contains(errCode) {
+                return errCode
+            }
+            
+            if let _ = ErrorPageHelper.CertErrorCodes[errCode] {
```
Comment (jhreis) [inline Client/Frontend/Browser/ErrorPageHelper.swift]: Generally just do actual `nil` checks:

`if ErrorPageHelper.CertErrorCodes[errCode] != nil { `

**Comment by jumde** [comment]
security review approved 👍

**Review by jhreis — APPROVED** [review]
