### PR TITLE
Fix #262, Fix #263: Add "reset to default value" functionality to Preferences

### LINKED ISSUE #262: Preference's will crash when setting `nil` on optional options
A `Preferences.Option` who's type is an Optional will crash if you set the value of that option to nil.

### LINKED ISSUE #263: Need ability to reset a Preferences back to default value
For Unit Tests that are effected by Preferences, we need the ability to reset their values back to default before a test runs.

### PR DESCRIPTION
**Pull request by kylehickinson**
@iccub Brought up that we needed a way to reset defaults (or have mock defaults as per FF), for unit tests that rely on `Preferences`.

This made me realize there was a bug that caused a crash/exception when you set any optional preference back to `nil`.

Also adds unit tests for `Preferences`.

## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [x] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

### CODE REVIEW

File: BraveShared/Preferences.swift [hunk 1]
```diff
@@ -63,10 +79,18 @@ extension Preferences {
...
+        public func reset() {
+            value = defaultValue
+        }
+        
         /// Creates a preference
         public init(key: String, default: ValueType, container: UserDefaults = Preferences.defaultContainer) {
             self.key = key
             self.container = container
+            self.defaultValue = `default`
             value = (container.value(forKey: key) as? ValueType) ?? `default`
```
Comment (tmancey) [inline BraveShared/Preferences.swift:94]: nit: `default` could be self.defaultValue

Comment (kylehickinson) [reply BraveShared/Preferences.swift:94]: I actually can't do that due to referencing self before init completes: `'self' captured by a closure before all members were initialized`

Comment (tmancey) [reply BraveShared/Preferences.swift:94]: 👍 I've now learnt to read the part that clearly says 'public init'

**Review by jhreis — APPROVED** [review]
