### PR TITLE
Fix #4637: Add Referral check to onboarding

### LINKED ISSUE #4637: Referral check confirmation is not shown for clean install leading to empty tiles on NTP
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/4378
NTP top tiles are not shown when you have something copied in the clipboard

### Steps to Reproduce 
  1. Copy something in the clipboard
  2. Install the latest app 1.33 (21.12.6.2) from TF
  3. Skip or view the welcome onboarding flow
  4. NTP is blank, doesn't show any top tiles, due to onboarding flow, referral check might have broken

**Note:** Follow the same steps in-app store version 1.32 and observe top tiles are shown in the NTP

**Actual result:** 
NTP top tiles are not shown when you have something copied in the clipboard

**1.33**

https://user-images.githubusercontent.com/38657976/144834574-4153a21f-718a-4f2d-8c47-c4d655966654.MP4

**1.32**

https://user-images.githubusercontent.com/38657976/144834790-7f2f2ac3-acad-44c1-b8eb-99541c3b0819.MP4

**Expected result:**
Top tiles should be shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33 (21.12.6.2)

**Device details:** 
iPad 7th Generation - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel @iccub

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Added the referral check controller to onboarding and linked it into the new onboarding flow.
- Verified NTP tiles show again.

This pull request fixes #4637

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2831,6 +2831,7 @@ extension BrowserViewController: NewTabPageDelegate {
         if Preferences.General.isNewRetentionUser.value == true,
             Preferences.DebugFlag.skipNTPCallouts != true,
             !topToolbar.inOverlayMode,
+            topToolbar.currentURL == nil,
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController.swift]: Didnt have this already very weird

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: Is it just me? OR is this somehow constantly being removed from development?
I have no idea why it was missing again.. but it seems this PR adds it back lol

Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift]: I agree this is totally weird :)

**Review by soner-yuksel — APPROVED** [review]
