### PR TITLE
Fix #5940: Fixes last playback not working at all

### LINKED ISSUE #5940: Playlist item not saving its last position
### Description: 
Slack Link: https://bravesoftware.slack.com/archives/CKJCXTP9B/p1661862230456169

Playlist item not saving its last position

### Steps to Reproduce 
  1. Open a video website
  2. Add a video to offline 
  3. Play the video and note the time when you stop
  4. Close Playlist and Brave
  5. Open Brave and Playlsit

**Actual result:** 
- Video position in step 3 is not saved

**Expected result:**
- Video position should be saved and the video should start where the user stopped

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix for last playback not working at all when leaving the current screen
- Fix for last playback not working at all due to shared folders refactor

This pull request fixes #5940

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by iccub** [comment]
As this relies on shared folders PR, putting blocked label on it until the first PR merges

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift [hunk 1]
```diff
@@ -247,20 +255,37 @@ class PlaylistListViewController: UIViewController {
...
+    let lastPlayedItemId = PlaylistManager.shared.allItems.first(where: { $0.pageSrc == lastPlayedItemUrl })?.tagId
+    
+    // If the user is current viewing the same video as the last played item
+    // then we choose whichever time offset is more recent
+    if let pageSrc = initialItem?.pageSrc,
+       let lastPlayedItem = Preferences.Playlist.lastPlayedItemUrl.value,
+       pageSrc == lastPlayedItem {
+      
+      // User is current on the same page as the last played item
+      lastPlayedItemTime = initialItemOffset > Preferences.Playlist.lastPlayedItemTime.value ?
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift]: nit: I believe we can use `max` value here between `initialItemOffset` and `Preferences.Playlist.lastPlayedItemTime.value`

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift [hunk 2]
```diff
@@ -247,20 +255,37 @@ class PlaylistListViewController: UIViewController {
     }
     
     // Shared folders are loading
-    if PlaylistManager.shared.currentFolder == nil {
+    if PlaylistManager.shared.currentFolder?.isPersistent == false {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift:258]: Why are we checking `isPersistent` now instead of `existence` ?

Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift:258]: Shared folders that are NOT persistent (not stored on the device, but only shown via the website) should not autoplay. That's why :)

This also checks existence because `currentFolder` is optional

**Review by soner-yuksel — APPROVED** [review]
