### PR TITLE
Fix #6715: Remove use of Playability API

### LINKED ISSUE #6715: Brave iOS preloads podcast episodes without user interaction - inflates industry download stats
### Description: 
Podcast hosting companies always use [`<audio preload="none">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-preload) on their embedded players, so as not to prefetch/download any episode that a listener does not explicitly play.  This is due to the way open podcasting works, where the industry still uses downloads as the only proxy for listens that is available on the server side.

Brave, however, seems to ignore this attribute in some cases and prefetches the audio on page load, with no user playback intent.  This inflates download stats, and therefore can affect what shows charge to their advertisers.

Note it does not seem to happen on every web player, just a subset, but even these players do not have the same problem on other iOS browsers - it seems specific to Brave.

My hunch is that it has something to due with the [Brave Playlist](https://brave.com/playlist/) feature - as the requests are not sent with the Brave iOS user agent, rather the generic "AppleCoreMedia" user-agent, a sure sign that an app is using AVPlayer/AVURLAsset without changing the default user-agent (which you should also do! [example here](https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/PlaybackItem.swift))

Is there a way to disable the Playlist feature on iOS to validate this theory?

This is a pretty big deal as it affects $$$ in the podcast world, and as a long time user of Brave I would hate to see Brave singled out as a bad actor here.

Thanks!

### Steps to Reproduce 
  1.  Use a client proxy like [Charles](https://www.charlesproxy.com/)
  2. Navigate to one of the following known problematic urls:
      - https://buzzcast.buzzsprout.com/231452/11989348-podcasting-trends-that-should-stay-in-2022
      - https://theunnoticed.cc/
      - https://anchor.fm/potd

### Actual result:
  Audio is fetched!

### Expected result:
  No audio is fetched

### Reproduces how often:
  Every time

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Use custom user agent.
- Remove use of Playability API (even though it only ever requests bytes [0-1], it affects websites where `preload=none` is set. This means we can no longer detect if an item is playable before showing it in the URL bar)

This pull request fixes #6715

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift [hunk 1]
```diff
@@ -780,7 +780,7 @@ extension PlaylistCarplayController {
   }
 
   func load(url: URL, autoPlayEnabled: Bool) -> AnyPublisher<Void, Error> {
-    load(asset: AVURLAsset(url: url), autoPlayEnabled: autoPlayEnabled)
+    load(asset: AVURLAsset(url: url, options: AVAsset.defaultOptions), autoPlayEnabled: autoPlayEnabled)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift:783]: Small style nit: Can't `AVAsset` prefix be omitted in all these references? (i.e. `AVAsset.defaultOptions` → `.defaultOptions`)

Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift:783]: No because the `options` parameter is `[String: Any]?` but the extension is on `AVAsset` so when I do:
`AVURLAsset(url: "....", options: .defaultOptions)` the compiler sees: `Dictionary<String, Any>.defaultOptions` which doesn't exist since it exists only on `AVAsset`.

Comment (kylehickinson) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift:783]: Thanks, didn't realize that!

**Review by kylehickinson — APPROVED** [review]
