### PR TITLE
Fix #3291: Intermittent crash when scrolling page while educational notification appearing

### LINKED ISSUE #3291: Intermittent crash when scrolling page while educational notification appearing
### Description: 

When on a new profile, scrolling through a website right after it loads while one of the educational notifications from https://github.com/brave/brave-ios/issues/2980 starts loading will intermittently crash the browser. I've ran into this one three different times but can't seem to reproduce often.

Created an issue so we can track/aware that we have a crash for the above scenario.

### Steps to Reproduce

  1. clean install `1.23 (21.2.10.18)`
  2. scroll through Brave Today and select a random article from the feed
  3. once it starts loading, start scrolling through the website
  4. hopefully one of the notifications from https://github.com/brave/brave-ios/issues/2980 is triggered

While the notification appears, Brave will sometimes freeze and crash after ~10s.

**Note:** Crashed twice using the following:
* https://www.theverge.com/2021/2/10/22277540/star-wars-severs-ties-the-mandalorian-gina-carano-cara-dune

**Actual result:** 

Brave freezing/crashing.

**Expected result:**

Brave shouldn't be crashing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

It's hard to reproduce but there's definitely a crash somewhere there.

**Brave Version:** 

* Reproduced three times using `1.23 (21.2.10.18)`

**Device details:** 

`iPhone 11` running `iOS 14.4` using `1.23 (21.2.10.18)` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @srirambv @bsclifton @iccub @kylehickinson @soner-yuksel

### PR DESCRIPTION
**Pull request by soner-yuksel**
Until we can find the real reason Disabling Pan Gesture for Share Educational Pop-Overs

## Summary of Changes

This pull request fixes #3291

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

> Skip all onboarding
> Ensure that you have https://www.theverge.com/2021/2/10/22277540/star-wars-severs-ties-the-mandalorian-gina-carano-cara-dune in your clipboard/copied
> Paste the above using Paste & Go
> Once the page starts loading, start swiping down before the Trackers & ads blocked on this page education modal appears 

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Shields/ShareTrackersController.swift [hunk 1]
```diff
@@ -322,3 +322,9 @@ private class ShareTrackersView: UIView, ShareTrayViewDelegate, Themeable {
         actionButton.appearanceTextColor = .white
     }
 }
+
+// MARK: - PopoverContentComponent
+
+extension ShareTrackersController: PopoverContentComponent {
+    var isPanToDismissEnabled: Bool { return false }
```
Comment (iccub) [inline Client/Frontend/Shields/ShareTrackersController.swift:329]: `return` can be omitted

**Review by iccub — APPROVED** [review]
