### PR TITLE
Fix 3565 - Playlist bugs, Text, and Thumbnail loading for live videos.

### LINKED ISSUE #3565: Rename Added to playlist to Added to Brave Playlist to keep it consitent
### Description: 
#3555 only changed the text for Add to Brave Playlist. Once video is added to playlist it still uses the older text `Added to Playlist`. 

### Steps to Reproduce 
  1. Install 1.25
  2. Visit a video 
  3. Add to playlist and see the toast message

**Actual result:** 

**Expected result:**
Should be consistent text and show `Added to Brave Playlist`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.21.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes text to say "Added to Brave Playlist".
- Fixes thumbnail loading for live streams so they can load from cache properly.
- Added loading activity indicator to make it more clear things are loading.
- Fixed bug in Javascript causing long-press to not work.

This pull request fixes #3565

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -1149,7 +1149,7 @@ extension Strings {
         public static let toastAddedToPlaylistTitle =
             NSLocalizedString("playList.toastAddedToPlaylistTitle",
                               bundle: .braveShared,
-                              value: "Added to Playlist",
+                              value: "Added to Brave Playlist",
```
Comment (iccub) [inline BraveShared/BraveStrings.swift:1152]: wait for @anthonypkeane with it

**Review by iccub — APPROVED** [review]
Wait with copy change for Anthony, rest looks good

File: BraveShared/BraveStrings.swift (hunk 1 above)
Comment (iccub) [reply BraveShared/BraveStrings.swift:1152]: unblocked, we keep your change

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — APPROVED** [review]
