### PR TITLE
Fix #2287 - NTP images not showing when the new assets are downloaded.

### LINKED ISSUE #2287: NTP SI logo's are not being replaced when pushing new assets to replace older assets
### Description: 

When pushing new NTP SI assets to replace assets that are currently live, the logo isn't being replaced. However, the images and links are being replaced.

When pushing new assets, we should be replacing the following:

* images
* logo(s)
* links

### Steps to Reproduce 

There's really no STR that QA can run through as we need help from someone with access to the back-end. Quick summary of what needs to be completed:

* ensure that current assets are being replaced with newer assets (images/logo/links)
* ensure sending a blank `photo.json` removes the current NTP SI assets without any issues

**Actual result:** 

When pushing new NTP SI assets, the logo's are not being replaced.

**Expected result:**

When pushing new NTP SI assets, it should replace the old images, logos and links.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the scenario mentioned above.

**Brave Version:** 

* `1.14.3 (20.1.30.18)`

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - *Reproduced*
* `iPhone 6s` running `iOS 13.3.1` - *Reproduced*
* `iPad Mini 4` running `iOS 12.4.1` - *Reproduced*
* `iPad Air 3rd Gen` running `iOS 13.3.1` - *Reproduced*

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @jhreis @LaurenWags @srirambv @anthonypkeane @Brandon-T

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

Not actually sure why `UIImage(named: "/var/UUID/ApplicationSupport/NTPDownloads/someImage.png")` loads "sometimes".. In the debugger, the image NEVER loads and we can never debug it.. It gives an error `"File contains no IDAT"` if we try to watch it as a variable expression.. but in app, it loads "sometimes".. If I change it to `contentsOfFile`, it loads 100% of the time in the debugger so we are doing this to make sure it also loads 100% of the time in app.

This pull request fixes issue #2288 (unconfirmed) #2287

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]
Another report to send to Apple, huh? :D

Perhaps it's another bug related to lazy initialization?

**Review by iccub — CHANGES_REQUESTED** [review]
Is blank for bundled resources, works for resources downloaded over the network

Zrzut ekranu 2020-01-31 o 11 34 57

File: Client/Frontend/Browser/HomePanel/NewTabPageBackgroundDataSource.swift [hunk 1]
```diff
@@ -29,7 +29,7 @@ class NewTabPageBackgroundDataSource {
         }
         
         lazy var imageLiteral: UIImage? = {
-            return UIImage(named: imageUrl)
+            return UIImage(contentsOfFile: imageUrl)
```
Comment (iccub) [inline Client/Frontend/Browser/HomePanel/NewTabPageBackgroundDataSource.swift]: Leaving this named should work, since all background are bundled.
And use `contentsOfFile` only for sponsored images at line 47

**Comment by jhreis** [comment]
~@iccub we shouldn't bundle resources anymore. I think it is fine, if this only works with remote resources.~
Realized, this impacts _normal_ background images 🙄

**Review by jhreis — APPROVED** [review]

**Review by iccub — APPROVED** [review]
