### PR TITLE
Fix #3549: Update TabsBar theme when toggled from system settings.

### LINKED ISSUE #3549: Tab bar theme doesn't change when device theme is changed via control center
### Description: 
[Follow up to #2558] Tab bar theme doesn't change when device theme is changed via control center

### Steps to Reproduce 
  1. Clean install 1.25
  2. Open a few tabs
  3. Change device theme from dark/light via control centre
  4. Tabs bar stays on older theme and doesn't switch to new theme

**Actual result:** 

https://user-images.githubusercontent.com/17010094/115381694-b90cf800-a1cb-11eb-9217-aa5df811aa80.MP4

**Expected result:**
Should respect theme when changed via control centre

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.15.13)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by iccub**
Ref #2558, a workaround had to be used.
There is a problem with UserInterfaceStyle state caused by our
appearance extensions.

## Summary of Changes

This pull request fixes #3549 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

STR in the ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift [hunk 1]
```diff
@@ -136,14 +140,6 @@ class TabsBarViewController: UIViewController {
         overflowIndicators()
     }
     
-    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
```
Comment (iccub) [inline Client/Frontend/Browser/TabsBar/TabsBarViewController.swift:139]: Theming code is called from BVC from the same method, i removed it to not apply theme twice

**Review by Brandon-T — APPROVED** [review]
