### PR TITLE
Fix #5749, #5567: Opening wallet panel on ethereum dapp causes page to reload

### LINKED ISSUE #5567: Switching network doesn't switch tokens fast enough
### Description: 
Switching network doesn't switch tokens fast enough

### Steps to Reproduce 
  1. Visit coingecko.com and search for a token and try to add, shows MM issue 
  2. Open `app.1inch.io` in a second tab and try connect and cancel the connection
  3. Visit `https://coinmarketcap.com` and search for a token (WTRTL)
  4. Change network to Fantom on wallet and add the token from CMC page from previous step
  5. Switch network back to Ethereum on Wallet page
  6. Search for a different token (PROM) on CMC page 
  7. Add the token(PROM) to wallet
  8. Open wallet portfolio page and switch network(ETH->Fantom), takes a long time to switch tokens
  9. Switch from Fantom-> ETH, still takes a long time to switch to native tokens 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/175292707-a91a6bdc-8f3e-40e9-ba07-140a1d700537.MP4

**Expected result:**
Should switch fast if not instantly 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.22.18)

**Device details:** 
iPad Pro (iOS 15.6 Beta). Performance is better on mobile compared to iPad

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### LINKED ISSUE #5749: Ethereum dapps page reloading when wallet panel is opened
### Description: 

Ethereum dapp sites are reloading when the panel is opened

### Steps to Reproduce 
  1. Visit an ethereum dapp site
  2. Open wallet panel
  3. Observe reload

**Actual result:** 

Dapp site reloads behind the panel:
https://user-images.githubusercontent.com/5314553/181307776-dc64cd23-b630-41b7-8303-2e004183514a.mp4

**Expected result:**

Dapp site should not reload unless the network actually changes

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

The issue is related to the `chainChangedEvent(_ chainId: String)` function reloading in [BrowserViewController+Wallet.swift](https://github.com/brave/brave-ios/blob/development/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWallet.swift#L299). May need to store last emitted chain id, or prevent this from being called unnecessarily.

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Fixed an issue where we were calling `setNetwork` on Json Rpc Service when we were initializing `KeyringStore` or `NetworkStore`. This would occur when opening the wallet panel, opening main wallet, and when checking pending transactions to show badge on wallet icon.
    - `NetworkStore` was calling `setNetwork` in `init` when fetching the currently selected network so we can update our `selectedChain` value. Since the value is fetched from Json Rpc Service, we don't need to call `setNetwork` on Json Rpc Service after.
    - In `KeyringStore`, the first call to `updateKeyringInfo()` would assign to `selectedAccount`, which then was calling `setSelectedAccount` on Keyring Service. This then triggered `selectedAccountChanged()` observation to call `setNetwork` on Json Rpc Service.
- Fixed Portfolio race condition when switching accounts from one coin type to another. The account switch would trigger an `update()` call in `PortfolioStore` prior to us updating the selected coin type, then the account switch triggers a network switch which updates the selected coin type. This meant 2 calls to `update()` could be running at the same time but for different selected coin types, so depending on which completed first we could show the incorrect user assets.
- Additionally, while fixing `PortfolioStore` made a small change to the logic so we update the user visible tokens immediately (then update again once balances, prices and price history are fetched) to resolve #5567.

This pull request fixes #5749, #5567

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
**Wallet dapp reload bug:**

1. Open [Metamask test dapp site](https://metamask.github.io/test-dapp/)
2. Connect your account(s)
3. Open wallet panel via icon in URL bar
4. Verify page does not reload behind the panel
5. Close the panel
6. Tap `Get Encryption Key`. Click Provide on model get public encryption key request.
7. Enter some text in message box below `Get Encryption Key` box
8. Tap `Encrypt`, tap `Decrypt`
9. Tap 'Allow' on decrypt request.
The Get Public Encryption Key -> Encrypt -> Decrypt flow was broken due to the reloading.

**Portfolio race condition:**

0. Solana support must be enabled
1. Open main wallet, and open Send Transaction modal.
2. Tap selected account to switch accounts
3. Select an account of a different coin type (ex. if Ethereum account selected, select a Solana account)
4. Close Send Transaction modal
5. Verify Portfolio store shows correct user assets
6. Open Send Transaction modal
7. Select originally selected account (must be different coin type than current selection)
8. Close Send Transaction modal
9. Verify Portfolio store shows correct user assets

## Screenshots:
Ethereum dapp reload on panel open fixed:

https://user-images.githubusercontent.com/5314553/181783672-373d4362-439f-4c44-a616-39b6101b569b.mp4

Portfolio race condition (video from `development`), occurs frequently:

https://user-images.githubusercontent.com/5314553/181783484-758de79c-26f8-4580-b4c0-f3a3024c4a91.mp4

Portfolio race condition fixed (video from this branch):

https://user-images.githubusercontent.com/5314553/181784459-dfe3c005-73b4-4e60-a88e-5dec18e45253.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/KeyringStore.swift [hunk 1]
```diff
@@ -367,9 +371,13 @@ extension KeyringStore: BraveWalletKeyringServiceObserver {
...
     Task { @MainActor in
+      let previouslySelectedCoin = await walletService.selectedCoin()
       walletService.setSelectedCoin(coinType)
-      let network = await rpcService.network(coinType)
-      await rpcService.setNetwork(network.chainId, coin: coinType) // update network here in case NetworkStore is closed. p.s. Multiple network selection with the same network will not cause `chainChangedEvent` getting called multiple times.
+      if previouslySelectedCoin != coinType {
+        // update network here in case NetworkStore is closed.
+        let network = await rpcService.network(coinType)
+        await rpcService.setNetwork(network.chainId, coin: coinType)
+      }
```
Comment (nuo-xu) [inline BraveWallet/Crypto/Stores/KeyringStore.swift:380]: dont think networkStore will ever close while keyringStore is open and getting `selectedAccountChanged` called.

Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/KeyringStore.swift:380]: I think `KeyringStore` can be initialized without `NetworkStore` in `WalletStore` if the default keyring is not created. This was added when we [added Solana account creation](https://github.com/brave/brave-ios/pull/5705/files#diff-adaa11a29db87248efa6499c3d9f1c020b1461ee06dfcf56b3f31bea2c6ee0c2R378).

File: BraveWallet/Crypto/Stores/PortfolioStore.swift [hunk 2]
```diff
@@ -94,137 +98,142 @@ public class PortfolioStore: ObservableObject {
...
+        .compactMap {
+          if let price = Double($0.price) {
+            return $0.decimalBalance * price
           }
-          let symbol = token.symbol.lowercased()
-          balances[symbol, default: 0] += balance
+          return nil
         }
+        .reduce(0.0, +)
+      balance = currencyFormatter.string(from: NSNumber(value: currentBalance)) ?? "–"
```
Comment (nuo-xu) [inline BraveWallet/Crypto/Stores/PortfolioStore.swift:153]: why its a `-` lol

Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/PortfolioStore.swift:153]: Existing code, I assume `-` instead of `0` to differentiate between zero balance and failed to load/parse balance.

**Review by nuo-xu — APPROVED** [review]
