### PR TITLE
Fix #848: Race condition when joining an existing Sync group.

### LINKED ISSUE #848: Sync chain creator gets listed twice on the second device
### Description: 
Sync chain creator gets listed twice on the second device

### Steps to Reproduce 
  1. Create sync chain on device 1
  2. Scan QR code on device 2
  3. Device 1 gets listed twice on device 2

**Actual result:** 
file 2
file 3

**Expected result:**
Should only list the device once

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
Device 1: iPad Pro (iOS 12.1.2) running 1.8(19.2.5.3) - Sync chain creator
Device 2: iPhone 7+ (iOS 12.1.2) running 1.8(19.2.5.3) 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adaquate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/sync/Sync.swift [hunk 1]
```diff
@@ -297,7 +297,12 @@ public class Sync: JSInjector {
             
             func startFetching() {
                 // Perform first fetch manually
-                self.fetchWrapper()
+                // First fetch has a slight delay to prevent race conditions when joining to an existing group.
+                // Fixing concurrency problem(#692) will most likely resolve this issue.
+                let delayBeforeFirstFetchInSeconds: TimeInterval = 3
+                DispatchQueue.main.asyncAfter(deadline: .now() + delayBeforeFirstFetchInSeconds, execute: {
+                    self.fetchWrapper()
```
Comment (jhreis) [inline Data/sync/Sync.swift]: Pass in `fetchWrapper` directly into the execute:

`DispatchQueue.main.asyncAfter(deadline: .now() + delayBeforeFirstFetchInSeconds, execute:fetchWrapper)`

**Review by jhreis — CHANGES_REQUESTED** [review]
Definitely a hack, but will work for now. Just one change.

**Review by jhreis — APPROVED** [review]
