### PR TITLE
Fix #6518: Fix issue with CF "unbreak" styles not applied on some pages

### LINKED ISSUE #6518: scrolling/swiping stops working under https://www.theblock.co after using `Open in New Tab`
### Description: 

Scrolling/Swiping under https://www.theblock.co will stop working after using `Open In New Tab` making it impossible to use the website. I run into this pretty consistently making it impossible to use the website. Sometimes scrolling will just stop working when scrolling through https://www.theblock.co/latest.

### Steps to Reproduce 

  1. launch/install brave from TF or the App Store (reproducible using `1.45.1 (22.11.17.19)` & `1.45.2 (22.11.29.0)`
  2. run through onboarding (doesn't matter if you skip or run through everything)
  3. load https://www.theblock.co/latest
  4. long tap on several of the article images and click on `Open in New Tab`

You'll notice after opening ~2-3 websites using the STR/Cases mentioned above, scrolling will break on the active tab.

**Actual result:** 

The ability to scroll/swipe through the website eventually breaks under https://www.theblock.co making it impossible to use the website. Here's a quick video of the issue occurring. You won't see the scrolling gestures but near the end, I'm attempting to scroll through the website and nothing happens:

https://user-images.githubusercontent.com/2602313/204747822-57d257a3-920b-49a2-be1b-572ba393fbe8.mp4

**Expected result:**

The ability to scroll/swipe through https://www.theblock.co should always work and not break. Once it breaks, it makes the entire tab usable and users need to either switch context or close the tab all together.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the STR/Cases outlined above.

**Brave Version:** 

* `1.45.1 (22.11.17.19)` - **Reproducible**
* `1.45.2 (22.11.29.0)` - **Reproducible**

**Device details:** 

* `iPhone 11` running `iOS 16.2` - **Reproducible**
* `iPad Air (3rd Gen)` running `iOS 16 BETA` - **Reproducible**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `No` (still reproducible when shields have been disabled)

### Additional Information

CCing @srirambv @Uni-verse

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #6518 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

Some steps in the enclosed ticket

Other test pages are:
[theblock.co](http://theblock.co/) 
- [x] Page is frozen. Caused by style priority

http://dailymail.co.uk/
- [x] A popup saying Adblock is disabled on iPad. Fixed by style priority

https://vivenu.com/event/luftgekuhlt-9-1efbgi
- [ ] Frozen page. Broken on desktop too (not fixed by this PR)

https://the-media-leader.com/why-ad-block-users-are-not-all-militant-ad-haters/
- [x] Cookie notice appears

https://bbs.animanch.com/
http://haronbouchannel.com/
https://chiebukuro.yahoo.co.jp/
http://yahoo.co.jp/
- [x] document.body doesn’t exist causing the script to not work. (I know many ads are hidden after this fix however I don't know if this hides all ads)

https://special.usps.com/testkits
- [ ] Main page content missing (not fixed by this PR)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 1]
```diff
@@ -47,7 +47,8 @@ window.__firefox__.execute(function($) {
   let notYetQueriedIds = []
   
   const CC = {}
-  CC.allSelectorsToRules = CC.allSelectorsToRules || new Map()
+  CC.allHideSelectorsToRules = CC.allHideSelectorsToRules || new Map()
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Why is this necessary? `CC = {}` on line 49. So it's clear that `CC` does NOT have an `allHideSelectorsToRules` property.
So therefore it will always hit the `||` condition and initialize to `new Map()`.
Might as well do: `CC.allHideSelectorsToRules = new Map()`

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 2]
```diff
@@ -47,7 +47,8 @@ window.__firefox__.execute(function($) {
...
+  CC.allRules = []
   CC.observingHasStarted = CC.observingHasStarted || false
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Same thing here. `CC` is initialized on line 49, so it'll never have an `observingHasStarted`. Just do: `CC.observingHasStarted = false`.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 3]
```diff
@@ -47,7 +47,8 @@ window.__firefox__.execute(function($) {
...
   // All new selectors go in `firstRunQueue`
   CC.firstRunQueue = CC.firstRunQueue || new Set()
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Same thing.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 4]
```diff
@@ -151,56 +152,58 @@ window.__firefox__.execute(function($) {
...
     selectors.forEach(selector => {
-      if ((typeof selector === 'string') && (CC.hide1pContent || !CC.allSelectorsToRules.has(selector))) {
+      if ((typeof selector === 'string') && (CC.hide1pContent || !CC.allHideSelectorsToRules.has(selector))) {
         const rule = selector + '{display:none !important;}'
-        CC.cosmeticStyleSheet.insertRule(rule, nextIndex)
+        CC.allRules.push(rule)
         
         if (!CC.hide1pContent) {
-          CC.allSelectorsToRules.set(selector, nextIndex)
+          CC.allHideSelectorsToRules.set(selector, CC.allRules.count - 1)
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: `CC.allRules` is an array according to line `51`. There is no such thing as `Array.count` in Javascript.
This will always set `selector` to `undefined`.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 5]
```diff
@@ -701,20 +705,29 @@ window.__firefox__.execute(function($) {
       scheduleQueuePump(false, false)
     }
   }
-
-  CC.tryScheduleQueuePump = CC.tryScheduleQueuePump || tryScheduleQueuePump
-  tryScheduleQueuePump()
   
   // Wait until document head is ready. We just need to wait a moment
   window.setTimeout(function () {
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Is this documentation correct? I don't see where exactly it is waiting for `head` to be ready?
This script is injected inside of `SiteStateListenerScriptHandler`'s message handler, via `evaluateJavascript` which executes when `document` is already loaded.
`SiteStateListenerScriptHandler` is injected at `documentStart`, so after `head` has already loaded and when the document has loaded.

Why do we need this timeout?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 1 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: It's taken from the typescript file which works a little bit differently on desktop. I thought about cleaning all this up but I decided not to touch the file too much because I'd still like to use the same source file for both iOS and desktop. But maybe now that these files are sort of going in separate directions I should.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 2 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Same answer. The original file was identical to the one in desktop but it has since diverged.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 3 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: same.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 5 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: ahh yes an old comment from the old way it was injected I believe. Not even sure if this timeout is all that necessary anymore.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 4 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Ahh good catch. This script is yet acting on this part of the function because it doesn't support non-aggressive mode yet so it's not a problem however it should be fixed.

**Review by Brandon-T — APPROVED** [review]

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 6]
```diff
@@ -489,33 +491,33 @@ window.__firefox__.execute(function($) {
...
-    const lastIdx = CC.allSelectorsToRules.size - 1
+    const lastIdx = CC.allHideSelectorsToRules.size - 1
     // to deal with removing rules
     
     for (let _i = 0, rulesToRemove1 = rulesToRemove; _i < rulesToRemove1.length; _i++) {
       const ruleIdx = rulesToRemove1[_i]
       // Safe to asset ruleIdx is a number because we've already filtered out
       // any `undefined` instances with the filter call above.
-      CC.cosmeticStyleSheet.deleteRule(ruleIdx)
+      delete myArray[ruleIdx]
```
Comment (pes10k) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: `delete` in JS causes all sorts of unexpected perf issues.  Probably better to rework this.  Also, probably better to use a more descripitve name than `myArray` ;)

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 7]
```diff
@@ -489,33 +491,33 @@ window.__firefox__.execute(function($) {
...
     }
     
     // Re-sync the indexes
     // TODO: Sync is hard, just re-build by iterating through the StyleSheet rules.
-    const ruleLookup = Array.from(CC.allSelectorsToRules.entries())
+    const ruleLookup = Array.from(CC.allHideSelectorsToRules.entries())
```
Comment (pes10k) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: no need to convert to Array

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 8]
```diff
@@ -489,33 +491,33 @@ window.__firefox__.execute(function($) {
...
       .filter(function (i) { return i !== undefined })
       .sort()
       .reverse()
 
     // Delete the rules
-    const lastIdx = CC.allSelectorsToRules.size - 1
+    const lastIdx = CC.allHideSelectorsToRules.size - 1
     // to deal with removing rules
     
     for (let _i = 0, rulesToRemove1 = rulesToRemove; _i < rulesToRemove1.length; _i++) {
```
Comment (pes10k) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: similarly, maybe a better name than `rulesToRemove1` and `rulesToRemove`

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js [hunk 9]
```diff
@@ -489,33 +491,33 @@ window.__firefox__.execute(function($) {
     }
     // Find selectors we have a rule index for
     const rulesToRemove = Array.from(selectors)
-      .map(function (selector) { return CC.allSelectorsToRules.get(selector) })
+      .map(function (selector) { return CC.allHideSelectorsToRules.get(selector) })
```
Comment (pes10k) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: nit, but maybe standardize on `function` or `=>` (here the `=>` is probably better, since you don't need `this`)

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 6 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: I need these indexes to stay in place for now because they are stored in a hash and are referenced for the non-aggressive mode. I will look at cleaning up this file but for now a lot of this logic is there to work on desktop and unless I start diverging this file from the desktop version and cleaning up what is not necessary for iOS it will be tricky to remove this delete.

Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: though myArray is a definite typo.

Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Fixed

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 7 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Fixed

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 9 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: Fixed. Well actually its been removed

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js (hunk 8 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/SelectorsPollerScript.js]: This was actually removed. I think the code here was just some ugly typescript conversion.

**Review by pes10k — APPROVED** [review]

**Review by pes10k — APPROVED** [review]

**Review by pes10k — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
