### PR TITLE
Fix: #4371 Test network UI in Buy Screen

### LINKED ISSUE #4371: Handle buy UI for different ethereum chains
When you select a test network, the UI changes to show slightly different copy and the button opens a test faucet as seen on desktop nightly:

image

URLs are hard-coded here: https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/utils/buy-asset-url.ts

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Integrated UI for test network chosen in Buy Screen.

This pull request fixes #4371 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

simulator_screenshot_1ED22E23-C265-4DC8-8B39-F6AC438CCB7A

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/WalletStrings.swift [hunk 1]
```diff
@@ -869,5 +869,26 @@ extension Strings {
...
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Test Faucet",
+      comment: "The title below account picker when user has selected a test network"
+    )
+    public static let buyTestDescription = NSLocalizedString(
+      "wallet.buyTestDescription",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Get Ether from a faucet for Rinkeby Test Network",
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: This will change based on the test network so probably should do `Get Ether from a faucet for %@` and replace it with the name of the chain

File: BraveWallet/Crypto/BuySwapSwap/BuyTokenView.swift [hunk 2]
```diff
@@ -31,52 +31,83 @@ struct BuyTokenView: View {
...
-              .keyboardType(.decimalPad)
+        } else {
+          Section {
+            VStack(alignment: .leading, spacing: 10.0) {
+              Text(Strings.Wallet.buyTestTitle)
+                .font(.headline)
+              Text(Strings.Wallet.buyTestDescription)
+                .font(.subheadline)
+                .foregroundColor(Color(.secondaryBraveLabel))
+            }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/BuyTokenView.swift:89]: Missed adding `.listRowBackground(Color(.secondaryBraveGroupedBackground))`

File: BraveWallet/Crypto/BuySwapSwap/BuyTokenView.swift [hunk 3]
```diff
@@ -31,52 +31,83 @@ struct BuyTokenView: View {
...
-        .listRowBackground(Color(.secondaryBraveGroupedBackground))
-        Section(
-          header: HStack {
-            Button(action: {
-              buyTokenStore.fetchBuyUrl(account: keyringStore.selectedAccount, amount: amountInput) { urlString in
-                guard let urlString = urlString, let url = URL(string: urlString) else {
-                  return
+          .listRowBackground(Color(.clear))
+          Section(
+            header: HStack {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/BuyTokenView.swift]: No need for an `HStack`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
