### PR TITLE
Fix #849, fix #845: update contexts with changes after NSBatchDelete.

### LINKED ISSUE #845: Device name gets duplicated if sync chain fails the first time
### Description: 
Device name gets duplicated if sync chain fails the first time

### Steps to Reproduce (May not be reliable steps)
  1. Scan a QR code quickly 
  2. Move the camera away and lock the device so that sync chain fails
  3. Scan the QR again to join the sync chain
  4. Device name gets duplicated

**Actual result:** 
Device name gets duplicated if sync chain fails the first time

**Expected result:**
Device name shouldn't get duplicated if sync chain fails the first time and device joins a chain on second attempt

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
In between easy and intermittent. If you are lucky everytime otherwise its intermittent

**Brave Version:** 
1.8(19.02.05.03)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Related to #844

### LINKED ISSUE #849: Reset and resync still shows the older device name from previous sync
### Description: 
Reset and resync still shows the older device name from previous sync

### Steps to Reproduce 
  1. Create a sync chain on device 1
  2. Add device 2 to the chain by scanning the QR code
  3. Reset sync on device 2
  4. Reset sync on device 1 as well
  5. Recreate sync on device 1, shows device 2 in the devices list

**Actual result:** 
Reset and resync still shows the older device name from previous sync

**Expected result:**
Reset and resync shouldn't show the older device from previous sync

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8(19.2.5.3)

**Device details:** 
Device 1: iPad Pro (iOS 12.1.2)
Device 2: iPhone 7+ (iOS 12.1.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adaquate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/models/CRUDProtocols.swift [hunk 1]
```diff
@@ -56,7 +56,20 @@ public extension Deletable where Self: NSManagedObject {
                 }
             } else {
                 let deleteRequest = NSBatchDeleteRequest(fetchRequest: request)
```
Comment (iccub) [inline Data/models/CRUDProtocols.swift]: Alternatively, to make it simpler we could just use regular context deletion and iterating over collection of objects.
At the moment there are no places in code where we store a lot of objects(except for browsing history) so batch deletion doesn't bring that much of speed improvement.

**Review by jhreis — APPROVED** [review]
This is super unfortunate honestly. But nice find.

**Comment by jhreis** [comment]
@iccub I fixed the merge conflicts quickly, just waiting for CI.
