### PR TITLE
Fix #807: Don't fire url autocompletion when deleting characters.

### LINKED ISSUE #807: URL autocomplete is annoying when trying to delete the URL
### Description: 
URL autocomplete is annoying when trying to delete the URL

### Steps to Reproduce 
  1. Visit a site to add to history
  2. Open a new tab and visit the same site 
  3. Try to edit the URL, autocomplete keeps filling the URL from history 

**Actual result:** 
URL autocomplete is annoying when trying to delete the URL

**Expected result:**
In edit mode autocomplete should not complete making it hard to edit the URL

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes issue #807 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/internal/issues/new?assignees=&labels=security%2C+security-reviews&template=security-review.md&title=iOS:%20Security+Review+for) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Search/SearchLoader.swift [hunk 1]
```diff
@@ -73,6 +73,13 @@ class _SearchLoader<UnusedA, UnusedB>: Loader<[Site], SearchViewController> {
                 
                 // First, see if the query matches any URLs from the user's search history.
                 self.load(result)
+                
+                // If the new search string is not longer than the previous
+                // we don't need to find an autocomplete suggestion.
+                if oldValue.count > self.query.count {
```
Comment (danishjafri88) [inline Client/Frontend/Browser/Search/SearchLoader.swift:79]: Will this not fail when I select the entire query and start typing again. ie on search bar type a query, then select all and type a letter for new query? (Of course this will only fail for the first replacing character, post the first it will start working again).

Comment (iccub) [reply Client/Frontend/Browser/Search/SearchLoader.swift:79]: Yes, it will not autofill after first character, do you think it's worth fixing? any smart solution for this?

Comment (iccub) [reply Client/Frontend/Browser/Search/SearchLoader.swift:79]: perhaps it's even good, as query suggestion based on 1 character isn't that useful

Comment (danishjafri88) [reply Client/Frontend/Browser/Search/SearchLoader.swift:79]: Yeah, I don't see any problems with this. I am ok just wanted to bring it to notice.

**Review by danishjafri88 — APPROVED** [review]

File: Client/Frontend/Browser/Search/SearchLoader.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/Search/SearchLoader.swift:79]: FYI, maybe you can add another check like `if oldValue.count > self.query.count && oldValue.hasPrefix(self.query) {` or something on that line

Comment (danishjafri88) [reply Client/Frontend/Browser/Search/SearchLoader.swift:79]: either is fine

**Review by Brandon-T — APPROVED** [review]
