### PR TITLE
Fix #1040, threading conflict when compiling rulelists.

### LINKED ISSUE #1040: App won’t start on IPad Air 2 after 1.9 and later
### Description: 
When updating to 1.9 I noticed that the app just wouldn’t want to start on my iPad Air 2 and 1.9.1 did no difference. It just starts a white screen and nothing more pops up. I have tried reinstalling the app two time. One time on 1.9 and one time on 1.9.1.

### Steps to Reproduce 
  1. Download Brave on IPad Air 2
  2. Try to start it

**Actual result:** 
Not much more than a black screen...

**Expected result:**
Fully functioning and useful.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% after update to 1.9

**Brave Version:** 
Can get exact version since the app won’t start, but it’s past 1.9

**Device details:** 
iPad Air 2 on IOS 12.2.0

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

Not easy to test because the bug doesn't always happen.
Please try to do a clean install few times and confirm that the UI does not get frozen.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift [hunk 1]
```diff
@@ -46,8 +46,7 @@ class AdblockDebugMenuTableViewController: TableViewController {
             """
         
         var section = Section(header: .title("Available lists"), footer: .title(footerNote))
-        guard let store = WKContentRuleListStore.default() else { return completion }
-        
+        let store = ContentBlockerHelper.ruleStore
```
Comment (kylehickinson) [inline Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift:49]: I assume that accessing this is safe to do on both bg thread + main thread in Swift land, right? Trying to recall the rules for when static variables are initialized and if they're done atomically…

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Approved but had to restart the build cause it failed for no reason

File: Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift:49]: no idea really, shouldn't it crash then with EXC_BAD_ACCESS?

I would say, keep it in mind and if the problem with threading and rulelist compilation persist, try to dig more and make it more robust
