### PR TITLE
Fix #4173: Fixes PrivilegedRequest to work on all iOS versions.

### LINKED ISSUE #4173: PrivilegedRequest no longer works on iOS-15
### Description: 
- iOS 15 sandboxes the URLRequest that is sent to the WKWebView. In other words, it makes a COPY OR reconstructs the request. Any associated values with the request, is therefore lost. 
- In other words, `URLProtocol.property(forKey: SOME_KEY, in: self)` will NOT work on `WKWebView` requests on iOS 15+.

- As a result of the above, Reader-Mode and other `localhost` requests are broken completely and will be denied automatically.

### Steps to Reproduce 
  1. Enter reader-mode on iOS 15

**Actual result:** 
- Reader-Mode does NOT work.

**Expected result:**
- Reader-Mode should work.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily Reproduced

**Brave Version:** 
Any

**Device details:** 
iOS 15+

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Moved `PrivilegedRequest` to the shared module because Xcode 13 refuses to compile `Shared` due to `Shared` calling `import Client` inside the `URLExtensions.swift` file. The error is: `Shared, BraveShared, and Client have cyclical dependencies on Shared`.
- Fixed `PrivilegedRequest` to use a generated Query-String parameter to determine if a `URLRequest` or `URL` is privileged.
- Changed all `originalURL` code to strip the privileges from the URL when no longer needed, so the query parameter isn't leaked.

This pull request fixes #4173

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Enter & Leave Reader-Mode on iOS 15+ and it should work.
- Test Session Restore works (very important), open few tabs, kill app, reopen app
- Test Session Restore UPGRADE (have some tabs open, upgrade the app, confirm session is restored correctly).
- Test Error Pages like 404 shows correctly.
- Test NTP shows correctly.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/SessionData.swift [hunk 1]
```diff
@@ -67,4 +67,15 @@ class SessionData: NSObject, NSSecureCoding {
     static var supportsSecureCoding: Bool {
         return true
     }
+    
+    private static func updateSessionURLs(urls: [URL]) -> [URL] {
+        return urls.compactMap { url in
+            if PrivilegedRequest.isWebServerRequest(url: url),
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/SessionData.swift:73]: nit: Maybe you can add convenience method inside  PrivilegedRequest for checking if it is Webserver request and privileged and return stripped url and use it also inside Tab class.

File: Shared/Extensions/URLExtensions.swift [hunk 2]
```diff
@@ -421,7 +429,15 @@ extension URL {
     }
 
     public var originalURLFromErrorURL: URL? {
-        let components = URLComponents(url: self, resolvingAgainstBaseURL: false)
+        var url = self
```
Comment (soner-yuksel) [inline Shared/Extensions/URLExtensions.swift:432]: Is it possible to add unit tests for `decodeReaderModeURL` and `originalURLFromErrorURL` ?

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — CHANGES_REQUESTED** [review]
blocking until we figure out session restore problems

File: Shared/Extensions/URLExtensions.swift (hunk 2 above)
Comment (Brandon-T) [reply Shared/Extensions/URLExtensions.swift:432]: Test are already tests: `testoriginalURLFromErrorURL`
If any of the tests currently fail, it means this PR is invalid because we want all the tests to still work even with the changes. That way, we know for sure we didn't break anything. It should work on iOS 13+, 14+ and 15+.

**Review by soner-yuksel — APPROVED** [review]

File: Client/Frontend/Browser/SessionRestoreHandler.swift [hunk 3]
```diff
@@ -22,6 +31,7 @@ struct SessionRestoreHandler {
 
                     let securityToken = UserScriptManager.messageHandlerToken.uuidString
                     sessionRestoreString = sessionRestoreString.replacingOccurrences(of: "%SECURITY_TOKEN%", with: securityToken, options: .literal)
+//                    sessionRestoreString = sessionRestoreString.replacingOccurrences(of: "%RESTORE_TOKEN%", with: "\(PrivilegedRequest.key)=\(PrivilegedRequest.token)", options: .literal)
```
Comment (iccub) [inline Client/Frontend/Browser/SessionRestoreHandler.swift]: can be removed?

File: Shared/PrivilegedRequest.swift [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+        let modifyURL = { (url: URL) -> URL in
+            if PrivilegedRequest.isWebServerRequest(url: url),
+               let url = PrivilegedRequest.store(url: url) {
+                return url
+            }
+            return url
+        }
+
+        super.init(url: modifyURL(URL), cachePolicy: cachePolicy, timeoutInterval: timeoutInterval)
+        setPrivileged()
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift]: I don't think we need this anymore right?

File: Shared/PrivilegedRequest.swift [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+    }
+}
+
+extension URLRequest {
+    public var isPrivileged: Bool {
+        if PrivilegedRequest.isPrivileged(url: url) {
+            return true
+        }
+
+        return URLProtocol.property(forKey: REQUEST_KEY_PRIVILEGED, in: self) != nil
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift]: remove?

File: Shared/PrivilegedRequest.swift [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+        if let value = url?.getQuery()[PrivilegedRequest.key],
+           !value.isEmpty,
+           value == PrivilegedRequest.token {
+            return true
+        }
+        return false
+    }
+
+    public static func isWebServerRequest(url: URL) -> Bool {
+        url.absoluteString.hasPrefix("http://localhost:\(AppConstants.webServerPort)/")
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift]: 1. Using `url.host` and `url.hostPort` might be more reliable here. 
2. Adding tests would be helpful.

File: Shared/PrivilegedRequest.swift [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+        super.init(url: modifyURL(URL), cachePolicy: cachePolicy, timeoutInterval: timeoutInterval)
+        setPrivileged()
+    }
+
+    required init?(coder aDecoder: NSCoder) {
+        super.init(coder: aDecoder)
+        setPrivileged()
+    }
+
+    private func setPrivileged() {
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift]: remove?

File: Shared/PrivilegedRequest.swift [hunk 8]
```diff
@@ -0,0 +1,98 @@
...
+                                         value: PrivilegedRequest.token)
+            queryItems.append(queryItem)
+        }
+
+        components.queryItems = queryItems
+        return components.url
+    }
+
+    public static func removePrivileges(url: URL) -> URL? {
+        guard var components = URLComponents(url: url, resolvingAgainstBaseURL: false),
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift:52]: I understand the reason for doing this, but there is still a possibility of leaking the `token` in logs. I don't think it happens in this PR, but URLs are often logged for debugging purposes.

What do you think about adding the key as a headers instead?

File: Shared/PrivilegedRequest.swift [hunk 9]
```diff
@@ -0,0 +1,98 @@
...
+    public static func isPrivileged(url: URL?) -> Bool {
+        if let value = url?.getQuery()[PrivilegedRequest.key],
+           !value.isEmpty,
+           value == PrivilegedRequest.token {
+            return true
+        }
+        return false
+    }
+
+    public static func isWebServerRequest(url: URL) -> Bool {
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift:72]: nit: This can be used in `init` and `isPrivileged` to avoid code duplication.

File: Client/Application/WebServer.swift [hunk 10]
```diff
@@ -86,6 +86,14 @@ class WebServer {
         if components.host == "localhost" && components.scheme == "http" {
             components.port = Int(WebServer.sharedInstance.server.port)
         }
+        
+        // If the request was privileged
+        // Update its privilege token
+        if let url = components.url,
+           PrivilegedRequest.isWebServerRequest(url: url),
+           components.valueForQuery(PrivilegedRequest.key) != nil {
```
Comment (jumde) [inline Client/Application/WebServer.swift]: This will leak the token to any request of the form `http://localhost:port/random.html?<key>=any_value`

**Review by iccub — APPROVED** [review]

File: Shared/PrivilegedRequest.swift (hunk 8 above)
Comment (Brandon-T) [reply Shared/PrivilegedRequest.swift:52]: I would, but what would we do when we call `history.go(currentPage);` in `SessionRestore.html` since I can't add headers there :(

Firefox similar: https://github.com/mozilla-mobile/firefox-ios/blob/8b1450fbeb87f1f559a2f8e42971c715dc96bcaf/Client/Frontend/Browser/PrivilegedRequest.swift#L30

But as part of a class called `InternalURL` and it adds the token to the query parameters.

File: Client/Application/WebServer.swift (hunk 10 above)
Comment (Brandon-T) [reply Client/Application/WebServer.swift]: Lucky me. This code is no longer needed as the token is handled properly in `SessionRestore.html`. I am removing it now.

File: Shared/PrivilegedRequest.swift (hunk 9 above)
Comment (Brandon-T) [reply Shared/PrivilegedRequest.swift:72]: It is used in `init` but I didn't put it in `isPrivileged` because I wasn't sure 100% if we have any non-localhost requests that are possibly `privileged`.

File: Shared/PrivilegedRequest.swift (hunk 6 above)
Comment (Brandon-T) [reply Shared/PrivilegedRequest.swift]: Fixed.

File: Shared/PrivilegedRequest.swift (hunk 9 above)
Comment (jumde) [reply Shared/PrivilegedRequest.swift:72]: All current accesses to `isPrivileged` are for localhost URLs. But, I think we can leave it as is for now and may be re-work this later.

File: Shared/PrivilegedRequest.swift [hunk 11]
```diff
@@ -0,0 +1,83 @@
...
+        components.queryItems = items.filter { $0.name != PrivilegedRequest.key }
+        if let items = components.queryItems,
+            items.isEmpty {
+            components.queryItems = nil
+        }
+        return components.url
+    }
+
+    public static func isPrivileged(url: URL?) -> Bool {
+        if let value = url?.getQuery()[PrivilegedRequest.key],
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift:64]: nit: What do you think about invoking the `removePrivileges` code here, instead of duplicating it for all `isPrivileged` checks?

**Comment by jumde** [comment]
Given the scope of changes, I think we need a detailed test plan for this PR. List of features that should be tested - 

1. Reader mode
2. Certificate errors
3. Session restore

File: Shared/PrivilegedRequest.swift [hunk 12]
```diff
@@ -0,0 +1,83 @@
+// Copyright 2021 The Brave Authors. All rights reserved.
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+
+private let REQUEST_KEY_PRIVILEGED = "privileged"
```
Comment (jumde) [inline Shared/PrivilegedRequest.swift]: remove?

**Review by jumde — APPROVED** [review]
lgtm

**Review by kylehickinson — APPROVED** [review]
