### PR TITLE
Fix #944: Show alert when trying to remove device while offline.

### LINKED ISSUE #944: Device removed when offline doesn't get removed from the sync chain
### Description: 
Device removed when offline doesn't get removed from the sync chain

### Devices
Device 1: iPhone 7+
Device 2: iPhone 6

### Steps to Reproduce 
  1. Create sync chain on device 1
  2. Sync device 2 using QR code, ensure both devices are listed in each other
  3. Put device 1 on offline mode, remove device 1 from sync chain on device 1
  4. Sync device 1 again to the sync chain by scanning QR code on device 2
  5. Both devices show device 1 twice 

**Actual result:** 
Device removed when offline doesn't get removed from the sync chain

**Expected result:**
Changes made offline should propagate when devices are online

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9 (19.02.03.15)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 1]
```diff
@@ -130,6 +135,16 @@ class SyncSettingsTableViewController: UITableViewController {
         present(actionShet, animated: true)
     }
     
+    private func showNoConnectionAlert() {
```
Comment (jhreis) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: This is directly copied from `SyncViewController` let's abstract this function and have it return a `UIAlertController`. Best not to copy.

**Review by jhreis — CHANGES_REQUESTED** [review]

**Review by jhreis — APPROVED** [review]
