### PR TITLE
Fix 3551 - Playlist performance on bad network

### LINKED ISSUE #3551: Video saving takes preference over page load
### Description: 
Video download takes preference over page load 

### Steps to Reproduce 
  1. Install 1.25(21.4.15.13)
  2. Visit a site in a new tab
  3. Visit a YT video in a second tab and add to playlist
  4. Let video download for offline play
  5. Disconnect network 
  6. Open a link in a new tab from step 2
  7. Reconnect to network
  8. Video download starts in background, page from step 6 doesn't load until offline video download is complete

**Actual result:** 
Video saving takes preference over page load 

**Expected result:**
Should not have preference 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix playlist performance on bad networks (Previously, if you download multiple items at the same time on a really bad network, the playlist UI locks up.. which means the main-thread locks up, and therefore even tabs, etc are blocked from loading and doing anything else).
- Fixed by moving everything to `willDisplayCell(forRow at:)` instead of `cellForRow(at:)` because `cellForRow(at:)` will re-configure the cell no matter what, even if it is already properly displaying and you just want to modify one thing.
- Fixed by moving callbacks to hlsQueue and fileQueue and dispatching to main only when UI needs updating.
- Fixed crash by making callbacks serial.

This pull request fixes #3551

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift [hunk 1]
```diff
@@ -86,20 +85,67 @@ public class PlaylistDownloadManager: PlaylistStreamDownloadManagerDelegate {
     }
     
     func downloadHLSAsset(_ assetUrl: URL, for item: PlaylistInfo) {
-        hlsDelegate.downloadAsset(hlsSession, assetUrl: assetUrl, for: item)
+        if Thread.current.isMainThread {
+            self.hlsDelegate.downloadAsset(self.hlsSession, assetUrl: assetUrl, for: item)
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift]: `self` not needed here

File: Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift [hunk 2]
```diff
@@ -86,20 +85,67 @@ public class PlaylistDownloadManager: PlaylistStreamDownloadManagerDelegate {
...
+                guard let self = self else { return }
+                self.hlsDelegate.downloadAsset(self.hlsSession, assetUrl: assetUrl, for: item)
+            }
+        }
     }
     
     func downloadFileAsset(_ assetUrl: URL, for item: PlaylistInfo) {
-        fileDelegate.downloadAsset(fileSession, assetUrl: assetUrl, for: item)
+        if Thread.current.isMainThread {
+            self.fileDelegate.downloadAsset(self.fileSession, assetUrl: assetUrl, for: item)
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift]: `self` not needed here

File: Client/Frontend/Browser/Playlist/Cells/PlaylistCell.swift [hunk 3]
```diff
@@ -161,8 +161,7 @@ class PlaylistCell: UITableViewCell {
             return UIEdgeInsets(top: 0, left: self.titleLabel.frame.origin.x, bottom: 0, right: 0)
         }
         
-        set (newValue) {
-            // swiftlint:disable:this unused_setter_value
+        set (newValue) { // swiftlint:disable:this unused_setter_value
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Cells/PlaylistCell.swift]: I believe we can skip `(newValue)` part, you can type `set {}` only

File: Client/Frontend/Browser/Playlist/PlaylistToast.swift [hunk 4]
```diff
@@ -146,6 +146,16 @@ class PlaylistToast: Toast {
             $0.contentEdgeInsets = UIEdgeInsets(top: 10.0, left: 10.0, bottom: 10.0, right: 20.0)
             $0.titleEdgeInsets = UIEdgeInsets(top: 0.0, left: 10.0, bottom: 0.0, right: -10.0)
             
+            let colors = [#colorLiteral(red: 0.4352941176, green: 0.2980392157, blue: 0.8235294118, alpha: 1), #colorLiteral(red: 0.7490196078, green: 0.07843137255, blue: 0.6352941176, alpha: 1), #colorLiteral(red: 0.968627451, green: 0.2274509804, blue: 0.1098039216, alpha: 1)]
+            let gradientView = GradientView(colors: colors,
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/PlaylistToast.swift]: This seem to be code from your previous gradient PR, can you make sure you work on development branch?
Or merge the gradient branch first then rebase

**Review by iccub — CHANGES_REQUESTED** [review]
Look nice, many small improvements

Please merge Gradient PR and rebase this, or rebase this on dev to not include Gradient code in this pull request

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift [hunk 5]
```diff
@@ -86,20 +85,67 @@ public class PlaylistDownloadManager: PlaylistStreamDownloadManagerDelegate {
...
     }
     
     func cancelDownload(item: PlaylistInfo) {
-        hlsDelegate.cancelDownload(item: item)
-        fileDelegate.cancelDownload(item: item)
+        if Thread.current.isMainThread {
+            hlsDelegate.cancelDownload(item: item)
+            fileDelegate.cancelDownload(item: item)
+        } else {
+            hlsQueue.addOperation { [weak self] in
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift:114]: For canceling the operation cant we just force it to run on main thread directly ?

File: Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift [hunk 6]
```diff
@@ -364,7 +414,9 @@ private class PlaylistFileDownloadManager: NSObject, URLSessionDownloadDelegate
         activeDownloadTasks[task] = MediaDownloadTask(id: item.pageSrc, name: item.name, asset: asset)
         task.resume()
         
-        delegate?.onDownloadStateChanged(streamDownloader: self, id: item.pageSrc, state: .inProgress, displayName: asset.displayNames(for: asset.preferredMediaSelection), error: nil)
+        DispatchQueue.main.async {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift:417]: For sake of synchronization can you also use `ensureMainThread` here. Also there couple of them above ^

**Review by soner-yuksel — APPROVED** [review]
LGTM

File: Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift (hunk 5 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift:114]: It is ran on main-thread only atm. This is only if there is a different thread (IE: I left it there for when debugging performance issues on separate threads).

File: Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift (hunk 6 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift:417]: I don't want `ensureMainThread` because I need it `Dispatch` at a later time. Calling `ensureMainThread` does NOT guarantee an `async` dispatch. It only guarantees that it is either ran on main thread synchronously OR async depending on the calling context.

This is why I have it as `DispatchQueue.main.async`
