### PR TITLE
Fix #5662: Full text not shown on button in search promo in some non-US languages (iOS 14)

### LINKED ISSUE #5662: Full text not shown on button in search promo in some non-US languages (iOS 14)
### Description: 
Full text not shown on button in search promo, specifically in Polish where there would be more characters (iOS 14)

iOS 15 | iOS 14
-|-
IMG_3224 | IMG_2728

### Steps to Reproduce 

Precondition: Set language to Polish (Polski)

  1. Clean install 
  2. Set default search engine to anything other than brave search
  3. Restart the app 
  4. Search for something in the URL box
  5. Observe search promo

**Actual result:** 
Button text doesn't encompass the whole description

**Expected result:**
Should show full description (3 words in polish, see above picture)

**Brave Version:** 
1.40.1 (22.7.5.21)

**Device details:** 
iPhone iOS 14

### PR DESCRIPTION
**Pull request by soner-yuksel**
Changes made to Promotion cell to show full text in buttons for long text languages etc

## Summary of Changes

This pull request fixes #5662 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

1. Precondition: Set language to Polish (Polski)
2. Clean install
3. Set default search engine to anything other than brave search
4. Restart the app
5. Search for something in the URL box

## Screenshots:
Screen Shot 2022-07-11 at 3 30 30 PM

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift [hunk 1]
```diff
@@ -9,8 +9,9 @@ import BraveUI
 import BraveShared
 
 class BraveSearchPromotionCell: UITableViewCell {
-  
-  struct UX {
+  private struct DesignUX {
+    static let paddingX: CGFloat = 15.0
+    static let paddingY: CGFloat = 10.0
```
Comment (iccub) [inline Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift:14]: `CGFloat` type declaration can be skipped now if I remember correctly

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Search/BraveSearchPromotionCell.swift:14]: yeap at https://github.com/brave/brave-ios/pull/5678/commits/88ddc0b1c93d257d766916c23cb4d1dd0423a6fd
