### PR TITLE
Fix #2177: Sort custom tipping amounts from least to greatest BAT amount

### LINKED ISSUE #2177: publisher set custom tip amounts display out of order on banner
### Description: 
When you open the tip banner for a verified publisher with custom tip amounts set, the tip amounts don't display from least to greatest (i.e. 5 BAT, 10 BAT, 20 BAT). They display mixed up.

However, if the publisher doesn't have custom tip amounts set, then the tip amounts display in order from least to greatest.

### Steps to Reproduce 
Below sites referenced are on Prod, if you need staging examples msg @LaurenWags 
  1. Have Rewards enabled
  2. Visit a verified publisher without custom tip amounts set (ex. basicattentiontoken.org) and open tip banner
  3. See tip amounts in order 1 BAT, 5 BAT, 10 BAT.
  4. Visit a verified publisher with custom tip amounts set (ex. github.com/feross or rebron.org)

**Actual result:** 
Tip amounts displayed out of order:
IMG_7E3C83FD2ED7-1

IMG_D6548E368495-1

**Expected result:**
tip amounts to be in order (least to greatest) when going left to right on the buttons:
IMG_C9E0CE394F14-1

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily for custom tip amounts

**Brave Version:** 
1.14.2 and 1.15

**Device details:** 
iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes issue #2177 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

Simulator Screen Shot - iPhone 11 Pro - 2020-01-10 at 15 45 38

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Tipping/TippingViewController.swift [hunk 1]
```diff
@@ -132,7 +132,9 @@ class TippingViewController: UIViewController, UIViewControllerTransitioningDele
       
       self.tippingView.overviewView.disclaimerView.isHidden = banner.status == .verified
       
-      let bannerAmounts = banner.amounts.isEmpty ? TippingViewController.defaultTippingAmounts : banner.amounts.compactMap({ $0.doubleValue })
+      let bannerAmounts = banner.amounts.isEmpty ?
+        TippingViewController.defaultTippingAmounts :
+        banner.amounts.compactMap({ $0.doubleValue }).sorted(by: <)
```
Comment (iccub) [inline BraveRewardsUI/Tipping/TippingViewController.swift]: nitpick: round brackets surrounding `({ $0.doubleValue })` are not needed

**Review by iccub — APPROVED** [review]

**Review by iccub — APPROVED** [review]
