### PR TITLE
Fix #7059: Don't show Brave News reload button on RSS-only feed

### LINKED ISSUE #7059: In an RSS-only Brave News state, the "New Content Available" button comes up every time NTP is viewed
### Description: 

The purple "New Content Available" button shows up every time you come back from visiting a link in a RSS-only feed

### Steps to Reproduce 
  1. Enable Brave News and unfollow Top Sources (and any other sources you're following)
  2. Follow an RSS feed of your choosing (replicated with Daring Fireball: `https://daringfireball.net/feeds/main`)
  3. Visit an RSS feed's link
  4. Click the back button to go back to NTP/Brave News

### Actual result:
The "New Content Available" button appears every time

### Expected result:
It should not appear unless the sources expire (24 hours) or you edit your sources

### Reproduces how often:
Easily

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #7059 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/WebFilters/AdblockRustEngine.swift [hunk 1]
```diff
@@ -30,7 +30,6 @@ extension AdblockEngine {
     }
     
     guard let requestHost = requestURL.host, let sourceHost = sourceURL.host else {
-      assertionFailure("You must provide absolute paths for `requestURL` and `sourceURL`")
```
Comment (kylehickinson) [inline Sources/Brave/WebFilters/AdblockRustEngine.swift:33]: Unrelated, but as discussed in Slack https://bravesoftware.slack.com/archives/GB9CJGQV6/p1677704768849219

**Review by iccub — APPROVED** [review]
