### PR TITLE
Fix #1828: DataControllerTests failing intermittently.

### LINKED ISSUE #1828: DataControllerTests failing intermittently on Travis
### Steps to Reproduce 
  1. Observe CI on travis

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
Please do not merge until 1.13 lands :) still not 1000% sure it's fixed 

This pull request fixes issue #1828 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: DataTests/DataControllerTests.swift [hunk 1]
```diff
@@ -88,8 +82,10 @@ class DataControllerTests: CoreDataTestCase {
     }
     
     func testNoChangesContext() {
-        DataController.perform { context in
-            // Do nothing
+        backgroundSaveAndWaitForExpectation(inverted: true) {
+            DataController.perform { context in
```
Comment (iccub) [inline DataTests/DataControllerTests.swift:86]: This closure was leaking to other tests causing

```
'NSInvalidArgumentException', reason: 'Object's persistent store is not reachable from this NSManagedObjectContext's coordinator'
```

now it's wrapped in 1 second inverted expectation which should help

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
@iccub This good to go?

**Comment by iccub** [comment]
yes, let's try it @kylehickinson
