### PR TITLE
Fixed #515 for case of entering PBM from inside a normal tab

### LINKED ISSUE #515: Link opened in PT shows incorrect tab count
### Description: 
Link opened in PT shows incorrect tab count 

### Steps to Reproduce 
  1. Open 3 tabs in normal mode and visit a site in each of them
  2. Long press on a link and open in a private tab
  3. Private tab container shows tab count as 4 where its only one tab. Also shows tabs bar for the single tab which has the horrible gradient effect at the end
  4. Open tab container in private mode and switch back to tab, count shows correct and tabs bar is gone 

**Actual result:** 
https://drive.google.com/open?id=1k6vidnOyrZVgXRO7gZL6IaRXlqx5OfEE

**Expected result:**
Tab count should only be for private tabs and not all tabs from normal mode as well

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easy

**Brave Version:** 
1.7(18.11.30.3)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by danishjafri88**
No check was in place to see if the new private tab was opened from a normal tab link
Hence a check was put in place

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -780,7 +780,13 @@ class BrowserViewController: UIViewController {
         }
         
         func shouldShowTabBar() -> Bool {
-            let tabCount = tabManager.tabsForCurrentMode.count
+            let tabCount: Int
+            if !PrivateBrowsingManager.shared.isPrivateBrowsing && tabManager.selectedTab?.isPrivate == true {
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift]: Why is `tabsForCurrentMode` not returning the correct data? Is this happening too soon? Then we should probably find a way to fix the timing. This feels pretty hacky.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: Changed the implementation to setting the mode at source.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -2366,6 +2366,7 @@ extension BrowserViewController: ContextMenuHelperDelegate {
             let tabType = currentTab.type
 
             let addTab = { (rURL: URL, isPrivate: Bool) in
+                PrivateBrowsingManager.shared.isPrivateBrowsing = isPrivate
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift]: Where is this currently being handled?

Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: Not handled anywhere

File: Client/Frontend/Browser/TabManager.swift [hunk 3]
```diff
@@ -193,7 +193,10 @@ class TabManager: NSObject {
         if previous === tab {
             return
         }
-
+        // Convert the global mode to private if opening private tab from normal tab/ history/bookmark.
+        if selectedTab?.isPrivate == false && tab?.isPrivate == true {
+            PrivateBrowsingManager.shared.isPrivateBrowsing = true
```
Comment (jhreis) [inline Client/Frontend/Browser/TabManager.swift:198]: Does this ever get turned back off?

Comment (danishjafri88) [reply Client/Frontend/Browser/TabManager.swift:198]: When in private mode the only way you can go back to normal is by tab tray. When you switch mode from tab tray it resets this value.

Comment (jhreis) [reply Client/Frontend/Browser/TabManager.swift:198]: Oh I see, I thought previously you said this wasn't used anywhere, but just not in all instances of getting into private mode.

**Review by jhreis — APPROVED** [review]
