### PR TITLE
Fix #3600 - Stop Picture-In-Picture on playback end

### LINKED ISSUE #3600: Auto close PiP player when playback ends
### Description: 
Auto close PiP player when playback ends

### Steps to Reproduce 
  1. Add a single video to playlist
  2. Background the app so video continues to play in PiP mode
  3. Wait for the video to be over, PiP is still shown

**Actual result:** 

**Expected result:**
Close the player when video playback stops

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.28.19)

**Device details:** 
iPad/iPhone (iOS 14.x)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Stop Picture-In-Picture when the last video has finished playing and there is no active repeat mode.

This pull request fixes #3600

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/PlaylistViewController.swift [hunk 1]
```diff
@@ -209,9 +209,16 @@ private class ListController: UIViewController {
...
         }
         
-        playerView.stop()
         playerView.pictureInPictureController?.delegate = nil
         playerView.pictureInPictureController?.stopPictureInPicture()
+        playerView.stop()
+        
+        if let delegate = UIApplication.shared.delegate as? AppDelegate {
+            if UIDevice.isIpad {
+                playerView.attachLayer()
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/PlaylistViewController.swift:218]: Curious why are we adding player layer back If it is an iPad?

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — APPROVED** [review]
