### PR TITLE
Fix #7116: Fix favicon flickering and rendering large

### LINKED ISSUE #7116: Favicon flickers sometimes when rendering in History Search
### Description: 
- When searching history, favicons flicker

### Steps to Reproduce 
  1. Open History
  2. Search for any existing history

### Actual result: 
- Favicon flickers

### Expected result:
- Favicon should render immediately

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 

- 1.48.x

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Some Favicons that are too large such as Twitter (Twitter has a favicon of 1024 x 1024).
- Max favicon size is now 256x256 (scaled down) and a minimum of 64x64 (scaled up). 
   Anything else is rendered as is.
- Fixed fetching favicons from cache immediately instead of waiting on the `Task` to do it. 
   Tasks are too slow and will display the result on the next render queue causing flickering. 
   So we fetch it immediately if it exists already.

This pull request fixes #7116

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Favicon/FaviconFetcher.swift [hunk 1]
```diff
@@ -90,8 +90,12 @@ public class FaviconFetcher {
     return favicon
   }
   
+  /// Retrieves a Favicon from the cache
+  public static func getIcon(for url: URL) -> Favicon? {
```
Comment (iccub) [inline Sources/Favicon/FaviconFetcher.swift]: Is this method name clear enough? How do we know when to use `getIcon` vs `loadIcon` for example?

Comment (Brandon-T) [reply Sources/Favicon/FaviconFetcher.swift]: Changed. I thought it was clear enough I guess, with the additional comment. But changed it to `getIconFromCache` so it should be clear enough now.

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — APPROVED** [review]
