### PR TITLE
Fix #7657 - #7656: Local Authentication Changes and Bug Fixes

### LINKED ISSUE #7656: There is no way to close "Unlock" screen with a device gesture or back button
### Description: 

There is no way to close `Unlock` screen with a device gesture or back button

### Preconditions
- Make sure device unlock is enabled. You can enable `PIN` option.
- `Sync` is already enabled

### Steps to Reproduce 
  1. Launch Brave > Tree-dot menu > Settings
  2. Sync > Observe `PIN` screen to unlock the device
  3. Tap `Cancel` > Try to go back to a previous Settings screen > Observe that the gesture is not working 
  4. The other way to repro it > Go to `Logins & Passwords` in Brave settings
  5. Tap on any saved account > Tap `Password` > Reveal or Copy > Cancel PIN unlock > Observe the same issue

### Actual result: 

There is no way to close "Unlock" screen with a device gesture if the user chooses to cancel the device unlock. There is no back button on the UI as well. The only way to hide that `Unlock` screen is to close/hide and open Brave again.

https://github.com/brave/brave-ios/assets/128532965/1d8edec0-ef70-43f2-b06f-e26a0f113e66

### Expected result:

The user must be able to return to a previous menu from `Unlock` screen without leaving/closing/hiding Brave.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Version: 1.52 (23.6.28.13)
BraveCore: 1.52.129 (114.0.5735.198)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 16.5]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #7657: Landing on the wrong screen after unlocking is done
### Description: 

Landing on the wrong screen after unlocking is done

### Preconditions
- Make sure device unlock is enabled. You can enable `PIN` option.
- `Sync` is already enabled

### Steps to Reproduce 
  1. Launch Brave > Tree-dot menu > Settings
  2. Sync > Observe `PIN` screen to unlock the device
  3. Tap `Cancel` > Tap `Unlock` again
  4. Enter correct PIN > Observe

### Actual result: 

- The user is landing on `Settings` screen instead of `Sync` screen if canceling the first attempt to unlock the device and then trying to unlock it again. 
- The same issue was observed for `Logins & Password` screen where the user landed on a previous screen.

https://github.com/brave/brave-ios/assets/128532965/24c635f6-b507-469d-8301-55f527540c9f

### Expected result:

- The user must land on `Sync` screen when unlocking the device by going to `Sync` settings.
- The user must be able to `copy` or `reveal` the saved password when unlocking the device by going to `Saved passwords` settings.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.52 (23.6.28.13)
BraveCore: 1.52.129 (114.0.5735.198)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 16.5]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
This PR is adding unlock capability to local authentication and in addition to cancel ability the dismiss logic after unlocking and cancel to unlock is added for variety of screens.

## Summary of Changes

This pull request fixes #7656
This pull request fixes #7657

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Test1:
1. Launch Brave > Tree-dot menu > Settings
2. Sync > Observe PIN screen to unlock the device
3. Tap Cancel > Tap Unlock again
4. Enter correct PIN > Observe

Test2:
1. Launch Brave > Tree-dot menu > Settings
2. Sync > Observe PIN screen to unlock the device
3. Tap Cancel > Try to go back to a previous Settings screen > Observe that the gesture is not working
4. The other way to repro it > Go to Logins & Passwords in Brave settings
5. Tap on any saved account > Tap edit bar button > Cancel PIN unlock > Observe the dismiss

## Screenshots:

https://github.com/brave/brave-ios/assets/6643505/8265bb32-c507-48bd-bd75-b21dd811e4d6

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Passcode/WindowProtection.swift [hunk 1]
```diff
@@ -77,6 +95,20 @@ public class WindowProtection {
     return true
   }
 
+  var isCancallable: Bool = false {
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Passcode/WindowProtection.swift]: typo: `isCancallable` → `isCancellable`

File: Sources/Brave/Frontend/Passcode/WindowProtection.swift [hunk 2]
```diff
@@ -46,6 +56,14 @@ public class WindowProtection {
         $0.width.greaterThanOrEqualTo(230)
         $0.top.equalTo(lockImageView.snp.bottom).offset(60)
       }
+      cancelButton.snp.makeConstraints {
+        $0.leading.greaterThanOrEqualToSuperview().offset(20)
+        $0.trailing.lessThanOrEqualToSuperview().offset(20)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Passcode/WindowProtection.swift]: This should be `inset(20)` or `offset(-20)`

**Review by stoletheminerals — APPROVED** [review]

File: Sources/Brave/Frontend/Passcode/WindowProtection.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Passcode/WindowProtection.swift]: Fix at https://github.com/brave/brave-ios/pull/7682/commits/a54c0d94342d4d059d483c41c660bd7c4db76bcb

File: Sources/Brave/Frontend/Passcode/WindowProtection.swift (hunk 2 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Passcode/WindowProtection.swift]: Fix at https://github.com/brave/brave-ios/pull/7682/commits/a54c0d94342d4d059d483c41c660bd7c4db76bcb

**Review by kylehickinson — APPROVED** [review]
