### PR TITLE
Fix: #1129 Disable Auto-Play Toggle added.

### LINKED ISSUE #1129: Disable video autoplay on iOS?
### Description: 

I followed a link to this site from a thread on Apple's support forums, saying this browser allows disabling video autoplay on iOS. I've been experimenting with the browser on my iPhone for a while now but cannot find a way to set autoplay to off. Videos play automatically on the sites I tried (e.g., cnn.com). I searched the wiki and the issues page but the word "autoplay" doesn't bring up any results. Please help a newbie.

### Steps to Reproduce 
  1. Go to a CNN story that contains video

Thanks!

### PR DESCRIPTION
**Pull request by Brandon-T**
- Disable Auto-Play Toggle added.
- Fixes: https://github.com/brave/brave-ios/issues/1129

URLs to test:

https://www.cnn.com/2019/08/10/europe/russia-jet-propulsion-blast-radiation-intl/index.html
https://videojs.github.io/autoplay-tests/plain/attr/autoplay.html
https://videojs.github.io/autoplay-tests/

URLs known for auto-play 100% of the time:
https://www.youtube.com/watch?v=JASUsVY5YJ8

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/TabManager.swift [hunk 1]
```diff
@@ -1082,6 +1084,9 @@ extension TabManager: PreferencesObserver {
             }
             // The default tab configurations also need to change.
             configuration.preferences.javaScriptCanOpenWindowsAutomatically = allowPopups
+        case Preferences.General.mediaAutoPlays.key:
+            let allowsMediaAutoPlay = Preferences.General.mediaAutoPlays.value
+            configuration.mediaTypesRequiringUserActionForPlayback = allowsMediaAutoPlay ? [] : .all
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabManager.swift]: Do we need to update all the current tabs? (see blockPopups update above)

**Review by iccub — CHANGES_REQUESTED** [review]
Provide a url or two for QA in test steps.

Code looks good overall :)

File: Client/Frontend/Browser/TabManager.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/TabManager.swift]: @kylehickinson  We can't change WKWebViewConfiguration after the web-view has been created :( I originally had the code there to do it but it made no difference and then I realized you can't change WKWebViewConfiguration and the Apple-docs state that it's only used during init lol.

Comment (kylehickinson) [reply Client/Frontend/Browser/TabManager.swift]: Ah, so we'd have to destroy all web views on change if we wanted that to fix current tabs? Same as cookie control I guess, probably not worth it? @iccub What do you think?

Comment (iccub) [reply Client/Frontend/Browser/TabManager.swift]: I think we should recreate all web views, we do that already for another preference `blockAllCookies`

See here https://github.com/brave/brave-ios/blob/development/Client/Frontend/Browser/BrowserViewController.swift#L3026

Comment (Brandon-T) [reply Client/Frontend/Browser/TabManager.swift]: @iccub @kylehickinson 

Hmm but why re-create all of them for `auto-play`? I mean, I have no problem doing it, I just don't understand why we want to do that.

If the user wants to play the video, they'd tap it no?
I ask because in the future this MIGHT affect background play. If I reload all tabs in the background and each tab starts playing it will be really weird..

Are we sure?

**EDIT:**

Done.

Comment (iccub) [reply Client/Frontend/Browser/TabManager.swift]: It's a minor thing so not recreating it is fine too :) especially if you predict unexpected behavior in the future

Comment (kylehickinson) [reply Client/Frontend/Browser/TabManager.swift]: FYI we don't need to reload all the tabs, just destroy their web views so that the next time they are opened they will reload automatically (IIRC)

Comment (Brandon-T) [reply Client/Frontend/Browser/TabManager.swift]: @kylehickinson I tried that. They don't reload automatically unless you call `loadRequest request`

File: Client/Frontend/Browser/Tab.swift [hunk 2]
```diff
@@ -197,6 +197,8 @@ class Tab: NSObject {
             configuration!.allowsInlineMediaPlayback = true
             // Enables Zoom in website by ignoring their javascript based viewport Scale limits.
             configuration!.ignoresViewportScaleLimits = true
+            // Enables media auto-play based on the current preference setting (default is false)
+            configuration!.mediaTypesRequiringUserActionForPlayback = Preferences.General.mediaAutoPlays.value ? [] : .all
```
Comment (danishjafri88) [inline Client/Frontend/Browser/Tab.swift]: Doing this here is not required, since this is set in `getNewConfiguration()`

File: Client/Frontend/Browser/TabManager.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/TabManager.swift]: @Brandon-T Doing this here is not required since you are doing `reset()` below

**Review by danishjafri88 — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/TabManager.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/TabManager.swift]: @kylehickinson I fixed it. It will lazy reload now. Only the selected tab reloads and other tabs will reload only when you tap on them.

**Review by iccub — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
