### PR TITLE
Fix #1746 - Show confirmation screen without delay on OnboardingAds.

### LINKED ISSUE #1746: Update Onboarding "My First Ad" screen to show start browsing after 1s delay
### Description: 
Joining rewards triggers sample ad notification and then waits for 8secs with the counter at 0. It gives a feeling that the onboarding is stuck. We should consider reducing the wait time before showing the `Start Browsing` button. 

### Steps to Reproduce 
  1. Go through onboarding flow

**Actual result:** 
FilefromiOS

**Expected result:**
No UI stall making it look like its stuck without visual feedback

## Affected User Flows

Note the final flow "1s delay". This makes the final screen display after a 1s delay regardless of the "My First Ad" auto-dismissing after 3s

### New user, In ad region

user flow - ios onboarding ads available

### Existing user, in ad region

user flow - ios onboarding existing user in ad region

### (Future case) Existing user, BR on, ad becomes available in the region

user flow - ios onboarding BR on notify ads

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

This pull request fixes issue https://github.com/brave/brave-ios/issues/1746

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift [hunk 1]
```diff
@@ -43,11 +43,12 @@ class OnboardingAdsCountdownViewController: OnboardingViewController, UNUserNoti
         contentView.resetAnimation()
         contentView.animate(from: 0.0, to: 1.0, duration: UX.animationTime) { [weak self] in
             guard let self = self else { return }
+            
+            //Show the confirmation screen no matter what..
+            self.contentView.setState(.finished)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift]: I thought this is supposed to be after a 1s delay?

Comment (Brandon-T) [reply Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift]: So it won't right after the animation?

Comment (kylehickinson) [reply Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift]: As seen in ticket, all the flows which show ads countdown have "1 second delay":

File: Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift [hunk 2]
```diff
@@ -44,8 +44,10 @@ class OnboardingAdsCountdownViewController: OnboardingViewController, UNUserNoti
         contentView.animate(from: 0.0, to: 1.0, duration: UX.animationTime) { [weak self] in
             guard let self = self else { return }
             
-            //Show the confirmation screen no matter what..
-            self.contentView.setState(.finished)
+            //Show the confirmation screen no matter what.. after 1 second delay
+            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
+                self.contentView.setState(.finished)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift:49]: What happens if the user taps/dismisses the ad before this executes?

File: Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift]: Hmm but this ticket doesn't make sense.. I can show it 1 second after the animation is complete, but you don't even notice this 1s at all because it's so fast so it's going to flash/flicker.

What happens when the user decides to press BOTH the ad notification AND the button at the same time which can happen because the screen is multi-touch..

In any case, I added the 1s delay after the animation is complete.

Comment (kylehickinson) [reply Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift]: If that's the case, it's up to you to inform @karenkliu, showing her what it looks like in both scenarios and get a final decision and update the flows/spec if it changes, otherwise QA will just test based on spec and re-open ticket if it doesn't have the delay

File: Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift:49]: Race Condition?

Honestly, I have no idea what "should" happen. What does happen though, is that if you tap "Start Browsing" it goes straight to the browser. If you tap the ad, it goes straight to the browser with a new tab.

Likewise what should happen when they tap both at the same time (as per previous comment)?

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift (hunk 2 above)
Comment (karenkliu) [reply Client/Frontend/Browser/Onboarding/OnboardingAdsCountdownViewController.swift:49]: @kylehickinson @Brandon-T 
If you tap "Start Browsing", it should go straight to the browser.
If you tap the ad, it should go straight to the browser with a new tab opened to www.brave.com/my-first-ad/

It is not possible to "tap both at the same time" because either action will remove the possibility of performing the other action.
