### PR TITLE
Fix #2041 - Session storage not clearing when toggling the PBO switch.

### LINKED ISSUE #2041: Session is retained when PBO is setting is toggled [Follow up to 1987]
### Description: 
Session is retained when PBO is setting is toggled [Follow up to #1987]

### Steps to Reproduce 
  1. Login to a site in a normal tab
  2. Enable PBO from settings, do not click on done
  3. Turn off PBO, switches to a new normal tab
  4. Visit the site from step 1, the session is restored

**Actual result:** 
sessions_ios

**Expected result:**
Should clear session when the user hits ok on the alert.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.27.14)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes session storage not being cleared due to a race-condition in WKWebsiteDataStore. 
- Also added a popup UI to block the user from toggling the switch back & forth until the data has actually been cleared.

This pull request fixes issue #2041

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

STR in the ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -3395,8 +3395,22 @@ extension BrowserViewController: PreferencesObserver {
                 
                 // Clear ALL data when going from normal mode to private
                 // The other way around is handled in `removeTab`
-                let clearables: [Clearable] = [CookiesAndCacheClearable()]
-                _ = ClearPrivateDataTableViewController.clearPrivateData(clearables)
+                
+                let alert = UIAlertController(title: "Privacy", message: "Clearing session.. Please Wait..", preferredStyle: .alert)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: These will need to be localized. Also do we really need to do a popup? Seems a bit overkill 😅

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -3395,8 +3395,22 @@ extension BrowserViewController: PreferencesObserver {
...
+                
+                //If I don't dispatch after, the WKWebsiteDataStore has no time to sync its process.
+                //This is a bug in WebKit itself. If this isn't done, data is NOT cleared!
+                DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
+                    let clearables: [Clearable] = [CookiesAndCacheClearable()]
+                    ClearPrivateDataTableViewController.clearPrivateData(clearables).uponQueue(.main) { [weak self] in
+                        alert.dismiss(animated: true, completion: nil)
+                        
+                        guard let self = self else { return }
+                        self.tabManager.removeAll()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Do we need to do this again? Its done up at line 3393 just before showing the alert

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -3395,8 +3395,22 @@ extension BrowserViewController: PreferencesObserver {
...
+                        self.tabManager.reset()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Same as above (though above we do `resetConfiguration`)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift]: Hmm, we probably don't need the popup but I don't know of a better way to block the user from spamming the switch unlimited..

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: What if we just disabled the switch until it finishes?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -3583,7 +3583,7 @@ extension BrowserViewController: PreferencesObserver {
                 }
                 
                 group.wait(timeout: .now() + 10.0)
-            }
+            }*/
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Commented region can be removed

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
