### PR TITLE
Fix #6675: Both reveal and copy password actions should prompt for authentication

### LINKED ISSUE #6675: Both reveal and copy password actions should prompt for authentication
### Description: 
See https://community.brave.com/t/passwords-stored-in-brave-are-not-private/457682/6

### Steps to Reproduce 
1. Open Brave
2. Open the Settings menu
3. Under “Security”, you will find “Logins & Passwords”
4. Tap on any login.
5. Note that when you click “reveal” on the password, it prompts you for Face ID, Touch ID, or a system password
6. When tapping on “copy”, there is no authentication or verification and it simply copied the password to your clipboard.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
Securing password copy in case password is not revealed stage for additional security

## Summary of Changes

This pull request fixes #6675

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

- Save a login credential (any)
- Go Settings - Logins & Password
- Go Password Details
- Click password for actions

While Password Reveal is not activate action cop ask authentication in that stage

## Screenshots:

https://user-images.githubusercontent.com/6643505/210639266-e6115ded-b69f-4aae-8053-bf3ff0668bde.mov

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Login/LoginInfoViewController.swift [hunk 1]
```diff
@@ -417,7 +417,27 @@ extension LoginInfoViewController: LoginInfoTableViewCellDelegate {
...
   }
+  
+  func didSelectCopyWebsite(_ cell: LoginInfoTableViewCell, authenticationRequired: Bool) {
+    func addPasswordToPasteBoardWithExpiry() {
+      let expireDate = Date().addingTimeInterval(5.minutes)
 
+      UIPasteboard.general.setItems(
+        [[UIPasteboard.typeAutomatic: cell.descriptionTextField.text ?? ""]],
+        options: [UIPasteboard.OptionsKey.expirationDate: expireDate])
+    }
```
Comment (kylehickinson) [inline Client/Frontend/Login/LoginInfoViewController.swift:428]: We should probably switch this to use our convenience method [`setSecureString(_:expirationDate:)`](https://github.com/brave/brave-ios/blob/41ddb78f1dd31a675d9d01ea969f115f8a911065/Sources/BraveWallet/Extensions/UIPasteboardExtensions.swift#L14) in a future PR (we'd have to move it out of BraveWallet first)

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Login/LoginInfoViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Login/LoginInfoViewController.swift:428]: Sounds good, I will keep in mind.
