### PR TITLE
Fix #1908: Correct message for claiming ads earning view.

### LINKED ISSUE #1908: Incorrect message for ads grant in rewards panel
### Description: 
Incorrect message for ads grant in rewards panel

### Steps to Reproduce 
  1. Wait for ads grant to show up
  2. Got to settings 

**Actual result:** 
image

**Expected result:**
Similar to desktop 
image

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.5.20)

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
Note: Sriram marked this ticket for 1.14, if we want to get it in along with other more important tickets to 1.13 the milestone needs to be updated.

This pull request fixes issue #1908 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Settings/Grants/SettingsGrantSectionView.swift [hunk 1]
```diff
@@ -50,10 +50,11 @@ class SettingsGrantSectionView: SettingsSectionView {
     switch type {
     case .ads(let amount):
       iconImageView.image = UIImage(frameworkResourceNamed: "icn-ads")
+      
       if let amount = amount {
-        textLabel.text = String(format: Strings.SettingsAdsGrantText, "\(amount) \(Strings.BAT) ")
+        textLabel.text = "\(amount) \(Strings.BAT) " + Strings.SettingsAdsGrantText
       } else {
-        textLabel.text = Strings.SettingsAdsGrantText
+        textLabel.text = Strings.NotificationEarningsClaimDefault
```
Comment (iccub) [inline BraveRewardsUI/Settings/Grants/SettingsGrantSectionView.swift:57]: fallbacks to `Your rewards from Ads are here!` if no amount is provided

File: BraveRewardsUI/Settings/Grants/SettingsGrantSectionView.swift [hunk 2]
```diff
@@ -50,10 +50,11 @@ class SettingsGrantSectionView: SettingsSectionView {
     switch type {
     case .ads(let amount):
       iconImageView.image = UIImage(frameworkResourceNamed: "icn-ads")
+      
       if let amount = amount {
-        textLabel.text = String(format: Strings.SettingsAdsGrantText, "\(amount) \(Strings.BAT) ")
+        textLabel.text = "\(amount) \(Strings.BAT) " + Strings.SettingsAdsGrantText
```
Comment (iccub) [inline BraveRewardsUI/Settings/Grants/SettingsGrantSectionView.swift]: This string is not formatted, there is a chance that it may not  sound correctly for all languages, we could always fall back to using the `NotificationEarningsClaimDefault` for all cases

Comment (kylehickinson) [inline BraveRewardsUI/Settings/Grants/SettingsGrantSectionView.swift]: Can we just add this to the string formatter like so:
`"\(amount) \(Strings.BAT) \(Strings.SettingsAdsGrantText)"`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Probably block on merging until 1.13 has officially been submitted?

**Comment by iccub** [comment]
yep, don't merge if this isnt going into 1.13
