### PR TITLE
Fix #5537: Wallet panel loading state

### LINKED ISSUE #5537: Wallet panel shows onboarding before any other state
### Description: 
Reported to typically occur on Polygon network, most times when tapping the wallet icon in the URL bar the onboarding state is shown on the panel briefly before the locked/unlocked states. Sometimes it shows onboarding long enough that user can tap on button to trigger onboarding when the wallet is already setup, getting into a weird state

### Steps to Reproduce 
  1. Use dapp on polygon network
  2. Tap wallet icon

**Actual result:** 

Onboarding is shown

**Expected result:**

Loading state / don't show onboarding

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

I'm unable to reproduce / visually see this one myself, but can see in layout logs we show onboarding for 2 layout passes. A loading state should resolve this.

More info / report video:
https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1655318011732479

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Restore `visibleScreen: VisisbleScreen` property to be a computed property, so we don't rely on `keyringStore.keyring` changing after the view is created. 

This pull request fixes #5537

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Hard to reproduce reliably with known `WalletStore` leaks resolved. This bug can occur when the keyring store fetches the default keyring prior to the Wallet Panel View, so the `.onChange(of: keyringStore.keyring)` doesn't fire because the keyring didn't change after setting up the observation.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

File: BraveWallet/Panels/WalletPanelView.swift [hunk 1]
```diff
@@ -33,7 +33,19 @@ public struct WalletPanelContainerView: View {
     case unlock
   }
 
-  @State private var visibleScreen: VisibleScreen = .loading
+  private var visibleScreen: VisibleScreen {
```
Comment (nuo-xu) [inline BraveWallet/Panels/WalletPanelView.swift:36]: just want make srue you dont want this to be a @State property anymore? i guess you dont need it anymore cuz you are listening the change for `keyringStore.keyring`.

Comment (StephenHeaps) [reply BraveWallet/Panels/WalletPanelView.swift:36]: Yeah, it was only made to `@State` so I could preserve the animation when locking the wallet, but this caused some other issues, ex. when `WalletStore` leaks we can get stuck in loading state because the `keyringStore.keyring` never changes, so the `onChange(of:)` doesn't fire.

**Review by nuo-xu — APPROVED** [review]
