### PR TITLE
Fix #2314: Crash with TabsButton setup.

### LINKED ISSUE #2314: Crash when tabs button is initialized
### Description: 
Tabs Button crashes sometimes

### Steps to Reproduce 
  1. Hard to repro

**Actual result:** 

Zrzut ekranu 2020-02-10 o 20 55 23

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes issue #2314 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Widgets/TabsButton.swift [hunk 1]
```diff
@@ -118,6 +113,7 @@ extension TabsButton: Themeable {
         
         textColor = top ? theme.colors.tints.header : theme.colors.tints.footer
```
Comment (iccub) [inline Client/Frontend/Widgets/TabsButton.swift:114]: Previously setting `textColor` called `updateButtonVisuals()` which causes the crash because `highlightTextColor` was not set yet

**Review by kylehickinson — APPROVED** [review]
