### PR TITLE
Fix #3602 - Fixing swipe to dismiss Toast on iPad and on Toolbar

### LINKED ISSUE #3593: Swipe to dismiss sometimes adds the video to playlist
### Description: 
Found while testing #3574, swipe down on the toast message sometimes adds the video to playlist. This happens more on iPad than on iPhone's

### Steps to Reproduce 
  1. Install 1.25(21.4.27.17)
  2. Load a video and wait for the add to playlist toast to show up
  3. Swipe down to dismiss, the video may get added instead of dismissing the toast

**Actual result:** 
Hard to record try it out yourselves

**Expected result:**
Swipe left/right so as to not accidentally add the video to playlist

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.27.17)

**Device details:** 
Easy on iPad hard on iPhone's

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### LINKED ISSUE #3602: [Follow up to #3593] Swipe to dismiss sometimes adds the video to playlist
### Description: 
Found while testing #3574, swipe down on the toast message sometimes adds the video to playlist. This happens more on iPad than on iPhone's

### Steps to Reproduce 
  1. Install 1.25(21.4.27.17)
  2. Load a video and wait for the add to playlist toast to show up
  3. Swipe down to dismiss, the video may get added instead of dismissing the toast

**Actual result:** 
Hard to record try it out yourselves

**Expected result:**
Swipe left/right so as to not accidentally add the video to playlist

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.27.17)

**Device details:** 
Easy on iPad hard on iPhone's

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixing swipe distance in landscape for all devices.
- Swipe distance for iPad adjusted and dismissing on tab swipe on iPhone fixed.

This pull request fixes #3602

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/PlaylistToast.swift [hunk 1]
```diff
@@ -11,35 +11,94 @@ import SnapKit
...
+        if let shadowLayer = shadowLayer {
+            shadowLayer.path = path
+            shadowLayer.shadowPath = path
+        } else {
+            shadowLayer = CAShapeLayer().then {
+                $0.path = path
+                $0.fillColor = UIColor.clear.cgColor
+                $0.shadowColor = UIColor.black.cgColor
+                $0.shadowPath = path
+                $0.shadowOffset = CGSize(width: 0.0, height: 0.0)
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/PlaylistToast.swift]: Can simplify CGSize here and simply type `$0.shadowOffset = .zero`

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/Playlist/PlaylistToast.swift [hunk 2]
```diff
@@ -11,35 +11,94 @@ import SnapKit
...
+                $0.shadowOpacity = 0.5
+                $0.shadowRadius = ButtonToastUX.toastButtonBorderRadius
+            }
+            
+            shadowLayer?.do {
+                layer.insertSublayer($0, at: 0)
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/PlaylistToast.swift]: This part is the same as the previous shadowlayer, no? Maybe abstract it a little

**Review by iccub — CHANGES_REQUESTED** [review]
Two nitpicks, this shadow logic is complex a bit

**Review by iccub — APPROVED** [review]
