### PR TITLE
Fix #1127: Select tab if it's not selected to prevent fatalCrash

### LINKED ISSUE #1127: App is crashed with `fatalError` on push animation of BVC to Tray when selectedTab is nil.
For an unknown reason the selectedTab is nil when transitioning from `BrowserViewController` to `TabTray` using a custom push animation. It 's not yet known how and why the selectedTab is nil at that point of time, since the moment the you close the current selectedTab a new one is selected or if empty a new one is created and selected. 

### Steps to Reproduce 
No STR. Please update if found.
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by danishjafri88**
This fix should stop the crashes, but the cause of `nil` selectedTab is still unknown.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

**Review by iccub — APPROVED** [review]
looks promising :)

as you said in the description, it's not easy to test so we just have to monitor crashes in Xcode organizer

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1426,10 +1426,16 @@ extension BrowserViewController {
 
 extension BrowserViewController: URLBarDelegate {
     func showTabTray() {
+        guard !tabManager.tabsForCurrentMode.isEmpty else {
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift]: This is a double negative. Just use an `if`:

```suggestion
        if tabManager.tabsForCurrentMode.isEmpty {
```

**Review by jhreis — CHANGES_REQUESTED** [review]

**Review by jhreis — APPROVED** [review]
