### PR TITLE
Fix #4944: Swap value reset to 0

### LINKED ISSUE #4944: Swap value is reset to 0 when it crosses a threshold
### Description: 
Swap value is reset to 0 when it crosses a threshold. Found while investigating https://github.com/brave/brave-core/pull/12127

### Steps to Reproduce 
  1. Enable Wallet
  2. Select Swap
  3. Enter an unusually long decimal value, input values resets to 0

**Actual result:** 

https://user-images.githubusercontent.com/17010094/152483603-241b9423-0d79-47c4-aad4-688e725f74d1.MP4

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 
iPhone XR (iOS 15.3)

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes

This pull request fixes #4944

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
1. Open swap view
2. Enter a long decimal value
3. Value should no longer reset

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift [hunk 1]
```diff
@@ -572,6 +571,7 @@ public class SwapTokenStore: ObservableObject {
             return
           }
           self.state = .error(Strings.Wallet.unknownError)
+          self.clearAllAmount()
```
Comment (nuo-xu) [inline BraveWallet/Crypto/Stores/SwapTokenStore.swift:574]: so it will reset if there is an unknown error? i actually dont know what is the expected reset behaviour. But I'm ok with this.

**Review by nuo-xu — APPROVED** [review]

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift (hunk 1 above)
Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/SwapTokenStore.swift:574]: Yes, I checked for other usage of `clearAllAmount()` / field resets and we seem to only reset when we hit an unknown error. For this issue specifically, we were getting the insufficient liquidity error which I don't think should reset the value. Similar for insufficient balance error. The 'swap' button updates for both of those errors so I don't think we need to reset value fields.
