### PR TITLE
Fix #851: Show image title when long-pressing an image

### LINKED ISSUE #851: Display title tag when long-pressing on image
### Description: 
When long-pressing on an image, it shows the image URL but no title text. Could this show the title text like Safari does?

Sites such as XKCD.com have title tags on images and are only available by long-pressing the image in Safari.

### Steps to Reproduce 
  1. Go to XKCD.com
  2. Long press on the comic picture until it prompts you to Open Image In New Tab / Save Image / Copy Image.
  3. At the top, you'll see a path to the image, but not the title text. 
  4. Compare this with Safari by following steps 1-3 above. You'll see Safari shows the text in the title tag.

**Actual result:** 
First picture: Brave. Second picture: Safari.
image
image

**Expected result:**
No expected result. 

**Reproduces how often:** 
100% of the time.

**Brave Version:**
iOS 1.7.4.

**Device details:** 
iPhone XS, iOS 12.1.3

### PR DESCRIPTION
**Pull request by cndouglas**
Fix #851

This change sets the context menu's title to the image's title (if it exists). Otherwise, it shows the image's URL, which is the existing behavior.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

1. Go to https://xkcd.com/2107/
2. Long-press on the comic image.
3. The image's title should be displayed above the Open Image In New Tab button, as shown in the screenshot below.

### Screenshots:

See https://github.com/brave/brave-ios/pull/875#issuecomment-483455131

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Assets/AllFramesAtDocumentEnd.js [hunk 1]
```diff
@@ -1 +1 @@
...
...eturn""==n&&(n=e.baseURI),this._getPasswordOrigin(n,!0)}};function i(e){t.onUsernameInput(e)}var s=document.body;function a(e){for(var n=0;n<e.length;n++){var t=e[n];"FORM"===t.nodeName?u(t):t.hasChildNodes()&&a(t.childNodes)}return!1}function u(e){try{t._asyncFindLogins(e,{}).then(function(e){t.loginsFound(e.form,e.loginsFound)}).then(null,n)}catch(e){n(e)}}function l(e,n,t){var r=document.createEvent("KeyboardEvent");r.initKeyboardEvent(n,!0,!0,window,0,0,0,0,0,t),e.dispatchEvent(r)}new MutationObserver(function(e){for(var n=0;n<e.length;++n)a(e[n].addedNodes)}).observe(s,{attributes:!1,childList:!0,characterData:!1,subtree:!0}),window.addEventListener("load",function(e){for(var n=0;n<document.forms.length;n++)u(document.forms[n])}),window.addEventListener("submit",function(e){try{t._onFormSubmit(e.target)}catch(e){n(e)}}),Object.defineProperty(window.__firefox__,"logins",{enumerable:!1,configurable:!1,writable:!1,value:Object.freeze(new function(){this.inject=function(e){try{t.receiveMessage(e)}catch(e){}}})})})},function(e,n,t){"use strict";window.__firefox__.includeOnce("PrintHandler",function(){window.print=function(){webkit.messageHandlers.printHandler.postMessage({})}})}]);
```
Comment (iccub) [inline Client/Assets/AllFramesAtDocumentEnd.js]: I think you have to remove this change from the PR, otherwise our CI throws an error.
This line sometimes get changed when running the bootstrap script, sorry about that

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Assets/AllFramesAtDocumentEnd.js (hunk 1 above)
Comment (cndouglas) [reply Client/Assets/AllFramesAtDocumentEnd.js]: I forgot to include `ContextMenu.js` in the commit. Fixed.

File: Client/Assets/AllFramesAtDocumentEnd.js [hunk 2]
```diff
@@ -1 +1 @@
...
...eturn""==n&&(n=e.baseURI),this._getPasswordOrigin(n,!0)}};function o(e){t.onUsernameInput(e)}var s=document.body;function a(e){for(var n=0;n<e.length;n++){var t=e[n];"FORM"===t.nodeName?u(t):t.hasChildNodes()&&a(t.childNodes)}return!1}function u(e){try{t._asyncFindLogins(e,{}).then(function(e){t.loginsFound(e.form,e.loginsFound)}).then(null,n)}catch(e){n(e)}}function l(e,n,t){var r=document.createEvent("KeyboardEvent");r.initKeyboardEvent(n,!0,!0,window,0,0,0,0,0,t),e.dispatchEvent(r)}new MutationObserver(function(e){for(var n=0;n<e.length;++n)a(e[n].addedNodes)}).observe(s,{attributes:!1,childList:!0,characterData:!1,subtree:!0}),window.addEventListener("load",function(e){for(var n=0;n<document.forms.length;n++)u(document.forms[n])}),window.addEventListener("submit",function(e){try{t._onFormSubmit(e.target)}catch(e){n(e)}}),Object.defineProperty(window.__firefox__,"logins",{enumerable:!1,configurable:!1,writable:!1,value:Object.freeze(new function(){this.inject=function(e){try{t.receiveMessage(e)}catch(e){}}})})})},function(e,n,t){"use strict";window.__firefox__.includeOnce("PrintHandler",function(){window.print=function(){webkit.messageHandlers.printHandler.postMessage({})}})}]);
```
Comment (jhreis) [inline Client/Assets/AllFramesAtDocumentEnd.js]: What changes took place here and were they intentional?

File: Client/Frontend/Browser/ContextMenuHelper.swift [hunk 3]
```diff
@@ -91,7 +92,9 @@ extension ContextMenuHelper: TabContentScript {
         }
 
         if linkURL != nil || imageURL != nil {
-            elements = Elements(link: linkURL, image: imageURL)
+            let rawTitle = data["title"] as? String ?? ""
```
Comment (jhreis) [inline Client/Frontend/Browser/ContextMenuHelper.swift]: For consistency sake, I think following the pattern that `image` and `link` use would probably be best:

```
var titleText: String?
if let title = data["title"] as? String, !title.isEmpty {
    titleText = title
}
```

...

```
if linkURL != nil || imageURL != nil {
    elements = Elements(link: linkURL, image: imageURL, title: title)
}

**Review by jhreis — CHANGES_REQUESTED** [review]
Still waiting on a security review, but did leave one comment. However, feel free to wait for sec-review before making changes. Don't want to waste your time 😄

File: Client/Frontend/Browser/ContextMenuHelper.swift (hunk 3 above)
Comment (cndouglas) [reply Client/Frontend/Browser/ContextMenuHelper.swift]: Fixed.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -2485,7 +2485,7 @@ extension BrowserViewController: ContextMenuHelperDelegate {
 
         if let url = elements.image {
             if dialogTitle == nil {
-                dialogTitle = url.absoluteString
+                dialogTitle = elements.title ?? url.absoluteString.ellipsize(maxLength: ActionSheetTitleMaxLength)
```
Comment (cndouglas) [inline Client/Frontend/Browser/BrowserViewController.swift]: I moved the `ellipsize` method to here (from line 2562) so that only URLs are "ellipsized". Titles will always be shown in full, which matches Safari's behavior.

Comment (jhreis) [reply Client/Frontend/Browser/BrowserViewController.swift]: Does this put an ellipse'd URL solely on one single line?

**Review by jhreis — CHANGES_REQUESTED** [review]
@cndouglas Thanks for your patience here. So talked with both sec and design, and they want both
- [ ] title
- [ ] full url

Potentially will be a lot of information in here. Give `title\nurl` and `url\ntitle`, and see which one feels more natural.

Additionally, security is more leaning towards full URL, so I think we'll go with that for now.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 4 above)
Comment (cndouglas) [reply Client/Frontend/Browser/BrowserViewController.swift]: From a quick test, looks like the URL may be up to around 3 lines long.

**Comment by cndouglas** [comment]
@jhreis
I removed the "ellipsize" call, so now the title and URL are always shown in full.

I went with the Title-URL option but made it easy to switch if desired.

I also made the current URL behavior behavior more explicit in the code. As I noted on line 2491, "If the image is a link, show the link's URL. Otherwise, show the image's source URL."

Here are examples of what the two options look like (for the image on https://xkcd.com/2131/):
Title-URL (this PR):
TitleURL
URL-Title (alternative):
URLTitle

**Comment by cndouglas** [comment]
@jhreis I just sent you an email.

**Comment by jhreis** [comment]
@cndouglas thanks! Just running this by our sec team again for final approval.

**Comment by jhreis** [comment]
@cndouglas looks super great. Sounds like the consensus is:

```
title\n 
\n
url
```

e.g.:

> This is an amazing title
>
> someurl.tld

**Review by iccub — APPROVED** [review]

**Comment by cndouglas** [comment]
Per https://github.com/brave/brave-ios/pull/875#issuecomment-482181660, I added another space between the title and the URL, so now there are two spaces (`\n\n`). Here's what it looks like now:

**Comment by jhreis** [comment]
@cndouglas _perfect_ Thanks! I am submitting a security review request, so will merge it once that has been completed. Thanks!

**Comment by jumde** [comment]
image

Text overflow hides the URL. We should have text limits to avoid this case.

**Comment by cndouglas** [comment]
We could do a character limit for the title. However, the website could theoretically get around the limit by using dozens of newlines in the title.

**Comment by iccub** [comment]
We could trim whitespace characters, right?

**Comment by jhreis** [comment]
Alright, sorry for the insane changes, but after sec review, we decided to switch the title / url. If the text overflows, we want to guarantee that the user can at least see the full URL.

**Comment by cndouglas** [comment]
I switched the URL and title. I also fixed the logic if the title is not nil but empty (line 2483).

Screenshot:

**Review by jhreis — APPROVED** [review]

**Comment by jhreis** [comment]
This is great, thanks!
