### PR TITLE
Fix #8585 - Fix Javascript Disabling <NoScript>

### LINKED ISSUE #8585: Javascript Disabled [No-Script] not working
### Description: 
```html
<html>
  <head>
  </head>
  <body>
     <h1>This color is red if you have scripts disabled</h1>
     <noscript>
       <style>
         h1 {
           color: red;
         }
       </style>
     </noscript>
  </body>
</html>
```

from: https://kkarikos.github.io/ does not work.
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1694087671230389?thread_ts=1693847447.126979&cid=C06UXF3KJ

It works in Safari, but not Brave

### Actual result: 
- Text is black

### Expected result:
- Text should be red

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- Any >= iOS 14+

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix Disabling JS not working due to a bug in iOS
- Also, note that we do not need to refresh the page. 
- Changing it on the configuration directly works!

This pull request fixes #8585

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

**Review by cuba — APPROVED** [review]

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -380,7 +380,18 @@ extension BrowserViewController: WKNavigationDelegate {
...
+        // https://github.com/brave/brave-ios/issues/8585
+        //
+        // However, the deprecated API WKWebViewConfiguration.preferences.javaScriptEnabled DOES work!
+        // Even though `configuration` is @NSCopying, somehow this actually updates the preferences LIVE!!
+        // This follows the same behaviour as Safari
+        //
+        // - Brandon T.
+        //
         preferences.allowsContentJavaScript = isScriptsEnabled
+        webView.configuration.preferences.javaScriptEnabled = isScriptsEnabled
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:394]: Does setting it via https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/3194420-defaultwebpagepreferences work which is not deprecated?

Comment (kylehickinson) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:394]: Another thing to check: Does creating a new `WKWebpagePreferences` object instead and returning that instead of assigning `allowsContentJavaScript` to the one passed into the delegate method work?

Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:394]: Neither of those work.
I tried default preferences before this PR, and I just tried creating a new one, it doesn't work still.
Also tried it directly inside of `TabManagerNavDelegate` too. No luck.

**Comment by diracdeltas** [comment]
IIRC this has broken before too. Can we add an automated test for it?

**Comment by Brandon-T** [comment]
> IIRC this has broken before too. Can we add an automated test for it?

We can, but the problem is that this is OS related since the API gets updated when the OS gets updated (WebKit ships with the OS), so the unit test would only tell us when the OS has changed the behaviour.

Is that acceptable?

**Comment by iccub** [comment]
pinging @diracdeltas about the comment Brandon wrote, easy to miss notifications during the winter break

**Comment by diracdeltas** [comment]
thx for the reminder. that sgtm. also i should have clarified adding a test does not block this PR.

**Comment by jparedeslopez** [comment]
@anthonypkeane  was this fix released to prod already? We need it to fix the issue with images.

**Comment by iccub** [comment]
@jparedeslopez next week most likely
