### PR TITLE
Fix #1242: Configure logger for Brave Rewards.

### LINKED ISSUE #1242: Configure logger for Rewards
### Description: 

No logs are showing when working with Rewards which makes it hard to debug.

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
Sample log output 
```
2019-07-12 18:44:55.624 [Error] > [wallet.cc.47] Wallet creation didn't finish or corrupted. We need to clear persona Id and start again
2019-07-12 18:44:56.062 [Info] > [ledger_impl.cc.1179] [ RESPONSE - RequestCredentialsCallback ]
2019-07-12 18:44:56.062 [Info] > [ledger_impl.cc.1179] > time: 1562949896
2019-07-12 18:44:56.062 [Info] > [ledger_impl.cc.1179] > result: Success
```

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift [hunk 1]
```diff
@@ -37,6 +38,29 @@ extension BrowserViewController {
         popover.addsConvenientDismissalMargins = false
         popover.present(from: topToolbar.locationView.rewardsButton, on: self)
     }
+    
+    func configureRewardsLogs() {
+        if rewards == nil { return }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: This should be actually be setup before `rewards` is created so that logs come in during initialization

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift [hunk 2]
```diff
@@ -37,6 +38,29 @@ extension BrowserViewController {
...
+    }
+    
+    private func logCallback(logLevel: LogLevel, line: Int32, file: String, data: String) {
+        if data.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty { return }
+        
+        let logger = Logger.rewardsLogger
+        // Rewards logger gives us full file path, extracting filename from it.
+        let fileName = (file as NSString).lastPathComponent
+        
+        let logOutput = "[\(fileName).\(line)] \(data)"
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: Is showing filename and line something we can control with `Logger` somehow? So that we dont always show them regardless of log level?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: XCLogger `file` and `line` will point to this exact method, not to the source code of BraveRewards

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: Ah, I see, lame… I wonder if we should add some sort of pref around whether or not to pre-pend file info? I guess if its just filename + line it won't be that bad… but still

Thoughts?

Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: Yeah I was thinking about that, I can add some parameters with default values to the `configureRewardsLogs()`

Or I could see if XCLogger has fileinfo enabled and then redirect it to use the one provided by Rewards logger

File: Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift [hunk 3]
```diff
@@ -37,6 +38,29 @@ extension BrowserViewController {
         popover.addsConvenientDismissalMargins = false
         popover.present(from: topToolbar.locationView.rewardsButton, on: self)
     }
+    
+    func configureRewardsLogs() {
+        if rewards == nil { return }
+        RewardsLogger.configure(logCallback: logCallback, withFlush: nil)
+    }
+    
+    private func logCallback(logLevel: LogLevel, line: Int32, file: String, data: String) {
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: Should this function be static? How does `logCallback` get called when it's non-static? Does self somehow get retained with the block when we do `RewardsLogger.configure`?

Just curious is all.

Anyway, code looks good!

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: Thats a good point, not sure that this being non-static may make it hold a ref to `BrowserViewController` or if its copying it as a block somehow… It might not be a huge issue anyways since we never dealloc BrowserViewController :P

Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BVC+Rewards.swift]: This function doesn't call BrowserViewController so we should be fine

**Review by kylehickinson — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
