### PR TITLE
Fix #8635: URLBar updates and CertValidation

### LINKED ISSUE #7403: Brave incorrectly reports HTTP connection as secure (shows lock icon)
### Description: 

When visiting an HTTP website, for example ~~http://www.newlispfanclub.alh.net/forum/~~ http://www.newlispfanclub.alh.net/forum/viewtopic.php?p=22253#p22253 , Brave shows the connection as secure even though it's not an HTTPS connection.

### Steps to Reproduce 
  1. Visit ~~http://www.newlispfanclub.alh.net/forum/~~ http://www.newlispfanclub.alh.net/forum/viewtopic.php?p=22253#p22253

### Actual result: 

IMG_7464
IMG_7465

### Expected result:

For the lock icon to be replaced with some sort of not-lock icon and a clear warning shown either in the URL bar or somewhere else.

### Reproduces how often:

Easily reproduced.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight?  Don't know.
- Can you reproduce this issue with the previous version of the current build from TestFlight?  Don't know.
- Can you reproduce this issue with the current build from AppStore?  Yes.

### Device details: 

iOS 16.4.1 (a)

### Website problems only:
- did you check with Brave Shields down? Irrelevant
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, Safari shows "Not Secure"

### LINKED ISSUE #8393: [Follow up to #4358] The page is not closed/removed automatically after `.mobileconfig` file is downloaded
### Description: 

Follow-up to #4358

### Steps to Reproduce 
  1. Launch Brave
  2. Go to `https://gist.githubusercontent.com/nstanke/1df2ad86487c3b9a805d/raw/9b09ade1208a7f9ab41d3b3e7ca76fb1d877bece/mailinabox.mobileconfig`
  3. See a pop-up message > Tap `Allow`
  4. Tap `Close` > Observe
  5. Tap `Done` > Observe

### Actual result: 

The page is not closed/removed automatically after `.mobileconfig` file is downloaded.

|1|2|3|4|
|:-:|:-:|:-:|:-:|
|  |  |  |  |

https://github.com/brave/brave-ios/assets/128532965/c065ed1f-9c34-442b-a993-957bdb439742

### Expected result:

After `.mobileconfig` file is downloaded, that page must be closed/removed automatically similar to what is happening in Safari.

https://github.com/brave/brave-ios/assets/128532965/a7ed56dd-59e1-4a41-bb2e-f44021c9c371

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 

iPhone 14 / iOS 17.2

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #8576: Address bar blank before website starts loading
### Description: 
Address bar empty unless website starts loading

Regression in 1.61, probably due to URL bar revamp effort

### Steps to Reproduce 
  1. Open new tab
  2. Search for website or keyword
  3. Observe 

### Actual result: 

https://github.com/brave/brave-ios/assets/17885425/a6ae9967-1ba9-41ea-8c5a-4ff48718751d

### Expected result:
URL bar should not be blank after clicking on link or entering search

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.61 (23.12.15.14)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone 12, iOS 17.1.1

### LINKED ISSUE #8635: Intermittent Incorrect URL Bar state and various fixes related with state and url
### Description: 

URL Bar update moved to `didFailProvisionalNavigation` to support spoofing prevention properly. For cancelation  `didFailProvisionalNavigation` should be used.

This way we can cover both cancelation url update problem and also blank address bar before loading starts.

Issues closed related with this were 

https://github.com/brave/brave-ios/issues/8393
https://github.com/brave/brave-ios/issues/8576

Also the async trigger for observe webview key values inside didCommit is removed. In addition verifyTrust is forced to run async and the awaited result is used on updateURL bar.

We are thinking these 2 changes will solve the intermittent problem related with loading urls stuck in insecure state.

In addition this change also should be tested where we show secure icon when insecure website is loaded.

https://github.com/brave/brave-ios/issues/7403

### Test Plan

Test all the STRs in these 3 tickets, fresh test all over again.

https://github.com/brave/brave-ios/issues/8393
https://github.com/brave/brave-ios/issues/8576
https://github.com/brave/brave-ios/issues/7403

In addition always keep an eye on if a insecure website indicator shown on a secure website.

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

- Update URL bar on cancellation instead of URL change, because URL change can update the certificate state and URL spoofing is possible.

- Remove `didCommit` serverTrust validation as it works fine with URLBar Revamp. 
- Make the validation function async-await
- Remove `select` as it crashes in debug builds

This pull request fixes #8635
and
This pull request fixes #8393
This pull request fixes #7403 
This pull request fixes #8576

#8393 #7403  #8576 has to be re-tested.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
- Re-test all the linked tickets

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/CertificateUtilities/BraveCertificateUtils.swift [hunk 1]
```diff
@@ -232,4 +233,8 @@ public extension BraveCertificateUtils {
       }
     }
   }
+  
+  static func verifyTrust(_ trust: SecTrust, host: String, port: Int) async -> Int {
+    return Int(BraveCertificateUtility.verifyTrust(trust, host: host, port: port))
+  }
 }
```
Comment (cuba) [inline Sources/CertificateUtilities/BraveCertificateUtils.swift:240]: I don't think we should handle this here as this will need to be uplifted to 1.62 but I find it a little strange we have a `BraveCertificateUtility` in brave core and a `BraveCertificateUtils` in iOS. I wonder if we can just extend the other one or something in some future update.

**Review by cuba — APPROVED** [review]

File: Sources/CertificateUtilities/BraveCertificateUtils.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/CertificateUtilities/BraveCertificateUtils.swift:240]: We will cherry pick this to Release branch which is pointing to 1.62 and there is no problem with it. 

But for extending BraveCertificateUtility, you can create an issue for it and we can discuss in Triage.

File: Sources/Brave/Frontend/Browser/BrowserViewController/BVC+WKNavigationDelegate.swift [hunk 2]
```diff
@@ -788,6 +778,10 @@ extension BrowserViewController: WKNavigationDelegate {
     // original web page in the tab instead of replacing it with an error page.
     var error = error as NSError
     if error.domain == "WebKitErrorDomain" && error.code == 102 {
+      if let tab = tabManager[webView], tab === tabManager.selectedTab {
+        updateToolbarCurrentURL(tab.url?.displayURL)
+        updateWebViewPageZoom(tab: tab)
+      }
```
Comment (bsclifton) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BVC+WKNavigationDelegate.swift:784]: @Brandon-T what was the issue with this logic? where it was removed in https://github.com/brave/brave-core/pull/22534
