### PR TITLE
Fixes #1255: WebView becomes blank when showing PDF on Tab-Tray

### LINKED ISSUE #1255: WebView becomes blank when showing PDF and Switching from tab tray to browser.
### Description: 
WebView displays blank pdf document after transitioning from tab tray controller to browser controller.

### Steps to Reproduce 
  1. Open a pdf in browser (any pdf)
  2. Tap tab tray button 
  3. press done button in tab tray to go back to browser

**Actual result:** 
Blank/Empty pdf document

**Expected result:**
Actual document before going to tab controller

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
The issue is internal to a webkit and will require a workaround. Maybe a page refresh?
https://bugs.webkit.org/show_bug.cgi?id=193281

### PR DESCRIPTION
**Pull request by Brandon-T**
Fixes PDFs not rendering when UINavigationController `pushes` the WKWebView controller to the tab tray and back. Even happens in a brand new project that contains only a WKWebView (with a PDF loaded) and embedded in a NavigationController)..

Can be reproduced using this code: https://gist.github.com/Brandon-T/6ef3a15498ecf7ec7d5ce170e5533934

OR

Following the steps in Ticket: #1255

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/BrowserTrayAnimators.swift [hunk 1]
```diff
@@ -94,8 +94,29 @@ private extension TrayToBrowserAnimator {
             bvc.topToolbar.isTransitioning = false
             bvc.updateTabsBarVisibility()
             transitionContext.completeTransition(true)
+            
+            self.WKWebViewPDFNotRenderingBugFix(for: bvc)
         })
     }
+    
+    /// Fixes a Bug in iOS 12.2 where:
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserTrayAnimators.swift:102]: Does this happen on this iOS version only?

Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserTrayAnimators.swift:102]: I am not able to verify it on iOS 12.1 or 12.3+ as I don't have those devices.. However, it happens in Simulator 12.3+.

IIRC, there is a rdar open for it and it says it doesn't happen on before 12.1.. but happens on >=12.2

I just can't verify it myself on all the versions.

Comment (iccub) [reply Client/Frontend/Browser/BrowserTrayAnimators.swift:102]: Thanks for explanation, could you add a rdar link or bug number to the comment?

File: Client/Frontend/Browser/BrowserTrayAnimators.swift [hunk 2]
```diff
@@ -94,8 +94,29 @@ private extension TrayToBrowserAnimator {
             bvc.topToolbar.isTransitioning = false
             bvc.updateTabsBarVisibility()
             transitionContext.completeTransition(true)
+            
+            self.WKWebViewPDFNotRenderingBugFix(for: bvc)
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserTrayAnimators.swift:98]: Can we do this only if a PDF file is opened, any easy way to check it?

File: Client/Frontend/Browser/BrowserTrayAnimators.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserTrayAnimators.swift:102]: @iccub Added to the comment the links for WebKit bug tracker and for StackOverflow where a Firefox Developer also having the same issue but solved it worse by reloading the entire page and redrawing the PDF :(

File: Client/Frontend/Browser/BrowserTrayAnimators.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserTrayAnimators.swift:98]: Done. You are right. There is a better way :) I found that each tab has a `mimeType` and I used that to determine if we are viewing a PDF. Also optimized it to not check every tab because it only ever happens to the selected tab.

**Review by iccub — APPROVED** [review]
Great job :)

**Review by danishjafri88 — APPROVED** [review]
