### PR TITLE
Fix #951: Set `customTitle` to `title` when updating a Bookmark.

### LINKED ISSUE #951: Editing bookmarks/folder in iOS doesn't propagate to Desktop
### Description: 
Editing bookmarks/folder in iOS doesn't propagate to Desktop 

### Devices
Device 1: Ubuntu 18.04 running `0.61.47 `
Device 2: iPhone 7+ running 1.9.(19.3.6.15)

### Steps to Reproduce 
  1. Import bookmarks into desktop profile before enabling sync
  2. Create sync chain on desktop and add iPhone to the chain using QR code
  3. Ensure all bookmarks from desktop is sync'd to the mobile
  4. Edit bookmark folder name on iPhone, Edit bookmark title on iPhone
  5. Changes don't propagate to desktop
  6. Add a new bookmark on iPhone to force sending records, still bookmark/folder from step 4 doesn't show up on desktop 

**Actual result:** 
Desktop folder names unchanged
screenshot from 2019-03-08 10-27-52

Edited bookmark title doesn't change on desktop
screenshot from 2019-03-08 10-33-10

Folder names changed on iPhone
file 3

Bookmark title edited on iPhone
file 4

**Expected result:**
Any changes made on iPhone too bookmarks or folders should propagate to all devices on the chain

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/models/Bookmark.swift [hunk 1]
```diff
@@ -314,7 +314,8 @@ extension Bookmark {
             }
             
             if let ct = customTitle, !ct.isEmpty {
-                bookmarkToUpdate.customTitle = customTitle
+                bookmarkToUpdate.customTitle = ct
+                bookmarkToUpdate.title = ct
```
Comment (iccub) [inline Data/models/Bookmark.swift:318]: An updated bookmark from desktop comes with `customTitle` and `title` having the same value. We have to match the behavior

**Review by kylehickinson — APPROVED** [review]
