### PR TITLE
Fix #7170: Do not double encode Brave Search fallback query.

### LINKED ISSUE #7170: Brave Search fallback encoding bug
### Steps to Reproduce 
  1.
  2.
  3.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #7170 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Query to use for test: `truitt white hinges berkeley`.

1. Enable "Google fallback query" from BraveSearch website settings.
2. Search for `truitt white hinges berkeley` from the app's url bar
3. Search for `truitt white hinges berkeley` from website's search bar
4. Verify that both search results are the same.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/Search/BraveSearchManager.swift [hunk 1]
```diff
@@ -177,7 +177,7 @@ class BraveSearchManager: NSObject {
     guard var components = URLComponents(string: fallbackProviderURLString) else { return }
 
     var queryItems: [URLQueryItem] = [
-      .init(name: "q", value: query.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed))
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/Search/BraveSearchManager.swift:180]: Curious Where do we do other encoding ?

Comment (iccub) [reply Sources/Brave/Frontend/Browser/Search/BraveSearchManager.swift:180]: seems to be done when you submit a query from the in-app url bar

**Review by soner-yuksel — APPROVED** [review]
