### PR TITLE
Fix #2333 - Fixes issue where rewards SummaryView is null.

### LINKED ISSUE #2333: Show pending contributions doesn't open contribution list
### Description: 
Show pending contributions doesn't open contribution list

### Steps to Reproduce 
  1. Install 1.15(20.02.12.10)
  2. Visit an unverified pub and tip them
  3. Open a new tab and open rewards panel
  4. Tap on `Show pending contribution` doesn't open pending list

**Actual result:** 
pending-contribution

**Expected result:**
Should open the pending list 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.02.12.10)

**Device details:** 
iPhone 7+ (iOS 13.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Found while testing  #1670

### PR DESCRIPTION
**Pull request by Brandon-T**
Fixes issue where Wallet.rewardsSummaryView is nil and not set to self.summaryView before setup is called.. therefore accessing it is a NOP and event handlers aren't triggered.

## Summary of Changes

This pull request fixes issue #2333

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Wallet/WalletViewController.swift [hunk 1]
```diff
@@ -224,7 +224,7 @@ class WalletViewController: UIViewController, RewardsSummaryProtocol {
       self.state.delegate?.loadNewTabWithURL(url)
     }
     
-    walletView.rewardsSummaryView?.disclaimerView?.labels.forEach {
```
Comment (Brandon-T) [inline BraveRewardsUI/Wallet/WalletViewController.swift:227]: `walletView.rewardsSummaryView` is nil by the time we get to this line.. It later on does `walletView.rewardsSummaryView = self.rewardsSummaryView` somewhere else in an update function. So that's the reason this fix works and will always work.
:)

**Review by kylehickinson — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
