### PR TITLE
Fix #6254: Fix engine crashes by using serial queue for cosmetic filters

### LINKED ISSUE #6254: Adblock/Cosmetic filters crash
### Steps to Reproduce 
No way to reproduce found so far.

**Actual result:** 
Crash

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #6254 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]
looks good to me, lets wait for Kyle to see if theres any async await issues

File: Sources/Brave/Frontend/Browser/PageData.swift [hunk 1]
```diff
@@ -98,18 +98,26 @@ struct PageData {
...
-    userScriptTypes = userScriptTypes.union(
-      adBlockStats.makeEngineScriptTypes(frameURL: mainFrameURL, isMainFrame: true, domain: domain)
-    )
+    async let engineScripts = adBlockStats.makeEngineScriptTypes(frameURL: mainFrameURL, isMainFrame: true, domain: domain)
     
     // Add engine scripts for all of the known sub-frames
-    let additionalScriptTypes = allSubframeURLs.map({ frameURL in
-      return self.adBlockStats.makeEngineScriptTypes(frameURL: frameURL, isMainFrame: false, domain: domain)
+    async let additionalScriptTypes = allSubframeURLs.asyncConcurrentCompactMap({ frameURL in
+      return await self.adBlockStats.makeEngineScriptTypes(frameURL: frameURL, isMainFrame: false, domain: domain)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/PageData.swift:115]: This `asyncConcurrentCompactMap` is completely useless as `makeEngineScriptTypes` is `MainActor` isolated thus won't execute concurrently

File: Sources/Brave/Frontend/Browser/PageData.swift [hunk 2]
```diff
@@ -98,18 +98,26 @@ struct PageData {
...
+  func makeMainFrameEngineScriptTypes(domain: Domain) async -> Set<UserScriptType> {
+    return await adBlockStats.makeEngineScriptTypes(frameURL: mainFrameURL, isMainFrame: true, domain: domain)
+  }
+  
+  func makeAllEngineScripts(for domain: Domain) async -> Set<UserScriptType> {
     // Add engine scripts for the main frame
-    userScriptTypes = userScriptTypes.union(
-      adBlockStats.makeEngineScriptTypes(frameURL: mainFrameURL, isMainFrame: true, domain: domain)
-    )
+    async let engineScripts = adBlockStats.makeEngineScriptTypes(frameURL: mainFrameURL, isMainFrame: true, domain: domain)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/PageData.swift:111]: This async let is also not very useful for the same reason: `makeEngineScriptTypes` will block main actor anyways and thus the calls below that also make calls to `makeEngineScriptTypes` will not execute until after this is done

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift [hunk 3]
```diff
@@ -187,38 +187,36 @@ public actor AdBlockEngineManager: Sendable {
 extension AdBlockEngineManager {
   /// A method that logs info on the given resources
   fileprivate func debug(compiledResults: [ResourceWithVersion: Result<Void, Error>]) {
-    let resourcesString = compiledResults.sorted(by: { $0.key.order < $1.key.order })
-      .map { (resourceWithVersion, compileResult) -> String in
+    log.debug("Loaded \(compiledResults.count, privacy: .public) (total) engine resources:")
```
Comment (kylehickinson) [inline Sources/Brave/WebFilters/AdBlockEngineManager.swift]: Does this need to be public?

File: Sources/Brave/WebFilters/ContentBlocker/ContentBlockerHelper.swift [hunk 4]
```diff
@@ -45,12 +45,8 @@ enum BlockingStrength: String {
 class ContentBlockerHelper {
   private(set) weak var tab: Tab?
   
-  /// The rule types and source types that are currently loaded in this tab
-  private(set) var loadedRuleTypeWithSourceTypes: Set<ContentBlockerManager.RuleTypeWithSourceType> = []
-  /// The rule types with their source types that should be  loaded in this tab
-  var ruleListTypes: Set<ContentBlockerManager.RuleTypeWithSourceType> = [] {
-    didSet { reloadNeededRuleLists() }
-  }
```
Comment (kylehickinson) [inline Sources/Brave/WebFilters/ContentBlocker/ContentBlockerHelper.swift:53]: You could have just `@MainActor` isolated this property instead of make a function

File: Sources/Brave/Frontend/Browser/PageData.swift (hunk 1 above)
Comment (cuba) [reply Sources/Brave/Frontend/Browser/PageData.swift:115]: my next pr fixes this (as in it will need to be async), I was hoping to keep it to have less merge conflicts as I borrowed a subset of changes from that pr.

Comment (kylehickinson) [reply Sources/Brave/Frontend/Browser/PageData.swift:115]: No sorry, fix it here. If the contents inside need to be async then use `asyncCompactMap` instead

File: Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift [hunk 5]
```diff
@@ -313,53 +313,44 @@ final public class ContentBlockerManager: Sendable {
...
     }
     
     return results
   }
   
+  /// Return the enabled rule types for this domain and the enabled settings
+  @MainActor public func ruleLists(for domain: Domain) async -> Set<WKContentRuleList> {
+    let ruleTypes = enabledRuleTypes(for: domain)
+    
+    return await Set(ruleTypes.asyncConcurrentCompactMap { ruleType in
```
Comment (kylehickinson) [inline Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift]: `asyncConcurrentCompactMap` also not needed here, `cachedRuleList` is not async

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/Browser/PageData.swift (hunk 1 above)
Comment (cuba) [reply Sources/Brave/Frontend/Browser/PageData.swift:115]: I will actually get rid of the `@MainActor` on that method because it's not needed. This should allow things to go in parallel. Is this ok with you?

File: Sources/Brave/WebFilters/ContentBlocker/ContentBlockerHelper.swift (hunk 4 above)
Comment (cuba) [reply Sources/Brave/WebFilters/ContentBlocker/ContentBlockerHelper.swift:53]: Well its actually the change was more than just @MainActor so it was a new method. I generally dislike using vars for more complex things but I can make it a var if you wish.

File: Sources/Brave/Frontend/Browser/PageData.swift (hunk 2 above)
Comment (cuba) [reply Sources/Brave/Frontend/Browser/PageData.swift:111]: So as I said above I made the method non `@MainActor` so this should also allow this to be in parallel

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift (hunk 3 above)
Comment (cuba) [reply Sources/Brave/WebFilters/AdBlockEngineManager.swift]: Fixed

File: Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift (hunk 5 above)
Comment (cuba) [reply Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift]: Removed the async. It was async because of the cherry pick which had some internals async. Thought this contentBlockerManager is going to completely change.

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift (hunk 3 above)
Comment (kylehickinson) [reply Sources/Brave/WebFilters/AdBlockEngineManager.swift]: Sorry I didn't mean the extension, I meant the log itself (`privacy: .public`), this code is only compiled in Debug anyways, so it doesn't need to be explicitly public

File: Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift [hunk 6]
```diff
@@ -633,16 +633,13 @@ extension PlaylistWebLoader: WKNavigationDelegate {
...
-        tab.contentBlocker.ruleListTypes = enabledRuleTypes
+        let ruleLists = await ContentBlockerManager.shared.ruleLists(for: domainForShields)
+        tab.contentBlocker.set(ruleLists: ruleLists)
 
         let isScriptsEnabled = !domainForShields.isShieldExpected(.NoScript, considerAllShieldsOption: true)
         preferences.allowsContentJavaScript = isScriptsEnabled
       }
 
-      // Cookie Blocking code below
-      tab.setScript(script: .cookieBlocking, enabled: Preferences.Privacy.blockAllCookies.value)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift]: Whats this removal for?

Comment (cuba) [reply Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift]: Ahh nice catch. I should have seen this. It was some cherry picked change I don't want here.

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift (hunk 3 above)
Comment (cuba) [reply Sources/Brave/WebFilters/AdBlockEngineManager.swift]: Ahh right. Fixed

Comment (kylehickinson) [reply Sources/Brave/WebFilters/AdBlockEngineManager.swift]: You only fixed this for the log below? But not this one? `privacy: .private` is redundant as well btw, its the default

Comment (cuba) [reply Sources/Brave/WebFilters/AdBlockEngineManager.swift]: Oh yah sorry I missed that. I fixed it now.

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift [hunk 7]
```diff
@@ -184,41 +184,39 @@ public actor AdBlockEngineManager: Sendable {
...
 
 #if DEBUG
-extension AdBlockEngineManager {
+private extension AdBlockEngineManager {
   /// A method that logs info on the given resources
-  fileprivate func debug(compiledResults: [ResourceWithVersion: Result<Void, Error>]) {
-    let resourcesString = compiledResults.sorted(by: { $0.key.order < $1.key.order })
-      .map { (resourceWithVersion, compileResult) -> String in
+  func debug(compiledResults: [ResourceWithVersion: Result<Void, Error>]) {
+    log.debug("Loaded \(compiledResults.count, privacy: .private) (total) engine resources:")
```
Comment (kylehickinson) [inline Sources/Brave/WebFilters/AdBlockEngineManager.swift]: As mentioned `privacy: .private` is redundant

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift [hunk 8]
```diff
@@ -184,41 +184,39 @@ public actor AdBlockEngineManager: Sendable {
...
-        ].joined(separator: ", ")
+          "", resourceWithVersion.debugDescription,
+          "\(resultString)",
+        ].joined(separator: " ")
         
-        return ["{", sourceDebugString, "}"].joined()
-      }.joined(separator: ", ")
-
-    log.debug("Loaded \(self.enabledResources.count, privacy: .public) (total) engine resources: \(resourcesString, privacy: .public)")
+        log.debug("\(sourceDebugString, privacy: .private)")
```
Comment (kylehickinson) [inline Sources/Brave/WebFilters/AdBlockEngineManager.swift]: same here

File: Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift [hunk 9]
```diff
@@ -425,45 +388,44 @@ final public class ContentBlockerManager: Sendable {
   #if DEBUG
   /// A method that logs info on the given resources
   private func debug(resources: [String: Resource]) {
-    let resourcesString = resources
+    Self.log.debug("Compiled \(resources.count, privacy: .public) block list resources:")
```
Comment (kylehickinson) [inline Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift]: Doesn't need to be public

Comment (cuba) [reply Sources/Brave/WebFilters/ContentBlocker/ContentBlockerManager.swift]: Fixed

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift (hunk 8 above)
Comment (cuba) [reply Sources/Brave/WebFilters/AdBlockEngineManager.swift]: Fixed

File: Sources/Brave/WebFilters/AdBlockEngineManager.swift (hunk 7 above)
Comment (cuba) [reply Sources/Brave/WebFilters/AdBlockEngineManager.swift]: Fixed

**Review by kylehickinson — APPROVED** [review]
