### PR TITLE
Fix #553: Add collapsed URL bar state with domain information

### LINKED ISSUE #553: Do not hide address bar on navigation
### Description: 
Hiding URL bar on navigation can be used by phishing actors. 

See here: https://www.securitee.org/files/hindsight_ccs2017.pdf (ABB 15-16)

### Steps to Reproduce 
  1. Navigate to reddit.com
  2. Scroll

**Actual result:** 
Scrolling hides the address bar

**Expected result:**
URL bar should be visible at all times

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Everytime

**Brave Version:** 
1.7 (18.11.30.03)

**Device details:** 
iPhone SE | iOS 12.1

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #553 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Verify URL bar when collapsed displays the correct secure content state (lock for secure/https, warning icon when http/otherwise not secure such as certs)
- Test extremely long URLs such as `http://www.reddit.com_______________________________________________.__________________________.______________www.reddit.com______________________________________________________.___._______________wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.xdv.cz.srv21.endora.cz/metapoc/index.html` to ensure that you are always able to see the eTLD+1

## Screenshots:

| Secure | Insecure + Long URL |
| --- | --- |
| image | image |

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1533,6 +1541,7 @@ public class BrowserViewController: UIViewController, BrowserViewControllerDeleg
 
         if tabManager.selectedTab === tab {
           topToolbar.secureContentState = tab.secureContentState
+          collapsedURLBarView.secureContentState = tab.secureContentState
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: I wonder if there's value in making it more like a single source of truth when setting data to toolbars, so when a top toolbar is updated, the collapsed bar is always updated too.
In this solution there's a chance we may forget about collapsed toolbar, maybe make helper methods which always set it in both places.

Just a random thought whether it would be worth it or better to not couple it, this is not blocking for me

File: Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+
+import Foundation
+import UIKit
+import BraveCore
+import BraveShared
+
+/// A view that displays the tab's secure content state and the URL while scrolling into the page
+class CollapsedURLBarView: UIView {
+  private let stackView = UIStackView().then {
+    $0.axis = .horizontal
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift]: Not needed, should be horizontal by default

File: Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+  }
+  
+  private let lockImageView = ToolbarButton(top: true).then {
+    $0.setImage(UIImage(named: "lock_verified", in: .current, compatibleWith: nil)!.template, for: .normal)
+    $0.isHidden = true
+    $0.tintColor = .bravePrimary
+    $0.isAccessibilityElement = true
+    $0.imageView?.contentMode = .center
+    $0.contentHorizontalAlignment = .center
+    $0.accessibilityLabel = Strings.tabToolbarLockImageAccessibilityLabel
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift:26]: Shouldn't this label be dynamic depending on secure/insecure state?

File: Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+  
+  var secureContentState: TabSecureContentState = .unknown {
+    didSet {
+      updateLockImageView()
+    }
+  }
+  
+  var currentURL: URL? {
+    didSet {
+      urlLabel.text = currentURL.map {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift:63]: Why is this a map over simple `URLFormatter.formatURL(forDisplayOmitSchemePathAndTrivialSubdomains: currentURL.absoluteString)`?

**Review by iccub — CHANGES_REQUESTED** [review]
Left few questions, the only blocking Q about accessibility label on the lock icon

And found few functional blockers, more details on slack

File: Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift (hunk 4 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift:63]: Because `currentURL` is optional, so the map actually gives me a non-optional value, and when its nil simply returns nil instead of executing the map function

File: Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift (hunk 3 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/UrlBar/CollapsedURLBarView.swift:26]: Hmm probably yeah, copy pasted this from URL bar. The string actually reads "Secure connection" so we should probably only set it to that when its actually secure

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: Honestly as it is now there are too many places that set these values in general 😆 I will take a look at merging the setters into 1 spot though

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 5]
```diff
@@ -107,7 +108,7 @@ public class BrowserViewController: UIViewController, BrowserViewControllerDeleg
   fileprivate let crashedLastSession: Bool
 
   // These views wrap the top and bottom toolbars to provide background effects on them
-  var header: UIStackView!
+  var header = HeaderContainerView()
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: does it still have to be `var` btw?

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 5 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: Hmm probably not actually 🙂

**Comment by iccub** [comment]
Functional review passed, works nicely now, good job
