### PR TITLE
Fix #7303: Fix Recently Closed Tabs and Tab Restore

### LINKED ISSUE #7303: Tabs not restoring properly
### Description: 
- Tabs don't restore correctly on development

### Steps to Reproduce 
  1. Install AppStore 1.49.x
  2. Open some tabs
  3. Install Development (Release scheme) 1.51.x

### Actual result: 
- Tabs are not restored

### Expected result:
- Tabs should be restored

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduces

### Brave Version: 

- 1.51.x

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix recently closed crash
- Fix tab restore (rewrote model 20 because somehow the rebase of model 20 onto 19 does NOT work and we have zero idea why!)

This pull request fixes #7303

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -58,7 +58,7 @@ var package = Package(
     .package(url: "https://github.com/apple/swift-algorithms", from: "1.0.0"),
     .package(url: "https://github.com/devxoul/Then", from: "2.7.0"),
     .package(url: "https://github.com/mkrd/Swift-BigInt", from: "2.0.0"),
-    .package(url: "https://github.com/GuardianFirewall/GuardianConnect", exact: "1.8.1"),
+    .package(url: "https://github.com/GuardianFirewall/GuardianConnect", exact: "1.8.3"),
```
Comment (kylehickinson) [inline Package.swift]: Can we put this in a separate PR with a small description of the problem/solution for the future :)

**Review by soner-yuksel — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
