### PR TITLE
Fix #1217: Support PINs for security keys

### LINKED ISSUE #1217: PINS don't work with YubiKeys
Set a PIN on a yubikey, and try to authenticate with webauthn.io. Does not work on current releases.

## Test Plan

Specified here: https://github.com/brave/brave-ios/pull/1303

### PR DESCRIPTION
**Pull request by jumde**
fix #1217 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

1. Set a PIN on your YubiKey using Yubikey Manager
2. Navigate to demo.yubico.com/u2f/
3. Confirm that a PIN is prompted during the registration workflow.
4. Entering a correct PIN should successfully complete registration
5. Entering an incorrect PIN should throw an error.

### Screenshots:

Screen Shot 2019-07-30 at 12 16 06 PM

Screen Shot 2019-07-30 at 12 16 14 PM

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

**Comment by jumde** [comment]
Added a small change for exclude credentials: https://github.com/brave/brave-ios/pull/1303/commits/949394d6911030ec690846de0b55e88ca229fe00 

@Brandon-T  `Exclude Credentials` is optional for the registration request, so using an `Optional type`. Let me know if you have any concerns.

File: Client/U2FExtensions.swift [hunk 1]
```diff
@@ -311,10 +311,10 @@ class U2FExtensions: NSObject {
                 }
                 
                 return credentialDescriptor
-            })
+            }) ?? []
             
-            guard exclusionList.count == publicKey.excludeCredentials.count else {
-                sendFIDO2AuthenticationError(handle: handle)
+            guard (exclusionList.count == 0 && publicKey.excludeCredentials?.count == nil) || (exclusionList.count == publicKey.excludeCredentials?.count) else {
```
Comment (Brandon-T) [inline Client/U2FExtensions.swift]: Hmm this part: `exclusionList.count == 0  && publicKey.excludeCredentials?.count == nil`. Is it correct?

It says (that guard statement is equivalent): 
```swift
if exclusionList.count != 0 || publicKey.excludeCredentials != nil  { 
    sendFIDO2RegistrationError(handle: handle)
}
```

It's optional so we shouldn't have to guard against it being empty. We only need to guarantee that if we receive exclusionList, it maps perfectly which is what `exclusionList.count == publicKey.excludeCredentials?.count` does :)

File: Client/U2FExtensions.swift [hunk 2]
```diff
@@ -465,6 +576,57 @@ class U2FExtensions: NSObject {
...
+            return
+        }
+        popup.dismissWithType(dismissType: .flyDown)
+    }
+    
+    private func handlePinVerificationRequired(completion: @escaping (Bool) -> Void ) {
+        ensureMainThread {
+            let alert = UIAlertController.userTextInputAlert(title: Strings.pinTitle, message: Strings.pinLabel, placeholder: Strings.pinPlaceholder) {
+                pin, _ in
+                if let pin = pin, !pin.isEmpty {
```
Comment (Brandon-T) [inline Client/U2FExtensions.swift:606]: What if these conditions do not hold true? The completion never gets called. Is it correct?

File: Client/U2FExtensions.swift [hunk 3]
```diff
@@ -465,6 +576,57 @@ class U2FExtensions: NSObject {
...
+                        completion(true)
+                        return
+                    }
+
+                    fido2Service.execute(verifyPinRequest) { (error) in
+                        guard error == nil else {
+                            completion(true)
+                            return
+                        }
+                        completion(false)
```
Comment (Brandon-T) [inline Client/U2FExtensions.swift:621]: After calling `completion(false)`, do you need a `return` statement or is showing the alert what you intended? It looks intentional because the same logic is used in `handlePinVerificationRequired`

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/U2FExtensions.swift [hunk 4]
```diff
@@ -84,37 +85,82 @@ class U2FExtensions: NSObject {
     fileprivate var fidoSignRequests: [Int: [FIDOSignRequest]] = [:]
     
     fileprivate static var observationContext = 0
+    fileprivate var popup: AlertPopupView
+    fileprivate var currentMessageType = U2FMessageType.None
+    fileprivate var currentHandle: Int = -1
```
Comment (iccub) [inline Client/U2FExtensions.swift]: `Int` can be removed

File: Client/U2FExtensions.swift [hunk 5]
```diff
@@ -162,10 +208,17 @@ class U2FExtensions: NSObject {
...
+        case #keyPath(YKFKeySession.sessionState):
             ensureMainThread {
                 self.handleSessionStateChange()
             }
+        case #keyPath(YKFKeySession.u2fService.keyState), #keyPath(YKFKeySession.fido2Service.keyState):
+            ensureMainThread {
+                self.presentInteractWithKeyModal()
+            }
+        default:
+            return
```
Comment (iccub) [inline Client/U2FExtensions.swift:221]: Could add a log about unhandled keypath

File: Client/U2FExtensions.swift [hunk 6]
```diff
@@ -319,6 +374,33 @@ class U2FExtensions: NSObject {
         }) }
     }
     
+    private func handleMakeCredential(handle: Int, request: WebAuthnRegisterRequest, error: Error?) {
+        guard let error = error else {
```
Comment (iccub) [inline Client/U2FExtensions.swift:378]: this is wrong, if there's no `error`, rest of the method will never execute
Am I missing something here?

File: Client/U2FExtensions.swift [hunk 7]
```diff
@@ -454,6 +538,33 @@ class U2FExtensions: NSObject {
         }) }
     }
     
+    private func handleGetAssertion(handle: Int, request: WebAuthnAuthenticateRequest, error: Error?) {
+        guard let error = error else {
```
Comment (iccub) [inline Client/U2FExtensions.swift:542]: same as previous comment about `error`

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/U2FExtensions.swift (hunk 1 above)
Comment (jumde) [reply Client/U2FExtensions.swift]: @Brandon-T - `exclusionList.count == publicKey.excludeCredentials?.count` if `publicKey.excludeCredentials` is not present `publicKey.excludeCredentials?.count` is set to `nil` but `exclusionList.count` is `0`.

File: Client/U2FExtensions.swift (hunk 6 above)
Comment (jumde) [reply Client/U2FExtensions.swift:378]: Ideally error should not be `nil` here see: https://github.com/brave/brave-ios/pull/1303/files#diff-1faf1a9d0dd722c9a8d957734c58b2e6R333 - I'll update the code to pass `Error` instead of `Error?` here.

File: Client/U2FExtensions.swift (hunk 5 above)
Comment (jumde) [reply Client/U2FExtensions.swift:221]: @iccub - there can be a lot more keyPaths depending on services that are enabled for the key, I think `log.info("Unhandled keyPath")` should be sufficient here. Let me know if you disagree.

Comment (iccub) [reply Client/U2FExtensions.swift:221]: I'm fine with doing nothing here then, no need to spam with logs :)

File: Client/U2FExtensions.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/U2FExtensions.swift]: @jumde I see what you mean. But in that case, you can do:

`guard exclusionList.count == publicKey.excludeCredentials?.count ?? 0 else {...}` instead.

Rest of stuff works perfectly. UI shows up nicely.

Comment (jumde) [reply Client/U2FExtensions.swift]: Sounds good, thanks!

File: Client/U2FExtensions.swift (hunk 3 above)
Comment (jumde) [reply Client/U2FExtensions.swift:621]: I can add a `return` there, but I don't think it matters. Its just the end of the callback and it will return after invoking `completion(false)`

File: Client/U2FExtensions.swift (hunk 2 above)
Comment (jumde) [reply Client/U2FExtensions.swift:606]: Good catch, fixed: https://github.com/brave/brave-ios/pull/1303/files#diff-1faf1a9d0dd722c9a8d957734c58b2e6R624

File: Client/U2FExtensions.swift (hunk 3 above)
Comment (jumde) [reply Client/U2FExtensions.swift:621]: Done!

**Review by Brandon-T — APPROVED** [review]

**Review by iccub — APPROVED** [review]
