### PR TITLE
Fix #5776: Logic update for showing or hiding buy/send/swap options

### LINKED ISSUE #5776: Wallet: Clear up logic for showing or hiding buy/send/swap options
### Description: 
Currently we have wrong or partially correct logic to determine show or hide buy/send/swap options though out the wallet.

For Buy:
Mobile only support Buy with Wyre right now. 
1. we need to fetch buyable tokens using correct chain id with Wyre provider
2. after compare with desktop, currently there are three networks support buy with Wyre. They are Eth Mainnet, EVM Polygon Mainnet and EVM Acalanche Mainnet

For Send:
No restriction

For Swap:
User api from BraveWalletSwapService.isSwapSupported to show or hide swap option.

### PR DESCRIPTION
**Pull request by nuo-xu**
## Description:
For Buy:
Mobile only support Buy with Wyre right now.

we need to fetch buyable tokens using correct chain id with Wyre provider
after compare with desktop, currently there are three networks support buy with Wyre. They are Eth Mainnet, EVM Polygon Mainnet and EVM Acalanche Mainnet
For Send:
No restriction

For Swap:
User api from BraveWalletSwapService.isSwapSupported to show or hide swap option.

This pull request fixes #5776 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:
Please refer to the issue.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: BraveWallet/WalletConstants.swift [hunk 1]
```diff
@@ -47,6 +47,11 @@ struct WalletConstants {
   
   /// The link for users to learn more about Solana SPL token account creation in transaction confirmation screen
   static let splTokenAccountCreationLink = URL(string: "https://support.brave.com/hc/en-us/articles/5546517853325")!
+  
+  /// Supported networks for buying via Wyre
+  static let supportedBuyWithWyreNetworkChainIds: [String] = [
+    BraveWallet.MainnetChainId
```
Comment (StephenHeaps) [inline BraveWallet/WalletConstants.swift:57]: minor nit: can we reference the #5781 issue here for why Polygon and Avalanche were removed in this PR?

File: BraveWallet/Crypto/BuySendSwap/BuyTokenView.swift [hunk 2]
```diff
@@ -75,41 +83,11 @@ struct BuyTokenView: View {
...
-                  guard let urlString = urlString, let url = URL(string: urlString) else {
-                    return
-                  }
-                  openWalletURL?(url)
-                }
-              }) {
-                Text(Strings.Wallet.buyTestButtonTitle)
-              }
-              .buttonStyle(BraveFilledButtonStyle(size: .normal))
-              .frame(maxWidth: .infinity)
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/BuySendSwap/BuyTokenView.swift:109]: Did we intentionally remove buy functionality for Ropsten / other test networks? Maybe due to faucet being unavailable? Maybe we want to remove the unused localized strings if so.

Comment (nuo-xu) [reply BraveWallet/Crypto/BuySendSwap/BuyTokenView.swift:109]: We no longer support eth testnets in Buy. Will remove related strings.

**Review by StephenHeaps — APPROVED** [review]
