### PR TITLE
Fix #1739 -  Fix AdsNotification not dynamically supporting DarkMode

### LINKED ISSUE #1739: Changing theme during onboarding doesn't change the theme for sample ad
### Description: 
Changing theme during onboarding doesn't change the theme for sample ad

### Steps to Reproduce 
  1. Clean install 1.13
  2. Launch browser and start onboarding 
  3. Toggle device theme via control center, sample ad doesn't get the updated theme

**Actual result:** 
darkads

**Expected result:**
Should update theme automatically

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.18.15)

**Device details:** 
iPhone Xr and iPhone 7+ on iOS 13.2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Cant reproduce it on iPad

### PR DESCRIPTION
**Pull request by Brandon-T**
Fix Trait collection not updating on iOS13 for Ads Notification views when DarkMode is dynamically changed.

## Summary of Changes

This pull request fixes issue #1739

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Ads/AdsViewController.swift [hunk 1]
```diff
@@ -332,3 +332,13 @@ extension AdsViewController {
     })
   }
 }
+
+extension AdsViewController {
+  public override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
+    if #available(iOS 13.0, *) {
```
Comment (kylehickinson) [inline BraveRewardsUI/Ads/AdsViewController.swift:340]: I forget, do you need to call super on this? Also didn't realize Swift let you override functions in extensions now :P

Comment (Brandon-T) [reply BraveRewardsUI/Ads/AdsViewController.swift:340]: Yeah you must call super.

**Review by kylehickinson — APPROVED** [review]
