### PR TITLE
Fix #1805: Show publisher name in the tipping panel

### LINKED ISSUE #1805: Publisher name missing in tips panel
### Description: 
Publisher name missing in tips panel 

### Steps to Reproduce 
  1. Enable rewards
  2. Visit any site and open the tips panel
  3. Publisher name is not shown on the tips panel

**Actual result:** 
image

**Expected result:**
Similar to desktop and Android should show the publisher name
Desktop:
image
Android:
image

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.25.14)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### PR DESCRIPTION
**Pull request by kylehickinson**
Please use rebase merge strategy

## Summary of Changes

This pull request fixes issue #1805 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

| Regular | Media |
| --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2019-10-28 at 15 22 43 | Simulator Screen Shot - iPhone 11 Pro - 2019-10-28 at 15 22 52 |

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Tipping/TippingOverviewView.swift [hunk 1]
```diff
@@ -29,14 +29,17 @@ class TippingOverviewView: UIView {
...
     $0.backgroundColor = UX.faviconBackgroundColor
-    $0.clipsToBounds = true
-    $0.layer.cornerRadius = UX.faviconSize.width / 2.0
     $0.layer.borderColor = UIColor.white.cgColor
     $0.layer.borderWidth = 2.0
   }
   
+  let publisherNameLabel = UILabel().then {
+    $0.appearanceTextColor = .white
+    $0.font = .systemFont(ofSize: 20.0, weight: .medium)
```
Comment (iccub) [inline BraveRewardsUI/Tipping/TippingOverviewView.swift:40]: What if the name is very long, should we shrink it or break to few lines, have you tested it?
How do we do it for other places with pub names?

Comment (kylehickinson) [reply BraveRewardsUI/Tipping/TippingOverviewView.swift:40]: I thought about it, in panel we make it have 2 lines but I think everywhere else it is truncated

Comment (srirambv) [reply BraveRewardsUI/Tipping/TippingOverviewView.swift:40]: On Android it truncates the pub name like this
image

So probably follow the same. Desktop has bigger text area so it shows on a new line

Comment (iccub) [reply BraveRewardsUI/Tipping/TippingOverviewView.swift:40]: Do you want to add it @kylehickinson?
There's method for truncating strings in StringExtensions

Comment (kylehickinson) [reply BraveRewardsUI/Tipping/TippingOverviewView.swift:40]: It will truncate automatically as its constrained to the right side, no need to truncate manually :)

**Review by iccub — APPROVED** [review]

File: BraveRewardsUI/Tipping/TippingOverviewView.swift (hunk 1 above)
Comment (kylehickinson) [reply BraveRewardsUI/Tipping/TippingOverviewView.swift:40]: Simulator Screen Shot - iPhone 11 Pro - 2019-10-28 at 15 43 33
