### PR TITLE
Fix #1923: Shields & Settings Design Update

### LINKED ISSUE #1923: Implement simpler Shield Panel design on iOS
## Description

Implement the simpler shield panel design

## Designs
shields 1

Tapping the help icon will show more information about Brave Shields:

shields 2

Advanced site-specific controls are available in an expand/collapse section, which persists across sites. So if the user expanded Advanced controls on one site, it will still be expanded when they open Shields on a different site.

shields 3

Label changes:

- "Block Ads & Tracking" becomes "Block cross-site trackers"
- "HTTPS Everywhere" becomes "Upgrade connections to HTTPS"
- "Block Phishing and Malware" is moved to "Brave Shields & Privacy" page in global app settings

Tapping "Change global Shields defaults" under Advanced Controls deeplinks the user to the "Brave Shields & Privacy" page pre-scrolled to the "BRAVE SHIELDS GLOBAL DEFAULTS" section:

Settings 2

When Brave Shields is down (whether Advanced controls is expanded or not), users can report a broken site by tapping "Report a broken site"

shields webcompat 1
shields webcompat 2

The confirmation message should dismiss on its own after 1s if the user doesn't tap out first:

shields webcompat 3

### Dark theme
Dark theme is supported. Text, toggles, buttons, links, and icons have lighter colors:

dark theme shields 1
dark theme shields 2
dark theme shields 3
dark theme shields 4
dark theme shields 5
dark theme shields 6

### Landscape mode
This works the same as currently.

shields landscape

### Settings
Since Brave Shields global defaults now has its own page in app settings, make some minor organizational changes to main app settings page as well:

Settings 1

settings refresh overview

### Interaction finesse
The expand/collapse Advanced controls should animate content in:

shields expand collapse

Breakdown: Grow white panel 0.2s, then content fades in Y+10 0.3s

Also, use existing iOS functionality to slide content in from left for each new view.

To add delight to the experience as well as a fun touch complimenting the oversized toggle, implement new color gradient when the toggle is ON:

fabtoggle

it's a loop with 2ms between each color state + easy ease:
linear-gradient(120deg, rgba(255,167,59,1) 0%, rgba(255,118,84,1) 100%);
linear-gradient(120deg, rgba(255,118,84,1) 0%, rgba(251,84,43,1) 100%);
linear-gradient(120deg, rgba(251,84,43,1) 0%, rgba(247,36,28,1) 100%);
linear-gradient(120deg, rgba(247,36,28,1) 0%, rgba(252,79,130,1) 100%);
linear-gradient(120deg, rgba(252,79,130,1) 0%, rgba(255,167,59,1) 100%);
linear-gradient(120deg, rgba(255,167,59,1) 0%, rgba(255,118,84,1) 100%);
#FFA73B :arrow_right: #FF7654 :arrow_right: #FB542B :arrow_right: #F7241C :arrow_right: #FC4F82 :arrow_right: #FFA73B

[fabtoggle.mov.zip](https://github.com/brave/brave-ios/files/4182705/fabtoggle.mov.zip)

## User Flow
prototype

Zipped .mov: 
[prototype.zip](https://github.com/brave/brave-ios/files/4125423/prototype.zip)

### Notes
Shields will still show the "Report a broken site" button when Shields is down even if they have already reported that site.

## Assets
Figma: https://www.figma.com/file/aiHUCYczQPYP1mtGTOZ5NJ/Sketchimport-ios-shields?node-id=0%3A231

[icons.zip](https://github.com/brave/brave-ios/files/4125506/icons.zip)
[settings icons.zip](https://github.com/brave/brave-ios/files/4187837/settings.icons.zip)

### PR DESCRIPTION
**Pull request by kylehickinson**
Can be squash merged

## Summary of Changes

This pull request fixes #1923 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Verify shields act as usual
- Verify shields icon on NTP is disabled like desktop
- Verify global shields act as usual
- Verify all settings toggles act as normal (a number of them have moved)
- Verify new design (themes, desktop parity, etc.)
- Verify new report a site functionality (may require asking @aekeus) 

## Screenshots:

<details>
<summary><strong>Shields On</strong></summary>

| Basic | Advanced | Scrolled | Info |
| --- | --- | --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 17 59 50 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 17 59 53 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 17 59 55 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 17 59 57 |

</details>

<details>
<summary><strong>Shields Off</strong></summary>
 
| Basic | Report Site | Reported |
| --- | --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 18 00 01 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 18 00 04 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 18 00 06 |

</details>

<details>
<summary><strong>Dark Mode</strong></summary>

</details>

<details>
<summary><strong>Settings</strong></summary>

| Base | Scrolled |
| --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 18 04 51 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 18 05 00 |

| Shields & Privacy | Scrolled |
| --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 18 05 14 | Simulator Screen Shot - iPhone 11 Pro - 2020-08-31 at 18 05 16 |

</details>

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift [hunk 1]
```diff
@@ -0,0 +1,328 @@
...
+import Shared
+import BraveShared
+
+private let log = Logger.browserLogger
+
+class BraveShieldsAndPrivacySettingsController: TableViewController {
+    let profile: Profile
+    let tabManager: TabManager
+    
+    init(profile: Profile, tabManager: TabManager) {
```
Comment (iccub) [inline Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift]: The only kind of bug i'm able to find nowadays :D this VC doesn't deinitialize correctly

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 2]
```diff
@@ -63,7 +63,11 @@ class SettingsViewController: TableViewController {
         self.tabManager = tabManager
         self.rewards = rewards
         
-        super.init(style: .grouped)
+        if #available(iOS 13.0, *) {
+            super.init(style: .insetGrouped)
```
Comment (iccub) [inline Client/Frontend/Settings/SettingsViewController.swift:69]: this VC also doesn't deinit

File: Client/Frontend/Shields/AdvancedShieldsView.swift [hunk 3]
```diff
@@ -0,0 +1,258 @@
...
+            }
+            
+            stackView.addArrangedSubview(titleLabel)
+            stackView.addArrangedSubview(toggleSwitch)
+            
+            titleLabel.text = title
+            toggleSwitch.addTarget(self, action: #selector(switchValueChanged), for: .valueChanged)
+            
+            toggleSwitch.setContentHuggingPriority(.required, for: .horizontal)
+//            titleLabel.setContentCompressionResistancePriority(.required, for: .vertical)
```
Comment (iccub) [inline Client/Frontend/Shields/AdvancedShieldsView.swift]: comment

File: Client/Frontend/Shields/ShieldsViewController.swift [hunk 4]
```diff
@@ -145,25 +216,110 @@ class ShieldsViewController: UIViewController, PopoverContentComponent {
...
+        updateContentView(to: shieldsView.reportBrokenSiteView, animated: true)
+    }
+    
+    @objc private func tappedCancelReportingButton() {
+        updateContentView(to: shieldsView.stackView, animated: true)
+    }
+    
+    @objc private func tappedSubmitReportingButton() {
+        if let url = url {
+            WebcompatReporter.reportIssue(on: url)
```
Comment (iccub) [inline Client/Frontend/Shields/ShieldsViewController.swift:314]: Do we care if the user has default or mobile ua when reporting broken site?
If so we should pass it here, we have access to `tab` from this place

File: Client/Frontend/Shields/SiteReportedView.swift [hunk 5]
```diff
@@ -0,0 +1,57 @@
+// Copyright 2020 The Brave Authors. All rights reserved.
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import UIKit
+import Shared
+import BraveShared
+
+class SiteReportedView: UIStackView, Themeable {
```
Comment (iccub) [inline Client/Frontend/Shields/SiteReportedView.swift:10]: What do you think about auto dismissing this view after few seconds?

**Review by iccub — CHANGES_REQUESTED** [review]
looks nice, good job on accessibility polish,
I have to take a second look at clear-priv-data changes

todo:
look for retain cycles in setting screen and shield settings screen
check if we have to pass correct user agent(mobile or desktop) to the web compat reporter

File: Client/Frontend/Shields/SimpleShieldsView.swift [hunk 6]
```diff
@@ -38,42 +38,87 @@ class SimpleShieldsView: UIView, Themeable {
...
+            stackView.snp.makeConstraints {
+                $0.edges.equalToSuperview()
+            }
+        }
+        
+        override var accessibilityLabel: String? {
+            get {
+                [countLabel.accessibilityLabel, Strings.Shields.blockedCountLabel]
+                    .compactMap { $0 }
+                    .joined(separator: ".")
```
Comment (kylehickinson) [inline Client/Frontend/Shields/SimpleShieldsView.swift]: Todo: `.` → `. ` (space after)

File: BraveUI/Popover/PopoverNavigationController.swift [hunk 7]
```diff
@@ -98,6 +98,25 @@ open class PopoverNavigationController: UINavigationController, PopoverContentCo
   override public func preferredContentSizeDidChange(forChildContentContainer container: UIContentContainer) {
     self.preferredContentSize = container.preferredContentSize
   }
+  
+  /// The last visible controller to be popped from this navigation controller
+  ///
+  /// Used because when you pop a controller off the stack it is no longer listed within
+  /// `viewControllers`, or set as `visibleViewController` even if the animation is still
+  /// ongoing.
+  weak var lastPoppedController: UIViewController?
```
Comment (kylehickinson) [inline BraveUI/Popover/PopoverNavigationController.swift]: Self-review: should be `private(set)`

File: Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift]: Lol I really have to remember to check this before submitting PRs 😂

File: Client/Frontend/Shields/ShieldsViewController.swift (hunk 4 above)
Comment (kylehickinson) [reply Client/Frontend/Shields/ShieldsViewController.swift:314]: We pass in the UA set up in AppDelegate. I'm not sure that it matters which UA is used because the reporter endpoint only uses it to categorize the OS as iOS

Comment (iccub) [reply Client/Frontend/Shields/ShieldsViewController.swift:314]: sounds good, can leave it as it is

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Settings/SettingsViewController.swift:69]: Turns out this VC never deinit'd even before this PR, fixed it though :)

File: Client/Frontend/Shields/SiteReportedView.swift (hunk 5 above)
Comment (kylehickinson) [reply Client/Frontend/Shields/SiteReportedView.swift:10]: Just tested desktop and it actually dismisses automatically after 5s, so I'll add auto-dismissal too, but 5s seems too long for mobile, going to shorten it

File: Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift]: Fixed

**Review by iccub — APPROVED** [review]
Good job, can be merged now after resolving conflicts
