### PR TITLE
Fix:3415: Selecting a custom search engine as default removes it from custom search engine list

### LINKED ISSUE #3415: Selecting a custom search engine as default removes it from custom search engine list
### Description: 
Selecting a custom search engine as default removes it from custom search engine list

### Steps to Reproduce 
  1. Add GH as a custom search engine
  2. Set GH as default SE, removes it from custom search engine list
  3. Set Bing as default SE, GH is added back to custom search engine list

**Actual result:** 

https://user-images.githubusercontent.com/17010094/111311292-f1ae3480-8655-11eb-8319-9649c5286afd.MP4

**Expected result:**
Not sure

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24

**Device details:** 
iPhone 7+ (iOS 14.4)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel  @anthonypkeane

### PR DESCRIPTION
**Pull request by soner-yuksel**
Adding back the custom search engine to the list if it is selected as default and disabling deletion for that row

## Summary of Changes

This pull request fixes #3415

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Add GH as a custom search engine
- Set GH as default SE and see it is not removed from the list
- Try to delete the engine while set as default and see option is not enable

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Settings/SearchSettingsTableViewController.swift [hunk 1]
```diff
@@ -290,6 +289,15 @@ class SearchSettingsTableViewController: UITableViewController {
             }
         }
     }
+    
+    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
+        if let engine = customSearchEngines[safe: indexPath.row],
+           engine == searchEngines.defaultEngine(forType: .standard) {
```
Comment (iccub) [inline Client/Frontend/Settings/SearchSettingsTableViewController.swift:295]: Should we make a check for `privateBrowsing` mode too?
What if user sets it for priv mode

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/Settings/SearchSettingsTableViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Settings/SearchSettingsTableViewController.swift:295]: They cant set it for Private mode, it was one of the security requirements so we disabled.
https://github.com/brave/brave-ios/pull/3350 you can see the change here.

**Review by iccub — APPROVED** [review]
