### PR TITLE
Fix #3665 - Performance issues with playlist

### LINKED ISSUE #3665: Add to playlist option freezes on 3aw.com
### Description: 
Reported here

### Steps to Reproduce 
  1. Go to https://www.3aw.com.au/brett-ratten-responds-to-max-king-critics/
  2. Scroll down to audio player, play it

**Actual result:** 
Notice it freezed the app for few seconds

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Removed all mutation observers in favour of overridden properties.
- Move all JS communication to a background queue and dispatch to main only when necessary.
- Changed `AVAsset.isPlayable` to load asynchronously.

This pull request fixes #3665

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

For testing:

Go to YouTube or any media site
Make sure network link conditioner is set to very very bad network
While the site is loading, keep trying to scroll the page.
if the page doesn't scroll properly or exhibits freezing, we have a problem.
If the page does scroll and load correctly, the toast will come up properly without lagging.
Page overall should be much snappier.
Tested:

I tested on YouTube, SoundCloud, Vimeo, dailymotion, twitch. Note for SoundCloud you have to press play first then attempt to scroll while it is loading.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/UserContent/UserScripts/Playlist.js [hunk 1]
```diff
@@ -237,50 +237,28 @@ window.__firefox__.includeOnce("$<Playlist>", function() {
...
-                            }
-                        });
-                    });
-                });
-                node.observer.observe(node, { subtree: true, childList: true });
-            }
-        }
-
-        function $<observeDynamicElements>(node) {
+        /*function $<observeDynamicElements>(node) {
```
Comment (jumde) [inline Client/Frontend/UserContent/UserScripts/Playlist.js]: nit: can we remove the code instead of commenting it out?

**Review by jumde — APPROVED** [review]
++

**Review by iccub — CHANGES_REQUESTED** [review]
Remove commented out code, rest looks good

**Review by iccub — APPROVED** [review]

**Comment by Brandon-T** [comment]
For testing:
- Go to YouTube or any media site
- Make sure network link conditioner is set to very very bad network
- While the site is loading, keep trying to scroll the page.
- if the page doesn't scroll properly or exhibits freezing, we have a problem.
- If the page does scroll and load correctly, the toast will come up properly without lagging.
- Page overall should be much snappier.

Tested:
- I tested on YouTube, SoundCloud, Vimeo, dailymotion, twitch. Note for SoundCloud you have to press play first then attempt to scroll while it is loading.
