### PR TITLE
Fix #3171: High input lag when typing in url bar.

### LINKED ISSUE #3171: High input lag when typing in url bar.
### Steps to Reproduce 
  1. Open url bar
  2. Start typing quickly
  3.

**Actual result:** 
Notice how slow it is

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
BraveCore `Bookmarkv2.byFrequency` runs on main thread,
and is not performant in general. Takes about 200ms per query.
This commit moves this operation to a background cancellable thread.

I cleaned up search loader code as well.

## Summary of Changes

This pull request fixes #3171 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/FrecencyQuery.swift [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+            .map { Site(url: $0.url ?? "", title: $0.title ?? "") }
+        cancellable = DispatchWorkItem {
+            // brave-core fetch can be slow over 200ms per call,
+            // a cancellable serial queue is used for it.
+            let bookmarkSites = Bookmarkv2.byFrequency(query: query)
+                .map { Site(url: $0.url ?? "", title: $0.title ?? "", bookmarked: true) }
+            
+            let result = Set<Site>(historySites + bookmarkSites)
+            
+            completion(result)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/FrecencyQuery.swift]: Why not dispatch this to main in this function rather than in the call site?

Comment (iccub) [reply Client/Frontend/Browser/FrecencyQuery.swift]: I'll change it,
I did not dispatch on main here because we do additional processing after completion:
```
for site in result {
                    if let completion = self.completionForURL(site.url) {
```

My goal was to move as much code as possible on background thread to reduce UI lag, this code is called on each key stroke

Comment (kylehickinson) [reply Client/Frontend/Browser/FrecencyQuery.swift]: Gotcha, yeah I saw there was further processing, just wanted to make sure it was intentional since it breaks usual convention. If we're keeping it maybe just add documentation mentioning it calls completion on a background queue

**Review by kylehickinson — APPROVED** [review]
