### PR TITLE
Fix #7312: Reset wallet from app settings does not hide wallet sections

### LINKED ISSUE #7312: Reset wallet does not hide wallet specific sections
### Description: 

Reset wallet does not hide wallet specific sections until settings is closed and re-opened _only when opened from main app settings_.

### Steps to Reproduce 
  1. Tap `...` menu and tap Settings
  2. Tap 'Reset Brave Wallet' and confirm the reset on the alert
  3. Observe Wallet settings are still visible until Web3 Settings is closed and re-opened.

### Actual result: 

https://user-images.githubusercontent.com/5314553/233715093-33040073-309b-49a3-af83-d79ed317d2a5.mp4

### Expected result:

Hide the wallet specific settings that are hidden when wallet is not setup.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

This does not occur when resetting wallet from within Brave Wallet -> Settings (only occurs when reset from main app settings):

https://user-images.githubusercontent.com/5314553/233715230-2fa8835c-ec4a-40b3-8f79-1b117a846ca4.mp4

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Small regression in https://github.com/brave/brave-ios/pull/6923/files caused us to no longer observe changes to `isDefaultKeyringCreated` which was being used to determine if we hide or show these Wallet specific settings sections

This pull request fixes #7312

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Setup or restore a wallet if one is not setup
2. Visit main app settings via `...` menu in Browser view.
3. Tap `Web3` section
4. Tap `Reset Brave Wallet` and confirm the reset on the alert
5. Verify Wallet specific sections are removed (everything above & including `Reset Brave Wallet` row)

## Screenshots:

https://user-images.githubusercontent.com/5314553/233716517-c8abc482-e9b2-4495-bc43-6c1359df4040.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Settings/Web3SettingsView.swift [hunk 1]
```diff
@@ -171,6 +171,17 @@ private struct WalletSettingsView: View {
   }
 
   var body: some View {
+    if !keyringStore.isDefaultKeyringCreated {
```
Comment (iccub) [inline Sources/BraveWallet/Settings/Web3SettingsView.swift]: maybe reverse this condition, easier to read :D

**Review by iccub — APPROVED** [review]

File: Sources/BraveWallet/Settings/Web3SettingsView.swift [hunk 2]
```diff
@@ -171,6 +171,17 @@ private struct WalletSettingsView: View {
...
+      // `KeyringStore` is optional in `Web3SettingsView`, but observed here.
+      // When wallet is reset, we need SwiftUI to be notified `isDefaultKeyringCreated`
+      // changed so we can hide Wallet specific sections
+      EmptyView()
+    } else {
+      sections
+    }
```
Comment (kylehickinson) [inline Sources/BraveWallet/Settings/Web3SettingsView.swift]: You can technically just do 

```swift
if keyringStore.isDefaultKeyringCreated {
  sections
}
```

The ViewBuilder will implicitly make an `EmptyView` for the else state

Comment (StephenHeaps) [reply Sources/BraveWallet/Settings/Web3SettingsView.swift]: Good point. I think I will leave it as-is for now so we can include the comment and don't mistakenly keep this section around in the future 🙂.

File: Sources/BraveWallet/Settings/Web3SettingsView.swift (hunk 1 above)
Comment (StephenHeaps) [reply Sources/BraveWallet/Settings/Web3SettingsView.swift]: Thanks! Addressed in [fb3d6ac](https://github.com/brave/brave-ios/pull/7313/commits/fb3d6ac5439f566883c0bbfa176492266ac6b3d0)

**Review by nuo-xu — APPROVED** [review]
