### PR TITLE
Fix #5243: Update network session publisher API to receive on main queue

### LINKED ISSUE #5243: Adding custom search engine through keyboard shortcut will crash app
### Description: 
When adding custom search engine from the magnifying glass icon in the keyboard shortcuts, app will crash. 

```
{"app_cohort":"2|date=1649451600000&sf=143441&tid=b67027331fbbd99fa0be6856ee5abe3d9b644270fb19e19e37c5ff605f18df7a&ttype=i","app_name":"Client","app_version":"1.38","timestamp":"2022-04-11 12:24:51.00 -0700","slice_uuid":"97d04663-51c6-3aec-9931-a38a8942786a","adam_id":"1052879175","build_version":"22.4.8.16","platform":2,"bundleID":"com.brave.ios.browser","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 15.2.1 (19C63)","incident_id":"C086A10E-421B-463F-8A5C-F62BC2D0ADA2","name":"Client","is_beta":1}
{
  "uptime" : 420000,
  "procLaunch" : "2022-04-08 14:24:05.4906 -0700",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad7,11",
  "procStartAbsTime" : 9851889957666,
  "coalitionID" : 942,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 15.2.1",
    "releaseType" : "User",
    "build" : "19C63"
  },
  "captureTime" : "2022-04-11 12:24:49.3457 -0700",
  "incident" : "C086A10E-421B-463F-8A5C-F62BC2D0ADA2",
  "bug_type" : "309",
  "pid" : 39982,
  "procExitAbsTime" : 10258622621439,
  "cpuType" : "ARM-64",
  "procName" : "Client",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/3790F113-B432-4507-BF65-FCBD1D55610C\/Client.app\/Client",
  "bundleInfo" : {"CFBundleShortVersionString":"1.38","CFBundleVersion":"22.4.8.16","CFBundleIdentifier":"com.brave.ios.browser","DTAppStoreToolsBuild":"13E500"},
  "storeInfo" : {"itemID":"1052879175","storeCohortMetadata":"2|date=1649451600000&sf=143441&tid=b67027331fbbd99fa0be6856ee5abe3d9b644270fb19e19e37c5ff605f18df7a&ttype=i","entitledBeta":true,"deviceIdentifierForVendor":"BEA0E447-50BB-4A49-A5FD-5DE3818ECF45","softwareVersionExternalIdentifier":"86815037","applicationVariant":"1:iPad7,11:15","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.brave.ios.browser",
  "isBeta" : 1,
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
```

### Steps to Reproduce 
  1. Navigate to wikipedia
  2. Open an article 
  3. Tap on the search field to type
  4. Tap the magnifying glass keyboard icon to add custom search engine

**Actual result:** 

https://user-images.githubusercontent.com/17885425/162818444-6246bca3-d739-43bc-99e4-4711c9e4ebf2.MP4

**Expected result:**
Custom Search should be added

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.38 (22.4.8.16)

**Device details:** 
iPhone 12, iPhone X, iPad. iOS 15.x, iOS 14.x

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
[crash_report_custome_search.log](https://github.com/brave/brave-ios/files/8467313/crash_report_custome_search.log)

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #5243

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Client/Networking/NetworkSession.swift [hunk 1]
```diff
@@ -62,6 +62,7 @@ extension URLSession: NetworkSession {
     return self.dataTaskPublisher(for: urlRequest)
       .map({ ($0, $1) })
       .mapError({ $0 as Error })
+      .receive(on: DispatchQueue.main)
```
Comment (kylehickinson) [inline Client/Networking/NetworkSession.swift:65]: @Brandon-T I assume the prior closure-based version used to jump to main for the completion handler since this crash is a regression, so I think receiving on `main` for all network session tasks is probably fine. Let me know if there's any case where this doesn't work

**Review by Brandon-T — APPROVED** [review]
