### PR TITLE
Fix #5189: Clear ETH permissions when resetting wallet, clearing cookies & site data

### LINKED ISSUE #5189: Clear ETH permissions when resetting wallet, clearing site data
### Description: 
When we reset wallet from wallet settings, or clear site data we should remove ETH permissions from the `Domain`

### Steps to Reproduce 
  1. Open a dapps site like app.uniswap.org
  2. Connect one of your wallet accounts
  3. Reset wallet from wallet settings
  4. Restore / add a new wallet (different account than previous)
  5. Open the same dapps site like app.uniswap.org
  6. Open wallet panel from URL bar
  7. Tap 'Connected...' to view the connected accounts (might need PR #5186). The header will state n+1 accounts connected but only list the accounts in the current wallet (the previously connected account is not shown as a row) because we didn't clear eth permissions for this domain.

**Actual result:** 
Screen Shot 2022-03-31 at 1 29 04 PM

**Expected result:**
Header only lists same # of accounts as shown in account rows, `Domain` data cleared on reset

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

https://github.com/brave/brave-ios/pull/5147/files#r833678892

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Update 'Reset Wallet' action to remove all ETH Permissions
- Update 'Clear Data Now' action with 'Cookies and Site Data' toggle enabled

This pull request fixes #5189 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Reset Wallet:
1. Connect Wallet / a wallet account to a dapp site like [app.uniswap.org](https://app.uniswap.org/#/swap)
2. Open wallet settings
3. Tap 'Reset Wallet'
4. Restore the same wallet / account used in step 1
5. Visit the same dapp site connected in step 1
6. You should be prompted to connect the wallet/account again, as permissions were cleared

Clear Cookies and Site Data:
1. Connect Wallet / a wallet account to a dapp site like [app.uniswap.org](https://app.uniswap.org/#/swap)
2. Open Settings -> Brave Shields & Privacy and toggle on 'Cookies and Site Data' in the 'Clear Private Data' section.
3. Visit the same dapp site connected in step 1
4. You should be prompted to connect the wallet/account again, as permissions were cleared

## Screenshots:
Reset Wallet:

https://user-images.githubusercontent.com/5314553/163427433-570b0090-a7a7-416a-a4dc-3d10dddd4a13.mov

Clear Cookies and Site Data:

https://user-images.githubusercontent.com/5314553/163427460-950bb341-f1f5-4fa4-ae69-0d8db27b2776.mov

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Wallet/WalletProviderConstants.swift [hunk 1]
```diff
@@ -27,6 +27,6 @@ extension Web3ProviderEvent {
     .init("chainChanged", arguments: chainId)
   }
   static func ethereumAccountsChanged(accounts: [String]) -> Self {
-    .init("accountsChanged", arguments: accounts.first)
+    .init("accountsChanged", arguments: accounts.first ?? "")
```
Comment (nuo-xu) [inline Client/Wallet/WalletProviderConstants.swift]: rebasing first?

Comment (StephenHeaps) [reply Client/Wallet/WalletProviderConstants.swift]: Rebased now thanks 👍

File: Data/models/Domain.swift [hunk 2]
```diff
@@ -158,6 +158,26 @@ public final class Domain: NSManagedObject, CRUD {
...
+      } catch {
+        let fetchError = error as NSError
+        print(fetchError)
+      }
+
+      DispatchQueue.main.async {
+        completionOnMain?()
+      }
+    }
+  }
```
Comment (nuo-xu) [inline Data/models/Domain.swift:187]: can we add a unit test for this static function?

Comment (StephenHeaps) [reply Data/models/Domain.swift:187]: [405005e](https://github.com/brave/brave-ios/pull/5258/commits/405005e617494ea5fbe9515bdb740c5b2a5fd6c7)

File: Data/models/Domain.swift [hunk 3]
```diff
@@ -158,6 +158,26 @@ public final class Domain: NSManagedObject, CRUD {
...
+      let fetchRequest = NSFetchRequest<Domain>()
+      fetchRequest.entity = Domain.entity(context)
+      do {
+        let results = try context.fetch(fetchRequest)
+        results.forEach {
+          $0.wallet_permittedAccounts = nil
+        }
+      } catch {
+        let fetchError = error as NSError
+        print(fetchError)
```
Comment (kylehickinson) [inline Data/models/Domain.swift]: Use Logger if we're gonna log something instead of print

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -394,6 +394,10 @@ class BrowserViewController: UIViewController, BrowserViewControllerDelegate {
             let provider = self.braveCore.walletProvider(with: self, isPrivateBrowsing: tab.isPrivate) else {
         return nil
       }
+      if let keyringService = BraveWallet.KeyringServiceFactory.get(privateMode: tab.isPrivate) {
+        tab.walletKeyringService = keyringService
+        keyringService.add(tab)
+      }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Maybe better to put this where `makeWalletProvider` is actually called, not inside the closure

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Data/models/Domain.swift [hunk 5]
```diff
@@ -158,6 +158,33 @@ public final class Domain: NSManagedObject, CRUD {
...
+        log.error("Clear ethereum permissions error: \(error)")
+      }
+
+      DispatchQueue.main.async {
+        completionOnMain?()
+      }
+    }
+  }
+
+  public static func clearAllEthereumPermissions() async {
```
Comment (kylehickinson) [inline Data/models/Domain.swift]: I think we need to isolate this to `@MainActor`

Comment (StephenHeaps) [reply Data/models/Domain.swift]: Fixed in [40664d2](https://github.com/brave/brave-ios/pull/5258/commits/40664d291f2b879536832e3581fffe73cc683f7f)

**Review by kylehickinson — APPROVED** [review]
