### PR TITLE
Fix #3760 - Fix Brave-Talk and Youtube not working when tabs are switched

### LINKED ISSUE #3760: Investigate Brave talk audio video when app is background or tab is switched
Currently when you switch tabs or lock the screen, audio stops working.
We have to see what can be done on iOS side and implement it if needed

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- On iOS 14.5+ Allow tabs to keep playing media even when it is not the currently visible.

This pull request fixes #3760

## Submitter Checklist:

- [X] *Unit Tests* are updated to cover new or changed functionality
- [X] User-facing strings use `NSLocalizableString()`

## Test Plan:
Must be done on a iOS 14.5+ device

1. Go to youtube, play a video.
2. Switch tabs.
**Expected**: Video MUST still be playing without stopping or pausing.

--

1. Go to together.brave.com on computer.
2. Join call with “Desktop” user name or w/e.
3. Go to the same URL on mobile.
4. Join call with “Mobile” user name or w/e.
5. Turn on microphone on Mobile, but disable on Desktop.
6. Switch tabs on Mobile.
**Expected**: MUST still hear microphone coming from Mobile through to Desktop.

8. Turn on webcam on Mobile, switch tabs.
**Expected**: MUST see yourself on Desktop from Mobile camera even with mobile tab inactive.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]
good job finding this api

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2102,7 +2102,24 @@ extension BrowserViewController: TabManagerDelegate {
...
             wv.accessibilityElementsHidden = true
             wv.accessibilityIdentifier = nil
-            wv.removeFromSuperview()
+            
+            // Firefox code removed webview from superview,
+            // but this causes PDFs to stop rendering,
+            // audio and video to stop playing, etc..
+            for tab in tabManager.allTabs where tab != selected {
+                if let webView = tab.webView {
+                    if #available(iOS 14.5, *) {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:2112]: Should we add `else` here to always remove webview for <14.5?

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — APPROVED** [review]
