### PR TITLE
Fix #3215:  Removing Selected Tab Assertion

### LINKED ISSUE #3215: Removing Selected Tab Assertion
### Description: 
One of the highest velocity crashes is pointing out to selectTab inside TabManager. If we check Stack Trace this crash is related with TabTrayController and previously this crash has been fixed in https://github.com/brave/brave-ios/issues/3041

So in order have a better insight about the problem the assertion is removed and a guard is added with a logger inside.

### Steps to Reproduce 
We need a quick sanity check in order to be sure this change doesn't effect anything while selecting a tab.

Steps for sanity check Test Plan:
  1. Create new tabs with different URLs and check selecting different tabs work (normal/private)
  2. Put application in background while some tabs are open and click an external link from a different application - Brave Browser should be default browser
  3. Open Tab Tray while some tabs open, put the application in background without closing the TabTray and click an external link from a different application while Brave Browser is default Browser
 

**Actual result:**
Nothing out of ordinary happens

**Expected result:**
After sanity check, select tab related functionality should work properly. Test Plan is shared under Steps to Reproduce

**Reproduces how often:
N/A

**Brave Version:** 
Version 1.22.2 (21.1.20.17)

**Device details:**
Any model iPhone and iPad

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

Actually this assertion should be hit in Release build but wanted to test how Stack Trace will change when we are not checking actual tab is nit pointing to the same memory location with selected tab.

This pull request fixes #3215

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

Sanity check:

- Create new tabs with different URLs and check selecting different tabs work (normal/private)
- Put application in background while some tabs are open and click an external link from a different application - Brave Browser should be default browser
- Open Tab Tray while some tabs open, put the application in background without closing the TabTray and click an external link from a different application while Brave Browser is default Browser

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/TabManager.swift [hunk 1]
```diff
@@ -244,8 +244,6 @@ class TabManager: NSObject {
             selectedTab?.createWebview()
             restoreTab(t)
         }
-
-        assert(tab === selectedTab, "Expected tab is selected")
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabManager.swift:247]: Can we replace this with a check and `log.error` + some info like the current tab, what the selected one is, etc. in case we notice it happen locally

Comment (soner-yuksel) [reply Client/Frontend/Browser/TabManager.swift:247]: Requested change at https://github.com/brave/brave-ios/pull/3212/commits/6a6d16f0075982a5f5dcda2d86333c13fa81bd2d

**Review by kylehickinson — APPROVED** [review]
