### PR TITLE
Fix #2961: Problems with Sharing a PDF File / Additional Share Issues

### LINKED ISSUE #2961: Problems with Sharing a PDF File
### Description: 

While Sharing a PDF file in Brave browser, some of the applications have problems.

- Mail app: Instead of attaching the PDF file, the URL of the PDF file is copied as message.
- iBooks: A pop-up showing "Creating a PDF" is shown and nothing happens

### Steps to Reproduce 
  1. Open a PDF file in the browser
  2. Tap 'share'
  3. Share vie 'Books.app.

**Actual result:** 
Nothing happens

**Expected result:**
- Mail app: Should Attach the PDF to Template Email
- iBooks: Should save the PDF to Books

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.20

**Device details:** 
iOS 14, did not check previous versions

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Reported by @PrivacyMatters

### PR DESCRIPTION
**Pull request by soner-yuksel**
Fixed:

Sharing PDF file with iBooks and Mail app.
Sharing Function inside a website with whatsapp will work properly
Creating PDF from the WebPage and passing it to iBooks If activity is chosen
Sharing Downloaded Files

## Summary of Changes

This pull request fixes #2961 / Adding "whatsapp" "http" " https" as Query Schemes

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Load Brave Browser with a PDF link and Press Share from Menu
- Choose iBook Apps for sharing or Mail

- Load a website that has whatsapp share
- Press share and observe the pop up for permission

## Screenshots:

ezgif-6-20b0e9d7d636

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — CHANGES_REQUESTED** [review]
Doesn't seem to work for me,
tried with this link http://wbia.tu.kielce.pl/wp-content/uploads/2019/10/BN1-3-004_wytrzymalosc_materialow-1-B1N.pdf

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2730,7 +2748,7 @@ extension BrowserViewController: TabManagerDelegate {
 }
 
 /// List of schemes that are allowed to be opened in new tabs.
-private let schemesAllowedToBeOpenedAsPopups = ["http", "https", "javascript", "about"]
+private let schemesAllowedToBeOpenedAsPopups = ["http", "https", "javascript", "about", "whatsapp"]
```
Comment (jumde) [inline Client/Frontend/Browser/BrowserViewController.swift:2756]: nit: add a manual test for this new scheme.

File: Client/Frontend/Share/ShareExtensionHelper.swift [hunk 2]
```diff
@@ -54,27 +66,69 @@ class ShareExtensionHelper: NSObject {
...
+                    if let logins = returnedItems {
+                        self.fillPasswords(logins as [AnyObject])
+                    }
                 }
-            }
 
-            completionHandler(completed, activityType)
+                completionHandler(completed, activityType, nil)
+            } else {
+                self.writeWebPagePDFDataToURL { url, error in
```
Comment (jumde) [inline Client/Frontend/Share/ShareExtensionHelper.swift:93]: same with .mail right?

File: Client/Frontend/Share/ShareExtensionHelper.swift [hunk 3]
```diff
@@ -54,27 +66,69 @@ class ShareExtensionHelper: NSObject {
...
+            
+            webView.createPDF { result in
+                dispatchPrecondition(condition: .onQueue(.main))
+                
+                switch result {
+                case .success(let data):
+                    let validFilenameSet = CharacterSet(charactersIn: ":/")
+                        .union(.newlines)
+                        .union(.controlCharacters)
+                        .union(.illegalCharacters)
```
Comment (jumde) [inline Client/Frontend/Share/ShareExtensionHelper.swift:114]: @soner-yuksel - do you have examples of filenames in which `controlCharacters` and `illegalCharacters` are part of the filename?

File: Client/Frontend/Share/ShareExtensionHelper.swift [hunk 4]
```diff
@@ -9,18 +9,30 @@ import OnePasswordExtension
...
+        case `default`
+    }
+    
     fileprivate weak var selectedTab: Tab?
 
     fileprivate let selectedURL: URL
     fileprivate var onePasswordExtensionItem: NSExtensionItem!
     fileprivate let browserFillIdentifier = "org.appextension.fill-browser-action"
 
+    fileprivate func isFile(url: URL) -> Bool { url.scheme == "file" }
```
Comment (iccub) [inline Client/Frontend/Share/ShareExtensionHelper.swift]: maybe it's worth adding a helper method in a URL extension, we have `URLExtensions` file for it

File: Client/Frontend/Share/ShareExtensionHelper.swift [hunk 5]
```diff
@@ -54,27 +66,69 @@ class ShareExtensionHelper: NSObject {
...
-            if UIPasteboard.general.hasURLs, let url = UIPasteboard.general.urls?.first {
-                UIPasteboard.general.urls = [url]
-            }
+        activityViewController.completionWithItemsHandler = { [weak self] activityType, completed, returnedItems, activityError in
+            guard let self = self else { return }
             
-            if self.isPasswordManagerActivityType(activityType.map { $0.rawValue }) {
-                if let logins = returnedItems {
-                    self.fillPasswords(logins as [AnyObject])
+            if self.shareActivityType(activityType.map { $0.rawValue }) != .iBooks { //!self.isOpenInIBooksActivityType(activityType.map { $0.rawValue }) {
```
Comment (iccub) [inline Client/Frontend/Share/ShareExtensionHelper.swift]: is this comment still needed?

File: Client/Frontend/Share/ShareExtensionHelper.swift [hunk 6]
```diff
@@ -54,27 +66,69 @@ class ShareExtensionHelper: NSObject {
...
+                    completionHandler(completed, activityType, nil)
+                    return
+                }
+                // Bug 1392418 - When copying a url using the share extension there are 2 urls in the pasteboard.
+                // This is a iOS 11.0 bug. Fixed in 11.2
+                if UIPasteboard.general.hasURLs, let url = UIPasteboard.general.urls?.first {
+                    UIPasteboard.general.urls = [url]
+                }
+                
+                if self.shareActivityType(activityType.map { $0.rawValue }) != .password { //self.isPasswordManagerActivityType(activityType.map { $0.rawValue }) {
```
Comment (iccub) [inline Client/Frontend/Share/ShareExtensionHelper.swift]: is this comment still needed?

**Review by iccub — APPROVED** [review]
works for me :)

File: Client/Frontend/Share/ShareExtensionHelper.swift (hunk 4 above)
Comment (soner-yuksel) [reply Client/Frontend/Share/ShareExtensionHelper.swift]: Good idea !

File: Client/Frontend/Share/ShareExtensionHelper.swift (hunk 2 above)
Comment (soner-yuksel) [reply Client/Frontend/Share/ShareExtensionHelper.swift:93]: No this is actually sharing the website itself so in mail sharing, it needs to share the link directly which it does right now. However if it is a url that opens a pdf in browser, it is creating a temporary document and attaches it to mail.

File: Client/Frontend/Share/ShareExtensionHelper.swift (hunk 3 above)
Comment (soner-yuksel) [reply Client/Frontend/Share/ShareExtensionHelper.swift:114]: This is for creating a file name for the pdf we want to save. So If it is extracting the string components without Illegal Unicode Characters (Cn) and Control (Cc, Cf) or New Line.

It is creating this name from the webview title so actually it can have anything there thats why.

I dont have an example but I guess we can try to upload a pdf to a website with title including any character if it is necessary.

And this method was already being used while trying to create PDF from the settings menu directly.

Comment (jumde) [reply Client/Frontend/Share/ShareExtensionHelper.swift:114]: As a defense in depth strategy, I think we can remove the `controlCharacters` and `illegalCharacters` from the `validFileNameSet` to avoid any path-traversal issues.

**Review by jumde — APPROVED** [review]
lgtm

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift:2756]: Tests are added for every url scheme
