### PR TITLE
Fix #6195: Remove PlaylistDetectorScript and fix item Expiration

### LINKED ISSUE #6195: Playlist Items on Playlist Folders not loading properly and shows as Expired
### Description: 
- Sometimes when visiting a Playlist Folder page, the items are loading as expired.

### Steps to Reproduce 
  1. Visit https://playlist.bravesoftware.com/japan-sample/ for example
OR:
  1. Have a playlist item that is expired, and try to play it.

**Actual result:** 
- Item does not load or shows up as all expired.

**Expected result:**
- Item should load and not show as expired.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced.

**Brave Version:** 
- 1.43

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Remove `PlaylistDetector.js`, so only `Playlist.js` is ever loaded even for streams, expired streams, and playlist folders.
- Revert change to node's UUID-Tag. It should never be recreated.

This pull request fixes #6195

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
- In ticket.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Tab.swift [hunk 1]
```diff
@@ -317,7 +317,6 @@ class Tab: NSObject {
       }
       let webView = TabWebView(frame: .zero, tab: self, configuration: configuration!, isPrivate: isPrivate)
       webView.delegate = self
-      configuration = nil
```
Comment (Brandon-T) [inline Client/Frontend/Browser/Tab.swift:320]: **Note:** I do NOT know why we ever set the configuration here to `nil`. 
I have removed it as I tested and it has no negative impacts. Also Firefox either removed it or doesn't have it.
Plus it should NEVER be nil otherwise `createWebView` can be called TWICE which we do NOT want!

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/PlaylistScript.js [hunk 2]
```diff
@@ -228,18 +224,6 @@ window.__firefox__.includeOnce("Playlist", function($) {
         })
       }, 2000);  // Resolution of 1000ms is fine for us.
     }
-
-    function onReady(fn) {
```
Comment (Brandon-T) [inline Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/PlaylistScript.js:232]: Function was not used anymore so removed it.

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/PlaylistScript.js [hunk 3]
```diff
@@ -214,10 +214,6 @@ window.__firefox__.includeOnce("Playlist", function($) {
     }
     
     function requestWhenIdleShim(fn) {
-      fn.toString = function() {
```
Comment (Brandon-T) [inline Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Sandboxed/PlaylistScript.js:217]: Script is sandboxed. No need for this.

**Review by iccub — APPROVED** [review]
Works well for me :)

**Comment by soner-yuksel** [comment]
Works well for me either, we should merge this solution and check(ask users) if this change will also solve problem with downloaded videos are showing expired.
If not we might need to change URL bookmark for that problem

**Review by soner-yuksel — APPROVED** [review]

**Review by StephenHeaps — APPROVED** [review]
