### PR TITLE
Fix #903: Puts more strict access on PhotoAlbum.

### LINKED ISSUE #903: Provide More Granular Photo Access
### Description: 

Starting in iOS 11, Apple has provided a write-only photo permissions. We should support this, even if never prompted (e.g. only a native Photos permission). This is supported in other browsers (e.g. FF)

### Steps to Reproduce 
  1. Go into Device Settings (_not_ Brave settings)
  2. Select Brave from app list
  3. Select Photos
  1. Select "Add Photos Only"

### PR DESCRIPTION
**Pull request by Brandon-T**
Change Brave photos to only use write permissions. So we use iOS's built in writer for iOS 12 (already handled automatically on iOS 13).

## Steps to Reproduce
1. Go to a website like `https://imgur.com`
2. Long press on an image (not a video)
3. Should bring up context menu.
4. Hit Save/Add to Photos

**Expected:**
1. Should add to photos.
2. Should prompt if access is denied or changed from Settings->Privacy->Photos->Brave.
3. Should show "Write Only" in Settings->Privacy->Photos->Brave.

## Summary of Changes

This pull request fixes issue #903

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2856,6 +2856,21 @@ extension BrowserViewController: ReaderModeBarViewDelegate {
 }
 
 extension BrowserViewController: ContextMenuHelperDelegate {
+    @objc
+    private func image(image: UIImage, didFinishSavingwithError error: NSError?, contextInfo: UnsafeRawPointer?) {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:2864]: Just to be sure, this code is for iOS 12 only right? Since `ContextMenuHelper` is a iOS 12 helper

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -2856,6 +2856,21 @@ extension BrowserViewController: ReaderModeBarViewDelegate {
...
+        
+        if error != nil {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: Remove it and use an early return statement `if error == nil { return }`, code will be less indented this way

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -2856,6 +2856,21 @@ extension BrowserViewController: ReaderModeBarViewDelegate {
...
+            let accessDenied = UIAlertController(title: Strings.AccessPhotoDeniedAlertTitle, message: Strings.AccessPhotoDeniedAlertMessage, preferredStyle: .alert)
+            let dismissAction = UIAlertAction(title: Strings.CancelButtonTitle, style: .default, handler: nil)
+            accessDenied.addAction(dismissAction)
+            let settingsAction = UIAlertAction(title: Strings.OpenPhoneSettingsActionTitle, style: .default ) { _ in
+                UIApplication.shared.open(URL(string: UIApplication.openSettingsURLString)!, options: [:])
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: Can you unwrap this?

**Review by iccub — CHANGES_REQUESTED** [review]
Q:
This is iOS 12 only change so test steps for QA should mention to only test on iOS12 right?

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift:2864]: Yes this should only be for iOS 12. This callback doesn't get triggered on 13.

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
