### PR TITLE
Fix #5433: Auto show pending requests when wallet panel is open

### LINKED ISSUE #5433: Automatically show dapp requests received while wallet panel is open
### Steps to Reproduce 
  1. Remove web3 site connections for [app.skiff.com](https://app.skiff.com/) in wallet settings
  2. Visit [app.skiff.com](https://app.skiff.com/)
  3. Tap 'Log in with Brave Wallet'
  4. Tap wallet notification
  5. Connect a wallet account
  6. When new site connection view dismisses after connecting an account, leave panel open until wallet badge to appears on wallet button in URL bar
  7. Observe request is not automatically shown
  8. Close wallet panel and tap wallet button in URL bar
  9. Observe request received is now shown modally

**Actual result:** 

https://user-images.githubusercontent.com/5314553/171697518-7e91f5c2-b41f-4dbc-b58e-e0ed5a019630.mov

**Expected result:**

Should not have to close wallet panel and re-open to see new request. Additionally the bell icon should appear on the wallet panel.

**Reproduces how often:** 
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Keep a reference to the open `WalletStore` when presenting the wallet panel or the main wallet.
- When a new dapp request is received, we receive a call to our tab delegate `updateURLBarWalletButton()` function which asks the open `CryptoStore` if we have an available pending request. By keeping a reference to the open `WalletStore`, we can assign this new pending request (when current `pendingRequest` is nil to prevent changing open request) to show the new request modal while the wall is still open. Otherwise existing flow of creating a temporary `CryptoStore` to check for pending requests remains.

This pull request fixes #5433

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Skiff:
  1. Remove web3 site connections for [app.skiff.com](https://app.skiff.com/) in wallet settings
  2. Visit [app.skiff.com](https://app.skiff.com/)
  3. Tap 'Log in with Brave Wallet'
  4. Tap wallet notification
  5. Connect a wallet account
  6. When new site connection view dismisses after connecting an account, leave panel open until wallet badge to appears on wallet button in URL bar
  7. Observe request is now automatically shown
  
  NOTE: To complete Skiff login/setup, we need #5424 for the encryption requests.

Add then switch network test:
1. Remove Binance from custom networks list if it is added
2. Using [eth-manual-tests](https://github.com/bbondy/eth-manual-tests), tap `wallet_addEthereumChain`
3. Accept add chain request
4. After accepting, the switch network requests should present automatically

## Screenshots:

Skiff:

https://user-images.githubusercontent.com/5314553/172172134-3cb188d3-b62b-4dc4-8c8b-8c1174035f74.mov

Add -> Switch network:

https://user-images.githubusercontent.com/5314553/172172395-f4930052-1e3a-468b-92b6-5d13c0b42710.mov

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/CryptoStore.swift [hunk 1]
```diff
@@ -281,6 +281,9 @@ public class CryptoStore: ObservableObject {
       return true
     }
     let pendingRequest = await fetchPendingWebpageRequest()
+    if self.pendingRequest == nil {
+      self.pendingRequest = pendingRequest
+    }
```
Comment (nuo-xu) [inline BraveWallet/Crypto/Stores/CryptoStore.swift:286]: should we check the equality rather than checking if its nil?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 2]
```diff
@@ -184,16 +184,7 @@ extension BrowserViewController {
...
-    guard let walletStore = WalletStore.from(privateMode: privateMode) else {
-      log.error("Failed to load wallet. One or more services were unavailable")
-      return
-    }
-    self.onPendingRequestUpdatedCancellable = walletStore.onPendingRequestUpdated
-      .sink { [weak self] _ in
-        self?.updateURLBarWalletButton()
-      }
-
+    guard let walletStore = self.walletStore ?? newWalletStore() else { return }
```
Comment (nuo-xu) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift:187]: should keep the same log.error when `walletStore` is nil

File: BraveWallet/Crypto/Stores/CryptoStore.swift (hunk 1 above)
Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/CryptoStore.swift:286]: I didn't want to change the request if the user was already viewing a specific one so I didn't use an equality check here. Thoughts?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift [hunk 3]
```diff
@@ -72,16 +72,24 @@ extension CryptoStore {
...
 extension BrowserViewController {
-  func presentWalletPanel(tab: Tab) {
+  /// Initializes a new WalletStore for displaying the wallet, setting up an observer to notify
+  /// when the pending request is updated so we can update the wallet url bar button.
+  func newWalletStore() -> WalletStore? {
     let privateMode = PrivateBrowsingManager.shared.isPrivateBrowsing
     guard let walletStore = WalletStore.from(privateMode: privateMode) else {
-      return
+      log.error("Failed to load wallet. One or more services were unavailable")
+      return nil
```
Comment (nuo-xu) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift:81]: nvm you put it here :)

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift (hunk 2 above)
Comment (StephenHeaps) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift:187]: I moved the log.error into the `newWalletStore()` function below which includes a guard on `WalletStore.from(privateMode:)` to avoid duplicate loc. I can remove from there and add to the two spots we call this `newWalletStore()` function instead if that helps?

File: BraveWallet/Crypto/Stores/CryptoStore.swift (hunk 1 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/CryptoStore.swift:286]: yeah ok. given we hard-coded the order of checking pending request, i doubt it will somehow have a different request.

**Review by nuo-xu — APPROVED** [review]

File: BraveWallet/Crypto/Stores/CryptoStore.swift (hunk 1 above)
Comment (StephenHeaps) [reply BraveWallet/Crypto/Stores/CryptoStore.swift:286]: Yeah I originally had the equality check, and I agree it's unlikely, but I don't think we can guarantee a new request doesn't come in. 
Ex. Add Chain request received while viewing an add suggested token request.
