### PR TITLE
Fix #4893 b/s/s buttons are not responding in asset details screen 

### LINKED ISSUE #4893: Searching a token and loading the details doesn't allow for the Send/Swap buttons to work
### Description: 
Searching a token and loading the details doesn't allow for the Send/Swap buttons to work 

### Steps to Reproduce 
Scenario 1:

  1. Clean profile
  2. Click on search asset 
  3. Search for BAT
  4. Select BAT from the list, loads asset details
  5. Tap on Buy/Send/Swap doesn't load the respective action sheet

Scenario 2:

  1. Clean profile
  2. Add a custom asset say TUSD
  3. Open asset detail from search result
  4. Tap on Send doesn't load
  5. Close the asset page and click on quick action button
  6. Select Send, doesn't load the send token action page
  7. Select Swap, loads close and select send loads send action page

**Actual result:** 

Scenario 1 | Scenario 2
-- | --
<video src=https://user-images.githubusercontent.com/17010094/150954408-fc334196-d3d3-4d01-90a1-a5bbbcf43667.mp4> | <video src=https://user-images.githubusercontent.com/17010094/150954428-9d105624-756b-4220-9888-d76b83bb2cda.mp4>

**Expected result:**
Should be able to select action items from asset details page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.35(22.1.24.23)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @nuo-xu

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Force setting on `buySendSwapDestination` in the next runloop in order make SwiftUI know the next presenting animation.
Asset Search Screen will be dismissed if users go to b/s/s from Asset Details Screen.

This pull request fixes #4893 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
According to #4863

Scenario 1:

Clean profile
Click on search asset
Search for BAT
Select BAT from the list, loads asset details
Tap on Buy/Send/Swap doesn't load the respective action sheet

Expected behaviour: b/s/s button should open b/s/s screen accordingly 

Scenario 2:

Clean profile
Add a custom asset say TUSD
Open asset detail from search result
Tap on Send doesn't load
Close the asset page and click on quick action button
Select Send, doesn't load the send token action page
Select Swap, loads close and select send loads send action page

(Custom Tokens will not be listed in the `Asset Search Screen` but in `Edit Visible Asset Screen` )

## Screenshots:

https://user-images.githubusercontent.com/1187676/151051927-d338afa5-0d03-4766-932c-994cc1d58452.mov

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Portfolio/PortfolioView.swift [hunk 1]
```diff
@@ -109,7 +109,8 @@ struct PortfolioView: View {
           AssetDetailView(
             assetDetailStore: cryptoStore.assetDetailStore(for: token),
             keyringStore: keyringStore,
-            networkStore: cryptoStore.networkStore
+            networkStore: cryptoStore.networkStore,
+            isPresentingAssetSearch: .constant(false)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Portfolio/PortfolioView.swift]: We don't want to use `.constant` outside of mocks

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
