### PR TITLE
Fix #6295: Disable autoplay on Playlist when adding Shared Folder

### LINKED ISSUE #6295: Playlist autoplaying when adding Shared Folder
### Description: 
- Playlist will auto-play an unrelated folder when adding a shared folder
- https://bravesoftware.slack.com/archives/C01QVPRR3RR/p1666609944907779

### Steps to Reproduce 
  1. Turn Auto Play on
  2. Add items to Saved folder
  3. Notice Items will auto-play
  4. Exit Playlist
  5. Visit Shared Playlist website
  6. Add Shared Playlist
  7. Notice: Plays items from saved folder automatically.

**Actual result:** 
- Play items from other folders while shared playlist is loading

**Expected result:**
- Should not play items from other folders when shared playlist is loading

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced

**Brave Version:** 
- 1.43.x

**Device details:** 
- Any

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Disable Auto-Play on Playlist when adding Shared Folder
- Cancel loading when the user navigates away from Shared Folder while being added.

This pull request fixes #6295

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift [hunk 1]
```diff
@@ -664,6 +667,73 @@ extension PlaylistListViewController {
...
+            if let image = UIImage(data: data, scale: UIScreen.main.scale) {
+              self.playerView.setStaticImage(image: image)
+            }
+          }
+        }
+        
+        Task { @MainActor in
+          let items = try await PlaylistSharedFolderNetwork.fetchMediaItemInfo(item: model, viewForInvisibleWebView: self.view)
+          try folder.playlistItems?.forEach({ playlistItem in
+            try Task.checkCancellation()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift]: This cancellation will do nothing because you are creating subtasks and not cancelling those. You need to use `withTaskCancellationHandler` or `async let` to ensure proper cancellation propagates down

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift [hunk 2]
```diff
@@ -664,6 +667,73 @@ extension PlaylistListViewController {
...
+              return
+            }
+            
+            if let image = UIImage(data: data, scale: UIScreen.main.scale) {
+              self.playerView.setStaticImage(image: image)
+            }
+          }
+        }
+        
+        Task { @MainActor in
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift]: `@MainActor` here is redundant, you are already inside of a `MainActor` isolated `Task`

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift [hunk 3]
```diff
@@ -664,6 +667,73 @@ extension PlaylistListViewController {
...
+      // Shared Folder doesn't exist
+      do {
+        self.playerView.setStaticImage(image: UIImage())
+        let model = try await PlaylistSharedFolderNetwork.fetchPlaylist(folderUrl: folderSharingUrl)
+        let folder = await PlaylistSharedFolderNetwork.createInMemoryStorage(for: model)
+        PlaylistManager.shared.currentFolder = folder
+        self.loadingState = .partial
+        
+        if let folderImageUrl = model.folderImage {
+          Task { @MainActor in
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift]: `@MainActor` here is redundant, you are already inside of a `MainActor` isolated `Task`

**Review by kylehickinson — CHANGES_REQUESTED** [review]
The subtasks created should be removed in favour of `async let`

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift]: Addressed. I tested it and it cancels all tasks properly.

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift]: Fixed.

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift]: Fixed.

**Review by kylehickinson — APPROVED** [review]
