### PR TITLE
Fix #7401: Previously opened tabs are closed on Brave relaunching

### LINKED ISSUE #7401: Previously opened tabs are closed on Brave relaunching
### Description: 

Previously opened tabs are closed on Brave relaunching

### Steps to Reproduce 
  1. Launch Brave
  2. Open a few tabs
  3. Close and relaunch Brave > Observe

### Actual result: 

All opened tabs are getting closed when closing and relaunching Brave

https://user-images.githubusercontent.com/128532965/236556990-9cd2c8c1-54d2-4dee-a4fc-c7858c292fc3.mov

### Expected result:

Previously opened tabs must remain on the app relaunching

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

1.51 (23.5.5.18)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 

iPhone 14 [iOS 16.4.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

Create Session Window If needed when migrate webs state is called

This pull request fixes #7401

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

- Launch Brave
- Open a few tabs
- Close and relaunch Brave > Observe

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Sources/Data/models/SessionWindow.swift [hunk 1]
```diff
@@ -63,6 +63,22 @@ extension SessionWindow {
...
+  public static func createIfNeeded(index: Int32, isPrivate: Bool, isSelected: Bool) {
+    DataController.performOnMainContext { context in
+      if SessionWindow.getActiveWindow(context: context) != nil {
+        return
+      }
+      
+      _ = SessionWindow(context: context, index: index, isPrivate: isPrivate, isSelected: isSelected)
+      
+      do {
+        try context.save()
```
Comment (iccub) [inline Sources/Data/models/SessionWindow.swift:75]: doesnt `performOnMainContext` call context.save()?

Comment (Brandon-T) [reply Sources/Data/models/SessionWindow.swift:75]: It does not afaik. It does:
```swift
DataController.perform(.existing(MainContext)) {
}
```

Which does:
```swift
case .existing(let existingContext):
     task(existingContext)
```

Only background or new context does:
```swift
case .new(let inMemory):
   try backgroundContext.save()
```

Comment (iccub) [reply Sources/Data/models/SessionWindow.swift:75]: and view context is always `existing`, no?

Comment (Brandon-T) [reply Sources/Data/models/SessionWindow.swift:75]: Yeah correct. It's always existing, so it never does a `save`. It only does `task(existingContext)`

**Review by iccub — APPROVED** [review]
