### PR TITLE
Fix #1554: Adds fallback logic for failed database migration.

### LINKED ISSUE #1554: Data loss on 1.12 upgrade for some users.
### Description: 
Users have reported loosing their bookmarks and history when migrating to 1.12.
Likely cause is the failure to migrate DB from documents directory to application support directory.

### Steps to Reproduce 
It has not been reproducible by the dev team, so FWIW
  1. Create bookmarks in older version of app
  2. update to 1.12

**Actual result:** 
No bookmarks

**Expected result:**
Bookmarks should be there

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.12

**Device details:** 
older devices such as iPhone 6s and iPad mini 2
iOS 12

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by jhreis**
## Summary of Changes

This pull request fixes issue #1554

*Items remaining*
- Added migration flags
- Add migration re-try on subsequent version upgrades

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

### New Users
1. Install 1.12.1 Brave
1. Save a bookmark 
1. Open Files app > Brave
1. See if there are any files stored here (there should not be)

### 1.12 Users, Good State -> standard upgrade testing
1. Install latest 1.12
1. Save bookmarks, open tabs
1. Install 1.12.1
1. Verify everything looks good

### 1.12 Users, Bad State
- Since we are not attempting to recover any data, we do not actually need to do anything special here, same as above.

### 1.11.4 Users, successful migration
- Since we can't repro a failed migration, this will be standard upgrade testing
- It would be best if testers had device plugged into Xcode logger in case they do run into any issues, then we can capture the error logs
1. Install 1.11.4 Brave
1. Save bookmarks, tabs
1. Upgrade to 1.12.1
1. Verify everything looks good
1. Go into Files app > Brave
1. See if there are any files stored here (there should not be)

### 1.11.4 Users, failed migration
- I will release a special beta version for this (will provide specific build number). This special build will force a migration failure, so this is how it should look / function.
1. Install 1.11.4 Brave
1. Save bookmarks, tabs
1. Upgrade to 1.12.1 <Migration Failure Version>
1. Verify everything looks good (since we fallback, there should be no apparent data lose)
1. Go into Files app > Brave
1. See if there are any files stored here (*there _should_ be ~3 "Brave" files in here this time*)

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/internal/issues/new?assignees=&labels=security%2C+security-reviews&template=security-review.md&title=iOS:%20Security+Review+for) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Client/Application/Migration.swift [hunk 1]
```diff
@@ -26,8 +26,25 @@ class Migration {
     }
     
     static func moveDatabaseToApplicationDirectory() {
-        //Moves Coredata sqlite file from Documents dir to application support dir.
-        DataController.shared.migrateToNewPathIfNeeded()
+        if Preferences.Database.DocumentToSupportDirectoryMigration.completed.value {
```
Comment (danishjafri88) [inline Client/Application/Migration.swift:29]: Can we merge the two if's and the code below. and keep a common comment for it.

**Review by danishjafri88 — APPROVED** [review]

File: Client/Application/Migration.swift [hunk 2]
```diff
@@ -26,8 +26,25 @@ class Migration {
...
+            // Migration has been done in some regard, so drop out.
+            return
+        }
+        
+        if Preferences.Database.DocumentToSupportDirectoryMigration.previousAttemptedVersion.value == AppInfo.appVersion {
+            // Migration has already been attempted for this version.
```
Comment (iccub) [inline Client/Application/Migration.swift:35]: We could convert some of these comments to debug logs

File: Data/DataPreferences.swift [hunk 3]
```diff
@@ -22,4 +22,21 @@ extension Preferences {
         /// See Sync.syncSeed for more details.
         static let seedName = Option<Bool>(key: "sync.is-sync-seed-set", default: false)
     }
+    
+    final class Database {
+        
+        public final class DocumentToSupportDirectoryMigration {
+            /// This is the filepath used for the coredata database
```
Comment (iccub) [inline Data/DataPreferences.swift]: Is this comment relevant? the preference is a bool, not a filepath string

File: Data/models/DataController.swift [hunk 4]
```diff
@@ -30,22 +31,75 @@ public class DataController: NSObject {
...
+            throw MigrationError.MigrationFailed("Document -> Support database migration failed: \(error)")
+            // Migration failed somehow, and old store is present. Flag not being updated 😭
         }
+        
+        // Regardless of cleanup logic, the actual migration was successful, so we're just going for it 🙀😎
+        Preferences.Database.DocumentToSupportDirectoryMigration.completed.value = true
+        
+        // Cleanup time 🧹
+        do {
+            try coordinator.destroyPersistentStore(at: oldDocumentStoreURL, ofType: NSSQLiteStoreType, options: nil)
```
Comment (iccub) [inline Data/models/DataController.swift:86]: Don't we need `NSPersistentStoreFileProtectionKey` option here as well?

File: Data/models/DataController.swift [hunk 5]
```diff
@@ -30,22 +31,75 @@ public class DataController: NSObject {
...
+        let coordinator = migrationContainer.persistentStoreCoordinator
+
+        guard let oldStore = coordinator.persistentStore(for: oldDocumentStoreURL) else {
+            throw MigrationError.OldStoreMissing("Old store unavailable")
+        }
+        
+        // Attempting actual database migration Document -> Support 🤞
+        do {
+            let migrationOptions = [
+                NSPersistentStoreFileProtectionKey: true
```
Comment (iccub) [inline Data/models/DataController.swift:73]: Is this the key that will most likely help with this migration bug in 1.12?
If so I would add a comment here

**Review by iccub — CHANGES_REQUESTED** [review]

File: Data/models/DataController.swift (hunk 4 above)
Comment (jhreis) [reply Data/models/DataController.swift:86]: Based on my testing, I'm not even entirely sure that's a valid key for `destroy`. We considered just excluding this entirely, as we're deleting the files right after, so could do that.

File: Client/Application/Migration.swift (hunk 2 above)
Comment (jhreis) [reply Client/Application/Migration.swift:35]: Yes, true, I'll place some logs in. We need to massively cleanup our logs in general too, lol.

File: Data/models/DataController.swift (hunk 5 above)
Comment (jhreis) [reply Data/models/DataController.swift:73]: I don't think it is actually necessary. The modification to `addPersistentStore` should be enough. I just added this in case it was useful for adding file protection for the new store. @Brandon-T is submitting a new PR to handle some of the encryption concerns too at some point.

**Review by iccub — APPROVED** [review]

File: Client/Application/Migration.swift (hunk 1 above)
Comment (jhreis) [reply Client/Application/Migration.swift:29]: Going to leave separate to leave comment clarity. Otherwise comment will be something like:
// this 
// or
// something else

Which is okay, but given how sensitive this is, I think this is probably fine. Appreciate the feedback though.

File: Data/DataPreferences.swift (hunk 3 above)
Comment (jhreis) [reply Data/DataPreferences.swift]: Good catch, fixed. I originally had this just pointing to filepath, but switched to bool. Thanks 😄

**Comment by kjozwiak** [comment]
Results for `iPhone 6s+` using `iOS 12.4.1`:

#### `New Users` - **PASSED** (x2) <-- Using `Production` TF

* installed `1.12.1 (19.9.20.20.23)` & saved a bookmark
* opened `Files.app` and ensured that there weren't any files being stored under `Brave`
* restarted `Brave` a few times and ensured that there weren't any files being created under `Brave`

#### `1.12 Users, Good State -> standard upgrade testing` - **PASSED** (x3) <-- Using `Production` TF

* installed `1.12 (19.9.12.18)` and saved several bookmarks and opened ~10 different tabs
* updated to `1.12.1 (19.9.20.20.23)` and ensured that all the bookmarks and tabs were still present after updating
* opened `Files.app` and ensured that there weren't any files being stored under `Brave`

#### `1.11.4 Users, successful migration` - **PASSED** (x3) <-- Using `Production` TF

* installed `1.11.4 (19.8.29.21)` and saved several bookmarks and opened ~10 different tabs
* updated to `1.12.1 (19.9.20.20.23)` and ensured that all the bookmarks and tabs were still present after updating
* opened `Files.app` and ensured that there weren't any files being stored under `Brave`

#### `1.11.4 Users, failed migration` - (x3) **Needs conformation from Developer** <-- Using `BETA` TF

* installed `1.11.4 (19.8.30.19)` and saved several bookmarks and opened ~10 different tabs
* updated to `1.12.1 (19.9.20.23.9)` (corrupted DB build)

As mentioned in Slack earlier, the following occurs:

* onboarding appears twice, once for `1.11.4 (19.8.30.19)` and once for `1.12.1 (19.9.20.23.9)` after upgrading
* all NTP stats are being cleared
* Setting are being cleared
* `profile.profile` folder is being left behind which includes `login` & `TabManagerScreenshot` files
