### PR TITLE
Fix #1906 - Onboarding being hidden by PBO popup (DDG).

### LINKED ISSUE #1906: Rewards onboarding is behind the PB modals
### Description: 
Rewards onboarding is behind the PB modals

### Steps to Reproduce 
  1. Clean install Appstore build
  2. Go to settings and set PB only 
  3. Upgrade to 1.13 and launch browser
  4. Onboarding screen is hidden behind PB modals

**Actual result:** 
image

**Expected result:**
Onboarding should be shown above app modals

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12.1->1.13

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

This pull request fixes issue https://github.com/brave/brave-ios/issues/1906

- Does not present the DDG popup until onboarding was skipped or completed when in PBO mode.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -3405,13 +3410,28 @@ extension BrowserViewController: OnboardingControllerDelegate {
...
         #endif
         
-        onboardingController.dismiss(animated: true)
+        // Present private browsing prompt if necessary when onboarding has been completed
+        onboardingController.dismiss(animated: true) {
+            if PrivateBrowsingManager.shared.isPrivateBrowsing && self.presentedViewController == nil {
+                DispatchQueue.main.asyncAfter(deadline: .now() + 0.4) {
+                    self.presentDuckDuckGoCallout()
+                }
+            }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Lets move this into a function and use it in both closures

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
