### PR TITLE
Fix #523: Passcode is reset if database is destroyed (e.g. new install).

### LINKED ISSUE #523: PIN/passcode is retained on clean install/stored in keychain
### Description: 
If you have a PIN set up and you delete the app, when you re-install that same PIN is used. Per discussion with @jhreis and @danishjafri88 this is because the PIN is stored in the keychain and imported automatically. We should be checking if it's a fresh install.

### Steps to Reproduce 
  1. Install 1.7 (18.11.30.3).
  2. Set a PIN. 
  3. Delete app.
  4. Re-install app.

**Actual result:** 
You are asked for PIN when you go to relaunch.

**Expected result:**
Not asked for PIN since this is a fresh install.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.7 (18.11.30.3)

**Device details:** 
iPad iOS12

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### PR DESCRIPTION
**Pull request by jhreis**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Data/models/DataController.swift [hunk 1]
```diff
@@ -96,5 +89,19 @@ public class DataController: NSObject {
...
         container.persistentStoreDescriptions = [storeDescription]
     }
+    
+    let storeURL: URL = {
+        let urls = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)
+        guard let docURL = urls.last else {
+            log.error("Could not load url at document directory")
+            fatalError()
+        }
+        let storeURL = docURL.appendingPathComponent(DataController.databaseName)
```
Comment (kylehickinson) [inline Data/models/DataController.swift]: Small nit: You could just return the `docURL.appendingPathComponent(DataController.databaseName)` since you don't use `storeURL`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Data/models/DataController.swift (hunk 1 above)
Comment (jhreis) [reply Data/models/DataController.swift]: 👍 I sometimes do this to document what the whole `docURL.append...` stuff _is_. However, as you point out, totally unnecessary here, as that is what the prop itself is named. Fixed.

**Review by kylehickinson — APPROVED** [review]
