### PR TITLE
Fix #2922: Restore vpn settings cell.

### LINKED ISSUE #2922: VPN Row missing from settings
### Steps to Reproduce 
  1. Go to settings
  2. No vpn settings row is present

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
Regression caused by #1923

## Summary of Changes

This pull request fixes #2922 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 1]
```diff
@@ -190,15 +190,15 @@ class SettingsViewController: TableViewController {
...
-        
         section.rows.append(
             Row(text: Strings.BraveToday.braveToday, selection: {
                 let todaySettings = BraveTodaySettingsViewController(dataSource: self.feedDataSource)
                 self.navigationController?.pushViewController(todaySettings, animated: true)
             }, image: #imageLiteral(resourceName: "settings-brave-today").template, accessory: .disclosureIndicator)
         )
         
+        section.rows.append(vpnSettingsRow())
+
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: You aren't setting `vpnRow` anymore, doesn't that need to happen?

**Review by kylehickinson — CHANGES_REQUESTED** [review]
No idea how I missed that… Must have been accidentally removed just before PR or something cause it definitely existed at some point 😂

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Settings/SettingsViewController.swift]: good catch, it's needed to update the label with `enabled/disabled/expired` states

**Review by kylehickinson — APPROVED** [review]
