### PR TITLE
Fix #7623: Native asset is not added as visible asset once a custom network is added

### LINKED ISSUE #7623: Adding custom network does not add native asset to visible assets
### Description: 

When adding a custom network, the network's native asset used to be automatically added as a visible asset shown in Portfolio. Since moving to core data for user assets, this does not occur.

### Steps to Reproduce 
  1. Add an EVM network (via Settings or DApp like https://chainlist.org)
  2. Open Portfolio and observe the added network's native asset is not visible
  3. Tap 'Edit User Assets'
  4. Filter to only the newly added network
  5. Observe the only asset (native asset) is unchecked.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/857145a9-cd52-4b53-88d2-7f2e2a3a641a

### Expected result:

Native asset is added as a visible asset.

### Reproduces how often: 

Easily reproduced

### Brave Version:

Regressed in v1.53 with #7443 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

The native asset is not removed from Core Data when you remove the network, so if you remove the network & re-add it, it will have the previous visibility status.

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
When user adds a custom network via dapp request or wallet settings, we will need to store it's native asset as the default visible asset. For the same reason, once user decides to delete a custom network, we will delete all the local stored assets that are in this network.

This pull request fixes #7623

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

1. Add a custom network from chainlist.org (connect wallet then add network)
2. approve the request, switch/not switch to that network 
3. go to portfolio
4. observe the new network's native asset has been automatically added as a visible asset
5. Manually add a custom network from settings 
6. go to portfolio 
7. observe the new network's native asset has been automatically added as a visible asset 
8. Remove a custom network from settings
9. go to portfolio 
10. observe all the assets that in the removed network have been removed. 
11. Navigate to the [CAROT add token request page](https://vittominacori.github.io/watch-token/page/?hash=0x7b2261646472657373223a22307831666635316461373163336435623866383531313265613361343434306265623637613632616439222c226c6f676f223a22227d&network=mainnet). 
12. Tap 'Add to MetaMask' button, and accept the request to add the suggested token in wallet
13. go to portfolio
14. observe the suggested token has been added as a visible assets

## Screenshots:

https://github.com/brave/brave-ios/assets/1187676/7abd5624-411b-4474-bfad-cac9118b3a66

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Settings/CustomNetworkDetailsView.swift [hunk 1]
```diff
@@ -260,17 +260,20 @@ enum CustomNetworkError: LocalizedError, Identifiable {
 struct CustomNetworkDetailsView: View {
   @ObservedObject var networkStore: NetworkStore
   @ObservedObject var model: CustomNetworkModel
+  var onCustomNetworkUpdated: (() -> Void)?
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Settings/CustomNetworkDetailsView.swift]: This seems to just be used to call `updateAssets()` in `CryptoStore`? You should be able to use `onNetworkListChanged()` observer method for this so you don't have to pass this closure around 🙂.

File: Sources/BraveWallet/Panels/Add Suggested Network/SuggestedNetworkView.swift [hunk 2]
```diff
@@ -342,7 +342,13 @@ struct SuggestedNetworkView: View {
...
       return
     }
-    onDismiss()
+    if let chain {
+      networkStore.customNetworkNativeAssetMigration(chain) {
+        onDismiss()
+      }
+    } else {
+      onDismiss()
+    }
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Panels/Add Suggested Network/SuggestedNetworkView.swift]: You could use the `onAddEthereumChainRequestCompleted` for this piece so it's not handled in this view, but noting that it would only cover `wallet_addEthereumChain` DApp requests and not when added from our Web3 settings.

File: Sources/BraveWallet/Panels/RequestContainerView.swift [hunk 3]
```diff
@@ -51,7 +51,10 @@ struct RequestContainerView<DismissContent: ToolbarContent>: View {
               cryptoStore: cryptoStore,
               keyringStore: keyringStore,
               networkStore: cryptoStore.networkStore,
-              onDismiss: onDismiss
+              onDismiss: {
+                cryptoStore.updateAssets()
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Panels/RequestContainerView.swift]: I don't think this is needed if we move update logic to `onNetworkListChanged()`, however it does make me realize we are also missing the logic to add as visible user asset when `AddSuggestedTokenView` adds a new asset 😮.

**Review by StephenHeaps — COMMENTED** [review]
Changes are working as intended, but a couple comments. We can handle `wallet_watchAsset` request in a separate issue/PR if needed?

File: Sources/BraveWallet/Settings/CustomNetworkDetailsView.swift (hunk 1 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Settings/CustomNetworkDetailsView.swift]: omg i was looking for an observer method for this but counln't find any cuz i was only looking at the JsonRPCServiceObserver lol
updated in [3ae6668](https://github.com/brave/brave-ios/pull/7625/commits/3ae66680a0580698e1bdd31a74d0ce0faf705cb9)

File: Sources/BraveWallet/Panels/Add Suggested Network/SuggestedNetworkView.swift (hunk 2 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Panels/Add Suggested Network/SuggestedNetworkView.swift]: updated in [3ae6668](https://github.com/brave/brave-ios/pull/7625/commits/3ae66680a0580698e1bdd31a74d0ce0faf705cb9)

File: Sources/BraveWallet/Panels/RequestContainerView.swift (hunk 3 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Panels/RequestContainerView.swift]: updated in [3ae6668](https://github.com/brave/brave-ios/pull/7625/commits/3ae66680a0580698e1bdd31a74d0ce0faf705cb9)

**Review by StephenHeaps — APPROVED** [review]
