### PR TITLE
Fix #1876: Revert `domainUrl`, add new method to strip www from url.

### LINKED ISSUE #1876: Per site settings are not retained during upgrade
### Description: 
Per-site settings are not retained during an upgrade

### Steps to Reproduce 
  1. Clean install 1.12.1 and do not change any default shields settings
  2. Visit https://brianbondy.com/ and enable all shields settings 
  3. Upgrade to 1.13 and relaunch
  4. `Block Script` and `Fingerprinting Protection` isn't enabled after upgrade

**Actual result:** 
Per-site settings are not retained during upgrade

**Expected result:**
Upgrade should retain per-site shields settings 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.1.19)

**Device details:** 
iPhone & iPad on both iOS 12 and iOS 13

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

### PR DESCRIPTION
**Pull request by iccub**
#ref 1533

## Summary of Changes
This commit:
https://github.com/brave/brave-ios/commit/d482ffbe4c638734a49b5b25f67711cea26bf718

had a bug where `domainURL` wasn't stripping url parameters.
Now there are two methods, one to strip `www` only and leave params, 
and old `domainURL` which keeps the scheme without params

This pull request fixes issue #1876 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Shared/Extensions/URLExtensions.swift [hunk 1]
```diff
@@ -238,19 +238,28 @@ extension URL {
     }
 
     /**
-     * Returns just the domain, but with the same scheme, and a trailing '/'.
```
Comment (iccub) [inline Shared/Extensions/URLExtensions.swift:241]: This comment is actually outdated, see https://github.com/brave/brave-ios/commit/0158c51c503a151facbab2b8b0d01950b6096050#diff-005e296c633487f7dcebd610aa8bdd11

**Review by Brandon-T — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
