### PR TITLE
Fix #5560: Brave-Core overrides not working in debug builds

### LINKED ISSUE #5560: [BraveCore] - Overrrides no longer work in debug builds
### Description: 
- Brave-Core overrides do not work in debug builds anymore

### Steps to Reproduce 
  1. Override `sync-url`
  2. Notice that syncing still uses the default Brave-Core URL

**Actual result:** 
- Overrides not working

**Expected result:**
- Overrides should work

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily Reproduced

**Brave Version:** 
- 1.39

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Sets the build channel so overrides can work when `Brave-Core` is initialized.

This pull request fixes #5560

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: App/iOS/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -33,7 +33,7 @@ extension AppDelegate {
 
 class AppDelegate: UIResponder, UIApplicationDelegate {
   var window: UIWindow?
-  var braveCore: BraveCoreMain = {
+  lazy var braveCore: BraveCoreMain = {
```
Comment (soner-yuksel) [inline App/iOS/Delegates/AppDelegate.swift:36]: why do we decide to lazily initialize braveCore ?

Comment (kylehickinson) [reply App/iOS/Delegates/AppDelegate.swift:36]: @soner-yuksel It will still be initialized before `init` is called below without lazy.  Other option is to move the initialization to `init` method after app constants set.

**Review by kylehickinson — APPROVED** [review]
