### PR TITLE
Fix incorrect constraints when presenting a PopoverController

### LINKED ISSUE #358: Bottom toolbar does not hide when scrolling on an iPhone X
### Description: 

Usually when you scroll down a page, the url bar +toolbar hide. Only the url bar hides on an iPhone X

### Steps to Reproduce 
  1. Open any page that you can scroll (yahoo.com) on an iPhone X
  2. Scroll

**Actual result:** Bottom toolbar doesn't hide
**Expected result:** Bottom toolbar hides
**Reproduces how often:** Always

### PR DESCRIPTION
**Pull request by kylehickinson**
Also cleans up some mixed usage between SnapKit and vanilla NSLayoutConstraint API.

Constraining to the origin view was technically invalid and was adding constraints to the root window of the application (since they belong to different view hierarchies). For some odd reason this worked fine instead of throwing an exception however obviously had strange side-effects.

Fixes #358 (sorry @klymenkoo!)

## Pull Request Checklist

- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

_None included_

## Notes for testing this patch

_None included_

### CODE REVIEW

File: Client/Frontend/Popover/PopoverController.swift [hunk 1]
```diff
@@ -345,36 +345,39 @@ extension PopoverController {
...
         }
         
         context.containerView.addSubview(view)
         
-        switch containerView.arrowDirection {
-        case .down:
-            containerView.bottomAnchor.constraint(equalTo: popoverContext.originView.topAnchor, constant: -arrowDistance).isActive = true
-        case .up:
-            containerView.topAnchor.constraint(equalTo: popoverContext.originView.bottomAnchor, constant: arrowDistance).isActive = true
+        let originViewFrame = context.containerView.convert(popoverContext.originView.frame, from: popoverContext.originView.superview)
```
Comment (danishjafri88) [inline Client/Frontend/Popover/PopoverController.swift]: Once the view is added as subview at line 353, we can use the view itself for constraint purpose. Current implementation puts constraints between views which are not direct superview/subview. This causes the view lifecycle update calls on the topmost view as the constraints attached to the current view gets updated. Simple replacement of context.containerView with just view, will do it.

**Review by danishjafri88 — DISMISSED** [review]
Please change as requested in the comment https://github.com/brave/brave-ios/pull/369#discussion_r228998192

**Review by danishjafri88 — APPROVED** [review]
