### PR TITLE
Fix #6656: Remove wallet injection from Private Browsing

### LINKED ISSUE #6656: Brave iOS browser throws TypeError on all pages visited in incognito mode
### Description: 
Brave iOS browser throws `TypeError: undefined is not an object (evaluating 'window.ethereum.selectedAddress = undefined')` on all pages visited in incognito mode

I've created a [test page](https://rdwallis.github.io/rdwallis/BraveBug.html) which appends all thrown errors to the document but I think this occurs on every website visited in incognito mode.

### Steps to Reproduce 
  1. Open Brave Browser in Incognito Mode
  2. Visit https://rdwallis.github.io/rdwallis/BraveBug.html
  3. You will see multiple Js Errors appended to the document

**Actual result:** 
IMG_8CFC6957AC15-1

**Expected result:**
Blank Page with no errors like on Safari

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time any page is visited in incognito mode.

**Brave Version:** 
Version 1.45.2 (22.11.29.0)
BraveCore 1.45.134 (107.0.5304.141)
Device iPhone13,1 (iOS 16.2)

**Device details:** 
iPhone 12 mini (iOS 16.2)

**Website problems only:**
- did you check with Brave Shields down?
Yes, problem occurs with Brave Shields up or down
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes, problem does not occur

### Additional Information
I think the error is caused by this line of code: 
https://github.com/brave/brave-ios/blob/6bce727178fbf74fa3ae2c1d53abc806727bed72/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWallet.swift#L452

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Remove wallet script injections in Private Browsing Mode

This pull request fixes #6656

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes
  
## Test Plan:
  https://brandon-t.github.io/wallet/wallet.html should show no errors.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by StephenHeaps — COMMENTED** [review]
Thanks for taking a look at this one 👍

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift [hunk 1]
```diff
@@ -407,7 +407,8 @@ extension Tab: BraveWalletEventsListener {
   }
   
   func updateEthereumProperties() {
-    guard let keyringService = BraveWallet.KeyringServiceFactory.get(privateMode: false),
+    guard !isPrivate,
```
Comment (StephenHeaps) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift:416]: I believe we need this same Private Browsing check in a few more spots in `BrowserViewController+Wallet.swift`: `emitEthereumEvent`, `accountChangedEvent`, `emitSolanaEvent`, `updateSolanaProperties`.

Comment (StephenHeaps) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift:416]: Tested and discussed, only `chainChangedEvent` or `emitEthereumEvent` need the fix applied. This can occur if you open Send in main wallet and change the selected chain.

`accountChangedEvent` is only called when the Solana Provider for the tab is non-nil, but it will be nil in private tab. 
`emitSolanaEvent` is only called from `SolanaProviderScriptHandler` which is only injected in non-private tabs.
`updateSolanaProperties` checks for non-nil Solana Provider in the tab, but it will be nil in private tab.

**Review by StephenHeaps — APPROVED** [review]
