### PR TITLE
Fix #5134: Clear Private Data should reset the Shield Preferences on Domains 

### LINKED ISSUE #5134: Clear Private Data should reset the Shield Preferences on Domains
### Description: 

The `clear data` shortcut does not have ability to clear `Domain` persistent data like shield settings or other `Domain` persistent data

### Steps to Reproduce 
  1. Open a website
  2. Disable Brave Shields for the website
  3. Close tab
  4. Tap 3-dot menu
  5. Tap 'Settings'
  6. Tap 'Brave Shields & Privacy'
  7. Tap 'Clear Data Now'
  8. Re-open website from step 1

**Actual result:** 

- Brave shield and any other changes done to Shield preferences remains not changed (not reseted)

**Expected result:**

- Brave shield and other changes to Shield preferences is reset to default value of enabled

**Reproduces how often:** 
Easily reproduced

**Brave Version:** 
N/A

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

Desktop is using a separate toggle for site & shield data, in future we might need to consider making changes to toggles to clarify the changes.

reset

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This pull request fixes #5134

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Open a website
- Disable Brave Shields for the website
- Close tab
- Tap 3-dot menu
- Tap 'Settings'
- Tap 'Brave Shields & Privacy'
- Tap 'Clear Data Now'
- Re-open website from step 1

## Screenshots:

https://user-images.githubusercontent.com/6643505/159777821-5aef5364-4f4b-4453-b80d-62709c7e72c7.mp4

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Data/models/Domain.swift [hunk 1]
```diff
@@ -200,31 +200,34 @@ extension Domain {
...
+        let results = try context.fetch(fetchRequest)
+        results.forEach {
+          if let bms = $0.bookmarks, bms.count > 0 {
+            // Clear visit count and clear the shield settings
+            $0.visits = 0
+            $0.shield_allOff = nil
+            $0.shield_adblockAndTp = nil
+            $0.shield_noScript = nil
+            $0.shield_fpProtection = nil
+            $0.shield_safeBrowsing = nil
```
Comment (StephenHeaps) [inline Data/models/Domain.swift:217]: I don't think needed in this PR, but I wonder if we should reset `wallet_permittedAccounts` too? If we can do it in wallet panel branch cc @kylehickinson

**Review by StephenHeaps — APPROVED** [review]
Lone comment can be addressed in wallet dapps branch so no not blocking 🙂

**Review by iccub — APPROVED** [review]
