### PR TITLE
Fix #7674: Update bookmarks cell to show the count of child bookmarks in a folder

### LINKED ISSUE #7674: Would be nice to see the number of saved bookmarks under the folder name
### Description: 

Would be nice to see the number of saved bookmarks under the folder name

### Steps to Reproduce 
  1. Launch Brave 
  2. Open any website > Bookmark it
  3. Open `Bookmarks` > Observe that the user can't see how many bookmarks are saved in the folder

### Actual result: 

The user can't see how many bookmarks are saved in the folder. 

|iOS|Android|
|:-:|:-:|
|  |  |

### Expected result:

It would be nice to see the number of saved bookmarks under the folder name. Similar thing implemented on Android already.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.52 (23.6.30.11)
BraveCore: 1.52.129 (114.0.5735.198)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 16.5.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Add the bookmark child count to the Bookmarks Folder

This pull request fixes #7674

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Screenshots:
image
image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift [hunk 1]
```diff
@@ -443,16 +443,26 @@ class BookmarksViewController: SiteTableViewController, ToolbarUrlActionsProtoco
...
       configCell(image: UIImage(braveSystemNamed: "leo.folder"))
       cell.textLabel?.font = UIFont.boldSystemFont(ofSize: fontSize)
       cell.accessoryType = .disclosureIndicator
       cell.setRightBadge(nil)
+      
+      // 0 bookmarks
+      // 1 bookmark
+      // 2 bookmarks
+      // ...
+      cell.detailTextLabel?.text = String(format: item.bookmarkNode.childCount == 1 ? Strings.bookmarkSingleCount :
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: Bookmark node childCount includes subfolders right ? So this will give us a number showing the number of bookmarks + folder for that particular folder.

I think this might be confusing maybe we should specifically show user, their bookmark count and folder count separately.

Like `5 Bookmarks - 3 Folders`

Hmm what do you think ?

Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: Oops. This is supposed to be `children.count` like in the line below it. Will fix it.

**Review by iccub — APPROVED** [review]

**Review by soner-yuksel — APPROVED** [review]
