### PR TITLE
Fix #8350: Fix Playlist not working on Youtube at all

### LINKED ISSUE #8350: Adding high quality youtube videos to playlist does not work

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Update the Playlist Swizzling scripts to run on iPhone and not just iPad
- Update the Playlist Swizzling scripts to handle ManagedMediaSource
- Update WebKit error handling code to allow WebKit to automatically refresh the frame whenever it fails and continue on like normal (gets rid of the unnecessary/false alert that something went wrong)

This pull request fixes #8350

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
- Test adding videos to Playlist from Youtube
- Test adding 4K videos to Playlist from Youtube

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift [hunk 1]
```diff
@@ -36,7 +36,7 @@ class LivePlaylistWebLoader: UIView, PlaylistWebLoader {
     }, type: .private
   ).then {
     $0.createWebview()
-    $0.setScript(script: .playlistMediaSource, enabled: Preferences.Playlist.webMediaSourceCompatibility.value)
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift:39]: Should we remove the preference entirely ?

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistSwizzlerScript.js [hunk 2]
```diff
@@ -4,12 +4,16 @@
...
-  //HTMLMediaElement.prototype.webkitSourceAddId = null;
-  //window.SourceBuffer = null;
-  
+
+if (window.MediaSource || window.WebKitMediaSource || window.ManagedMediaSource || (window.HTMLMediaElement && HTMLMediaElement.prototype.webkitSourceAddId)) {
   delete window.MediaSource;
   delete window.WebKitMediaSource;
+  delete window.ManagedMediaSource;
+  
+//  window.MediaSource = undefined;
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistSwizzlerScript.js:15]: Also could be a good idea to write description the reason of the change

**Review by soner-yuksel — APPROVED** [review]

File: Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift (hunk 1 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift:39]: We should keep it just in case. Users can select it from settings which can allow them to downgrade quality if they wish, and use a different API. We can remove it in the future if it becomes useless.

I used it to test this PR just to make sure it worked :)

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistSwizzlerScript.js (hunk 2 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/PlaylistSwizzlerScript.js:15]: Added a comment :)
