### PR TITLE
Fix #7964: Onboarding Completed Screen cannot be dimissed

### LINKED ISSUE #7962: Onboarding gets stuck when fingerprint unlock is skipped
### Description: 
Onboarding gets stuck when fingerprint unlock is skipped

### Steps to Reproduce 
  1. Install 1.57 and create a new wallet onboarding
  2. On use biometric unlock screen click on the edge of the button
  3. Selects Skip instead of enabling biometric unlock
  4. Gets stuck on the last screen of onboarding
  5. Doesn't let you close the screen. Have to force quit and restart to use the browser again

### Actual result: 
Onboarding gets stuck when fingerprint unlock is skipped

### Expected result:
Should select the correct option and complete onboarding

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Hard. Happened a couple of times

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
Happened on iPad and iPhone with biometric unlock

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### LINKED ISSUE #7964: Action message isn't removed when navigating between screen or when clearing input text
### Description: 
Action message isn't removed when navigating between screen or when clearing input text

### Steps to Reproduce 
Scenario 1:
  1. Start onboarding for a new wallet
  2. Continue on back wallet phrase screen
  3. Tap on copy to clipboard
  4. Go to next screen to confirm random words
  5. Go back to previous screen
  6. Copied text is shown instead of copy to clipboard button

Scenario 2:
  1. Start onboarding for a new wallet
  2. Continue on back wallet phrase screen
  3. Enter a wrong word when asked to type in 
  4. Shows `Recovery phrase doesn't match` message
  5. Clear input text but continues to show the message
  6. Enter the correct word but add a space at the start or at the end and continue
  7. Shows `Recovery phrase doesn't match` message 

### Actual result: 
Action message isn't removed when navigating between screen or when clearing input text

### Expected result:
Should clear the on screen message when navigated away from the screen or when input field is cleared

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
There is a bug in SwiftUI (possibly fixed in iOS 17) that button cannot be recognized in the frame area. This will cause screen cannot be dismissed even the button is tapped in onboarding completed screen.
This PR is adding a tap gesture on the screen, so that user can tap anywhere to pass this final step of onboarding. 
This PR also make the biometric view scrollable so that users can click the skip button when device screen is small. 

This pull request fixes #7962

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

- It's really hard to reproduce as the issue mentioned. But this is an indirect fix for this issue. We are adding a tap gesture on the screen, so that user can tap anywhere on the screen to dismiss this screen. 
- Test biometric screen can be dismissed by tapping on skip in a small screen device. 

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Sources/BraveWallet/Crypto/Onboarding/OnBoardingCompletedView.swift [hunk 1]
```diff
@@ -22,38 +22,43 @@ struct OnboardingCompletedView: View {
...
-            .font(.subheadline)
-            .foregroundColor(.secondary)
-            .fixedSize(horizontal: false, vertical: true)
-            .padding(.top, 4)
-          Button {
-            keyringStore.markOnboardingCompleted()
-          } label: {
-            Text(Strings.Wallet.onboardingCompletedButtonTitle)
-              .frame(maxWidth: .infinity)
+      GeometryReader { geometry in
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Onboarding/OnBoardingCompletedView.swift:25]: PR description only mentions tap gesture, what are the other changes for? I don't think the `GeometryReader` is needed?

Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Onboarding/OnBoardingCompletedView.swift:25]: This removes the hardcoded top padding on the VStack `.padding(.top, 124)` to force it fit the entire screen in order to make its subviews stay centred vertically. I initially thought the scrollView was doing some weird stuff that could cause this problem. but its not. left it thinking it's still a good improvement by removing hardcoded top padding.

**Review by StephenHeaps — APPROVED** [review]
