### PR TITLE
Fix #3056: Update search engine display names outside of OpenSearch xml.

### LINKED ISSUE #3056: Search Engine resets after upgrade
### Description: 
Search Engine resets after upgrade

### Steps to Reproduce 
  1. Install 1.21 
  2. Set Startpage as default via onboarding
  3. Ensure both normal and private tabs are set with Startpage as default
  4. Upgrade to 1.22(20.11.19.10)
  5. Search engine is reset to Google

**Actual result:** 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1605872680107800

**Expected result:**
Should retain default search engine from upgrade

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.22(20.11.19.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by iccub**
Ref #3050
Ref #3002

## Summary of Changes

Long story short, changing search engine name in the xml breaks a lot. We should refactor it better at some point

This pull request fixes #3056 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Search/OpenSearch.swift [hunk 1]
```diff
@@ -21,6 +21,23 @@ class OpenSearchEngine: NSObject, NSSecureCoding {
...
     
     let shortName: String
+    
+    // Backwards compatibility workaround, see #3056.
+    // We use `shortName` to store persist what engines are set as default, order etc.
+    // This means there's no easy way to change display text for the search engine without
+    // saved engines breaking.
+    // This updates the engines name in the UI, without changing it at the xml level.
+    // In the future we might refactor it.
+    var displayName: String {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Search/OpenSearch.swift:31]: Do you think it might be better to have an enum for engine types and create a struct for holding the names(shortname/ displayName) and return their rawValue according to Engine type?

But I think this is quick workaround, we can refactor like you said.

**Review by soner-yuksel — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/Search/OpenSearch.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Browser/Search/OpenSearch.swift:31]: Not for now, but I agree, we could have a struct or an enum of search engines we use.
And we should distinguish between display name and search engine identifier, which is not the case now
