### PR TITLE
Fix #3978 - Fix #3979: Private Mode Only Fixes for Shortcuts

### LINKED ISSUE #3978: Clear history voice command clears data but switches to normal tab
### Description: 
Clear history voice command clears data but switches to normal tab 

### Steps to Reproduce 
  1. Clean install 1.29
  2. Visit a few pages on normal tab to add to history
  3. Switch to Private Browsing only
  4. Use Siri voice command to clear history
  5. Closes private tab, clears history and switches back to normal tabs even though private browsing only is enabled

**Actual result:** 
Clear history voice command clears data but switches to normal tab 

**Expected result:**
Should close all private tabs and just create a new private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.29(21.07.28.22)

**Device details:** 
iPhone 7+ (iOS 14.5.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### LINKED ISSUE #3979: Brave news voice command switches to normal tab even when private browsing only is set
### Description: 
Brave news voice command switches to normal tab even when private browsing only is set

### Steps to Reproduce 
  1. Enable Brave News
  2. Set to use Private browsing only
  3. Use Siri voice command to launch Brave News
  4. Switches to normal tab and loads Brave News feed

**Actual result:** 
Brave news voice command switches to normal tab even when private browsing only is set

**Expected result:**
Should do nothing as browser is set to Private browsing only and Brave News isn't available on private tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.29(21.07.28.22)

**Device details:** 
iPhone7+ (iOS 14.5.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by soner-yuksel**
PB Only mode is enabled All private tabs closed and a new private tab is created
Do nothing as browser when browser to PB only and Brave News isn't available on private tabs
Open Tab in current mode when VPN shortcuts is called

## Summary of Changes

This pull request fixes #3978
This pull request fixes #3979

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Follow the Test Plan in the ticket

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1588,11 +1588,18 @@ class BrowserViewController: UIViewController {
...
+        // All private tabs closed and a new private tab is created
+        if Preferences.Privacy.privateBrowsingOnly.value {
+            tabManager.removeAll()
+            openBlankNewTab(attemptLocationFieldFocus: true, isPrivate: true)
+        } else {
+            History.deleteAll { [weak self] in
+                guard let self = self else { return }
+                
+                self.tabManager.clearTabHistory() {
+                    self.openBlankNewTab(attemptLocationFieldFocus: true, isPrivate: false)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift:1601]: If you are currently in private browsing mode here shouldn't we open a new private tab?

Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift:1601]: I am not sure. But I believe this shortcut should open a new tab in normal mode after clearing the history. This is technically clearing the tabs in private mode with this way.

**Review by Brandon-T — APPROVED** [review]

**Review by iccub — APPROVED** [review]
