### PR TITLE
Fix #8694: Fix potential tab loss when window not found

### LINKED ISSUE #8694: WindowID passed to NSPredicate as a String can cause TabLoss
### Description: 
- In the code, WindowID is passed to NSPredicate as a String instead of UUID. This causes the window to not be found.

### Brave Version: 
- 1.61.x

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Pass WindowID as a UUID directly to NSPredicate

This pull request fixes #8694

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Data/models/SessionWindow.swift [hunk 1]
```diff
@@ -65,7 +65,7 @@ extension SessionWindow {
   }
   
   public static func from(windowId: UUID, in context: NSManagedObjectContext) -> SessionWindow? {
-    let predicate = NSPredicate(format: "\(#keyPath(SessionWindow.windowId)) == %@", windowId.uuidString)
+    let predicate = NSPredicate(format: "\(#keyPath(SessionWindow.windowId)) == %@", argumentArray: [windowId])
```
Comment (kylehickinson) [inline Sources/Data/models/SessionWindow.swift]: Just use `windowId as NSUUID`

**Review by iccub — APPROVED** [review]
