### PR TITLE
Fix #6965: Duplicate add network requests can be shown

### LINKED ISSUE #6965: Unable to add custom network via panel prompt
### Description: 
Unable to add custom network via panel prompt

### Steps to Reproduce 
  1. Visit `https://chainlist.org`
  2. Select a network and try to add
  3. Approve prompt shows up twice but never adds the network to the list. For some network it keeps prompting and never adds it

### Actual result: 

https://user-images.githubusercontent.com/17010094/219615961-f43ed1c0-918f-4be0-8328-2d7376bcaae8.MP4

### Expected result:
Should be able to add a custom network

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
All devices

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Adding a new ethereum chain requires a network call, however we were not waiting for the response of attempting to add the new chain before dismissing the Add Network request modal. This could create a race condition where we still have the add network request pending when we are dismissing the Add Network request modal, so it would be shown again.
- Added a loading state and error alert to `SuggestedNetworkView`. Error will dismiss the modal after as the add chain request is removed in core: https://github.com/brave/brave-core/blob/b31c48fff4b9aecdef95a9bba344f9329b3ab1e7/components/brave_wallet/browser/json_rpc_service.cc#L521
- Added an optional completion closure to `handleWebpageRequestResponse` so `SuggestedNetworkView` knows when to start/stop loading, and can now show an error alert when failing to add the network

This pull request fixes #6965

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Visit Chainlist.org
2. Connect your wallet and try adding a few chains.
3. Verify each only shows 'add network' modal once before showing 'switch network' modal.
4. Find [Astar on Chainlist.org](https://chainlist.org/chain/592) and try to add it.
5. (assuming it still fails) Verify loading state is shown, and wait for timeout on the request.
6. Verify closing the alert will dismiss the Add Network modal as the request is removed when error is received.

## Screenshots:

Add Network Fixed:

https://user-images.githubusercontent.com/5314553/222518389-fcbbb88d-eb9e-4858-adb1-4febe0a41de6.mov

Add Network error alert (new):

https://user-images.githubusercontent.com/5314553/222572235-60a70c66-4d3c-4ef1-ab02-8dc6bbe01311.mov

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/CryptoStore.swift [hunk 1]
```diff
@@ -386,12 +386,34 @@ public class CryptoStore: ObservableObject {
...
 
-  func handleWebpageRequestResponse(_ response: WebpageRequestResponse) {
+  struct AddNetworkCompletion {
+    let chainId: String
+    let completion: (_ error: String?) -> Void
+  }
+  // Helper to store the completion block of an Add Network request.
+  // The completion closure is handled in `onAddEthereumChainRequestCompleted`
+  // when we determine if the chain was added successfully or not.
+  var addNetworkWebpageRequestCompletion: AddNetworkCompletion?
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/CryptoStore.swift]: shouldn't this be a list? what if while adding network 1, im adding network 2 that also takes 4 min ?

Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Stores/CryptoStore.swift]: These add chain requests are stored in a [flat_map](https://chromium.googlesource.com/chromium/src/base/+/master/containers/flat_map.h#32) in [brave-core](https://github.com/brave/brave-core/blob/master/components/brave_wallet/browser/json_rpc_service.h#L607-L609) which [behaves a bit more like an array for us when we fetch these requests](https://github.com/brave/brave-core/blob/master/components/brave_wallet/browser/json_rpc_service.h#L607-L609) so while I don't think this is currently an issue, I think it's probably best to update here to treat these requests as if they were stored a dictionary; I'll try and update this to be safe.

Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Stores/CryptoStore.swift]: Updated in [1cabf89](https://github.com/brave/brave-ios/pull/7047/commits/1cabf891bc8232e88b5d92112926a44380d9e2a6)

**Review by nuo-xu — APPROVED** [review]
