### PR TITLE
Fix #8232: Display 0 for send amount for all percentage if selected token balanc…

### LINKED ISSUE #8232: Do not show decimal values if token balance is 0
### Description: 
Do not show decimal values if token balance is 0

### Steps to Reproduce 
  1. Create a new wallet so balance is 0
  2. Select Send screen and select a token
  3. Select the pre-set values
  4. Shows decimals for pre-set values 

### Actual result: 
Shows decimals for pre-set values when token balance is 0

### Expected result:
Do not show decimal values if token balance is 0

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by nuo-xu**
Display 0 for send amount for all percentage if selected token balance is zero

## Summary of Changes

This pull request fixes #8232

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

please refer to the issue

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 1]
```diff
@@ -232,7 +232,7 @@ public class SendTokenStore: ObservableObject, WalletObserverStore {
       decimalPoint = Int(selectedSendToken?.decimals ?? 18)
       rounded = false
     }
-    sendAmount = ((selectedSendTokenBalance ?? 0) * amount.rawValue).decimalExpansion(precisionAfterDecimalPoint: decimalPoint, rounded: rounded)
+    sendAmount = selectedSendTokenBalance == 0 ? "0" : ((selectedSendTokenBalance ?? 0) * amount.rawValue).decimalExpansion(precisionAfterDecimalPoint: decimalPoint, rounded: rounded)
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Stores/SendTokenStore.swift]: What about using `trimmingTrailingZeros` extension instead?
And I think we should apply this in Swap too 🙂

Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Stores/SendTokenStore.swift]: updated in [a2f6916](https://github.com/brave/brave-ios/pull/8234/commits/a2f6916b1266a15ac1fa8c8b42969de2def63dae)

**Review by StephenHeaps — APPROVED** [review]
