### PR TITLE
Fix #2337: TabContentScript memory leak.

### LINKED ISSUE #2337: WKScriptMessage crash
### Description: 

Hard to say what is the problem, I believe this is some kind of memory leak.

Zrzut ekranu 2020-02-17 o 16 28 09

### Steps to Reproduce 
  1. Hard to repro :( Never managed to repro it

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes issue #2337 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

For devs only:
you can add `deinit` in `TabContentScriptManager` and `U2F extensions` to verify it gets deallocated properly

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/Tab.swift [hunk 1]
```diff
@@ -263,6 +263,8 @@ class Tab: NSObject {
     }
     
     func deleteWebView() {
+        contentScriptManager.uninstall(from: self)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Tab.swift:266]: Do we need to do this anywhere else? Should this be placed inside the `if webView = webView` condition?

Comment (iccub) [reply Client/Frontend/Browser/Tab.swift:266]: From my tests this is the only place where contents scripts are leaking, 

I can move it under webview unwrapping, but we uninstall it with optional chaining anyway

File: Client/WebAuthN/U2FExtensions.swift [hunk 2]
```diff
@@ -231,8 +231,8 @@ class U2FExtensions: NSObject {
         
         super.init()
         
-        let handleCancelButton: () -> PopupViewDismissType = {
-            self.sendJSError()
+        let handleCancelButton: () -> PopupViewDismissType = { [weak self] in
+            self?.sendJSError()
```
Comment (iccub) [inline Client/WebAuthN/U2FExtensions.swift:235]: this was actually a harder leak, each tab close increased app memory by around 1 megabyte until the app was killed

**Review by kylehickinson — APPROVED** [review]
