### PR TITLE
Fix #7877: Fix NightMode applying to elements with a background-image

### LINKED ISSUE #7877: Occasional inverted colors when searching Brave Search in Night Mode
I have night mode enabled on iOS

Sometimes when I search on Brave Search, some of the images in the search results end up inverted, like this
image

usually if i reload the page though, the images end up presented as normal 
image

Additional details:
1. problem doesn't happen consistently, but happens semi-often for me, a few times a week or so.
1. I haven't noticed any pattern between the search query and whether this problem comes up
1. from looking at the above images, you can see that there are other small differences in the styling of the inverted and not-inverted versions of the pages (for example, some font sizing/width), which makes me think that the problem is markup or a stylesheet being accidentally included / omitted, and not something deeper)

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Use the computed style instead of a query selector, to determine which elements have a background-image and to invert them.

This pull request fixes #7877

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Screenshots:

Before: 
image

After:
image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -180,8 +180,11 @@ extension BrowserViewController: WKNavigationDelegate {
     
     if ["sms", "tel", "facetime", "facetime-audio"].contains(requestURL.scheme) {
       // Do not allow opening external URLs from child tabs
-      handleExternalURL(requestURL, tab: tab, navigationAction: navigationAction)
-      return (.cancel, preferences)
+      return await withCheckedContinuation { continuation in
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: This part is pushed accidentally.

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 2]
```diff
@@ -190,21 +193,30 @@ extension BrowserViewController: WKNavigationDelegate {
     // So the Apple maps URLs will open properly
     if let mapsURL = isAppleMapsURL(requestURL), mapsURL.enabled {
       // Do not allow opening external URLs from child tabs
-      handleExternalURL(mapsURL.url, tab: tab, navigationAction: navigationAction)
-      return (.cancel, preferences)
+      return await withCheckedContinuation { continuation in
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Same as above ^

**Review by soner-yuksel — APPROVED** [review]
