### PR TITLE
Fix #6917 - Fix Favicons showing transparent & caching

### LINKED ISSUE #6917: Favicon issue after removing some favorites on NTP
### Description: 
Favicon issue after removing some favorites on NTP

### Steps to Reproduce 
  1. Install 1.48
  2. Delete 2 favorites on NTP
  3. Brave Support Favicon will appear to be transparent

### Actual result: 

https://user-images.githubusercontent.com/17885425/217929926-d7f7d02c-d15a-4860-b73d-d31de9ba3c06.MP4

### Expected result:
Favicon should be displayed correctly

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version: 
`1.48 (23.2.7.21)`

- Can you reproduce this issue with the most recent build from TestFlight?  Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? TBD
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone 12, iOS 16.2

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix Favicons showing transparent
- Fix defaulting to monogram and to globe icon on failure 
- Fix padding of monogram icons
- Fix padding on transparent favicons
- Remove caching of bundled icons otherwise NTP never shows the fetched icons. 
- Fix icon transparency for blurred backgrounds

This pull request fixes #6917

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. On NTP, tap on `Show More` to show the Brave Support Icon
2. It should show the support icon!
----
1. On NTP, tap on `Show More`.
2. Tap on Reddit.
3. Show the Tab Switcher
4. Favicon should show!
5. Close the tab.
6. On NTP, tap on `Show More`.
7. Reddit icon should be updated!
8. Repeat steps for Youtube and Amazon.
----
1. Visit https://app.uniswap.org/
2. Open TabSwitcher
3. Favicon should show!
----
1. Do NOT visit any sites (Fresh install).
2. Join a sync chain with Desktop.
3. On Desktop, visit youtube and amazon.
4. Bookmark both sites on Desktop.
5. Icons should sync to Mobile.
6. Icons might look blurry.
7. Visit the bookmarks on Mobile.
8. Icons should be HD!

## Screenshots:
image

image

image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by StephenHeaps — APPROVED** [review]

File: Sources/Favicon/UIImage+FaviconRenderer.swift [hunk 1]
```diff
@@ -100,12 +100,22 @@ extension UIImage {
...
-  static func renderImage(_ image: UIImage, backgroundColor: UIColor?) async -> Favicon {
+  static func renderFavicon(_ image: UIImage, backgroundColor: UIColor?, shouldScale: Bool) async -> Favicon {
     if let cgImage = image.cgImage {
-      let padding = image.hasTransparentEdges ? 4.0 : 0.0
+      let hasTransparentEdges = image.hasTransparentEdges
+      
+      var padding = hasTransparentEdges ? 4.0 : 0.0
+      var idealSize = image.size
+      if shouldScale && max(idealSize.width, idealSize.height) < 64.0 {
+        let ratio = 64.0 / min(idealSize.width, idealSize.height)
```
Comment (iccub) [inline Sources/Favicon/UIImage+FaviconRenderer.swift:110]: guard against division by zero maybe

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
