### PR TITLE
Fix # 4111 - Playlist delete item and live stream playback.

### LINKED ISSUE #4111: Remove playlist item from url bar button does not always work
### Steps to Reproduce 
1) add to Brave playlist
2) open in playlist
3) tap done
4) tap button in url bar
5) tap remove

**Actual result:** 
Fails to remove

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes UUID generation for playing where left off. Sometimes without a `return` statement in a lambda in JS, it returns a huge string of "undefined" but other times returns a proper UUID. No idea why.
- Fixes Deleting the item by checking if the cached URL is length 0. This is literally impossible in the first place, but just in case.
- Fixes Streaming live URL to be the direct URL instead of page URL (another fix for bug discovered by Soner: https://github.com/brave/brave-ios/pull/4100)
- Fix possible reason for removing not working (Removing from playlist but not from URLBar - URLBar not updating).
- Fixed possible reason for removing not working (Invalid cache/offline status).
- Fix onboarding showing up when deleting item from playlist but not from URLBar.

This pull request fixes #4111

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift [hunk 1]
```diff
@@ -482,7 +482,7 @@ extension PlaylistCarplayController {
             }
             
             // Attempt to play the stream
-            if let url = URL(string: item.pageSrc) {
+            if let url = URL(string: item.src) {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift:485]: So the `pageSrc` might be different and it will not load  playlist item ?

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift [hunk 2]
```diff
@@ -76,7 +76,7 @@ extension PlaylistListViewController: UITableViewDataSource {
                 }
                 return nil
             }
-        } else {
+        } else if trackStatus != .loading {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift:79]: Dont want to log if it is failed?

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift:485]: It won't be. The `item.src` is guaranteed to be a direct link to the video. The `pageSrc` would be something like `youtube.com/watch?v=VideoID`. In the case where it can't get the video direct link, it will fallback to the webView which will load `pageSrc`.

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift (hunk 2 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDataSource.swift:79]: It will log only if it is `!loading` (not loading). So if it fails or gets cancelled or anything, it will log. But when it is `loading` it will not log because it spams the console with 100+ message that it is loading every single byte :(
