### PR TITLE
Fix: 4294 support wallet add custom asset

### LINKED ISSUE #4294: Add support for adding custom ERC20/ERC721 tokens
On the "Edit Visible Assets" screen, we need to add a button to add a custom asset.  That asset can then be selected/unselected as a visible asset and be part of portfolio balance calculations

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Users now able to add their custom assets from the Edit Visible Asset screen.
Currently only support ERC20 tokens
Once the custom asset is added successfully it will be automatically become a visible asset in user portfolio. 
Portfolio now only displays visible assets.
UserAssetStore will include all tokens from TokenRegistery depends on if user current network selection is mainnet. Otherwise, userAssetStore will only union userAssets and .eth.
In Edit Visible Assets screen, user can swipe to delete custom asset in iOS 15+ and long press the custom asset row and delete it from the context menu for OS below 15.

This pull request fixes #4294 #4520 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:
simulator_screenshot_BEB539AD-A6D3-4DAB-A72D-3B9BEF85D78D

simulator_screenshot_B8FBB39C-8E10-4593-992F-2E1A1868D89B

simulator_screenshot_286F45CF-0BDC-47CC-B007-CCF1E5D4B9B6

simulator_screenshot_61206E52-4E7A-4A69-B338-2B54DB4D19F6

simulator_screenshot_0D40797D-DCB5-4F4C-9ECF-220227A4D3CE

simulator_screenshot_B4E246D5-04CC-46DE-BD73-9E50C8AB3E65

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-11-18 at 16 35 15

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/WalletStrings.swift [hunk 1]
```diff
@@ -1296,5 +1296,103 @@ extension Strings {
...
+      value: "Decimals of precision",
+      comment: "A title that will be displayed on top of the text field for users to input the custom token's decimals of precision"
+    )
+    public static let decimalsPrecisionPlaceholder = NSLocalizedString(
+      "wallet.decimalsPrecisionPlaceholder",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "0",
+      comment: "A placeholder for the text field that users will input the custom token's decimals of precision"
+    )
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: This doesn't need to be localized :)

File: BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+  @State private var nameInput = ""
+  @State private var addressInput = ""
+  @State private var symbolInput = ""
+  @State private var decimalsInput = ""
+  @State private var showError = false
+  
+  var userAssetStore: UserAssetsStore
+  
+  var body: some View {
+    NavigationView {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift:23]: Please check this on iPad, it may need `.navigationStyle(.stack)`

File: BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift [hunk 3]
```diff
@@ -73,6 +86,35 @@ struct EditUserAssetsView: View {
         ) {
           ForEach(tokenStores, id: \.token.id) { store in
             EditTokenView(assetStore: store)
+              .osAvailabilityModifiers { content in
+                if !store.isCustomToken {
+                  content
+                } else {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift]: We shouldn't include non-`#available` checks within this modifier to avoid lifetime side effects

File: BraveWallet/WalletStrings.swift [hunk 4]
```diff
@@ -1296,5 +1296,103 @@ extension Strings {
...
+    public static let customTokenAdd = NSLocalizedString(
+      "wallet.customTokenAdd",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Add",
+      comment: "The title of the navigation bar item button on the top right of the add custom token screen"
+    )
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: We already have this string in WalletStrings (`addAccountAddButton`), maybe just rename that to `add` instead

File: BraveWallet/WalletStrings.swift [hunk 5]
```diff
@@ -1296,5 +1296,103 @@ extension Strings {
...
+    public static let addCustomTokenError = NSLocalizedString(
+      "wallet.addCustomTokenError",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Cannot add your custom token right now",
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: cc @jamesmudgett for copy on these errors

File: BraveWallet/WalletStrings.swift [hunk 6]
```diff
@@ -1296,5 +1296,103 @@ extension Strings {
...
+      comment: "The message in the pop up when there is an error occurs during the process of adding a custom token."
+    )
+    public static let removeCustomTokenError = NSLocalizedString(
+      "wallet.removeCustomTokenError",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Cannot remove your custom token right now",
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: cc @jamesmudgett for copy on these errors

File: BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift [hunk 7]
```diff
@@ -40,6 +40,8 @@ struct EditUserAssetsView: View {
   
   @Environment(\.presentationMode) @Binding private var presentationMode
   @State private var query = ""
+  @State private var showCustomAsset = false
+  @State private var showError = false
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift]: Better naming on what error this is for: e.g. `isPresentingAssetRemovalError`

File: BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift [hunk 8]
```diff
@@ -40,6 +40,8 @@ struct EditUserAssetsView: View {
   
   @Environment(\.presentationMode) @Binding private var presentationMode
   @State private var query = ""
+  @State private var showCustomAsset = false
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift]: nit: naming `isPresentingAddCustomAsset`/`isAddingCustomAsset`

File: BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift [hunk 9]
```diff
@@ -73,6 +86,35 @@ struct EditUserAssetsView: View {
...
+                if !store.isCustomToken {
+                  content
+                } else {
+                  if #available(iOS 15.0, *) {
+                    content
+                      .swipeActions(edge: .trailing) {
+                        Button(role: .destructive) {
+                          userAssetsStore.removeUserAsset(token: store.token) { [self] success in
+                            showError = !success
+                          }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Portfolio/EditUserAssetsView.swift]: Move to its own function and ref in both flows

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift (hunk 2 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift:23]: Looks fine on iPad. I added new screenshot. Tested on iOS 14 and 15

**Review by kylehickinson — APPROVED** [review]
