### PR TITLE
Fix #492, fix #491, don't apply adblock rules on session restore htmls.

### LINKED ISSUE #491: Removing app from memory and relaunch causes empty tabs
### Description: 
Removing app from memory and relaunch causes empty tabs

### Steps to Reproduce 
  1. Visit a few sites in each new tab
  2. Go to settings and enable all shields switches
  3. Remove app from memory 
  4. Relaunch the app, all tabs just retain the site name but is empty, no url, shields shows generic shields text

**Actual result:** 
https://drive.google.com/open?id=1IiJbbmKpJsoGKdBCPpYtejn4xnK-g1jv

**Expected result:**
Should not lose webview state after app is relaunched

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #492: Custom favourites show up as https://localhost:6751/about/sessionrest... in history
### Description: 
Custom favourites show up as https://localhost:6751/about/sessionrest... in history

### Steps to Reproduce 
  1. Visit a few sites in new tab and add as favourite and open the default favourites in new tabs
  2. Enable Block scripts and fingerprint from settings and remove the app from memory
  3. Relaunch the app, go to history
  4. Newly added custom top tiles show up as `https://localhost:6751/about/sessionrest...`

**Actual result:** 
https://drive.google.com/open?id=1f7Fzz_0a7RFmxefmBQ4_914M7q9wMA7t

**Expected result:**
Should show proper site name 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
No adblock rules should be used on session restore urls. It uses javascript to retrieve the
request then the page is reloaded with a proper url and adblocking rules are applied.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -146,9 +146,12 @@ extension BrowserViewController: WKNavigationDelegate {
             // Weird behavior here with `targetFram` and `sourceFrame`, on refreshing page `sourceFrame` is not nil (it is non-optional)
             //  however, it is still an uninitialized object, making it an unreliable source to compare `isMainFrame` against.
             //  Rather than using `sourceFrame.isMainFrame` or even comparing `sourceFrame == targetFrame`, a simple URL check is used.
+            // No adblocking logic is be used on session restore urls. It uses javascript to retrieve the
+            // request then the page is reloaded with a proper url and adblocking rules are applied.
             if
                 let mainDocumentURL = navigationAction.request.mainDocumentURL,
                 mainDocumentURL == url,
+                !url.isSessionRestoreURL,
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:154]: Not 100% sure about placement of this check. Alternatively I could place it only before applying script blocking, but I do not think there is any case where we want to do ad block operations on session restore htmls

File: Shared/Extensions/URLExtensions.swift [hunk 2]
```diff
@@ -366,6 +366,10 @@ extension URL {
     public var safeBrowsingErrorURL: Bool {
         return scheme == "http" && host == "localhost" && path.contains("/errors/SafeBrowsingError.html")
     }
+    
+    public var isSessionRestoreURL: Bool {
+        return scheme == "http" && host == "localhost" && path.contains("/about/sessionrestore")
```
Comment (jhreis) [inline Shared/Extensions/URLExtensions.swift]: Let's abstract the first part of this: `scheme == "http" && host == "localhost"`, as it is used in 3 places now. Maybe a (or something):
```
private var isLocalhost: Bool {
    return scheme == "http" && host == "localhost"
}
```

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 1 above)
Comment (jhreis) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:154]: Yeah, I think this is correct.

**Review by jhreis — CHANGES_REQUESTED** [review]

**Comment by danishjafri88** [comment]
Is there a case where we will apply adblock rules to any localhost calls? If no we can change the check to !url.isLocalhost.

**Comment by jhreis** [comment]
@danishjafri88 I am unsure if iOS does, but to match desktop, we will leave shields functional wherever possible. There are some situations where we post external content on our own server (e.g. reader-mode), where having shields enabled may be necessary.

**Comment by danishjafri88** [comment]
Fixes #491

**Review by jhreis — APPROVED** [review]
