### PR TITLE
Fix #2325: Re download NTP assets immediately once setting is re-enab…

### LINKED ISSUE #2325: NTP SI - Images not showing after disabled and enabled
### Description: 
NTP SI are not shown if a user turns off SI in settings and then enables SI again.

### Steps to Reproduce 
  1. Go to settings and turn off SI
  2. Close settings
  3. Open settings and enable SI

**Actual result:** 
SI are not shown again

**Expected result:**
SI should be shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easy

**Brave Version:** 
1.14.3

### PR DESCRIPTION
**Pull request by iccub**
…led.

## Summary of Changes

This pull request fixes issue #2325

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

str in the ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/HomePanel/NTPBackgroundDataSource.swift [hunk 1]
```diff
@@ -204,6 +204,7 @@ extension NTPBackgroundDataSource: PreferencesObserver {
         if sponsoredPref.key == key {
             if sponsoredPref.value {
                 // Enabled? -> issue download
+                Preferences.NTP.ntpCheckDate.value = nil
```
Comment (iccub) [inline Client/Frontend/Browser/HomePanel/NTPBackgroundDataSource.swift:207]: without it, after reenabling the setting user needs to wait for another NTP fetch tick(~5 hours)

**Review by Brandon-T — APPROVED** [review]
