### PR TITLE
Fix #3496: Pop-over messages should not be shown on NTP

### LINKED ISSUE #3496: Pop-over messages should not be shown on NTP
Description:
The pop-over messages are being shown when NTP is on active display.

Steps to Reproduce

- Follow test plan from #3387
- Create a new tab using the + icon on bottom toolbar while page is loading

**Actual  result:**

Image from iOS (20)

**Expected result:**

No pop-over should be presented on NTP

Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced,

Brave Version:
1.24(21.3.25.18)

Device details:
All

Website problems only:

did you check with Brave Shields down? N_A
did you check in Safari/Firefox (WkWebView-based browsers)? N_A

### PR DESCRIPTION
**Pull request by soner-yuksel**
Changing the debug values divide by 100 and adding condition for NTP is on the screen

## Summary of Changes

This pull request fixes #3496

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- While testing Benchmark Tiers in Debug Scheme observe Tier values will be presented divided by 100 for easy testing
- Check Pop-over messages are being shown when NTP is on active display

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+ProductNotification.swift [hunk 1]
```diff
@@ -50,7 +50,7 @@ extension BrowserViewController {
         }
         
         var value: Int {
-            AppConstants.buildChannel.isPublic ? self.rawValue : self.rawValue / 10
+            AppConstants.buildChannel.isPublic ? self.rawValue : self.rawValue / 100
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+ProductNotification.swift:53]: Is this ok by QA or you adding another hardocded values in other PR?

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+ProductNotification.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+ProductNotification.swift:53]: No I asked QA about it and they actually said they preferred this and it is fine 1 mil / 100 :)
