### PR TITLE
Fix #5208: Fixes Cosmetic Filters Crash on Network Call

### LINKED ISSUE #5208: Sometimes Cosmetic Filters can crash when making a network request
### Description: 
- Under some very weird circumstances, Cosmetic Filters can crash while making a network request

### Steps to Reproduce 
  1. No idea

**Actual result:** 
- Crash in Xcode Organizer

**Expected result:**
- No Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Very Hard

**Brave Version:** 
1.36

**Device details:** 
Any

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Switch all Cosmetic Filters code to use publishers instead of Async Await (some sort of weird crash is happening that can't be reproduced)

This pull request fixes #5208

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Test Cosmetic Filters
Test Adblock and Adblock Stats

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Networking/NetworkSession.swift [hunk 1]
```diff
@@ -23,6 +30,40 @@ extension URLSession: NetworkSession {
       httpVersion: "HTTP/1.1",
       headerFields: [:])!
   }
+  
+  func dataRequest(with url: URL, _ completion: @escaping (Result<NetworkSessionDataResponse, Error>) -> Void) {
+    self.dataTask(with: url) { data, response, error in
+      if let error = error {
+        completion(.failure(error))
+      } else {
+        completion(.success((data ?? Data(), response ?? self.createResponse(url: url))))
```
Comment (iccub) [inline Client/Networking/NetworkSession.swift:39]: should we return a failure if `data` is nil?

File: Client/Networking/NetworkSession.swift [hunk 2]
```diff
@@ -23,6 +30,40 @@ extension URLSession: NetworkSession {
...
+      }
+    }.resume()
+  }
+  
+  func dataRequest(with urlRequest: URLRequest, _ completion: @escaping (Result<NetworkSessionDataResponse, Error>) -> Void) {
+    self.dataTask(with: urlRequest) { data, response, error in
+      if let error = error {
+        completion(.failure(error))
+      } else {
+        completion(.success((data ?? Data(), response ?? self.createResponse(url: urlRequest.url))))
```
Comment (iccub) [inline Client/Networking/NetworkSession.swift:49]: should we return a failure if `data` is nil?

File: Client/WebFilters/CosmeticFiltersResourceDownloader.swift [hunk 3]
```diff
@@ -64,109 +66,122 @@ class CosmeticFiltersResourceDownloader {
...
   }
 
-  private func downloadCosmeticSamples(with engine: AdblockRustEngine) async throws {
-    try await downloadResources(for: engine, type: .cosmeticSample)
-    log.debug("Downloaded Cosmetic Filters CSS Samples")
-    Preferences.Debug.lastCosmeticFiltersCSSUpdate.value = Date()
+  private func downloadCosmeticSamples(with engine: AdblockRustEngine) -> AnyPublisher<Void, Error> {
+    downloadResources(for: engine, type: .cosmeticSample)
+      .receive(on: DispatchQueue.main)
+      .map {
```
Comment (iccub) [inline Client/WebFilters/CosmeticFiltersResourceDownloader.swift:165]: what does it `map` to? shouldn't sink be used here or something else

File: Client/WebFilters/CosmeticFiltersResourceDownloader.swift [hunk 4]
```diff
@@ -64,109 +66,122 @@ class CosmeticFiltersResourceDownloader {
...
 
-  private func downloadResourceSamples(with engine: AdblockRustEngine) async throws {
-    try await downloadResources(for: engine, type: .resourceSample)
-    log.debug("Downloaded Cosmetic Filters Scriptlets Samples")
-    Preferences.Debug.lastCosmeticFiltersScripletsUpdate.value = Date()
+  private func downloadResourceSamples(with engine: AdblockRustEngine) -> AnyPublisher<Void, Error> {
+    return downloadResources(for: engine, type: .resourceSample)
+      .receive(on: DispatchQueue.main)
+      .map {
+        log.debug("Downloaded Cosmetic Filters Scriptlets Samples")
```
Comment (iccub) [inline Client/WebFilters/CosmeticFiltersResourceDownloader.swift:176]: what does it map to? shouldn't sink be used here or something else

File: Client/Networking/NetworkSession.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Networking/NetworkSession.swift:39]: I left it like this because the previous code was doing it, but I think it's actually better to return an error if it is nil. Though some requests might not return any data for the body.

File: Client/WebFilters/CosmeticFiltersResourceDownloader.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/WebFilters/CosmeticFiltersResourceDownloader.swift:165]: It maps to nothing. The `downloadResources` function just returns `Void` already. So when I called `map` here, it's just like calling `.then` on a `promise`. So no need for sink here because I'm not returning a `AnyCancellable`. This function is executed as part of the chain of completion :)

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 5]
```diff
@@ -409,9 +409,22 @@ class BrowserViewController: UIViewController, BrowserViewControllerDelegate {
...
+    var contentBlockListTask: AnyCancellable?
+    contentBlockListTask = ContentBlockerHelper.compileBundledLists()
+      .receive(on: DispatchQueue.main)
+      .sink { [weak self] res in
+        switch res {
+        case .failure(let error):
+          log.error("Content Blocker failed to compile bundled lists: \(error)")
+        default:
+          break
+        }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: nit: Can be simplified to 

```swift
if case .failure(let error) = res { 
  log.error(...)
}
```

Since you are not checking the other cases

File: Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift [hunk 6]
```diff
@@ -198,20 +198,20 @@ extension BrowserViewController {
...
-        await MainActor.run { [weak self] in
-          guard
-            let openSearchEngine = OpenSearchParser(pluginMode: true).parse(
-              response.data, referenceURL: reference, image: icon, isCustomEngine: true)
-          else {
-            return
-          }
-
-          self?.addSearchEngine(openSearchEngine)
+    NetworkManager().downloadResource(with: url) { [weak self] result in
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/OpenSearch/BrowserViewController+OpenSearch.swift]: Technically you don't need weak self here since you are not holding onto a ref to the network manage and BVC never dies (atm)

File: Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift [hunk 7]
```diff
@@ -535,49 +552,88 @@ class NTPDownloader {
...
-              let (data, _) = try await self.download(type: type, path: itemURL, etag: nil)
-              let file = directory.appendingPathComponent(itemURL)
-              try data.write(to: file, options: .atomicWrite)
-            }
+      for itemURL in imagesToDownload {
+        group.enter()
+        self.download(type: type, path: itemURL, etag: nil) { data, _, err in
+          if let err = err {
+            error = err
+            group.leave()
```
Comment (kylehickinson) [inline Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift]: Just add `defer { group.leave() }` to the top of the closure instead of having to remember calling leave before each return

File: Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift [hunk 8]
```diff
@@ -535,49 +552,88 @@ class NTPDownloader {
...
+        }
+
+        for topSite in topSites {
+          group.enter()
+
+          self.download(type: type, path: topSite.iconUrl, etag: nil) { data, _, err in
+            if let err = err {
+              error = err
+              group.leave()
+              return
```
Comment (kylehickinson) [inline Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift]: Same as above

File: Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift [hunk 9]
```diff
@@ -38,13 +39,24 @@ class AdblockDebugMenuTableViewController: TableViewController {
...
+          
+          var compileListsTask: AnyCancellable?
+          compileListsTask = ContentBlockerHelper.compileBundledLists()
+            .receive(on: DispatchQueue.main)
+            .sink { [weak self] res in
+              switch res {
+              case .failure(let error):
+                let alert = UIAlertController(title: nil, message: "Failed to Recompile Blockers: \(error)", preferredStyle: .alert)
+                alert.addAction(UIAlertAction(title: "OK", style: .default))
+                self?.present(alert, animated: true)
```
Comment (kylehickinson) [inline Client/Frontend/Settings/AdblockDebugMenuTableViewController.swift]: same comment as above

File: Client/Networking/NetworkManager.swift [hunk 10]
```diff
@@ -21,6 +39,74 @@ class NetworkManager {
...
+    checkLastServerSideModification: Bool = false,
+    customHeaders: [String: String] = [:]
+  ) -> AnyPublisher<CachedNetworkResource, Error> {
+    let request = createDownloadRequest(with: url,
+                                        resourceType: resourceType,
+                                        customHeaders: customHeaders)
+    
+    if let retryTimeout = retryTimeout {
+      return dataRequest(with: request)
+        .retry(3, delay: .init(floatLiteral: retryTimeout), scheduler: DispatchQueue.main)
```
Comment (kylehickinson) [inline Client/Networking/NetworkManager.swift]: Why `.init(floatLiteral:)`?

File: Client/Networking/NetworkManager.swift [hunk 11]
```diff
@@ -21,6 +39,74 @@ class NetworkManager {
...
+  /// - parameter checkLastServerSideModification: If true, the `CachedNetworkResource` will contain a timestamp
+  /// when the file was last time modified on the server.
+  func downloadResource(
+    with url: URL,
+    resourceType: NetworkResourceType = .regular,
+    retryTimeout: TimeInterval? = 60,
+    checkLastServerSideModification: Bool = false,
+    customHeaders: [String: String] = [:],
+    _ completion: @escaping (Result<CachedNetworkResource, Error>) -> Void
+  ) {
```
Comment (kylehickinson) [inline Client/Networking/NetworkManager.swift:52]: Why do we have both closure and combine based solutions for this? We should probably only have 1 solution that is called by both. You can make the one that returns an AnyPublisher simply return a `Future` that calls this one

File: Client/Networking/NetworkSession.swift [hunk 12]
```diff
@@ -3,10 +3,17 @@
...
 
 protocol NetworkSession {
+  func dataRequest(with url: URL, _ completion: @escaping (Result<NetworkSessionDataResponse, Error>) -> Void)
+  func dataRequest(with urlRequest: URLRequest, _ completion: @escaping (Result<NetworkSessionDataResponse, Error>) -> Void)
+  
+  func dataRequest(with url: URL) -> AnyPublisher<NetworkSessionDataResponse, Error>
+  func dataRequest(with urlRequest: URLRequest) -> AnyPublisher<NetworkSessionDataResponse, Error>
+  
   func dataRequest(with url: URL) async throws -> NetworkSessionDataResponse
   func dataRequest(with urlRequest: URLRequest) async throws -> NetworkSessionDataResponse
```
Comment (kylehickinson) [inline Client/Networking/NetworkSession.swift:18]: Should we keep these if they were causing problems?

File: Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift [hunk 13]
```diff
@@ -409,39 +409,40 @@ class NTPDownloader {
...
-    do {
-      (data, cacheInfo) = try await download(
-        type: type,
-        path: type.resourceName,
-        etag: getETag(type: type))
-    } catch {
-      throw NTPError.metadataError(error)
-    }
+      if let error = error {
+        return completion(nil, nil, .metadataError(error))
```
Comment (kylehickinson) [inline Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift]: Can be consistent with these `return completion(...)` calls? I see both 

```
completion(...)
return
```

and

```
return completion(...)
```

I think we decided on the former in the past, but I can't remember

File: Client/Networking/NetworkManager.swift [hunk 14]
```diff
@@ -31,30 +117,89 @@ class NetworkManager {
...
+        completion(.failure("Network Manager Deallocated"))
+        return
+      }
+      
+      switch $0 {
+      case .success(let result):
+        completion(.success(result))
+      case .failure(let error):
+        if times > 0 {
+          DispatchQueue.main.asyncAfter(deadline: .now() + retryDelay) {
```
Comment (kylehickinson) [inline Client/Networking/NetworkManager.swift]: The other version of retry takes a scheduler directly, should we do the same for this?

File: Client/WebFilters/ContentBlocker/BlocklistName.swift [hunk 15]
```diff
@@ -88,36 +89,43 @@ class BlocklistName: CustomStringConvertible, ContentBlocker {
...
-      log.error("Could not read data for content blocker compilation.")
-      return
-    }
-
-    do {
-      let rule = try await ruleStore.compileContentRuleList(forIdentifier: filename, encodedContentRuleList: dataString)
+  ) -> AnyPublisher<Void, Error> {
+    return Future { [weak self] completion in
+      guard let self = self else {
+        completion(.failure("BlockListName Deallocated"))
```
Comment (kylehickinson) [inline Client/WebFilters/ContentBlocker/BlocklistName.swift:109]: Should a completion block be called if the blocklist itself is no longer around?

**Review by kylehickinson — CHANGES_REQUESTED** [review]
initial review, as per slack, replace flatMap's and check eager vs deferred publishers,

rest is mostly nits :)

File: Client/Networking/NetworkManager.swift (hunk 10 above)
Comment (Brandon-T) [reply Client/Networking/NetworkManager.swift]: Changed to `.seconds`

File: Client/Networking/NetworkManager.swift (hunk 11 above)
Comment (Brandon-T) [reply Client/Networking/NetworkManager.swift:52]: Fixed. I chose to just retain the publisher locally. That way I can get rid of the duplicate `retry` too.

File: Client/Networking/NetworkSession.swift (hunk 12 above)
Comment (Brandon-T) [reply Client/Networking/NetworkSession.swift:18]: I want to keep them for now because I want to run some tests some time to see what is causing the issue and I'm hoping with an upgraded Xcode it will either crash or give an error or be fixed :D .

File: Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift (hunk 13 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/New Tab Page/Backgrounds/NTPDownloader.swift]: Fixed it was indeed the former. I basically didn't touch anything in the file, I just did a git reset and worked from there, so these show up as changes when it's just legacy code :)

File: Client/WebFilters/ContentBlocker/BlocklistName.swift (hunk 15 above)
Comment (Brandon-T) [reply Client/WebFilters/ContentBlocker/BlocklistName.swift:109]: I think it should call it. I rather not have a dangling future :) but I did guard against the errors anyway. So if this does happen, it just logs the error to let us know why compilation failed so at least we'd know we need to hold a ref.

**Review by kylehickinson — APPROVED** [review]
