### PR TITLE
Fix #3470: Update Tab's title when website's URL changes dynamically.

### LINKED ISSUE #3470: Tab title does not get updated on youtube.
### Steps to Reproduce 
  1. Make sure tabs are visible, by default on iPad or open at least 2 tabs on iPhone
  2. Go to youtube
  2. Tap on a video
  3. Tap on a different video, from recommended list for example

**Actual result:** 
Tab title has not changed

**Expected result:**
Tab title should have changed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #3470 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

STR in the ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift [hunk 1]
```diff
@@ -157,15 +157,34 @@ class TabsBarViewController: UIViewController {
...
+        if let cell = collectionView.cellForItem(at: selectedTabIndex) as? TabBarCell {
+            cell.titleLabel.text = tab.displayTitle
+        }
+        
+    }
+    
     func reloadDataAndRestoreSelectedTab() {
         collectionView.reloadData()
         
-        if let tabManager = tabManager, let selectedTab = tabManager.selectedTab {
```
Comment (iccub) [inline Client/Frontend/Browser/TabsBar/TabsBarViewController.swift:163]: No changes here, only extracted selectedTabIndexPath to a helper function, please double check though

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift [hunk 2]
```diff
@@ -157,15 +157,34 @@ class TabsBarViewController: UIViewController {
...
+                                      animated: (!tabManager.isRestoring),
+                                      scrollPosition: .centeredHorizontally)
+        }
+    }
+    
+    private var selectedTabIndexPath: IndexPath? {
+        guard let tabManager = tabManager, let selectedTab = tabManager.selectedTab else { return nil }
+        let selectedIndex = tabList.index(of: selectedTab) ?? 0
+        
+        return IndexPath(row: selectedIndex, section: 0)
```
Comment (Brandon-T) [inline Client/Frontend/Browser/TabsBar/TabsBarViewController.swift:187]: For this line, instead of defaulting to index path 0 which is the very first tab, can we return nil since the return is optional?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/TabsBar/TabsBarViewController.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Browser/TabsBar/TabsBarViewController.swift:187]: yes

**Review by soner-yuksel — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
