### PR TITLE
Fix #3633 - iPad Offline File Location

### LINKED ISSUE #3633: Do not show videos saved in playlist under Downloaded videos
### Description: 
Do not show videos saved in playlist under Downloaded videos

### Steps to Reproduce 
  1. Install 1.25 build
  2. Open any video and add it to playlist for offline viewing
  3. Open Settings -> iPad Storage -> Recently Downloaded video
  4. Lists all videos saved for offline

**Actual result:** 
image | image
-- | --

**Expected result:**
Videos saved for offline view should not be listed under Downloaded videos

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.5.4.19)

**Device details:** 
iPad Pro (iOS 14.5)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Moved iPad playlist downloads under m3u8 downloader to same folder as all other files.

This pull request fixes #3633

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift [hunk 1]
```diff
@@ -317,6 +317,21 @@ private class PlaylistHLSDownloadManager: NSObject, AVAssetDownloadDelegate {
         
         guard let asset = activeDownloadTasks.removeValue(forKey: task),
               let assetUrl = pendingDownloadTasks.removeValue(forKey: task) else { return }
+        
+        let cleanupAndFailDownload = { (location: URL?, error: Error) in
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Cache/PlaylistDownloadManager.swift:325]: You prefer this over having a normal function?

**Review by iccub — APPROVED** [review]
