### PR TITLE
Fix #5534: Add zero-width space for eTLD+1 url to force the origin is wrapped as a whole.

### LINKED ISSUE #5534: Wallet: Make sure eTLD+1 wraps as a whole
### Description: 
In many screens, we display eTLD+1 to indicates this DApp is making a request or eth permission edit mode.
We have bolded the eTLD+1 but currently it wrapps and breaks it apart when the url origin is long enough. This is hard for users to notice the eTLD+1 part from the long url. That is a security concern we need to fix. 

### Steps to Reproduce 
  1. Go to any screen display url origin. for example, edit site connection screen
  2. make sure the eTLD+1 is bolded and wrapped as a whole if the url is very long

**Actual result:** 
eTLD+1-wrapps

**Expected result:**
eTLD+1_wrapps_correct

**Note: after this https://github.com/brave/brave-ios/pull/5522, insecure context page will no longer get injected wallet provider js.**
Here is a [long url with wallet dapp functionality](http://www.reddit.com_______________________________________________.__________________________.______________www.reddit.com______________________________________________________.___._______________wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.xdv.cz.srv21.endora.cz/metapoc/index.html)

### PR DESCRIPTION
**Pull request by nuo-xu**
## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Please refer to the issue

## Screenshots:
simulator_screenshot_7EFEC0DC-DDAF-47F9-926A-F43C27E2C126

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by StephenHeaps — APPROVED** [review]

**Comment by kylehickinson** [comment]
@nuo-xu Can you please make an issue for this and move the test cases there for QA to verify

File: BraveWallet/Extensions/Text+URLOrigin.swift [hunk 1]
```diff
@@ -19,7 +19,8 @@ extension Text {
         let originStart = origin[origin.startIndex..<range.lowerBound]
         let etldPlusOne = origin[range.lowerBound..<range.upperBound]
         let originEnd = origin[range.upperBound...]
-        self = Text(originStart) + Text(etldPlusOne).bold() + Text(originEnd)
+        let zwspEtldPlusOne = "\u{200b}\(String(etldPlusOne))"
```
Comment (kylehickinson) [inline BraveWallet/Extensions/Text+URLOrigin.swift:22]: What does VoiceOver read this out as? Do we need to set `accessibilityLabel` somewhere?
