### PR TITLE
Fix #8709: Portfolio filters not opening intermittently

### LINKED ISSUE #8709: Portfolio asset filters does not always open
### Description: 

Sometimes tapping the filters button in the assets section of Portfolio tab does not open the filters tray intermittently.

### Steps to Reproduce 
  1. Scroll to bottom of Portfolio
  2. Scroll to top
  3. Tap filters button
  4. Observe filters tray does not open (intermittent)
     - Sometimes scrolling up/down will open the tray

### Actual result: 

Tapping filters button does not open filters tray.

https://github.com/brave/brave-ios/assets/5314553/c314b0d4-1d5c-4baa-99a5-012e463aeec3

### Expected result:

Tapping filters button always opens filters tray

### Reproduces how often: 

Intermittent Issue

### Brave Version:

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Moved Portfolio Assets & NFT filter sheet presentations outside of Portfolio `ScrollView`, previously in a `LazyVStack` which seems to have caused presentation issues after scrolling larger lists of assets.
- Updated some layout logic to remove `LazyVStack`s where not necessary; occasionally hitting mis-estimated row heights in the assets listscroll view.

This pull request fixes #8709

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Open Portfolio filters and group assets by account (easier to reproduce when grouped).
2. Collapse 1 or more of the groups, but not all (keep some larger groups expanded).
3. Scroll up and down the Portfolio assets list quickly.
4. Tap Filters button
5. Verify filters tray always opens.
6. Repeat a few times; this bug was not occurring consistently.

## Screenshots:

https://github.com/brave/brave-ios/assets/5314553/f49a8f88-ee07-4570-b028-5d90f7b0995d

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/NFT/NFTView.swift [hunk 1]
```diff
@@ -50,25 +49,6 @@ struct NFTView: View {
     .padding(.horizontal, 32)
   }
   
-  private var editUserAssetsButton: some View {
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/NFT/NFTView.swift:53]: This wasn't in use for NFTs section anymore after updating to open Add NFT directly.

**Review by nuo-xu — APPROVED** [review]
