### PR TITLE
Fix #1695, Fix #1720, Fix #1719: Removes Onboarding agreement checkbox & Updates UI.

### LINKED ISSUE #1695: Remove Rewards ToS checkbox slide in onboarding
## Description 
Currently, there is an additional step in the onboarding flow to check the Rewards Terms of Service checkbox:
ios 4

Remove the checkbox slide and add "By turning on Rewards, you agree to the Terms of Service." to the Rewards slide.

## Design
ios 3

### New user, In ad region
Show search engine selection, Brave Shields explanation, Brave Rewards, and ad onboarding.

user flow - ios onboarding ads available

### New user, Out of ad region
Show search engine selection, Brave Shields explanation, and Brave Rewards.

user flow - ios onboarding ads unavailable

ios ads unavailable

### Existing user, in ad region
Show Brave Rewards and ad onboarding.
user flow - ios onboarding existing user in ad region

### Existing user, out of ad region
Show Brave Rewards.
user flow - ios onboarding existing user out of ad region

ios ads unavailable

### (Future case) Existing user, BR on, ad becomes available in the region
Show ad onboarding.

user flow - ios onboarding BR on notify ads

ios br on

### LINKED ISSUE #1719: Onboarding continue buttons are not horizontally centered
Onboarding continue buttons are not properly horizontally centered as seen by this screen:

Group

This is true for other onboarding screens as well despite there being enough space to be centered without breaking the Skip button layout

### LINKED ISSUE #1720: Onboarding Terms and conditions web view cannot be exit on iOS 12
### Description: 

When you click the terms and conditions button while onboarding rewards on an iOS 12 device the bar which allows you to close the web view does not appear

https://bravesoftware.slack.com/archives/C06UXF3KJ/p1570824862027700

**Device details:** Tested and not working iOS 12 on an iPhone 7

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
Removes the onboarding terms of agreement checkbox and the logic to dim the agreement button.
Updates insets to match design.
Added new sub-title label on the agreement screen.

This pull request fixes issue #1695
This pull request fixes issue #1720 
This pull request fixes issue #1719

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — CHANGES_REQUESTED** [review]
There's an extra step in onboarding in this implementation:

As per flow here: https://github.com/brave/brave-ios/issues/1695

The initial "Brave Rewards" screen that used to be before the checkbox screen is gone now. Now only the one with the ToS link exists (basically just removing a screen from the flow)

This also means that "cancel" is no longer a valid button, and it will go to "Skip" the same as the other screens

**Comment by Brandon-T** [comment]
Also forgot to mention, cancel no longer goes "BACKWARDS" which changed quite a bit. It always goes forwards now that it's skip and triggers the 60-day flow.

File: Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift [hunk 1]
```diff
@@ -33,22 +44,23 @@ class OnboardingRewardsAgreementViewController: OnboardingViewController {
     }
     
     override func continueTapped() {
+        rewards?.ads.isEnabled = true
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift]: Which continue button is this? Is this this screen? 
 
Simulator Screen Shot - iPhone 11 Pro - 2019-10-17 at 11 34 02

Comment (Brandon-T) [reply Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift]: @kylehickinson 

Correct. Honestly I purposely changed the name to "continue" because this one button has had it's fair share of changes lol.. "ShowMe", "Join", "Turn On", "Continue", etc.. I just decided "continue" will be generic enough that if I change the title it just means it continues to the next screen.

If we want, I can change it's name to "turnOnButton" or something.

Comment (kylehickinson) [reply Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift]: The main issue is you can't enable ads like this anymore. It will be enabled automatically based on if your region is supported when you create the wallet. The only time you have to set this to true is when you're turning on ads for existing users who have enabled rewards already when their region was unsupported and now their region is supported

Comment (kylehickinson) [reply Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift]: @Brandon-T ☝️

Comment (Brandon-T) [reply Client/Frontend/Browser/Onboarding/OnboardingRewardsAgreementViewController.swift]: Fixed.

File: Client/Frontend/Browser/Onboarding/OnboardingNavigationController.swift [hunk 2]
```diff
@@ -55,8 +55,8 @@ class OnboardingNavigationController: UINavigationController {
             }
             #else
             switch self {
-            case .newUser: return BraveAds.isCurrentRegionSupported() ? [.searchEnginePicker, .shieldsInfo, .rewardsInfo, .rewardsAgreement, .adsCountdown] : [.searchEnginePicker, .shieldsInfo, .rewardsInfo, .rewardsAgreement]
-            case .existingUserRewardsOff: return BraveAds.isCurrentRegionSupported() ? [.rewardsInfo, .rewardsAgreement, .adsCountdown] : []
+            case .newUser: return BraveAds.isCurrentRegionSupported() ? [.searchEnginePicker, .shieldsInfo, .rewardsAgreement, .adsCountdown] : [.searchEnginePicker, .shieldsInfo, .rewardsAgreement]
+            case .existingUserRewardsOff: return BraveAds.isCurrentRegionSupported() ? [.rewardsAgreement, .adsCountdown] : []
             case .existingUserRewardsOn: return BraveAds.isCurrentRegionSupported() ? [.rewardsInfo, .adsCountdown] : []
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Onboarding/OnboardingNavigationController.swift:60]: Can we change `rewardsInfo` to something that describes that we're just turning on ads for the user here? Since it looks like `OnboardingRewardsViewController` is only for this one flow now its a bit confusing to figure out which screen belongs to that this flow.

**Review by kylehickinson — CHANGES_REQUESTED** [review]
Just one minor last thing for future us. Then should be good to go

**Review by kylehickinson — APPROVED** [review]
