### PR TITLE
Fix #7366: Tab restoring white screen sometimes

### LINKED ISSUE #7366: Sometimes tabs lose their order or get a white screen
### Description: 
- Sometimes tabs lose their ordering when restoring
- Sometimes tabs restore to a white screen instead of the page being viewed (extremely hard to reproduce!)

### Steps to Reproduce 
  1. Open a bunch of websites
  2. Kill the app
  3. Re-open the app
  4. Repeat

### Actual result: 
- Sometimes the tab restored is a white screen
- Sometimes the order of the tabs change

### Expected result:
- Should restore properly
- Should keep restoration order

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Extremely hard to reproduce

### Brave Version: 

- 1.51.x

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix tab error messages and ordering
- Fix tab restoring to white screen

This pull request fixes #7366

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Data/models/SessionTab.swift [hunk 1]
```diff
@@ -176,12 +179,14 @@ extension SessionTab {
...
-        guard let sessionTab = Self.from(tabId: tab.tabId, in: context) else { return }
+      for tab in tabs {
+        guard let sessionTab = Self.from(tabId: tab.tabId, in: context) else {
+          Logger.module.error("Error: SessionTab.updateAll missing managed object")
+          continue
+        }
         sessionTab.interactionState = tab.interactionState
         sessionTab.title = tab.title
         sessionTab.url = tab.url
-        sessionTab.index = Int32(index)
```
Comment (kylehickinson) [inline Sources/Data/models/SessionTab.swift:184]: Is this change intended?

Comment (Brandon-T) [reply Sources/Data/models/SessionTab.swift:184]: Yeah it is intended so tabs keep their index.

Comment (kylehickinson) [reply Sources/Data/models/SessionTab.swift:184]: Oh I didnt realize this PR was fixing 2 separate issues

**Review by kylehickinson — APPROVED** [review]

**Review by soner-yuksel — APPROVED** [review]
