### PR TITLE
Fix #8107: Fix incorrect account opening Send from Filecoin asset detail

### LINKED ISSUE #8107: Incorrect account opening Send from Filecoin asset detail
### Description: 

Tapping `Send` on Filecoin asset detail for Filecoin Mainnet will crash if user has no Filecoin accounts

### Steps to Reproduce 
  1. Setup a wallet without any Filecoin accounts or restore a wallet without FIL balance (so no Filecoin accounts are created)
  2. Open FIL on Filecoin Mainnet asset detail screen
  3. Tap Send
  4. Incorrect account is selected for Filecoin mainnet

### Actual result: 

Incorrect account type is selected (not a Filecoin account).
Crashes on debug builds.

https://github.com/brave/brave-ios/assets/5314553/01e1a532-de48-4e43-8330-95f0b90e3ef0

### Expected result:

Prompts to create a Filecoin account

### Reproduces how often: 

Easily reproduced

### Brave Version:

v1.58

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes

This pull request fixes #8107

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

1. make sure you wallet has no filecoin account (create a new wallet)
2. turn on show test networks in Settings
3. go to `FIL` asset detail screen
4. click either buy or send button
5. you should get prompt with an alert asking you if you want to create an account
6. Click no an the alert to dismiss the alert, you will still be at the asset detail screen, and not be redirected to other screen.
7. Click yes to bring up account creation screen with Filecoin UI with correct Filecoin network preselected and no way to change it. (e.x if you comes from FIL on testnet asset details screen, account creation screen should pre-selected Filecoin Testnet instead of Mainnet.)
8. Either click cancel or swipe down to dismiss account creation screen, you will still be at the asset detail screen, and not be redirected to other screen.
9. Repeat step 4 - 6
10. Fill in all the information or leave them as they are then click `Add` to create a new account
11. Observe that the account creation screen will be dismissed and you will be redirected to Buy/Send screen depends on which button you clicked in step 8
12. Goes back to the asset screen again
13. repeat step 3
14. Observe this time, you will be redirect to Buy/Send screen depends on which button you clicked in step 12 since now we a filecoin account 

=====================

1. make sure you wallet has no filecoin account (create a new wallet)
2. turn on show test networks in Settings 
3. got buy/swap screen 
4. open network selection and choose either Filecoin Mainnet or Filecoin Testnet
5. you should get prompt with an alert asking you if you want to create an account
6. Click no an the alert to dismiss the alert, you will still be at the network selection screen, and not be redirected to other screen.
7. Click yes to bring up account creation screen with Filecoin UI with correct Filecoin network preselected and no way to change it. (e.x if you comes from FIL on testnet asset details screen, account creation screen should pre-selected Filecoin Testnet instead of Mainnet.)
8. Either click cancel or swipe down to dismiss account creation screen, you will still be at the network selection screen, and not be redirected to other screen.
9. Repeat step 4 - 6
10. Fill in all the information or leave them as they are then click `Add` to create a new account
11. Observe that the account creation screen will be dismissed then network selection will be dismissed and the correct network has been selected.

## Screenshots:

https://github.com/brave/brave-ios/assets/1187676/0268fe56-11c5-4beb-b9c8-6bc5d20b2fcb

https://github.com/brave/brave-ios/assets/1187676/fc86db6c-aec8-439f-bb35-e583235e2c2d

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/BuySendSwap/SendTokenView.swift [hunk 1]
```diff
@@ -292,7 +294,7 @@ struct SendTokenView: View {
         }
       }
     }
-    .task {
+    .task { @MainActor in
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/BuySendSwap/SendTokenView.swift]: I don't think `@MainActor` annotation is needed here since `.task` declared on the `body`: https://oleb.net/2022/swiftui-task-mainactor/

File: Sources/BraveWallet/Extensions/KeyringServiceExtensions.swift [hunk 2]
```diff
@@ -63,4 +63,9 @@ extension BraveWalletKeyringService {
     )
     return allKeyrings
   }
+  
+  /// Check if prefilled token's coin type has an associated keyring created.
+  @MainActor func isKeyringAvailable(for coin: BraveWallet.CoinType) async -> Bool {
+    await !keyrings(for: coin.keyringIds).filter(\.isKeyringCreated).isEmpty
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Extensions/KeyringServiceExtensions.swift]: nit: I think you can just do for better readability (no negatives + isEmpty 😅):
```await keyrings(for: coin.keyringIds).contains(where: \.isKeyringCreated)```

I think we should make the comment above function more about what the function does than where it's used (prefilled token is irrelevant here) 🙂.

File: Sources/BraveWallet/Crypto/Stores/NetworkStore.swift [hunk 3]
```diff
@@ -272,6 +272,10 @@ public class NetworkStore: ObservableObject {
   func customNetworkNativeAssetMigration(_ network: BraveWallet.NetworkInfo, completion: (() -> Void)? = nil) {
     assetManager.addUserAsset(network.nativeToken, completion: completion)
   }
+  
+  func network(for token: BraveWallet.BlockchainToken) -> BraveWallet.NetworkInfo {
+    return allChains.first { $0.chainId == token.chainId } ?? customChains.first { $0.chainId == token.chainId } ?? allChains.first ?? .init()
+  }
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Stores/NetworkStore.swift]: Shouldn't this just return optional instead of `allChains.first ?? .init()`?

File: Sources/BraveWallet/Extensions/ViewExtensions.swift [hunk 4]
```diff
@@ -30,4 +31,48 @@ extension View {
...
+  
+  func addAccount(
+    keyringStore: KeyringStore,
+    networkStore: NetworkStore,
+    accountNetwork: BraveWallet.NetworkInfo?,
+    isShowingConfirmation: Binding<Bool>,
+    isShowingAddAccount: Binding<Bool>,
+    onConfirmAddAccount: @escaping () -> Void,
+    onCancelAddAccount: @escaping () -> Void,
+    onAddAccountDismissed: @escaping () -> Void
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Extensions/ViewExtensions.swift]: I think these could be optional so we don't have `onCancelAddAccount: {}` 🙂

**Review by StephenHeaps — COMMENTED** [review]
One small bug when cancelling add account request via `Add Account` modal:

https://github.com/brave/brave-ios/assets/5314553/0730e9ff-e3ef-401e-93e9-ed90dd78dc9b

This might make the `onCancelAddAccount: {}` comment irrelevant if we use that closure to clean buy/send/swap destination.

File: Sources/BraveWallet/Extensions/KeyringServiceExtensions.swift (hunk 2 above)
Comment (StephenHeaps) [reply Sources/BraveWallet/Extensions/KeyringServiceExtensions.swift]: After debugging bug when cancelling `Add Account View` modal, we need to update this to check for `accountInfos` being populated not just `isKeyringCreated`. Possible to have `isKeyringCreated` as true but 0 `accountInfos` here.

**Review by StephenHeaps — APPROVED** [review]
