### PR TITLE
Fix #456: Popup windows now work properly in private mode.

### LINKED ISSUE #456: Qwant, Startpage links and popups do not work in private mode
We should handle window.open when in private mode

Enhancement for #446 & #455:

**What**
In private mode the WKProcessPool of the WKWebViewConfiguration is overridden to avoid passing of cookies and other data between WKWebViews. This behaviour when combined with a popup ie window.open results in a crash

**Why**
When a window.open is called the parent WKWebView calls the delegate method: 

```
optional public func webView(_ webView: WKWebView, createWebViewWith configuration: WKWebViewConfiguration, for navigationAction: WKNavigationAction, windowFeatures: WKWindowFeatures) -> WKWebView?
``` 

in `WKUIDelegate`. It provides a configuration for the new window. When in private mode, this configuration is altered resulting in corruption of configuration and subsequent crash.

**Current-Fix**
For now all popups are blocked when in private mode. (BrowserViewController.swift)
See: https://github.com/brave/brave-ios/issues/456#issuecomment-474025905

**Enhancement**
Two possible solutions:

1. Keep blocking popups and instead show an alert telling the user of the reason.
2. Intercept popup call in private mode, create a new tab (not a popup) with the same request and return nil. (What other info needs to be used from the callback can be discussed later.)

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

### PR DESCRIPTION
**Pull request by jhreis**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2105,12 +2105,7 @@ private let schemesAllowedToBeOpenedAsPopups = ["http", "https", "javascript", "
 
 extension BrowserViewController: WKUIDelegate {
     func webView(_ webView: WKWebView, createWebViewWith configuration: WKWebViewConfiguration, for navigationAction: WKNavigationAction, windowFeatures: WKWindowFeatures) -> WKWebView? {
-        /* Fix for #446, when in private mode the WKProcessPool of the configuration is changed,
-         this leads to a crash for popups ie window.open where the configuration is created by parent wkwebview.
-         To handle this for now we are stopping popup when in private mode.
-         The fix is done in guard statement below.
-         */
-        guard let parentTab = tabManager[webView], !parentTab.isPrivate else { return nil }
+        guard let parentTab = tabManager[webView] else { return nil }
```
Comment (jhreis) [inline Client/Frontend/Browser/BrowserViewController.swift:2108]: Since https://github.com/brave/brave-ios/pull/1007/files#diff-75a5bde6af31e1ad1834bee74125b792L12 is removed, we can now allow popups in private mode so removed unnecessary check.

**Review by danishjafri88 — APPROVED** [review]

**Comment by jumde** [comment]
No security review required. 

Some test cases I had in mind:

- [ ] http://www.popuptest.com/ - Tests for automatic pop-ups
- [ ] Cookies are sandboxed: Cookies from parent are not accessible in pop-up if pop-up is in a different origin.
- [ ] onclick window.open works. 

Tests in progress.
