### PR TITLE
Fix #2153: Don't reset the user wallet button when balance updates

### LINKED ISSUE #2153: Verified wallet text flickers when panel is opened
### Description: 
Verified wallet text flickers when panel is opened

### Steps to Reproduce 
  1. Install 1.15
  2. Enable rewards and connect wallet using Uphold (not KYC)
  3. Open panel, `Your wallet` text flickers once before the hyperlink gets active

**Actual result:** 
uphold

**Expected result:**
No flickering text when panel is opened

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15

**Device details:** 
iPhone XR (iOS 13.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes issue #2153 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Wallet/WalletViewController.swift [hunk 1]
```diff
@@ -628,31 +628,33 @@ extension WalletViewController {
...
-             .pending:
-          self.walletView.headerView.setUserWalletStatus(.connectedNotVerified)
-        case .disconnectedVerified,
-             .disconnectedNotVerified:
-          self.walletView.headerView.setUserWalletStatus(.disconnected)
-        case .verified:
-          self.walletView.headerView.setUserWalletStatus(.verified)
-        @unknown default:
-          break
+    if userWallet == nil {
```
Comment (iccub) [inline BraveRewardsUI/Wallet/WalletViewController.swift:631]: Could replace it with `if userWallet != nil { return }` to remove one level of indentation, but I'm fine with it as it is

**Review by iccub — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
