### PR TITLE
Fix #3726, #3727 - Playlist not showing in Toast or Share Menu for some sites

### LINKED ISSUE #3726: Listennotes.com isn't recognized to save for playlist
### Description: 
Listennotes.com isn't recognized to save for playlist

### Steps to Reproduce 
  1. Install 1.26
  2. Visit listennotes.com
  3. No playlist toast shown. Doesn't allow to add on context menu or share menu

**Actual result:** 
Listennotes.com isn't recognized to save for playlist

**Expected result:**
Should be recognized as per #3648

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.26

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Some sites are using `setAttribute` and others are setting the `src` property directly.
- This code hooks both so that playlist works properly on all sites.
- This was a regression due to the performance fix that removed mutation observers. 
- We will have no performance impact with this code, but we'll have support for more sites :)

This pull request fixes #3726, #3727

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/UserContent/UserScripts/Playlist.js [hunk 1]
```diff
@@ -261,8 +261,10 @@ window.__firefox__.includeOnce("$<Playlist>", function() {
                     return this.getAttribute('src')
                 },
                 set: function(value) {
+                    // Typically we'd call the original setter.
+                    // But since the property represents an attribute, this is okay.
                     this.setAttribute('src', value);
-                    $<notifyNode>(this);
+                    //$<notifyNode>(this); // Handled by `setAudioAttribute`
```
Comment (iccub) [inline Client/Frontend/UserContent/UserScripts/Playlist.js]: Should not this say handled by `setVideoAttribute` not `audio`?

File: Client/Frontend/UserContent/UserScripts/Playlist.js [hunk 2]
```diff
@@ -273,10 +275,76 @@ window.__firefox__.includeOnce("$<Playlist>", function() {
...
+            HTMLAudioElement.prototype.setAttribute = function(key, value) {
+                setAudioAttribute.call(this, key, value);
+                if (key.toLowerCase() == 'src') {
+                    $<notifyNode>(this);
+                }
+            }
+            
+            // FOR DEBUGGING ONLY!
+            
+            /*var oldAudio = Audio;
```
Comment (iccub) [inline Client/Frontend/UserContent/UserScripts/Playlist.js]: Do we want to expose it to users? Afaik we do not run this script through webpack to remove such comments

**Review by iccub — APPROVED** [review]
