### PR TITLE
Fix #5816: Fix some tokens not displaying price history in asset details 

### LINKED ISSUE #5816: Wallet bug: Cannot see price history (chart) for some tokens on Mainnet (possibly other networks)
Simulator Screen Shot - iPhone Xʀ - 2022-08-09 at 09 50 46

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Return correct `assetRatioId` 

This pull request fixes #5816

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:
on mainnet, 1nch, aave, etc don't have price history.

## Screenshots:

simulator_screenshot_872F21E4-A7C5-415A-A6DF-9F0F3674E0D2 | simulator_screenshot_AA68E442-D83A-4F18-91DB-31673A405BD0
--|--

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Extensions/BraveWalletExtensions.swift [hunk 1]
```diff
@@ -196,8 +196,19 @@ extension BraveWallet.NetworkInfo {
...
 
 extension BraveWallet.BlockchainToken {
-  /// The id to fetch price and price history. Use `coingeckoId` when it's not empty, otherwise use `symbol`
   var assetRatioId: String {
-    coingeckoId.isEmpty ? symbol : coingeckoId
+    if !coingeckoId.isEmpty {
+      return coingeckoId
+    }
+    
+    if chainId != BraveWallet.MainnetChainId {
```
Comment (StephenHeaps) [inline BraveWallet/Extensions/BraveWalletExtensions.swift]: I think can remove below check and update this to include it? `if chainId != BraveWallet.MainnetChainId || contractAddress.isEmpty {`

File: BraveWallet/Extensions/BraveWalletExtensions.swift [hunk 2]
```diff
@@ -196,8 +196,19 @@ extension BraveWallet.NetworkInfo {
 }
 
 extension BraveWallet.BlockchainToken {
-  /// The id to fetch price and price history. Use `coingeckoId` when it's not empty, otherwise use `symbol`
```
Comment (StephenHeaps) [inline BraveWallet/Extensions/BraveWalletExtensions.swift:199]: Why remove the comment describing what this property is for?

**Review by iccub — APPROVED** [review]

**Review by StephenHeaps — APPROVED** [review]
