### PR TITLE
Fix 5403: Close wallet panel when user goes to full screen wallet or full screen wallet settings from panel

### LINKED ISSUE #5403: Wallet panel account connection status is not updated after user remove all permissions from wallet settings
### Steps to Reproduce 
  1. connect your wallet to a dapp and grant permission to all your accounts in your wallet
  2. open wallet panel and click the `...` button on top right
  3. select `Settings` then select `Manage Site Connections`
  4. click `Remove all` to remove all permissions
  5. back to wallet panel 
  6. observe wallet panel still displaying account is connected
  7. if you dismiss the wallet panel and open it up again
  8. no account is connected (Correct)
  
**Actual result:** 
After all permissions are removed, wallet panel still displaying account connected

**Expected result:**
should have no account connected

### PR DESCRIPTION
**Pull request by nuo-xu**
Changing UX: Close wallet panel when user goes to full screen wallet or full screen wallet settings from panel

This pull request fixes #5403 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Please refer to the issue.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift [hunk 1]
```diff
@@ -112,6 +112,12 @@ extension BrowserViewController: BraveWalletDelegate {
       )
     }
   }
+  
+  func onFullScreenWallet(_ viewController: UIViewController) {
+    self.dismiss(animated: true) { [weak self] in
+      self?.present(viewController, animated: true)
+    }
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift]: Why can't this call just happen in the call above?

File: BraveWallet/WalletHostingViewController.swift [hunk 2]
```diff
@@ -15,6 +15,8 @@ public protocol BraveWalletDelegate: AnyObject {
   ///
   /// This will be called after the wallet UI is dismissed
   func openWalletURL(_ url: URL)
+  /// Will dismiss wallet panel and open full screen wallet or full screen wallet settings
+  func onFullScreenWallet(_ viewController: UIViewController)
```
Comment (kylehickinson) [inline BraveWallet/WalletHostingViewController.swift]: Naming needs work, you're saying to full screen wallet but you pass an arbitrary `UIViewController`. Overall this is confusing.

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/WalletHostingViewController.swift (hunk 2 above)
Comment (kylehickinson) [reply BraveWallet/WalletHostingViewController.swift]: Also please avoid prefixing methods with "on"

File: BraveWallet/WalletHostingViewController.swift [hunk 3]
```diff
@@ -15,6 +15,8 @@ public protocol BraveWalletDelegate: AnyObject {
   ///
   /// This will be called after the wallet UI is dismissed
   func openWalletURL(_ url: URL)
+  /// Present Wallet with or without dismiss the Wallet Panel depends on the value of the `presentWalletWithContext`
+  func walletPanel(_ presentWalletWithContext: PresentingContext)
```
Comment (kylehickinson) [inline BraveWallet/WalletHostingViewController.swift]: Pass in the wallet panel so that you don't have to use `presentedViewController` down below:

```swift
func walletPanel(
  _ panel: WalletPanelHostingController, 
  presentWalletWithContext: PresentingContext
)
```

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by StephenHeaps — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
