### PR TITLE
Fix: #1655 - Feature/device check updates

### LINKED ISSUE #1655: Implement DeviceCheck
@anthonypkeane commented on [Fri Apr 12 2019](https://github.com/brave/brave-ios/issues/1052)

### Description: 
Implement DeviceCheck for upcoming Brave Rewards on iOS
https://developer.apple.com/documentation/devicecheck

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

Fixes: #1655
Fixes PaymentId and makes sure the code works with the server updates.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/DeviceCheck/DeviceCheck.swift [hunk 1]
```diff
@@ -155,9 +155,11 @@ class DeviceCheckClient {
       
       let parameters = [
         "publicKeyHash": publicKey,
-        "paymentID": paymentId
+        "paymentId": paymentId
       ]
       
+      print(parameters)
```
Comment (kylehickinson) [inline Client/DeviceCheck/DeviceCheck.swift]: Needed?

File: Client/DeviceCheck/DeviceCheck.swift [hunk 2]
```diff
@@ -336,10 +338,12 @@ private extension DeviceCheckClient {
     switch endpoint {
     case .register(let parameters):
       request.httpBody = try JSONEncoder().encode(parameters)
+      print(String(data: request.httpBody!, encoding: .utf8)!)
```
Comment (kylehickinson) [inline Client/DeviceCheck/DeviceCheck.swift]: Needed?

**Review by kylehickinson — APPROVED** [review]

**Review by iccub — APPROVED** [review]

**Comment by iccub** [comment]
Please squash and merge, and add `Ref # device check ticket number` in the commit
