### PR TITLE
Fix #3593 - Fix playlist swipe conflicting with Button touch

### LINKED ISSUE #3593: Swipe to dismiss sometimes adds the video to playlist
### Description: 
Found while testing #3574, swipe down on the toast message sometimes adds the video to playlist. This happens more on iPad than on iPhone's

### Steps to Reproduce 
  1. Install 1.25(21.4.27.17)
  2. Load a video and wait for the add to playlist toast to show up
  3. Swipe down to dismiss, the video may get added instead of dismissing the toast

**Actual result:** 
Hard to record try it out yourselves

**Expected result:**
Swipe left/right so as to not accidentally add the video to playlist

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.27.17)

**Device details:** 
Easy on iPad hard on iPhone's

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix playlist swipe conflicting with Button touch via PanGesture and distance calculations.

This pull request fixes #3593

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/PlaylistToast.swift [hunk 1]
```diff
@@ -117,8 +117,8 @@ class PlaylistToast: Toast {
                 $0.titleLabel?.lineBreakMode = .byClipping
                 $0.titleLabel?.adjustsFontSizeToFitWidth = true
                 $0.titleLabel?.minimumScaleFactor = 0.1
-                
-                $0.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(buttonPressed)))
+                $0.addTarget(self, action: #selector(buttonPressed), for: .touchUpInside)
+                //$0.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(buttonPressed)))
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/PlaylistToast.swift]: nit : Delete the comment

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — CHANGES_REQUESTED** [review]
What about setting `cancelsTouchesInView` to false in the gesture recognizer like @kylehickinson recommended?
Would that help

**Comment by Brandon-T** [comment]
> What about setting `cancelsTouchesInView` to false in the gesture recognizer like @kylehickinson recommended?
> Would that help

Not needed afaict. I switched out the gesture recognizer for a button touch event and the pan gesture doesn't trigger until a certain distance is reached.

**Review by iccub — APPROVED** [review]
