### PR TITLE
Fix #5966: Edit visible token lists is not correct after a new solana account has been created and selected.

### LINKED ISSUE #5966: Solana tokens are not listed immediately after creating account
### Description: 
Solana tokens are not listed immediately after creating account

### Steps to Reproduce 
  1. Clean profile and create wallet
  2. Search for AAPL token, lists the token
  3. Select to show in portfolio
  4. Token is listed in Eth Portfolio
  5. Select Solana from network picker, Create new Solana account
  6. Search for ABNB token, doesn't list continues to show ETH tokens
  7. Change network to ETH and change back to Solana
  8. Search for ABNB, now token is listed

**Actual result:** 
Solana tokens are not listed immediately after creating account

**Expected result:**
Should list the tokens immediately without having to switch networks

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.43 (22.9.2.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps @nuo-xu

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Correctly set network after a new keyring is created.

This pull request fixes #5966 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/KeyringStore.swift [hunk 1]
```diff
@@ -377,21 +377,8 @@ extension KeyringStore: BraveWalletKeyringServiceObserver {
...
-        coin = .sol
-      case BraveWallet.FilecoinKeyringId:
-        coin = .fil
-      default:
-        break
-      }
-      
       let newKeyring = await keyringService.keyringInfo(keyringId)
       if let newAccount = newKeyring.accountInfos.first {
-        walletService.setSelectedCoin(coin)
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/KeyringStore.swift:394]: coin type will be set to the new created keyring's coin type, so we dont need to set it for the WalletService.

**Review by iccub — APPROVED** [review]

File: Sources/BraveWallet/Crypto/Stores/KeyringStore.swift [hunk 2]
```diff
@@ -366,7 +366,7 @@ extension KeyringStore: BraveWalletKeyringServiceObserver {
     Task { @MainActor in
       let previouslySelectedCoin = await walletService.selectedCoin()
       walletService.setSelectedCoin(coinType)
-      if previouslySelectedCoin != coinType {
+      if previouslySelectedCoin != coinType || selectedAccount.coin != coinType {
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/KeyringStore.swift:369]: `selectedAccount.coin != coinType` will take care of the case that a new keyring has been created.

**Review by StephenHeaps — APPROVED** [review]
