### PR TITLE
Fix #2255: Correct layout for claiming grants NTP banner.

### LINKED ISSUE #2255: "Claim my Reward" modal/overlay covering the entire screen and missing button
### Description: 

The `Claim my reward` modal/overlay for ad grants doesn't match the current specification. The current version is missing the `Claim my reward` button and covers the entire screen. Because there's no button available, the only thing the user can do is press the `X` button to close the modal/overlay.

### Steps to Reproduce

  1. install `1.14.3 (20.1.28.18)` via the `Dev` TF channel
  2. skip the `Onboarding` process and go into `Settings` --> `View Rewards Debug Menu`
  3. select `Staging` and restart the browser (should close automatically)
  4. once the browser is relaunched, enable rewards via the panel (`Join Rewards`)
  5. go into `Settings` --> `View Rewards Debug Menu`
  6. restore a wallet that has an ad grant available (use the shared GDoc) and restart the browser
  7. open a new NTP and you'll get the `Brave Reward` modal that displays your ad grant

**Actual result:** 

IMG_0006 (1)

**Expected result:**

As per the specification, the modal/overlay should look as follows:

Screen Shot 2020-01-28 at 9 09 11 PM

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.14.3 (20.1.28.18)` (using the `Dev` TF channel)

**Device details:** 

* `iPhone 11` running `iOS 13.3` - **Reproduced**
* `iPad 3rd Gen` running `iOS 13.3` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @brave/legacy_qa @anthonypkeane @iccub @jhreis @jamesmudgett

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes issue #2255 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

Zrzut ekranu 2020-01-29 o 09 32 52

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/NTP/ClaimRewardsNTPNotificationViewController.swift [hunk 1]
```diff
@@ -55,29 +55,30 @@ class ClaimRewardsNTPNotificationViewController: TranslucentBottomSheet {
...
             }
+            $0.bottom.equalToSuperview()
+        }
+    }
+    
+    private func updateMainViewConstraints() {
+        guard let mainView = mainView else { return }
+        
+        mainView.snp.remakeConstraints {
+            $0.leading.trailing.bottom.top.equalTo(view.safeAreaLayoutGuide).inset(16)
```
Comment (jhreis) [inline Client/Frontend/NTP/ClaimRewardsNTPNotificationViewController.swift]:
```suggestion
            $0.edges.equalTo(view.safeAreaLayoutGuide).inset(16)
```

**Review by jhreis — CHANGES_REQUESTED** [review]

**Review by jhreis — APPROVED** [review]
