### PR TITLE
Fix #7697: Connecting second Solana account does not show connect request

### LINKED ISSUE #7697: Cannot connect second Solana account to DApp after one account previously connected
### Description: 

Regressed with `getAllowedAccounts` refactor changes in [v1.53 core bump](https://github.com/brave/brave-ios/pull/7554)

### Steps to Reproduce 
1. Have 2+ Solana accounts.
2. Open https://pwgoom.csb.app/ and connect the selected Solana account.
3. Verify the selected account address is displayed on the test DApp site.
4. Open the Wallet Panel and change to the a different Solana account
5. Tap `Connect` on the test Dapp site
6. Observe no connection request received. Open/close panel & no connection request shown.
7. Workaround: User can grant permission via `Disconnected` button on the Wallet Panel.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/4a912749-5db6-4581-9b68-38774e27837c

### Expected result:

Dapp connection panel is shown for the newly selected Solana account.

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.53+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- If you previously connected 1 Solana account to a Dapp, then changed accounts to another account that was never connected, tapping `Connect` / `Connect Wallet` will not create the dapp request.
- The bug was in refactor to `getAllowedAccounts` in v1.53 core bump.
    - `getAllowedAccounts` was not factoring in the `accounts` param when returning permitted accounts.
    - `if !allowedAccounts.isEmpty {` check was incorrectly returning empty array when there were allowed accounts.

This pull request fixes #7697

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Have 2+ Solana accounts, disconnect all from the https://pwgoom.csb.app/ test DApp site.
2. Open https://pwgoom.csb.app/ test DApp and connect the selected Solana account.
3. Verify the selected account address is displayed on the test DApp site.
4. Open the Wallet Panel and change to the a different Solana account
5. Verify connect request is now shown automatically for the new Solana account

## Screenshots:

https://github.com/brave/brave-ios/assets/5314553/833d6a89-ecc7-4105-8dae-e7f434a961ce

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift [hunk 1]
```diff
@@ -299,12 +290,19 @@ extension Tab: BraveWalletProviderDelegate {
...
       return []
     }
-    // keyring locked status is checked in `EthereumProviderImpl::GetAllowedAccounts`
-    return permissions
+    // Filter `accounts` requested to return only those permitted
+    return accounts.filter { address in
+      permittedAccountAddresses.contains(where: { permittedAddress in
+        permittedAddress.caseInsensitiveCompare(address) == .orderedSame
+      })
+    }
```
Comment (nuo-xu) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift:305]: not sure why we need filter from `accounts`? isn't this will be the same with `permittedAccountAddresses`?

Comment (StephenHeaps) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift:305]: Because core expects us to only return the permitted accounts for the given accounts array they request. For example, consider scenario where a user has 2 accounts (`0xA`, `0xB`) but only permits `0xA` to connect. If they then switch to the non-permitted account `0xB` and try to connect, core will call this `getAllowedAccounts()` function with `accounts: ["0xB"]` but we'd incorrectly return `["0xA"]` is connected so a permission request would not be created.

[Desktop implementation](https://github.com/brave/brave-core/blob/db3af86e921baa371556e158292bc36a74aea794/components/permissions/contexts/brave_wallet_permission_context.cc#L233-L249) of this method.

**Review by nuo-xu — APPROVED** [review]
