### PR TITLE
Fix # 5081: Add error handling in edit gas fee, priority fee and nonce

### LINKED ISSUE #5081: Add error handling on Edit Gas Fee / Priority Fee / Nonce Screen
We are missing error handling for these three screen. 
Copies will be provided.

### PR DESCRIPTION
**Pull request by nuo-xu**
This pull request fixes #5081 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Transaction Confirmations/EditGasFeeView.swift [hunk 1]
```diff
@@ -23,6 +23,7 @@ struct EditGasFeeView: View {
   
   @State private var perGasPrice: String = ""
   @State private var gasLimit: String = ""
+  @State private var showError: Bool = false
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/Transaction Confirmations/EditGasFeeView.swift]: nitpick: I tend to prefer using `is` prefix for boolean flags, especially with SwiftUI state; ex `isShowingAlert`. I thought it was in the [Ray Wenderlich style guide](https://github.com/raywenderlich/swift-style-guide#naming) but I don't see it. thoughts?

File: BraveWallet/WalletStrings.swift [hunk 2]
```diff
@@ -1870,5 +1870,19 @@ extension Strings {
       value: "Enter custom nonce value",
       comment: "The placeholder for custom nonce textfield."
     )
+    public static let editTransactionError = NSLocalizedString(
+      "wallet.editTransactionError",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Please check your inputs and try again.",
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift:1877]: Do we need copy from Ryan or is this the official copy?

Comment (nuo-xu) [reply BraveWallet/WalletStrings.swift:1877]: those copies are approved by Ryan

File: BraveWallet/Crypto/Transaction Confirmations/EditGasFeeView.swift (hunk 1 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Transaction Confirmations/EditGasFeeView.swift]: yep. i will update

**Review by StephenHeaps — APPROVED** [review]
