### PR TITLE
Fix #7785: User assets are not migrated if user restore wallet from lock screen

### LINKED ISSUE #7785: No visible assets after restoring wallet without resetting first
### Description: 

After restoring a wallet without resetting the existing wallet first, there are no visible assets displayed in Portfolio.

### Steps to Reproduce 
  1. Reset your wallet if you haven't already (not 100% sure if required, any existing wallet might suffice)
  2. Create a new wallet
  3. After wallet onboarding/setup and Portfolio is shown, lock the wallet and tap `Restore` on the unlock wallet screen
  4. Restore your wallet
  5. Observe no visible assets selected

### Actual result: 

No visible assets are shown / selected

https://github.com/brave/brave-ios/assets/5314553/dec46f6d-2123-4cbf-a836-345a220bed1a

### Expected result:

Default visible assets are shown & selected

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Restore a wallet should be considered as a fresh wallet restore meaning all user assets that we stored locally need to be wiped and new user assets migration should be preformed. 

This pull request fixes #7785

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Please refer to the issue 

## Screenshot:
https://github.com/brave/brave-ios/assets/1187676/2b3ba605-8d50-4986-beb6-1969c1b63fbf

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/CryptoStore.swift [hunk 1]
```diff
@@ -561,11 +562,18 @@ extension CryptoStore: BraveWalletKeyringServiceObserver {
...
   public func keyringRestored(_ keyringId: BraveWallet.KeyringId) {
-    // if a keyring is restored, we want to reset user assets local storage
-    // and migrate with for new keyring
+    // This observer method will only get called when user restore a wallet
+    // from the lock screen
+    // We will need to
+    // 1. reset wallet user asset migration flag
+    // 2. wipe user assets local storage
+    // 3. migrate user assets with new keyring
+    guard !isUpdatingUserAssets else { return }
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Stores/CryptoStore.swift:571]: What is this flag for? It's always false, maybe not needed?

**Review by StephenHeaps — APPROVED** [review]

**Review by StephenHeaps — APPROVED** [review]
