### PR TITLE
Fix #8484: Portrait Orientation Locking on Phone is not working

### LINKED ISSUE #6275: Sync chain flow via tab sync displayed in landscape [iOS 16]
### Description: 
In landscape view, user is not forced to portrait when sync chain modals are displayed via tab sync flow. Instead, sync chain modals are displayed in landscape which results in some elements not shown correctly as we display these flow in portrait only.

We should fix this flow for landscape on iOS 16 or force portrait mode to avoid potential usability issues

### Steps to Reproduce 
  1. Fresh profile
  2. Open tab tray, select `tabs from other devices` segmented tab
  3. Rotate device to landscape
  4. Tap on `Start a sync chain`
  5. Sync modal will display in landscape
  6. Select Select the `Tablet or Phone` option
  7. Observe
  8. Delete sync chain
  9. Repeat steps.. this time choose `I have a sync code`
  10. Notice the scan modal in landscape is not displayed correctly

**Actual result:** 
Sync chain modals are not displayed in portrait view.
Example | Example
-|-
IMG_3981 | IMG_3982

**Expected result:**
We should fix this flow in landscape or force portrait to avoid potential usability issues

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.45.x

**Device details:** 
iPhone 12 Pro, iOS 16.x

### LINKED ISSUE #8484: Portrait Orientation Locking on Phone is not working
### Description: 

The orientation lock is not working properly for sync screens related with API change in iOS16.

Also related with https://github.com/brave/brave-ios/issues/6275

### Steps to Reproduce 

1. Fresh profile
2. Open tab tray, select tabs from other devices segmented tab
3. Rotate device to landscape
4. Tap on Start a sync chain
5. Sync modal will display in landscape
6. Select Select the Tablet or Phone option
7. Observe
8. Delete sync chain
9. Repeat steps.. this time choose I have a sync code
10. Notice the scan modal in landscape is not displayed correctly

### Actual result: 

The screen in landscape is not displayed **correctly**

### Expected result:
The portrait display lock should work properly

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone iOS 16- 17

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

Additionally same flow should be tested for Settings -> Sync screens

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

Fixing locking orientation logic for iOS16 and beyond

This pull request fixes #8484
This pull request fixes #6275

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Try Sync Screens and states triggered from Settings and Tab Tray

Test Wallet Opening 

## Screenshots:

https://github.com/brave/brave-ios/assets/6643505/a322e554-7b2b-434a-8129-9d6544043339

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by StephenHeaps — APPROVED** [review]

File: Sources/Shared/DeviceOrientation.swift [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+    
+  public var isLandscape: Bool {
+    if #available(iOS 16.0, *) {
+      return windowScene?.interfaceOrientation.isLandscape ?? false
+    }
+    
+    return UIDevice.current.orientation.isLandscape
+  }
+    
+  public var isPortrait: Bool {
```
Comment (kylehickinson) [inline Sources/Shared/DeviceOrientation.swift]: These don't seem to be used anywhere outside of this class and will technically be invalid on iPad so probably shouldn't be public

File: Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift [hunk 2]
```diff
@@ -793,6 +793,19 @@ class TabTrayController: AuthenticationController {
   }
 }
 
+// MARK: InterfaceOrientation
+
+extension TabTrayController {
+  
+  override var preferredInterfaceOrientationForPresentation: UIInterfaceOrientation {
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift]: Pr works fine without this one afaict.

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift (hunk 2 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift]: Let me test and will remove after that.

File: Sources/Shared/DeviceOrientation.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/Shared/DeviceOrientation.swift]: Access modifiers are changed at https://github.com/brave/brave-ios/pull/8485/commits/8ac94bc1e30e13dfb6d42a77619106ce97830561

File: Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift (hunk 2 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/Tabs/TabTray/TabTrayController.swift]: Fixed / Removed at https://github.com/brave/brave-ios/pull/8485/commits/8ac94bc1e30e13dfb6d42a77619106ce97830561

**Review by Brandon-T — APPROVED** [review]

File: Sources/Shared/DeviceOrientation.swift [hunk 3]
```diff
@@ -0,0 +1,62 @@
+// Copyright 2023 The Brave Authors. All rights reserved.
```
Comment (kylehickinson) [inline Sources/Shared/DeviceOrientation.swift:1]: Is it possible to move this to `BraveShared`? We shouldn't be adding anything to Shared anymore

Comment (soner-yuksel) [reply Sources/Shared/DeviceOrientation.swift:1]: oh sorry I just merged this before your comment, let me do this in a different PR

Comment (soner-yuksel) [reply Sources/Shared/DeviceOrientation.swift:1]: PR created https://github.com/brave/brave-ios/pull/8499
