### PR TITLE
Fix #1983: Always add constraints when showing reader mode bar.

### LINKED ISSUE #1983: Navigating to address bar from reader mode hides it
### Description: 
Probably a regression caused by one of my layout constraints fixes

### Steps to Reproduce 
  1. Tap on reader mode
  2. Tap on address bar

**Actual result:** 
Zrzut ekranu 2019-11-19 o 17 32 45

**Expected result:**
The address bar should be present

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
Regression caused by https://github.com/brave/brave-ios/pull/1736

This pull request fixes issue #1983 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Tap on reader mode, then on address bar again. Verify the address bar is showing

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -2687,6 +2682,12 @@ extension BrowserViewController {
             readerModeBar.delegate = self
             view.insertSubview(readerModeBar, belowSubview: header)
             self.readerModeBar = readerModeBar
+            
+            readerModeBar.snp.makeConstraints { make in
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift:2686]: Note: It's not actually in `viewDidLayoutSubviews` Github is showing it weird..
