### PR TITLE
Fix: #4493 Hardcode swap assets in Ropsten

### LINKED ISSUE #4492: 試試
## User Experience 

1. 
2. 
3. 

### Additional information

### LINKED ISSUE #4493: Hardcode Assets for Swap only in Ropsten Network
### Description: 
If the network is Ropsten, there will be only three assets to choose from `[.eth, .dai, .usdc]` instead of all tokens from `TokenRegistry`. 
Furthermore, the `contractAddress` for these three assets if user wants to swap are:
.eth: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
.dai:  "0xad6d458402f60fd3bd25163575031acdce07538d"
.usdc: "0x07865c6e87b9f70255377e024ace6630c1eaa37"

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
There are now harcoded assets in Ropsten for swapping. (ETH still has its own hardcoded swapping address)
If user wants to swap assets in Ropsten, they will choose from ETH, DAI and USDC.
Fixed buyAmount is wrong if sell assets has less than 18 decimals.
Fixed showing wrong error message after select a new sell asset that has no balance.
Fixed showing wrong state after select amount of sell assets that has no balance.
Fixed buy amount label has wrong rounded value.

This pull request fixes #4493 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift [hunk 1]
```diff
@@ -430,33 +451,45 @@ public class SwapTokenStore: ObservableObject {
...
+      if let toToken = selectedToToken {
+        rpcController.balance(for: toToken, in: accountInfo) { [weak self] balance in
+          self?.selectedToTokenBalance = BDouble(balance ?? 0)
+          completion?()
+        }
+      } else {
+        if chainId == BraveWallet.MainnetChainId {
+          selectedToToken = allTokens.first(where: { $0.symbol == "BAT" })
+        } else if chainId == BraveWallet.RopstenChainId {
+          selectedToToken = allTokens.first(where: { $0.symbol == "DAI" })
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SwapTokenStore.swift]: Do a case insensitive compare or uppercase `$0.symbol` to ensure a normalized compare

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift [hunk 2]
```diff
@@ -430,33 +451,45 @@ public class SwapTokenStore: ObservableObject {
...
+        }
+        completion?()
+      }
+    }
+    
+    tokenRegistry.allTokens { [weak self] tokens in
+      guard let self = self else { return }
+      
+      self.rpcController.chainId { chainId in
+        self.chainId = chainId
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SwapTokenStore.swift:482]: If a user changes their network do we need an updated `chainId` elsewhere? If so this class should become an roc controller observer and set this value when chainId change event is hit

File: BraveWallet/Extensions/BraveWalletSwiftUIExtensions.swift [hunk 3]
```diff
@@ -34,9 +34,31 @@ extension BraveWallet.ERCToken: Identifiable {
   public var isETH: Bool {
     contractAddress.isEmpty && symbol.lowercased() == "eth"
   }
+  
+  public func swapAddress(in chainId: String) -> String {
+    if chainId == BraveWallet.RopstenChainId {
+      switch symbol {
```
Comment (kylehickinson) [inline BraveWallet/Extensions/BraveWalletSwiftUIExtensions.swift]: uppercase this before compare

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift (hunk 2 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/SwapTokenStore.swift:482]: class is already a `BraveWalletEthJsonRpcControllerObserver` to observe the chain changed event. This event will eventually call `prepare` function which will update the `chainId` there.

**Review by kylehickinson — APPROVED** [review]
