### PR TITLE
Fix #7961: Tokens on Testnets still shown in Edit Visible Assets Screen when testnets are filtered out

### LINKED ISSUE #7961: Test network tokens are still shown in edit visible tokens when filtering to a specific network
### Description: 
Test network tokens are still shown in edit visible tokens when filtering to a specific network

### Steps to Reproduce 
  1. Enable show test networks in settings
  2. Enable all networks to show tokens in filter settings
  3. Disable show test networks in settings
  4. Filter edit visible tokens to a particular network
  5. Continues to show test network tokens with filtered netwrok

### Actual result: 
Test network tokens are still shown in edit visible tokens when filtering to a specific network

### Expected result:
Should only show the tokens from selected network

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes

This pull request fixes #7961

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Please refer to the issue

## Screenshots:

https://github.com/brave/brave-ios/assets/1187676/d719a07b-0528-40b6-8d36-785f9cd5519b

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Tests/BraveWalletTests/SelectAccountTokenStoreTests.swift [hunk 1]
```diff
@@ -6,10 +6,18 @@
...
 
 @MainActor class SelectAccountTokenStoreTests: XCTestCase {
   
+  override func setUp() {
+    Preferences.Wallet.showTestNetworks.reset()
+  }
+  override func tearDown() {
+    Preferences.Wallet.showTestNetworks.reset()
+  }
+
```
Comment (StephenHeaps) [inline Tests/BraveWalletTests/SelectAccountTokenStoreTests.swift]: For all of these test classes, I think it's better to just enable this flag in `setUp()` (so all tests in each `XCTestCase` run with test networks enabled) and call `reset()` in `tearDown()`; then we can remove the assignments in `setupStore()`.

Comment (nuo-xu) [reply Tests/BraveWalletTests/SelectAccountTokenStoreTests.swift]: updated in [33d9ab4](https://github.com/brave/brave-ios/pull/7972/commits/33d9ab4fc7e67803402e2e3f6cebe4a1f45b5a0b)

**Review by StephenHeaps — APPROVED** [review]
