### PR TITLE
Fix #6243: Adding shared playlist multiple times might not succeed 

### LINKED ISSUE #6243: [Follow up to 6224] Adding shared playlist multiple times might not succeed
### Description: 

Adding and deleting shared playlist over and over again  will cause failure while adding the shared playlist. It will fail adding same playlist folder after deleting. This will cause an assertion failure in debug builds.

### Steps to Reproduce 
  1. Add shared playlist from `playlist.brave.com/bsa-sample`
  2. Delete the folder after loading
  3. Repeat until there is an error

**Actual result:** 
Adding fill fail.

**Expected result:**
It should add with no problem.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
`1.44`

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
Changing merge policy while saving folder and item after re-ordering

## Summary of Changes

This pull request fixes #6243

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Data/models/PlaylistFolder.swift [hunk 1]
```diff
@@ -118,13 +118,23 @@ final public class PlaylistFolder: NSManagedObject, CRUD, Identifiable {
...
       PlaylistFolder.saveContext(context)
+      context.mergePolicy = policy
       
       DispatchQueue.main.async {
         completion?(folderId)
       }
     }
   }
+  
+  public static func clearMemoryContext() {
```
Comment (kylehickinson) [inline Sources/Data/models/PlaylistFolder.swift]: This doesn't seem to be called anywhere?

Comment (soner-yuksel) [reply Sources/Data/models/PlaylistFolder.swift]: Yes forgot to remove this function, this is not necessary. Fixed https://github.com/brave/brave-ios/pull/6244/commits/cab6f78d0ea438c07ef2d08ea0463dd57dade097

**Review by Brandon-T — APPROVED** [review]
