### PR TITLE
Fix #5072, #5071, #5068, #5065, #5069: CarPlay folders not updating correctly when phone is used at the same time.

### LINKED ISSUE #5065: Folder name changes back to original name when app is removed from memory and relaunched
### Description: 
Folder name changes back to original name when app is removed from memory and relaunched

### Steps to Reproduce 
  1. Install 1.36(22.3.3.9)
  2. Create a playlist folder and give it a name ex `Fav Music`
  3. Add a playlist item to the above created folder (Optional step)
  4. Rename the folder to some other name ex `Rock Music`
  5. Close playlist and remove app from memory
  6. Relaunch browser and check the name of the folder its reverted back to the original name (in this case `Fav Music`)

**Actual result:** 

https://user-images.githubusercontent.com/17010094/157195817-88c4aefc-7e3b-4102-9966-3ad5bcd42fed.MP4

**Expected result:**
Should retain the changes

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.3.3.9)

**Device details:** 
iOS XR (iOS 15.3.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

### LINKED ISSUE #5068: Wrong folders playlist items are shown when playing an item from a different folder
### Description: 
Wrong folders playlist items are shown when playing an item from a different folder

### Steps to Reproduce 
  1. Add 2 playlist item in folder A
  2. Add 1 playlist item in folder B
  3. Connect to CarPlay
  4. Open folder A on device and start playing an item 
  5. Use CarPlay to navigate to Folder B and play the playlist item 
  6. On mobile device, only playlist folder name updates to B but still lists playlist items from folder A

**Actual result:** 
Wrong folders playlist items are shown when playing an item from a different folder

**Expected result:**
Should update the playlist items when folder is changed. Note only happens when connected to CarPlay

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.3.3.9)

**Device details:** 
iPhone XR (iOS 15.3.1) + CarPlay

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

### LINKED ISSUE #5069: Album art on lock screen changes if user navigates to different folders on CarPlay
### Description: 
Album art on lock screen changes if user navigates to different folders on CarPlay

### Steps to Reproduce 
  1. Create Playlist folders and add playlist items to it
  2. Connect device to CarPlay
  3. Play an item on CarPlay
  4. Check device lock screen, shows the current playing item and the album art on lock screen
  5. Change the folder view and open a different folder with playlist item
  6. Device lock screen updates the album art for current playing item. Shows album art of the playlist item in the new folder

**Actual result:** 
Album art on lock screen changes if user navigates to different folders on CarPlay

**Expected result:**
Do not change album art just because user is navigating to a different playlist folder

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36(22.3.3.9)

**Device details:** 
iPhone XR (iOS 15.3.1) + CarPlay

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @Brandon-T

### LINKED ISSUE #5071: Current playing equalizer graphic is shown on index of the playlist item irrespective of the folder being opened
### Description: 
Current playing equalizer graphic is shown on index of the current playing item 

### Steps to Reproduce 
  1. Add 3 folder A, B, C
  2. Add 3 playlist items in Folder A, C
  3. Add 2 playlist item in folder B
  4. Connect device to CarPlay
  5. Go to folder A and play the file from CarPlay, shows equalizer graphic to indicate its currently playing 
  6. While playback, navigate back to folder C
  7. First item on folder C also shows the currently playing equalizer graphic
  8. Navigate back to Folder B, same thing happens
  9. Go back to Folder A and play the 3rd item in that folder
  10. Go back to folder C, shows the 3rd item is playing which is wrong
  11. Go back to folder B, neither of the playlist items have the currently playing graphics shown

**Actual result:** 
Current playing equalizer graphic is shown on index of the playlist item irrespective of the folder being opened

**Expected result:**
Do not show the currently playing graphics on every item in a folder but just show it for the actual playback file

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.3.3.9)

**Device details:** 
iPhone XR (iOS 15.3.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

### LINKED ISSUE #5072: No album art or track name is shown on CarPlay/Device when an item is moved into a different folder via context menu
### Description: 
No playlist details are shown on both lock screen and on CarPlay when an item is moved into a different folder via context menu

### Steps to Reproduce 
  1. Add playlist to a folder and play it
  2. Ensure its shown on both on CarPlay and Device
  3. Long press on the current playing item and select move and select a target folder
  4. Playback stops when the item is moved
  5. Click on play button on top right corner on CarPlay to resume play
  6. No album art or track name is shown on CarPlay 
  7. Check device lock screen, same no album art of track name is shown

**Actual result:** 

Device | CarPlay
-- | --
image | image

**Expected result:**
Should show track name and album art when playback resumes

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.3.3.9)

**Device details:** 
iPhone XR (iOS 15.3.1) + CarPlay

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix album art bugs on lockscreen and when changing between folders
- Fix folder name not saving properly when changing the name and killing the app
- Fixed playing indicator in CarPlay not updating correctly when playing from the phone
- Fixed folders on the phone not refreshing properly when playing an item in carplay

This pull request fixes #5072, #5071, #5068, #5065, #5069

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift [hunk 1]
```diff
@@ -14,6 +14,12 @@ import CoreData
 
 private let log = Logger.browserLogger
 
+private enum PlaylistCarPlayTemplateID: String {
+    case Folders
+    case ItemsList
+    case Settings
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift]: camel case?

File: Data/models/PlaylistFolder.swift [hunk 2]
```diff
@@ -83,6 +83,21 @@ final public class PlaylistFolder: NSManagedObject, CRUD, Identifiable {
         folder.delete()
     }
     
+    public static func updateFolder(folderID: NSManagedObjectID, _ update: @escaping (PlaylistFolder?, Error?) -> Void) {
```
Comment (kylehickinson) [inline Data/models/PlaylistFolder.swift]: nit but no fix needed in this PR: Use `Result<PlaylistFolder, Error>` in these situations instead of two optionals

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift]: If these are caps because you need to have the raw values themselves capitalized, use `case folders = "Folders"` instead

File: Data/models/PlaylistFolder.swift [hunk 3]
```diff
@@ -83,6 +83,21 @@ final public class PlaylistFolder: NSManagedObject, CRUD, Identifiable {
...
+        DataController.perform(context: .new(inMemory: false), save: true) { context in
+            do {
+                guard let folder = try context.existingObject(with: folderID) as? PlaylistFolder else {
+                    update(nil, "Invalid Folder")
```
Comment (kylehickinson) [inline Data/models/PlaylistFolder.swift]: Does this need to be localized?

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift [hunk 4]
```diff
@@ -343,6 +344,10 @@ class PlaylistListViewController: UIViewController {
             PlaylistManager.shared.fetchedObjects[safe: $0.row]
         })
         
+        if selectedItems.contains(where: { $0.pageSrc == PlaylistCarplayManager.shared.currentPlaylistItem?.pageSrc }) {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift:347]: Is it added because a playlist item should be stopped playing in car entirely when it is moved  to another folder in phone ?

File: Data/models/PlaylistFolder.swift (hunk 3 above)
Comment (Brandon-T) [reply Data/models/PlaylistFolder.swift]: No need. This is only `logged`. The error alert shown is localized :)

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift (hunk 4 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController.swift:347]: Yes that is correct. If the current item is moved, it needs to stop playing. It doesn't make sense to keep playing when we're moving the current item to a new folder. Otherwise the person will be able to pause and unpause an item that isn't in the current folder.

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistCarplayController.swift]: C++ strikes again :(
Fixed.

**Review by soner-yuksel — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
