### PR TITLE
Fix 2939: Reader mode should work for all URLs

### LINKED ISSUE #2939: reader mode breaks when loading certain URLs
### Description: 

When loading certain URLs, `reader mode` end up breaking. You'll need to restart Brave to recover.

### Steps to Reproduce 

* STR can be found via https://github.com/brave/security/issues/230#issuecomment-704693192

**Actual result:** 

* Example: https://youtu.be/zFh4qnFKHIQ

**Expected result:**

`Reader Mode` should work as expected, even when loading certain URLs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.21 (20.10.6.20)`

**Device details:** 

* `iPhone 11` running `iOS 14.0.1` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.0.1` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jumde @srirambv @aekeus @bsclifton

### PR DESCRIPTION
**Pull request by jumde**
## Summary of Changes

This pull request fixes https://github.com/brave/brave-ios/issues/2939

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Specified here: https://github.com/brave/brave-ios/issues/2939

1. Navigate to https://www.cnn.com/2020/10/07/weather/hurricane-delta-wednesday/index.html - confirm reader mode works
2. Transition to a different app (without closing the app) and open brave again
3. Verify that reader mode still works.

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Application/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -392,6 +392,7 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
 
         if let profile = self.profile {
             profile.reopen()
+            setUpWebServer(profile)
```
Comment (jumde) [inline Client/Application/Delegates/AppDelegate.swift]: Will be reverted when: https://github.com/brave/brave-ios/pull/2945 - is merged

Comment (iccub) [reply Client/Application/Delegates/AppDelegate.swift]: merged this, feel free to revert

**Review by iccub — APPROVED** [review]

File: Client/Application/Delegates/AppDelegate.swift (hunk 1 above)
Comment (jumde) [reply Client/Application/Delegates/AppDelegate.swift]: done!

**Review by iccub — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
