### PR TITLE
Fix #6807: Fixes CarPlay Wireless streaming and Bluetooth Wireless streaming + Enable Steering Wheel controls

### LINKED ISSUE #6807: Playlist :: Carplay 15 sec backward, fast backward, pause and resume buttons not working
### Description: 
Person reported in reported to the buttons on CarPlay that: 

"These buttons dont work in my car screen, so i have to control via my phone, but i'm unsure of other cars or if this is a known issue"

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes CarPlay Wireless streaming
- Enabled Bluetooth Wireless streaming
- Enable Steering Wheel controls
- Enabled Shared Playlist Folders

This pull request fixes: #6807, #6693

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
- Test CarPlay
- Test Bluetooth Streaming (NOT the same as CarPlay!)
- Test CarPlay wirelessly
- Test CarPlay Steering wheel controls
- Test Carplay non-steering wheel controls

## Screenshots:
https://user-images.githubusercontent.com/1530031/218175091-734139f5-912a-4acd-9d26-3bf16ac7f329.MOV

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

File: Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift [hunk 1]
```diff
@@ -384,6 +384,26 @@ class PlaylistViewController: UIViewController {
...
+      self.onNextTrack(self.playerView, isUserInitiated: true)
+    }.store(in: &playerStateObservers)
+    
+    player.publisher(for: .seekBackward).sink { [weak self] _ in
+      guard let self = self, !PlaylistCarplayManager.shared.isCarPlayAvailable else { return }
+      self.seekBackwards(self.playerView)
+    }.store(in: &playerStateObservers)
+    
+    player.publisher(for: .seekForward).sink { [weak self] _ in
+      guard let self = self, !PlaylistCarplayManager.shared.isCarPlayAvailable else { return }
```
Comment (cuba) [inline Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift:404]: Why are these `!PlaylistCarplayManager.shared.isCarPlayAvailable` shouldn't it be the opposite? Don't you need CarPlay to be available for seek forwards/backwards, etc to work? Or is this somehow ignoring the action if CarPlay is active because some other mechanism takes over? If this is the case, maybe a comment here would be useful because its not at all intuitive.

Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift:404]: This is the playlist controller. CarPlay is a separate controller and handles it's own stuff.

These functions are not for CarPlay. So there's a check to make sure that the user isn't using the phone and CarPlay at the same time. If they are, the CarPlay one takes precedence. There is a comment in the .finishedPlaying.

**Review by StephenHeaps — APPROVED** [review]
