### PR TITLE
Fix #846: Dismiss Sync screens after the device is removed from anoth…

### LINKED ISSUE #846: Sync page doesn't update until navigating out of sync page
### Description: 
Sync page doesn't update until navigating out of sync page

### Steps to Reproduce 
  1. Create sync chain on desktop
  2. Use QR code to join the sync chain on iOS
  3. Remove iOS device from desktop
  4. Desktop name gets duplicated on iOS, sync chain isn't removed, You can still add a new sync device via iOS
  5. Navigate out of settings page only then sync resets and shows the sync main page

**Actual result:** 
Sync page doesn't update until navigating out of sync page

**Expected result:**
Once device is reset and removed form sync chain it should automatically come out to sync home page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy. Was able to reproduce it twice

**Brave Version:** 
1.8(19.02.05.03)

**Device details:** 
iPhone 7+ (iOS 12.1)
BC on Linux running 0.59.35

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
…er device.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adaquate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Data/sync/Sync.swift [hunk 1]
```diff
@@ -179,6 +182,9 @@ public class Sync: JSInjector {
         fetchTimer = nil
         
         KeychainWrapper.standard.removeObject(forKey: Preferences.Sync.seedName.key)
+        // Edge case(#846). If a user stays on any of Sync screens while another device removes this device
```
Comment (jhreis) [inline Data/sync/Sync.swift]: Is this actually an edge case still? Maybe just remove the `Edge case(#846). ` as this technically isn't an edge case, but rather a solution to the above issue?

Comment (iccub) [reply Data/sync/Sync.swift]: You are right, I called it that way because it's rather unlikely that a user will be in one of the sync screens when his device gets deleted from another device.

**Review by jhreis — APPROVED** [review]

File: Client/Frontend/Sync/SyncViewController.swift [hunk 2]
```diff
@@ -43,4 +49,10 @@ class SyncViewController: UIViewController {
         
         code()
     }
+    
+    @objc func didLeaveSyncGroup() {
+        DispatchQueue.main.async { [weak self] in
+            self?.dismiss(animated: true, completion: nil)
```
Comment (jhreis) [inline Client/Frontend/Sync/SyncViewController.swift]: Wouldn't this pop the entire settings page?

Generally this should go inside the VC that is actually presenting, but this is probably fine here.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Sync/SyncViewController.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Sync/SyncViewController.swift]: Yes it drops the whole settings VC. I didn't want to implement it in all of the sync screens for sake of simplicity.
Device removal can happen in few of those Sync view controllers

Comment (jhreis) [reply Client/Frontend/Sync/SyncViewController.swift]: Understood, wdyt about having SettingsViewControl observe this though, since that is the one presenting the sync screens, and do something like:

```
didLeaveSyncGroup() {
    if children.contains(where: { $0.isKind(of: SyncViewController.classForCoder()) }) {
        self.navigationController.popToViewController(self, animated: true)
    }
}
```

This is a bit cleaner separation of concerns, since the child vc's do not need to worry about how they are being presented.

Comment (iccub) [reply Client/Frontend/Sync/SyncViewController.swift]: `navigationController` is nil in settings vc when another vc is presented. Please see my updated solution now, it should fix the problem.

File: Client/Frontend/Sync/SyncViewController.swift [hunk 3]
```diff
@@ -43,4 +49,12 @@ class SyncViewController: UIViewController {
         
         code()
     }
+    
+    @objc func didLeaveSyncGroup() {
+        DispatchQueue.main.async { [weak self] in
+            if let settingsVC = self?.navigationController?.childViewControllers.first {
```
Comment (jhreis) [inline Client/Frontend/Sync/SyncViewController.swift]: Maybe just use `self?.navigationController?.popToRootViewController(animated: true)` instead?

**Review by jhreis — APPROVED** [review]
