### PR TITLE
Fix #3071: Load favicons on background thread, fix cell reusing.

### LINKED ISSUE #3071: Improve bookmark scrolling when there is an insane amount of bookmarks
### Description: 
Improve bookmark scrolling when there is an insane amount of bookmarks

### Steps to Reproduce 
  1. Have a lot of bookmarks I mean really lot
  2. Open bookmarks menu and scroll through them
  3. There is a visible lag when trying to scroll through

**Actual result:** 
Lag when scrolling through a lot of bookmarks

**Expected result:**
Smooth scrolling 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.22(20.11.20.16)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #3071 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Import large amount of bookmarks, can use file from here https://github.com/brave/brave-ios/issues/3070
Scroll through bookmarks, see if there is a lag

This also fixed a bug where sometimes folder had backgrounds colors or favicons were incorrect

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift [hunk 1]
```diff
@@ -89,22 +93,40 @@ class FaviconFetcher {
...
+            }
+            self.fetchIcon(cachedOnly) { url, attributes in
+                DispatchQueue.main.async {
+                    completion(url, attributes)
+                }
             }
+        })
+        
+        if let task = loadTaskCancellable {
+            DispatchQueue.global(qos: .utility).async(execute: task)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favicons/FaviconFetcher.swift]: `utility` is a low priority task, something like seeing an icon may need to be bumped up to `userInitiated`. This also may spawn a lot of queue's on the global queue at once, are we sure we don't want to use a private `NSOperationQueue` instead?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift [hunk 2]
```diff
@@ -268,24 +270,36 @@ class BookmarksViewController: SiteTableViewController, ToolbarUrlActionsProtoco
...
         let lp = UILongPressGestureRecognizer(target: self, action: #selector(longPressedCell(_:)))
         cell.addGestureRecognizer(lp)
       }
       
+        if !shouldReuse {
+            return
+        }
+        
+        cell.imageView?.cancelFaviconLoad()
       cell.backgroundColor = .clear
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: nit: Some sort of mismatch in spacing here

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift]: this class has a mix of 2 and 4 space format, once you approve this PR i will reformat it, don't want to add noise to the PR until then

**Review by kylehickinson — APPROVED** [review]
