### PR TITLE
Fix #7448, fix #7413: VPN Initialize and Connect issues

### LINKED ISSUE #7413: VPN profile fails to initialize after purchase
### Description: 
VPN profile fails to initialize after purchase

Usually works the second time, sometimes takes a few tries on the install VPN profile screen on my device.

### Steps to Reproduce 
  1. Install 1.51.x, 1.50.x
  2. Complete IAP (Sandbox)
  3. Install VPN Profile
  4. Observe

### Actual result: 
IMG_3128 3

### Expected result:
Should prompt user to allow install

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: `1.51 (23.5.8.16)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone 12, iOS 16.4
iPhone X, iOS 16.3.1

### LINKED ISSUE #7448: [Follow up to #7432] An Infinite loading spinner is shown next to toggle switch when enabling VPN
### Description: 

Follow-up to #7432

### Steps to Reproduce 
  1. Launch Brave > Three Dot Menu
  2. Enable VPN
  3. Don't close the panel > Observe

### Actual result: 

An infinite loading spinner is shown next to the toggle switch when enabling VPN via the pop-up menu. If you close and reopen that menu, the loading spinner is not there anymore.

NOTE: This issue is not reproducible with 1.52

https://github.com/brave/brave-ios/assets/128532965/e816cae1-8baa-4fb3-920c-56ea9f2fc40f

### Expected result:

When enabling VPN, infinite loading spinner must not be shown

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes, with the latest 1.51
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 16.4.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
Pull request fixes the problem with infinite loading indicator when connection is successful. In addition it is adding a proper loading to Install profile and buy vpn screens, to handle problem with Profile install, it is added a retry mechanism to silently try to connect again since the tests how additional try will always succeed for install.

## Summary of Changes

This pull request fixes #7448
This pull request fixes #7413

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

7448

Launch Brave > Three Dot Menu
Enable VPN
Don't close the panel > Observe

7413

Install 1.51.x, 1.50.x
Complete IAP (Sandbox)
Install VPN Profile
Observe

## Screenshots:

7448

https://github.com/brave/brave-ios/assets/6643505/51855d2e-b9d1-412d-b43d-83edd1e34a2b

7413

https://github.com/brave/brave-ios/assets/6643505/007cba7d-e6f9-4368-a2ae-677563fceb5b

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]
Looks good. Thanks :)

File: Sources/BraveVPN/InstallVPNViewController.swift [hunk 1]
```diff
@@ -48,33 +50,49 @@ class InstallVPNViewController: UIViewController {
...
-                                      message: message,
-                                      preferredStyle: .alert)
-        alert.addAction(okAction)
-        
-        DispatchQueue.main.async {
-          self.present(alert, animated: true)
+        // Retry installing profile twice if it fails
+        // Error generated is WireGuard capabilities are not yet enabled on this node
+        if self.installVPNProfileRetryCount < 2 {
+          installVPNAction()
```
Comment (adityarajpt) [inline Sources/BraveVPN/InstallVPNViewController.swift:66]: `self.installVPNAction()`
