### PR TITLE
Fix #1801: Make bottom area of webview tappable.

### LINKED ISSUE #1801: Bottom area of web view can't be tapped.
### Steps to Reproduce 
  1. Open wikipedia, scroll down to bottom
  2. Try to tap on terms of use or privacy policy links
  3.

**Actual result:** 
They can't be tapped

**Expected result:**
Should be able to tap on them

Zrzut ekranu 2019-10-28 o 15 44 21

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
This is not website specific

### PR DESCRIPTION
**Pull request by iccub**
Solution taken from Firefox.

There are still some constraints issues, but it will be fixed in https://github.com/brave/brave-ios/pull/1736

## Summary of Changes

This pull request fixes issue #1801 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

See STR in the related ticket

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -891,11 +891,14 @@ class BrowserViewController: UIViewController {
...
-            make.width.equalTo(self.view.snp.width)
+            make.width.equalTo(self.view.safeArea.width)
             if let keyboardHeight = keyboardState?.intersectionHeightForView(self.view), keyboardHeight > 0 {
                 make.bottom.equalTo(self.view).offset(-keyboardHeight)
+            } else if let toolbar = self.toolbar {
+                make.bottom.lessThanOrEqualTo(toolbar.snp.top)
+                make.bottom.lessThanOrEqualTo(self.view.safeArea.bottom)
             } else {
-                make.bottom.equalTo(self.footer.snp.top)
+                make.bottom.equalTo(self.view.safeArea.bottom)
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift:901]: Should this be `view.safeArea` or `footer.safeArea`?
Code looks good.

Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController.swift:901]: `view` is safer, footer is not always present

**Review by kylehickinson — APPROVED** [review]
