### PR TITLE
Fix #3958: Do not reset to default when global settings are changed

### LINKED ISSUE #3958: Do not reset to default when global settings are changed
### Description: 
Do not reset to default when global settings are changed 

### Steps to Reproduce 
  1. Install 1.29
  2. Open settings -Shields & Privacy 
  3. Disable Browsing history and saved logins
  4. Close settings menu and reopen, settings are restored to default

**Actual result:** 

https://user-images.githubusercontent.com/17010094/126984106-08f191fa-7685-41cb-bd0b-11925e28b408.MP4

**Expected result:**
Settings changed should retain

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This pull request fixes #3958

Saving Global Settings for Private Data Toggles in Default Preferences.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Open settings -Shields & Privacy
- Disable Browsing history and saved logins
- Close settings menu and reopen, settings are conserved value

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift [hunk 1]
```diff
@@ -104,15 +104,21 @@ class BraveShieldsAndPrivacySettingsController: TableViewController {
         return shields
     }()
     
-    private lazy var toggles: [Bool] = {
```
Comment (kylehickinson) [inline Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift]: Not a huge deal, but now that this is no longer lazy, this will be executed for every clearable we have which seems a bit wasteful since it will evaluate to the exact same value each time.

Perhaps it would be easier to just set `Preferences.Privacy.clearPrivateDataToggles.value` in the [`valueChanged`  closure where `toggles[idx]` is set](https://github.com/brave/brave-ios/blob/3a040a87756f7dae5592714b2c0346c839f14da6/Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift#L146)?

Comment (soner-yuksel) [reply Client/Frontend/Settings/BraveShieldsAndPrivacySettingsController.swift]: Purpose was to gather the logic related with toggles to handle by itself but you are right it is wasteful.

Fix at https://github.com/brave/brave-ios/pull/3960/commits/3a7dfb3304ce58a43ed43738c9d7c7097d89b610

**Review by iccub — APPROVED** [review]
