### PR TITLE
Fix #6374: Fix crash in URL bar when dragging and dropping on itself

### LINKED ISSUE #6374: Crash when dragging current URL onto itself
### Description: 

If you long press the text in the URL bar while editing it will lift up, if you then simply move a little to the left/right and drop it will crash

### Steps to Reproduce 
  1. Visit any website 
  2. Tap URL bar to focus text
  3. Long press on focused text to cause a full URL drag
  4. Drop it slightly to the left/right of your pick up spot

**Reproduces how often:** Easily
**Brave Version:** 1.45 tested and reproduced but possibly from before then

Video:

https://user-images.githubusercontent.com/529104/201219875-e38ec224-0c77-42d0-9a6a-b718c7c010ec.mov

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix crash in drag-drop when dragging the URL bar's text on itself as the keyboard collapses.
- Implemented a custom drag-drop to accomplish this, as the default is trying to drag-drop an array for some reason.

This pull request fixes #6374

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift [hunk 1]
```diff
@@ -379,6 +379,12 @@ class TopToolbarView: UIView, ToolbarProtocol {
     locationTextField.attributedPlaceholder = self.locationView.placeholder
     locationTextField.rightView = qrCodeButton
     locationTextField.rightViewMode = .never
+    
+    let dragInteraction = UIDragInteraction(delegate: self)
+    locationTextField.addInteraction(dragInteraction)
+
+    let dropInteraction = UIDropInteraction(delegate: self)
+    self.addInteraction(dropInteraction)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Toolbars/UrlBar/TopToolbarView.swift]: Could we somehow pass this off to the BrowserViewController? It already has a drop interaction & delegate set up

**Review by kylehickinson — APPROVED** [review]
