### PR TITLE
Fix #1284: Support password-less logins for security keys

### LINKED ISSUE #1284: Webauthn ResidentKey support
### Description: 
Webauthn ResidentKey support does not seem to be complete on Brave.  It appears that residentKeys can be created during registration, however Brave does not appear to support use of residentKeys for authentication.

### Steps to Reproduce 
  1.  Using Brave on iOS, Go to https://demo.yubico.com/playground
  2.  Register a new user and sign-in
  3.  Click "ADD SECURITY KEY"
  4.  Select the box to "Enable passwordless login with this key"
  5.  Register the key
  6.  SIGN OUT
  7.  At the Sign In Screen click the link for "If you have enabled passwordless login..."
  8.  Try to authenticate with the key.
  9.  Remove key from Phone and plug it into a pc.  
  9.  On Windows 1903 using Edge go to https://demo.yubico.com/playground
 10. At the Sign In Screen click the link for "If you have enabled passwordless login..."
 11. Authenticate using the key that was registered using Brave on iOS. 

**Actual result:** 
During the login attempt using Brave on iOS I was prompted to "Interact with your authenticator", however nothing occurred. 

**Expected result:**
Similar to the experience using Edge on Windows, I should have been able to login to the site using the security key using a passwordless login flow.  

**Reproduces how often:** Easily reproduced

**Brave Version:** 
1.1.0 (19.06.21.17)

**Device details:** 
iPhone Xr (12.3.1)

### PR DESCRIPTION
**Pull request by jumde**
fix #1284 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

1. Navigate to https://yubico.com/playground
2. Create an account and add a security key with password-less login enabled
3. Sign-Out
4. On the login page, click on `If you have password-less login, click here to sign in`
5. With the key plugged in, you should login without entering any username and password.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Client/U2FExtensions.swift [hunk 1]
```diff
@@ -422,10 +423,17 @@ class U2FExtensions: NSObject {
...
+        
+        guard let requestId = response.credential?.credentialId.base64EncodedString() else {
+            sendFIDO2AuthenticationError(handle: handle)
+            return
+        }
         
         cleanupFIDO2Authentication(handle: handle)
         ensureMainThread {
-            self.tab?.webView?.evaluateJavaScript("navigator.credentials.postGet('\(handle)', \(true), '\(requestId)', '\(authenticatorData)', '\(clientDataJSONString)', '\(sig)', '')", completionHandler: { _, error in
+            self.tab?.webView?.evaluateJavaScript("navigator.credentials.postGet('\(handle)', \(true), '\(requestId)', '\(authenticatorData)', '\(clientDataJSONString)', '\(sig)', '\(userHandle)', '')", completionHandler: { _, error in
```
Comment (diracdeltas) [inline Client/U2FExtensions.swift:436]: are any of the parameters to `navigator.credentials.postGet` controllable by an external party (other than the user and the webpage that this JS is being evaluated on)? if so seems like there could be an XSS here (for instance set `clientDataJSONString` to `'); console.log(document.cookie);...` or something

Comment (jumde) [reply Client/U2FExtensions.swift:436]: These values are not controlled by any external user. `postGet` creates an `AuthenticatorAssertionResponse` object where the `clientDataJSONString` is converted to an ArrayBuffer and returned to the caller, see here: https://github.com/brave/brave-ios/pull/1327/files#diff-dd925ee95e1f0ee3f47db69a4451d76aR91

Comment (diracdeltas) [reply Client/U2FExtensions.swift:436]: where are the inputs to the constructor passed in? https://github.com/brave/brave-ios/pull/1327/files#diff-dd925ee95e1f0ee3f47db69a4451d76aR89

Comment (jumde) [reply Client/U2FExtensions.swift:436]: https://github.com/brave/brave-ios/pull/1327/files#diff-dd925ee95e1f0ee3f47db69a4451d76aR142

Comment (diracdeltas) [reply Client/U2FExtensions.swift:436]: cool, as long as you are confident this isn't an injection vector, lgtm
