### PR TITLE
Fix #3965: Add consistent capitalization to siri shortcut descriptions

### LINKED ISSUE #3965: Inconsistent capitalization of Open a New Tab under Open Brave News heading
### Description: 
Inconsistent capitalization of Open a New Tab under Open Brave News heading

### Steps to Reproduce 
  1. launch `Dev`
  2. tap `Settings`
  3. tap `Siri Shorcuts (sic)`
  4. swipe down to `Brave News`

**Actual result:** 

`Use Shortcuts to Open a New Tab...`

Image from iOS (1)

**Expected result:**
`Use Shortcuts to open a new tab...`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
`1.29 (21.7.20.15)`

**Device details:** 
iPhone 6s, iOS 14.7

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

Fix english text to have consistent capitalization on Siri Shortcut descriptions. Fixes https://github.com/brave/brave-ios/issues/3965

Note: Since the ticket was created a few new inconsistencies were added. I attempted to fix those as well however they are slightly out of the scope of the original ticket. More than happy to pull those changes out.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

STR included in ticket. Additional text changes outside of the STR include:
"Use Shortcuts to open playlist via Siri - Voice Assistant"
"Use Shortcuts to open a new tab & clear browser history via Siri - Voice Assistant"

## Screenshots:

Simulator Screen Shot - iPhone 13 Pro - 2022-03-01 at 11 50 54

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -2096,7 +2096,7 @@ extension Strings {
         public static let shortcutSettingsOpenPlaylistDescription =
             NSLocalizedString("shortcuts.shortcutSettingsOpenPlaylistDescription",
                               bundle: .braveShared,
-                              value: "Use Shortcuts to Open Playlist via Siri - Voice Assistant",
+                              value: "Use Shortcuts to open playlist via Siri - Voice Assistant",
```
Comment (iccub) [inline BraveShared/BraveStrings.swift]: Let's capitalize `Playlist` here. It's our product and we sometimes capitalize it. It is not consistent across the app unfortunately.

**Review by iccub — CHANGES_REQUESTED** [review]

File: BraveShared/BraveStrings.swift (hunk 1 above)
Comment (cuba) [reply BraveShared/BraveStrings.swift]: Done

**Review by iccub — APPROVED** [review]
Looks good :)
