### PR TITLE
Fix#2933:  Update Brave VPN intro card text + Graphic

### LINKED ISSUE #2933: Update Brave VPN intro card text + graphic
## Description
Update the promotional copy for VPN so it mentions trying for free and makes it clearer what the additional protections are.

Original thread for this issue:
> It seems strange to introduce the VPN with this `Protect your connection and block ads and trackers across your whole device.`
> Our new mobile onboarding makes it pretty clear that Brave blocks trackers and ads. So why would someone need a VPN that also block trackers and ads?? 

Also:
>...discussing why we aren't necessarily seeing a lot of users testing out the VPN. He brought up the point that maybe it's worth mentioning the free trial in some of the copy? You only find out about the free trial when you select a plan option.

### Steps to Reproduce 
  1. Go to settings
  2. See the intro card

**Actual result:** 
image

## Designs
New copy: `Upgrade to a VPN to protect your connection and block invasive trackers everywhere.`

Replace the background graphic as well; last release we missed incorrect grey icon colors in the background graphic.

image

## Assets
Figma: https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/iOS-VPN?node-id=0%3A199

### PR DESCRIPTION
**Pull request by soner-yuksel**
Adding new Asset Title - Subtitle - Button Title and Graphic for VPN Intro Banner

## Summary of Changes

This pull request fixes #2933

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Go to settings
- See the intro card
- Check Changes on the banner

## Screenshots:

test33

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -1017,11 +1017,17 @@ extension Strings {
                               value: "Buy",
                               comment: "Button text to buy Brave VPN")
         
+        public static let tryForFreeButton =
+            NSLocalizedString("learnMore",
```
Comment (iccub) [inline BraveShared/BraveStrings.swift]: change this key, it is used already, prefix it with `vpn.` to make sure it is unique

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
