### PR TITLE
Fix #938, remove passcode retry lock after entering foreground.

### LINKED ISSUE #938: Password lockout timer doesn't disappear after a certain amount of time
### Steps to Reproduce 
  1. Set pass code
  2. Close the app and reopen it to show the password prompt
  3. Enter wrong password 3 times
  4. Close the app, wait 15 minutes. Try to keep the app in memory, don't launch other apps etc.
  5. Open the app again

**Actual result:** 
You can't enter a password after waiting 15 minutes

**Expected result:**
You should be able to enter password after a lockout time is over

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Technical note: this is due to fact that the code for presenting the lockout does not go away when opening the app from foreground. It works if you kill the app and reopen it. 
The responsible VC most likely needs to observe for `UIApplicationWillEnterForeground`

### PR DESCRIPTION
**Pull request by iccub**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

See the STR in linked issue. For testing purposes I reduced the lockout timer from 15minutes to 1minute

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Shared/AuthenticationKeychainInfo.swift [hunk 1]
```diff
@@ -33,7 +33,7 @@ open class AuthenticationKeychainInfo: NSObject, NSCoding {
     open var useTouchID: Bool
 
     // Timeout period before user can retry entering passcodes
-    open var lockTimeInterval: TimeInterval = 15 * 60
+    private let lockTimeInterval: TimeInterval = AppConstants.BuildChannel == .release ? 15 * 60 : 60
```
Comment (iccub) [inline Shared/AuthenticationKeychainInfo.swift:36]: I decreased lockout timer for non-release builds to make it easier to test

**Review by danishjafri88 — DISMISSED** [review]
Looks good. Tested it out few times. Solid work

**Review by jhreis — CHANGES_REQUESTED** [review]
This still requires the app to be closed and reopened right? Just not thrown from memory?

I think it may be better to throw an event (or execute some internal function) after the lockout period duration that removes the alert page.

This would then handle all 3 situations automatically (thrown from memory, closed / reopened, stays on page). Could even re-fire event every minute to update a time countdown. (although this should prob be a followup PR).

**Comment by danishjafri88** [comment]
> This still requires the app to be closed and reopened right? Just not thrown from memory?
> 
> I think it may be better to throw an event (or execute some internal function) after the lockout period duration that removes the alert page.
> 
> This would then handle all 3 situations automatically (thrown from memory, closed / reopened, stays on page). Could even re-fire event every minute to update a time countdown. (although this should prob be a followup PR).

I think should be part of different PR altogether. As it is an enhancement

**Comment by iccub** [comment]
We still need some check on app launch and on foreground to show up keyboard and enable user interaction

File: Shared/AuthenticationKeychainInfo.swift (hunk 1 above)
Comment (jhreis) [reply Shared/AuthenticationKeychainInfo.swift:36]: - [ ] Please use `.isRelease` variable
- [ ] Use the newer API `15.minutes` and `1.minutes/60.seconds`

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift [hunk 2]
```diff
@@ -37,29 +37,32 @@ class PasscodeEntryViewController: BasePasscodeViewController {
...
-        if authenticationInfo?.isLocked() ?? false {
+    // `viewWillAppear()` doesn't trigger when the view controller is already loaded
+    // and a user goes from background to foreground, `UIApplicationWillEnterForeground` handles this case.
+    @objc func willEnterForeground() {
+        disableInteractionIfPasscodeLocked()
+    }
+    
+    private func disableInteractionIfPasscodeLocked() {
+        if authenticationInfo?.isLocked() == true {
+            displayLockoutError()
```
Comment (jhreis) [inline Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: I know this can handle being called multiple times, just want to make sure there aren't weird UI stuff going on though.

File: Client/Frontend/AuthenticationManager/BasePasscodeViewController.swift [hunk 3]
```diff
@@ -61,6 +61,10 @@ extension BasePasscodeViewController {
             return toast
         }()
     }
+    
+    func clearErrorToast() {
```
Comment (jhreis) [inline Client/Frontend/AuthenticationManager/BasePasscodeViewController.swift]: Is this needed, if just used in one place?

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Shared/AuthenticationKeychainInfo.swift (hunk 1 above)
Comment (iccub) [reply Shared/AuthenticationKeychainInfo.swift:36]: Can't use `minutes` here, this is `Shared` module and `BraveShared` can't be imported there (`Circular dependency between modules 'Shared' and 'BraveShared'`)

Same for `isRelease`, which is in `Client`

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: It's removed from superView each time it is called, should be safe.

**Review by jhreis — CHANGES_REQUESTED** [review]
The main point of using a timer was so we could remove all of the `passcodeCheck`. The timer be set for the full amount of the timeout (15 minutes), and only fire after that.

If the app is thrown from memory, then we will need to setup a new timer for the time remaining

e.g. 
User is locked out, after 6 minutes, the app is thrown from memory
Relaunch 3 minutes later, the user relaunches, the timer should be reset for 6 more additional minutes.

--

Optionally, if we wanted to have a countdown timer, we would probably setup the timer to run every minute and process lock / UI then.

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift [hunk 4]
```diff
@@ -72,6 +86,28 @@ class PasscodeEntryViewController: BasePasscodeViewController {
         delegate?.userDidCancelValidation?()
         super.dismissAnimated()
     }
+    
+    private func setUpTimer(force: Bool) {
```
Comment (jhreis) [inline Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: Is `force` needed here? We only use it when the user fails an auth attempt, and if `autInfo.lockoutTimeLeft` fails to unwrap it returns without "forcing" anyway, right? I think it would be fine/better to just force reset the timer every time this is called. There is no real harm it often resetting this, as long as the underlying time is correct.

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift [hunk 5]
```diff
@@ -37,33 +39,45 @@ class PasscodeEntryViewController: BasePasscodeViewController {
...
+    
+    private func disableUserInteraction() {
+        displayLockoutError()
+        // Don't show the keyboard or allow typing if we're locked out.
+        passcodePane.codeInputView.isUserInteractionEnabled = false
+        passcodePane.codeInputView.resignFirstResponder()
     }
 
     override func viewWillDisappear(_ animated: Bool) {
+        passcodeCheckTimer?.invalidate()
```
Comment (jhreis) [inline Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: See other comment, but if we decide to just always reset the timer, than we wouldn't need these lines anymore, as it would not matter if the timer was still in memory but invalidated (e.g. timer gets killed by iOS but object is still in memory).

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift [hunk 6]
```diff
@@ -37,33 +39,45 @@ class PasscodeEntryViewController: BasePasscodeViewController {
             make.bottom.left.right.equalTo(self.view)
             make.top.equalTo(view.safeArea.top)
         }
+        
+        NotificationCenter.default.addObserver(self, selector: #selector(willEnterForeground),
```
Comment (jhreis) [inline Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: I think better than using a global observer here, let's just let the prompting bleed back through from the app delegate. The app delegate already calls into the authenticator to setup this VC through a facade, and we should attempt to leverage this mechanism again. Otherwise we have one mechanism for presentation (e.g. app delegate), and a different mechanism for updating (e.g. notification center).

Currently, `AppAuthenticator` performs an early return when `isPrompting` is true. Instead of performing an early return we should just call something like `pincodeVC.update()` (I know the `AppAuthenticator` currently does not keep a reference to the pincodeVC, but not hard to add IMO. Thoughts?

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift (hunk 6 above)
Comment (iccub) [reply Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift]: Very good idea, thanks.
`passcodeVC` is already there, but in a static method, a small refactor should solve it

**Review by jhreis — APPROVED** [review]
