### PR TITLE
Fix #4191: - Allow sharing Brave Playlist + Fix Time Formatting for >= 1-Hour

### LINKED ISSUE #4191: Allow playlist items to be shared
Add UI so the played item can be shared.

It can be added to:
- ~~long press gesture~~
- swipe action

Upon one of those actions, a action sheet will show up with 2 actions:
- open in Brave: this closes playlist and opens the media url in new tab
- share: this opens standard share sheet with media url

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fix Time on Playlist showing incorrectly when Time >= 1-Hour.
- Added Sharing to Playlist.

This pull request fixes #4191

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

image
image
image

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayerTrackbar.swift [hunk 1]
```diff
@@ -234,8 +246,34 @@ class VideoTrackerBar: UIView {
     
     private func timeToString(_ time: CMTime) -> String {
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayerTrackbar.swift]: Since we got a bug let's add unit test for this method to catch all tricky cases

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client.xcodeproj/Brave.xctestplan [hunk 2]
```diff
@@ -43,7 +43,8 @@
     },
     {
       "skippedTests" : [
-        "NavigationRouterTests\/testNavigationPathInPrivateBrowsingOnlyMode()"
+        "NavigationRouterTests\/testNavigationPathInPrivateBrowsingOnlyMode()",
+        "PlaylistTests\/testVideoPlayerTrackBarTimeManualFormatter()"
```
Comment (iccub) [inline Client.xcodeproj/Brave.xctestplan:47]: why this test is skipped?

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift [hunk 3]
```diff
@@ -92,14 +107,69 @@ extension PlaylistListViewController: UITableViewDelegate {
...
 
         cacheAction.image = cacheState == .invalid ? #imageLiteral(resourceName: "playlist_download") : #imageLiteral(resourceName: "playlist_delete_download")
         cacheAction.backgroundColor = #colorLiteral(red: 0.4509803922, green: 0.4784313725, blue: 0.8705882353, alpha: 1)
         
         deleteAction.image = #imageLiteral(resourceName: "playlist_delete_item")
         deleteAction.backgroundColor = #colorLiteral(red: 0.9176470588, green: 0.2274509804, blue: 0.05098039216, alpha: 1)
         
-        return UISwipeActionsConfiguration(actions: [deleteAction, cacheAction])
+        shareAction.image = UIImage(systemName: "square.and.arrow.up")
+        shareAction.backgroundColor = #colorLiteral(red: 0.1764705926, green: 0.4980392158, blue: 0.7568627596, alpha: 1)
```
Comment (iccub) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift]: Don't we this or similar color hardcoded somewhere already?

File: Client.xcodeproj/Brave.xctestplan (hunk 2 above)
Comment (Brandon-T) [reply Client.xcodeproj/Brave.xctestplan:47]: I added two tests. One is testing my manual code which isn't ever used, and the other is testing the Formatter from Apple. If ever in the future we switch to the manual parsing, this test would be enabled again.

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift]: This colour was made up by me :( There is no design for it, so I chose one sort of in-between existing colours but one that would stand out enough on the swipe menu, and be colour blind friendly.

**Review by iccub — APPROVED** [review]
Code looks good to me, we waiting on a final blue color for the button we added
