### PR TITLE
Fix #175, fix #180: tab count fixes

### LINKED ISSUE #175: Tab count is incorrect upon tab restoration
### Description: 

It will always show "1" as the tab count when you launch and it restores more than 1 tab

### Steps to Reproduce 
  1. Open 4 tabs and load a website in each (empty new tabs will not be restored)
  2. Kill the app
  3. Relaunch

**Actual result:**

Confirm that the tab count in the toolbar is only showing "1"

**Expected result:**

Should display the number of tabs restored (4)

**Reproduces how often:**

Always

**Brave Version:** 

[development@db1cdeb](https://github.com/brave/brave-ios/commit/db1cdeb7f54467755ba7e229617e86b5ac534e6c)

### LINKED ISSUE #180: Tab count in private and normal modes is summed up.
STR:
- open 2 tabs in normal mode
- switch to private browsing
- open a tab

tab counter shows 3, should show 1 only for private browsing tabs
if you go back to normal mode it still shows 3 tabs

### PR DESCRIPTION
**Pull request by iccub**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [x] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Widgets/TabsButton.swift [hunk 1]
```diff
@@ -141,6 +141,7 @@ class TabsButton: UIButton {
         let currentCount = self.countLabel.text
         let infinity = "\u{221E}"
         let countToBe = (count < 100) ? count.description : infinity
+        countLabel.text = countToBe
```
Comment (kylehickinson) [inline Client/Frontend/Widgets/TabsButton.swift]: This label's text is set down on [L198](https://github.com/brave/brave-ios/pull/181/files#diff-2232a56906839da06d1d6785995815f9R198), so I think this might require taking another look as to why it's really not working.

I.e. Is the if statement just below not executing? Is `updateTabCountUsingTabManager` not being called? Why is this not working anymore since #131 (Could it be TabMO stuff not restoring fast enough? Race condition?)

I have lots of questions haha 😅

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Widgets/TabsButton.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Widgets/TabsButton.swift]: The statement below executes but it doesn't update the label somehow. Sorry for the lazy solution will dig into it more today or tomorrow :)

**Comment by iccub** [comment]
So this PR no 131 was the case, you removed a check for `tabManager.selectedTab` and it made calls updating tab count even before internal tab restoration method was called.
 
Thanks for holding this back and not accepting my lazy fix @kylehickinson

**Comment by kylehickinson** [comment]
Haha nice! I remember removing that check because it was causing the tab count _not_ to update on restore... Do we know what changed?

**Comment by iccub** [comment]
Ok I see what changed, this issue only happens in debug builds. If there the `app crashed, restore tabs?` popup it restores and updates tab count correctly. Going to investigate more

**Review by kylehickinson — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
