### PR TITLE
Fix #6118: Find in Page Problems

### LINKED ISSUE #6118: Find-In Page Bar Related Issues
### Description: 

**_De-activation:_**

There are multiple issues related with FindInPage de-activation.

After dismissing Find-In Page Bar using X button, the text is still selected and it is obstructing engaging the page in any other way.

This is reported by a user https://community.brave.com/t/cant-select-text-after-using-find-in-page/430885

However this problem persists also for other cases like adding a new tab using Bottom Bar / changing a tab using Tabs Bar or activating Tab Tray from Bottom Bar when Fin-In Page is still activated.

**_Presentation:_**

In addition to the other issues mentioned, activating Find-In Page when URL Bar is is activated as Bottom Bar has a problem with displaying the Bar under the keyboard when it is first activated.

### Steps to Reproduce 

**_De-activation:_**

1. Open a webpage in Brave IOS browser
2. Find text on page
3. Use the x button to dismiss the find in page bottom bar / Change the tab using Tab Bar / Open a new tab using BottomBar / Open TabTray using BottomBar 
4. Try to select text that doesn’t match the find on page results.
5. The find on page result is selected instead of the text I selected.

**_Presentation:_**

1. Open a webpage in Brave IOS browser
2. Activate URL Bottom Bar
3. Find text on page
4. Bar is presented under keyboard

**Actual result:** 

https://user-images.githubusercontent.com/6643505/194398967-dfad78c7-f388-4e81-bc15-ba0c6e2fcaa0.mp4

**Expected result:**

The proper de-activation and presentation of bar Find-In Page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any version

**Device details:** 
Any 

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### PR DESCRIPTION
**Pull request by soner-yuksel**
Fixing Cant select text after closing the bar and Editing issues related with new actions.

## Summary of Changes

This pull request fixes #6118 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
De-activation Problem:

- Open a webpage in Brave IOS browser
- Find text on page
- Use the x button to dismiss the find in page bottom bar / Change the tab using Tab Bar / Open a new tab using BottomBar / Open TabTray using BottomBar
- And Find-In Page deactivates properly

Presentation Problem:

- Open a webpage in Brave IOS browser
- Activate URL Bottom Bar
- Find text on page
- Bar is presented on top keyboard

## Screenshots:

https://user-images.githubusercontent.com/6643505/194400556-1de38779-7c84-417b-8706-cab8fb3a7539.MP4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1161,7 +1161,9 @@ public class BrowserViewController: UIViewController {
 
     header.snp.remakeConstraints { make in
       if self.isUsingBottomBar {
-        if let keyboardHeight = keyboardState?.intersectionHeightForView(self.view), keyboardHeight > 0, presentedViewController == nil {
+        // Need to check Find In Page Bar is enabled in order to aligh it properly when bottom-bar is enabled
+        if let keyboardHeight = keyboardState?.intersectionHeightForView(self.view), keyboardHeight > 0,
+           (presentedViewController == nil || findInPageBar != nil) {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController.swift:1166]: This is added for Find-In Page presented under the keyboard when Bottom Bar is selected.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift [hunk 2]
```diff
@@ -181,3 +181,101 @@ class WKWebViewFindStringFindDelegate: NSObject {
...
+        // delegate to slide the bar up and down with the keyboard. We don't want to animate the
+        // constraints added above, however, so force a layout now to prevent these constraints
+        // from being lumped in with the keyboard animation.
+        findInPageBar.layoutIfNeeded()
+      }
+
+      self.findInPageBar?.becomeFirstResponder()
+    } else {
+      // Empty string should be executed in order to remove the text highlights before find script done
+      find("", function: "find")
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift:264]: Before de-activating the Find-In Page to remove the highlights from the page so normal interaction can be done.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 3]
```diff
@@ -2077,6 +2042,7 @@ public class BrowserViewController: UIViewController {
     }
     
     if let findInPageBar = findInPageBar {
+      updateFindInPageVisibility(visible: false)
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController.swift:2045]: Added for the case when Zoom is activated while Find-In page is activated and searching a text.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -2316,6 +2282,8 @@ extension BrowserViewController: TabsBarViewControllerDelegate {
   func tabsBarDidSelectTab(_ tabsBarController: TabsBarViewController, _ tab: Tab) {
     if tab == tabManager.selectedTab { return }
     topToolbar.leaveOverlayMode(didCancel: true)
+    updateFindInPageVisibility(visible: false)
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController.swift:2285]: Fixes the different Tab selection case for Find-In Page de-activation.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 5]
```diff
@@ -3261,55 +3229,6 @@ extension BrowserViewController: TabTrayDelegate {
   }
 }
 
-extension BrowserViewController: FindInPageBarDelegate, FindInPageScriptHandlerDelegate {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController.swift:3264]: I moved the find-In page delegates to proper file for easy fetch functionality

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift:1166]: We will want this change specifically in 1.44 FYI

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift:1166]: I didn't think about that. @iccub should we move everything to 1.44 or only this part separately ?

Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController.swift:1166]: easier to have both imo

Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift:1166]: Ok changing milestone of the ticket
