### PR TITLE
Fix #3798: Adds scan QR code shortcut

### LINKED ISSUE #3798: `Scan QR Code` shortcut missing when tapping Brave icon
### Description: 

Looks like we're missing the `Scan QR Code` shortcut under the context menu when tapping and holding the Brave icon. Reported by @srirambv.

### Steps to Reproduce

  1. install `1.27.x` via TF
  2. long tap the Brave icon and notice that the `Scan QR Code` is missing

**Actual result:** 

IMG_3713

**Expected result:**

IMG_6956

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when running through the above STR

**Brave Version:** 

* `1.27 (21.6.15.14)` - **Reproduced*

**Device details:** 

* `iPhone 11` running `iOS 14.6` - **Reproduced**
* `iPhone 12` running `iOS 14.6` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @Brandon-T @iccub @kylehickinson

### PR DESCRIPTION
**Pull request by ns-vasilev**
Adding a new shortcut for scanning QR codes to shortcut menu.

## Summary of Changes

This pull request fixes #3798

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

Simulator Screen Shot - iPhone 8 - 2021-07-13 at 13 46 38

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

File: Client/Application/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -228,7 +228,13 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
             icon: UIApplicationShortcutIcon(templateImageName: "quick_action_new_private_tab"),
             userInfo: [:])
         
-        application.shortcutItems = Preferences.Privacy.privateBrowsingOnly.value ? [privateTabItem] : [newTabItem, privateTabItem]
+        let scanQr = UIMutableApplicationShortcutItem(type: "\(Bundle.main.bundleIdentifier ?? "").ScanQR",
```
Comment (soner-yuksel) [inline Client/Application/Delegates/AppDelegate.swift]: nit: Can you rename it similar other shortcut items ?

`let scanQRCodeItem = `

File: Client/Application/QuickActions.swift [hunk 2]
```diff
@@ -60,10 +61,16 @@ class QuickActions: NSObject {
             handleOpenNewTab(withBrowserViewController: browserViewController, isPrivate: false)
         case .newPrivateTab:
             handleOpenNewTab(withBrowserViewController: browserViewController, isPrivate: true)
+        case .scanQR:
```
Comment (soner-yuksel) [inline Client/Application/QuickActions.swift]: nit: Please change the naming as 

`case .scanQRCode:
`

**Comment by soner-yuksel** [comment]
Thanks for the contribution, this is awesome. 

I have a small concern here. Right now If we will attach the scanQRCode function to a Quick Action directly and scan a code from this action, it will actually open the website on existing tab.

I believe we should first open a new tab on the existing mode (private or default) and scan the code after that. What do you guys think? @iccub @Brandon-T

**Comment by iccub** [comment]
I prefer opening a new tab first, good point. Not sure how much harder it would be to do so

**Comment by soner-yuksel** [comment]
> I prefer opening a new tab first, good point. Not sure how much harder it would be to do so

Not hard, we can `openBlankNewTab` and using TabManager selectedTab, we can get if the current mode is private or standard. Question is do we want this or is it alright as it is ?

**Comment by iccub** [comment]
@soner-yuksel Firefox opens in the same tab

**Comment by iccub** [comment]
We can leave same tab and wait for users feedback

**Review by soner-yuksel — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]

**Comment by iccub** [comment]
Nice job :) we finally have time to include that for next release
