### PR TITLE
Fix #4193: Create PDF activity broke with XCode 13 compiler.

### LINKED ISSUE #4193: Brave’s action ‘Create PDF’ not working since 1.31 update
Investigate:
https://community.brave.com/t/brave-s-action-create-pdf-not-working-since-1-31-update/284008

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
The UIActivity deallocates before createPDF action is called.
I moved the create pdf action outside, this is what other UIActivities do as well

This pull request fixes #4193 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Must be tested on iOS 14 or higher

Open a site
Tap on 3dot menu
Scroll down, tap on 'Create PDF action'
Verify share sheet with pdf showed up

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

**Comment by soner-yuksel** [comment]
Wonder what change they made causes UIActivity to deallocate.

**Comment by iccub** [comment]
@soner-yuksel this is broken on iOS14 too btw, looks like xcode13 compiler change

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1676,28 +1676,38 @@ class BrowserViewController: UIViewController {
...
-                        try pdfData.write(to: url)
-                        let pdfActivityController = UIActivityViewController(activityItems: [url], applicationActivities: nil)
-                        if let popoverPresentationController = pdfActivityController.popoverPresentationController {
-                            popoverPresentationController.sourceView = sourceView
-                            popoverPresentationController.sourceRect = sourceRect
-                            popoverPresentationController.permittedArrowDirections = arrowDirection
-                            popoverPresentationController.delegate = self
+                let createPDFActivity = CreatePDFActivity() {
+                    
+                    webView.createPDF { [unowned self] result in
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: Shouldn't use `unowned` in this case even if its unlikely for BVC to dealloc during this time

File: Client/Frontend/Share/CreatePDFActivity.swift [hunk 2]
```diff
@@ -32,20 +30,8 @@ class CreatePDFActivity: UIActivity {
...
-            case .success(let data):
-                self.callback(data)
-                self.activityDidFinish(true)
-            case .failure(let error):
-                log.error("Failed to create PDF with error: \(error)")
-                self.activityDidFinish(false)
-            }
-        }
+        callback()
+        activityDidFinish(true)
```
Comment (kylehickinson) [inline Client/Frontend/Share/CreatePDFActivity.swift]: We should be passing back the success/failure to call back into the `UIActivity`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Share/CreatePDFActivity.swift (hunk 2 above)
Comment (iccub) [reply Client/Frontend/Share/CreatePDFActivity.swift]: I followed here what we do with other activities, like `AddFeedToBraveNewsActivity`

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController.swift]: i changed it precisely for this reason, bvc never deallocates, will go back to weak self, thanks

Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: I know its probably not going to in the current architecture, but `createPDF` is an escaping and long-running call so in this case we'd want to use `weak` anyways.

File: Client/Frontend/Share/CreatePDFActivity.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Share/CreatePDFActivity.swift]: `AddFeedToBraveNewsActivity` is different, it's not created unless success is the only option, in this case the activity is created but it can fail based on the executed task. You can simply do `callback: () -> Bool` instead and do `activityDidFinish(callback())` then return false when it fails in createPDF result closure

**Review by kylehickinson — APPROVED** [review]
