### PR TITLE
Fix #4744: Add checksum validation for send token address.

### LINKED ISSUE #4744: Add extra validation of ETH address in send
### Description: 
Same as Desktop ref: https://github.com/brave/brave-browser/issues/19532

In Ethereum an address casing is used as a checksum for validation. We should check this and if it fails give an error.

If an input address matches the API result for KeyringController's GetChecksumEthAddress then don't give a warning
If an address has each alphabetic character as lowercase, give a warning that the address has no checksum information and might be invalid.
If an address has each alphabetic character as uppercase, give a warning that the address has no checksum information and might be invalid.
If an address has both lowercase and uppercase alphabetic characters, and it doesn't match the checksum address, give an error and don't allow the user to send.

API available in  v1.35.30 and above

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Add checksum validation for send token address.

This pull request fixes #4744 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
1. Test invalid ETH address
2. Test address is own
3. Test address is token contract address
4. Test address is all lowercase or all uppercase 
5. Test address will give unmatched checksum address 

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by StephenHeaps — APPROVED** [review]

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 1]
```diff
@@ -185,7 +191,15 @@ public class SendTokenStore: ObservableObject {
       || (allTokens.first(where: { $0.contractAddress.lowercased() == normalizedSendAddress }) != nil) {
       addressError = .contractAddress
     } else {
-      addressError = nil
+      keyringService.checksumEthAddress(sendAddress) { [self] checksumAddress in
+        if sendAddress == checksumAddress {
+          addressError = nil
+        } else if sendAddress.removingHexPrefix.lowercased() == sendAddress.removingHexPrefix || sendAddress.removingHexPrefix.uppercased() == sendAddress.removingHexPrefix {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift:201]: Just do `caseInsentiveCompare` instead of doing both uppercase/lowercase

Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/SendTokenStore.swift:201]: based on the requirement , this is checking if the address is all in lowercase or all in uppercase. if the address is mixed with lowercase and uppercase then either it has to be the same as the checksum address (the first condition) or it has invalid checksum address (the last condition)

**Review by kylehickinson — APPROVED** [review]
