### PR TITLE
Ref #29: Shields relying on content rules now work

### LINKED ISSUE #90: Block Scripts
```
let baseRule = [{'trigger':{'url-filter':'.*','resource-type':['script']},'action':{'type':'block'}}]
```

Main place of complication here regards domain exceptions.

If Global Script Blocking (GSB) is `off` a `blacklist` of domains must be tracked.

If GSB is `on` a `whitelist` of domains must be tracked.

---

Whenever GSB is changed, all domain-specific script settings are left alone.

Whenever a domain exception is created, it i stored in CoreData, and the adblock script rule rebuilt and reloaded. During rebuilding, CD is quiried to build the `blacklist`/`whitelist`

Domain flags will be tracked in CoreData:

`shield_noScript`
`shield_allOff`

```
let domainString = Domain.domainAndScheme(fromUrl: url)
let basePredicate = NSPredicate(format: "url == %@", domainString)

...

// Gives us `whitelist` if GSB is on
// Gives us `blacklist` if GSB is off
let exceptionListPredicate = NSPredicate(format: "shield_noScript == \(!shield_allOff)")
let exceptionListDomains = // ...
```

The new baseRule ends up being:

```
let baseJSON = [{'trigger':{'url-filter':'.*','resource-type':['script']},'action':{'type':'block'}}]

let exceptionListKey = GSB.isOn ? "unless-domain" : "if-domain"
baseJSON["trigger"][exceptionListKey] = exceptionListDomains

// Reload Lists

// Refresh Tab
```

There are two situations that blocking logic must be handled.

- On creation of a tab's webview (can happen beyond just tab creation), content rules must be loaded into the webview's configuration
- Reloaded on change

### PR DESCRIPTION
**Pull request by jhreis**
Blocked until https://github.com/brave/brave-ios/pull/388 is merged.

Commit message body on merging should include:

> Fix #90: Script blocking now works globally and per-domain

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [x] I have updated the *UI Tests* to cover new or changed functionality
- [x] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/ContentBlocker/ContentBlockerHelper.swift [hunk 1]
```diff
@@ -5,23 +5,118 @@
...
-    case social = "disconnect-social"
-
-    var filename: String { return self.rawValue }
+// Rename to BlockList
+class BlocklistName: Equatable, Hashable {
+    static let ad = BlocklistName(filename: "block-ads")
+    static let tracker = BlocklistName(filename: "block-trackers")
+    static let https = BlocklistName(filename: "upgrade-http")
+    static let script = BlocklistName(filename: "block-scripts")
+    static let image = BlocklistName(filename: "block-images")
```
Comment (kylehickinson) [inline Client/Frontend/ContentBlocker/ContentBlockerHelper.swift:19]: I thought we weren't supporting block images in 1.7?

File: Client/Frontend/ContentBlocker/ContentBlockerHelper.swift [hunk 2]
```diff
@@ -5,23 +5,118 @@
...
+            onList.insert(.script)
+        }
+        
+        // TODO #159: Setup image shield
+        // TODO #269: Setup HTTPS shield
+        
+        return (onList, allLists.subtracting(onList))
+    }
+    
+    private static func include(domainSetting domain: NSNumber?, globalValue global: Preferences.Option<Bool>) -> Bool {
```
Comment (kylehickinson) [inline Client/Frontend/ContentBlocker/ContentBlockerHelper.swift]: Why not just make this an inline func in `blocklists(forDomain:)` since it's only called in there?

File: Client/Frontend/ContentBlocker/ContentBlockerHelper.swift [hunk 3]
```diff
@@ -60,11 +154,14 @@ enum BlockingStrength: String {
 
 @available(iOS 11.0, *)
```
Comment (kylehickinson) [inline Client/Frontend/ContentBlocker/ContentBlockerHelper.swift:156]: No longer required since we're iOS 12+

File: Client/Frontend/Shields/ShieldsViewController.swift [hunk 4]
```diff
@@ -63,15 +63,13 @@ class ShieldsViewController: UIViewController, PopoverContentComponent {
...
-                        // TODO: Switch ^ to `isEnabled.toggle()` when we support Swift 4.2+
-                    }
-                    view.toggleSwitch.isOn = shieldOverrideEnabled
+            if let url = url, let shieldState = Domain.getBraveShield(forUrl: url, shield: shield) {
+                // site-specific shield has been overridden, update
+                
+                view.toggleSwitch.isOn = Bool(truncating: shieldState)
+                if shield == .AllOff {
+                    // Reverse, as logic is inverted
+                    view.toggleSwitch.isOn.toggle()
```
Comment (kylehickinson) [inline Client/Frontend/Shields/ShieldsViewController.swift:72]: I don't think we're supporting Swift 4.2 yet (#285),  so we may have to get this at a later time

File: Client/Frontend/Shields/ShieldsViewController.swift [hunk 5]
```diff
@@ -63,15 +63,13 @@ class ShieldsViewController: UIViewController, PopoverContentComponent {
...
-                    if shield == .AllOff {
-                        // Reversed...
-                        shieldOverrideEnabled = !shieldOverrideEnabled
-                        // TODO: Switch ^ to `isEnabled.toggle()` when we support Swift 4.2+
-                    }
-                    view.toggleSwitch.isOn = shieldOverrideEnabled
+            if let url = url, let shieldState = Domain.getBraveShield(forUrl: url, shield: shield) {
+                // site-specific shield has been overridden, update
+                
+                view.toggleSwitch.isOn = Bool(truncating: shieldState)
```
Comment (kylehickinson) [inline Client/Frontend/Shields/ShieldsViewController.swift:69]: TIL, or not really because [Apple doesn't have any doc for this](https://developer.apple.com/documentation/swift/bool/2895323-init) lol.

File: Data/models/Domain.swift [hunk 6]
```diff
@@ -84,32 +84,21 @@ public final class Domain: NSManagedObject, CRUD {
...
-            shieldOptions.forEach { (shield, isOn) in
-                BraveShieldState.set(forUrl: url, state: (shield, isOn?.boolValue))
-            }
+    
+    public class func getBraveShield(forUrl url: URL, shield: BraveShieldState.Shield) -> NSNumber? {
+        let context = DataController.newBackgroundContext()
+        let domain = Domain.getOrCreateForUrl(url, context: context)
+        var returnValue: NSNumber?
+        switch shield {
+            case .AllOff: returnValue = domain.shield_allOff
```
Comment (kylehickinson) [inline Data/models/Domain.swift]: I think we can just switch these all to `return {x}` instead of assigning `returnValue`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/ContentBlocker/ContentBlockerHelper.swift (hunk 1 above)
Comment (jhreis) [reply Client/Frontend/ContentBlocker/ContentBlockerHelper.swift:19]: We aren't, it will be disabled in the UI, but figured I'd just throw in the scripts since I was already modifying all of these rulesets. Block image script does not properly deal with all images, so we will need to combine this with injected scripts as well.

File: Client/Frontend/Shields/ShieldsViewController.swift (hunk 5 above)
Comment (jhreis) [reply Client/Frontend/Shields/ShieldsViewController.swift:69]: Also, https://developer.apple.com/documentation/swift/bool/2895341-init, but can just switch to a standard ternary for now. Odd they don't have any docs on this.

File: Client/Frontend/ContentBlocker/ContentBlockerHelper.swift (hunk 3 above)
Comment (jhreis) [reply Client/Frontend/ContentBlocker/ContentBlockerHelper.swift:156]: This wasn't added, we'll create another ticket to go and purge all of these.

File: Client/Frontend/Shields/ShieldsViewController.swift (hunk 4 above)
Comment (jhreis) [reply Client/Frontend/Shields/ShieldsViewController.swift:72]: https://twitter.com/aligatr/status/1004099413709553666
I think it is fine per ^

Comment (kylehickinson) [reply Client/Frontend/Shields/ShieldsViewController.swift:72]: Yeah as discussed, it seems Swift stdlib is unaffected by `SWIFT_VERSION` configuration flag. Seems to use the toolchain based on Xcode version. Since we are using Xcode 10, Swift 4.2 for the language/stdlib is supported regardless of `SWIFT_VERSION`

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Waiting for @iccub to review before merging
