### PR TITLE
Fix brave/internal#677, fix #2290: Adjust rewards visibility based on DeviceCheck

### LINKED ISSUE #2290: Internal issue
https://github.com/brave/internal/issues/677

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes issue brave/internal#677

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Build `Fennec` scheme to simulator, all should be the same
- Build `Fennec_Enterprise`, `FirefoxBeta`, or `Firefox` scheme to simulator, Rewards should disappear

## Screenshots:

| Home | Settings | Onboarding |
| --- | --- | --- | 
| Simulator Screen Shot - iPhone 11 Pro - 2020-01-14 at 16 04 51 | Simulator Screen Shot - iPhone 11 Pro - 2020-01-14 at 16 04 53 | Simulator Screen Shot - iPhone 11 Pro - 2020-01-14 at 16 05 22 |

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Extensions/BraveRewardsExtensions.swift [hunk 1]
```diff
@@ -4,6 +4,18 @@
...
 import BraveRewards
+import DeviceCheck
+
+extension BraveRewards {
+  /// Whether or not Brave Rewards is available/can be enabled
+  public static var isAvailable: Bool {
+    #if DEBUG
+    return true
+    #else
+    return DCDevice.current.isSupported
```
Comment (Brandon-T) [inline BraveRewardsUI/Extensions/BraveRewardsExtensions.swift:15]: Nit: This could be in the DeviceCheck class we already have so that all `DCDevice` related stuff is in one place.. but entirely up to you. Not a problem to leave it here.

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 2]
```diff
@@ -3434,40 +3440,40 @@ extension BrowserViewController: OnboardingControllerDelegate {
...
-            if BraveAds.isCurrentLocaleSupported() {
-                Preferences.General.basicOnboardingProgress.value = OnboardingProgress.ads.rawValue
-            } else {
-                Preferences.General.basicOnboardingProgress.value = OnboardingProgress.rewards.rawValue
-            }
-            
-        case .existingUserRewardsOff:
-            if BraveAds.isCurrentLocaleSupported() {
-                Preferences.General.basicOnboardingProgress.value = OnboardingProgress.ads.rawValue
+        if !BraveRewards.isAvailable {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: nit: could reverse this condtion

File: Client/Frontend/Browser/Onboarding/OnboardingNavigationController.swift [hunk 3]
```diff
@@ -48,33 +48,33 @@ class OnboardingNavigationController: UINavigationController {
...
-                //The user already made it to rewards and agreed so they should only see ads countdown
-                if progress == .rewards || progress == .ads {
-                    return BraveAds.isCurrentLocaleSupported() ? [.adsCountdown] : [.rewardsAgreement]
-                }
-                return BraveAds.isCurrentLocaleSupported() ? [.searchEnginePicker, .shieldsInfo, .rewardsAgreement, .adsCountdown] : [.searchEnginePicker, .shieldsInfo, .rewardsAgreement]
-            case .existingUserRewardsOff(let progress):
-                //The user already made it to rewards and agreed so they should only see ads countdown
-                if progress == .rewards || progress == .ads {
-                    return BraveAds.isCurrentLocaleSupported() ? [.adsCountdown] : []
+            if !BraveRewards.isAvailable {
```
Comment (iccub) [inline Client/Frontend/Browser/Onboarding/OnboardingNavigationController.swift]: nit: could reverse this condition

File: Client/Frontend/Browser/Onboarding/OnboardingShieldsView.swift [hunk 4]
```diff
@@ -81,6 +73,18 @@ extension OnboardingShieldsViewController {
         }
         
         init(theme: Theme) {
+            if !BraveRewards.isAvailable {
```
Comment (iccub) [inline Client/Frontend/Browser/Onboarding/OnboardingShieldsView.swift]: nit: reverse

**Review by iccub — APPROVED** [review]
I would just reverse `!BR.isAvailable` in few places, approving bc it looks good anyway

**Comment by iccub** [comment]
This needs rebase I think, CI failing with that bug that I fixed some time ago

**Review by iccub — APPROVED** [review]
Please reference this ticket in commit when merging
https://github.com/brave/brave-ios/issues/2290

So qa will not miss it when testing(if they even can test it)

**Comment by kylehickinson** [comment]
I'm not sure how they can test this to be honest :) I may mark as `QA/No`
