### PR TITLE
Fix #7893: Browser Lock - Cancel Issue

### LINKED ISSUE #7893: Browser Lock - Cancel Issue
### Description: 

There is problem with Browser Lock screen logic reported by a user in community forums which doesnt block user from entering browser.

Community Report: https://community.brave.com/t/brave-browser-reuses-password-lock-for-opening-lock-after-accessing-passwords-cancel-button-then-unlocks-browser/501830

### Steps to Reproduce 

1. Make sure your Browser Lock is turned on, and access your saved passwords
2. Go to the iOS home menu, and reopen the app
3. You will now see the interface for the password lock, with the cancel button
4. Press cancel and snoop around on the person’s tabs because this browser’s lock just got bypassed

### Actual result: 

Cancel is presented on main browser lock

### Expected result:

It should not be allowing user to cancel

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This pull request fixes #7893

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
- Enable Browser Lock
- Put application to background
- And Open App again
- Check no cancel fro browser unlock

## Screenshots:

https://github.com/brave/brave-ios/assets/6643505/bf7b52b2-d4ef-4303-9d39-cda031bcb87a

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Passcode/WindowProtection.swift [hunk 1]
```diff
@@ -148,6 +148,8 @@ public class WindowProtection {
     NotificationCenter.default.publisher(for: UIApplication.didEnterBackgroundNotification)
       .sink(receiveValue: { [weak self] _ in
         guard let self = self else { return }
+        // Should set as non cancalbe for browser lock
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Passcode/WindowProtection.swift]: typo: `cancalbe` → `cancellable`

**Review by kylehickinson — APPROVED** [review]

File: Sources/Brave/Frontend/Passcode/WindowProtection.swift (hunk 1 above)
Comment (soner-yuksel) [reply Sources/Brave/Frontend/Passcode/WindowProtection.swift]: Fix at https://github.com/brave/brave-ios/pull/7894/commits/be3a38e534abf7e88f9df520f1935435ad300d57
