### PR TITLE
Fix #1268: Fix YubiKey workflow for fw 5.2.1

### LINKED ISSUE #1268: Fix YubiKey workflow for fw 5.2.1
### Test Plan

Specified here: https://github.com/brave/brave-ios/pull/1295

### PR DESCRIPTION
**Pull request by jumde**
fix https://github.com/brave/brave-ios/issues/1268

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

1. Using the YubiKey with fw 5.2.1, navigate to demo.yubico.com/u2f
2. Complete the registration/login workflow

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 1]
```diff
@@ -95,8 +95,8 @@ class UserScriptManager {
         
         var alteredSource = source
         let token = UserScriptManager.securityToken.uuidString.replacingOccurrences(of: "-", with: "", options: .literal)
-        alteredSource = alteredSource.replacingOccurrences(of: "$<webauthn>", with: "W\(token)", options: .literal)
-        alteredSource = alteredSource.replacingOccurrences(of: "$<u2f>", with: "U\(token)", options: .literal)
+        alteredSource = alteredSource.replacingOccurrences(of: "$<webauthn>", with: "fido2\(token)", options: .literal)
+        alteredSource = alteredSource.replacingOccurrences(of: "$<u2f>", with: "fido\(token)", options: .literal)
```
Comment (jumde) [inline Client/Frontend/Browser/UserScriptManager.swift:99]: Resolving conflicts for replacements.

**Review by kylehickinson — APPROVED** [review]
Not familiar with YubiKey FW but code looks good to me

**Comment by jumde** [comment]
> Not familiar with YubiKey FW but code looks good to me

@kylehickinson - You should get the new key in a few days. @tomlowenthal is working on shipping them.

**Review by danishjafri88 — APPROVED** [review]
