### PR TITLE
Fix #5727: Fix Wallet JS async-await and replyHandler order

### LINKED ISSUE #5727: Unable to join raffles on poap.fun dapp
### Description: 

Report received that the poap.fun dApp doesn’t recognize POAP that connected wallet has. And cannot join raffle even if the wallet has the specific POAP to join the raffle.

More info: https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1658402959515739

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Make Ethereum functions properly async and execute the JS update properties before the `replyHandler`.

This pull request fixes #5727

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Visit `https://poap.fun/`
2. Connect wallet.
3. Should show wallet `address` in the top navigation bar.

## Screenshots:
image

image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift [hunk 1]
```diff
@@ -409,55 +409,65 @@ extension Tab: BraveWalletEventsListener {
...
+      }
+      
+      group.addTask { @MainActor in
+        let coin = await walletService.selectedCoin()
+        let accounts = await keyringService.keyringInfo(coin.keyringId).accountInfos.map(\.address)
+        let selectedAccount = valueOrUndefined(await self.allowedAccounts(coin, accounts: accounts).1.first)
+        await webView.evaluateSafeJavaScript(
+          functionName: "window.ethereum.selectedAddress = \(selectedAccount)",
+          contentWorld: EthereumProviderScriptHandler.scriptSandbox,
+          asFunction: false)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift]: I don't see how this change is necessary: 

1. You don't need a task group for this, and there's no reason to run them concurrently here at all if they're all main actor isolated (only 1 will run at a time anyways)
2. `evaluateSafeJavaScript` is already MainActor isolated, meaning the first 2 tasks don't need MainActor isolation on the task itself
3. The previous code is basically identical (calling `evaluateSafeJavaScript` 3 times without waiting for completion)

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/EthereumProviderScriptHandler.swift [hunk 2]
```diff
@@ -99,13 +99,16 @@ class EthereumProviderScriptHandler: TabContentScript {
...
       updateJSProperties: Bool
     ) {
-      if reject {
-        replyHandler(nil, formedResponse.jsonString)
-      } else {
-        replyHandler(formedResponse.jsonObject, nil)
-      }
-      if updateJSProperties {
-        tab.updateEthereumProperties()
+      Task { @MainActor in
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/EthereumProviderScriptHandler.swift]: If `replyHandler` doesn't need to be executed on main then this is not required

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift (hunk 1 above)
Comment (kylehickinson) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift]: I guess the 1 main difference is this version waits until they all finish technically, if you want this behavior I recommend just awaiting on them all 1-by-1, it would be the same as it currently is

Comment (Brandon-T) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift]: Fixed.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/EthereumProviderScriptHandler.swift (hunk 2 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/EthereumProviderScriptHandler.swift]: Fixed.

**Review by kylehickinson — APPROVED** [review]

**Review by StephenHeaps — APPROVED** [review]
This seems to also resolve https://github.com/brave/brave-ios/issues/5582

**Review by nuo-xu — APPROVED** [review]
