### PR TITLE
Ref #7835, #8494: Fix handling of External URL when in third-party frames but active tab #8495

### LINKED ISSUE #7835: [hackerone] Add `Suppress` button to `Allow link to switch apps?` pop-up
https://hackerone.com/reports/2098015

### LINKED ISSUE #8494: links not opening third party apps when `target=blank/open in new tab`
### Description: 

As originally reported via https://x.com/StrawberrySith/status/1729823719030202673, AppStore links using `target=blank/open in new tab` are not opening/working as expected. Looks like it's generally working now that we've fixed https://github.com/brave/brave-ios/issues/8383.

### Steps to Reproduce 

  1. open https://connect.causality.xyz and attempt tapping/opening the `App Store` link

For context/information can be found via https://x.com/StrawberrySith/status/1729823719030202673 as mentioned above.

### Actual result: 

Tapping on the `App Store` link doesn't do anything.

### Expected result:

Tapping on the `App Store` link should produce the modal re: opening the link in another application (in this case the App Store)

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes

### Device details: 

* `iPhone 11` running `iOS 17.1.1` - **Reproduced**

### Website problems only:
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

To use [canOpenURL(_:)](https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl) an Application must declare the URL schemes you pass to this method by adding the LSApplicationQueriesSchemes key to your app's Info.plist file. This method always returns false for undeclared schemes, whether or not an appropriate app is installed.

We are a browser and we have to handle all schemes. Can Open URL is removed from handle external urls. It was added with https://github.com/brave/brave-ios/pull/8495

This pull request fixes #7835 
This pull request fixes #8494

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Check Test Plan and details for https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl

Additionally open a slack link outside the browser and see it works.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

**Review by StephenHeaps — APPROVED** [review]

File: Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -892,12 +892,8 @@ extension BrowserViewController {
           }
         }
         popup.addButton(title: Strings.openExternalAppURLAllow, type: .primary) { [weak tab] () -> PopupViewDismissType in
-          if UIApplication.shared.canOpenURL(url) {
-            UIApplication.shared.open(url, options: [:]) { didOpen in
-              openedURLCompletionHandler(!didOpen)
-            }
-          } else {
-            openedURLCompletionHandler(true)
+          UIApplication.shared.open(url, options: [:]) { didOpen in
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:895]: @soner-yuksel this should probably be `open(url, options: [.universalLinksOnly: true])`? I guess it doesn't really matter, but it's safer

Comment (kylehickinson) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:895]: This prompt is for external URLs with non-https schemes is it not? Universal links wouldn't be associated with those anyways

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:895]: Yeah they are non-https schemes, next time we make a chanhe here. (I am sure it will happen:)) I will add this with it.
