### PR TITLE
Fix #1986, Fix #1987 - PBO crash and clearing of PBO data from Normal to Private.

### LINKED ISSUE #1986: Browser crash when PBO is enabled from a private tab
### Description: 
Browser crash when PBO is enabled from a private tab. Found while testing #580 

### Steps to Reproduce 
  1. Login to a site in normal tab
  2. Open new private tab
  3. Go to settings and enable PBO, browser crash

**Actual result:** 
Browser crashes
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1574190790408200

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.19.15)

**Device details:** 
iPhone 7+ (iOS 13.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #1987: Session in normal tab is not lost when PBO is enabled and then disabled
### Description: 
Session in normal tab is not lost when PBO is enabled and then disabled. Found while testing #580 

### Steps to Reproduce 
  1. Login to a site in normal tab(I logged into community.brave.com)
  2. Enable PBO from settings, warn message is shown from #580
  3. Close the message and disable PBO to go back to normal tabs
  4. Visit the site from step 1, previous session is restored

**Actual result:** 
Session from normal tab is not lost when PBO is enabled and then disabled

**Expected result:**
Should lose all session as per #580 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.19.15)

**Device details:** 
iPhone 7+ (iOS 13.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Enabling PBO from private tab causes crash captured in #1986

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

- Fix crash in PBO when a zombie tab still has an observer attached to it which gets released in deinit. However, if the tab is loading data while it is being killed (IE: a large PDF, or inbox or webpage), then the observer can trigger `estimatedProgress` or any other keyPath causing a crash because the webView was already killed. Solution is to guard in the observer and let the deinit run its course naturally.

- Fix PBO not clearing data when going from Normal to PBO. Going from PBO to Normal already worked from previous PR. This seems like a regression fix :S Pretty sure I had already done this exact same thing.

This pull request fixes issue #1987 && #1986

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]
Fine with the first part (#1986), I'll let @iccub take a look at the `Clearables` stuff

**Review by iccub — CHANGES_REQUESTED** [review]
It still crashed for me
str:
1. Go to private mode
2. Open settings, enable Private browsing only

Zrzut ekranu 2019-11-20 o 15 37 05

**Comment by Brandon-T** [comment]
> It still crashed for me
> str:
> 
> 1. Go to private mode
> 2. Open settings, enable Private browsing only
> 
> Zrzut ekranu 2019-11-20 o 15 37 05

https://bravesoftware.slack.com/archives/GB9CJGQV6/p1574261904000100?thread_ts=1574194969.003500&cid=GB9CJGQV6

I really can't reproduce it with the code in this PR.. I don't know what's going on here..
Looks more like a race-condition now to me.. somehow collectionView is nil which means either the controller is dead or `viewDidLoad` wasn't called yet and the collectionView is being used..

But I can't get it to reproduce :(

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1121,7 +1121,20 @@ class BrowserViewController: UIViewController {
...
+            return  //False alarm.. the source MUST be a web view.
+        }
+        
+        //WebView is a zombie and somehow still has an observer attached to it
+        guard let tab = tabManager[webView] else {
+            log.error("WebView: \(webView) has been removed from TabManager but still has attached observers")
+            return
+        }
+        
+        //Must handle ALL keypaths
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:1136]: nitpick: please stick to one style for comments, sometimes you add a space after `//` sometimes not :D
we usually add spaces

**Review by iccub — APPROVED** [review]
Seems to be working now, nice job
