### PR TITLE
Fix #4904: MediaSource issue for Playlist on iPad.

### LINKED ISSUE #4904: Playlist Icon missing when loading video [iPad Only]
### Description: 
Playlist Icon missing in address bar when loading videos

**iPhone not impacted**

### Steps to Reproduce 
  1. Open New Tab
  2. Navigate to Video Site (i.e youtube.com, twitch.tv)
  3. From the landing page, click to play a video
  4. Observe the address bar

**Actual result:** 
Playlist Icon missing when playing a video 

https://user-images.githubusercontent.com/17885425/151273111-92445528-9800-4434-933d-a67f0be03be6.MP4

**Expected result:**
Playlist Icon should be displayed in the address bar when loading a video

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Repro rate : 100% on iPad

**Brave Version:** 
Impacted versions:

`1.35 (22.1.21.14)` and newer

Last seen working on `1.35 (22.1.14.22) `

**Device details:** 
Observed on `iPad (7th Gen)` running `iPadOS 15.2.1` using `1.35 (22.1.26.20)`

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
**iPhone not impacted**

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixed MediaSource not accessible by page on iPad

This pull request fixes #4904

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
1. Go to Youtube.com
2. Tap on a video.
3. Expected: Playlist URL Bar button should show if the `MediaSource` playlist setting is turned on. If the setting is off, button will not show.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 1]
```diff
@@ -252,7 +252,7 @@ class UserScriptManager {
         return WKUserScript(source: source,
                             injectionTime: .atDocumentStart,
                             forMainFrameOnly: false,
-                            in: .defaultClient)
+                            in: .page)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/UserScriptManager.swift:255]: Just double checking is there a handler we need to also set as `page` or just the `WKUserScript`?

Comment (Brandon-T) [reply Client/Frontend/Browser/UserScriptManager.swift:255]: We have no handler for this script. Usually it is true that `both` need it, but we're good here :)
It's basically a hack around `MediaSource` so websites can't use `blob:` as the URL for a video.
It doesn't call any handlers :D
```
if (window.MediaSource || window.WebKitMediaSource || window.HTMLMediaElement && HTMLMediaElement.prototype.webkitSourceAddId) {
    
    window.MediaSource = null;
    window.WebKitMediaSource = null;
    //HTMLMediaElement.prototype.webkitSourceAddId = null;
    //window.SourceBuffer = null;
    
    delete window.MediaSource;
    delete window.WebKitMediaSource;
}
```

**Review by kylehickinson — APPROVED** [review]
