### PR TITLE
Fix #5586: Account address on Sign, Encryption requests

### LINKED ISSUE #5586: Dapps: Add account address to Sign requests, Encryption requests
### Description: 

Full address should be visible on the Signature request, Get Public Encryption Key request, and Decrypt request

ref: https://github.com/brave/brave-browser/issues/23651

### Steps to Reproduce 
  1. Visit https://metamask.github.io/test-dapp/
  2. Tap 'Get encryption key'
  3. Observe account name shown, no account address on request modal.
  4. Click 'Provide'
  5. Enter a message in text box below 'Get encryption key' button
  6. Tap 'Encrypt', tap 'Decrypt'
  7. Observe account name shown, no account address on request modal
  8. Reject/approve request
  9. Tap 'Sign' under `Eth Sign` or `Personal Sign`
  10. Observe account name shown, no account address.

**Actual result:** 

get encryption public key | decrypt | sign message
--|--|--

**Expected result:**

Account address is shown, will full address being accessible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Added truncated address below the account name on each of the 3 views (Get Public Encryption Key request / Decrypt request share the same view)

This pull request fixes #5586

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
  1. Visit https://metamask.github.io/test-dapp/
  2. Tap 'Get encryption key'
  3. Observe account address shown below account name. Tap and hold to see context menu with full address.
  4. Click 'Provide'
  5. Enter a message in text box below 'Get encryption key' button
  6. Tap 'Encrypt', tap 'Decrypt'
  7. Observe account address shown below account name. Tap and hold to see context menu with full address.
  8. Reject/approve request
  9. Tap 'Sign' under `Eth Sign` or `Personal Sign`
  10. Observe account address shown below account name. Tap and hold to see context menu with full address.

## Screenshots:
get encryption public key | get encryption public key - address
--|--

decrypt | decrypt - address
--|--

sign message | sign message - address
--|--

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Panels/Encryption/EncryptionView.swift [hunk 1]
```diff
@@ -80,9 +80,16 @@ struct EncryptionView: View {
...
+          AddressView(address: account.address) {
+            VStack(spacing: 4) {
+              Text(account.name)
+                .font(.subheadline.weight(.semibold))
+                .foregroundColor(Color(.braveLabel))
+              Text(account.address.truncatedAddress)
+                .font(.subheadline.weight(.semibold))
+                .foregroundColor(Color(.secondaryBraveLabel))
+            }
+          }
```
Comment (nuo-xu) [inline BraveWallet/Panels/Encryption/EncryptionView.swift:92]: do we want the account name to be included for the context menu?

Comment (StephenHeaps) [reply BraveWallet/Panels/Encryption/EncryptionView.swift:92]: I think it's okay; it gives a bigger area for long press to see the context menu and lets the user see their account name with the associated address. Does it create issues/confusion with the copy menu? It can be just the address if warranted.

Comment (nuo-xu) [reply BraveWallet/Panels/Encryption/EncryptionView.swift:92]: i have no preference. either way is fine. its just some other places only the address has the context menu.

**Review by nuo-xu — APPROVED** [review]
