### PR TITLE
Fixes iPad Keyboard hidden #980 and #1122

### LINKED ISSUE #980: Intermittently bringing brave up from being minimized causes the pin window to show with no number pad.
### Description: 

Hard to reproduce but regularly brave will come up from being minimized with no numberpad showing on the passcode screen.
### Steps to Reproduce 
  1. Use brave.
  2. Minimize it.
  3. Bring it back up via its icon, note that no number pad shows. Only way to correct is force quit brave.

**Actual result:** 
1410A816-4412-4A85-A73E-510D12722DB1

**Expected result:**

Expect number pad to come up when passcode window comes up.
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent. Can not reliably reproduce but it does happen regularly.

**Brave Version:** 
1.8

**Device details:** 
iPhone 12.1.4

### PR DESCRIPTION
**Pull request by Brandon-T**
Added ability to bring the keyboard back into focus upon tapping the passcode pane.
Fixing Passcode keyboard being hidden.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift [hunk 1]
```diff
@@ -25,6 +25,9 @@ class PasscodeEntryViewController: BasePasscodeViewController {
         passcodePane = PasscodePane(title: nil, passcodeSize: authInfo?.passcode?.count ?? 6)
 
         super.init()
+        
+        passcodePane.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(passcodeCheckSetup)))
+        passcodePane.isUserInteractionEnabled = true
```
Comment (kylehickinson) [inline Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift:30]: This is probably fine, but do want to add some sort of label where the keyboard is supposed to overlap that says like "Tap to enter passcode" or something (so its more obvious).

Also, if we're going to add a tap gesture to the passcode pane, we will want to make it accessible (accessible label + maybe accessibility traits?)

Comment (jhreis) [reply Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift:30]: I think the label is unneeded. This is a pretty weird edge case and if the user ends up in it, clicking the buttons seems obvious (to me).

The second point is definitely valid. @Brandon-T can you add an accessibility label to this Pane?

Comment (Brandon-T) [reply Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift:30]: Added accessibility to the passcode pane.

**Review by jhreis — APPROVED** [review]

**Review by jhreis — CHANGES_REQUESTED** [review]
Modify string property to have `accessibility` in it for clarity, that it isn't "visible"

**Review by kylehickinson — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
