### PR TITLE
Fix #5405: Add origin w/ bolded eTLD+1 to Transaction Confirmation

### LINKED ISSUE #5405: Display origin w/ bolded eTLD+1 on transaction confirmations
### Description: 
We should use the OriginInfo property on a transaction to display the origin w/ bolded eTLD+1 on the transaction confirmation view

Screen Shot 2022-05-27 at 5 10 00 PM

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Transactions created within the wallet appear to have the URLOrigin `chrome://wallet/`. We should display 'Brave Wallet' for this case.

In some instances we may want to display the favicon, for Brave Wallet origin we should use the Brave logo:
Screen Shot 2022-05-27 at 5 18 40 PM

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- Display origin w/ bolded eTLD+1 on Transaction Confirmation View. ERC20 Approval will also show the favicon.
- For brave wallet origin, we display 'Brave Wallet' with brave logo (when showing favicon)

This pull request fixes #5405 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Brave Wallet ERC20 approve transaction:
1. Open & unlock wallet
2. Switch to Ropsten network
3. If you have 0 DAI, swap some ETH to DAI
4. Open swap panel and try to swap DAI to ETH. Swap button should show 'Activate Token DAI' if you have never swapped DAI before. Tap it.
5. Verify transaction shows brave logo + 'Brave Wallet' origin

Brave Wallet transaction:
1. Create a send/swap transaction within Brave Wallet
2. Verify transaction confirmation displays 'Brave Wallet' as origin

Dapp ERC20 approve transaction:
1. Open [Uniswap](https://app.uniswap.org/)
2. Change to swap from DAI to ETH (assuming never swapped DAI on Uniswap before, otherwise try another token)
3. Tap 'Allow the Uniswap Protocol to use your DAI'
4. Tap wallet notification
5. Verify transaction confirmation displays Uniswap favicon and the origin is displayed with a bolded eTLD+1

Dapp transaction:
1. Open [Uniswap](https://app.uniswap.org/)
6. Select DAI as the to token
7. Enter value in from field for ETH
8. Tap 'Swap' and then 'Confirm Swap'
9. Tap Wallet notification banner to open panel & transaction confirmation
10. Verify origin is displayed with a bolded eTLD+1

## Screenshots:

brave wallet - erc20 approve | brave wallet - swap | unswap - erc20 approve | uniswap - swap
--|--|--|--

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by nuo-xu — APPROVED** [review]

File: BraveWallet/Crypto/OriginText.swift [hunk 1]
```diff
@@ -5,22 +5,27 @@
 
 import BraveCore
 import SwiftUI
+import struct Shared.Strings
```
Comment (kylehickinson) [inline BraveWallet/Crypto/OriginText.swift]: Don't need to import Shared anymore post-SPM (`import Strings` should be enough)
