### PR TITLE
Fix #5827: Fix Swap is available after user creates first solana account

### LINKED ISSUE #5827: Disable Swap option for Solana accounts
### Description: 
Disable Swap option for Solana accounts

### Steps to Reproduce 
  1. Create a new wallet on iOS 16 deivce
  2. Create a new Solana account
  3. Go to accounts tab and click on action button, Shows both Send and Swap options for Solana account

**Actual result:** 
Swap option is shown for Solana accounts immediately after its created

**Expected result:**
Disable Swap option for Solana accounts

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy. Only shows after account is created. But once wallet is locked doesn't repro

**Brave Version:** 
1.42 (22.8.8.19)

**Device details:** 
iPad Pro (iOS 16 Beta 3)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### PR DESCRIPTION
**Pull request by nuo-xu**
This pull request fixes #5827

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:
1. make sure you dont have a solana account
2. go to wallet make sure you are on a network that support swap (e.x ETH)
3. create your first solana account
4. after you create solana account check if swap is still available 

Note: For verifying this on a local build please make sure you are on top of `release` branch.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/NetworkStore.swift [hunk 1]
```diff
@@ -55,7 +55,11 @@ public class NetworkStore: ObservableObject {
       // we don't need to call `setNetwork` on JsonRpcService
       self.selectedChainId = chain.chainId
       // update `isSwapSupported` for Buy/Send/Swap panel
-      self.isSwapSupported = await swapService.isSwapSupported(chain.chainId)
+      if chain.coin == .eth {
```
Comment (StephenHeaps) [inline BraveWallet/Crypto/Stores/NetworkStore.swift:58]: I think we need this check in `SwapTokenStore` too for when `isSwapSupported` returns true for Solana in v1.43 of Brave Core?

**Review by StephenHeaps — APPROVED** [review]

File: BraveWallet/Crypto/Stores/NetworkStore.swift (hunk 1 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/NetworkStore.swift:58]: inside `SwapTokenStore` is using `NetworkStore.isSwapSupported` which is always updated with the logic of checking network coin type.
