### PR TITLE
Fix ##6687: Don't show sms/tel dialog for non-active tabs

### LINKED ISSUE #6687: [hackerone] don't show `sms/tel` dialog for non-active tabs
https://hackerone.com/reports/1819652

### PR DESCRIPTION
**Pull request by soner-yuksel**
Adding active tab url check for tel / sms and changing the alert description

## Summary of Changes

This pull request fixes #6687

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Test 1: 

* Visit hxxps://csrf.jp/brave/sms.php
* Tap "Click Me" button
* [google.com](http://google.com/) is opened in the new tab
* Confirmation dialog for sms: link should not be shown on [google.com](http://google.com/)

Test 2: 

* Visit a website with a call to action like a business on [google](https://www.google.com/search?q=carpet&source=hp&ei=cOy1Y9qyEeXQkPIP64SFuAU&oq=carpet&gs_lcp=ChFtb2JpbGUtZ3dzLXdpei1ocBADMggIABCABBCxAzILCAAQgAQQsQMQgwEyBQgAEIAEMgUIABCABDILCC4QgAQQsQMQ1AIyBAgAEAMyCAgAEIAEEMkDMgUIABCSAzoOCAAQjwEQ6gIQjAMQ5QI6EQguEIAEELEDEIMBEMcBENEDOgsILhCABBCxAxCDAToICAAQsQMQgwE6DgguEIAEELEDEIMBENQCOggILhCABBDUAjoUCC4QgAQQsQMQgwEQxwEQ0QMQ1AI6DgguEIAEELEDEMcBENEDOgsIABCABBDJAxCLAzoICAAQkgMQiwM6DgguELEDEIMBEMcBENEDOgsILhCABBDHARDRAzoOCC4QgwEQ1AIQsQMQgAQ6EQguEIAEELEDEIMBEMcBEK8BOg4ILhCABBDJAxDHARCvAToICC4QgAQQsQM6CAguELEDEIMBUIkSWMhlYJlsaAhwAHgAgAGVAYgBowuSAQM0LjmYAQCgAQGwAQ-4AQI&sclient=mobile-gws-wiz-hp&dlnr=1&sei=hOy1Y-F-5KWq2w_mx6DIBQ#dlnr=1&trex=m_t:lcl_akp,rc_f:rln,rc_ludocids:15437203984229734589,ru_gwp:0%252C7,ru_lqi:CgZjYXJwZXQxfRUaAAAAAABIh87qoeeAgIAIWhIQABgAIgZjYXJwZXQqBAgDEACSAQ5mbG9vcmluZ19zdG9yZZoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VSWE9YWkxSSFZSUlJBQqoBDhABKgoiBmNhcnBldCgA,ru_phdesc:M3Ayh4oddxI,trex_id:N7qfbb&lpg=cid:CgIgAQ%3D%3D) 

* Press call button
* Check new dialog includes website

## Screenshots:

yuttree1-11_1

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 1]
```diff
@@ -54,16 +54,26 @@ extension BrowserViewController {
...
     }
     
+    var alertDetails = String(format: Strings.openExternalAppURLMessage, url.relativeString)
+    
     // We do not want certain schemes to be opened externally when called from subframes.
-    if ["tel", "sms"].contains(url.scheme) && !isMainFrame {
-      return
+    // And tel / sms dialog should not be shown for non-active tabs #6687
+    if ["tel", "sms"].contains(url.scheme) {
+      if !isMainFrame || tab?.url?.host != topToolbar.currentURL?.host {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:62]: Do we have to compare `host` instead of entire url? what if user has two xxx.com tabs, one of which is not active?

Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:62]: No we should not, here we are checking if the website is trying to do some trickery like doing a redirection to a totally new domain. User can have multiple tabs for xxx.com for instance this doesnt change the fact we are comparing tab url host with omnibox url host.

Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:62]: thanks for explaining

**Review by iccub — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]

File: Sources/BraveShared/BraveStrings.swift [hunk 2]
```diff
@@ -1092,6 +1092,7 @@ extension Strings {
   public static let shareWithMenuItem = NSLocalizedString("ShareWithMenuItem", tableName: "BraveShared", bundle: .module, value: "Share with...", comment: "Title for sharing url menu item")
   public static let openExternalAppURLTitle = NSLocalizedString("ExternalAppURLAlertTitle", tableName: "BraveShared", bundle: .module, value: "Allow link to switch apps?", comment: "Allow link to switch apps?")
   public static let openExternalAppURLMessage = NSLocalizedString("ExternalAppURLAlertMessage", tableName: "BraveShared", bundle: .module, value: "%@ will launch an external application", comment: "%@ will launch an external application")
+  public static let openExternalAppURLHost = NSLocalizedString("openExternalAppURLHost", tableName: "BraveShared", bundle: .module, value: "%@ says:", comment: "This will be used to indicate which website is calling the action. %s will replace the name of the website for instance: 'google.com says:'")
```
Comment (stoletheminerals) [inline Sources/BraveShared/BraveStrings.swift:1096]: Instead of `%@ says:` in the message body I think it's better to move the website name to the `openExternalAppURLTitle` variable, so it would say `Allow %@ to switch apps?`. What do you think @soner-yuksel ?

Comment (soner-yuksel) [reply Sources/BraveShared/BraveStrings.swift:1096]: Great idea. Fix at https://github.com/brave/brave-ios/pull/6704/commits/09b557867514bbac486f6986add5ab644c3c4b30

**Review by stoletheminerals — APPROVED** [review]
