### PR TITLE
Fix #5374: Add async request blocking via webkit message handlers

### LINKED ISSUE #5374: Block bad window.fetch() messages using the Rust engine
### Description: 
Block certain `window.fetch()` api calls by connecting to the rust engine asynchronously using apples built in javascript to swift mechanism `WKUserContentController`

### Test plan
1. You may test by building the debug version of the application and seeing if no javascript errors are thrown on the injected scripts.
2. Go to a few sites with known trackers and test that nothing is broken. (YouTube, Facebook, instagram, etc)

#### Test 2:
1. Switch languages to something that uses regional lists. (ex switch phone to the polish)
2. Go to twitter and make sure the login works

#### Test 3:
1. Go to  https://openocean.finance/ and make sure the page loads (should ideally run the application on debug mode to ensure no asserts are triggered)

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #5374 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

This is a tricky to test feature:
1. You may test by building the debug version of the application and seeing if no javascript errors are thrown on the injected scripts.
2. Go to a few sites with known trackers and test that nothing is broken. (YouTube, Facebook, instagram, etc)3. 

Test 2:
1. Switch languages to something that uses regional lists. (ex switch phone to the polish)
2. Go to twitter and make sure the login works

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)` - test for performance degradation
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/WebFilters/AdblockRustEngine.swift [hunk 1]
```diff
@@ -7,6 +7,29 @@ import Foundation
...
 extension AdblockEngine {
+  public enum ResourceType: String {
+    case script, xhr
+  }
+  
+  /// Check the rust engine if the request should be blocked given the `sourceURL` and `resourceType`.
+  ///
+  /// - Warning: You must provide a absolute URL (i.e. containing a host) fo r `requestURL` and `sourceURL`
+  public func shouldBlock(requestURL: URL, sourceURL: URL, resourceType: ResourceType) -> Bool {
+    let isThirdParty = requestURL.baseDomain != sourceURL.baseDomain
```
Comment (pes10k) [inline Client/WebFilters/AdblockRustEngine.swift:20]: if `baseDomain` is eTLD+1, please leave a comment saying so, bc otherwise this will look like an origin check to readers and seem very wrong :)

File: Client/WebFilters/AdblockRustEngine.swift [hunk 2]
```diff
@@ -7,6 +7,29 @@ import Foundation
...
+    
+    guard let requestHost = requestURL.host, let sourceHost = sourceURL.host else {
+      return false
```
Comment (pes10k) [inline Client/WebFilters/AdblockRustEngine.swift:29]: weren't you going to assert here?

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+    //[DEBUG]console.log(`[RB] URL: '${url}'`)
+    
+    const originalSend = this.send
+    this.send = function() {
+      sendMessage(url, 'xhr').then(blocked => {
+        this._blocked = blocked
+
+        if (blocked) {
+          //[DEBUG]console.log('[RB] BLOCKED: ' + url)
+          this.onerror(Error(`Content blocked for ${url}`))
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: you should check that `onerror` is set.  You also should not call `Error` but create something like `new ProgressEvent('error')`

You also should handle traditional event handers.

So. instead of `this.onerror(Error...`, you should do `this.dispatchEvent(new ProgressEvent('error'))`

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+  }
+  
+  const originalOpen = XMLHttpRequest.prototype.open
+  XMLHttpRequest.prototype.open = function() {
+    const sendArguments = arguments
+    originalOpen.apply(this, arguments)
+
+    // Extract the url string
+    let urlString = arguments[1]
+    if (!(typeof urlString === 'string' || urlString instanceof String)) {
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: why the typechecking here?  What else are you expecting than a string?  And why check for string twice?

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+
+    let isAsync = arguments[2]
+    if (isAsync !== undefined && !isAsync) {
+      // We can't handle non-async requests as they are not handled via callbacks
+      return
+    }
+
+    // Resolve the url in case it's a relative path
+    const url = makeURLFromString(urlString)
+    if (url === undefined) { return }
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: why return `undefined`?  This seems like invalid input.  `throw`ing seems right here, instead of silent failure

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+      //[DEBUG]console.log('[RB] Cannot extract url')
+      return originalFetch.apply(this, arguments)
+    }
+
+    // Resolve the url in case it's a relative path
+    const url = makeURLFromString(urlString)
+    if (url === undefined) { return }
+    //[DEBUG]console.log(`[RB] URL: '${url}'`)
+    
+    return sendMessage(url, 'script').then(blocked => {
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: why `script`?  This should be `fetch` no?

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 7]
```diff
@@ -0,0 +1,100 @@
+// Copyright 2022 The Brave Authors. All rights reserved.
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+((args) => {
+  "use strict";
+  //[DEBUG]console.log('[RB] Loaded request blocking')
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: please remove debugging code

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+    }
+  }
+  
+  const { fetch: originalFetch } = window
+  window.fetch = function() {
+    const [resource, config] = arguments
+    
+    // Extract the url string
+    let urlString
+    if (typeof resource === 'string' || resource instanceof String) {
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: Same question here, why all the type checking for all these values?  Why the uncertainty about data types?

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+      // Simple send where resource is a string
+      urlString = resource
+    } else if (resource !== undefined && (typeof resource.url === 'string' || resource.url instanceof String)) {
+      // Assume its a Request
+      urlString = resource.url
+    } else {
+      //[DEBUG]console.log('[RB] Cannot extract url')
+      return originalFetch.apply(this, arguments)
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js:34]: Under what circumstances would this happen?

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js (hunk 6 above)
Comment (pes10k) [reply Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: my error, should be `xmlhttprequest`

Comment (pes10k) [reply Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: https://help.eyeo.com/en/adblockplus/how-to-write-filters#options

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 10]
```diff
@@ -0,0 +1,75 @@
...
+      } else {
+        return originalFetch.apply(this, arguments)
+      }
+    })
+  }
+  
+  const originalOpen = XMLHttpRequest.prototype.open
+  XMLHttpRequest.prototype.open = function() {
+    const sendArguments = arguments
+    originalOpen.apply(this, arguments)
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: Note that the return value here is needed. https://developer.mozilla.org/en-US/docs/Web/API/Window/open#return_value

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+
+    // Extract the url string
+    let urlString = arguments[1]
+    let isAsync = arguments[2]
+    if (isAsync !== undefined && !isAsync) {
+      // We can't handle non-async requests as they are not handled via callbacks
+      return
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: Assert?  I dont think there are any cases where window.open returns undefined

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 12]
```diff
@@ -0,0 +1,75 @@
...
+    const url = new URL(urlString, window.location.href)
+    const originalSend = this.send
+    this.send = function() {
+      sendMessage(url).then(blocked => {
+        this._blocked = blocked
+
+        if (blocked) {
+          this.dispatchEvent(new ProgressEvent('error'))
+        } else {
+          originalSend.apply(this, arguments)
```
Comment (pes10k) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js]: This value too needs be returned to the original caller 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#return_value

File: Client/WebFilters/CosmeticFiltersResourceDownloader.swift [hunk 13]
```diff
@@ -308,8 +308,6 @@ public class CosmeticFiltersResourceDownloader {
           into: engine,
           data: $0.resource.data,
           id: $0.type.identifier)
-      case .tgz:
```
Comment (thypon) [inline Client/WebFilters/CosmeticFiltersResourceDownloader.swift:311]: Is the desktop version supporting `.tgz` compressed files for cosmetic filters and rules?

File: Client/WebFilters/AdblockerType.swift [hunk 14]
```diff
@@ -8,56 +8,55 @@ import Shared
...
-    default: return nil
-    }
-  }
-
   var associatedFiles: [FileType] { return [.json, fileForStatsLibrary] }
 
   private var fileForStatsLibrary: FileType {
     switch self {
     case .general, .regional: return .dat
-    case .httpse: return .tgz
```
Comment (thypon) [inline Client/WebFilters/AdblockerType.swift:31]: here, too. Is it HTTPSEverywhere right? Is it dropped?

File: Client/WebFilters/AdblockResourceDownloader.swift [hunk 15]
```diff
@@ -25,7 +25,15 @@ public class AdblockResourceDownloader {
...
   private let servicesKeyHeaderValue = "BraveServiceKey"
 
-  static let endpoint = "https://adblock-data.s3.brave.com/ios"
+  /// The base s3 environment url that hosts the debouncing (and other) files.
+  /// Cannot be used as-is and must be combined with a path
+  private lazy var baseResourceURL: URL = {
+    if AppConstants.buildChannel.isPublic {
+      return URL(string: "https://adblock-data.s3.brave.com")!
+    } else {
+      return URL(string: "https://adblock-data-staging.s3.bravesoftware.com")!
```
Comment (thypon) [inline Client/WebFilters/AdblockResourceDownloader.swift:34]: Isn't this string gonna be embed in the production build here?

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 16]
```diff
@@ -0,0 +1,77 @@
+// Copyright 2022 The Brave Authors. All rights reserved.
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+window.braveBlockRequests = (args) => {
+  "use strict";
+  const securityToken = args.securityToken
```
Comment (thypon) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js:9]: pls include `;`. Javascript parser is not too eager of missing `;`.

https://doc.casthighlight.com/alt_missingsemicolon-always-use-semicolons/

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 17]
```diff
@@ -0,0 +1,77 @@
...
+      securityToken: securityToken,
+      resourceURL: resourceURL.href,
+      sourceURL: window.location.href,
+      resourceType: 'xmlhttprequest'
+    })
+  }
+  
+  const { fetch: originalFetch } = window
+  window.fetch = function() {
+    const [resource] = arguments
```
Comment (thypon) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js:23]: here too, missing semicolon

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 18]
```diff
@@ -0,0 +1,77 @@
...
+    
+    // Extract the url
+    let urlString
```
Comment (thypon) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js:26]: and here

**Review by thypon — APPROVED** [review]

File: Client/WebFilters/AdblockerType.swift (hunk 14 above)
Comment (iccub) [reply Client/WebFilters/AdblockerType.swift:31]: this endpoint was never used for HTTPSE, we use a static list on iOS 14, and on iOS 15 we use Apple's built in httpse

File: Client/Frontend/Browser/User Scripts/UserScriptHelper.swift [hunk 19]
```diff
@@ -83,4 +83,14 @@ class UserScriptHelper {
...
   }
+
+  static func makeRequestBlockingParams(securityToken: String) throws -> String {
+    let params: [String: String] = [
+      "securityToken": securityToken,
+      "handlerName": RequestBlockingContentHelper.scriptMessageHandlerName()
+    ]
+    let encoder = JSONEncoder()
+    let data = try encoder.encode(params)
+    return String(data: data, encoding: .utf8)!
```
Comment (iccub) [inline Client/Frontend/Browser/User Scripts/UserScriptHelper.swift]: Better to unwrap it and do not continue if this function returns nil

File: Client/WebFilters/ShieldStats/Adblock/FifoDict.swift [hunk 20]
```diff
@@ -3,13 +3,13 @@
 
 import Foundation
 
-class FifoDict {
+class FifoDict<Element> {
```
Comment (iccub) [inline Client/WebFilters/ShieldStats/Adblock/FifoDict.swift:6]: nice generics improvement

**Review by iccub — CHANGES_REQUESTED** [review]

File: Client/Frontend/UserContent/UserScripts/RequestBlocking.js [hunk 21]
```diff
@@ -0,0 +1,84 @@
...
+  const originalSend = XMLHttpRequest.prototype.send
+  XMLHttpRequest.prototype.send = function () {
+    if (this._resourceURL === undefined) {
+      return originalSend.apply(this, arguments)
+    }
+    
+    sendMessage(this._resourceURL).then(blocked => {
+      if (blocked) {
+        Object.defineProperties(this, {
+          readyState: { value: 4 }
```
Comment (Brandon-T) [inline Client/Frontend/UserContent/UserScripts/RequestBlocking.js:73]: Why do we define this property on the promise or the send function (not sure which `this` it applies to)?

File: Client/WebFilters/AdblockResourceDownloader.swift [hunk 22]
```diff
@@ -102,22 +110,19 @@ public class AdblockResourceDownloader {
...
-        var url = URL(string: AdblockResourceDownloader.endpoint)
-      else {
+      guard let resourcePath = type.resourcePath(for: fileType) else {
         return nil
       }
 
-      url.appendPathComponent(resourceName)
-      url.appendPathExtension(fileExtension)
-
+      let url = URL(string: resourcePath, relativeTo: baseResourceURL)!
```
Comment (Brandon-T) [inline Client/WebFilters/AdblockResourceDownloader.swift]: Guard here instead of force unwrapping.

File: Client/WebFilters/ContentBlocker/RequestBlockingContentHelper.swift [hunk 23]
```diff
@@ -0,0 +1,86 @@
...
+    struct RequestBlockingDTOData: Decodable, Hashable {
+      enum CodingKeys: String, CodingKey {
+        case resourceURL, sourceURL, resourceType
+      }
+      
+      let resourceType: AdblockEngine.ResourceType
+      let resourceURL: URL
+      let sourceURL: URL
+      
+      init(from decoder: Decoder) throws {
```
Comment (Brandon-T) [inline Client/WebFilters/ContentBlocker/RequestBlockingContentHelper.swift]: This method can be removed entirely if `AdblockEngine.ResourceType` is codable.

File: Client/WebFilters/ContentBlocker/RequestBlockingContentHelper.swift [hunk 24]
```diff
@@ -0,0 +1,86 @@
...
+        let container = try decoder.container(keyedBy: CodingKeys.self)
+        let resourceURLString = try container.decode(String.self, forKey: .resourceURL)
+        let sourceURLString = try container.decode(String.self, forKey: .sourceURL)
+        let resourceTypeString = try container.decode(String.self, forKey: .resourceType)
```
Comment (Brandon-T) [inline Client/WebFilters/ContentBlocker/RequestBlockingContentHelper.swift]: There is no need to decode as a string first, then create a `URL` from it.
You can do: `resourceURL = try container.decode(URL.self, forKey: .resourceURL)` for example.
It will decode `URL` which is `Codable` :)
This way, you can get rid of all the `DecodingError.dataCorrupted` stuff.

```swift
import Foundation

let json = """
{
  "url": "https://google.ca"
}
"""

struct Foo: Codable {
  let url: URL
}

let data = json.data(using: .utf8)!
let foo = try JSONDecoder().decode(Foo.self, from: data)

print(foo.url)
```

If you want to test in a playground.

File: Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift [hunk 25]
```diff
@@ -37,6 +37,40 @@ public class AdBlockStats: LocalAdblockResourceProtocol {
     parseBundledGeneralBlocklist()
     loadDownloadedDatFiles()
   }
+  
+  /// Checks the general and regional engines to see if the request should be blocked.
+  ///
+  /// - Note: This method is should not be synced on `AdBlockStatus.adblockSerialQueue` and the result is synced on the main thread.
+  func shouldBlock(requestURL: URL, sourceURL: URL, resourceType: AdblockEngine.ResourceType, callback: @escaping (Bool) -> Void) {
+    Self.adblockSerialQueue.async { [weak self] in
+      let shouldBlock = self?.shouldBlock(requestURL: requestURL, sourceURL: sourceURL, resourceType: resourceType)
```
Comment (Brandon-T) [inline Client/WebFilters/ShieldStats/Adblock/AdBlockStats.swift]: `let shouldBlock = self?.shouldBlock(....) == true`
This way you don't have to unwrap `?? false`

Same for all the calls to `regionalAdblockEngine?.shouldBlock`

**Review by Brandon-T — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
