### PR TITLE
Fix: 3480 / 3476 / 3475: Bug Bash related with Social Media Sharing and pop-overs

### LINKED ISSUE #3475: Share button is not visible on social media share button
### Description: 
Share button is not visible on social media share button

### Steps to Reproduce 
  1. Set locale to Japan
  2. Follow test plan from #3387
  3. Trigger tooltip, share button is not visible

**Actual result:** 

**Expected result:**
Should be visible 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy but need patience to trigger the message

**Brave Version:** 
1.24(21.3.25.18)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### LINKED ISSUE #3476: Social media share message isn't translated
### Description: 
Social media share message isn't translated

### Steps to Reproduce 
  1. Set locale to Japenese
  2. Trigger tooltip using test plan from https://github.com/brave/brave-ios/pull/3387
  3. Click on share button and open any app to share
  4. Share message is not translated

**Actual result:** 

**Expected result:**
Should be translated to device locale

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.25.18)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### LINKED ISSUE #3480: Subtitles showing always First Tier description for every pop-over
Description:
The description inside Benchmark Tier always show same message.

### Steps to Reproduce 
  1. Follow test plan from #3387
  2. Trigger tooltip for 2nd / 3rd Tier etc.
  3. Description always "Congratulations. You're pretty special" 
  
**Actual result:**

IMG_6537

**Expected result:**
Show designated description for every Tier.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced,

**Brave Version:** 
1.24(21.3.25.18)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N_A
- did you check in Safari/Firefox (WkWebView-based browsers)? N_A

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This pull request fixes #3475
This pull request fixes #3476
This pull request fixes #3480

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Same Plans in the tickets

## Screenshots:

IMG_67591 11

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Widgets/InsetButton.swift [hunk 1]
```diff
@@ -13,14 +13,17 @@ class InsetButton: UIButton {
     }
     
     func addTrailingImageIcon(image: UIImage, offset: CGFloat = 15) {
-        let imageView = UIImageView(image: image)
-        imageView.translatesAutoresizingMaskIntoConstraints = false
+        let imageView = UIImageView(image: image).then {
+            $0.translatesAutoresizingMaskIntoConstraints = false
```
Comment (Brandon-T) [inline Client/Frontend/Widgets/InsetButton.swift:17]: Are these necessary? It is using manual constraints or `SnapKit`?

**Review by Brandon-T — APPROVED** [review]

**Review by iccub — APPROVED** [review]
