### PR TITLE
Fix #6608 & 6609: only erc721 nft opens new NFT detail screen.

### LINKED ISSUE #6608: Solana NFT shows Token standard as ERC721
### Description: 
Solana NFT shows Token standard as ERC721 

### Steps to Reproduce 
  1. Add a Solana NFT to potfolio
  2. Open NFT details screen
  3. Token standard shows as ERC721 instead of SPL Token

**Actual result:** 

**Expected result:**
Should be SPL Token

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46 (22.12.7.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
only ERC721 token will open up to the new NFT detail screen. 
any other NFT will open old asset detail screen with no price and image (same behaviour as in 1.45.2)
also fetch network info regardless nft has metadata or not

This pull request fixes #6608 #6609

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:
please refer to the issues.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift [hunk 1]
```diff
@@ -65,14 +65,18 @@ class NFTDetailStore: ObservableObject {
     self.erc721Metadata = erc721Metadata
   }
   
-  func fetchMetadata() {
+  func fetchNetworkInfo() {
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift]: Any reason to have these separate instead of a single `update()` function like other stores? We could still only fetch metadata if `erc721Metadata` is nil in the `update()` function.

Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift]: sure. will aggregate them into one single func.

Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Stores/NFTDetailStore.swift]: fixed in [314a66d](https://github.com/brave/brave-ios/pull/6617/commits/314a66d4e9565c4ac7944b0d72bf9e06aa5a5cd4)

**Review by StephenHeaps — APPROVED** [review]
