### PR TITLE
Fix #7897: Clearing Out Data From Recently Closed Tabs

### LINKED ISSUE #7897: "Reopen Last Closed Tab" is shown when no recently closed tabs are there
### Description: 

`Reopen Last Closed Tab` is shown when no recently closed tabs are there. Need to relaunch Brave to hide that option.

### Steps to Reproduce 
  1. Fresh launch Brave
  2. Tap and hold `Tabs switch button` >Tap `View Recently Closed Tabs` > Confirm there are no tabs shown > Done
  3. Open one tab > Now close that tab
  4. Tap and hold `Tabs switch button` again > Confirm that `Reopen Last Closed Tab` is shown now
  5. Tap `View Recently Closed Tabs` > Clear the list
  6. Tap and hold `Tabs switch button` > Observe that `Reopen Last Closed Tab` is still shown even when `Recently Closed Tabs` list is empty

### Actual result: 

`Reopen Last Closed Tab` is shown and it's possible to open a recently closed tab even when `Recently Closed Tabs` list is empty. This is true until you relaunch Brave.

https://github.com/brave/brave-ios/assets/128532965/0568097c-5d8c-491f-b5bf-bdd9fc346f73

### Expected result:

`Reopen Last Closed Tab` must not be shown when `Recently Closed Tabs` list is empty.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.57 (23.8.16.21)
BraveCore: 1.57.47 (116.0.5845.96)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 16.6]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by JonKaleidoscope**
## Summary of Changes

This pull request fixes #7897. When clearing recently closed tabs, data was being persisted. 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/Tabs/RecentlyClosedTabs/RecentlyClosedTabsView.swift [hunk 1]
```diff
@@ -30,13 +31,14 @@ struct RecentlyClosedTabsView: View {
...
     .actionSheet(isPresented: $showClearDataPrompt) {
       .init(title: Text(Strings.RecentlyClosed.recentlyClosedClearActionConfirmation),
-        buttons: [
-          .destructive(Text(Strings.RecentlyClosed.recentlyClosedClearActionTitle), action: {
-            RecentlyClosed.removeAll()
-            dismissView()
-          }),
-          .cancel()
-        ]
+            buttons: [
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Browser/Tabs/RecentlyClosedTabs/RecentlyClosedTabsView.swift:34]: Can you fix the indentation here? we use 2 space indentation.

**Review by soner-yuksel — COMMENTED** [review]
Thanks for the contribution, this is a nice simple way to solve this problem. Please make this small change mentioned https://github.com/brave/brave-ios/pull/7919#discussion_r1303089842 so I can approve and we can merge.

File: Sources/Brave/Frontend/Browser/Tabs/RecentlyClosedTabs/RecentlyClosedTabsView.swift (hunk 1 above)
Comment (JonKaleidoscope) [reply Sources/Brave/Frontend/Browser/Tabs/RecentlyClosedTabs/RecentlyClosedTabsView.swift:34]: @soner-yuksel 
I believe this re-indentation is correct but looks funny in the diff. The reason there is a change is because Xcode indentation is trying to line up the function parameters for the `init` which are `title` and `buttons`. Before these where not lined up. If you want these to be indented automatically on new line, I would need drop `title` parameter to a new line. Is that preferred?

(1) Current:
Screenshot 2023-08-23 at 10 29 56 AM

Alternative:
Screenshot 2023-08-23 at 10 33 26 AM

Comment (soner-yuksel) [reply Sources/Brave/Frontend/Browser/Tabs/RecentlyClosedTabs/RecentlyClosedTabsView.swift:34]: Oh I didnt recognize it, yeah looks ok.

**Review by soner-yuksel — APPROVED** [review]
Good work, thanks again @JonKaleidoscope
