### PR TITLE
Fix #467, dau first ping param conversion.

### LINKED ISSUE #467: DAU ping after upgrade is treated as first ping
### Steps to Reproduce 
  1. Install brave1.6.6 launch the app, wait few second so DAU ping happens
  2. Upgrade to 1.7
  3. Launch and run the app for 15 seconds so the DAU ping is sent

Second DAU ping on 1.7 is sent with `first=true` parameter set.

On 1.7 we introduced new preference `firstPingParam` which needs to be set up during migration process

### PR DESCRIPTION
**Pull request by iccub**
On old codebase we checked existence of `dau_stat` to determine whether it's first server ping.
We need to translate that to use the new `firstPingParam` preference.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: BraveShared/Preferences.swift [hunk 1]
```diff
@@ -147,6 +147,11 @@ extension Preferences {
     public class func migrateBraveShared(keyPrefix: String) {
         // DAU
         migrate(keyPrefix: keyPrefix, key: "dau_stat", to: Preferences.DAU.lastLaunchInfo)
+        // On old codebase we checked existence of `dau_stat` to determine whether it's first server ping.
+        // We need to translate that to use the new `firstPingParam` preference.
+        if Preferences.DAU.lastLaunchInfo.value != nil {
```
Comment (jhreis) [inline BraveShared/Preferences.swift]: Just place this logic when setting the `default` on `firstPingParam`:

```
static let firstPingParam = Option<Bool>(key: "dau.first-ping", default: Preferences.DAU.lastLaunchInfo.value == nil)
```

**Review by jhreis — CHANGES_REQUESTED** [review]

File: BraveShared/Preferences.swift [hunk 2]
```diff
@@ -29,7 +29,17 @@ extension Preferences {
     final class DAU {
         static let lastLaunchInfo = Option<[Int?]?>(key: "dau.last-launch-info", default: nil)
         static let weekOfInstallation = Option<String?>(key: "dau.week-of-installation", default: nil)
-        static let firstPingParam = Option<Bool>(key: "dau.first-ping", default: true)
+        static let firstPingParam: Option<Bool> = {
```
Comment (jhreis) [inline BraveShared/Preferences.swift]: We can literally just set the `defaultValue` inline:

(key: "", default: Preferences.DAU.lastLaunchInfo.value == nil`)

This then would set `default` to the correct value.

**Review by jhreis — CHANGES_REQUESTED** [review]

**Review by jhreis — APPROVED** [review]
