### PR TITLE
Fix #5027: Slow portfolio balance calls can show balance incorrectly

### LINKED ISSUE #5027: Slow portfolio balance calls can cause balance to show incorrectly
If you switch to the same network multiple times (which will cause balance calls to execute) there is a chance for the balance calls to double-up as the assets for that network will be the same.  The balances will then add up incorrectly.

Most likely there are race conditions between fetching balances and prices where `userVisibleAssets` is already set with some balances and thus its adding balances to a state that isn't currently 0.

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- There was a race condition as `update()` would reset `userVisibleAssets` and call `fetchBalances` and `fetchPrices` which both directly modifier `userVisibleAssets`, but if `update()` is called >1 times prior to fetch calls responding we could double up balances.
- Added `PortfolioStoreTests` to test against `update()`

This pull request fixes #5027

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Best to reproduce this off development first as race conditions are somewhat tricky.
1. Open and unlock wallet
2. Turn on network link conditioner to simulate slow network; I used 100kb/s down & up, 10ms delay and 25% packet drop for a slow network.
3. Rapidly change networks while loading
4. Observe balance exceed actual balance

## Screenshots:
Broken against `development`:
https://user-images.githubusercontent.com/5314553/157954951-c233204e-dbb5-4ac1-99d0-9c32f2125232.mov

Fixed against this `bugfix/5027-update-race-condition` branch:
https://user-images.githubusercontent.com/5314553/157961890-8db7a11b-473a-49f0-9061-db7017b9e3d6.mov

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/Stores/PortfolioStore.swift [hunk 1]
```diff
@@ -87,96 +87,108 @@ public class PortfolioStore: ObservableObject {
...
+      completion(priceHistories)
+    })
   }
-  
+
   func update() {
-    isLoadingBalances = true
-    rpcService.chainId { [self] chainId in
+    self.isLoadingBalances = true
+    self.rpcService.chainId { [self] chainId in
```
Comment (nuo-xu) [inline BraveWallet/Crypto/Stores/PortfolioStore.swift]: dont need `self` here

**Review by nuo-xu — APPROVED** [review]
