### PR TITLE
Fix #5120: Account activity view not showing all available assets on Ropsten

### LINKED ISSUE #5120: ERC20 Approval transactions display incorrectly
### Description: 

ERC20 approval transactions display incorrectly in the account activity list view for the Ropsten network.
We use hardcoded addresses for swapping USDC and DAI on Ropsten network, and these assets are not shown in the 'Edit Visible Assets' view so they do not appear in the Account Activity view, which causes our ERC 20 approval tx summary to only show 'Approved' and not 'Approved x USDC/DAI' (top tx is ERC20Approve tx type for USDC). 

### Steps to Reproduce 
  1. Switch to Ropsten network
  2. If you have 0 DAI, swap some ETH to DAI
  3. Open swap panel and try to swap DAI to ETH. Swap button should show 'Activate Token DAI'. Tap it.
  4. Confirm the approve transaction
  5. Open account activity and view transactions list

**Actual result:** 
activityview-development

**Expected result:**
Activity view shows DAI, USDC in Assets list
Transactions list shows 'Approved x DAI' / 'Approved x USDC' for ERC20Approve tx types

**Reproduces how often:** 
Easily reproduced

### Additional Information
Currently we are fetching tokens from the Blockchain Registry on the Ethereum Mainnet network, no matter which network is currently selected. The Blockchain Registry now returns the correct tokens and addresses for the Ropsten test network, so we should remove the hardcoded DAI / USDC addresses used for swapping on Ropsten test network and allow the user to add/remove any user assets returned from Blockchain Registry on Ropsten.

This affects a number of views:

- Edit user visible assets
  - Should be able to add DAI / USDC as visible assets on Ropsten network without adding as custom assets.
- Account activity view (account detail)
  - Asset list updated for new DAI / USDC user visible assets (if added by user)
  - Transaction list should show symbol for ERC 20 Approve transactions
- Asset search view
  - Should only show assets for that network
- Send Token
  - Same as before, should see ETH / DAI / USDC (previously they were hardcoded addresses for the assets)
- Swap Token
  - Should function the same as before, should see ETH / DAI / USDC (previously they were hardcoded addresses for the assets)

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- ~On Ropsten network we add USDC and DAI as swap options manually, but missed adding them to Account Activity (desktop shows them).~ 
- Currently we are fetching tokens from the Blockchain Registry on the Ethereum Mainnet network, no matter which network is currently selected. The Blockchain Registry now returns the correct tokens and addresses for the Ropsten test network, so we should remove the hardcoded DAI / USDC addresses used for swapping on Ropsten test network.

This affects a number of views:

- Edit user visible assets
  - Should be able to add DAI / USDC as user visible assets on Ropsten network without adding as custom assets.
- Account activity view (account detail)
  - Asset list updated for new DAI / USDC user visible assets (if added by user)
  - Transaction list should show symbol for ERC 20 Approve transactions
- Asset search view
  - Should only show assets for that network
- Send Token
  - Same as before, should see ETH / DAI / USDC (previously they were hardcoded addresses for the assets)
- Swap Token
  - Should function the same as before, should see ETH / DAI / USDC (previously they were hardcoded addresses for the assets)

This pull request fixes #5120

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Edit visible assets:
1. Switch to Ropsten network
2. Tap 'edit visible assets' button
3. DAI / USDC should now be listed to add

To get a ERC 20 Approve transaction:
1. Open & unlock wallet
4. Switch to Ropsten network
5. If you have 0 DAI, swap some ETH to DAI
6. Open swap panel and try to swap DAI to ETH. Swap button should show 'Activate Token DAI' if you have never swapped DAI before. Tap it.
7. Confirm the Approve transaction
8. Open Accounts tab
9. Tap account to see account activity. Should see ETH, USDC, DAI now, and DAI approve tx should be shown as 'Approve x DAI'

Search assets:
1. Search button on Portfolio / Accounts root
2. Should now show only ETH / DAI / USDC on Ropsten test network now

Swap / Send
1. Tap brave button to open buy / send / swap quick action sheet
2. Tap send/swap
3. Tap TO/FROM asset should still see USDC / DAI as options, and swap/send should still work as expected

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by nuo-xu — DISMISSED** [review]

**Review by nuo-xu — APPROVED** [review]

File: BraveWallet/Crypto/Stores/AccountActivityStore.swift [hunk 1]
```diff
@@ -39,38 +43,48 @@ class AccountActivityStore: ObservableObject {
...
-            }) {
-              assets[index].price = price.price
-            }
+      rpcService.chainId { [self] chainId in
+      blockchainRegistry.allTokens(chainId) { [self] allTokens in
+        self.allTokens = allTokens
+      }
+        walletService.userAssets(chainId) { [self] tokens in
+          var updatedAssets = tokens.map {
+            AssetViewModel(token: $0, decimalBalance: 0, price: "", history: [])
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/AccountActivityStore.swift]: Some sort of whitespace issue going on here, can you reformat this file/this function?

File: BraveWallet/Crypto/Stores/AccountActivityStore.swift [hunk 2]
```diff
@@ -39,38 +43,48 @@ class AccountActivityStore: ObservableObject {
...
           }
-        }
-        for token in tokens {
-          rpcService.balance(for: token, in: account) { value in
-            if let value = value,
-              let index = assets.firstIndex(where: {
+          let updatedTokens = updatedAssets.map { $0.token }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/AccountActivityStore.swift]: minor: You can do `updatedAssets.map(\.token)`

**Review by kylehickinson — APPROVED** [review]
Only minor nits
