### PR TITLE
Fix #4001: Brave-Search script has the wrong name

### LINKED ISSUE #4001: Add Brave Talk web-native communication.
Look for `Toggle Ads from Brave Properties Mini Spec` in gdrive

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- BraveSearch script has the wrong name
- Modified debug flags for simulator & debug builds so clipboard doesn't harass the devs

This pull request fixes #4001

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Same as #4001 

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

**Review by soner-yuksel — APPROVED** [review]

**Review by nuo-xu — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift [hunk 1]
```diff
@@ -13,6 +13,8 @@ import BraveCore
 extension BrowserViewController {
     
     func presentOnboardingIntro() {
+        if Preferences.DebugFlag.skipOnboardingIntro == true { return }
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift:16]: somehow we removed this again lolll
