### PR TITLE
Fix #490: Private mode shield overrides do not save to CoreData

### LINKED ISSUE #490: Site shield setting set in PB tab gets propagated to normal tabs
### Description: 
Site shield setting set in PB tab gets propagated to normal tabs as well

### Steps to Reproduce 
  1. Visit https://wired.com in a new private tab
  2. Enable Fingerprint protection from shields for that site
  3. Close PB tab and open the same site in normal tab, shields settings are propagated to normal tab 

**Actual result:** 
Site shield setting set in PB tab gets propagated to normal tabs as well

**Expected result:**
Changes should only persist in private tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by kylehickinson**
## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Shields/BraveShield.swift [hunk 1]
```diff
@@ -0,0 +1,145 @@
...
+    
+    /// Remove all private browsing shield overrides
+    class func resetPrivateBrowsingShieldOverrides() {
+        PrivateBrowsingShieldOverride.privateModeOverrides.removeAll()
+    }
+    
+    class func setBraveShield(forUrl url: URL, shield: BraveShield, isOn: Bool?,
+                              context: NSManagedObjectContext = DataController.newBackgroundContext()) {
+        
+        let domain = Domain.getOrCreateForUrl(url, context: context)
```
Comment (jhreis) [inline Client/Frontend/Shields/BraveShield.swift:60]: One thing that we should take care of here, is not store privately visited domains in CD unless user explicitly requests this. This would be like saving a favorite or bookmark. 

Inside here, we should check against `isPrivate`, and if it is, then save to array and completely bypass any concept of `Domain`.

**Review by jhreis — CHANGES_REQUESTED** [review]
Pretty much everything looks super solid. One main change.

Additionally, given the private mode stuff here, if we could create some unit tests around validating that `Domain` objects aren't saved while private mode is on, that would be great.

File: Client/Frontend/Shields/BraveShield.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Shields/BraveShield.swift:60]: While I can definitely fix in this case, Domain objects are created elsewhere even in private mode, completely unrelated to shields.

File: Client/Frontend/Shields/BraveShield.swift [hunk 2]
```diff
@@ -0,0 +1,173 @@
...
+        if PrivateBrowsingManager.shared.isPrivateBrowsing {
+            return getPrivateShieldForDomainUrl(url.domainURL.absoluteString, shield: shield, context: context)
+        }
+        let domain = Domain.getOrCreateForUrl(url, context: context)
+        return domain.getBraveShield(shield)
+    }
+    
+    func setBraveShield(shield: BraveShield, isOn: Bool?,
+                        context: NSManagedObjectContext = DataController.newBackgroundContext()) {
+        if PrivateBrowsingManager.shared.isPrivateBrowsing {
```
Comment (jhreis) [inline Client/Frontend/Shields/BraveShield.swift:75]: Now that https://github.com/brave/brave-ios/pull/621/files#diff-4078b8097af7507d3c5456a747da725dR56
exists, this shouldn't ever be called, since this requires a `Domain` instance.

Can we instead do a full assert here?

```
asset(!PrivateBrowsingManager.shared.isPrivateBrowsing, "Should not be updating Domain objects while in private mode")
```

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Shields/BraveShield.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Shields/BraveShield.swift:75]: Yeah, actually these instance method versions aren't even used anywhere else, so I'm going to make them private as well

**Review by jhreis — APPROVED** [review]
