### PR TITLE
Fix #8019: Fix issues with farbling plugins on iOS 17

### LINKED ISSUE #8019: [iOS 17] Fingerprinting is broken and showing the same values on both pages and after relaunching Brave when Shields enabled
### Description: 

[iOS 17] Fingerprinting is broken and showing the same values on `both pages` and after `relaunching Brave` when `Shields enabled`

### Steps to Reproduce 
  1. Launch Brave
  2. Go to https://dev-pages.brave.software/fingerprinting/farbling.html
  3. Make sure `Brave Shields` is enabled > Generate fingerprints
  4. Check results for `Plugins`, `Hardware connectivity and `Speech voices`
  5. For each separate feature the value must be the same in every column, but different for each feature
  6. Close and relaunch Brave > Run the test again
  7. Compare values with results in the previous step  > Observe that values are the same
  8. Open another page https://dev-pages.bravesoftware.com/fingerprinting/farbling.html
  9. Run the test and compare results > Observe that values are the same
  
Note: Hardware concurrency is hit or miss. We farble number of cores between 2-8 (on iOS 14 and can be less on older devices). With such a low variety of numbers, it's possible that both both test pages get the same value. This can be seen by killing the app and relaunching it. A new random value is given to the farbler and you will see the same values repeating on average 1/7 times as there are only 1/7 possible values we can use.

### Actual result: 

When `Brave Shields` is enabled on a device with `iOS 17` the values for farbling tests are the same. On iPad with iPadOS 16.5.1 the values are different as expected, so I believe this is `iOS 17` specific issue.

|1|2|3|4|
|:-:|:-:|:-:|:-:|
|  |  |  |  |

### Expected result:

Results must have different values for farbling tests.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.57 (23.9.1.15)
BraveCore: 1.57.53 (116.0.5845.114)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #8019

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

STR in issue

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js [hunk 1]
```diff
@@ -130,34 +130,45 @@ window.__firefox__.execute(function($) {
         // We need the original length so we can reference it (as we will change it)
         const plugins = window.navigator.plugins
         const originalPluginsLength = plugins.length
-
+        const pluginsPrototype = Object.getPrototypeOf(window.navigator.plugins)
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js:133]: Why are we still using `plugins`? It's deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/plugins and will be removed.

This code doesn't check for the existence of it before using it or attempting to get the prototype of it. If it ever returned `null` or `undefined` this would cause the entire script to fail loading as it'd give an error.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js [hunk 2]
```diff
@@ -130,34 +130,45 @@ window.__firefox__.execute(function($) {
...
+        const originalItem = window.navigator.plugins.item
+        pluginsPrototype.item = function () {
+          let index = arguments[0]
+          
           if (index < originalPluginsLength) {
-            return Reflect.apply(originalItemFunction, plugins, arguments)
+            return Reflect.apply(originalItem, this, arguments)
           } else {
-            return plugins[index]
+            const farbledIndex = index - originalPluginsLength
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js:152]: If originalPluginsLength > index, you'd end up with a negative farbledIndex here.
Is it possible to have an originalPluginsLength > index?

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js [hunk 3]
```diff
@@ -130,34 +130,45 @@ window.__firefox__.execute(function($) {
...
-
-        // Patch `PluginArray.item(index)` function to return the correct item
-        // otherwise it returns `undefined`
-        const originalItemFunction = plugins.item
-        window.PluginArray.prototype.item = function (index) {
+        
+        // Farble the `item` method on the plugins array
+        const originalItem = window.navigator.plugins.item
+        pluginsPrototype.item = function () {
+          let index = arguments[0]
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js]: Why do `pluginsPrototype.item = function()` + `let index = arguments[0]` instead of `pluginsPrototype.item = function(index)`?

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js [hunk 4]
```diff
@@ -130,34 +130,45 @@ window.__firefox__.execute(function($) {
...
-            return plugins[index]
+            const farbledIndex = index - originalPluginsLength
+            return fakePlugins[farbledIndex]
           }
         }
+        
+        // Farble the `namedItem` method on the plugins array
+        const originalNamedItem = window.navigator.plugins.namedItem
+        pluginsPrototype.namedItem = function () {
+          let name = arguments[0]
```
Comment (Brandon-T) [inline Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js]: Same thing. `.namedItem = function(name)`

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js (hunk 1 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js:133]: There is a check just 5 lines above

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js (hunk 3 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js]: Yes I could change this. I prefer arguments in case some new params are added to the API. though highly unlikely.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js (hunk 2 above)
Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js:152]: this is in an `else` of an `if` check which guarantees index is smaller than originalPluginsLength so the index may only be equal or greater than original plugins length. A negative value is impossible here.

Comment (cuba) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js:152]: I should also point out that if a user were to pass a negative value, this would fall into the if statement which then would get passed to the original method and handled as if unfarbled.

File: Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js (hunk 3 above)
Comment (Brandon-T) [reply Sources/Brave/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/FarblingProtectionScript.js]: Hmm, if new parameters were added, you'd have to change the code to use those anyway, so you could always change the function signature.

**Review by Brandon-T — APPROVED** [review]
