### PR TITLE
Ref #3939: When deleting history, delete its Screen Time entry.

### LINKED ISSUE #3939: Implement screentime
### Description: 
See this API https://developer.apple.com/documentation/screentime/stwebpagecontroller
It may be possible to block restricted pages based on screentime limits

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #3939

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Sync/BraveCore/History/HistoryAPIExtensions.swift [hunk 1]
```diff
@@ -53,10 +54,20 @@ extension BraveHistoryAPI {
     }
   }
   
-  func deleteAll(completion: @escaping () -> Void) {
+  func deleteAll(includeScreenTimeHistory: Bool = true, completion: @escaping () -> Void) {
```
Comment (soner-yuksel) [inline Sources/Brave/Frontend/Sync/BraveCore/History/HistoryAPIExtensions.swift]: I think we can remove the parameter. The only place used deleteAll is in history screen and I dont think we will ever need to call deleteAll without needing to delete screen time history.

**Review by soner-yuksel — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
