### PR TITLE
Fix #4308: Fix all Session Restore, Reader-Mode, GCDWebServer issues

### LINKED ISSUE #4308: Update Session Restore and GCDWebServer code
### Description: 
- We should minimize use of the GCDWebServer and start using the custom url SchemeHandler.
- Firefox has already done a similar change to their SessionRestore and InternalURL and PrivilegedRequest

### PR DESCRIPTION
**Pull request by Brandon-T**
## Info:
- Fix all session restore, reader-mode, error page, certificate error page, etc. bugs.
- Used InternalURL and fix PrivilegedRequest.
- Get rid of most of GCDWebServer code.

## Summary of Changes
- Use `InternalURL`
- Use `PrivilegedRequest` which uses `InternalURL`
- Remove most `GCDWebServer` handlers to use `WKURLSchemeHandler` instead
- Update ErrorPage HTML and CSS
- Update NetCert HTML and CSS
- Update SessionRestore HTML
- Rewrote all Interstitial pages
- Update SessionData and SavedTab to handle persistent private mode (though, not enabled yet)
- Added migration `SessionData.updateSessionURLs` to migrate session restore URLs to use the proper schemes instead of (`GCDWebServer` schemes && `localhost`).

- **TODO**: Update Unit Tests!! (Help wanted :))

This pull request fixes #4308

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Test Reader-Mode
- Test Session Restore
- Test Session Restore of Japanese website with Kanji or Katakana characters in the URL
- Test Session Restore of multiple tabs
- Test About Home page
- Test About License page
- Test Error Pages like on `gsdgsdglkangajkngkalngakgdaga.com` or random website.
- Test Error Pages on bad certificate website like: `https://expired.badssl.com/`
- Test Error Pages when there is no network (turn on airplane mode).

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by Brandon-T** [comment]
Added Interstitial Pages:

File: Client/Application/Delegates/AppDelegate.swift [hunk 1]
```diff
@@ -382,15 +382,20 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
...
-        if server.server.isRunning { return }
-        
-        ReaderModeHandlers.register(server, profile: profile)
-        ErrorPageHelper.register(server, certStore: profile.certStore)
-        SafeBrowsingHandler.register(server)
-        AboutHomeHandler.register(server)
-        AboutLicenseHandler.register(server)
-        SessionRestoreHandler.register(server)
-        BookmarksInterstitialPageHandler.register(server)
+        guard !server.server.isRunning else { return }
```
Comment (iccub) [inline Client/Application/Delegates/AppDelegate.swift:381]: I like `if server.server.isRunning { return }` more, more readable imo

File: Client/Application/Delegates/AppDelegate.swift [hunk 2]
```diff
@@ -382,15 +382,20 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
...
+        
+        let responders: [(String, InternalSchemeResponse)] =
+            [ (AboutHomeHandler.path, AboutHomeHandler()),
```
Comment (iccub) [inline Client/Application/Delegates/AppDelegate.swift]: Extra space after `[` character

File: Client/Application/Delegates/AppDelegate.swift [hunk 3]
```diff
@@ -382,15 +382,20 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
...
+              (AboutLicenseHandler.path, AboutLicenseHandler()),
+              (SessionRestoreHandler.path, SessionRestoreHandler()),
+              (ErrorPageHandler.path, ErrorPageHandler())]
+        responders.forEach { (path, responder) in
+            InternalSchemeHandler.responders[path] = responder
+        }
+        
+        ReaderModeHandlers.register(server, profile: profile) //TODO: PORT TO InternalSchemeHandler
+        SafeBrowsingHandler.register(server) //TODO: REMOVE COMPLETELY!!!
+        BookmarksInterstitialPageHandler.register(server) //TODO: PORT TO InternalSchemeHandler
```
Comment (iccub) [inline Client/Application/Delegates/AppDelegate.swift:394]: Are these todos still needed?

File: Client/Frontend/Browser/BrowserTrayAnimators.swift [hunk 4]
```diff
@@ -276,7 +278,7 @@ private func calculateExpandedCellFrameFromBVC(_ bvc: BrowserViewController) ->
 private func shouldDisplayFooterForBVC(_ bvc: BrowserViewController) -> Bool {
     if bvc.shouldShowFooterForTraitCollection(bvc.traitCollection) {
         if let url = bvc.tabManager.selectedTab?.url {
-            return !url.isAboutURL
+            return InternalURL(url)?.isAboutURL ?? false
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserTrayAnimators.swift:281]: maybe convert to `InternalURL(url)?.isAboutURL == false`

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 5]
```diff
@@ -1203,16 +1203,26 @@ class BrowserViewController: UIViewController, BrowserViewControllerDelegate {
...
-            if url.isAboutHomeURL && !url.isErrorPageURL {
+            
+            if isAboutHomeURL {
                 showNewTabPageController()
-            } else if !url.isLocalUtility || url.isReaderModeURL || url.isErrorPageURL {
+            } else if !url.absoluteString.hasPrefix("\(InternalURL.baseUrl)/\(SessionRestoreHandler.path)") {
                 hideActiveNewTabPageController(url.isReaderModeURL)
             }
+        } else if isAboutHomeURL {
+            showNewTabPageController()
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:1225]: are we sure we want this when top toolbar is in overlay mode?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 6]
```diff
@@ -1861,7 +1877,7 @@ class BrowserViewController: UIViewController, BrowserViewControllerDelegate {
             // Whether to show search icon or + icon
             toolbar?.setSearchButtonState(url: url)
             
-            if !url.isErrorPageURL, !url.isAboutHomeURL, !url.isFileURL {
+            if (!InternalURL.isValid(url: url) || url.isReaderModeURL), !url.isFileURL {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:1880]: why did you switch from about-home to reader-mode url check here?

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 7]
```diff
@@ -2267,6 +2288,33 @@ extension BrowserViewController: TabManagerDelegate {
             webView.snp.remakeConstraints { make in
                 make.left.right.top.bottom.equalTo(self.webViewContainer)
             }
+            
+            
+            // This is a terrible workaround for a bad iOS 12 bug where PDF
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift:2278]: i wonder if we still need it considering this comment says iOS 12 bug?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 8]
```diff
@@ -14,12 +14,16 @@ private let rewardsLog = Logger.braveCoreLogger
 
 extension WKNavigationAction {
     /// Allow local requests only if the request is privileged.
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:16]: is this comment still relevant?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 9]
```diff
@@ -258,7 +267,7 @@ extension BrowserViewController: WKNavigationDelegate {
             if
                 let mainDocumentURL = navigationAction.request.mainDocumentURL,
                 mainDocumentURL.schemelessAbsoluteString == url.schemelessAbsoluteString,
-                !url.isSessionRestoreURL,
+                !(InternalURL(url)?.isSessionRestore ?? false),
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:271]: convert to `== false`

File: Client/Frontend/Browser/MetadataParserHelper.swift [hunk 10]
```diff
@@ -27,18 +27,24 @@ class MetadataParserHelper: TabEventHandler {
...
             guard error == nil else {
+                // TabEvent.post(.pageMetadataNotAvailable, for: tab)
+                tab.pageMetadata = nil
                 return
             }
             
             guard let dict = result as? [String: Any],
                   let data = try? JSONSerialization.data(withJSONObject: dict, options: []) else {
                 log.debug("Page contains no metadata!")
+//                TabEvent.post(.pageMetadataNotAvailable, for: tab)
```
Comment (iccub) [inline Client/Frontend/Browser/MetadataParserHelper.swift:46]: do we use those tab events?

File: Client/Frontend/Browser/SessionData.swift [hunk 11]
```diff
@@ -48,33 +53,57 @@ class SessionData: NSObject, NSSecureCoding {
...
+    static func updateSessionURLs(urls: [URL]) -> [URL] {
         return urls.compactMap { url in
-            if PrivilegedRequest.isWebServerRequest(url: url),
-               PrivilegedRequest.isPrivileged(url: url),
-               let strippedURL = PrivilegedRequest.removePrivileges(url: url) {
-                return strippedURL
+            var url = url
+            let port = AppConstants.webServerPort
+            [("http://localhost:\(port)/errors/error.html?url=", "\(InternalURL.baseUrl)/\(SessionRestoreHandler.path)?url=")
+                // TODO: handle reader pages ("http://localhost:6571/reader-mode/page?url=", "\(InternalScheme.url)/\(ReaderModeHandler.path)?url=")
```
Comment (iccub) [inline Client/Frontend/Browser/SessionData.swift:88]: this is for future reader mode work I assume?

File: Client/Frontend/Browser/SessionRestoreHelper.swift [hunk 12]
```diff
@@ -25,17 +25,14 @@ class SessionRestoreHelper: TabContentScript {
...
-        if let tab = tab {
-            if body["name"] as? String == "didRestoreSession" {
+        if let tab = tab, let params = message.body as? [String: AnyObject] {
+            
+            if UserScriptManager.isMessageHandlerTokenMissing(in: params) {
+                log.debug("Missing required security token.")
+                return
+            }
+            
+            if params["name"] as! String == "didRestoreSession" {
```
Comment (iccub) [inline Client/Frontend/Browser/SessionRestoreHelper.swift]: can we safely cast it?

File: Client/Frontend/Browser/Tab.swift [hunk 13]
```diff
@@ -394,11 +386,26 @@ class Tab: NSObject {
     var displayTitle: String {
         if let title = webView?.title, !title.isEmpty {
             return title.contains("localhost") ? "" : title
-        } else if webView?.url?.isAboutHomeURL == true || self.url?.isAboutHomeURL == true {
+        }
+        
+        // When picking a display title. Tabs with sessionData are pending a restore so show their old title.
+        // To prevent flickering of the display title. If a tab is restoring make sure to use its lastTitle.
+        if let url = self.url, InternalURL(url)?.isAboutHomeURL ?? false, sessionData == nil, !restoring {
```
Comment (iccub) [inline Client/Frontend/Browser/Tab.swift:393]: convert to `== false`

File: Client/Frontend/Browser/TabManager.swift [hunk 14]
```diff
@@ -157,7 +157,12 @@ class TabManager: NSObject {
     }
     
     var openedWebsitesCount: Int {
-        tabsForCurrentMode.filter { $0.url?.isWebPage() == true && $0.url?.isAboutHomeURL == false }.count
+        tabsForCurrentMode.filter {
+            if let url = $0.url {
+                return url.isWebPage() && !(InternalURL(url)?.isAboutHomeURL ?? false)
```
Comment (iccub) [inline Client/Frontend/Browser/TabManager.swift:162]: convert to `== false`

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 15]
```diff
@@ -364,14 +364,14 @@ class AddEditBookmarkTableViewController: UITableViewController {
         
         for tab in tabs {
             if PrivateBrowsingManager.shared.isPrivateBrowsing {
-                if let url = tab.url, url.isWebPage(), !url.isAboutHomeURL {
+                if let url = tab.url, url.isWebPage(), !(InternalURL(url)?.isAboutHomeURL ?? false) {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift:366]: convert to `== false`

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 16]
```diff
@@ -364,14 +364,14 @@ class AddEditBookmarkTableViewController: UITableViewController {
...
                     bookmarkAPI.add(url: url, title: tab.title, parentFolder: parentFolder)
                 }
             } else {
                 if let tabID = tab.id {
                     let fetchedTab = TabMO.get(fromId: tabID)
                     
-                    if let urlString = fetchedTab?.url, let url = URL(string: urlString), url.isWebPage(), !url.isAboutHomeURL {
+                    if let urlString = fetchedTab?.url, let url = URL(string: urlString), url.isWebPage(), !(InternalURL(url)?.isAboutHomeURL ?? false) {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift:373]: convert to `== false`

File: Shared/Extensions/URLExtensions.swift [hunk 17]
```diff
@@ -652,6 +591,128 @@ extension String {
...
+            return URL(string: nestedUrl)
+        }
+        return nil
+    }
+
+    public var isAboutHomeURL: Bool {
+        if let urlParam = extractedUrlParam, let internalUrlParam = InternalURL(urlParam) {
+            return internalUrlParam.aboutComponent?.hasPrefix("home") ?? false
+        }
+        return aboutComponent?.hasPrefix("home") ?? false
```
Comment (iccub) [inline Shared/Extensions/URLExtensions.swift:699]: convert to `== false`

**Review by iccub — CHANGES_REQUESTED** [review]
left few questions and nitpicks, will run this branch later for functional review

File: Client/Application/Delegates/AppDelegate.swift (hunk 3 above)
Comment (Brandon-T) [reply Client/Application/Delegates/AppDelegate.swift:394]: Yeah they are. They can stay for now because `reader-mode` and the safebrowsing and interstitial handlers are still using GCDWebServer.

File: Client/Frontend/Browser/BrowserTrayAnimators.swift (hunk 4 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserTrayAnimators.swift:281]: Doesn't work if I do that. `InternalURL(url)` returns nil and when I do `isAboutURL` on it, it returns `Optional(nil)`. So `nil == false` returns false :(

https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 6 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift:1880]: This check is checking specifically if the URL is NOT `errorPage` or `aboutHome` or `fileURL`.
The content of the `if-statement` runs `webView.evaluateSafeJavaScript(functionName: "\(ReaderModeNamespace).checkReadability"` which is only valid on a reader-mode page. Error page and about home should not support `reader-mode`.

So the check should actually be only if it is a reader-mode page or regular page.
So it is correct. The URL must not be a `valid` internal URL (regular page), OR it must be a valid reader-mode page.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 7 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController.swift:2278]: It is needed for iOS 12+.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 8 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:16]: Yes, it is valid. I'll update it to be a better comment.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 9 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:271]: That won't work. Try it in a playground:

```swift
import Foundation

class OptionalInit {
    init?() {
        return nil
    }

    var whatever: Bool {
        return false
    }
}

print(OptionalInit()?.whatever == false)
```

If it prints `false` it won't work. The `optional` returns `Optional(nil)` not `false`. So `Optional(nil) == false` returns `false` :(

File: Client/Frontend/Browser/MetadataParserHelper.swift (hunk 10 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/MetadataParserHelper.swift:46]: We don't have those added yet, but we can add them later. This class will need refactoring.

File: Client/Frontend/Browser/SessionData.swift (hunk 11 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/SessionData.swift:88]: Yeah :) It is for when we move reader-mode to `WKURLSchemeHandler` instead of GCDWebServer.

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift (hunk 9 above)
Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift:271]: okay, ignore my other comments about it then, posted few of them :o

File: Client/Frontend/Browser/Tab.swift (hunk 13 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Tab.swift:393]: https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

File: Client/Frontend/Browser/TabManager.swift (hunk 14 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/TabManager.swift:162]: https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift (hunk 15 above)
Comment (Brandon-T) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift:366]: https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

**Review by iccub — APPROVED** [review]
I ran some tests and all works for me :)
