### PR TITLE
Fix: #485, Added Cookie control to block all cookies.

### LINKED ISSUE #485: Block All Cookies Settings Option
### Description: 
Block all cookies doesn't block like it should

### Steps to Reproduce 
  1. Set `Block all cookies` from settings
  2. Visit https://jsfiddle.net in a new tab
  3. Page loads correctly even with block cookies set

**Actual result:** 
Page laods when block all cookies is set

**Expected result:**
Page should not load when `Block all cookies` is set 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
This is regressed on 1.6.6 as well. On b-c and Android when `Block all cookies` is set the page doesn't load which is the expected behaviour

### PR DESCRIPTION
**Pull request by danishjafri88**
Fixed: #485  Added Cookie control to block all cookies.
This is a new implementation of Cookie control as mentioned in #485. Please follow instructions to verify it.
-> In Safari/Chrome desktop go to settings and block all cookies.
-> Go to jsfiddle.net 
-> Open web inspector and goto console.
-> The console should have errors relating to security or access denied.
-> The page would be stuck.

-> Open Safari `Preferences` in Mac> `Advanced` tab> Check `Show Develop Menu..`
-> Install this build of brave in a device connected to the Mac above.
-> Go to settings and enable `block all cookies`
-> Go to jsfiddle.net 
-> While brave is open, open Safari>`Develop` menu> your iOS device> jsfiddle.net(under brave)
-> In the new web inspector verify as above.

*How*
Steps involved:
1. ContentRule for blocking-cookies in http headers
2. Hook into Dom cookie/localStorage/sessionStorage to make them inaccessible/Empty
3. Add a posix lock on Cookie and WebSiteData folders in iOS App library directory to make WebSQLDB and IndexedDB inaccessible.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

**Comment by jhreis** [comment]
Blocked per security and UI review.

File: Client/FileManagerExtension.swift [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+        case cache = "/Caches"
+    }
+    typealias FolderLockObj = (folder: Folder, lock: Bool)
+    public func lockFolders(_ lockObjects: [FolderLockObj]) {
+        let baseDir = NSSearchPathForDirectoriesInDomains(.libraryDirectory, .userDomainMask, true)[0]
+        for lockObj in lockObjects {
+            do {
+                try self.setAttributes([FileAttributeKey.posixPermissions: (lockObj.lock ? NSNumber(value: 0 as Int16) : NSNumber(value: 0o755 as Int16))], ofItemAtPath: baseDir + lockObj.folder.rawValue)
+            } catch {
+                print(error)
```
Comment (jhreis) [inline Client/FileManagerExtension.swift]: Should use a `log.error`, instead of a raw `print`

File: Client/Frontend/UserContent/UserScripts/CookieControl.js [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+                          });
+}
+
+
+//Access to localStorage should be denied when user has blocked all Cookies.
+var localStDesc = Object.getOwnPropertyDescriptor(window, 'localStorage');
+if (localStDesc) {
+    Object.defineProperty(window, 'localStorage', {
+                          get: function () {
+                          var err= new Error();
```
Comment (jhreis) [inline Client/Frontend/UserContent/UserScripts/CookieControl.js]: I'm not sure we should throw an error this clean, this could allow websites to pretty easily work around us. 

catch(error) {
    if (err.name = "BraveSecurityError") { resetLocalStorage() }
}

**Review by jhreis — CHANGES_REQUESTED** [review]

**Comment by jumde** [comment]
@jhreis @danishjafri88 - On desktop, block all cookies blocks all storage `Cookies | Local Storage | Session Storage | WebSQL | IndexedDB`, but I see that only cookies and local storage is blocked with this change. Can we replicate desktop behavior here? You can use `browsertesting.orgfree.com/stp.html` to verify the behavior

**Comment by jumde** [comment]
@jhreis @danishjafri88 - Looks like cookies set on the server side are available, check `http://dustiest-limitation.000webhostapp.com/first_party.php`

File: Client/Frontend/UserContent/UserScripts/CookieControl.js (hunk 2 above)
Comment (danishjafri88) [reply Client/Frontend/UserContent/UserScripts/CookieControl.js]: Yeah, I made a code to randomise the error name. Will add that back.

File: Client/FileManagerExtension.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/FileManagerExtension.swift]: Done

**Comment by danishjafri88** [comment]
@jumde the recent push has all the required changes. Please let me know if its in parity with desktop/ Safari iOS. 
Changes done are updated in PR description.

**Comment by danishjafri88** [comment]
@jumde browsertesting.orgfree.com/stp.html the results will be a little misguiding for this push.
It will show cookies as saved even though thats false. Cookies are not saved anymore.
IndexedDB does not return an error in JS but does in iOS runtime. The runtime error is: 

could not create directory "/private/var/mobile/Containers/Data/Application/97A6AB8C-7352-4D59-AD2D-5009B458660A/Library/WebKit/WebsiteData/IndexedDB" for future sandbox extension, error Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “IndexedDB” in the folder “WebsiteData”." UserInfo={NSFilePath=/private/var/mobile/Containers/Data/Application/97A6AB8C-7352-4D59-AD2D-5009B458660A/Library/WebKit/WebsiteData/IndexedDB, NSUnderlyingError=0x28215b750 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}

**Comment by danishjafri88** [comment]
@jhreis we need Strings for the alerts.

File: BraveShared/BraveStrings.swift [hunk 3]
```diff
@@ -428,6 +428,9 @@ public extension Strings {
...
     public static let Block_all_cookies = NSLocalizedString("BlockAllCookies", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Block all cookies", comment: "cookie settings option")
+    public static let Block_all_cookies_alert_info = NSLocalizedString("BlockAllCookiesAlertInfo", tableName: "BraveShared", bundle: Bundle.braveShared, value: "This Setting does this blah blah blah", comment: "Information displayed to user when block all cookie is enabled.")
+    public static let Block_all_cookies_alert_title = NSLocalizedString("BlockAllCookiesAlertTitle", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Block all cookies alert title", comment: "Title of alert displayed to user when block all cookie is enabled.")
+    public static let Block_all_cookies_failed_alert_msg = NSLocalizedString("BlockAllCookiesFailedAlertMsg", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Block all cookies failed alert message", comment: "Message of alert displayed to user when block all cookie operation fails")
```
Comment (danishjafri88) [inline BraveShared/BraveStrings.swift]: Need strings for these!

**Comment by danishjafri88** [comment]
FYI please test on actual device.

File: Client/Frontend/Browser/UserScriptManager.swift [hunk 4]
```diff
@@ -55,6 +62,18 @@ class UserScriptManager {
...
     }()
     
+    private let cookieControlUserScript: WKUserScript? = {
+        guard let path = Bundle.main.path(forResource: "CookieControl", ofType: "js"), let source: String = try? String(contentsOfFile: path) else {
+            log.error("Failed to load cookie control user script")
+            return nil
+        }
+        var alteredSource: String = source
+        let token = UserScriptManager.securityToken.uuidString.replacingOccurrences(of: "-", with: "", options: .literal, range: nil)
+        alteredSource = alteredSource.replacingOccurrences(of: "$<local>", with: "L\(token)", options: .literal, range: nil).replacingOccurrences(of: "$<session>", with: "S\(token)", options: .literal, range: nil).replacingOccurrences(of: "$<cookie>", with: "C\(token)", options: .literal, range: nil)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/UserScriptManager.swift]: Small nit, maybe break this into multiple lines (super long), and also `range` should have a default so I don't think you have to include it as nil.

```suggestion
        alteredSource = alteredSource.replacingOccurrences(of: "$<local>", with: "L\(token)", options: .literal)
                                     .replacingOccurrences(of: "$<session>", with: "S\(token)", options: .literal)
                                     .replacingOccurrences(of: "$<cookie>", with: "C\(token)", options: .literal)
```

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 5]
```diff
@@ -196,6 +197,54 @@ class SettingsViewController: TableViewController {
                     self.navigationController?.pushViewController(clearPrivateData, animated: true)
                 },
                 accessory: .disclosureIndicator
+            ),
+            Row(
+                text: Strings.Block_all_cookies,
+                accessory: .switchToggle(
+                    value: Preferences.Privacy.blockAllCookies.value, { [unowned self] in
+                        func perform(with status: Bool) {
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: This function name isn't super clear

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 6]
```diff
@@ -196,6 +197,54 @@ class SettingsViewController: TableViewController {
...
+                            let status = $0
+                            // THROW ALERT to inform user of the setting
+                            let alert = UIAlertController(title: Strings.Block_all_cookies_alert_title, message: Strings.Block_all_cookies_alert_info, preferredStyle: .alert)
+                            let okAction = UIAlertAction(title: Strings.OKString, style: .default, handler: { (action) in
+                                perform(with: status)
+                            })
+                            alert.addAction(okAction)
+                            
+                            let cancelAction = UIAlertAction(title: Strings.CancelButtonTitle, style: .cancel, handler: { (action) in
+                                self.undoToggleEvent(section: 1, row: 1)
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: Probably not a good idea to rely on hardcoded section/row numbers. This might break when we add Sync (can't remember currently where it goes in settings off the top of my head) or other settings. Maybe stick to the section/row uuid to obtain a section/row index?

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 7]
```diff
@@ -196,6 +197,54 @@ class SettingsViewController: TableViewController {
...
+                                ])
+                            if success {
+                                Preferences.Privacy.blockAllCookies.value = status
+                            } else {
+                                //Revert the changes. Not handling success here to avoid a loop.
+                                _ = FileManager.default.lockFolders([
+                                    (.cookie, !status),
+                                    (.webSiteData, !status)
+                                    ])
+                                self.undoToggleEvent(section: 1, row: 1)
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: Same as below (hard-coded section/row)

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 8]
```diff
@@ -196,6 +197,54 @@ class SettingsViewController: TableViewController {
...
+                                
+                                // TODO: Throw Alert to user to try again?
+                                let alert = UIAlertController(title: nil, message: Strings.Block_all_cookies_failed_alert_msg, preferredStyle: .alert)
+                                let okAction = UIAlertAction(title: Strings.OKString, style: .default)
+                                alert.addAction(okAction)
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: okAction can just be created inline since its not used elsewhere and is only saving 1 character in length

File: Client/FileManagerExtension.swift [hunk 9]
```diff
@@ -0,0 +1,30 @@
...
+        case webkit = "/WebKit"
+        case cache = "/Caches"
+        case webSiteData = "/WebKit/WebsiteData"
+    }
+    typealias FolderLockObj = (folder: Folder, lock: Bool)
+    public func lockFolders(_ lockObjects: [FolderLockObj]) -> Bool {
+        let baseDir = NSSearchPathForDirectoriesInDomains(.libraryDirectory, .userDomainMask, true)[0]
+        for lockObj in lockObjects {
+            do {
+                try self.setAttributes([FileAttributeKey.posixPermissions: (lockObj.lock ? NSNumber(value: 0 as Int16) : NSNumber(value: 0o755 as Int16))], ofItemAtPath: baseDir + lockObj.folder.rawValue)
```
Comment (kylehickinson) [inline Client/FileManagerExtension.swift]: nit: is `FileAttributeKey` needed (or can it just be `.posixPermissions`)

File: Client/FileManagerExtension.swift [hunk 10]
```diff
@@ -0,0 +1,30 @@
...
+
+public extension FileManager {
+    public enum Folder: String {
+        case cookie = "/Cookies"
+        case webkit = "/WebKit"
+        case cache = "/Caches"
+        case webSiteData = "/WebKit/WebsiteData"
+    }
+    typealias FolderLockObj = (folder: Folder, lock: Bool)
+    public func lockFolders(_ lockObjects: [FolderLockObj]) -> Bool {
```
Comment (kylehickinson) [inline Client/FileManagerExtension.swift]: This method name could be clearer that it can also unlock folders

File: BraveShared/BraveStrings.swift (hunk 3 above)
Comment (kylehickinson) [reply BraveShared/BraveStrings.swift]: We should probably get these from product before merging

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveShared/BraveStrings.swift (hunk 3 above)
Comment (jhreis) [reply BraveShared/BraveStrings.swift]: https://github.com/brave/brave-ios/issues/686

File: Client/FileManagerExtension.swift (hunk 10 above)
Comment (danishjafri88) [reply Client/FileManagerExtension.swift]: renamed to `setFolderAccess`

File: Client/FileManagerExtension.swift (hunk 9 above)
Comment (danishjafri88) [reply Client/FileManagerExtension.swift]: removed

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 8 above)
Comment (danishjafri88) [reply Client/Frontend/Settings/SettingsViewController.swift]: Done

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 5 above)
Comment (danishjafri88) [reply Client/Frontend/Settings/SettingsViewController.swift]: renamed to `toggleCookieSetting`

**Comment by jumde** [comment]
> @jhreis @danishjafri88 - On desktop, block all cookies blocks all storage `Cookies | Local Storage | Session Storage | WebSQL | IndexedDB`, but I see that only cookies and local storage is blocked with this change. Can we replicate desktop behavior here? You can use `browsertesting.orgfree.com/stp.html` to verify the behavior

Resolved

**Comment by jumde** [comment]
> @jhreis @danishjafri88 - Looks like cookies set on the server side are available, check `http://dustiest-limitation.000webhostapp.com/first_party.php`

Resolved

File: Client/Frontend/Browser/UserScriptManager.swift (hunk 4 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/UserScriptManager.swift]: Done

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 6 above)
Comment (danishjafri88) [reply Client/Frontend/Settings/SettingsViewController.swift]: Agreed, changed to as suggested :)

File: BraveShared/BraveStrings.swift [hunk 11]
```diff
@@ -428,9 +428,10 @@ public extension Strings {
...
-    public static let Block_all_cookies_failed_alert_msg = NSLocalizedString("BlockAllCookiesFailedAlertMsg", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Block all cookies failed alert message", comment: "Message of alert displayed to user when block all cookie operation fails")
+    public static let Block_all_cookies_action = NSLocalizedString("BlockAllCookiesAction", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Block All", comment: "block all cookies settings action title")
+    public static let Block_all_cookies_alert_info = NSLocalizedString("BlockAllCookiesAlertInfo", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Blocking all Cookies will prevent some websites from working correctly.", comment: "Information displayed to user when block all cookie is enabled.")
+    public static let Block_all_cookies_alert_title = NSLocalizedString("BlockAllCookiesAlertTitle", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Block all Cookies?", comment: "Title of alert displayed to user when block all cookie is enabled.")
```
Comment (jumde) [inline BraveShared/BraveStrings.swift]: - [ ] Need text for title

**Comment by jumde** [comment]
@jhreis @danishjafri88 - With the latest changes, here is one issue that I'm seeing.

Repro Steps:

- Toggle 1p cookie blocking.
- Open `http://dustiest-limitation.000webhostapp.com/first_party.php`. This loads `peltate-worth.000webhostapp.com` in 3p context.
- All cookies are blocked as expected.
- Switch off 1p cookie blocking. The page reloads and cookies for `peltate-worth` are available but, not for `dustiest-limitation`. 
- Refreshing the page fixes the issue. 

This is not a blocker for sec review. Let me know if you'd like me to file a separate bug for this issue

**Comment by jumde** [comment]
security review ++

**Comment by danishjafri88** [comment]
@jumde I have fixed the bug, it arose because I was only reloading the page and not making a fresh request. The 1p will be saved after switch off while 3p may or may not be saved as the default webkit ITP(Intelligent Tracking Protection) may block it.(Default behaviour matches Safari).

File: Client/FileManagerExtension.swift [hunk 12]
```diff
@@ -0,0 +1,30 @@
...
+
+import Foundation
+import Shared
+
+private let log = Logger.browserLogger
+
+public extension FileManager {
+    public enum Folder: String {
+        case cookie = "/Cookies"
+        case webkit = "/WebKit"
```
Comment (kylehickinson) [inline Client/FileManagerExtension.swift]: I know this isn't used at all, but we should be wary of having the option here. Locking the `WebKit` parent folder will cause issues with content blockers compiling. Perhaps we should remove this case?

File: Client/Frontend/Browser/TabManager.swift [hunk 13]
```diff
@@ -166,6 +160,29 @@ class TabManager: NSObject {
         assert(Thread.isMainThread)
         return allTabs.filter { $0.type == type }
     }
+    
+    private class func getNewConfiguration(isPrivate: Bool) -> WKWebViewConfiguration {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabManager.swift]: Is there a reason to keep the `isPrivate` arg or even the `WKWebViewConfigurations` above? Currently there doesn't seem to be any difference and we can always re-add it later if the configuration diverges for private mode

File: Client/Frontend/Browser/TabManager.swift [hunk 14]
```diff
@@ -166,6 +160,29 @@ class TabManager: NSObject {
...
+        configuration = TabManager.getNewConfiguration(isPrivate: false)
+        privateConfiguration = TabManager.getNewConfiguration(isPrivate: true)
+    }
+    
+    func reset() {
+        resetConfiguration()
+        allTabs.filter({$0.webView != nil}).forEach({
+            $0.resetWebView(config: $0.isPrivate ? privateConfiguration : configuration)
+        })
+        selectTab(selectedTab, ignorePrevious: true)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabManager.swift]: `ignorePrevious` is a bit odd, can we not just reset `_selectedIndex` to -1 so there's no selected tab and then there's no "previous" tab.

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 15]
```diff
@@ -196,6 +197,53 @@ class SettingsViewController: TableViewController {
...
+                            let status = $0
+                            // THROW ALERT to inform user of the setting
+                            let alert = UIAlertController(title: Strings.Block_all_cookies_alert_title, message: Strings.Block_all_cookies_alert_info, preferredStyle: .alert)
+                            let okAction = UIAlertAction(title: Strings.Block_all_cookies_action, style: .destructive, handler: { (action) in
+                                toggleCookieSetting(with: status)
+                            })
+                            alert.addAction(okAction)
+                            
+                            let cancelAction = UIAlertAction(title: Strings.CancelButtonTitle, style: .cancel, handler: { (action) in
+                                self.toggleSwitch(on: false, section: self.privacySection, rowUUID: Preferences.Privacy.blockAllCookies.key)
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: You should be able to use `row.view` since I changed the implementation of `BoolRow`'s in https://github.com/brave/brave-ios/pull/743/files and it will return the actual `UISwitch` instead of creating a new one each time.

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/FileManagerExtension.swift (hunk 12 above)
Comment (danishjafri88) [reply Client/FileManagerExtension.swift]: Yeah, I added it while trying somethings, will remove it

File: Client/Frontend/Browser/TabManager.swift (hunk 13 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/TabManager.swift]: Even I thought so, don't know why it was there first place. Will update

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 15 above)
Comment (danishjafri88) [reply Client/Frontend/Settings/SettingsViewController.swift]: Great, will update

File: Client/Frontend/Browser/TabManager.swift (hunk 14 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/TabManager.swift]: Well actually no, If the user enables block all cookies then we have to reload the selectedTab. Other tabs load on tab selection but the currently selectedTab needs reload call explicitly. Unless this bool is there while previous and selectedTab are nil, the underlying exit condition will be met and the func will return(without reloading the tab). This logic is in place to avoid the func execution in case the current tab is selected. This function is tightly coupled with the tabmanger logic. I don't find it helpful to change so much in this PR. Maybe we can make more loosely coupled funcs in refactor.

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 15 above)
Comment (danishjafri88) [reply Client/Frontend/Settings/SettingsViewController.swift]: Updated the BoolRow class to take a custom `on Value Change` closure as param.

File: Client/Frontend/Browser/TabManager.swift (hunk 14 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/TabManager.swift]: What I'm saying is that this `ignorePrevious` is only used in this one case to select the already selected tab.

You could just do this:

```swift
let currentSelectedTab = selectedTab // Retain ref to the tab you want to "re"select
_selectedTab = -1 // Reset selected tab (now `selectedTab` returns nil)
selectTab(currentSelectedTab) // Select it
```

Comment (danishjafri88) [reply Client/Frontend/Browser/TabManager.swift]: Oh yeah, this solves it! Thanks :)

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 16]
```diff
@@ -23,8 +24,8 @@ extension TabBarVisibility: RepresentableOptionType {
 
 /// The same style switch accessory view as in Static framework, except will not be recreated each time the Cell
 /// is configured, since it will be stored as is in `Row.Accessory.view`
+fileprivate typealias ValueChange = (Bool) -> Void
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: One last random thing: why is this needed to be pulled out? 

You could just do this below in the `BoolRow` func: 
`... onValueChange: SwitchAccessoryView.ValueChange? = nil) -> Row {`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/UserContent/UserScripts/CookieControl.js [hunk 17]
```diff
@@ -0,0 +1,40 @@
+// The $<> is used to replace the var name at runtime with a random string.
+
+//Cookie should neither be saved nor accessed (local or session) when user has blocked all cookies.
+var $<cookie> = Object.getOwnPropertyDescriptor(Document.prototype, 'cookie') ||
```
Comment (jhreis) [inline Client/Frontend/UserContent/UserScripts/CookieControl.js:8]: Can you fix up the indentation a bit here? May need to use a 3rd party editor, but would be nice to keep clean.
(I know some of the other JS files aren't nice looking, but just leave those for now).

File: Client/Frontend/UserContent/UserScripts/CookieControl.js [hunk 18]
```diff
@@ -0,0 +1,40 @@
...
+Object.getOwnPropertyDescriptor(HTMLDocument.prototype, 'cookie');
+if ($<cookie> && $<cookie>.configurable) {
```
Comment (jhreis) [inline Client/Frontend/UserContent/UserScripts/CookieControl.js:10]: Why is `configurable` needed here but not for `localStorage` or `sessionStorage`?

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 16 above)
Comment (danishjafri88) [reply Client/Frontend/Settings/SettingsViewController.swift]: Pushed back in. I was trying to keep it loosely coupled so that load is faster. But yeah it wont matter much.

File: Client/Frontend/UserContent/UserScripts/CookieControl.js (hunk 17 above)
Comment (danishjafri88) [reply Client/Frontend/UserContent/UserScripts/CookieControl.js]: Tried many 3p editor all do the same thing with the standard format settings. 
screenshot 2019-01-23 at 9 44 09 pm

Comment (danishjafri88) [reply Client/Frontend/UserContent/UserScripts/CookieControl.js]: If this is all, I will push this

File: Client/Frontend/UserContent/UserScripts/CookieControl.js (hunk 18 above)
Comment (danishjafri88) [reply Client/Frontend/UserContent/UserScripts/CookieControl.js:10]: Configurable, if false, any attempts to delete the property or change its attributes  will fail. So it is just a check to make sure we don't attempt to change a non configurable property. 
LocalStorage and SessionStorage are readOnly, so not required.

File: Client/Frontend/UserContent/UserScripts/CookieControl.js (hunk 17 above)
Comment (danishjafri88) [reply Client/Frontend/UserContent/UserScripts/CookieControl.js:8]: Done :) Took some trick

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 19]
```diff
@@ -23,8 +24,9 @@ extension TabBarVisibility: RepresentableOptionType {
 
 /// The same style switch accessory view as in Static framework, except will not be recreated each time the Cell
 /// is configured, since it will be stored as is in `Row.Accessory.view`
+
 private class SwitchAccessoryView: UISwitch {
-    typealias ValueChange = (Bool) -> Void
+    fileprivate typealias ValueChange = (Bool) -> Void
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsViewController.swift]: This line change isn't necessary (since parent access control is `private`)

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/UserContent/UserScripts/CookieControl.js [hunk 20]
```diff
@@ -0,0 +1,40 @@
+// The $<> is used to replace the var name at runtime with a random string.
```
Comment (jhreis) [inline Client/Frontend/UserContent/UserScripts/CookieControl.js:5]: Should add the license header here, even though it is JS, it is original code from us.

File: Client/Frontend/ContentBlocker/BlocklistName.swift [hunk 21]
```diff
@@ -16,6 +16,7 @@ class BlocklistName: Hashable, CustomStringConvertible, ContentBlocker {
     static let tracker = BlocklistName(filename: "block-trackers")
     static let https = BlocklistName(filename: "upgrade-http")
     static let image = BlocklistName(filename: "block-images")
+    static let blockCookie = BlocklistName(filename: "block-cookies")
```
Comment (jhreis) [inline Client/Frontend/ContentBlocker/BlocklistName.swift]: `block` here is inferred.

**Review by kylehickinson — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
