### PR TITLE
Fix #6509: Buy / Send / Swap doesn't respect prefilled token network

### LINKED ISSUE #6509: Buy / Send / Swap doesn't respect prefilled token network
### Description: 

Buy / Send / Swap can be opened with a prefilled token, but use the currently selected network which may not match that token.

### Steps to Reproduce 
  1. Open Buy / Send / Swap and select Ethereum network
  2. Close Buy / Send / Swap and tap Solana Mainnet asset in Portfolio assets list
  3. Tap 'Buy' or 'Send' or 'Swap' on asset detail page
  4. Observe correct token selected, but Ethereum network displayed (token belongs to Solana).
      - Note: the balance will always be 0, so transaction can't be created.

**Actual result:** 

https://user-images.githubusercontent.com/5314553/204588142-5f758f3b-0482-456d-b990-92b96e972654.mov

**Expected result:**

Selected network should switch to prefilled token, or don't prefill the token.

**Reproduces how often:** 

Easy

**Brave Version:** 

v1.46 (22.11.28.21) or later

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by StephenHeaps**
## Summary of Changes
- When `BuyTokenStore`, `SendTokenStore`, or `SwapTokenStore` are opened with a `prefilledToken` that does not belong to the currently selected network, we switch to that network before assigning it as the selected token.

This pull request fixes #6509

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Make sure to have visible asset for multiple different networks in Portfolio.
2. Open asset detail view for any asset and tap buy/send/swap
3. Verify correct network is displayed
4. Switch network to a different network and dismiss buy/send/swap
5. Tap buy/send/swap
6. Verify correctly switches back to the token's network. 
7. Repeat from step 1 for each buy/send/swap button available for that token to verify the network switches correctly for buy, send and swap.
8. Start from step 2, but open asset detail view for a token on a different network that originally tested

## Screenshots:

https://user-images.githubusercontent.com/5314553/205174684-de4e9c88-93b8-4f4d-aed6-6e165c68201f.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

File: Sources/BraveWallet/Crypto/Stores/BuyTokenStore.swift [hunk 1]
```diff
@@ -152,6 +176,7 @@ public class BuyTokenStore: ObservableObject {
     
     let coin = await walletService.selectedCoin()
     selectedNetwork = await rpcService.network(coin)
+    await validatePrefilledToken(on: selectedNetwork) // selectedNetwork may change
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/BuyTokenStore.swift:179]: when there is no `prefilledToken` we dont need to validate the current selected network

Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Stores/BuyTokenStore.swift:179]: The function returns immediately if `prefilledToken` is nil

File: Sources/BraveWallet/Crypto/Stores/BuyTokenStore.swift [hunk 2]
```diff
@@ -57,14 +58,37 @@ public class BuyTokenStore: ObservableObject {
     self.rpcService = rpcService
     self.walletService = walletService
     self.assetRatioService = assetRatioService
-    self.selectedBuyToken = prefilledToken
+    self.prefilledToken = prefilledToken
```
Comment (nuo-xu) [inline Sources/BraveWallet/Crypto/Stores/BuyTokenStore.swift:61]: probably dont need this property at all as you just need to pass this value to `validatePrefilledToken` which will be called in updateInfo()
Same in send and swap

Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Stores/BuyTokenStore.swift:61]: I think it's better if we don't handle this at initialization of the store keep the initialization clean. If this store is initialized within the `body` of a SwiftUI view (ex. `NavigationLink` destination initializer), it could cause unwanted network switches for the user; worse if `NavigationLink` is used like this in a `List`.

**Review by nuo-xu — APPROVED** [review]
