### PR TITLE
Fix #4651: Added Drag drop for Favourites, and Disabled Widgets

### LINKED ISSUE #4651: browser crashing when moving/editing or adding `Favorites` via NTP
### Description: 

When either editing/adding or drag & dropping favorite tiles on `iOS 14`, brave will crash instantly. This is 100% reproducible on `iOS 14` only. Crashes aren't present in `iOS 15`. Found while running through https://github.com/brave/brave-ios/issues/4463. This also happens if you go into `Show More` and attempt to move around any of the `Favorites` in that view as well.

Crash Stack --> [Client-2021-12-07-164357.ips.beta.txt](https://github.com/brave/brave-ios/files/7671780/Client-2021-12-07-164357.ips.beta.txt)

### Steps to Reproduce
 
  1. install `1.33 (21.12.6.21)` via TF
  2. Skip onboarding and dismiss the modal popups re: Shields/Settings
  3. move around any of the `Favorites` under NTP (instant crash)
  4. edit and try saving any `Favorite` tile under NTP (instant crash)
  5. adding a new `Favorite` (instant crash)

**Actual result:** 

Crash Stack --> [Client-2021-12-07-164357.ips.beta.txt](https://github.com/brave/brave-ios/files/7671780/Client-2021-12-07-164357.ips.beta.txt)

**Expected result:**

Browser shouldn't be crashing when interacting with NTP tiles on `iOS 14`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible following the STR/Cases mentioned above.

**Brave Version:** 

* `1.33 (21.12.6.21)` 

**Device details:** 

* `iPhone 12` running `iOS 15.1.1` - **`Couldn't reproduce/working as expected`**
* `iPhone 6+` running `iOS 14.6` - **`Crashes instantly whenever moving Favorites`**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @Brandon-T @kylehickinson @soner-yuksel

### LINKED ISSUE #4685: disable the ability to move NTP `Favorite` tiles on `iOS 14`
### Description: 

Due to https://github.com/brave/brave-ios/issues/4651 and the complexity required to fix the issue in time, it was decided to disable the ability to move around `Favorite` tiles on the NTP for `iOS 14` devices.

### Steps to Reproduce

* see https://github.com/brave/brave-ios/issues/4651 STR that caused the crash
* ensure that you can't move around `Favorite` tiles under NTP
* ensure that you can still move around tiles under the `Favorite` section once you tap on the URL

**Actual result:** 

Brave crashing whenever attempting to move around the NTP Favorite tiles on `iOS 14`

**Expected result:**

Disabled the ability to move around tiles under NTP. Crash will be fixed at a later time via https://github.com/brave/brave-ios/issues/4651.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.33 (21.12.6.21)` 

**Device details:** 

* `iPhone 12` running `iOS 15.1.1` - **`Couldn't reproduce/working as expected`**
* `iPhone 6+` running `iOS 14.6` - **`Crashes instantly whenever moving Favorites`**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- This happens only on **iOS 14** right now.
- Widgets are `observing` the `Favourite` changes and causing a crash when dragging-and-dropping favourites on NTP.
- Widgets are `observing` the `Favourite` changes and causing a crash when editing, removing, or adding favourites to NTP.
- Widgets have been disabled entirely by this PR. The widgets code is retaining something in memory + the observer, and so a crash happens. Removing widgets fixes everything including all the random weird crashes.

This pull request fixes #4651

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by soner-yuksel — APPROVED** [review]

**Review by kylehickinson — CHANGES_REQUESTED** [review]
Can you open an issue to re-implement widget favourites and then add comments everywhere that needs to go back

File: Client/Application/NavigationRouter.swift [hunk 1]
```diff
@@ -80,7 +80,9 @@ enum NavigationPath: Equatable {
         case .deepLink(let link): NavigationPath.handleDeepLink(link, with: bvc)
         case .url(let url, let isPrivate): NavigationPath.handleURL(url: url, isPrivate: isPrivate, with: bvc)
         case .text(let text): NavigationPath.handleText(text: text, with: bvc)
-        case .widgetShortcutURL(let path): NavigationPath.handleWidgetShortcut(path, with: bvc)
+        case .widgetShortcutURL(let path):
+            print("WIDGETS DISABLED - DUE TO CRASH ON iOS 14!")
+            break //NavigationPath.handleWidgetShortcut(path, with: bvc)
```
Comment (kylehickinson) [inline Client/Application/NavigationRouter.swift]: Is this needed? This doesn't have anything to do with favourites FRC, no?

**Review by kylehickinson — APPROVED** [review]
