### PR TITLE
Fix #3491: Add New Menu UI

### LINKED ISSUE #3491: New Menu UI
Change the `•••` menu to display a scrollable modal which will allow for more dynamic actions within the menu.

Main differences:
- Starts half expanded, can be scrolled to full expansion
- Most screens are presented within the menu (with the exception of Playlist for the time being) and website actions
- Website actions are brought up to the main menu rather than living only within the Share With… menu

Expected behaviour of all actions within the new menu should match previous behaviour of old menu (Bookmarks bring up bookmarks, downloads brings up downloads, show desktop site loads desktop sites, etc. etc.)

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #3491 

This also changes private mode theming to only affect the main browser toolbars

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Verify all menu options from old design are available in the new design and function correctly
- Verify theming works as needed
- Verify VPN button toggles correctly, shows loading accordingly while connecting, and shows the correct on/off state when opening the menu
- **Note**:  #3672 moves the share with… button to the top, which will be inconsistent with screenshots below

## Screenshots:

| Old (NTP) | New (NTP) | 
| --- | --- | 
| Simulator Screen Shot - iPhone 12 Pro - 2021-05-06 at 11 00 48 | new menu |

| Old (Website) | New (Website) | 
| --- | --- | 
| Simulator Screen Shot - iPhone 12 Pro - 2021-05-06 at 11 00 52 | Simulator Screen Shot - iPhone 12 Pro - 2021-05-06 at 10 54 18 |

| Old (Website) | New (Website) Expanded | 
| --- | --- | 
| Simulator Screen Shot - iPhone 12 Pro - 2021-05-06 at 11 00 52 | Simulator Screen Shot - iPhone 12 Pro - 2021-05-06 at 10 54 20  |

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveUI/SwiftUI/TableCellButtonStyle.swift [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+import SwiftUI
+
+/// A button style that mimics a table cell being highlighted in the background
+public struct TableCellButtonStyle: ButtonStyle {
+  @Environment(\.colorScheme) private var colorScheme: ColorScheme
```
Comment (Brandon-T) [inline BraveUI/SwiftUI/TableCellButtonStyle.swift:11]: Can we put the `private` on a new line?

So:
```swift
@Environment(\.colorScheme)
private var colorScheme: ColorScheme
```

Not sure what you guys prefer but I think it is cleaner. We do it for `@objc`?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+        var body: some View {
+            VStack(alignment: .leading, spacing: 2) {
+                if let tab = tab {
+                    Text(verbatim: tab.displayTitle)
+                        .font(.callout)
+                        .fontWeight(.medium)
+                        .lineLimit(1)
+                        .foregroundColor(Color(Theme.of(nil).colors.tints.home))
+                }
+                Text(verbatim: url.baseDomain ?? url.absoluteDisplayString)
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift]: Maybe `url.baseDomain ?? url.host ?? url.absoluteDisplayString`? That way you attempt to get base domain else eTLD else display string?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: BraveUI/SwiftUI/TableCellButtonStyle.swift (hunk 1 above)
Comment (kylehickinson) [reply BraveUI/SwiftUI/TableCellButtonStyle.swift:11]: We as a team haven't really talked about what to do with property wrappers like we have for attributes. Funnily enough though `@objc` is one of the few attributes we decided to allow on same line since it was short lol

We could employ a similar rule for longer-property wrappers to be separated to a new line? Or property wrappers with arguments to a new line? Lets discuss with the team

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift (hunk 2 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift]: Good call, `absoluteDisplayString` only strips http/https so `host` is probably a better fallback

File: BraveUI/SwiftUI/TableCellButtonStyle.swift (hunk 1 above)
Comment (iccub) [reply BraveUI/SwiftUI/TableCellButtonStyle.swift:11]: What's the general consensus for it in SwiftUI community?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+import SwiftUI
+import BraveUI
+import Shared
+
+extension BrowserViewController {
+    func featuresMenuSection(_ menuController: MenuViewController) -> some View {
+        VStack(spacing: 0) {
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift:13]: What is default spacing for V/H stacks?

File: BraveUI/SwiftUI/TableCellButtonStyle.swift [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+  public init() { }
+  public func makeBody(configuration: Configuration) -> some View {
+    configuration.label
+      .contentShape(Rectangle()) // Needed or taps don't activate on empty space
+      .background(
+        Color(colorScheme == .dark ? .white : .black)
```
Comment (iccub) [inline BraveUI/SwiftUI/TableCellButtonStyle.swift:17]: Why not using our theme colors here? do we even have them for 'buttonstyle'

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 5]
```diff
@@ -1,405 +1,287 @@
...
 import BraveShared
 import BraveUI
+import SwiftUI
 
-private class MenuCell: UITableViewCell {
-    let iconView = UIImageView().then {
-        $0.snp.makeConstraints { make in
-            make.width.equalTo(50)
+struct MenuItemHeaderView: View {
+    @Environment(\.colorScheme) var colorScheme: ColorScheme
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:15]: This does not seem used here? and maybe make private if it is needed to be here

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 6]
```diff
@@ -1,405 +1,287 @@
...
+        // Issue: https://github.com/slackhq/PanModal/issues/139
+        false
     }
     
-    deinit {
-        NotificationCenter.default.removeObserver(self)
-    }
-    
-    // MARK: - Table view data source
+    private var isDismissing: Bool = false
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift]: Bool can be removed

**Review by iccub — CHANGES_REQUESTED** [review]
Found few problems in dark mode,
code looks nice overall

File: Client/Extensions/AppearanceExtensions.swift [hunk 7]
```diff
@@ -67,9 +67,6 @@ extension Theme {
         InsetButton.appearance(whenContainedInInstancesOf: [SearchSuggestionPromptView.self]).appearanceTextColor = colors.tints.home
         
         // Overrides all views inside of itself
-        // According to docs, UIWindow override should be enough, but some labels on iOS 13 are still messed up without UIView override as well
```
Comment (soner-yuksel) [inline Client/Extensions/AppearanceExtensions.swift:70]: The comment is so contradictory I wonder why did they add it to window before :)

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 8]
```diff
@@ -2483,11 +2494,26 @@ extension BrowserViewController: ToolbarDelegate {
...
+        let selectedTabURL: URL? = {
+            guard let url = tabManager.selectedTab?.url, !url.isLocal || url.isReaderModeURL else { return nil }
+            return url
+        }()
+        var activities: [UIActivity] = []
+        if let url = selectedTabURL, let tab = tabManager.selectedTab {
+            activities = shareActivities(for: url, tab: tab, sourceView: view, sourceRect: self.view.convert(self.topToolbar.menuButton.frame, from: self.topToolbar.menuButton.superview), arrowDirection: .up)
+        }
+        let menuController = MenuViewController(content: { menuController in
+            VStack(spacing: 6) {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController.swift]: do you think we should start adding these values in struct or unnecessary for single instance ?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+                MenuItemButton(icon: #imageLiteral(resourceName: "nav-share").template, title: Strings.shareWithMenuItem) {
+                    self.dismiss(animated: true)
+                    self.tabToolbarDidPressShare()
+                }
+            }
+        }
+    }
+    
+    struct MenuTabDetailsView: View {
+        @SwiftUI.Environment(\.colorScheme) var colorScheme: ColorScheme
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift:78]: https://github.com/brave/brave-ios/pull/3465/files#r605576363
Same comment applies here I guess

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift (hunk 5 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:15]: These are used to force SwiftUI to recompute the body of the View when the users system theme changes (as we don't have an observable "current" theme object anywhere)

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 10]
```diff
@@ -1,405 +1,287 @@
...
+    var action: () -> Void
+    
+    var body: some View {
+        Button(action: action) {
+            MenuItemHeaderView(icon: icon, title: title)
+                .padding(.horizontal, 14)
+                .frame(maxWidth: .infinity, minHeight: 48.0, alignment: .leading)
         }
+        .buttonStyle(TableCellButtonStyle())
+        .accentColor(Color(Theme.of(nil).colors.tints.home))
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift]: why do we use `.accentColor` here instead of `.background(`

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift (hunk 3 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift:13]: Default is based on context of views its encapsulating, where its placed, etc. unfortunately

File: BraveUI/SwiftUI/TableCellButtonStyle.swift (hunk 1 above)
Comment (kylehickinson) [reply BraveUI/SwiftUI/TableCellButtonStyle.swift:11]: @iccub In all of Apple's docs/usage, it is always same-line with exceptions for some of the longer more complex property wrappers that take multiple arguments like `FetchRequest`

File: Client/Extensions/AppearanceExtensions.swift (hunk 7 above)
Comment (kylehickinson) [reply Client/Extensions/AppearanceExtensions.swift:70]: Yeah I am not sure, keeping it unfortunately completely breaks SwiftUI re-render after color scheme changes

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 11]
```diff
@@ -1,405 +1,287 @@
...
-        self.bvc = bvc
-        self.tab = tab
-
-        super.init(nibName: nil, bundle: nil)
     }
     
-    @available(*, unavailable)
-    required init?(coder aDecoder: NSCoder) {
-        fatalError()
+    override var preferredStatusBarStyle: UIStatusBarStyle {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:135]: Just curious do we need need to set Status bar style for this controller ?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 12]
```diff
@@ -1,405 +1,287 @@
...
+            presentingViewController?.dismiss(animated: flag, completion: completion)
+        } else {
+            super.dismiss(animated: flag, completion: completion)
         }
     }
     
-    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
-        return visibleButtons.count
+    private var isPresentingInnerMenu: Bool {
+        if let _ = presentedViewController as? InnerMenuNavigationController {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift]: can we use is here instead 
`presentedViewController is InnerMenuNavigationController`

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift (hunk 10 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift]: This `accentColor` was to set colors of Toggle's to brave's orange, but it doesn't seem to work as Michal tested.

`background` places a `View` behind this view, which isn't what we wanted in this case

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift (hunk 9 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift:78]: > These are used to force SwiftUI to recompute the body of the View when the users system theme changes (as we don't have an observable "current" theme object anywhere)

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 8 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/BrowserViewController.swift]: I think it is unnecessary at the moment, as it is a small computed View. If the menu grows to be larger though we can always reconsider

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift (hunk 11 above)
Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:135]: It is to keep the status bar white when the user navigates to other VC's inside the menu

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 13]
```diff
@@ -1,405 +1,287 @@
...
-        let cell = { () -> MenuCell in
-            guard let button = MenuButtons(rawValue: indexPath.row) else {
-                assertionFailure("No cell with \(indexPath.row) tag.")
-                return MenuCell()
+}
+
+extension MenuViewController: PanModalPresentable {
+    var panScrollable: UIScrollView? {
+        // For SwiftUI:
+        //  - in iOS 13, ScrollView will exist within a host view
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:168]: Damn thats great info here 👏

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 14]
```diff
@@ -1,405 +1,287 @@
...
-                case .notPurchased, .purchased, .expired:
-                    break
-                case .installed(let enabled):
-                    menuCell.toggleButton.isOn = enabled
-                    menuCell.isLoading = BraveVPN.reconnectPending
+            for view in parentView.subviews {
+                if let scrollView = view as? UIScrollView {
+                    return scrollView
+                }
+                if !view.subviews.isEmpty, let childScrollView = _scrollViewChild(in: view, depth: depth + 1) {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:182]: I have 2 questions here,
- First one I guess we are doing this check for iOS 13 only, If thats the case can we mark it like that
- Second question is Can there be a situation where we have a scrollview as a direct subview and also scroll view within a hostview? If yes shouldnt we pick the scrollview which exists as direct subview ?

Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:182]: 1. Not 13 only, 14 can also have subviews as subview of the `view` when we create custom VC's that aren't UITVC's
2. Yes but we always want the top-level one we find since its the one that controls whether or not panning begins to open/close the pan modal. If its the direct view it will return a few lines above, otherwise we check 1 more level deep. Any other scrolls within are assumed to function separately. I guess one improvement would be to find the first one that scrolls vertically, but Im not sure how we could go about doing that

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 15]
```diff
@@ -1,405 +1,287 @@
...
-            case .history: return #imageLiteral(resourceName: "menu-history").template
-            case .settings: return #imageLiteral(resourceName: "menu-settings").template
-            case .add: return #imageLiteral(resourceName: "menu-add-bookmark").template
-            case .share: return #imageLiteral(resourceName: "nav-share").template
-            case .downloads: return #imageLiteral(resourceName: "menu-downloads").template
+        present(container, animated: true) {
+            self.panModalSetNeedsLayoutUpdate()
+        }
+        if expandToLongForm {
+            DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) {
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:109]: why do we delay while xpanding to long form ?

Comment (kylehickinson) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift:109]: Just makes the animation look nicer, I'll make a comment explaining 🙂

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift [hunk 16]
```diff
@@ -1,405 +1,308 @@
...
+        super.viewWillAppear(animated)
+        let animateNavBar = (navigationController?.isBeingPresented == false ? animated : false)
+        navigationController?.setNavigationBarHidden(true, animated: animateNavBar)
+        self.navigationController?.preferredContentSize = {
+            let controller = UIHostingController(rootView: self.rootView.content)
+            let size = controller.view.sizeThatFits(CGSize(width: 375, height: 0))
+            // Have to increase the content size by the hidden nav bar height so that the size
+            // doesn't change when the user navigates within the menu where the nav bar is visible
+            let navBarHeight = navigationController?.navigationBar.bounds.height ?? 0
+            return CGSize(width: 375, height: min(max(size.height + 16, 240), 580 + navBarHeight))
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift]: I see these 580 and 375 magic numbers in few places, would it be worth extracting to a constant?

**Review by iccub — CHANGES_REQUESTED** [review]

**Comment by kylehickinson** [comment]
Theme related issues will be solved in #3606

**Review by iccub — APPROVED** [review]
Needs 1 more rebase, code looks good

**Review by Brandon-T — APPROVED** [review]
