### PR TITLE
Fix #2202: Display correct publisher disclaimer for connected wallets

### LINKED ISSUE #2202: Incorrect message to a verified Brave creator on iOS (Testflight and production versions)
If a user on iOS is browser wallet (iOS does not support user wallets) opens a panel, the panel shows incorrect message about the creator.

see image below:
image

Expected:
No text is expected to be shown. A non user wallet should be able to tip all Brave verified creators, with our without an Uphold account, without an ID check.

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes issue #2202 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Panel messaging:

|  | Anon Wallet | User Wallet Connected (empty anon wallet) |
| --- | --- | --- |
| unverified publisher | not verified | not verified |
| wallet connected publisher | _nothing_ | not connected |
| verified publisher | _nothing_ | _nothing_ |

Where 
    - **not verified**:
    ```
    This creator has not yet signed up to receive contributions from Brave users. Any tips you send will remain in your wallet until they verify.
    ```
    - **not connected**
    ```
   This Brave Verified Creator has not yet configured their account to receive contributions from Brave Users. Any tips you send will remain in your wallet until they complete this process.
    ```

## Screenshots:

Publisher: `snow.fish`, status: `wallet_connected`

| Anon Panel | Anon Tip |
| --- | --- |
| no-user-wallet-connected-pub | no-user-wallet-connected-pub-tip |
| User Wallet Connected Panel | User Wallet Connected Tip |
| user-wallet-connected-pib | user-wallet-connected-pub-tip |

Publisher: `github.com`, status: `unverified`

| User Wallet Connected Panel | User Wallet Connected Tip |
| --- | --- |
| unverified-pub | unverified-pub-tip |

Publisher: `laurenwags.github.io`, status: `verified`

| User Wallet Connected Panel | User Wallet Connected Tip |
| --- | --- |
| verified | verified-tip |

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveRewardsUI/Localized Strings/Strings.swift [hunk 1]
```diff
@@ -156,6 +157,7 @@ internal extension Strings {
   static let learnMoreCreateWallet1 = NSLocalizedString("BraveRewardsLearnMoreCreateWallet1", bundle: .rewardsUI, value: "Yes, I'm In!", comment: "")
   static let learnMoreBraveAdsTitle = NSLocalizedString("BraveRewardsLearnMoreBraveAdsTitle", bundle: .rewardsUI, value: "Ads", comment: "")
   static let tippingUnverifiedDisclaimer = NSLocalizedString("BraveRewardsTippingUnverifiedDisclaimer", bundle: .rewardsUI, value: "NOTE: This creator has not yet signed up to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.", comment: "")
+  static let tippingNotConnectedDisclaimer = NSLocalizedString("BraveRewardsTippingUnverifiedDisclaimer", bundle: .rewardsUI, value: "NOTE: This Brave Verified Creator has not yet signed up to receive contributions from Brave users. Your browser will keep trying to contribute until they verify, or until 90 days have passed.", comment: "")
```
Comment (iccub) [inline BraveRewardsUI/Localized Strings/Strings.swift]: Rename string key

File: BraveRewardsUI/Tipping/TippingViewController.swift [hunk 2]
```diff
@@ -129,8 +129,21 @@ class TippingViewController: UIViewController, UIViewControllerTransitioningDele
           self.tippingView.overviewView.socialStackView.addArrangedSubview(UIImageView(image: UIImage(frameworkResourceNamed: $0.iconName)))
         })
       }
-      
-      self.tippingView.overviewView.disclaimerView.isHidden = banner.status == .verified
+    
+      if (state.ledger.walletBalances[.anonymous] ?? 0) > 0 || (state.ledger.walletBalances[.unblindedTokens] ?? 0) > 0 {
```
Comment (iccub) [inline BraveRewardsUI/Tipping/TippingViewController.swift]: We use this in two places, maybe extract to a computed property on ledger object?

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]

**Comment by kylehickinson** [comment]
Same test failures on CI, merging anyways
