### PR TITLE
Fix #3227: Implement History Sync

### LINKED ISSUE #3227: Implement History Sync
## Problem Description 

The iOS browser should sync relevant history entries (based on the same rules Chromium follows).

The iOS Sync Settings should provide a way to enable/disable different Sync types acting from iOS.

## Feature Overview 

- As Chromium rules suggest only "**typed_urls**" will be synced. Which means all the history will be added locally using core as   however entries from directed urls will not be synced with browser. All other rules related with History will stay the same on iOS side UI, the max number of items queried etc.

- Sync Settings will contain a new section which will allow user to toggle different Sync types according to users preference.

## Design 

History UI will stay the same however there will be a new section in Sync settings that has the Sync type toggles.

1 qq q

### Additional information

This implementation will also include "Delete All" functionality on History page so users can have a better place to interact the history deletion.

Ticket for Delete All: https://github.com/brave/brave-ios/issues/3723

### LINKED ISSUE #3591: rewards not being disabled when toggling off via rewards panel
### Description: 

There's a pretty bad bug/state where toggling/disabling rewards doesn't actually disable the feature/rewards. The toggle will slide to the disabled position, but rewards won't be disabled. It takes several attempts of disabling/enabling to get it disabled. However, even when you disable it, sometimes restarting the browser will re-enable it again. I've ran into pretty often/easily when running through https://github.com/brave/brave-ios/issues/3410. Reproduced it on the current version that's available in the AppStore as well.

### Steps to Reproduce
 
  1. launch the latest version of `1.25.x` via TF
  2. skip through all the onboarding modals/windows
  3. enable rewards and wait a few seconds
  4. restart the browser and try disabling rewards

If the above case doesn't work, just keep enabling/disabling rewards. You'll eventually get into the above state.

**Actual result:** 

Example of the issue occurring ---> https://youtu.be/SyuP_7Fc__M

**Expected result:**

Rewards shouldn't be that difficult to disable and should work every single time it's toggled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Pretty easy to reproduce. I can basically do it 100% of the time running through the above STR.

**Brave Version:** 

* `1.24 (21.4.1.15)` - **Reproduced**
* `1.25 (21.4.27.17)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.4.2` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.4.2` - **Reproduced**

**Website problems only:** `N/A`
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @kylehickinson @anthonypkeane @bsclifton @srirambv

### LINKED ISSUE #3721: Update history empty state UI
### Description: 

Currently when a user has no history, the list is empty and provides no empty state, we should add something to this screen so it is more obvious

### Screenshot/Design:

Here is a sample design for the empty State:

savelater

### LINKED ISSUE #3723: Add "Delete All" functionality to History Controller
### Description: 

Currently, there is no "Delete Entire History" functionality on History page itself. Users should have to navigate Settings -> Shields & Privacy -> Clear Data and mark Browsing History and execute Clear Data now.

The idea is to add new simple way to clear entire History inside the page.

**Actual result:** 

Only way is to clear the History on the page itself is to delete all entry one by one.

**Expected result:**

Add a "Delete All" bar button item on History Navigation bar and press it will show a action sheet alert for explainin the functionality and approval of the user.

**Screenshot:** 

deleteAll

### LINKED ISSUE #3869: Bump Brave Core library to 1.26.x
Specifically: https://github.com/brave/brave-browser/releases/v1.26.71

## Test Plan

Will be tested via manual passes of rewards/ads/sync

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Summary of Changes

This Pull Request contains 

- History Migration
- Sync Profile
- History Fetch/Add/Delete with Core and Sync
- Brave-Core Bump 1.26.x
- Delete All functionality on History
- Empty State for History 

###  History Migration:

We are adding history brave-core migration to our existing migrator used for bookmarks and making both of the sync types work together and handle error cases related for both of the types. So in future the new sync types can also use same migrator.

### History Fetch/Add/Delete/Remove with Core and Sync

A new HistoryFetcher is created where we perform the fetch from brave-core and various utility methods are created over the data. This fetcher is using Ordered Dictionary so in order to use this we added [Swift Collections](https://github.com/apple/swift-collections) package. Believe the utility brought with Swift Collections will also be useful for the rest of the application. https://swift.org/blog/swift-collections/

In addition old add delete methods are replaced with brave-core  functionality. 

### Sync Profile

Enable/Disable different Sync Types is added. Sync Settings will contain a new section which will allow user to toggle different Sync types according to users preference. This is using BraveSyncProfileService and it will also help when new sync types are added to give user ability to turn them on/off.

This pull request fixes #3227
This pull request fixes #3723
This pull request fixes #3721
This pull request fixes #3869
This pull request fixes #3591

Brave Core PR is merged and uplifted to 1.26.x and in addition this PR also handles the changes made in core to align history and bookmarks code.

Core PR For History Sync: https://github.com/brave/brave-core/pull/8869

Core PR For alignment: https://github.com/brave/brave-core/pull/9145

SecReview: https://github.com/brave/security/issues/501

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Test Migration: The test cases and conditions are same with bookmark. Try migration 3 times but for both history and bookmarks together in this case.

- Update application with existing History base
- Check migration is happened and data is same

Normal Add / Delete / Delete All 

- Fresh install or updated app
- Try Add history by entering urls or redirecting from other places
- Delete individual history
- Delete All history in History Screen

Test Sync: Same testing cases with bookmarks release but this time after joining to sync chain can actually turn on/off 
which type of sync should be enabled

- Can test turning on different sync types and check If their functionality can be turned on/off
- History Sync should be tested but keep in mind only typed urls is going to be synced from desktop to mobile also mobile to desktop 
- Migrated urls will be marked as types since we dont have informationa bout them so they should be synced

## Screenshots:

119523015-6b475a80-bd4a-11eb-99f3-f2daf41bf66a

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by aarsxx — APPROVED** [review]

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -2004,6 +2004,41 @@ extension Strings {
...
+        public static let historyMigrationErrorMessage =
+            NSLocalizedString("sync.historyMigrationErrorMessage", tableName: "BraveShared", bundle: .braveShared,
+                              value: "Failed to migrate hitory. Please try again later.",
+                              comment: "Message for popup when the history migration fails")
+        public static let syncConfigurationInformationText =
+            NSLocalizedString("sync.syncConfigurationInformationText", tableName: "BraveShared", bundle: .braveShared,
+                              value: "Manage what information you would like to sync between devices. These settings only affect this device.",
+                              comment: "Information Text underneath the toggles for enable/disable different sync types for the device")
+        public static let syncSettingsTitle =
+            NSLocalizedString("sync.syncConfigurationInformationText", tableName: "BraveShared", bundle: .braveShared,
```
Comment (Brandon-T) [inline BraveShared/BraveStrings.swift]: Duplicate key `sync.syncConfigurationInformationText` for both `syncConfigurationInformationText` and `syncSettingsTitle`

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Application/ClientPreferences.swift [hunk 2]
```diff
@@ -218,9 +218,19 @@ extension Preferences {
     }
     
     final class Chromium {
+        /// The boolean determine Bookmark Migration is finished on client side
         static let syncV2BookmarksMigrationCompleted = Option<Bool>(key: "chromium.migration.bookmarks", default: false)
-        static let syncV2BookmarksMigrationCount = Option<Int>(key: "chromium.migration.bookmarks.count", default: 0)
```
Comment (Brandon-T) [inline Client/Application/ClientPreferences.swift:226]: Are you sure we can delete this key and it is replaced with `syncV2ObjectMigrationCount` but has a different string/key?

File: Client/Application/Migration.swift [hunk 3]
```diff
@@ -22,13 +29,28 @@ class Migration {
...
+        if !isChromiumMigrationCompleted {
+            braveCoreSyncObjectsMigrator = BraveCoreMigrator()
         }
         
         if !Preferences.Migration.playlistV1FileSettingsLocationCompleted.value {
             movePlaylistV1Items()
         }
+        
+        // Adding Observer to enable sync types 
+        NotificationCenter.default.addObserver(
```
Comment (Brandon-T) [inline Client/Application/Migration.swift:47]: Maybe we can add the observer that uses `Publisher` instead? So we know for sure it is deleted  when the `deinit` is called.

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 4]
```diff
@@ -2056,11 +2021,11 @@ extension BrowserViewController: TabDelegate {
 extension BrowserViewController: SearchViewControllerDelegate {
     func searchViewController(_ searchViewController: SearchViewController, didSubmit query: String) {
         topToolbar.leaveOverlayMode()
-        processAddressBar(text: query)
+        processAddressBar(text: query, visitType: .typed)
     }
     
     func searchViewController(_ searchViewController: SearchViewController, didSelectURL url: URL) {
-        finishEditingAndSubmit(url, isBookmark: false)
+        finishEditingAndSubmit(url, visitType: .typed)
```
Comment (Brandon-T) [inline Client/Frontend/Browser/BrowserViewController.swift:2086]: A selected URL from suggestions or QRCode is considered `typed`?

File: Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift [hunk 5]
```diff
@@ -371,18 +371,18 @@ class NewTabPageViewController: UIViewController {
...
-              let creativeInstanceId = background.currentBackground?.wallpaper.creativeInstanceId else {
-            return
-        }
-        rewards.ads.reportNewTabPageAdEvent(
-            background.wallpaperId.uuidString,
-            creativeInstanceId: creativeInstanceId,
-            eventType: event
-        )
-    }
+//    private func reportSponsoredImageBackgroundEvent(_ event: NewTabPageAdEventType) {
```
Comment (Brandon-T) [inline Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: Why did we remove this?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client.xcodeproj/project.pbxproj [hunk 6]
```diff
@@ -12556,6 +12623,11 @@
 			package = 27F4798A25AF94B0004922E4 /* XCRemoteSwiftPackageReference "yubikit-ios" */;
 			productName = YubiKit;
 		};
+		2FCE87D4264195EC00B98D7E /* OrderedCollections */ = {
+			isa = XCSwiftPackageProductDependency;
+			package = 2FCE87D3264195EC00B98D7E /* XCRemoteSwiftPackageReference "swift-collections" */;
+			productName = OrderedCollections;
+		};
```
Comment (kylehickinson) [inline Client.xcodeproj/project.pbxproj]: `OrderedCollections` should be added as a library in `SPMLibraries`, not as a library in `Client`. This is to ensure that if another target wants to use anything in there we do not get a duplicate symbols error

File: Client/Application/Migration.swift [hunk 7]
```diff
@@ -7,11 +7,18 @@ import Shared
...
 
 class Migration {
-    private(set) public static var braveCoreBookmarksMigrator: BraveCoreMigrator?
+    
+    private(set) public static var braveCoreSyncObjectsMigrator: BraveCoreMigrator?
+
+    private(set) public static var isChromiumMigrationCompleted: Bool = {
+        return Preferences.Chromium.syncV2BookmarksMigrationCompleted.value &&
+            Preferences.Chromium.syncV2HistoryMigrationCompleted.value
+    }()
```
Comment (kylehickinson) [inline Client/Application/Migration.swift]: Doesn't need to be an assignment:

```suggestion
    public static var isChromiumMigrationCompleted: Bool {
        Preferences.Chromium.syncV2BookmarksMigrationCompleted.value &&
            Preferences.Chromium.syncV2HistoryMigrationCompleted.value
    }
```

File: Client/Application/Migration.swift [hunk 8]
```diff
@@ -22,13 +29,28 @@ class Migration {
...
         if !Preferences.Migration.playlistV1FileSettingsLocationCompleted.value {
             movePlaylistV1Items()
         }
+        
+        // Adding Observer to enable sync types 
+        NotificationCenter.default.addObserver(
+            self,
+            selector: #selector(enableUserSelectedTypesForSync), name: NSNotification.Name(rawValue: BraveServiceStateObserver.coreServiceLoadedNotification),
+            object: nil)
+    }
```
Comment (kylehickinson) [inline Client/Application/Migration.swift]: nit: weird spacing, `name` and the last parentheses should get dropped down to its own line

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 9]
```diff
@@ -1243,23 +1196,25 @@ class BrowserViewController: UIViewController {
...
             
             // Another Fix for: https://github.com/brave/brave-ios/pull/2296
             // Disable any sort of privileged execution contexts
             // IE: The user must explicitly tap a bookmark they have saved.
             // Block all other contexts such as redirects, downloads, embed, linked, etc..
-            webView.evaluateSafeJavaScript(functionName: code, sandboxed: false, asFunction: false) { _, error in
-                if let error = error {
-                    log.error(error)
+            if visitType == .bookmark {
+                if let webView = tab.webView, let code = url.bookmarkletCodeComponent {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: nit: These two if's can be combined since there is no control flow specific to either

File: Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift [hunk 10]
```diff
@@ -232,7 +232,7 @@ class NewTabPageViewController: UIViewController {
     override func viewDidAppear(_ animated: Bool) {
         super.viewDidAppear(animated)
         
-        reportSponsoredImageBackgroundEvent(.viewed)
+//        reportSponsoredImageBackgroundEvent(.viewed)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: Reason for removal?

File: Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift [hunk 11]
```diff
@@ -662,7 +662,7 @@ class NewTabPageViewController: UIViewController {
         UIImpactFeedbackGenerator(style: .medium).bzzt()
         delegate?.navigateToInput(logo.destinationUrl, inNewTab: false, switchingToPrivateMode: false)
         
-        reportSponsoredImageBackgroundEvent(.clicked)
+//        reportSponsoredImageBackgroundEvent(.clicked)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: Same as above

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift [hunk 12]
```diff
@@ -113,7 +113,7 @@ class AddEditBookmarkTableViewController: UITableViewController {
     
     // MARK: - Init
     
-    private var frc: BookmarksV2FetchResultsController
+    private var frc: BookmarksV2FetchResultsController?
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift:116]: Why is this optional now?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift [hunk 13]
```diff
@@ -9,219 +9,305 @@ import Storage
 import Data
 import CoreData
 
-private struct HistoryViewControllerUX {
-  static let welcomeScreenPadding: CGFloat = 15
-  static let welcomeScreenItemTextColor = UIColor.gray
-  static let welcomeScreenItemWidth = 170
-}
+// MARK: - HistoryViewController
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: Redundant mark

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift [hunk 14]
```diff
@@ -9,219 +9,305 @@ import Storage
...
+    }
+    
+    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
+        let cell = super.tableView(tableView, cellForRowAt: indexPath)
+        configureCell(cell, atIndexPath: indexPath)
+        
+        return cell
+    }
+    
+    func configureCell(_ _cell: UITableViewCell, atIndexPath indexPath: IndexPath) {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: nit: remove underscore from argument name

File: Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift [hunk 15]
```diff
@@ -16,9 +16,10 @@ private let log = Logger.browserLogger
 // with the same layout/interface as `Bookmark (from CoreData)`
 class Bookmarkv2: WebsitePresentable {
     private let bookmarkNode: BookmarkNode
-    private var observer: BookmarkModelListener?
-    private static let bookmarksAPI = BraveBookmarksAPI()
-    
+    private var bookmarkFavIconObserver: BookmarkModelListener?
+    private static var bookmarkModelLoadedObserver: BookmarkModelListener?
+    private static let bookmarksAPI = (UIApplication.shared.delegate as? AppDelegate)?.braveCore?.bookmarksAPI
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift:21]: This isn't really an optimal solution, we are just kicking the can from brave-core doing this via `GetApplicationContext` to us doing it ourselves using `UIApplication`. Needs an architecture shift to accept the bookmarks API as an init argument or something else

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 16]
```diff
@@ -28,11 +31,30 @@ class BraveCoreMigrator {
...
-        if Preferences.Chromium.syncV2BookmarksMigrationCompleted.value {
+        // Check If Chromium Sync Objects Migration is complete (Bookmarks-History)
+        if Migration.isChromiumMigrationCompleted {
             migrationObserver = .completed
         }
         
+        if let appDelegate = (UIApplication.shared.delegate as? AppDelegate) {
+            bookmarksAPI = appDelegate.braveCore?.bookmarksAPI
+            historyAPI = appDelegate.braveCore?.historyAPI
+        }
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift:64]: Same as above, this is not really a good solution

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 17]
```diff
@@ -12,14 +12,17 @@ import CoreData
 
 private let log = Logger.browserLogger
 
+// MARK: MigrationSyncTypes
+
+public enum MigrationSyncTypes {
+    case bookmarks
+    case history
+    case all
+}
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: After I looked over the usage of these I believe these are not useful in their current state. The only use you have for them at the moment are for failure cases, and it is a sequential failure, so if you fail one you return early and dont even try others. You also never actually check against the `.all` type. This pretty much matches a `throw`, so the proper implementation would to have an `Error` type.

Something like 

```swift
enum MigrationError: Error {
  case failedBookmarksMigration
  case failedHistoryMigration
}
```

You could also add reasons to each if you needed, as well as implement `localizedDescription` if you want for each case so that you dont even have to `switch` on them when creating the alerts to show the user on failure if you wanted.

Then the migration becomes

```swift
public func migrate(_ completion: (MigrationError?)? = nil) {
  ...
}
```

File: Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift [hunk 18]
```diff
@@ -0,0 +1,25 @@
...
+
+    // MARK: Private
+    
+    func postServiceLoadedNotification() {
+        NotificationCenter.default.post(
+            name: Notification.Name(rawValue: BraveServiceStateObserver.coreServiceLoadedNotification),
+            object: nil)
+        
+        BraveServiceStateObserver.isServiceLoadStatePosted = true
+    }
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift]: Don't quite understand this class, why is it the callers responsibility to check `isServiceLoadStatePosted` before calling this? Could it not just guard at the top before posting? Why is this post tracked specifically since it can be called from multiple spots? 

Also why is this an instance method but the state static?

File: Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift [hunk 19]
```diff
@@ -0,0 +1,25 @@
...
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import Foundation
+
+class BraveServiceStateObserver: NSObject {
+    
+    // MARK: Static
+    
+    static let coreServiceLoadedNotification = "BraveServiceStateDidLoaded"
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift]: This should be setup like this:

```
static let coreServiceLoadedNotification: Notification.Name = .init(rawValue: "BraveServiceStateDidLoaded")
```

File: Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift [hunk 20]
```diff
@@ -38,6 +40,23 @@ extension BraveSyncAPI {
         Preferences.Chromium.syncEnabled.value = false
     }
     
+    func enableSyncTypes() {
+        guard let syncProfileService =
+                (UIApplication.shared.delegate as? AppDelegate)?.braveCore?.syncProfileService else {
+            return
+        }
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift:47]: As mentioned in other places, this is not a good solution

File: Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift [hunk 21]
```diff
@@ -38,6 +40,23 @@ extension BraveSyncAPI {
...
+
+        syncProfileService.userSelectedTypes = []
+        
+        if Preferences.Chromium.syncBookmarksEnabled.value {
+            syncProfileService.userSelectedTypes.update(with: .BOOKMARKS)
+        }
+        
+        if Preferences.Chromium.syncHistoryEnabled.value {
+            syncProfileService.userSelectedTypes.update(with: .HISTORY)
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift:56]: How come these enum cases are all-caps?

File: Client/Frontend/Sync/BraveCore/History/HistoryServiceStateObserver.swift [hunk 22]
```diff
@@ -0,0 +1,49 @@
...
+        case serviceLoaded
+        case serviceDeleted
+        case historyVisited(HistoryNode)
+        case historyModified(_ nodeList: [HistoryNode])
+        case historyDeleted(_ nodeList: [HistoryNode], isAllHistory: Bool)
+    }
+    
+    init(_ listener: @escaping (StateChange) -> Void) {
+        self.listener = listener
+
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/History/HistoryServiceStateObserver.swift]: nit: empty line?

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift [hunk 23]
```diff
@@ -0,0 +1,221 @@
...
+import CoreData
+import Shared
+
+private let log = Logger.browserLogger
+
+struct Historyv2Section {
+    var title: String
+    
+    var numberOfObjects: Int
+}
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: I don't see this type used anywhere, can be removed?

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 24]
```diff
@@ -218,28 +236,59 @@ class SyncSettingsTableViewController: UITableViewController {
...
+                return configureInformationView(with: Strings.Sync.syncConfigurationInformationText)
+            default:
+                return nil
+        }
+    }
+
+    override func tableView(_ tableView: UITableView, heightForFooterInSection sectionIndex: Int) -> CGFloat {
+        switch sectionIndex {
+            case Sections.syncTypes.rawValue:
+                return UITableView.automaticDimension
```
Comment (kylehickinson) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift:262]: Does automatic dimension even work with footers this way?

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 25]
```diff
@@ -258,25 +307,57 @@ class SyncSettingsTableViewController: UITableViewController {
...
+            switch syncType {
+                case .bookmarks:
+                    return Preferences.Chromium.syncBookmarksEnabled.value
+                case .history:
+                    return Preferences.Chromium.syncHistoryEnabled.value
+            }
+        }
+    }
+    
+    private func configureInformationView(with info: String) -> UITextView {
```
Comment (kylehickinson) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift]: Name should probably be like `makeInformationTextView(with info: String)` instead

File: Shared/Extensions/URLExtensions.swift [hunk 26]
```diff
@@ -192,6 +192,22 @@ extension URL {
             return urlString
         }
     }
+    
+    public var typedDisplayString: String {
```
Comment (diracdeltas) [inline Shared/Extensions/URLExtensions.swift:199]: i assume the URL is already normalized to lowercase? might be good to have tests for this function

File: Shared/Extensions/URLExtensions.swift [hunk 27]
```diff
@@ -192,6 +192,22 @@ extension URL {
...
+        } else if urlString.hasPrefix("https://") {
+            urlString = String(urlString[urlString.index(urlString.startIndex, offsetBy: 8)...])
+        }
+        
+        if urlString.hasSuffix("/") {
+            urlString.removeLast()
+        }
+        
+        return urlString
+    }
```
Comment (kylehickinson) [inline Shared/Extensions/URLExtensions.swift]: 1. Missing documentation as to what this does
2. Missing tests around it

But why do we need this anyways?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveShared/BraveStrings.swift (hunk 1 above)
Comment (soner-yuksel) [reply BraveShared/BraveStrings.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/78c29884f6afce95aa286694b9316fb58c33734f

File: Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift (hunk 5 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: This probably happened while rebasing, no reason to touch here. Thanks for catching reverted.
Fix at https://github.com/brave/brave-ios/pull/3703/commits/967c3377c51d5f8b50dc447086da1b0ea0dec8c1

File: Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift (hunk 10 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: Reverted.
https://github.com/brave/brave-ios/pull/3703#discussion_r667122505

File: Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift (hunk 11 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/New Tab Page/NewTabPageViewController.swift]: Reverted.
https://github.com/brave/brave-ios/pull/3703#discussion_r667122505

File: Client/Application/Migration.swift (hunk 7 above)
Comment (soner-yuksel) [reply Client/Application/Migration.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/7b2245d8faec9661c2c7682df4c0f91cc229d06c

File: Client/Application/Migration.swift (hunk 8 above)
Comment (soner-yuksel) [reply Client/Application/Migration.swift]: Fix a https://github.com/brave/brave-ios/pull/3703/commits/7b2245d8faec9661c2c7682df4c0f91cc229d06c

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift (hunk 13 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/86bbfe1e0a6830bff924eebb8f33ee6518107585

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift (hunk 14 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/86bbfe1e0a6830bff924eebb8f33ee6518107585

File: Client/Frontend/Sync/BraveCore/History/HistoryServiceStateObserver.swift (hunk 22 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/History/HistoryServiceStateObserver.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/86bbfe1e0a6830bff924eebb8f33ee6518107585

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift (hunk 23 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: Yes this was part of scraped out implementation.
Fixed at https://github.com/brave/brave-ios/pull/3703/commits/86bbfe1e0a6830bff924eebb8f33ee6518107585

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift (hunk 25 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/SyncSettingsTableViewController.swift]: Fixed at https://github.com/brave/brave-ios/pull/3703/commits/86bbfe1e0a6830bff924eebb8f33ee6518107585

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 9 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift]: Fixed at https://github.com/brave/brave-ios/pull/3703/commits/86bbfe1e0a6830bff924eebb8f33ee6518107585

File: Client.xcodeproj/project.pbxproj (hunk 6 above)
Comment (soner-yuksel) [reply Client.xcodeproj/project.pbxproj]: True dat! Should have paid attention here.
Fixed at https://github.com/brave/brave-ios/pull/3703/commits/cecca1fb278994f80f272544cd37e41f5770b822

File: Shared/Extensions/URLExtensions.swift (hunk 27 above)
Comment (soner-yuksel) [reply Shared/Extensions/URLExtensions.swift]: The problem is according to visitType (checking if the visit type is .typed url) we need to record all the navigation that is made before we add history item. The reason is brave-core side only wants us to sync the typed urls. This is what we gather from browser and we are forced to mimic this behaviour. 

Inside the `func navigateInTab(tab: Tab, to navigation: WKNavigation? = nil)` is where the history registry is made before and I was careful not to make any changes to how url is retrieved and where it is being added.

`typedNavigation` is just a dictionary where the display url is the key and visitType is value. According to this url is from bookmarks, typed, linked etc.. the url key might be different because of scheme existence or the "/" suffix. So we have to strip out these from the url string, I wanted to use `absoluteDisplayString` however it was behaving differently when the url is not secure.

Test and documentation is added fix at https://github.com/brave/brave-ios/pull/3703/commits/e5d686c76f61778b93219063462a2703f7ab2bf4

File: Shared/Extensions/URLExtensions.swift (hunk 26 above)
Comment (soner-yuksel) [reply Shared/Extensions/URLExtensions.swift:199]: Yes this function already start the processing with absoluteString for the URL. Tests are added at https://github.com/brave/brave-ios/pull/3703/commits/e5d686c76f61778b93219063462a2703f7ab2bf4

Please check https://github.com/brave/brave-ios/pull/3703#discussion_r668010909 for additional details

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift (hunk 24 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/SyncSettingsTableViewController.swift:262]: Oh yes they do work like this perfectly, didnt have any problem with this approach. We have to also define footer height zero so first section will not have extra spacing we dont want. But If you have a different approach you wanted I can change this.

File: Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift (hunk 21 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift:56]: `BraveSyncUserSelectableTypes` defined in brave_sync_profile in brave_core and I guess we didnt think about swift conversion at that point.

File: Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift (hunk 15 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift:21]: We will address this issue as the first thing after implementation is merged.
https://github.com/brave/brave-ios/issues/3916

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift (hunk 16 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift:64]: Same as https://github.com/brave/brave-ios/pull/3703#discussion_r668082916

File: Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift (hunk 20 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveSyncAPI+Utilities.swift:47]: And same as https://github.com/brave/brave-ios/pull/3703#discussion_r668082916, evry bookmark and history API usage will be addressed.

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift (hunk 12 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift:116]: Because `Bookmarkv2ExclusiveFetcher` is working with bookmarksAPI and we are currently fetching it from AppDelegate over bravecore property.

It will be addressed with #3916 after the changes .

File: Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift (hunk 18 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift]: Because to enableDifferent Sync Types we have to be sure brave-core service is loaded and ready to be used. We add an observer (BraveServiceStateObserver.coreServiceLoadedNotification) to enable User Selected Types For Sync. And this can happen either bookmarksAPI is loaded or historyAPI receives isBackEndloaded. So both `HistoryServiceStateObserver` and `BookmarkModelStateObserver` are BraveServiceStateObservers.

But you are right this can be guarded before posting so Fix at https://github.com/brave/brave-ios/pull/3703/commits/63c2ed3fef842469b56604858a6a0a83990deb66

File: Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift (hunk 19 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveServiceStateObserver.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/63c2ed3fef842469b56604858a6a0a83990deb66

File: Shared/Extensions/URLExtensions.swift (hunk 27 above)
Comment (Brandon-T) [reply Shared/Extensions/URLExtensions.swift]: `url.schemelessAbsoluteString` might help?

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift (hunk 17 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: Thats a great observation, thanks for checking it deeply. I did it like this way because I would like to add async migration between different types so one type will not wait for the other. Actually I have the code implemented but I had problem with DCHECK On brave-core side.

Changes made as you suggested which includes the CoreMigration method using interstitialspage.
Fix at https://github.com/brave/brave-ios/pull/3703/commits/0c734ac8b97c639db3100e17e1a12a675caf7433

File: Client/Application/Migration.swift (hunk 3 above)
Comment (soner-yuksel) [reply Client/Application/Migration.swift:47]: Oh we should certainly get rid of the notification center and use combine here. If it is alright I would like to do this while we are handling the Observer API changes in core side with this ticket.
https://github.com/brave/brave-ios/issues/3757

File: Client/Application/ClientPreferences.swift (hunk 2 above)
Comment (soner-yuksel) [reply Client/Application/ClientPreferences.swift:226]: Yes because syncV2ObjectMigrationCount is the count for number for how many times the migration failed so In out situation after user upgraded their app version, the migration process will work again for the history items.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 4 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController.swift:2086]: Selected URL from suggestions is always considered typed URL before we removed VisitType from the app. but the QRCode is a great point I didnt think about or consider.

However IMO the QR code should be also considered as typed since the user is scanning this code and making app open a URL. I feel like this is something we should be syncing. Please let me know If you think differently.

File: Shared/Extensions/URLExtensions.swift (hunk 27 above)
Comment (soner-yuksel) [reply Shared/Extensions/URLExtensions.swift]: Changed the implementation using `schemelessAbsoluteString`
Fix at https://github.com/brave/brave-ios/pull/3703/commits/382666ee2b53cd730e44b957254c81880e89757b

File: Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved [hunk 28]
```diff
@@ -64,6 +64,42 @@
...
+          "version": "0.4.3"
+        }
+      },
+      {
+        "package": "swift-collections",
+        "repositoryURL": "https://github.com/apple/swift-collections",
+        "state": {
+          "branch": null,
+          "revision": "2d719d75a2065f213e58a5164384a3d2fcf9b59a",
+          "version": "0.0.2"
```
Comment (kylehickinson) [inline Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved]: Can you update this, its at `0.0.4` now, it'll save us a commit later when Xcode resolves it to a new version and wants us to commit the change (File > Swift Packages > Update to Latest) or just remove it and re-add it :)

File: Client/Frontend/Browser/FrequencyQuery.swift [hunk 29]
```diff
@@ -0,0 +1,41 @@
...
+                .map { Site(url: $0.url ?? "", title: $0.title ?? "") }
+            
+            cancellable = DispatchWorkItem {
+                // brave-core fetch can be slow over 200ms per call,
+                // a cancellable serial queue is used for it.
+                DispatchQueue.main.async {
+                    let bookmarkSites = Bookmarkv2.byFrequency(query: query)
+                        .map { Site(url: $0.url ?? "", title: $0.title ?? "", bookmarked: true) }
+
+                    let result = Set<Site>(historySites+bookmarkSites)
```
Comment (Brandon-T) [inline Client/Frontend/Browser/FrequencyQuery.swift]: `historySites + bookmarkSites` (space).

File: Client/Frontend/Browser/FrequencyQuery.swift [hunk 30]
```diff
@@ -0,0 +1,41 @@
...
+        
+        Historyv2.byFrequency(query: query) { historyList in
+            let historySites = historyList
+                .map { Site(url: $0.url ?? "", title: $0.title ?? "") }
+            
+            cancellable = DispatchWorkItem {
+                // brave-core fetch can be slow over 200ms per call,
+                // a cancellable serial queue is used for it.
+                DispatchQueue.main.async {
+                    let bookmarkSites = Bookmarkv2.byFrequency(query: query)
```
Comment (Brandon-T) [inline Client/Frontend/Browser/FrequencyQuery.swift:27]: Does the Brave-Core that History Sync is in, also contain the Bookmark `byFrequency` fix which uses completion block like `History.byFrequency` OR will that be next release?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 31]
```diff
@@ -12,14 +12,25 @@ import CoreData
...
+    case failedBookmarksMigration
+    case failedHistoryMigration
     
-    @Observable
-    private(set) public var migrationObserver: MigrationState = .notStarted
+    public var errorDescription: String? {
+        switch self {
+        case .failedBookmarksMigration:
+            return Strings.Sync.v2MigrationErrorMessage
+            case .failedHistoryMigration:
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: nit: random tab

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 32]
```diff
@@ -12,14 +12,25 @@ import CoreData
 
 private let log = Logger.browserLogger
 
-class BraveCoreMigrator {
+// MARK: MigrationError
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: nit: redundant mark

fyi, Xcode will automatically add implicit mark's for all types defined in the file, so any mark added above it that is the same name will just result in a double mark in the file navigator.

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 33]
```diff
@@ -12,14 +12,25 @@ import CoreData
...
+
+public enum MigrationError: LocalizedError {
```
Comment (kylehickinson) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: No need to be `public` since this exists in Client

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/FrequencyQuery.swift (hunk 30 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/FrequencyQuery.swift:27]: I forgot to uplift your fix to 1.26.x. Thats why we dont have the change here but when we fetch core 1.27+, wI will make a change here with it.

File: Client/Frontend/Browser/FrequencyQuery.swift (hunk 29 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/FrequencyQuery.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/5a29a500e8f7ced107114ae9ca5ed26dd743fdcd

File: Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved (hunk 28 above)
Comment (soner-yuksel) [reply Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/5a29a500e8f7ced107114ae9ca5ed26dd743fdcd Updated. :)

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift (hunk 31 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/5a29a500e8f7ced107114ae9ca5ed26dd743fdcd

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift (hunk 32 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: The reason I am used to adding the MARK for all types defined in the file is I am very used to using `Minimap` on Xcode and it provides me a very fast navigation and If you will not write the mark, map will not be so useful. But I understand confusion with FileNavigator, I will be careful from now on.

Fix at https://github.com/brave/brave-ios/pull/3703/commits/5a29a500e8f7ced107114ae9ca5ed26dd743fdcd

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift (hunk 33 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/5a29a500e8f7ced107114ae9ca5ed26dd743fdcd

**Review by kylehickinson — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift [hunk 34]
```diff
@@ -7,6 +7,28 @@ import Shared
 import WebKit
 import Storage
 
+// MARK: VisitType
+
+enum VisitType: Int {
+    case unknown
+    /**
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift]: We use `///` for documentation in the app, can change it to match our style

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift [hunk 35]
```diff
@@ -9,224 +9,302 @@ import Storage
...
+    }
+    
+    override func viewWillAppear(_ animated: Bool) {
+        super.viewWillAppear(animated)
+        
+        refreshHistory()
+    }
+    
+    private func refreshHistory() {
+        guard !isHistoryRefreshing else {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: maybe convert to `if`?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift [hunk 36]
```diff
@@ -9,224 +9,302 @@ import Storage
...
+        return overlayView
+    }
+    
+    fileprivate func updateEmptyPanelState() {
+        if  historyFRC?.fetchedObjectsCount == 0 {
+            if emptyStateOverlayView.superview == nil {
+                tableView.addSubview(emptyStateOverlayView)
+                emptyStateOverlayView.snp.makeConstraints { make -> Void in
+                    make.edges.equalTo(tableView)
+                    make.size.equalTo(view)
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: are those 2 constraints not in conflict? no runtime errors when its added?

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift [hunk 37]
```diff
@@ -9,224 +9,302 @@ import Storage
...
+        
+        cell.do {
+            $0.backgroundColor = UIColor.clear
+            $0.setLines(historyItem.title, detailText: historyItem.url)
+            
+            $0.imageView?.contentMode = .scaleAspectFit
+            $0.imageView?.image = FaviconFetcher.defaultFaviconImage
+            $0.imageView?.layer.borderColor = BraveUX.faviconBorderColor.cgColor
+            $0.imageView?.layer.borderWidth = BraveUX.faviconBorderWidth
+            $0.imageView?.layer.cornerRadius = 6
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift:194]: Can add `layer.cornerCurve = .continuous` here

File: Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift [hunk 38]
```diff
@@ -309,24 +359,28 @@ extension Bookmarkv2 {
...
+        }
+        
         if bookmarksAPI.isLoaded {
             DispatchQueue.main.async {
                 completion()
             }
         } else {
-            var observer: BookmarkModelListener?
-            observer = Bookmarkv2.bookmarksAPI.add(BookmarkModelStateObserver({
+            //var observer: BookmarkModelListener?
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift]: is this still needed?

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift [hunk 39]
```diff
@@ -261,7 +267,136 @@ class BraveCoreMigrator {
...
+    private func performHistoryMigrationIfNeeded(_ completion: ((Bool) -> Void)?) {
+        log.info("Migrating to Chromium History v1 - Start")
+        migrateHistory() { success in
+            Preferences.Chromium.syncV2HistoryMigrationCompleted.value = success
+            completion?(success)
+        }
+    }
+    
+    private func migrateHistory(_ completion: @escaping (_ success: Bool) -> Void) {
+        DataController.performOnMainContext { context in
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift:307]: I wonder if this will be a performance problem, imagine users using Brave daily for 5 years, the history DB will be huge right

File: Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift [hunk 40]
```diff
@@ -0,0 +1,147 @@
...
+    }
+    
+    var sectionCount: Int {
+        return sectionDetails.elements.filter { $0.value > 0 }.count
+    }
+    
+    func performFetch(_ completion: @escaping () -> Void) {
+        clearHistoryData()
+        
+        historyAPI?.search(withQuery: "", maxCount: 0, completion: { [weak self] historyNodeList in
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift]: `maxCount = 0` means no there's no fetch limit? Is this performant enough?

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift [hunk 41]
```diff
@@ -0,0 +1,215 @@
...
+    
+    /// Sections in History List to be displayed
+    enum Section: Int, CaseIterable {
+        /// History happened Today
+        case today
+        /// History happened Yesterday
+        case yesterday
+        /// History happened between yesterday and end of this week
+        case lastWeek
+        /// History happaned
```
Comment (iccub) [inline Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: typo, and it happened when exactly? can update this comment

File: Data/models/History.swift [hunk 42]
```diff
@@ -134,6 +110,13 @@ public final class History: NSManagedObject, WebsitePresentable, CRUD {
         
         return all(where: predicate, fetchLimit: 100, context: DataController.viewContext) ?? []
     }
+    
+    public class func fetchAllHistory(_ context: NSManagedObjectContext? = nil, visitedAscending: Bool = false) -> [History] {
+        let predicate = NSPredicate(format: "visitedOn >= %@", History.thisMonth as CVarArg)
```
Comment (iccub) [inline Data/models/History.swift:121]: does it fetch all history or last months history?

**Review by iccub — APPROVED** [review]
few questions and nitpicks, code looks very good in general

**Review by aarsxx — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift (hunk 34 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+ReaderMode.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/859375beafc1a0b1778a58dd79cb21c16bacd6cf

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift (hunk 36 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/859375beafc1a0b1778a58dd79cb21c16bacd6cf

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift (hunk 37 above)
Comment (soner-yuksel) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift:194]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/859375beafc1a0b1778a58dd79cb21c16bacd6cf

File: Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift (hunk 38 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/Bookmarks/Bookmarkv2.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/859375beafc1a0b1778a58dd79cb21c16bacd6cf

File: Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift (hunk 40 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift]: Great catch, this has be "200" like we are doing before.

Fix at https://github.com/brave/brave-ios/pull/3703/commits/859375beafc1a0b1778a58dd79cb21c16bacd6cf

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift (hunk 41 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/History/Historyv2.swift]: Fix at https://github.com/brave/brave-ios/pull/3703/commits/859375beafc1a0b1778a58dd79cb21c16bacd6cf

File: Data/models/History.swift (hunk 42 above)
Comment (soner-yuksel) [reply Data/models/History.swift:121]: This fetches last months history from old History data and being used while migrating existing history to core history. This is the portion we were showing to our users so it makes sense to only migrate this part.

File: Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift (hunk 39 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/BraveCoreMigrator.swift:307]: It will not create a problem cause only the visual portion we show to user which is last month's history is migrated.
Please check comment  https://github.com/brave/brave-ios/pull/3703#discussion_r677619942

Also addHistory method from brave-core has to be called in main thread.

File: Data/models/History.swift (hunk 42 above)
Comment (iccub) [reply Data/models/History.swift:121]: sounds fine to me, although i would update method name or add a documentation comment that it fetches last month only

Comment (soner-yuksel) [reply Data/models/History.swift:121]: Method name and updated documentation comments
Please check at https://github.com/brave/brave-ios/pull/3703/commits/d643b01dc714abb7710d5d699b766a9c7232ac1a

**Review by iccub — APPROVED** [review]

**Review by aarsxx — APPROVED** [review]

**Comment by iccub** [comment]
Need rebase, i merged bunch of code recently

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift [hunk 43]
```diff
@@ -0,0 +1,215 @@
...
+// MARK: History Fetching
+
+extension Historyv2 {
+
+    public class func add(url: URL, title: String, dateAdded: Date, isURLTyped: Bool = true) {
+        guard let historyAPI = Historyv2.historyAPI else {
+            return
+        }
+
+        let historyNode = HistoryNode(url: url, title: title, dateAdded: dateAdded)
```
Comment (jumde) [inline Client/Frontend/Sync/BraveCore/History/Historyv2.swift:127]: @soner-yuksel - iOS supports special URLs and external URLs as well. `about:` | `mailto:` and `tel:` URLs. Do you know if these URLs are filtered before adding to the sync chain?

**Comment by soner-yuksel** [comment]
The security review is ongoing. Merging this to unblock feature core requirements. If any issue arose in security review there will be upcoming Pull Request.

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift [hunk 44]
```diff
@@ -39,85 +36,141 @@ class SyncSettingsTableViewController: UITableViewController {
...
-        let view = SyncSelectDeviceTypeViewController()
-        view.syncInitHandler = { title, type in
-            let view = SyncAddDeviceViewController(title: title, type: type)
-            view.doneHandler = {
-                self.navigationController?.popToViewController(self, animated: true)
+    private func presentAlertPopup(for type: DeviceRemovalType, device: BraveSyncDevice) {
+        var title: String?
+        var message: String?
+        var removeButtonName: String?
+        let deviceName = device.name ?? Strings.syncRemoveDeviceDefaultName
```
Comment (jumde) [inline Client/Frontend/Sync/SyncSettingsTableViewController.swift:110]: @soner-yuksel - do you know if the `device-name` is sanitized before presenting in UI? I've come across cases where `<script>` tags in device name causes script execution.

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift (hunk 43 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/BraveCore/History/Historyv2.swift:127]: So the condition of the where the `add` is used is not changed. Only how we add is changed in this context.
History `add` is used inside `func navigateInTab(tab: Tab, to navigation: WKNavigation? = nil) `

And the conditions are 
`if !url.isErrorPageURL, !url.isAboutHomeURL, !url.isFileURL 
`
https://github.com/brave/brave-ios/blob/7391ecf4a767241a9bf0461006b96275b9b3902e/Client/Frontend/Browser/BrowserViewController.swift#L1837

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift (hunk 44 above)
Comment (soner-yuksel) [reply Client/Frontend/Sync/SyncSettingsTableViewController.swift:110]: This was an existing method which was moved in the file from previous position.
However the device_name is not a user entry field, it is fetched using `BraveSyncAPI` and underneath this information is fetched from `DeviceInfoSyncServiceFactory`

File: Client/Frontend/Sync/BraveCore/History/Historyv2.swift (hunk 43 above)
Comment (jumde) [reply Client/Frontend/Sync/BraveCore/History/Historyv2.swift:127]: This looks good. I think we should add `externalURL` to this list. I can file a follow-up issue for that? Let me know if you disagree.

File: Client/Frontend/Sync/SyncSettingsTableViewController.swift (hunk 44 above)
Comment (jumde) [reply Client/Frontend/Sync/SyncSettingsTableViewController.swift:110]: I verified that the `device-name` is not sanitized. I wasn't able to cause an injection, but as a defense in depth strategy what do you think about encoding the string before printing out the device name.
