### PR TITLE
Fix #2650: Save favicons in in-memory db in private mode.

### LINKED ISSUE #2650: Favicons not showing in private mode
### Steps to Reproduce 
  1. Visit neowin.net in normal mode
  2. Switch to pbm
  3.Start typing neowin in url bar

**Actual result:** 
Monogram is shown instead of proper favicon

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
Use fallback persisted favicon in no in-memory favicon exists.

Sec review https://github.com/brave/security/issues/181

## Summary of Changes

This pull request fixes #2650 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/FaviconHandler.swift [hunk 1]
```diff
@@ -46,10 +46,7 @@ class FaviconHandler {
             guard let tab = tab else { return }
             
             tab.favicons.append(favicon)
-            if !tab.isPrivate {
-                FaviconMO.add(favicon, forSiteUrl: currentURL)
-                
-            }
+            FaviconMO.add(favicon, forSiteUrl: currentURL, isPrivateBrowsing: tab.isPrivate)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/FaviconHandler.swift]: Maybe can do `isPrivateBrowsing` → `persistent` to match Domain.getOrCreate?

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift [hunk 2]
```diff
@@ -237,8 +238,22 @@ class FaviconFetcher {
...
+        // 1. Check if current domain has a favicon.
+        var correctFavicon = domain.favicon
+        
+        // 2. Private mode uses their own in-memory only favicons.
+        // If no in-memory favicon is found we look if there's any persisted one(from normal browsing mode)
+        // and use that one until in-memory favicon is saved.
+        if correctFavicon == nil,
+            PrivateBrowsingManager.shared.isPrivateBrowsing,
+            let urlString = domain.url,
+            let url = URL(string: urlString) {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favicons/FaviconFetcher.swift]: We can just give `Domain.getPersistedDomain` `self.url` instead of computing based on `domain` (this is what we use to make `domain` in `FaviconFetcher.init`)

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift [hunk 3]
```diff
@@ -237,8 +238,22 @@ class FaviconFetcher {
     }
     
     private func fetchIcon(_ completion: @escaping (URL, FaviconAttributes) -> Void) {
+        // Fetch icon logic:
+        // 1. Check if current domain has a favicon.
+        var correctFavicon = domain.favicon
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Favicons/FaviconFetcher.swift]: Maybe lets use `domainFavicon`

File: Data/models/Domain.swift [hunk 4]
```diff
@@ -59,6 +59,12 @@ public final class Domain: NSManagedObject, CRUD {
         return getOrCreateInternal(url, context: context, saveStrategy: saveStrategy)
     }
     
+    /// Returns saved Domain for url or nil if it doesn't exist.
+    /// Always called on main thread context.
+    public class func getPersistedDomain(for url: URL) -> Domain? {
+        Domain.first(where: NSPredicate(format: "url == %@", url.domainURL.absoluteString))
+    }
```
Comment (kylehickinson) [inline Data/models/Domain.swift:66]: Not sure if we need a unit test for this?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]

File: Data/models/FaviconMO.swift [hunk 5]
```diff
@@ -15,16 +15,18 @@ public final class FaviconMO: NSManagedObject, CRUD {
...
             if item == nil {
                 item = FaviconMO(entity: FaviconMO.entity(context), insertInto: context)
                 item!.url = favicon.url
             }
             if item?.domain == nil {
+                let strategy: Domain.SaveStrategy = persistent ?.delayedPersistentStore : .inMemory
+                
                 item!.domain = Domain.getOrCreateInternal(siteUrl, context: context,
-                                                          saveStrategy: .delayedPersistentStore)
+                                                          saveStrategy: strategy)
```
Comment (jumde) [inline Data/models/FaviconMO.swift:29]: @iccub - The `in-memory` db is not cleared when a user exits PBM, so favicons for sites browsed in private browsing mode will be available in the normal browsing mode. Let me know if I'm missing something.

Comment (iccub) [reply Data/models/FaviconMO.swift:29]: We never user in-memory db for anything in normal browsing mode.

You are right with not clearing the in-memory on exit, I thought we do it, it is cleared on app relaunch

Comment (jumde) [reply Data/models/FaviconMO.swift:29]: Clearing the `in-memory` data on transitioning from normal to PBM makes sense. If not, users will be able to see the browsing history on re-transitioning to the PBM.

Comment (jumde) [reply Data/models/FaviconMO.swift:29]: Follow-up issue: https://github.com/brave/brave-ios/issues/2656

**Review by jumde — APPROVED** [review]
