### PR TITLE
Fix #721: Lock settings portrait orientation on iPhones.

### LINKED ISSUE #721: Disable orientation change for Sync screens on iPhone
### Steps to Reproduce 
  1. Launch sync in horizontal mode

**Actual result:** 
zrzut ekranu 2019-01-15 o 13 40 50

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
We agreed with @jhreis to bring back 1.6 behavior and lock settings screens in portrait orientation. This also fixes layout issues for Sync screens.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adaquate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Settings/SettingsNavigationController.swift [hunk 1]
```diff
@@ -18,6 +18,18 @@ class SettingsNavigationController: UINavigationController {
     override var preferredStatusBarStyle: UIStatusBarStyle {
         return .default
     }
+    
+    override var supportedInterfaceOrientations : UIInterfaceOrientationMask {
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsNavigationController.swift]: nit: Space between `:` (on all 3 methods), I think this will cause warnings in SwiftLint?

File: Client/Frontend/Settings/SettingsNavigationController.swift [hunk 2]
```diff
@@ -18,6 +18,18 @@ class SettingsNavigationController: UINavigationController {
...
+        return UIInterfaceOrientationMask.portrait
+    }
+    
+    override var shouldAutorotate : Bool {
+        return false
+    }
+    
+    override var preferredInterfaceOrientationForPresentation : UIInterfaceOrientation {
+        return UIInterfaceOrientation.portrait
```
Comment (kylehickinson) [inline Client/Frontend/Settings/SettingsNavigationController.swift]: nit:
```suggestion
        return .portrait
```

**Review by kylehickinson — CHANGES_REQUESTED** [review]
All good functionally, just some minor nit's :)

File: Client/Frontend/Settings/SettingsNavigationController.swift (hunk 1 above)
Comment (iccub) [reply Client/Frontend/Settings/SettingsNavigationController.swift]: You are right, it didn't show any warning to me :( fixing

**Review by kylehickinson — APPROVED** [review]
