### PR TITLE
Fix #2671: Fix crash when opening fav in PBM from NTP/Fav overlay

### LINKED ISSUE #2671: Brave crashes when open top-tiles via `Open in New Private Tab`
### Description: 
Brave crashes when open top-tiles via `Open in New Private Tab`

### Steps to Reproduce 
  1. Clean profile 1.18 (20.6.24.15)
  2. Skip the onboarding flow
  3. Long press on any one of the top tile and select the option `Open in New Private tab`
  4. Brave crashes

**Actual result:** 
Brave crashes

**Expected result:**

should not be any crash
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.18 (20.6.24.15)

**Device details:** 

iPhone 8 - IOS 13.3.1
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @bsclifton @anthonypkeane @brave/legacy_qa

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes #2671

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Favorites/FavoritesViewController.swift [hunk 1]
```diff
@@ -279,7 +279,9 @@ extension FavoritesViewController: UICollectionViewDataSource, UICollectionViewD
             var urlChildren: [UIAction] = [openInNewTab]
             if !PrivateBrowsingManager.shared.isPrivateBrowsing {
                 let openInNewPrivateTab = UIAction(title: Strings.openNewPrivateTabButtonTitle, image: nil, identifier: nil, discoverabilityTitle: nil) { _ in
-                    self.action(bookmark, .opened(inNewTab: true, switchingToPrivateMode: true))
+                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
+                        self.action(bookmark, .opened(inNewTab: true, switchingToPrivateMode: true))
```
Comment (iccub) [inline Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: Why it crashes without it?

Comment (kylehickinson) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: The action occurs which removes the NTP/Overlay, when that happens and the context menu tries to dismiss its preview, the view doesn't exist to animate back to, which crashes here: https://github.com/brave/brave-ios/blob/184fc8f4864636e7dbbd03a5c45c3524d9b7273a/Client/Frontend/Browser/Favorites/FavoritesViewController.swift#L310

Comment (iccub) [reply Client/Frontend/Browser/Favorites/FavoritesViewController.swift]: Sounds good, can add a comment about it

**Review by iccub — APPROVED** [review]
