### PR TITLE
Fix #6475: Fixes resolution of videos in Brave when browsing

### LINKED ISSUE #6475: Youtube playback quality Safari parity mismatch
We should try to match Safari in what playback options are available on youtube. See screenshots to notice differences

Sample url https://www.youtube.com/watch?v=Uz-Ei3vqo-Q
Default - desktop UA

Zrzut ekranu 2022-11-24 o 11 18 46

Mobile UA
Zrzut ekranu 2022-11-24 o 11 27 10

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixes resolution of videos in Brave when browsing

This pull request fixes #6475

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Tab.swift [hunk 1]
```diff
@@ -335,7 +335,7 @@ class Tab: NSObject {
       
       let scriptPreferences: [UserScriptManager.ScriptType: Bool] = [
         .cookieBlocking: Preferences.Privacy.blockAllCookies.value,
-        .playlistMediaSource: Preferences.Playlist.webMediaSourceCompatibility.value,
+        //.playlistMediaSource: Preferences.Playlist.webMediaSourceCompatibility.value,
```
Comment (iccub) [inline Client/Frontend/Browser/Tab.swift]: this comment still relevant?

**Review by iccub — CHANGES_REQUESTED** [review]

**Review by iccub — APPROVED** [review]
