### PR TITLE
Fix #461. Tab count will changed to correct value

### LINKED ISSUE #461: Incorrect tab count shown after clearing browsing data
### Description: 
Incorrect tab count shown after clearing browsing data

### Steps to Reproduce 
  1. Bookmark a site
  2. Close all tabs
  3. Load the bookmark in a new tab
  4. Open a new tab and load a site and close it
  5. Open tab container and add a new tab
  6. Clear browsing history and go back to tabs, tab count shows 2 when there is only one new tab

**Actual result:** 
Incorrect tab count shown after clearing browsing data

**Expected result:**
Should only show the current number of tabs as count

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Somewhat easy if you keep trying for like 10 mins. Reproduced twice with the steps 

**Brave Version:** 
1.7 (18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
#335

### PR DESCRIPTION
**Pull request by danishjafri88**
Fix #461. Tab count change was animated even when not visible, this when combined with ViewController Transition occasionally resulted in wrong tab count (The transform applied was never removed.)

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -1991,8 +1991,9 @@ extension BrowserViewController: TabManagerDelegate {
 
     fileprivate func updateTabCountUsingTabManager(_ tabManager: TabManager, animated: Bool = true) {
         let count = tabManager.tabsForCurrentMode.count
-        toolbar?.updateTabCount(count, animated: animated)
-        urlBar.updateTabCount(count, animated: !urlBar.inOverlayMode)
+        // The window check insures that the view is visible and hence can be animated
+        toolbar?.updateTabCount(count, animated: self.view.window != nil ? animated : false)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: This seems like a strange check to be made right here… Is there not a better way we can assure the count will be reflected regardless of animation? (from within `updateTabCount`)

Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: Yeah This check wont fix the issue, I realised, I have pushed the fix just now. The animation completion closure was capturing the local count var and thus this issue. Plus made a change to make sure clone tab is not made when its not animated. About the check here, this is also a good to have since its useless to have animation when it will not be visible.

Comment (jhreis) [reply Client/Frontend/Browser/BrowserViewController.swift]: Can we remove this now then?

File: Client/Frontend/Widgets/TabsButton.swift [hunk 2]
```diff
@@ -138,11 +138,14 @@ class TabsButton: UIButton {
         return button
     }
     
+    var countToBe: String {
```
Comment (jhreis) [inline Client/Frontend/Widgets/TabsButton.swift]: Isn't this just used in a single function? If so, let's just inline it.

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (danishjafri88) [reply Client/Frontend/Browser/BrowserViewController.swift]: I would recommend keeping it as it saves unnecessary animation calls

Comment (jhreis) [reply Client/Frontend/Browser/BrowserViewController.swift]: Let's just remove the entire animation here. We intentionally removed it in 1.6, and would avoid all of this stuff.

File: Client/Frontend/Widgets/TabsButton.swift [hunk 3]
```diff
@@ -116,100 +107,16 @@ class TabsButton: UIButton {
...
-                UIView.animate(withDuration: 1.5, delay: 0, usingSpringWithDamping: 0.5, initialSpringVelocity: 0.0, options: [], animations: animate, completion: completion)
-            } else {
-                completion(true)
-            }
-        }
-    }
-    @objc func cloneDidClickTabs() {
-        sendActions(for: .touchUpInside)
+        currentCount = count
+        self.accessibilityLabel = Strings.Show_Tabs
```
Comment (jhreis) [inline Client/Frontend/Widgets/TabsButton.swift]: Now that the button is not being replaced, we should be able to move this, this is just setting to constant.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Client/Frontend/Widgets/TabsButton.swift (hunk 3 above)
Comment (danishjafri88) [reply Client/Frontend/Widgets/TabsButton.swift]: Moved

**Review by jhreis — APPROVED** [review]
