### PR TITLE
Sync improvements

### LINKED ISSUE #447: Nested bookmarks are not removed from sync
### Steps to Reproduce 
  1. Create a folder and add few bookmarks there.
  2. Remove the folder
  3. Join another device to sync group

**Actual result:** 
Bookmarks from the previously deleted folder are shown on the new device

### PR DESCRIPTION
**Pull request by iccub**
This PR fixes a lot of problems with sync.
- threading issues in `get-existing-objects`
- sending updated records(did not work at all previously)
- adding `syncTimestamp` to Bookmark
- removing nested bookmarks
- adding nested bookmarks from sync server in correct order
- deleting a device from sync seems to work more reliable too
- leave sync group when user initialized sync for the first time and `sync-setup-error` happens

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

**Comment by iccub** [comment]
This PR also fixes some issues with Bookmarks not getting deleted on a device. Removing/updating bookmarks should now work better in general.

File: Data/models/Bookmark.swift [hunk 1]
```diff
@@ -425,6 +426,55 @@ extension Bookmark {
         record?.delete()
     }
     
+    /// Gets all nested bookmarks recursively.
+    public static func getAllChildren(forFolderUUID syncUUID: [Int]?,
```
Comment (jhreis) [inline Data/models/Bookmark.swift]: This looks pretty similar to `getChildren`, can we centralize logic any way?

File: Data/sync/Sync.swift [hunk 2]
```diff
@@ -459,12 +463,20 @@ extension Sync {
...
-        if recordType == .prefs, let data = fetchedRecords as? [SyncDevice] {
+        if recordType == .prefs {
             // Devices have really bad data filtering, so need to manually process more of it
             // Sort to not rely on API - Reverse sort, so unique pulls the `latest` not just the `first`
-            fetchedRecords = data.sorted { device1, device2 in
+            fetchedRecords = fetchedRecords.sorted { device1, device2 in
                 device1.syncTimestamp ?? -1 > device2.syncTimestamp ?? -1 }.unique { $0.objectId ?? [] == $1.objectId ?? [] }
             
+        } else if recordType == .bookmark {
+            // Bookmars are sorted to have the oldest bookmark to come in first, so it can be added before it's children.
```
Comment (jhreis) [inline Data/sync/Sync.swift]: How is this changing current behavior?

**Review by jhreis — CHANGES_REQUESTED** [review]
This is a great PR!

Can you please rewrite the commit without a ticket to include the prefix: `No Bug: `?

lmk if you need help rewriting an old commit message.

File: Data/sync/Sync.swift (hunk 2 above)
Comment (iccub) [reply Data/sync/Sync.swift]: Currently bookmarks from the server are received in random order I believe, but if we want to add them properly we have to sort it.
Otherwise nested bookmark could go in before its parent which resulted in children bookmarks being outside of their parent folder.

File: Data/models/Bookmark.swift (hunk 1 above)
Comment (iccub) [reply Data/models/Bookmark.swift]: Not easy to centralize it without nesting logic, for `getAllChildren` we never want to ignore folders while `getChildren` has this option. And recursive search never wants to skip folders.

I think of renaming it to `getAllInsideOf(folderUUID syncUUID..`

Comment (jhreis) [reply Data/models/Bookmark.swift]: Oh this is recursive? If so, should be renamed, I think `getAllInsideOf` is probably better, helps. Or `getRecursiveChildren` or something.

File: Data/sync/Sync.swift (hunk 2 above)
Comment (jhreis) [reply Data/sync/Sync.swift]: I see, this should be handled when a folder is added though, when a folder is added we already attempt to find all orphaned children.
https://github.com/brave/brave-ios/pull/454/files#diff-01f57e7d7609dba0eec131782b05f57dR210

Comment (iccub) [reply Data/sync/Sync.swift]: But if we first save children and parent next, the children will stay at root level. It doesn't remove the Bookmark and move it into a correct place.

Comment (jhreis) [reply Data/sync/Sync.swift]: Alright, we'll take care of this separately.

File: Data/models/Bookmark.swift [hunk 3]
```diff
@@ -425,6 +426,55 @@ extension Bookmark {
...
+    /// Gets all nested bookmarks recursively.
+    public static func getRecursiveChildren(forFolderUUID syncUUID: [Int]?,
+                                            context: NSManagedObjectContext = DataController.viewContext) -> [Bookmark]? {
+        guard let searchableUUID = SyncHelpers.syncDisplay(fromUUID: syncUUID) else {
+            return nil
+        }
+        
+        let syncParentDisplayUUIDKeyPath = #keyPath(Bookmark.syncParentDisplayUUID)
+        
+        let predicate = NSPredicate(format: "\(syncParentDisplayUUIDKeyPath) == %@", searchableUUID)
```
Comment (jhreis) [inline Data/models/Bookmark.swift:472]: Why use `\(foo)` for one and `%@` for the other?

File: Data/models/Bookmark.swift [hunk 4]
```diff
@@ -425,6 +426,55 @@ extension Bookmark {
...
+                if let nestedBookmarks = getRecursiveChildren(forFolderUUID: $0.syncUUID) {
+                    allBookmarks.append(contentsOf: nestedBookmarks)
+                }
+            }
+        }
+        
+        return allBookmarks
+    }
+    
+    public func removeFolderAndSendSyncRecords(uuid: [Int]?) {
```
Comment (jhreis) [inline Data/models/Bookmark.swift]: Is this needed? Can't the normal `remove` function take care of this? Rather than identifying which function to call?

File: Data/models/Bookmark.swift [hunk 5]
```diff
@@ -425,6 +426,55 @@ extension Bookmark {
...
+        
+        if let allNestedBookmarks = Bookmark.getRecursiveChildren(forFolderUUID: syncUUID) {
+            log.warning("All nested bookmarks of :\(String(describing: title)) folder is nil")
+            
+            allBookmarks.append(contentsOf: allNestedBookmarks)
+        }
+        
+        Sync.shared.sendSyncRecords(action: .delete, records: allBookmarks)
+        
+        delete()
```
Comment (jhreis) [inline Data/models/Bookmark.swift]: We sure that all children will get deleted from CD too this way?

File: Data/sync/Sync.swift (hunk 2 above)
Comment (jhreis) [inline Data/sync/Sync.swift]: `Bookmars` typo.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Data/models/Bookmark.swift (hunk 4 above)
Comment (iccub) [reply Data/models/Bookmark.swift]: Normal `remove` drops folder and children all at once, while for sync, each record to delete must be passed separately.

File: Data/models/Bookmark.swift (hunk 3 above)
Comment (iccub) [reply Data/models/Bookmark.swift:472]: Because `\(foo)` is static, and the second one is dynamic perhaps?
This convention is widely used in apple docs https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/FetchingObjects.html
minus the `#keypath` trick.

File: Data/models/Bookmark.swift (hunk 5 above)
Comment (iccub) [reply Data/models/Bookmark.swift]: Yes, I verified it with core data

File: Data/models/Bookmark.swift (hunk 4 above)
Comment (iccub) [reply Data/models/Bookmark.swift]: So after you drop folder, we have no children bookmark references to send them to sync's remove

Comment (jhreis) [reply Data/models/Bookmark.swift]: Yeah, I just mean, maybe the `remove` function should be smarter.

**Review by jhreis — APPROVED** [review]
