### PR TITLE
Fix #4521, #4525: Register SafeBrowsing page as an error url & Fix Licenses pages

### LINKED ISSUE #4521: About Licenses page is blank
### Description: 

About Licenses page is blank

Found while testing https://github.com/brave/brave-ios/issues/4308

### Steps to Reproduce 
  1. install `1.32.3 (21.11.13.9)`
  2. launch Brave
  3.tap on the 3-dot menu on the bottom toolbar
  4. tap `Settings`
  5. swipe down to the very bottom
  6. tap on `Licenses` under `ABOUT`

**Actual result:** 
Only a blank page loads

Image from iOS (3)

**Expected result:**

Image from iOS (4)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave `1.32.3 (21.11.13.9)`

**Device details:** 
`iPhone 6s (iOS 15.0.3)`

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Register safe browsing page as an InternalURL.
- Register license page as an InternalURL.
- Remove unused constants and changed some to use InternalURL (no difference to the code as the results are the same).

This pull request fixes ##4521, #4525

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/ClipboardBarDisplayHandler.swift [hunk 1]
```diff
@@ -87,7 +87,7 @@ class ClipboardBarDisplayHandler: NSObject, URLChangeDelegate {
         // Ugly hack to ensure we wait until we're finished restoring the session on the first tab
         // before checking if we should display the clipboard bar.
         guard sessionRestored,
-            !url.absoluteString.hasPrefix("\(WebServer.sharedInstance.base)/about/sessionrestore?history=") else {
+            !url.absoluteString.hasPrefix("\(InternalURL.baseUrl)/\(SessionRestoreHandler.path)?history=") else {
```
Comment (Brandon-T) [inline Client/Frontend/Browser/ClipboardBarDisplayHandler.swift:90]: Note: This change doesn't `fix` anything. It is just cleanup. The URLs are actually the exact same (including the QueryURL, Path, etc) :)

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — APPROVED** [review]
Tested both tickets and it works nicely
