### PR TITLE
Fix #5251: Keep user on Sync chain always (until they manually leave)

### LINKED ISSUE #5251: Sync users are sometimes kicked off out of the sync chain
Setting as QA/No because we never managed to reproduce it

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Do not ever leave the sync chain until a button is pressed
- Show error alert but do nothing after it is shown
- If no devices found on the chain, do nothing (technically this should never happen, but it seems like it is, based on this report: https://bravesoftware.slack.com/archives/C2HJYB45N/p1650373022612009?thread_ts=1649769016.099419&cid=C2HJYB45N)

This pull request fixes #5251

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Test that syncing still works (joining, leaving, being removed by other device, etc)

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Sync/SyncAddDeviceViewController.swift [hunk 1]
```diff
@@ -114,11 +109,19 @@ class SyncAddDeviceViewController: SyncViewController {
     self.codewordsView.text = syncAPI.getSyncCode()
     self.setupVisuals()
   }
+  
+  override func viewDidAppear(_ animated: Bool) {
+    super.viewDidAppear(animated)
+    
+    if !syncAPI.isInSyncGroup {
+      DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [weak self] in
```
Comment (soner-yuksel) [inline Client/Frontend/Sync/SyncAddDeviceViewController.swift]: Do we need the delay here since we are already showing the error in viewDidAppear ?

**Review by soner-yuksel — APPROVED** [review]

File: Client/Frontend/Sync/SyncAddDeviceViewController.swift (hunk 1 above)
Comment (Brandon-T) [reply Client/Frontend/Sync/SyncAddDeviceViewController.swift]: Fixed.
