### PR TITLE
Fix #3453: Base relative feed/favicon URLs on the page response URL

### LINKED ISSUE #3453: Source list doesn't auto pick https context
### Description: 
Source list doesn't auto pick https context

### Steps to Reproduce 
  1. Install 1.24
  2. Go to Settings -> Brave Today -> Add Source 
  3. Type in `news.google.com`, throws insecure `http` message
  4. Add `https://`prefix to `news.google.com`, shows secure feed list

**Actual result:** 

https://user-images.githubusercontent.com/17010094/112307212-9654f580-8c98-11eb-9aae-580a36e024b8.MP4

**Expected result:**
User doesn't have to specify `https://` manually to get the secure feed list

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24 (21.3.22.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @kylehickinson

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

Attempting to download page source of insecure/http pages (i.e. `github.com`, which `URIFixup` makes `http://github.com`) which are upgraded to secure/https from the server making a redirect do not use the response URL when forming relative `URL`'s

This also fixes the same problem in favicon fetching HTML scraping

This pull request fixes #3453 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Search for a RSS feed on a popular website that automatically redirects to https
- Verify that the results are secure for URLs that are relative

Example: Typing in `daringfireball.net` loads `http://daringfireball.net` which automatically redirects and responds as `https://daringfireball.net` and has the following feeds linked in its HTML:

```html
<link rel="alternate" type="application/json" href="/feeds/json">
<link rel="alternate" type="application/atom+xml" href="/feeds/main">
```

Which are relative, and now should still return as secure feeds:

image

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/Favicons/FaviconFetcher.swift [hunk 1]
```diff
@@ -345,7 +345,9 @@ class FaviconFetcher {
     private func parseHTMLForFavicons(for url: URL, _ completion: @escaping (FaviconAttributes) -> Void) {
         let pageTask = session.dataTask(with: url) { [weak self] (data, response, error) in
             guard let self = self else { return }
-            guard let data = data, error == nil, let root = try? HTMLDocument(data: data) else {
+            guard let data = data, error == nil,
+                  let root = try? HTMLDocument(data: data),
+                  let url = response?.url else {
```
Comment (iccub) [inline Client/Frontend/Browser/Favicons/FaviconFetcher.swift:350]: are these `url` values needed? can we replace with empty assignment?

Comment (kylehickinson) [reply Client/Frontend/Browser/Favicons/FaviconFetcher.swift:350]: Yes they are used when creating the resulting `URL` objects as they use `URL(string:relativeTo:)` to ensure we handle possible relative URLs

Comment (kylehickinson) [reply Client/Frontend/Browser/Favicons/FaviconFetcher.swift:350]: We dont need to worry about this being nil, `response` should be non-nil if `error` is `nil`

**Review by iccub — APPROVED** [review]
