### PR TITLE
Fix #6379: ERC721 tokens from token registry will fail to be added as visible assets

### LINKED ISSUE #6379: Wallet: Prompt users Add custom asset screen when adding ERC721 assets fetched from token registry that do not have a Token Id
There are 5 ERC721 tokens from token registry do not have `tokenId` which will cause users fail to add them as visible asset. 
We should prompt users the Add Custom Asset screen so that they can manually input a tokenId for them when they want to add those tokens as visible assets.

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
ERC721 tokens from token registry does not have any `tokenId` value, which will cause users fail to add them as their visible assets.
In order to finish this flow, we need to prompt users the Add Custom NFT screen to ask them to input token id or modify other fields if they need.

This pull request fixes #6379

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:
on Eth Mainnet there are 5 ERC721 tokens from token registry do not have token id values
- Crypto Kitties
- PUNKS Comic
- Kudos
- Sandbox's LANDs
- Su Squares

1. Open Brave and go to wallet
2. unlock your wallet if its locked
3. Click `Edit Visible Assets` either in the visible fungible tokens section or the visible non-fungible tokens section
4. search for one of the above 5 ERC721 tokens (let say Token A)
5. try to click the row of this token
6. observe Add Custom Asset screen should show up with no segment to allow users to switch to Add Token mode
7. observe Token A token's name, address, symbol are prefilled; network is selected as Eth mainnet
8. enter a token id and click `Add`
9. observe Add Custom Asset screen will be dismissed
10. observe in the token list, Token A will be displayed with checked mark
11. dismiss this screen to go back to portfolio screen
12. observe, Token A will appear in the visible NFT section with correct balance 
13. click `Edit Visible Asset` again either in the visible fungible tokens section or the visible non-fungible tokens section
14. check if Token A is being displayed with a checkmark
15. uncheck Token A by clicking its row
16. dismiss this screen to go back to portfolio screen
17. check Token A should be no longer in the visible NFT section

## Screenshots:

https://user-images.githubusercontent.com/1187676/201960115-4f6fd38c-e8bc-4af7-9678-99e8b422e2d6.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift [hunk 1]
```diff
@@ -275,6 +279,17 @@ struct AddCustomAssetView: View {
             .navigationViewStyle(.stack)
           }
       )
+      .onAppear {
+        if let token = tokenNeedsTokenId {
+          Task { @MainActor in
+            selectedTokenType = .nft
+            networkSelectionStore.networkSelectionInForm = await userAssetStore.ethMainnet()
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift]: Why is this hardcoded to ethereum mainnet? What if an ERC721 token is added for another network? I think we can use `chainId` to fetch the correct network here

File: Sources/BraveWallet/Crypto/Stores/UserAssetsStore.swift [hunk 2]
```diff
@@ -83,14 +83,34 @@ public class UserAssetsStore: ObservableObject {
...
+          }
+        }
+        
+        assetStores = uniqueAssets.union(userAssets, f: { $0.id }).map { token in
+          var isCustomToken: Bool {
+            if token.contractAddress.isEmpty {
+              return false
+            }
+            // Any token with a tokenId should be considered a custom token.
+            if !token.tokenId.isEmpty {
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Stores/UserAssetsStore.swift:102]: Should this be specific to ERC721? In [EditUserAssetsView](https://github.com/brave/brave-ios/pull/6389/files#diff-54eee099ef64e253287bb50597d410abde1f4177ebe8382f111f8ed37a3bcbe4R20) we are using `isErc721` check as well, probably want to sync for that.

File: Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift [hunk 3]
```diff
@@ -318,21 +333,33 @@ struct AddCustomAssetView: View {
...
-        decimals: 0,
-        visible: true,
-        tokenId: tokenIdToHex,
-        coingeckoId: coingeckoId,
-        chainId: network.chainId,
-        coin: network.coin
-      )
+      if let knownERC721Token = tokenNeedsTokenId {
+        knownERC721Token.tokenId = tokenIdToHex
+        knownERC721Token.chainId = networkSelectionStore.networkSelectionInForm?.chainId ?? BraveWallet.MainnetChainId
```
Comment (StephenHeaps) [inline Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift]: Not sure we want to fallback to ethereum mainnet here, I think we should use `knownERC721Token.chainId` as the fallback?

**Review by StephenHeaps — CHANGES_REQUESTED** [review]
Minor but I think we want to display `nftTokenTitle` (currently in `PortfolioView` but needs moved to `BraveWalletSwiftUIExtensions` for #6394) in Edit Visible Assets View to match desktop.
crypto kitties | crypto kitties - user assets
--|--

File: Sources/BraveWallet/Crypto/Stores/UserAssetsStore.swift (hunk 2 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Stores/UserAssetsStore.swift:102]: no. its not only for ERC721. all NFT needs to have a token Id
1. if erc721 from token registry has not yet been added as custom nft, user should not able to swipe to delete
2. once its been added as a custom nft with a token id value, it can be deleted 
3. after the custom asset version is deleted, next time, user will need to enter a token id again if they want to set the erc721 as a visible asset.

Comment (StephenHeaps) [reply Sources/BraveWallet/Crypto/Stores/UserAssetsStore.swift:102]: > all NFT needs to have a token Id

Solana NFTs don't have `tokenId` though. If a Solana NFT asset gets added to token registry, would this allow swipe to delete (but likely fail to delete)?

Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Stores/UserAssetsStore.swift:102]: there is no NFT from token registry for solana mainnet and testnets. all Solana NFTs will need to be added manually as custom assets which their addresses will not be found from the token registry.

File: Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift (hunk 1 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift]: fixed in [9848819](https://github.com/brave/brave-ios/pull/6389/commits/98488194d30ccb16a832ccaff3e9313268319ac5)

File: Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift (hunk 3 above)
Comment (nuo-xu) [reply Sources/BraveWallet/Crypto/Portfolio/AddCustomAssetView.swift]: fixed in [9848819](https://github.com/brave/brave-ios/pull/6389/commits/98488194d30ccb16a832ccaff3e9313268319ac5)

**Comment by nuo-xu** [comment]
@StephenHeaps token's nftTokenTitle is fixed in [9848819](https://github.com/brave/brave-ios/pull/6389/commits/98488194d30ccb16a832ccaff3e9313268319ac5)

**Review by StephenHeaps — APPROVED** [review]
