### PR TITLE
Fix #4236 - Use SceneDelegate instead of AppDelegate

### LINKED ISSUE #4228: Clean exit check broken on latest development build
### Steps to Reproduce 
  1. Open few tabs
  2. Force close the app
  3. Reopen

**Actual result:** 
App think it crashed and ask to restore tabs.

**Expected result:**
Should restore tabs without prompt

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
Happens on latest development, does not happen on production builds.

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### LINKED ISSUE #4236: Opening links from other app when Brave is set as default broken on latest development
### Steps to Reproduce 
  1. Set Brave as default
  2. Go to other app, like notes
  3. Tap on url

**Actual result:** 
Brave opens but the link does not show up

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes

- Change from AppDelegate to properly support SceneDelegate.
- This will bring us closer to supporting multiple windows and getting rid of all the singletons everywhere.
- Fixes the issues CarPlay introduced by using SceneDelegate for iOS 14+.
- Should have moved a long time ago :)

This pull request fixes #4236, fixes #4228

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Test opening URLs from other apps (Safari, Twitter, etc)
- Test Sharing URLs
- Test Playlist (Pip, Carplay, Error messages/popups)
- Test Opening and Closing Tabs (NTP + Regular browsing)
- Test Rewards
- Test Stats on NTP
- Test Onboarding + Selecting search engine from Onboarding
- Test Sync
- Test ReaderMode
- Test Private Browsing

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Application/Delegates/SceneDelegate.swift [hunk 1]
```diff
@@ -40,10 +30,43 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
...
         
-        let appDelegate = UIApplication.shared.delegate as? AppDelegate
-        window = UIWindow(windowScene: windowScene).then {
-            SceneObserver.setupApplication(window: $0)
+        // Setup browser state
+        browserViewController.shouldShowIntroScreen = SceneDelegate.shouldShowIntroScreen
+        
+        if SceneDelegate.shouldHandleUrpLookup {
+            // TODO: Find a better way to do this when multiple windows are involved.
+            SceneDelegate.shouldHandleUrpLookup = false
```
Comment (iccub) [inline Client/Application/Delegates/SceneDelegate.swift:52]: this goes away with the new onboarding flow btw

File: Client/Application/Delegates/SceneDelegate.swift [hunk 2]
```diff
@@ -55,39 +78,436 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
...
+        if let intent = userActivity.interaction?.intent as? OpenWebsiteIntent {
+            return switchToTabForIntentURL(intentURL: intent.websiteURL)
+        }
+        
+        if let intent = userActivity.interaction?.intent as? OpenHistoryWebsiteIntent {
+            return switchToTabForIntentURL(intentURL: intent.websiteURL)
+        }
+        
+        if let intent = userActivity.interaction?.intent as? OpenBookmarkWebsiteIntent {
+            return switchToTabForIntentURL(intentURL: intent.websiteURL)
```
Comment (iccub) [inline Client/Application/Delegates/SceneDelegate.swift]: split `return` and method call in two separate lines

File: Client/Application/Delegates/SceneDelegate.swift [hunk 3]
```diff
@@ -55,39 +78,436 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
...
+        }
+        
+        return
```
Comment (iccub) [inline Client/Application/Delegates/SceneDelegate.swift]: can be removed

File: Client/Frontend/Reader/ReadabilityService.swift [hunk 4]
```diff
@@ -22,8 +22,9 @@ class ReadabilityOperation: Operation {
     var result: ReadabilityOperationResult?
     var tab: Tab!
     var readerModeCache: ReaderModeCache
+    private var rewards: BraveRewards?
```
Comment (iccub) [inline Client/Frontend/Reader/ReadabilityService.swift]: unfortunate that we have to pass rewards here only to configure a tab,
we can think of refactoring it later

**Review by iccub — CHANGES_REQUESTED** [review]
Looks super clean and a lot of code comments which i like,
will run this app now to catch any early bugs

File: Client/Frontend/Browser/Tab.swift [hunk 5]
```diff
@@ -361,11 +363,9 @@ class Tab: NSObject {
         deleteWebView()
         deleteNewTabPageController()
         contentScriptManager.helpers.removeAll()
-        guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else { return }
-        
-        let rewards = appDelegate.browserViewController.rewards
+
         if !PrivateBrowsingManager.shared.isPrivateBrowsing {
-            rewards.reportTabClosed(tabId: Int(rewardsId))
+            rewards?.reportTabClosed(tabId: Int(rewardsId))
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Tab.swift]: If its not a huge refactor (which I don't think it should be… but famous last words), can we move this to BVC's delegate that notifies when a tab is closed? That way we don't have to pass in a `BraveRewards` object into `Tab`

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift [hunk 6]
```diff
@@ -42,9 +42,8 @@ extension BrowserViewController {
             // 60 days has passed since the user last saw the onboarding.. it's time to show the onboarding again..
             if daysUntilNextPrompt <= Date() && !isRewardsEnabled {
                 guard let onboarding = OnboardingNavigationController(
-                    profile: profile,
-                    onboardingType: .existingUserRewardsOff(currentProgress),
-                    rewards: rewards
+                    browser: self,
+                    onboardingType: .existingUserRewardsOff(currentProgress)
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Onboarding.swift]: These changes (passing BVC into the onboarding flow) are fine for now but I don't want to see them when we implement the new onboarding flow

File: Client/Application/Delegates/SceneDelegate.swift [hunk 7]
```diff
@@ -55,39 +78,436 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
...
+        do {
+            return try DiskImageStore(files: profile.files,
+                                      namespace: "TabManagerScreenshots",
+                                      quality: UIConstants.screenshotQuality)
+        } catch {
+            log.error("Failed to create an image store for files: \(profile.files) and namespace: \"TabManagerScreenshots\": \(error.localizedDescription)")
+            assertionFailure()
+        }
+        return nil
+    }()
```
Comment (kylehickinson) [inline Client/Application/Delegates/SceneDelegate.swift]: Why are these static, couldn't they exist in AppDelegate and pass into each scene?

File: Client/Application/Delegates/SceneDelegate.swift [hunk 8]
```diff
@@ -55,39 +78,436 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
...
+        })
+    }
+    
+    /// Should NEVER be used
+    /// Returns the very first `BrowserViewController` found in any `UIScene`
+    /// within the entire application. If this function is being used, it is time to refactor your code.
+    var browserViewController: BrowserViewController? {
+        log.debug("********* WARNING *********: Accessing `browserViewController` on `UIApplication`!!!\n DOES NOT SUPPORT MULTIPLE WINDOWS.")
+        
+        return browserViewControllers.first
```
Comment (kylehickinson) [inline Client/Application/Delegates/SceneDelegate.swift]: Is this used now? If not, can we delete it?

Comment (Brandon-T) [reply Client/Application/Delegates/SceneDelegate.swift]: It is used in 2 places with `UIApplication.shared.browserViewController`. These two places I have zero idea how to refactor as they're static content scripts and singletons :(

File: Client/Application/Delegates/SceneDelegate.swift (hunk 7 above)
Comment (Brandon-T) [reply Client/Application/Delegates/SceneDelegate.swift]: Not sure how to pass the data from `AppDelegate` to each scene.

**Review by iccub — APPROVED** [review]
Good job on this unexpected task :)
I ran the app and it seems to work well

File: Client/Application/Delegates/AppDelegate.swift [hunk 9]
```diff
@@ -365,130 +267,77 @@ class AppDelegate: UIResponder, UIApplicationDelegate, UIViewControllerRestorati
...
+
+        application.shortcutItems = Preferences.Privacy.privateBrowsingOnly.value ? [privateTabItem, scanQRCodeItem] : [newTabItem, privateTabItem, scanQRCodeItem]
     }
 
     func application(_ application: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
-        guard let routerpath = NavigationPath(url: url) else {
-            return false
-        }
-        self.browserViewController.handleNavigationPath(path: routerpath)
+        log.debug("APPLICATION OPEN URL")
```
Comment (kylehickinson) [inline Client/Application/Delegates/AppDelegate.swift]: Do we need all the debug logs in this PR still? Or were they just for testing?

File: Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift [hunk 10]
```diff
@@ -749,16 +751,10 @@ extension PlaylistWebLoader: WKNavigationDelegate {
...
-        guard let profile = (UIApplication.shared.delegate as? AppDelegate)?.profile else {
-            completionHandler(.rejectProtectionSpace, nil)
-            return
-        }
-        
         let origin = "\(challenge.protectionSpace.host):\(challenge.protectionSpace.port)"
         if challenge.protectionSpace.authenticationMethod == NSURLAuthenticationMethodServerTrust,
            let trust = challenge.protectionSpace.serverTrust,
-           let cert = SecTrustGetCertificateAtIndex(trust, 0), profile.certStore.containsCertificate(cert, forOrigin: origin) {
+           let cert = SecTrustGetCertificateAtIndex(trust, 0), SceneDelegate.profile.certStore.containsCertificate(cert, forOrigin: origin) {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift]: Can we pass the `certStore` directly into the cache loader instead of accessing `SceneDelegate.profile` directly?

If not, can we open a new issue to clean this up and ref that issue here in a TODO

File: Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCarplayManager.swift [hunk 11]
```diff
@@ -64,107 +51,45 @@ class PlaylistCarplayManager: NSObject {
...
-        #if targetEnvironment(simulator)
-        // Force CarPlay on the simulator
-        // This is because we don't actually know if the CarPlay simulator is showing or not
-        // and we don't get notified when it disconnects :(
-        attemptInterfaceConnection(isCarPlayAvailable: true)
-        #else
-        guard let contentManager = contentManager else {
-            log.error("Invalid MPPlayableContentManager!")
-            return
+    func getCarPlayController() -> NSObject? {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCarplayManager.swift]: Can we return the real value now instead of `NSObject` that its iOS 14+ and only has 1 implementation?

File: Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift [hunk 12]
```diff
@@ -55,12 +56,17 @@ class PlaylistViewController: UIViewController {
     private var assetStateObservers = Set<AnyCancellable>()
     private var assetLoadingStateObservers = Set<AnyCancellable>()
     
-    init(mediaPlayer: MediaPlayer, initialItem: PlaylistInfo?, initialItemPlaybackOffset: Double) {
+    private(set) weak var browser: BrowserViewController?
+    
+    init(browser: BrowserViewController?, mediaPlayer: MediaPlayer, initialItem: PlaylistInfo?, initialItemPlaybackOffset: Double) {
+        self.browser = browser
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Controllers/PlaylistViewController.swift]: We don't need to pass in `browser` anymore do we?  Shouldn't you be passing in a `PlaylistViewControllerDelegate`?

File: Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift [hunk 13]
```diff
@@ -397,7 +397,8 @@ class PlaylistWebLoader: UIView {
             $0.edges.equalToSuperview()
         }
         
-        if let browserController = (UIApplication.shared.delegate as? AppDelegate)?.browserViewController {
+        // TODO: REFACTOR to support multiple windows better
+        if let browserController = webView.currentScene?.browserViewController {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Playlist/Managers & Cache/PlaylistCacheLoader.swift:404]: Can you open an issue for this refactor and anywhere where we have this TODO around multi-window support ref that issue in its todo?

File: Client/Frontend/Reader/ReadabilityService.swift [hunk 14]
```diff
@@ -22,8 +22,9 @@ class ReadabilityOperation: Operation {
...
 
-    init(url: URL, readerModeCache: ReaderModeCache) {
+    init(url: URL, readerModeCache: ReaderModeCache, rewards: BraveRewards?) {
```
Comment (kylehickinson) [inline Client/Frontend/Reader/ReadabilityService.swift]: Rewards not used

File: Client/Frontend/Reader/ReadabilityService.swift [hunk 15]
```diff
@@ -117,14 +118,20 @@ class ReadabilityService {
         return ReadabilityServiceSharedInstance
     }
 
-    var queue: OperationQueue
+    private var queue: OperationQueue
+    private weak var rewards: BraveRewards?
```
Comment (kylehickinson) [inline Client/Frontend/Reader/ReadabilityService.swift]: Rewards not used

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
🎉
