### PR TITLE
Fix #4814: Save logins switch is shown when focus is set to search field without any saved passwords

### LINKED ISSUE #4814: Save logins switch is shown when focus is set to search field without any saved passwords
### Description: 
Save logins switch is shown when focus is set to search field without any saved passwords

### Steps to Reproduce 
  1. Clean install 
  2. Open `Logins & Password` from menu
  3. Focus on search field
  4. `Save Logins` text is hidden but the switch isn't

**Actual result:** 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.2) | iPad Pro (iOS 15.3)
-- | -- | --
 |  | 

**Expected result:**
Hide the switch when text is hidden

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.34 (22.1.5.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel

### PR DESCRIPTION
**Pull request by soner-yuksel**
Fixing appearing toggle bug while searching and removing unnecessary empty view

## Summary of Changes

This pull request fixes #4814

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Clean install
- Open Logins & Password from menu
- Focus on search field
- Save Logins text is hidden with the switch

## Screenshots:

https://user-images.githubusercontent.com/6643505/149387513-15716186-7d6e-4b98-835d-1dfc8723f006.MP4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Login/LoginListViewController.swift [hunk 1]
```diff
@@ -194,7 +193,7 @@ extension LoginListViewController {
             let cell = tableView.dequeueReusableCell(withIdentifier: Constants.saveLoginsRowIdentifier, for: indexPath).then {
                 $0.textLabel?.text = Strings.saveLogins
                 $0.separatorInset = .zero
-                $0.accessoryView = toggle
+                $0.accessoryView =  !searchController.isActive ? toggle :  nil
```
Comment (iccub) [inline Client/Frontend/Login/LoginListViewController.swift]: Maybe flip this condition so it check for `active` instead of `!active`?

Comment (soner-yuksel) [reply Client/Frontend/Login/LoginListViewController.swift]: Fixed at https://github.com/brave/brave-ios/pull/4852/commits/6a414e58fbbb54d91b4409a5193d18714b7d5c7e

**Review by iccub — APPROVED** [review]
