### PR TITLE
Fix #4918: IDN domains not working

### LINKED ISSUE #4918: IDN domains not working
### Description: 
All domains with special letters such as an ö triggers a Google search instead of display the website.

### Steps to Reproduce 
  1. Enter "ö.de" in the URL bar
  2. Hit open
  3. Be disappointed

**Actual result:** 
A Google search for "ö.de" is started

**Expected result:**
Calling up the ö.de page or its redirection to https://www.dasoertliche.de/

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Alsways

**Brave Version:** 
v.1.24.1 (22.1.20.22)

**Device details:** 
iPhone X (iOS 15.2.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
## Security Review
- https://github.com/brave/security/issues/1110

## Summary of Changes
- International Domains will load and not open links with search engine.
- Session Restore will restore IDN URLs correctly.
- Error Pages will show correctly for IDN URLs.

This pull request fixes #4918

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

- Enter "ö.de" in the URL bar
- Hit open
- https://mobil.dasoertliche.de/ loaded

## Screenshots:

https://user-images.githubusercontent.com/6643505/202580850-f00c22d1-1a11-4869-b172-e8f283c669e3.mp4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Shared/URIFixup.swift [hunk 1]
```diff
@@ -149,7 +153,7 @@ public class URIFixup {
 
     // If there is a "." or ":", prepend "http://" and try again. Since this
     // is strictly an "http://" URL, we also require a host.
-    if let url = URL(string: "http://\(escaped)"), url.host != nil {
+    if let url =  NSURL(idnString: "http://\(escaped)") as URL?, url.host != nil {
```
Comment (cuba) [inline Sources/Shared/URIFixup.swift]: 2 spaces

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 2]
```diff
@@ -664,6 +664,45 @@ extension BrowserViewController: WKNavigationDelegate {
...
+    // Ignore the "Frame load interrupted" error that is triggered when we cancel a request
+    // to open an external application and hand it over to UIApplication.openURL(). The result
+    // will be that we switch to the external app, for example the app store, while keeping the
+    // original web page in the tab instead of replacing it with an error page.
+    let error = error as NSError
+    if error.domain == "WebKitErrorDomain" && error.code == 102 {
+      return
+    }
+
+    if checkIfWebContentProcessHasCrashed(webView, error: error as NSError) {
```
Comment (cuba) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: you have a `let error = error as NSError` just above. Do you need that `as NSError` here?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift [hunk 3]
```diff
@@ -664,6 +664,45 @@ extension BrowserViewController: WKNavigationDelegate {
...
+      return
+    }
+
+    if let url = error.userInfo[NSURLErrorFailingURLErrorKey] as? URL {
+      ErrorPageHelper(certStore: profile.certStore).loadPage(error, forUrl: url, inWebView: webView)
+      // Submitting same errornous URL using toolbar will cause progress bar get stuck
+      // Reseting the progress bar in case there is an error is necessary
+      topToolbar.hideProgressBar()
+
+      // If the local web server isn't working for some reason (Firefox cellular data is
```
Comment (cuba) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift]: Should probably replace "Firefox" with "Brave"

**Review by cuba — APPROVED** [review]
Nothing major

**Review by iccub — APPROVED** [review]

File: Sources/Shared/URIFixup.swift [hunk 4]
```diff
@@ -59,11 +59,15 @@ public class URIFixup {
   }
 
   public static func getURL(_ entry: String) -> URL? {
-    if let url = URL(string: entry), InternalURL.isValid(url: url) {
-      return URL(string: entry)
+    let trimmed = entry.trimmingCharacters(in: .whitespacesAndNewlines)
+    
+    // NSURL: idnString from brave core handles the puny code represantation of Hostnames
+    // Using Punycode, host names containing Unicode characters are transcoded to a subset of ASCII
+    let entryURL = URL(string: trimmed) ?? NSURL(idnString: trimmed) as URL?
```
Comment (kylehickinson) [inline Sources/Shared/URIFixup.swift]: Do we even want to use `URL(string:)` at all here and just skip to only making the URL via `NSURL(idnString:)`

Comment (soner-yuksel) [reply Sources/Shared/URIFixup.swift]: Actually we dont want this because what `NSURL(idnString:)` is doing for IP addresses.

like `http://127.0.1` will be auto converted to `http://127.0.0.1` or

`http://1.1:80` will be "http://1.0.0.1:80"

@Brandon-T correct me If I am wrong here.

Comment (kylehickinson) [reply Sources/Shared/URIFixup.swift]: @soner-yuksel That is correct & valid IP address expansion, makes me think we should definitely use the IDN string initializer by default :)

Comment (soner-yuksel) [reply Sources/Shared/URIFixup.swift]: Thanks @kylehickinson Let me look into it, I will make the change and update the test cases with it.

Comment (Brandon-T) [reply Sources/Shared/URIFixup.swift]: @soner-yuksel Kyle is correct. It should expand as it is a valid canonicalization. GURL will not make a mistake, so trust it :) we should be banning all usage of URL(string:"..."); soon.
Everywhere should be using the NSURL one.

I will write up an explanation later on WHY with some examples where Foundation.URL is completely busted.

This is one of those cases where URL treats them as different and if you compare them, it'd return false, which is incorrect.

Comment (soner-yuksel) [reply Sources/Shared/URIFixup.swift]: Changes at https://github.com/brave/brave-ios/pull/6431/commits/5699c6caa994f515a62a0e09e7ea7bc1a8e7fa9d

**Review by stoletheminerals — APPROVED** [review]

**Review by Brandon-T — APPROVED** [review]
