### PR TITLE
Fix #3358 - Update httpse data files

### LINKED ISSUE #3358: Update httpse data files
### Description: 
EFF's HTTPSE rulesets fixed a redirect loop on http://radio.garden/ due to https - https://github.com/EFForg/https-everywhere/issues/19927 

### Test Plan
Specified here: https://github.com/brave/brave-ios/pull/3402

### Steps to Reproduce 
  1. Navigate to http://radio.garden

**Actual result:** 
Redirect loop

**Expected result:**
No redirect loop

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.23.1

**Device details:** 
iPhone 11

### PR DESCRIPTION
**Pull request by jumde**
## Summary of Changes

This pull request fixes #3358 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
1. Navigate to radio.garden and verify the site loads without any redirect loops
2. Navigate to httpse-everywhere.badssl.com and verify that `HTTPS Everywhere` is working

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -336,6 +336,7 @@ class BrowserViewController: UIViewController {
         }
         Preferences.NewTabPage.selectedCustomTheme.observe(from: self)
         // Lists need to be compiled before attempting tab restoration
+        ContentBlockerHelper.clearBlockingRules()
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController.swift]: @kylehickinson worked on this more, I will leave this part to him,
if you want me to take over and look closer at it, let me know Kyle

**Review by Brandon-T — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift (hunk 1 above)
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: @jumde to fix potential race condition around not waiting for `removeContentRuleList` completion handler

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
