### PR TITLE
Fix: #4273 Built Send Crypto Screen 

### LINKED ISSUE #4273: Add support for sending crypto in wallet
The "Send" button in the Buy/Send/Swap popover does not currently show anything.  

See MVP doc/Figma for designs.

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
- Built Send Crypto Screen UI
- Integrated the screen with token fetching/selection/balance

This pull request fixes #4273 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:
simulator_screenshot_C15EAA98-BA84-4483-8060-A40AC488C9AE

simulator_screenshot_9BC6C333-EE90-460A-8CC8-FE4062E83249

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 1]
```diff
@@ -0,0 +1,167 @@
...
+  @Environment(\.presentationMode) @Binding private var presentationMode
+  
+  @State private var amountInput = ""
+  @State private var quickAmount: ShortcutAmountGrid.Amount? {
+    didSet {
+      if let _ = quickAmount {
+        // TODO: compute using `sendTokenStore.selectedSendTokenBalance` and `quickAmount` if there is one and update `amountInput`
+      }
+    }
+  }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Don't need this as its own `@State`, it should just calculate the amount from balance and then set `amountInput`

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+        Section(
+          header: WalletListHeaderView(title: Text(Strings.Wallet.sendCryptoToTitle))
+        ) {
+          HStack(spacing: 24.0) {
+            TextField(Strings.Wallet.sendCryptoAddressPlaceholder, text: $sendAddress)
+            Button(action: {}) {
+              Image("brave.clipboard")
+                .resizable()
+                .aspectRatio(contentMode: .fit)
+                .frame(width: length, height: length)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Set a `font` on this instead, `brave.clipboard` is a custom SF Symbol so no need to make it resizable/aspect-fit/frame modifiers

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+                .foregroundColor(Color(.primaryButtonTint))
+            }
+            Button(action: {}) {
+              Image("qr_code_button")
+                .renderingMode(.template)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: ~We should make this a custom SF symbol and them mimic `brave.clipboard`. I will get you a SVG for it~

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 4]
```diff
@@ -0,0 +1,167 @@
...
+              Text(sendTokenStore.selectedSendTokenBalance ?? "")
+                .font(.title3.weight(.semibold))
+                .foregroundColor(Color(.braveLabel))
+            }
+            .padding(.vertical, 8)
+          }
+        }
+        .listRowBackground(Color(.secondaryBraveGroupedBackground))
+        Section(
+          header: WalletListHeaderView(title: Text(String.localizedStringWithFormat(Strings.Wallet.sendCryptoAmountTitle, sendTokenStore.selectedSendToken?.symbol ?? ""))),
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Format to next line so it fits within ~110 char column

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+          footer: ShortcutAmountGrid(action: { amount in
+            quickAmount = amount
+          })
+          .listRowInsets(.zero)
+          .padding(.bottom, 8)
+        ) {
+          TextField(String.localizedStringWithFormat(Strings.Wallet.sendCryptoAmountPlaceholder, sendTokenStore.selectedSendToken?.symbol ?? ""), text: $amountInput)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Format to next line so it fits within ~110 char column

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 6]
```diff
@@ -0,0 +1,167 @@
...
+            }
+            Text("bc1qaq...mafs4e")
+              .font(.body)
+              .foregroundColor(Color(.braveLabel))
+          }
+        }
+        .listRowBackground(Color(.clear))
+        */
+        Section(
+          header: HStack {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: No need for `HStack`

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 7]
```diff
@@ -0,0 +1,155 @@
...
+  
+  func fetchAssets() {
+    rpcController.chainId { [self] chainId in
+      walletService.userAssets(chainId) { tokens in
+        userAssets = tokens
+        
+        if let selectedToken = selectedSendToken {
+          if tokens.isEmpty {
+            selectedSendToken = nil
+          } else if let index = tokens.firstIndex(where: { $0.id == selectedToken.id && $0.contractAddress != selectedToken.contractAddress }) {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift]: `id` comparison should be enough. And you can just do `first(where: { ... })` instead of first index

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 8]
```diff
@@ -0,0 +1,155 @@
...
+  }
+  
+  func fetchAssets() {
+    rpcController.chainId { [self] chainId in
+      walletService.userAssets(chainId) { tokens in
+        userAssets = tokens
+        
+        if let selectedToken = selectedSendToken {
+          if tokens.isEmpty {
+            selectedSendToken = nil
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift:50]: Should default to `.eth`

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 9]
```diff
@@ -0,0 +1,155 @@
...
+        guard let index = tokens.firstIndex(where: { $0.id == token.id}) else {
+          self.selectedSendTokenBalance = nil
+          return
+        }
+        self.balance(for: tokens[index])
+      }
+    }
+  }
+  
+  private func balance(for token: BraveWallet.ERCToken) {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift]: rename to `fetchBalance` since there's no completion block handling you back a balance

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 10]
```diff
@@ -0,0 +1,155 @@
...
+        return
+      }
+      // Get balance for ETH token
+      if token.isETH {
+        self.rpcController.balance(accountAddress) { success, balance in
+          guard success else {
+            self.selectedSendTokenBalance = nil
+            return
+          }
+          self.selectedSendTokenBalance = balance
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift:91]: Can you mark these `selectedSendTokenBalance` setters with `// TODO: convert from wei`

File: BraveWallet/Crypto/Stores/SendTokenStore.swift [hunk 11]
```diff
@@ -0,0 +1,155 @@
...
+  }
+  
+  public func unlocked() {
+  }
+  
+  public func backedUp() {
+  }
+  
+  public func accountsChanged() {
+    fetchAssetBalance()
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/SendTokenStore.swift]: Don't think you have to re-fetch asset balance when an account is added/removed as long as the selected account still exists.  Maybe add a check here to see if selected account exists in in the keyring.accountInfos

File: BraveWallet/WalletStrings.swift [hunk 12]
```diff
@@ -852,22 +852,64 @@ extension Strings {
...
+      bundle: .braveWallet,
+      value: "Amount in %@", // TODO: Get real copy
+      comment: "A placeholder of the amount text field. '%@' will be replaced with a token symbol such as 'ETH' or 'BAT'"
+    )
+    public static let sendCryptoToTitle = NSLocalizedString(
+      "wallet.sendCryptoToTitle",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "To", // TODO: Get real copy
+      comment: "A title above the address you want to send to."
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: Add additional info in the comment with an example/context similar to `sendCryptoFromTitle`

File: BraveWallet/WalletStrings.swift [hunk 13]
```diff
@@ -852,22 +852,64 @@ extension Strings {
...
+    )
+    public static let sendCryptoAddressPlaceholder = NSLocalizedString(
+      "wallet.sendCryptoAddressPlaceholder",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Enter address or url", // TODO: Get real copy
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: I don't think we need a TODO on this

File: BraveWallet/WalletStrings.swift [hunk 14]
```diff
@@ -852,22 +852,64 @@ extension Strings {
...
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "Amount in %@", // TODO: Get real copy
+      comment: "A placeholder of the amount text field. '%@' will be replaced with a token symbol such as 'ETH' or 'BAT'"
+    )
+    public static let sendCryptoToTitle = NSLocalizedString(
+      "wallet.sendCryptoToTitle",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "To", // TODO: Get real copy
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: Don't need todo on this

File: BraveWallet/WalletStrings.swift [hunk 15]
```diff
@@ -852,22 +852,64 @@ extension Strings {
...
       bundle: .braveWallet,
-      value: "Continue to Wyre",
+      value: "Continue to Wyre", // TODO: Get real copy
       comment: "The title of the button for users to click when they are ready to buy using Wyre payment"
     )
+    public static let sendCryptoFromTitle = NSLocalizedString(
+      "wallet.sendCryptoFromTitle",
+      tableName: "BraveWallet",
+      bundle: .braveWallet,
+      value: "From", // TODO: Get real copy
```
Comment (kylehickinson) [inline BraveWallet/WalletStrings.swift]: Don't need todo on this

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift (hunk 3 above)
Comment (kylehickinson) [reply BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Turns out we have one already, its `brave.qr-code`

File: BraveWallet/Crypto/Stores/SendTokenStore.swift (hunk 8 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/SendTokenStore.swift:50]: > Should default to `.eth`

if userAssets is empty that means user has no asset to send? why we default it to be `.eth`?

File: BraveWallet/Crypto/Stores/SendTokenStore.swift (hunk 11 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Stores/SendTokenStore.swift]: > Don't think you have to re-fetch asset balance when an account is added/removed as long as the selected account still exists. Maybe add a check here to see if selected account exists in in the keyring.accountInfos

I wasn't too sure what this protocol is for that's why I fetch the assets there. But after your explanation, i think fetch assets in `selectedAccountChanged` is sufficient.

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 16]
```diff
@@ -0,0 +1,184 @@
...
+      $0.contentMode = .center
+      $0.translatesAutoresizingMaskIntoConstraints = false
+    }
+    view.addSubview(imageView)
+    NSLayoutConstraint.activate([
+      imageView.centerYAnchor.constraint(equalTo: view.centerYAnchor),
+      imageView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
+      imageView.widthAnchor.constraint(equalToConstant: 200),
+      imageView.heightAnchor.constraint(equalToConstant: 200),
+    ])
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: use SnapKit instead

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 17]
```diff
@@ -0,0 +1,184 @@
...
+  }
+}
+#else
+class WalletScannerViewController: UIViewController {
+  
+  private lazy var captureSession: AVCaptureSession = {
+    let session = AVCaptureSession()
+    session.sessionPreset = AVCaptureSession.Preset.high
+    return session
+  }()
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]:
```
private let captureSession = AVCaptureSession().then {
  $0.sessionPreset = .high
}
```

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 18]
```diff
@@ -0,0 +1,184 @@
...
+    NSLayoutConstraint.activate([
+      imageView.centerYAnchor.constraint(equalTo: view.centerYAnchor),
+      imageView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
+      imageView.widthAnchor.constraint(equalToConstant: 200),
+      imageView.heightAnchor.constraint(equalToConstant: 200),
+    ])
+  }
+  
+  override func viewDidLayoutSubviews() {
+    previewLayer?.frame = view.layer.bounds
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: call `super.viewDidLayoutSubviews`

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 19]
```diff
@@ -0,0 +1,184 @@
...
+    if getAuthorizationStatus != .denied {
+      setupCamera()
+    } else {
+      delegate?.didFail(reason: .permissionDenied)
+    }
+    
+    let imageView = UIImageView().then {
+      $0.image = UIImage(named: "camera-overlay")
+      $0.contentMode = .center
+      $0.translatesAutoresizingMaskIntoConstraints = false
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: `isAccessibilityElement = false`

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 20]
```diff
@@ -0,0 +1,184 @@
+// Copyright 2021 The Brave Authors. All rights reserved.
+// This Source Code Form is subject to the terms of the Mozilla Public
+// License, v. 2.0. If a copy of the MPL was not distributed with this
+// file, You can obtain one at http://mozilla.org/MPL/2.0/.
+
+import SwiftUI
+import AVFoundation
+import Shared
+
+struct WalletScannerView: UIViewControllerRepresentable {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: As per conversation: do something like this

```swift
struct WalletScannerView: View {
  @Binding var address: String
  @State private var isErrorPresented: Bool = false
  @Environment(\.presentationMode) @Binding private var presentationMode
  
  var simulatorBody: some View {
    
  }
  
  var body: some View {
    NavigationView {
    #if targetEnvironment(simulator)
    Text("Unable to scan on simulator")
      .onAppear {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
          address = ""
          presentationMode.dismiss()
        }
      }
    #else
    _WalletScannerView(address: _address)
      .ignoresSafeArea()
      .alert()
    #endif
    }
    .toolbar {
      ToolbarItemGroup(placement: .cancellationAction) {
        Text("")
      }
    }
  }
}
```

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 21]
```diff
@@ -6,140 +6,210 @@
...
-  enum ScanError: Error {
-    case badInput, badOutput, permissionDenied, others
-  }
-  
-  var completion: (Result<String, ScanError>) -> Void
-  
-  init(completion: @escaping (Result<String, ScanError>) -> Void) {
-    self.completion = completion
+struct WalletScannerView: View {
+  @Binding var toAddress: String
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: This could technically be re-used for any sort of address scanning, right? Maybe lets rename it to `AddressQRCodeScannerView` or something and just have the binding be `address` instead of `toAddress`

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 22]
```diff
@@ -6,140 +6,210 @@
...
+  @State private var isErrorPresented: Bool = false
+  @State private var permissionDenied: Bool = false
+  @Environment(\.presentationMode) @Binding private var presentationMode
+  
+  var body: some View {
+    #if targetEnvironment(simulator)
+    NavigationView {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: Can this `NavigationView` can exist outside of `#if/#else`?

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 23]
```diff
@@ -6,140 +6,210 @@
...
+                })
+              )
+            }
+        )
+    }
+    #endif
   }
+}
+
+struct _WalletScannerView: UIViewControllerRepresentable {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: Make this `private`

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 24]
```diff
@@ -6,140 +6,210 @@
...
+  typealias UIViewControllerType = WalletScannerViewController
+  @Binding var toAddress: String
+  @Binding var isErrorPresented: Bool
+  @Binding var isPermissionDenied: Bool
+  var dismiss: (() -> Void)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: nit: parenthesis not needed

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 25]
```diff
@@ -6,140 +6,210 @@
...
-    let viewController = WalletScannerViewController()
-    viewController.delegate = context.coordinator
-    return viewController
-  }
   func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {
   }
 }
 
-#if targetEnvironment(simulator)
 class WalletScannerViewController: UIViewController {
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: Make this `private`

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 26]
```diff
@@ -6,140 +6,210 @@
...
-  let captureDevice = AVCaptureDevice.default(for: .video)
+  var dismiss: (() -> Void)
   
-  var previewLayer: AVCaptureVideoPreviewLayer?
-  var delegate: WalletScannerCoordinator?
+  init(
+    toAddress: Binding<String>,
+    isErrorPresented: Binding<Bool>,
+    isPermissionDenied: Binding<Bool>,
+    dismiss: @escaping (() -> Void)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: nit: parenthesis not needed

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 27]
```diff
@@ -6,140 +6,210 @@
...
+  private var previewLayer: AVCaptureVideoPreviewLayer?
+  private var isFinishScanning = false
   
-  private lazy var captureSession: AVCaptureSession = {
-    let session = AVCaptureSession()
-    session.sessionPreset = AVCaptureSession.Preset.high
-    return session
-  }()
-  let captureDevice = AVCaptureDevice.default(for: .video)
+  var dismiss: (() -> Void)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: nit: parenthesis not needed

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 28]
```diff
@@ -6,140 +6,210 @@
...
-    
+
     captureSession.stopRunning()
   }
-  
+
   private func setupCamera() {
     guard let captureDevice = captureDevice else {
-      delegate?.didFail(reason: .others)
+      dismiss()
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: This should setup a generic error, not dismiss

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift [hunk 29]
```diff
@@ -148,37 +218,38 @@ class WalletScannerViewController: UIViewController {
...
+        return
+      }
+      
+      toAddress = stringValue
+      isFinishScanning = true
+      dismiss()
+    } else {
+      isFinishScanning = true
+      isErrorPresented = true
     }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Scanner/WalletScannerView.swift]: These can be all combined into a simpler flow

```swift
if !isFinishScanning, 
    let stringValue = (metadataObjects.first as? AVMetadataMachineReadableCodeObject)?.stringValue, 
    stringValue.isAddress {
  address = stringValue
  dismiss()
} else {
  isErrorPresented = true
}
isFinishScanning = true
```

Are we treating non-address as errors as well? Are we going to have a special error message for that?

File: BraveWallet/Crypto/Stores/Address.swift [hunk 30]
```diff
@@ -13,4 +13,13 @@ extension String {
...
     return "\(prefix(prefixLength))…\(suffix(4))"
   }
+  
+  /// Check if the string is a valid address
+  var isAddress: Bool {
+    // An address has to start with `0x`
+    guard starts(with: "0x") else { return false }
+    // Check the rest of the char is a hex digit
+    let clean = dropFirst(2)
+    return clean.filter(\.isHexDigit).count == clean.count
```
Comment (kylehickinson) [inline BraveWallet/Crypto/Stores/Address.swift]: Can be changed to `return dropFirst(2).allSatisfy(\.isHexDigit)`

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift (hunk 19 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Scanner/WalletScannerView.swift]: > `isAccessibilityElement = false`

it's right below at 159 😀

File: BraveWallet/Crypto/Scanner/WalletScannerView.swift (hunk 29 above)
Comment (nuo-xu) [reply BraveWallet/Crypto/Scanner/WalletScannerView.swift]: I checked other existed scanners they don't have output validation. We can treat it as invalid data to have a popup so that user knows the scan did happen but the data is wrong.

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 31]
```diff
@@ -0,0 +1,170 @@
...
+  
+  @Environment(\.presentationMode) @Binding private var presentationMode
+  
+  @State private var amountInput = ""
+  @State private var sendAddress = ""
+  @State private var isShowingScanner = false
+  
+  @ScaledMetric var length: CGFloat = 16.0
+  @ScaledMetric var recentCircleLength: CGFloat = 24.0
+  @ScaledMetric var recentIconLength: CGFloat = 14.0
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Make these private

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift [hunk 32]
```diff
@@ -0,0 +1,170 @@
...
+          header: WalletListHeaderView(title: Text(Strings.Wallet.sendCryptoToTitle))
+        ) {
+          HStack(spacing: 14.0) {
+            TextField(Strings.Wallet.sendCryptoAddressPlaceholder, text: $sendAddress)
+            Button(action: {}) {
+              Image("brave.clipboard")
+                .renderingMode(.template)
+                .foregroundColor(Color(.primaryButtonTint))
+                .font(.body)
+            }
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: For some reason when I tap this button, it shows the QR code scanner. Can you check why this happens?

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift (hunk 32 above)
Comment (kylehickinson) [reply BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift]: Oh its because you need to give both these buttons `.buttonStyle(PlainButtonStyle())` otherwise the entire cell becomes tappable

**Review by kylehickinson — APPROVED** [review]
