### PR TITLE
Fix #2940: Update VPN Settings banner UI.

### LINKED ISSUE #2940: make the "X" more visible on the VPN modal under "Settings"
### Description: 

When using the light theme, the `X` on the `VPN` modal via `Settings` is hard to see and could be perceived as a dark pattern re: making it harder to see on purpose.

### Steps to Reproduce

  1. install `1.21 (20.10.6.20)` from TF (release channel) using the light theme
  2. go into `Settings`

**Actual result:** 

Screen Shot 2020-10-06 at 8 31 02 PM

**Expected result:**

Screen Shot 2020-10-06 at 8 33 39 PM

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

* `1.21 (20.10.6.20)`

**Device details:** 

* Reproducible on all devices using `light` theme.

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jamesmudgett @aekeus @srirambv @bsclifton @iccub

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

I also fixed insets on iOS14+

This pull request fixes #2940 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Make sure you test on release channel

## Screenshots:

Zrzut ekranu 2020-10-7 o 17 53 49

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/BraveVPN/EnableVPNSettingHeader.swift [hunk 1]
```diff
@@ -91,13 +91,20 @@ class EnableVPNSettingHeader: UIView {
         }
         
         contentView.snp.makeConstraints {
-            $0.top.leading.trailing.equalToSuperview().inset(8)
+            $0.top.equalToSuperview().inset(8)
+            if #available(iOS 14, *) {
```
Comment (kylehickinson) [inline Client/Frontend/BraveVPN/EnableVPNSettingHeader.swift]: Inset grouped style is available on iOS 13 as well, so this should be 13 instead of 14

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]
