### PR TITLE
Fix #3312: Added Much Improved Find-In-Page

### LINKED ISSUE #3312: Search in pdf documents doesn’t work
### Description: 
Search in pdf documents doesn’t work

### Steps to Reproduce 
  1. Open (just an example): https://www.trm.dk/media/5076/anlaegsstatus-2-halvaar-2020.pdf
  2. Press ... and then Share with..
  3. Press find in page and do a search for an existing text string.

**Actual result:** 
No match is found in the pdf file.

**Expected result:**
Find in page find a matching text string

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave iPadOS 1.23 (21.2.12.22)

**Device details:** 
iPad Air 2, iPadOS 14.4

**Website problems only:**
- did you check with Brave Shields down? Yes, same problem
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Adds `Find-In-Page` feature for PDFs for pages using native code instead of JS
- Adds improved `Find-In-Page` for pages using native code instead of JS
- Fixes performance complaints of `Find-In-Page` as it doesn't use JS.
- Added documentation to all functions and enumerations used.

This pull request fixes #3312

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

STR in the ticket

## Screenshots:

https://i.imgur.com/wZJqMyj.mp4

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift [hunk 1]
```diff
@@ -0,0 +1,178 @@
...
+    
+    /// Not necessary, but just in case WebKit retains the delegate in the future,
+    /// it would be a good idea to restore the original state of the WebView upon destruction
+    private var originalDelegate: AnyObject?
+    
+    /// The WebView this delegate is installed in
+    private weak var webView: WKWebView?
+    
+    /// A callback function that is called when `find(string:...)` returns a result
+    private var findMatchesCallback: ((Int, Int) -> Void)?
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift:56]: Should we name parameters of this callback?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift [hunk 2]
```diff
@@ -0,0 +1,178 @@
...
+                                          .showFindIndicator,
+                                          /*.showOverlay, // Options used by Safari
+                                          .atWordStarts*/]
+    
+    /// List of selectors used. The only ones really needed is `set` and `find`.
+    /// The `get` selector is just for extra security in case something changes in the future,
+    /// with regards to retaining the delegate.
+    private static let getFindDelegateSelector = Selector(("_findDelegate"))
+    private static let setFindDelegateSelector = Selector(("_setFindDelegate:"))
+    private static let findStringSelector = Selector(("_findString:options:maxCount:"))
```
Comment (iccub) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift:72]: Safe to use it like here? In the past we tried to trick the static checker by combining the selector from 2 strings

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift (hunk 1 above)
Comment (nuo-xu) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift:56]: what are the two `Int`s?

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift [hunk 3]
```diff
@@ -0,0 +1,178 @@
...
+        }
+    }
+    
+    /// Finds a string on a Page or PDF or any searchable content
+    /// `string` - The string to find
+    /// `backwards` - Whether to search backwards (up the page) or fowards (down the page)
+    /// `completion` -  Called asynchronously when the Find Results are updated.
+    ///              - First parameter is the Index of the currently highlighted item
+    ///              - Second parameter is the Total results found on the page
+    func find(string: String, backwards: Bool, _ completion: @escaping (Int, Int) -> Void) {
```
Comment (nuo-xu) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift:138]: nvm i found them here lol

**Review by nuo-xu — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift (hunk 3 above)
Comment (iccub) [reply Client/Frontend/Browser/BrowserViewController/BrowserViewController+FindInPageDelegate.swift:138]: we can still add names for those params for better readability
