### PR TITLE
Fix #7813: Localize folder item count text.

### LINKED ISSUE #7813: 'Items' in change playlist view not translated
### Description: 
Items in change playlist folder view not translated

### Steps to Reproduce 
  1. Install `1.56.x`
  2. Change device language to non-english
  3. Navigate to video site
  4. Add media to playlist 
  5. Tap on playlist icon in url bar
  6. Select `Change Playlist`
  7. Observe 'item count' string under folder

### Actual result: 
IMG_3395

### Expected result:
'items' should be translated

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  1.56 (23.7.31.17)

- Can you reproduce this issue with the most recent build from TestFlight?  Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone, iPad

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes

This pull request fixes #7813 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Brave/Frontend/Browser/Playlist/Browser/PlaylistChangeFoldersView.swift [hunk 1]
```diff
@@ -102,6 +102,10 @@ struct PlaylistChangeFoldersView: View {
         }
       }
     }
+  
+  private func folderCountLabel(_ count: Int) -> String {
+    String(format: count == 1 ? Strings.PlayList.folderItemCountSingular : Strings.PlayList.folderItemCountPlural, count)
```
Comment (kylehickinson) [inline Sources/Brave/Frontend/Browser/Playlist/Browser/PlaylistChangeFoldersView.swift]: Probably not a big deal in this case but should probably use `String.localizedStringWithFormat`

**Review by kylehickinson — APPROVED** [review]
