### PR TITLE
Compile engines in parallel

### LINKED ISSUE #6461: Startup time increased after 1.45.* update
### Description: 
Before 1.45 update, Brave was the fastest browser. Now it takes much more time to load the application. 

### Steps to Reproduce 
  1. Open Brave Browser on iOS.

**Actual result:** 
Brave is loading fast. Even faster than Safari.

**Expected result:**
Brave is loading slower. And 2x slower, than Safari,

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Often, but looks like not every time. 

**Brave Version:** 
1.45.1 (22.11.17.19)

**Device details:** 
iPhone 11, iOS 16.1.1

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #6461

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — APPROVED** [review]

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/ContentBlockerScriptHandler.swift [hunk 1]
```diff
@@ -63,38 +63,40 @@ extension ContentBlockerHelper: TabContentScript {
...
+        
+        // Because javascript urls allow some characters that `URL` does not,
+        // we use `NSURL(idnString: String)` to parse them
+        guard let requestURL = NSURL(idnString: dto.data.resourceURL) as URL? else { return }
+        guard let sourceURL = NSURL(idnString: dto.data.sourceURL) as URL? else { return }
+        guard let domainURLString = domain.url else { return }
+        
+        // Getting this domain and current tab urls before going into asynchronous closure
+        // to avoid threading problems(#1094, #1096)
+        assertIsMainThread("Getting enabled blocklists should happen on main thread")
```
Comment (kylehickinson) [inline Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/ContentBlockerScriptHandler.swift]: This can probably be removed now

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift [hunk 2]
```diff
@@ -61,57 +61,57 @@ class SiteStateListenerScriptHandler: TabContentScript {
...
+          
+          let setup = UserScriptType.SelectorsPollerSetup(
+            frameURL: frameURL,
+            genericHide: models.contains { $0.genericHide },
+            hideSelectors: hideSelectors,
+            styleSelectors: Set(styleSelectorObjects)
+          )
+          
+          let encoder = JSONEncoder()
+          let data = try encoder.encode(setup)
```
Comment (kylehickinson) [inline Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: How large of a data set could this be? Perhaps we could execute this off-main

Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: There may be a few hundred selectors here so not too large but happy to move this off the main thread.

Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: Let me know what you think of this approach: https://github.com/brave/brave-ios/pull/6507/commits/b6efca30fc4df0cea5de35a9a043a1386e03b4a3

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/ContentBlockerScriptHandler.swift (hunk 1 above)
Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/ContentBlockerScriptHandler.swift]: Fixed here: https://github.com/brave/brave-ios/pull/6507/commits/1cde37c472b2965851f1692e23ec27727b0e7f45

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift [hunk 3]
```diff
@@ -61,61 +61,67 @@ class SiteStateListenerScriptHandler: TabContentScript {
...
-        tab.currentPageData?.framesInfo.removeValue(forKey: frameURL)
       }
     } catch {
       assertionFailure("Invalid type of message. Fix the `Site.js` script")
       Logger.module.error("\(error.localizedDescription)")
     }
   }
+  
+  private func makeArgs(from models: [CosmeticFilterModel], frameURL: URL) async throws -> String {
+    return try await Task.detached(priority: .high) {
```
Comment (kylehickinson) [inline Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: You don't need this Task.detached since async methods without specific actor isolation will run on the global executor by default

Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: Ahh that is really useful information. I'll make the change. What about the priority?

Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: Here is the change by the way: https://github.com/brave/brave-ios/pull/6507/commits/877838f335e59ae6db50ff641558598409e047fb

Comment (kylehickinson) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: Priority is inherited from the parent `Task`, so if the parent `Task` is created with `high` priority then this will inherit that :) 

Verified with this bit of code: 

```swift
func foo() async throws {
  await Task(priority: .high) { @MainActor in
    print("Task", "current priorty", Task.currentPriority, Thread.isMainThread)
    await bar()
  }.value
}

func bar() async {
  print("test", "current priorty", Task.currentPriority, Thread.isMainThread)
}
```

prints:
```
Task current priorty TaskPriority(rawValue: 25) true
test current priorty TaskPriority(rawValue: 25) false
```

Comment (kylehickinson) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: @cuba Sorry if I wasn't clear, you don't need a child `Task` at all. Not just that you don't need `detached`

Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift]: Ahh ok thank you for the clarification, here is the fix: https://github.com/brave/brave-ios/pull/6507/commits/21a1111ca5b350c0cad54e025db3e0c0a0aac308

**Comment by cuba** [comment]
@kylehickinson according to your review comments I thought this should also change: https://github.com/brave/brave-ios/commit/bb6246e84a11ee4a299e3bbd09638070aac19b57 (this is however not yet merged into this PR)

File: Client/WebFilters/ShieldStats/HttpsEverywhereStats.swift [hunk 4]
```diff
@@ -24,6 +24,19 @@ public class HttpsEverywhereStats: LocalAdblockResourceProtocol {
       setData(data: data)
     }
   }
+  
+  func shouldUpgrade(_ url: URL?) async -> Bool {
+    guard let url = url else {
+      Logger.module.error("Httpse should block called with empty url")
+      return false
+    }
```
Comment (kylehickinson) [inline Client/WebFilters/ShieldStats/HttpsEverywhereStats.swift]: A bit redundant as the closure based version does this check already

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 5]
```diff
@@ -29,14 +29,38 @@ public actor LaunchHelper {
     let task = Task {
       // Load cached data
       // This is done first because compileResources and loadCachedRuleLists need their results
-      async let loadBundledResources: Void = ContentBlockerManager.shared.loadBundledResources()
-      async let filterListCache: Void =  FilterListResourceDownloader.shared.loadCachedData()
-      async let adblockResourceCache: Void = AdblockResourceDownloader.shared.loadCachedData()
+      async let loadBundledResources: Void = measuredTask(
+        label: "bxx ContentBlockerManager.shared.loadBundledResources()", callback: {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: Can we make these labels more readable? (i.e. "Load Bundled Resources")

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 6]
```diff
@@ -64,4 +94,16 @@ public actor LaunchHelper {
...
+  private func measuredTask(label: String, callback: () async -> Void) async {
+    #if DEBUG
+    let startTime = CFAbsoluteTimeGetCurrent()
+    #endif
+    
+    await callback()
+    
+    #if DEBUG
+    print([label, "\(CFAbsoluteTimeGetCurrent() - startTime)"].joined(separator: ": "))
+    #endif
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: We could also just use OS Signposts instead.

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift [hunk 7]
```diff
@@ -64,4 +94,16 @@ public actor LaunchHelper {
       await AdBlockEngineManager.shared.startTimer()
     }
   }
+  
+  private func measuredTask(label: String, callback: () async -> Void) async {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: You probably want `@Sendable` on the callback (i.e. `callback: @Sendable () async -> Void`)

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 6 above)
Comment (kylehickinson) [inline Client/Frontend/Browser/Helpers/LaunchHelper.swift]: Move this to a `defer` instead

```swift
#if DEBUG
let startTime = CFAbsoluteTimeGetCurrent()
defer { print(label, "\(CFAbsoluteTimeGetCurrent() - startTime)") }
#endif
```

File: Client/WebFilters/ShieldStats/Adblock/AdBlockEngine+Extensions.swift [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+  ) -> [AdBlockEngineManager.Source: [AdBlockEngineManager.ResourceWithVersion]] {
+    var groups: [AdBlockEngineManager.Source: [AdBlockEngineManager.ResourceWithVersion]] = [:]
+    
+    for resourceWithVersion in resources {
+      var group = groups[resourceWithVersion.resource.source] ?? []
+      group.append(resourceWithVersion)
+      groups[resourceWithVersion.resource.source] = group
+    }
+    
+    return groups
```
Comment (kylehickinson) [inline Client/WebFilters/ShieldStats/Adblock/AdBlockEngine+Extensions.swift]: Just use `Dictionary(grouping:by:)` instead:

```swift
return Dictionary(grouping: resources, by: \.resource.source)
```

Also for future ref, you can use the `default` subscript argument to avoid the pattern inside the loop:

```swift
groups[resourceWithVersion.resource.source, default: []].append(resourceWithVersion)
```

File: Client/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift [hunk 9]
```diff
@@ -0,0 +1,149 @@
...
+  
+  init(engine: AdblockEngine, source: AdBlockEngineManager.Source, serialQueue: DispatchQueue) {
+    self.engine = engine
+    self.source = source
+    self.serialQueue = serialQueue
+  }
+  
+  deinit {
+    engine = nil
+  }
```
Comment (kylehickinson) [inline Client/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift]: This doesn't really make sense, the engine will be nil'd out anyways when the class deinit's anyways. If this is required, something else is up…

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 5 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift]: I will remove this logging for now and will wait for you to get back to get this done right. We don't really need this now (or maybe at all)

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 6 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift]: I will remove this logging for now and will wait for you to get back to get this done right. We don't really need this now (or maybe at all)

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 7 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift]: I will remove this logging for now and will wait for you to get back to get this done right. We don't really need this now (or maybe at all)

File: Client/Frontend/Browser/Helpers/LaunchHelper.swift (hunk 6 above)
Comment (cuba) [reply Client/Frontend/Browser/Helpers/LaunchHelper.swift]: I will remove this logging for now and will wait for you to get back to get this done right. We don't really need this now (or maybe at all)

File: Client/WebFilters/ShieldStats/Adblock/AdBlockEngine+Extensions.swift (hunk 8 above)
Comment (cuba) [reply Client/WebFilters/ShieldStats/Adblock/AdBlockEngine+Extensions.swift]: Nice, removed the method too as its not needed anymore

File: Client/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift (hunk 9 above)
Comment (cuba) [reply Client/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift]: I know :(. I think the serial queue is retaining the engine. I'll look more into this.

Comment (cuba) [reply Client/WebFilters/ShieldStats/Adblock/CachedAdBlockEngine.swift]: I don't know what I was seeing but I removed this engine = nil and I see no leaks anymore.  Engines are deallocated just fine. I kept my test (which was failing before) just in case. Perhaps something else I changed fixed the issue. I'll keep an eye on it just in case.

File: Client/WebFilters/ShieldStats/HttpsEverywhereStats.swift (hunk 4 above)
Comment (cuba) [reply Client/WebFilters/ShieldStats/HttpsEverywhereStats.swift]: Fixed

**Review by kylehickinson — APPROVED** [review]
Please replace all `withUnsafeContinuation` with checked equivalents. We've seen bugs in the past around unsafe continuations in backported OSs (13/14)

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/CosmeticFiltersScriptHandler.swift [hunk 10]
```diff
@@ -52,21 +52,25 @@ class CosmeticFiltersScriptHandler: TabContentScript {
...
-          return []
+      Task { @MainActor in
+        let domain = Domain.getOrCreate(forUrl: frameURL, persistent: tab?.isPrivate == true ? false : true)
+        let cachedEngines = AdBlockStats.shared.cachedEngines(for: domain)
+        
+        let selectorArrays = await cachedEngines.asyncConcurrentMap { cachedEngine -> [String] in
+          do {
+            return try cachedEngine.selectorsForCosmeticRules(
+              frameURL: frameURL,
+              ids: dto.data.ids,
```
Comment (Brandon-T) [inline Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/CosmeticFiltersScriptHandler.swift:63]: This might be a core data multithreading violation.
Domain is on a different thread than the concurrent map callback.

File: Client/WebFilters/AdBlockEngineManager.swift [hunk 11]
```diff
@@ -232,212 +122,119 @@ public actor AdBlockEngineManager: Sendable {
...
   
   /// Start a timer that will compile resources if they change
   public func startTimer() {
     guard endlessBuildTask == nil else { return }
     
-    self.endlessBuildTask = Task.detached {
-      try await withTaskCancellationHandler(operation: {
+    self.endlessBuildTask = Task(priority: .background) {
+      do {
         while true {
```
Comment (Brandon-T) [inline Client/WebFilters/AdBlockEngineManager.swift:144]: Use a timer instead of infinite loop. The timer will run at your interval and start a task. Otherwise you're infinitely blocking whatever core/thread this task is ran on.

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/CosmeticFiltersScriptHandler.swift (hunk 10 above)
Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/CosmeticFiltersScriptHandler.swift:63]: I don't see which part of the code you are referencing here. There is no `Domain` usage in this concurrent map.

Comment (cuba) [reply Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/CosmeticFiltersScriptHandler.swift:63]: If you mean this code `AdBlockStats.shared.cachedEngines(for: domain)` I do ensure the domain is on the main thread wherever I use it

File: Client/WebFilters/AdBlockEngineManager.swift (hunk 11 above)
Comment (cuba) [reply Client/WebFilters/AdBlockEngineManager.swift:144]: I used to do this on a detached Task. Perhaps I incorrectly removed that part. There is no reason I can't put it back

Comment (Brandon-T) [reply Client/WebFilters/AdBlockEngineManager.swift:144]: I'd rather something like:

Timer(sleepTime,repeating: true) {
    YourCodeHere()
}

This is because the timer will dispatch to a queue once triggered, rather than blocking an entire queue with a loop.

Comment (cuba) [reply Client/WebFilters/AdBlockEngineManager.swift:144]: The thing is that I don't think timers work in actors. I've never been able to get one working and the explanation I can give you is that actors don't use run loops and hence timers never trigger in an actor.

Comment (cuba) [reply Client/WebFilters/AdBlockEngineManager.swift:144]: Also I don't think Timer.sleep blocks an entire queue. The `sleep` function states in its documentation "This function doesn't block the underlying thread." I don't actually even need the `detached` here it would seem. I also tried this out in the following test:

```
func testBlockage() {
    let expectation = expectation(description: "Compiled engine resources")
    let engineManager = AdBlockEngineManager(stats: AdBlockStats())
    let sampleAdBlockDatURL = Bundle.module.url(forResource: "rs-ABPFilterParserData", withExtension: "dat")!
    
    Task {
      await engineManager.add(
        resource: .init(type: .dat, source: .filterList(uuid: UUID().uuidString)),
        fileURL: sampleAdBlockDatURL,
        version: nil
      )
      
      await engineManager.startTimer()
      await engineManager.compileResources()
      expectation.fulfill()
    }
    
    wait(for: [expectation], timeout: 2)
  }
  ```
  
  If the queue was blocked I think the compile would exceed the timeout and my test would fail.

**Review by Brandon-T — APPROVED** [review]
