### PR TITLE
Fix #6758: Block all schemes except http and https from Preview Links.

### LINKED ISSUE #6758: Don't show web preview for javascript links
### Description: 

For javascript links, we shouldn't show our web preview w/ ability to open in a new tab.

### Steps to Reproduce 
  1. Visit https://cp24.com/
  2. Tap and hold on any of the video title/descriptions
  3. Tap 'open in a new tab'

### Actual result: 

Brave:

https://user-images.githubusercontent.com/5314553/212188448-0552ccf1-1838-4be3-9581-4f92d29945a9.MP4

Safari:

https://user-images.githubusercontent.com/5314553/212188524-7060bb9f-16b5-4c2b-83a1-7c915251aa86.mov

### Expected result:

Don't show preview window, or option to open in a new tab

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

https://bravesoftware.slack.com/archives/GB9CJGQV6/p1673559087844689?thread_ts=1673558722.193979&cid=GB9CJGQV6

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Block all schemes except http and https from Preview Links.
- Only Http and Https schemes should be `previewed` when long-pressing a link. `file`, `data`, etc should not.

This pull request fixes #6758

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

File: Client/Frontend/Browser/BrowserViewController.swift [hunk 1]
```diff
@@ -3192,7 +3192,7 @@ extension BrowserViewController: WKUIDelegate {
     }
 
     let linkPreview: UIContextMenuContentPreviewProvider? = { [unowned self] in
-      if let tab = tabManager.tabForWebView(webView) {
+      if let tab = tabManager.tabForWebView(webView), url.schemeIsValid, ["http", "https"].contains(url.scheme) {
```
Comment (kylehickinson) [inline Client/Frontend/Browser/BrowserViewController.swift]: fyi we have `isWebPage(includeDataURIs:)` in `URLExtensions` if you want to use that

**Review by StephenHeaps — APPROVED** [review]
