### PR TITLE
Brave VPN 1.24 bugfixes

### LINKED ISSUE #3489: VPN crashes when switching regions after restoring subscription
### Description: 

I'm not really sure if this a realistic case on production but I can reproduce this crash pretty often using TF. When the subscription either expires completely or you need to restore a previous subscription, it automatically select the closest server to your location once restored despite a different location being set. If you set it back to `automatically` and then change it to another location, you'll sometimes run into a crash. I've managed to reproduce this three times.

### Steps to Reproduce

**Note:** I can't reproduce this 100% but this is a quick summary of what I did and ran into the crash

  1. sign up for VPN and get a monthly subscription
  2. once the VPN is enabled switch to a random region
  3. wait ~10-20min until the subscription times out/expires
  4. restore the subscription and you'll notice that the server closest to you is being used even though you have another region selected
  5. switch through a few locations and eventually you'll run into a crash

**Actual result:** 

* `Crash #1` - [Client-2021-03-30-120441.ips.beta.txt](https://github.com/brave/brave-ios/files/6230629/Client-2021-03-30-120441.ips.beta.txt)
* `Crash #2` - [Client-2021-03-30-115633.ips.beta.txt](https://github.com/brave/brave-ios/files/6230633/Client-2021-03-30-115633.ips.beta.txt)
* `Crash #3` - [Client-2021-03-30-124149.ips.beta.txt](https://github.com/brave/brave-ios/files/6230704/Client-2021-03-30-124149.ips.beta.txt)

**Expected result:**

Brave shouldn't be crashing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

It's not the easiest to reproduce as you need to get into a certain state but I managed to run into the above three times.

**Brave Version:** 

* `1.24 (21.3.29.21)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.4` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @iccub @bsclifton @brave/legacy_qa

### LINKED ISSUE #3490: brave not using selection server region when restoring subscription
### Description: 

When restoring a subscription, it will usually always use the `Automatic` choice and select a sever near your current location even though you had something else selected via the settings. For example:

* `Japan` is selected as the default location
* Subscription either expires or times out
* Restore your subscription and your VPN server will be something close to your location rather than `Japan`

### Steps to Reproduce
 
  1. launch `1.24` via TF (`1.24 (21.3.29.21)` in this case)
  2. sign up/grab a subscription for the VPN service (picked the monthly subscription)
  3. once the VPN service has been setup/installed, change the location to `Japan`
  4. wait ~10min or so until the subscription expires
  5. restore the subscription or get a new one (sometimes you can restore/sometimes you need to renew)
  6. once the VPN is enabled again, you'll notice you're using a VPN server closer to your location and not `Japan`

**Note:** Can use any location, doesn't have to be `Japan`.

**Actual result:** 

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------
IMG_3635 | IMG_3636 | IMG_3637

**Expected result:**

When a user has a custom region selected, we should be using that region when restoring subscriptions and not using `automatic` which selects a server close to your current location.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR. Managed to reproduce this every time when restoring subscriptions.

**Brave Version:** 

* `1.24 (21.3.29.21)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.4` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @bsclifton @iccub @brave/legacy_qa

### LINKED ISSUE #3492: location appears empty for certain VPN regions
### Description: 

Certain regions are not being displayed under the `Location` heading under `Settings`. This affects the following regions:

* `Brazil`, `Switzerland`, `Spain` & `USA (West)`

### Steps to Reproduce
 
  1. launch `1.24` via TF (used `1.24 (21.3.29.21)` in this case)
  2. signup/restore the Brave VPN service
  3. go into `Settings` -> `Brave Firewall + VPN` and click on `Change Location`
  4. select either `Brazil`, `Switzerland`, `Spain` or  `USA (West)`
  5. notice that the `Location` appears as `-` rather than specifically mentioning a location like the other region/locations

**Actual result:** 

**`Brazil`** | **`Switzerland`** | **`Spain`** | **`USA (West)`**
-----------|--------------------|--------------|-------------------
IMG_3654 | IMG_3653 | IMG_3652 | IMG_3650

**Expected result:**

Location should be appearing. Example:

113030177-4fb14080-915b-11eb-8853-8bb183afed48

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR.

**Brave Version:** 

* `1.24 (21.3.29.21)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.4` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @iccub @brave/legacy_qa

### LINKED ISSUE #3494: "Continue to Email" button under "Contact Technical Support" doesn't work on all devices
### Description: 

On some devices, particularly `iPhone 11` & `iPhone 12`, the `Continue to Email` under `Contact Technical Support` doesn't work. However, it's working on fine on all my other devices and @srirambv mentioned it works fine on his `iPhone 7` device that's also running `iOS 14.4.2`. 

This is also reproducible using `1.23.1 (21.2.24.16)`, Appears that it regressed a while ago.

### Steps to Reproduce

  1. sign up for VPN and get a monthly subscription
  2. once the VPN has connected, go into `Settings` -> `Brave Firewall + VPN` -> `Contact Technical Support`
  3. click on `Continue to Email` and you'll notice nothing happens 

**Actual result:** 

Example of the issue occurring: https://youtu.be/CtWGCn_EZYE

**Expected result:**

The `Continue to Email` button under `Contact Technical Support` should work as expected and let users submit reports.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.24 (21.3.29.21)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.4.2` - **Reproduced**
* `iPhone 12` running `iOS 14.4.2` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @iccub @brave/legacy_qa

### PR DESCRIPTION
**Pull request by iccub**
merge by rebase

## Summary of Changes

This pull request fixes #3489, fixes #3490, fixes #3492, fixes #3494 

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/BraveVPN/BraveVPNRegionPickerViewController.swift [hunk 1]
```diff
@@ -190,17 +193,24 @@ extension BraveVPNRegionPickerViewController: UITableViewDelegate, UITableViewDa
...
             // Here we observe vpn status and we show success alert if it connected,
-            // otherwise an error alert is show if it did not manage to connect in 30 seconds.
+            // otherwise an error alert is show if it did not manage to connect in 60 seconds.
             self.dispatchGroup?.enter()
             
-            DispatchQueue.main.asyncAfter(deadline: .now() + 30) {
+            DispatchQueue.main.asyncAfter(deadline: .now() + 60) {
+                self.vpnRegionChangeSuccess = false
+                self.dispatchGroup?.leave()
                 self.dispatchGroup = nil
```
Comment (iccub) [inline Client/Frontend/BraveVPN/BraveVPNRegionPickerViewController.swift:202]: im thinking if it's even worth to use dispatch group for this task,
goal is to listen and act on one of two conditions:
- vpn reconnected
- 60secs has passed

**Review by kylehickinson — APPROVED** [review]

**Review by soner-yuksel — APPROVED** [review]
