### PR TITLE
Fix #5848: Remove pending request indicator (badge) from the wallet icon in URL bar once wallet has been reset

### LINKED ISSUE #5848: Wallet reset doesn't remove wallet notification badge
### Description: 
Wallet reset doesn't remove wallet notification badge

### Steps to Reproduce 
  1. Initiate a wallet notification badge
  2. Open Settings and reset wallet
  3. Wallet icon in URL bar continues to show the badge
  4. Click on wallet opens onboarding 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/184400630-37b40d65-2f7c-4a72-a473-1f4fa90fee66.MP4

**Expected result:**
Should remove badge when wallet is reset

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.11.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

### PR DESCRIPTION
**Pull request by nuo-xu**
## Summary of Changes
Cancel all pending request once wallet has been reset

This pull request fixes #5848 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:
Please refer to the issue.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift [hunk 1]
```diff
@@ -147,33 +147,10 @@ extension BrowserViewController {
...
-           let walletService = walletService,
-           let swapService = swapService {
-          networkStore = NetworkStore(
-            keyringService: keyringService,
-            rpcService: rpcService,
-            walletService: walletService,
-            swapService: swapService
-          )
-        }
+        let privateMode = PrivateBrowsingManager.shared.isPrivateBrowsing
```
Comment (StephenHeaps) [inline Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift]: nit: `isPrivateMode` / `isPrivateBrowsing` to follow swift conventions

**Review by StephenHeaps — APPROVED** [review]
