### PR TITLE
Custom homepage minor fixes

### LINKED ISSUE #2499: Replace generic QR code icon for SR install
### Description: 
Replace generic QR code icon for SR install

**Actual result:** 
Uses a generic QR code icon for SR 

**Expected result:**
Icon should be as per spec

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.16

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### LINKED ISSUE #2500: Background images type option should be disabled when Show background images is disabled
### Description: 
Background images type option should be disabled when Show background images is disabled

### Steps to Reproduce 
  1. Install a SR build
  2. Disable `Show Background Images` under New Tab page options
  3. `Background Images` type is still enabled and selectable 

**Actual result:** 
Background images type option should be disabled when Show background images is disabled

**Expected result:**
Should hide image types option

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.16

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### LINKED ISSUE #2501: QR code title is not visible and doesn't match device theme
### Description: 
QR code modal title not visible on dark mode

### Steps to Reproduce 
  1. Set device theme to dark
  2. Install SR build
  3. Open QR code title is not visible and doesn't match device theme 

**Actual result:** 
QR code title is not visible and doesn't match device theme 

**Expected result:**
QR code title should be visible and match device theme 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.16

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
Please merge by rebase.

Fixes #2499 
Fixes #2500 
Fixes #2501 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

Zrzut ekranu 2020-04-30 o 19 12 43
Zrzut ekranu 2020-04-30 o 19 12 37
Zrzut ekranu 2020-04-30 o 19 12 31

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Settings/NTPTableViewController.swift [hunk 1]
```diff
@@ -94,14 +109,10 @@ class NTPTableViewController: TableViewController {
...
-            Row.boolRow(title: Strings.NTP.settingsBackgroundImages, option: Preferences.NewTabPage.backgroundImages),
-            moreSetting(section: section)
-        ]
-        return section
-    }()
+}
+
+extension NTPTableViewController: PreferencesObserver {
+    func preferencesDidChange(for key: String) {
+        loadSections()
```
Comment (iccub) [inline Client/Frontend/Settings/NTPTableViewController.swift:116]: This is unfortunate, but the `Static` framework isn't super flexible when it comes to dynamically updating rows, and there's no provided method to disable the row or hide it.

**Review by Brandon-T — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
