### PR TITLE
Fix #463: Fixes resolution issue in the favorites view

### LINKED ISSUE #463: Favourites show low resolution icons for some sites
### Description: 
Favourites show low resolution icons for some sites

### Steps to Reproduce 
  1. Visit https://quora in a new tab and add to favourites
  2. Open a new tab, shows low resolution image
  3. Add to bookmark, image doesn't look like low resolution because of small size

**Actual result:** 
image from ios

FF
image from ios 1

**Expected result:**
Should look similar to FF 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by danielbogomazov**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Notes for testing this patch

Fixes [issue 463](https://github.com/brave/brave-ios/issues/463)

The issue stems from passing in a non-nil icon value into the setIcon function which uses that image as an upscale instead of using the FaviconFetcher.

### CODE REVIEW

File: Client/Frontend/Browser/HomePanel/favorites/FavoritesDataSource.swift [hunk 1]
```diff
@@ -67,9 +67,10 @@ class FavoritesDataSource: NSObject, UICollectionViewDataSource {
         guard let fav = frc?.object(at: indexPath) else { return UICollectionViewCell() }
 
         cell.textLabel.text = fav.displayTitle ?? fav.url
-        cell.imageView.setIcon(fav.domain?.favicon, forURL: URL(string: fav.url ?? ""), scaledDefaultIconSize: CGSize(width: 40, height: 40), completed: { (color, url) in
+        let n: FaviconMO? = nil // Distinguishes which setIcon function is called
```
Comment (jhreis) [inline Client/Frontend/Browser/HomePanel/favorites/FavoritesDataSource.swift]: This is kind of an interesting workaround, however, there should be a more determined solution than using a typed optional set to nil to choose the function. One option would be to give the `setIcon` function different declarations/names, to avoid overloading and calling the wrong function.

**Comment by danielbogomazov** [comment]
The function names have been changed to help distinguish them. Let me know if there's anything else to fix :)

**Review by jhreis — APPROVED** [review]

**Comment by jhreis** [comment]
Thanks bunches! Really appreciate the work on this, and thanks for your huge patience with us 😄
