### PR TITLE
Fix #6173: Show correct Tabs Bar visibility state on iPad

### LINKED ISSUE #6173: Tabs are showing on upgraded profile [iPad]
### Description: 
Tabs bar is showing on upgraded profile, does not impact iPhone

### Steps to Reproduce 
  1. Install app version 1.43.x
  2. Confirm that Tabs switch is off by default
  3. Open some tabs
  4. Upgrade to 1.44 (22.10.13.13)
  5. Relaunch brave
  6. Observe tabs bar on NTP
  7. Check the tab switch state in the settings

**Actual result:** 
Tabs bar is shown, Tab Bar switch state is set to off

IMG_0661

**Expected result:**
Tabs should not be showing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.44.x

**Device details:** 
iPad Only

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by kylehickinson**
- First launch now only sets tabs bar visibility to `landscapeOnly` on phones
- Settings is now a bit more lenient on showing Tabs Bar setting as on even if the pref is set to `landscapeOnly`

## Summary of Changes

This pull request fixes #6173 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Settings/SettingsViewController.swift [hunk 1]
```diff
@@ -333,7 +333,7 @@ class SettingsViewController: TableViewController {
     
     if UIDevice.current.userInterfaceIdiom == .pad {
       tabs.rows.append(
-        Row(text: Strings.showTabsBar, image: UIImage(named: "settings-show-tab-bar", in: .module, compatibleWith: nil)!.template, accessory: .switchToggle(value: Preferences.General.tabBarVisibility.value == TabBarVisibility.always.rawValue, { Preferences.General.tabBarVisibility.value = $0 ? TabBarVisibility.always.rawValue : TabBarVisibility.never.rawValue }), cellClass: MultilineValue1Cell.self)
+        Row(text: Strings.showTabsBar, image: UIImage(named: "settings-show-tab-bar", in: .module, compatibleWith: nil)!.template, accessory: .switchToggle(value: Preferences.General.tabBarVisibility.value != TabBarVisibility.never.rawValue, { Preferences.General.tabBarVisibility.value = $0 ? TabBarVisibility.always.rawValue : TabBarVisibility.never.rawValue }), cellClass: MultilineValue1Cell.self)
```
Comment (iccub) [inline Client/Frontend/Settings/SettingsViewController.swift]: maybe break this long line, hard to notice the toggle logic at first glance

**Review by iccub — APPROVED** [review]

File: Client/Frontend/Settings/SettingsViewController.swift (hunk 1 above)
Comment (kylehickinson) [reply Client/Frontend/Settings/SettingsViewController.swift]: Haha easier to read now, but harder to tell what changed since git cant highlight the changed part in the line :P
