### PR TITLE
Fix #2119: Add preference around opening external apps

### LINKED ISSUE #2119: Switching to external without permission [Follow up to #551]
### Description: 
Switching to external without permission [Follow up to #551] 

### Steps to Reproduce 
  1. Install blick app from app store
  2. Upgrade to 1.14.1 via appstore
  3. Search for blick.ch and click on search result, automatically opens the installed app

**Actual result:** 
No user permission asked before switching to external app

**Expected result:**
Should have asked persmission which was the fix on #551 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.1

**Device details:** 
iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Reported on community https://community.brave.com/t/ask-before-open-app-instead-of-website/97970 and reproduced on iPhone
Adding same security labels as #551 
cc: @jumde

### PR DESCRIPTION
**Pull request by kylehickinson**
Also disables opening external apps while browsing in Private Mode

## Summary of Changes

This pull request fixes #2119 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Verify tapping universal links open apps by default in regular browsing mode
- Verify tapping universal links never open apps by default in private browsing mode
- Verify that switching the preference in _Brave Shields & Privacy_ page allows you to mimic private browsing mode behavior in regular mode

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: BraveShared/BraveStrings.swift [hunk 1]
```diff
@@ -585,6 +585,7 @@ extension Strings {
 
 extension Strings {
     public static let blockPopups = NSLocalizedString("BlockPopups", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Block Popups", comment: "Setting to enable popup blocking")
+    public static let followUniversalLinks = NSLocalizedString("FollowUniversalLinks", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Allow universal links to open in external apps", comment: "Setting to follow universal links")
```
Comment (iccub) [inline BraveShared/BraveStrings.swift:588]: This text is too cryptic for average user imo, or needs additional explanation in settings cell body

Comment (kylehickinson) [reply BraveShared/BraveStrings.swift:588]: cc @jamesmudgett @anthonypkeane

Comment (kylehickinson) [reply BraveShared/BraveStrings.swift:588]: Got confirmations that copy is OK here:

James - https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1613663957390700
Anthony - https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1613758058430400?thread_ts=1613751704.426100&cid=G01F4JUNXAQ

**Review by iccub — APPROVED** [review]
