### PR TITLE
Fix #4009: Disable History sync when user switches to PB only 

### LINKED ISSUE #4009: Disable History sync when user switches to PB only
### Description: 
Disable History sync when user switches to PB only

### Steps to Reproduce 

**Scenario 1 - PB Only mode before sync is enabled**
  1. Enable PB only mode
  2. Enable Sync and join a sync chain or add devices to the new one
  3. History from other devices show up on iOS
  4. Clear browser history from other device, history sync'd is also removed on iOS

**Scenario 2 - PB only mode after sync is enabled**
  1. Create a sync chain or join one 
  2. Enable history sync 
  3. Switch to PB only mode
  4. No further history is sync'd from iOS but history from other devices and normal tabs history still sync's

**Actual result:** 
History sync is enabled on all the three scenarios which defeats the purpose of private tabs only mode

**Expected result:**
Disable History sync when a user switches to PB only mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.30(21.8.5.11)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel @jumde

### PR DESCRIPTION
**Pull request by soner-yuksel**
History Private Browsing Only overlay is added in case PB Only Mode is enabled.
And hiding the "Delete All" button.

## Summary of Changes

This pull request fixes #4009

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Check History When B Only mode is enabled and sync items are being seen or an overlay is hown

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — COMMENTED** [review]
Maybe hide the delete-all button too?

**Comment by soner-yuksel** [comment]
> Maybe hide the delete-all button too?


You are totally right, we should hide the "Delete".

Change is at https://github.com/brave/brave-ios/pull/4013/commits/b944cbedbddfe8f057a33eecf516a2f965f6c7af

File: Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift [hunk 1]
```diff
@@ -48,12 +48,20 @@ class HistoryViewController: SiteTableViewController, ToolbarUrlActionsProtocol
...
+        if !Preferences.Privacy.privateBrowsingOnly.value {
+            navigationItem.rightBarButtonItem =
+                UIBarButtonItem(image: #imageLiteral(resourceName: "playlist_delete_item").template, style: .done, target: self, action: #selector(performDeleteAll))
+        }
     }
     
     override func viewWillAppear(_ animated: Bool) {
         super.viewWillAppear(animated)
         
+        guard !Preferences.Privacy.privateBrowsingOnly.value else {
```
Comment (iccub) [inline Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: convert to `if` this is too hard to read imo, two negations

Comment (soner-yuksel) [reply Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift]: Actually I always try to `guard` the initial conditions instead of showing them inside If clause but this particular conditions, you are right it is very hard to read.

Change at https://github.com/brave/brave-ios/pull/4013/commits/1125af9d61d254a04478cfdd92ceaa3c0d8a8079

**Review by iccub — APPROVED** [review]
