### PR TITLE
Fix #2518: Crash when favorites are inserted to NTP.

### LINKED ISSUE #2518: Browser crash when installing SR build
### Description: 
Browser crash when installing SR build

### Steps to Reproduce 
  1. Launch SR 
  2. Install dev build via TF
  3. Launch browser, crashes after a few seconds

**Actual result:** 
https://bravesoftware.slack.com/archives/CT7JC4KBM/p1588838082344400?thread_ts=1588830163.336500&cid=CT7JC4KBM

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

**Brave Version:** 
1.16(20.5.4.12)

**Device details:** 
iPad and iPhone running iOS 12

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Doesn't reproduce on iOS 13. 
cc: @iccub

### PR DESCRIPTION
**Pull request by iccub**
## Summary of Changes
This will require a bigger rework at some point, or just dropping FRC for this collection view, see https://stackoverflow.com/questions/20554137/nsfetchedresultscontollerdelegate-for-collectionview

This pull request fixes #2518 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/Frontend/Browser/HomePanel/favorites/FavoritesDataSource.swift [hunk 1]
```diff
@@ -133,6 +133,7 @@ extension FavoritesDataSource: NSFetchedResultsControllerDelegate {
             // otherwise it crashes with inconsistency exception.
             if let indexPath = newIndexPath, indexPath.row < columnsPerRow {
                 collectionView?.insertItems(at: [indexPath])
+                collectionView?.reloadData()
```
Comment (iccub) [inline Client/Frontend/Browser/HomePanel/favorites/FavoritesDataSource.swift]: Kind of related to http://www.openradar.me/15262692
Without this, on iOS 12 `NSInternalInconsistencyException` error is thrown when creating favorites

**Review by jhreis — APPROVED** [review]
