### PR TITLE
Fix #4677: Prefill default buy/send/swap token if user comes from token details screen

### LINKED ISSUE #4677: Selecting Swap from a token doesn't set it as the swap from token
### Description: 
Selecting Swap from a token doesn't set it as the swap from token

### Steps to Reproduce 

1.  Create/Restore wallet
2. Select BAT from portfolio
3. Select swap on the token details page
4. Swap sheet opens up but its set fro Swap from ETH to BAT instead of Swap from BAT to ETH

**Actual result:** 
Selecting Swap from a token doesn't set it as the swap from token

**Expected result:**
Should set BAT as swap from token as swap was initiated from that asset details page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by nuo-xu**
This pull request fixes #4677 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Case 1:
1. Go to buy/send/swap screen from Asset Detail Screen
2. Make sure the prefilled buy token, or send from token, or swap from token is the same as the token from the asset details screen (swap to token should not be the same as the swap from token)

Case 2:
1. Make sure the selected network is NOT Ropsten
2. Go to buy/send/swap screen from anywhere but NOT Asset Detail Screen
3. Make sure prefilled buy token is BAT, prefilled send from token is ETH, prefilled swap from token is ETH, the prefilled swap to token is BAT

Case 3:
1. Make sure the selected network is Ropsten
2. Go to send/swap screen from anywhere but NOT Asset Detail Screen
3. prefilled send from token is ETH, prefilled swap from token is ETH, prefilled swap to token is DAI

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by soner-yuksel** [comment]
BraveWalletTests are failing.

File: BraveWallet/Crypto/BuySendSwap/BuySendSwapDestination.swift [hunk 1]
```diff
@@ -6,15 +6,26 @@
...
-  case buy
-  case send
-  case swap
+enum BuySendSwapDestination: Identifiable, CaseIterable, Equatable, Hashable {
+  
+  static var allCases: [BuySendSwapDestination] = [.buy(), .send(), .swap()]
+  
+  case buy(BraveWallet.ERCToken? = nil)
+  case send(BraveWallet.ERCToken? = nil)
+  case swap(BraveWallet.ERCToken? = nil)
```
Comment (kylehickinson) [inline BraveWallet/Crypto/BuySendSwap/BuySendSwapDestination.swift]: If all of these take the same arg, it doesn't make sense to use an enum w/ associated value. Better to keep `BuySendSwapDestination` the same and put it inside a container `struct` i.e.

```swift
struct BuySendSwapDestination: Identifiable, Equatable, Hashable {
   enum Kind: Identifiable, CaseIterable, Equatable, Hashable { case buy, send, swap }
   var kind: Kind
   var initialToken: BraveWallet.ERCToken?
   var id: String { kind.id }
}
```

**Review by kylehickinson — CHANGES_REQUESTED** [review]

**Comment by nuo-xu** [comment]
> BraveWalletTests are failing.

fixed the unit tests :)

**Review by kylehickinson — CHANGES_REQUESTED** [review]
1. Maybe add some unit tests for prefilled tokens to ensure the selected tokens are correct.
2. If a user taps "buy" from a token that doesn't exist in the buy list supported by Wyre don't we need some sort of validation there before setting it as the `selectedBuyToken`?

**Comment by nuo-xu** [comment]
> 
hey @kylehickinson 
1. I will add unit tests to test prefilled tokens
2. This is clearly mobile only UX problem since desktop has no such flow that you click into token details and then go to buy token from there. So on desktop, the panel will only give you a list of Wyre supported tokens from `TokenRegistery.buyTokens`. I've tried this case on the current mobile flow(I added a random ERC20 token to my visible assets and try to buy this token from the token details screen), since the buy url is generated using account address and the token symbol, the url is still valid with website UI also makes sense. It is just going to be impossible for you to buy this token. I think this is acceptable behaviour for now.
Screenshot: 
IMG_87611756725F-1

File: BraveWallet/Crypto/Stores/SwapTokenStore.swift [hunk 2]
```diff
@@ -561,9 +563,17 @@ public class SwapTokenStore: ObservableObject {
         }
       } else {
         if chainId == BraveWallet.MainnetChainId {
-          selectedToToken = allTokens.first(where: { $0.symbol.uppercased() == "BAT" })
+          if let fromToken = selectedFromToken, fromToken.symbol.uppercased() == "BAT" {
```
Comment (Brandon-T) [inline BraveWallet/Crypto/Stores/SwapTokenStore.swift]: Can store `BAT` and `DAI` as constants somewhere?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

**Review by kylehickinson — APPROVED** [review]

**Comment by iccub** [comment]
Needs test plan

**Comment by nuo-xu** [comment]
> Needs test plan

Test plan added

**Review by Brandon-T — APPROVED** [review]
