### PR TITLE
Fix #2285: Fix NTP SI foreground timer

### LINKED ISSUE #2285: NTP SI not updating when app is in foreground for long time.
### Steps to Reproduce 
  1. Hard to test, needs coordination with server resources.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by Brandon-T**
Fixes the NTP timer calculation being off when you come back from the background after a longer period of time than the 5hours + max variance.

## Summary of Changes

This pull request fixes issue #2285 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
I'll wait for @iccub to merge but looks good

**Review by jhreis — APPROVED** [review]

**Comment by iccub** [comment]
Looks good, running final tests to verify

File: Client/Frontend/Browser/HomePanel/NTPDownloader.swift [hunk 1]
```diff
@@ -16,7 +17,13 @@ class NTPDownloader {
     private static let etagFile = "crc.etag"
     private static let metadataFile = "photo.json"
     private static let ntpDownloadsFolder = "NTPDownloads"
-    private static let baseURL = "https://brave-ntp-crx-input-dev.s3-us-west-2.amazonaws.com/"
+    private static let baseURL = { () -> String in
+        switch BraveLedger.environment {
+        case .production: return "https://brave-ntp-crx-input.s3-us-west-2.amazonaws.com/"
+        case .development: return "https://brave-ntp-crx-input-dev.s3-us-west-2.amazonaws.com/"
+        default: return "https://brave-ntp-crx-input.s3-us-west-2.amazonaws.com/"
```
Comment (kylehickinson) [inline Client/Frontend/Browser/HomePanel/NTPDownloader.swift]: Better if you just have `case .staging, .development:` instead of default (unless you want staging to point to prod servers? Then in that case `case .production, .staging`)

**Review by jhreis — APPROVED** [review]
