### PR TITLE
Fix #882: Disabled edit mode button when no bookmarks exist (note: no…

### LINKED ISSUE #882: When no bookmarks exist, edit mode shouldn't be active
### Description: 
When no bookmarks exist, edit mode shouldn't be active

### Steps to Reproduce 
  1. Add a single bookmark
  2. Go to edit mode and delete the bookmark
  3. Add a bookmark, goes directly into edit mode

**Actual result:** 
ezgif com-video-to-gif gif

**Expected result:**
When no bookmarks exist, edit mode should not be active

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by BekzhanKaspakov**
…w also exits edit mode when last bookmark is deleted)

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

Edit mode button disabled:
1. When you open bookmarks tab with no bookmarks.
2. When you delete last bookmark in edit mode
3. When you delete last bookmark without accessing edit mode

Edit mode button is re-enabled when you add a bookmark into an empty bookmarks list.
When last bookmark is deleted in edit mode, switches to not editing mode. 

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

File: Client/Frontend/Menu/BookmarksViewController.swift [hunk 1]
```diff
@@ -180,6 +180,12 @@ class BookmarksViewController: SiteTableViewController {
       print(error.description)
     }
     
+    if tableView.isEditing == false && bookmarksFRC?.fetchedObjects?.count == 0 {
```
Comment (jhreis) [inline Client/Frontend/Menu/BookmarksViewController.swift]: If table is blocked from being in edit mode while then this check isn't necessary.

File: Client/Frontend/Menu/BookmarksViewController.swift [hunk 2]
```diff
@@ -180,6 +180,12 @@ class BookmarksViewController: SiteTableViewController {
...
+        editBookmarksButton?.isEnabled = false
```
Comment (jhreis) [inline Client/Frontend/Menu/BookmarksViewController.swift]: Since this is just using a boolean conditional for a value setter

e.g.
```
if foo
    bar = true // value of `foo`
else 
    bar = false // value of `foo`
```

We can just always perform `bar = foo`:

```
editBookmarksButton.isEnabled = bookmarksFRC?.fetchedObjects?.count != 0

File: Client/Frontend/Menu/BookmarksViewController.swift [hunk 3]
```diff
@@ -180,6 +180,12 @@ class BookmarksViewController: SiteTableViewController {
...
+    } else {
+        editBookmarksButton?.isEnabled = true
```
Comment (jhreis) [inline Client/Frontend/Menu/BookmarksViewController.swift]: `editBookmarksButton` is forced unwrapped in the declaration so `?` is not necessary.

File: Client/Frontend/Menu/HomeMenuController.swift [hunk 4]
```diff
@@ -92,7 +92,12 @@ class HomeMenuController: UIViewController, PopoverContentComponent {
     
     bookmarksController.linkNavigationDelegate = self
     bookmarksController.bookmarksDidChange = { [weak self] in
-      self?.updateBookmarkStatus()
+        self?.updateBookmarkStatus()
+        if self?.bookmarksController.bookmarksFRC?.fetchedObjects?.count ?? 0 < 1 {
```
Comment (jhreis) [inline Client/Frontend/Menu/HomeMenuController.swift]: See above comment about this too.

**Review by jhreis — DISMISSED** [review]
Thanks for the helpful PR! This is really helpful! I left a few comments for changes.

Also, the following scenario does not seem to be handled:

1. on fresh launch, save a folder
1. go into new folder
1. save a bookmark
1. observe edit button is still disabled

Again, really nice work, and greatly appreciate your time and effort here!

File: Client/Frontend/Menu/HomeMenuController.swift (hunk 4 above)
Comment (BekzhanKaspakov) [reply Client/Frontend/Menu/HomeMenuController.swift]: I am worried if I messed up the tabulation size here. Is it ok for me to continue using tab size of 4 in this file, because it was 4 in other files?

Comment (BekzhanKaspakov) [reply Client/Frontend/Menu/HomeMenuController.swift]: If I understood correctly, the `?` is not necessary here. But when I tried removing it I got following error message. So should I leave it?

> Value of optional type 'HomeMenuController?' must be unwrapped to refer to member 'bookmarksController' of wrapped base type 'HomeMenuController'
Chain the optional using '?' to access member 'bookmarksController' only for non-'nil' base values
Force-unwrap using '!' to abort execution if the optional value contains 'nil'

File: Client/Frontend/Menu/BookmarksViewController.swift (hunk 3 above)
Comment (BekzhanKaspakov) [reply Client/Frontend/Menu/BookmarksViewController.swift]: Build succeeds, however when you try pressing menu button throws:

> Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

File: Client/Frontend/Menu/BookmarksViewController.swift (hunk 1 above)
Comment (BekzhanKaspakov) [reply Client/Frontend/Menu/BookmarksViewController.swift]: This was for checking when you open menu button. I will move it viewDidLoad() for clarity.

**Comment by BekzhanKaspakov** [comment]
Ignore commit `931140e`, I forgot to remove my debug `print()` there.

**Review by BekzhanKaspakov — COMMENTED** [review]
Made changes necessary to comments in the previous commit and fixed the case with deleting bookmarks inside a folder. @jhreis I unsure if this is the way to notify you that changes were made, I am sorry if I am bothering you, but I couldn't find any other way of notifying you.

**Review by iccub — APPROVED** [review]
Hi, sorry for having to wait so long. The PR looks good and I'm approving it.
I also rebased it and updated slightly because our menu has changed since March

Thanks for your contribution :)
