### PR TITLE
Fix #5700: Fix issues with JS urls using invalid characters

### LINKED ISSUE #5700: Issue with some request URLs not being parsed properly when request blocking
### Description: 
The issue is with some characters that are allowed in JS URL that are not allowed with swift URL

### Steps to Reproduce 
  1. Use debug mode
  2. Go around the amazon website (click links, scroll, etc)
  3. Should get an assertion failure (this crash only happens on debug mode, does not crash in production)

**Actual result:** 
Assertion failure triggered

**Expected result:**
No assertion should be triggered

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #5700 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Sources/Shared/Extensions/URLExtensions.swift [hunk 1]
```diff
@@ -114,6 +114,19 @@ private let ignoredSchemes = ["data"]
...
+  public init?(javascriptURLString urlString: String) {
+    if let url = URL(string: urlString) {
+      self = url
+    } else if let escapedURLString = urlString.addingPercentEncoding(withAllowedCharacters: .URLAllowed), let url = URL(string: escapedURLString) {
+      self = url
+    } else {
+      return nil
+    }
+  }
+
```
Comment (kylehickinson) [inline Sources/Shared/Extensions/URLExtensions.swift]: Please move this (and its accompanying tests) to `BraveShared`/`BraveSharedTests`, we are not adding code to the Shared module anymore

**Review by kylehickinson — CHANGES_REQUESTED** [review]

File: Sources/Shared/Extensions/URLExtensions.swift (hunk 1 above)
Comment (cuba) [reply Sources/Shared/Extensions/URLExtensions.swift]: No problem!

File: BraveShared/Extensions/URLExtensions.swift [hunk 2]
```diff
@@ -7,6 +7,19 @@ import Foundation
 import BraveCore
 
 extension URL {
+  /// Attempt to make a url that is sourced from a javascript `URL.href`.
+  ///
+  /// Since javascript's `URL` is more loose with acceptable caracters (such as `|`), we need to ensure such characters are escaped properly before we attempt to make a URL out of it.
+  public init?(javascriptURLString urlString: String) {
+    if let url = URL(string: urlString) {
```
Comment (Brandon-T) [inline BraveShared/Extensions/URLExtensions.swift]: Does it create a correct URL if you use `NSURL(idnString:)` instead of `URL(string:)` with the `|` character?

**Review by Brandon-T — CHANGES_REQUESTED** [review]

File: Client/WebFilters/ContentBlocker/RequestBlockingContentHelper.swift [hunk 3]
```diff
@@ -63,29 +63,31 @@ class RequestBlockingContentHelper: TabContentScript {
         return
       }
       
+      guard let requestURL = URL(javascriptURLString: dto.data.resourceURL) else { return }
+      guard let sourceURL = URL(javascriptURLString: dto.data.sourceURL) else { return }
```
Comment (kylehickinson) [inline Client/WebFilters/ContentBlocker/RequestBlockingContentHelper.swift]: Small nit: these can be one guard statement

File: BraveShared/Extensions/URLExtensions.swift (hunk 2 above)
Comment (cuba) [reply BraveShared/Extensions/URLExtensions.swift]: It does actually

**Review by Brandon-T — APPROVED** [review]

**Review by soner-yuksel — APPROVED** [review]

**Review by kylehickinson — APPROVED** [review]
