### PR TITLE
Fix #1911 - Clear Enrollment data when restoring a wallet

### LINKED ISSUE #1911: Restoring a wallet does not Enroll the user
### Description: 
When restoring a wallet to an existing wallet, the `isDeviceEnrolled` function returns true that the device is already enrolled because in order to restore a wallet, you must have enrolled previously with a dummy/fake wallet in the first place.

### Steps to Reproduce 
  1. Create a wallet (the dummy/fake wallet)
  2. Restore to existing wallet
  3. Claim a grant.

**Actual result:** 
1. Device is already enrolled from step 1 with paymentId from step 1.. but should be re-enrolled with paymentId from step 2 upon restoring.
2. Claim will fail.

**Expected result:**
1. Claim succeeds.
2. Device re-enrolled.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Extremely Often.

**Brave Version:** 
1.3.x

**Device details:** 
Any Device.

**Website problems only:**
- did you check with Brave Shields down? (N/A)
- did you check in Safari/Firefox (WkWebView-based browsers)?  (N/A)

### PR DESCRIPTION
**Pull request by Brandon-T**
When a wallet is successfully restored, remove the old private-key and enrollment preferences. This will cause it to generate a new private key during re-enrollment when claiming a grant.

## Summary of Changes

This pull request fixes issue #1911

- Delete the existing private key and preference when you restore a wallet.
- We can optionally keep the same private-key and just set the preference but I opted for both just in case someone decides to mess with their info.plist somehow.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

File: Client/DeviceCheck/Cryptography.swift [hunk 1]
```diff
@@ -269,6 +256,25 @@ public class Cryptography {
     return CryptographicKey(key: pKey, keyId: id)
   }
   
+  /// Deletes the key with the specified ID from the secure-enclave and keychain
+  @discardableResult
+  public class func delete(id: String) -> Error? {
```
Comment (iccub) [inline Client/DeviceCheck/Cryptography.swift:261]: Does it need to be public?

Comment (Brandon-T) [reply Client/DeviceCheck/Cryptography.swift:261]: Yeah because if it needs to be used outside of BraveRewards, it should be public otherwise it can't access it.

**Review by kylehickinson — APPROVED** [review]
