### PR TITLE
Fix #6724: Make WebView Delegations to be AsyncAwait compatible.

### LINKED ISSUE #6724: Block Scripts under  Brave Shields is not working
### Description: 

**Block Scripts** shields is not working. Both changing the shields from Shields screen or under shields defaults in settings doesnt work and javascript is not blocked on website.

There are also reports of this behaviour from users https://www.reddit.com/r/brave_browser/comments/106xpxi/block_scripts_not_working_anymore_ios/

### Steps to Reproduce 
  1. Load a website that can trigger a javascript action or inject a script
  2. Test the script is performing the desired action
  3. Change the Block Scripts value on/off
  4. Test and validate if script is working or blocked

### Actual result: 

Javascript blocking is not working

### Expected result:

When Block Scripts is enabled the javascript actions should be blocked

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
N/A

### Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes

### PR DESCRIPTION
**Pull request by Brandon-T**
## Summary of Changes
- Fixed cookie retrieval to be async-await.
- Make TabManager's WebView Delegations to be AsyncAwait compatible.

This pull request fixes #6724

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by cuba — APPROVED** [review]

File: Client/Frontend/Browser/TabManagerNavDelegate.swift [hunk 1]
```diff
@@ -78,47 +78,56 @@ class TabManagerNavDelegate: NSObject, WKNavigationDelegate {
...
-          pref = preference
-        })
+      // Needed to resolve ambiguous delegate signatures: https://github.com/apple/swift/issues/45652#issuecomment-1149235081
+      typealias WKNavigationActionSignature = (WKNavigationDelegate) -> ((WKWebView, WKNavigationAction, WKWebpagePreferences, @escaping (WKNavigationActionPolicy, WKWebpagePreferences) -> Void) -> Void)?
+      
+      // Needed to detect if async implementations exist as we cannot detect them directly
+      if delegate.responds(to: #selector(WKNavigationDelegate.webView(_:decidePolicyFor:preferences:decisionHandler:) as WKNavigationActionSignature)) {
+        // Do NOT change to `delegate.webView?(....)` the optional operator makes async-await calls crash the compiler atm!
+        // It must be force-unwrapped at the time of writing `January 10th, 2023`.
+        let (policy, preferences) = await delegate.webView!(webView, decidePolicyFor: navigationAction, preferences: preferences)
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/TabManagerNavDelegate.swift:94]: nit: Maybe a comment why force unwrap is necessary.

File: Client/Frontend/Browser/TabManagerNavDelegate.swift [hunk 2]
```diff
@@ -78,47 +78,56 @@ class TabManagerNavDelegate: NSObject, WKNavigationDelegate {
...
-
-          pref = preference
-        })
+      // Needed to resolve ambiguous delegate signatures: https://github.com/apple/swift/issues/45652#issuecomment-1149235081
+      typealias WKNavigationActionSignature = (WKNavigationDelegate) -> ((WKWebView, WKNavigationAction, WKWebpagePreferences, @escaping (WKNavigationActionPolicy, WKWebpagePreferences) -> Void) -> Void)?
+      
+      // Needed to detect if async implementations exist as we cannot detect them directly
+      if delegate.responds(to: #selector(WKNavigationDelegate.webView(_:decidePolicyFor:preferences:decisionHandler:) as WKNavigationActionSignature)) {
+        // Do NOT change to `delegate.webView?(....)` the optional operator makes async-await calls crash the compiler atm!
+        // It must be force-unwrapped at the time of writing `January 10th, 2023`.
```
Comment (soner-yuksel) [inline Client/Frontend/Browser/TabManagerNavDelegate.swift:94]: Lol I think I commented at the time you added extra comment here :D

**Review by soner-yuksel — APPROVED** [review]
Thanks @Brandon-T, Did a manual Test and it seems like Navigation Delegates / Shields are working

File: Client/Frontend/Browser/TabManagerNavDelegate.swift [hunk 3]
```diff
@@ -78,47 +78,56 @@ class TabManagerNavDelegate: NSObject, WKNavigationDelegate {
...
     }
 
     if res == .allow {
-      let tab = tabManager?[webView]
-      tab?.mimeType = navigationResponse.response.mimeType
+      // TabManager.subscript.getter requires MAIN-THREAD!
+      await Task { @MainActor in
+        let tab = tabManager?[webView]
+        tab?.mimeType = navigationResponse.response.mimeType
+      }.value
```
Comment (kylehickinson) [inline Client/Frontend/Browser/TabManagerNavDelegate.swift]: `@MainActor` can be added to the function definition instead of doing this.

Also for future usage: When you don't have any async code executing and you want it on main you can do `await MainActor.run { ... }` instead of `await Task { @MainActor in ... }`

Comment (kylehickinson) [reply Client/Frontend/Browser/TabManagerNavDelegate.swift]: Also if adding `@MainActor` here you may want to also add it to BVC's async delegate methods too if that was the original place it was always run

**Review by kylehickinson — APPROVED** [review]
Thanks for leaving comments on other callback methods :)

**Review by nuo-xu — APPROVED** [review]
