### PR TITLE
Fixed #518, caused by non thread safe favourite order

### LINKED ISSUE #518: Reorder favourites causes duplicates
### Description: 
Reorder favourites causes duplicates 

### Steps to Reproduce 
  1. Long press on favourite to edit mode
  2. Move one of them to a different position
  3. Favourite gets duplicated and doesn't come out of edit mode
  4. Tap on favourite loads the page but new tab still has them in edit mode
  5. Tap on edit button again and cancel brings them out of edit mode

**Actual result:** 
https://drive.google.com/open?id=1LFT5tgqpL5KJ6G4_vtaNL7YB1ETngJPJ

**Expected result:**
Should not duplicate and should come out of edit mode when tapped elsewhere

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.30.3)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by danishjafri88**
**Why**
Initial sync order was created in parallel, causing same order for more than one bookmark. This bug was further visible when user reorders the bookmarks and new orders are to be generated.

**Fix applied**

Background context performblockAndWait and all nested contexts changed to the original background context

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

File: Data/models/DataController.swift [hunk 1]
```diff
@@ -98,3 +98,16 @@ public class DataController: NSObject {
     }
 }
 
+extension NSManagedObjectContext {
+    public func saveContext () {
```
Comment (jhreis) [inline Data/models/DataController.swift]: We should probably only have one save context mechanism. Is there an issue with the other one?

File: Data/models/Bookmark.swift [hunk 2]
```diff
@@ -243,13 +243,25 @@ public final class Bookmark: NSManagedObject, WebsitePresentable, Syncable, CRUD
             format: "%K == %@ AND %K == NO", parentFolderKP, parent ?? nilArgumentForPredicate, isFavoriteKP)
     }
     
+    public class func add(defaults: [(url: URL, title: String)]) {
```
Comment (jhreis) [inline Data/models/Bookmark.swift]: This doesn't need to be specific to `defaults`, so just make it a general function `add(bookmarkData)` or something. But regardless, probably not needed for this PR.

**Review by jhreis — CHANGES_REQUESTED** [review]
There is kind of two things going on here. The actual fix, and then a `default` refactor. Would be best to separate these, and not combine them into a single PR, since they aren't really related.

File: Data/models/DataController.swift (hunk 1 above)
Comment (danishjafri88) [reply Data/models/DataController.swift]: Well yeah we can remove this. I use this to merge contexts. Removing

File: Data/models/Bookmark.swift (hunk 2 above)
Comment (danishjafri88) [reply Data/models/Bookmark.swift]: renamed

File: Data/models/DataController.swift (hunk 1 above)
Comment (jhreis) [reply Data/models/DataController.swift]: @danishjafri88 We shouldn't ever have to merge contexts.

Comment (danishjafri88) [reply Data/models/DataController.swift]: Not now perhaps, but there will be time where multiple contexts will come into play.

**Comment by danishjafri88** [comment]
The default refactor is part of the fix. The Bookmarks init (in loop) were done outside the context.

File: Data/models/Domain.swift [hunk 3]
```diff
@@ -44,9 +44,14 @@ public final class Domain: NSManagedObject, CRUD {
         //  A solution to consider is creating a new background context here, creating, saving, and then re-fetching
         //   that object in the requested context (regardless if it is `viewContext` or not)
         var newDomain: Domain!
-        context.performAndWait {
-            newDomain = Domain(entity: Domain.entity(context), insertInto: context)
-            newDomain.url = domainString
+        // Since most calls are from main queue performandWait has no adavantage.
+//        context.performAndWait {
```
Comment (jhreis) [inline Data/models/Domain.swift]: Removing this will introduce a race condition regression. Without blocking here, if two places attempt to pull "google.com" at the same time, it will create two domains, since the store does not have one yet. This function cannot return until the context creating the domain has been fully saved.

**Review by jhreis — CHANGES_REQUESTED** [review]

File: Data/models/Domain.swift (hunk 3 above)
Comment (danishjafri88) [reply Data/models/Domain.swift]: I will revert it, but we need an overhaul of the Database manager. `performblockandwait` is not of advantage if calling queue and context are both main. And if the calling queue is main and the context is background then it will block main thread. Also nothing is in place to make sure two background threads don't create two background context and add domains, which may cause redundancy.

File: Data/models/DataController.swift (hunk 1 above)
Comment (jhreis) [reply Data/models/DataController.swift]: We use lots of contexts, but generally they are just created for isolated instances, and main context auto-merges.

File: Data/models/Domain.swift (hunk 3 above)
Comment (jhreis) [reply Data/models/Domain.swift]: Yeah, we really should serialize this in a more robust way. Is this going to cause problems for the implementation though? Or was the issue just the default context abstraction?

File: Data/models/DataController.swift (hunk 1 above)
Comment (danishjafri88) [reply Data/models/DataController.swift]: Thats bad

File: Data/models/Domain.swift (hunk 3 above)
Comment (danishjafri88) [reply Data/models/Domain.swift]: The problem will be choppy main thread. But i guess we can ignore this till we refactor

**Comment by jhreis** [comment]
I don't think this solves the issue at hand. this only modifies the creation of the default sites, but does not modify their editing behaviors. The issue only happens after they have all been created.

File: Data/models/DataController.swift (hunk 1 above)
Comment (jhreis) [reply Data/models/DataController.swift]: This is actually how `NSPersistentContainer` are setup to work. Contexts are lightweight and should be destroyed often, unless used to contain persistent data (e.g. `viewContext`). This was introduced in iOS10, and we follow it pretty closely. 

We can discuss this more elsewhere though. There are some context improvements we need to make but using many background contexts and an auto-merged main thread context are not some of them.

File: Data/models/Domain.swift (hunk 3 above)
Comment (jhreis) [reply Data/models/Domain.swift]: Agreed, thankfully these are extremely lightweight operations. But something to improve.

**Review by jhreis — APPROVED** [review]
